iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_partitioned_orc.q, iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_partitioned_orc2.q, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_partitioned_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_partitioned_orc2.q.out, parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g, ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLUtils.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/set/AlterTableSetPartitionSpecAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/CreateMaterializedViewDesc.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/session/SessionStateUtil.java
Similar to create table store partition transform specification when creation materialized views in case of Iceberg storage format.
Support partitioned materialized views in Iceberg format.
Yes. Statements like
```
create materialized view mat1 partitioned on (b) stored by iceberg ...
create materialized view mat1 partitioned on spec (bucket(16, b), truncate(3, c)) stored by iceberg ...
```
are enabled.
```
mvn test -Dtest.output.overwrite -Dtest=TestIcebergCliDriver -Dqfile=mv_iceberg_partitioned_orc.q,mv_iceberg_partitioned_orc2.q -pl itests/qtest-iceberg -Piceberg -Pitests
```
=> HIVE-26925: MV with iceberg storage format fails when contains 'PARTITIONED ON' clause due to column number/types difference.

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/repl/ReplConst.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
To prevent the updation of "repl.target.last.id" whenever "repl.last.id" changed, i introduced new db param called "repl.resume.started". This new param will be set to "true" by orchestrator when RESUME is initiated.
This is needed for "RESUME" workflow after failover.
NO
* Tested in local environment
* Tested the change on on-prem cluster.
=> HIVE-26942 : Prevent updation of "repl.target.last.id" when RESUME action initiated

iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc2.q, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc2.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rewrite/AlterMaterializedViewRewriteAnalyzer.java
Use DDL_SHARED write type when Materialized view stored by iceberg is altered for enabling/disabling automatic query rewrite.
Later Iceberg commit request an exclusive write lock on the MV while updating data in metastore.
Yes, `alter materialized view <mv> [enable|disable] rewrite` not hangs and times out.
```
mvn test -Dtest.output.overwrite -Dtest=TestIcebergCliDriver -Dqfile=mv_iceberg_orc2.q -pl itests/qtest-iceberg -Piceberg -Pitests
```
=> HIVE-26967: Deadlock when enabling/disabling Materialized view stored by Iceberg

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/queries/positive/ctlt_iceberg.q, iceberg/iceberg-handler/src/test/results/positive/ctlt_iceberg.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/like/CreateTableLikeDesc.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/like/CreateTableLikeOperation.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
Two changes:
- Preserve the format version for the iceberg table
- Add auto translation logic for iceberg CTLT tables as well(if table created without external keyword, allow that by auto translating to external with purge true)
Better usability of iceberg tables with CTLT
Yes, format version preserved for Iceberg CTLT tables & auto translation to external with purge true like other commands for iceberg tables.
UT
=> HIVE-26950: Iceberg: (CTLT) Create external table like V2 table is not preserving table properties.

ql/src/java/org/apache/hadoop/hive/ql/exec/AbstractFileMergeOperator.java, ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java, ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java, ql/src/java/org/apache/hadoop/hive/ql/io/rcfile/truncate/ColumnTruncateMapper.java, ql/src/test/org/apache/hadoop/hive/ql/exec/TestFileSinkOperator.java
For dynamic partition insert into a non-acid table, if the source query contains union all, a sub-directory with prefix "HIVE_UNION_SUBDIR_" will be created under the temp dynamic partition directory. When the job is finished, 
it searches all the files under the temp dynamic partition directory for removing the double-committed output files,
so if there is another sub-directory under the dynamic partition directory, it'll fail to remove the duplicate files resulting from multiple task attempts.
The PR tries to solve if there is "HIVE_UNION_SUBDIR_" sub-directory, then searches the output files under ${tmp_dynamic_partition_directory}/HIVE_UNION_SUBDIR_x for deduplication.
No
=> HIVE-23891: UNION ALL and multiple task attempts can cause file duplication

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics2.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactorBase.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator2.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSMetricsListener.java
no_auto_compaction configuration should be allowed to overridden on a database level: adding no_auto_compaction=false should override the table level setting forcing the initiator to schedule compaction for all tables.
Currently a simple user can create a table with no_auto_compaction=true table property and create an aborted write transaction writing to this table. This way a malicious user can prevent cleaning up data for the aborted transaction, creating performance degradation.
No
Unit tests 
itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator2.java
itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics2.java
=> HIVE-26793: Create a new configuration to override 'no compaction' for tables

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/ExpressionTree.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java
Support partition filter for `char` and `varchar` types on HMS.
Some users may set the partition type as `char` or `varchar`, it can improve the performance if we support these "string like" types in partition filter.
No
Unit test.
=> HIVE-26661: Support partition filter for char and varchar types on Hive metastore

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/DbCPDataSourceProvider.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/HikariCPDataSourceProvider.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/datasource/TestDataSourceProviderFactory.java
Change the TxnHandler#connPoolMutex from a fixed size connection pool to NoPoolConnectionPool
- TxnHandler#MutexAPI is primarily designed to provide coarse-grained mutex support to maintenance tasks running inside the Metastore, now used by Compactor(Initiator/Cleaner), AcidHouseKeeperService, AcidTxnCleanerService, MaterializationsRebuildLockCleanerTask;
- A fixed size connection pool is a waste for other non leaders in the warehouse;
- Explore if we can remove the mutex used in TxnHandler#lockMaterializationRebuild and TxnHandler#compact, as user have a change to call them;
No
Tested manually by using existed TestTxnHandler#testMutexAPI against Postgres(docker container), MySQL(remote), Oracle(remote), Mssql(remote) with the proposed fix, worked fine.
=> HIVE-26794: Explore retiring TxnHandler#connPoolMutex idle connections

llap-server/src/main/resources/templates.py
JIRA link : https://issues.apache.org/jira/browse/HIVE-26939
This is because llap_server uses templates.py yarnfile to bringup the LLAP Application Master which has the placement_policy as "NODE". Hadoop has started using 2.12.7 jackson version which has issues in parsing NODE to either [node, rack]. Therefore it is not able to cast the placement policy correctly.
Resolution : We will have to send placement_policy as "node" from the templates.py of Hive Llap Server module.
=> HIVE-26939 : Changed placement policy from NODE to node

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/queries/positive/ctlt_iceberg.q, iceberg/iceberg-handler/src/test/results/positive/ctlt_iceberg.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/like/CreateTableLikeOperation.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
Preserve Partition Column in case of creating an iceberg table via CTLT
Partition Column isn't preserved if the source table is partitioned and target is Iceberg, when creating table via CTLT
Yes, partition columns preserved in CTLT when source table is partitioned
UT
=> HIVE-26974: Iceberg: CTL from iceberg table should copy partition fields correctly.

ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/AbstractGenericUDFArrayBase.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArraySlice.java, ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArraySlice.java, ql/src/test/queries/clientpositive/udf_array_slice.q, ql/src/test/results/clientpositive/llap/show_functions.q.out, ql/src/test/results/clientpositive/llap/udf_array_slice.q.out
Implement array_slice function in Hive
No
=> HIVE-26774 - Implement array_slice UDF to get the subset of elements from an array (subarray)

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java, ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
While performing a REPL LOAD, the source and target database names are made mandatory.
The standard REPL LOAD syntax is,
`repl load src into tgt with ( <config properties (if any) >);`
But in some cases, users are using the REPL LOAD command incorrectly. It does not really throw any meaningful error/warning message, and as expected it does not replicate the database as well.
For example,
`repl load target_db with ('hive.repl.rootdir'='hdfs://c3649-node2.coelab.cloudera.com:8020/user/hive/repl', 'hive.repl.include.external.tables'= 'true', 'hive.repl.replica.external.table.base.dir'='hdfs://c3649node2.coelab.cloudera.com:8020/warehouse/tablespace/external/hive/target_db.db')
`
The above command does not follow the REPL LOAD syntax. This does not produce any error message, nor it replicates …
=> HIVE-26931: REPL LOAD command does not throw any error for incorrect syntax

ql/src/java/org/apache/hadoop/hive/ql/exec/ExprNodeGenericFuncEvaluator.java, ql/src/java/org/apache/hadoop/hive/ql/exec/MapredContext.java
Post https://issues.apache.org/jira/browse/HIVE-24645, query compilation time increased for lot of queries. This is due to the fact that "MapredContext.createDummy" gets called from ExprNodeGenericFuncEvaluator.initialize() early in the compilation cycle. The fix for HIVE-24645 was supposed to be mainly for fetch.task.conversion, but got impacted for other cases.
Intent of this ticket is to go through that fix only on need basis. i.e for the cases where UDF configure needs to be called. For queries that do not have UDF, it will not go through this path and will reduce compilation times.
No
=> HIVE-27010: Reduce compilation time

ql/src/java/org/apache/hadoop/hive/ql/io/SingleFileSystem.java, ql/src/main/resources/META-INF/services/org.apache.hadoop.fs.FileSystem
Adds sfs+ofs support to mirror sfs+o3fs. ofs is a newer protocol by Ozone that's meant to replace o3fs.
=> HIVE-26757: Add sfs+ofs support

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
Fix the behaviour of optimized bootstrap, wherein repl.failover.endpoint was not removed on replicated database on target, when replication is setup from target to source.
This would have made background threads skip the replicated database on target.
To enable background threads for replicated database on target when replication is setup from target to source.
No
=> HIVE-26963: Unset repl.faliover.endpoint during second cycle of optimized bootstrap.

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/StringUtils.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
https://issues.apache.org/jira/browse/HIVE-23935
Entire Trace -
```
0: jdbc:hive2://localhost:10000> !primarykeys Persons
Error: MetaException(message:java.lang.NullPointerException) (state=,code=0)
org.apache.hive.service.cli.HiveSQLException: MetaException(message:java.lang.NullPointerException)
at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:360)
at org.apache.hive.jdbc.Utils.verifySuccess(Utils.java:351)
at org.apache.hive.jdbc.HiveDatabaseMetaData.getPrimaryKeys(HiveDatabaseMetaData.java:573)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at …
```
=> HIVE-23935. Fetching primaryKey through beeline fails with NPE.

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/aggr/DateColumnStatsAggregator.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/aggr/DecimalColumnStatsAggregator.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/aggr/DoubleColumnStatsAggregator.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/aggr/LongColumnStatsAggregator.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/aggr/TimestampColumnStatsAggregator.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/merge/BinaryColumnStatsMerger.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/merge/BooleanColumnStatsMerger.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/merge/ColumnStatsMerger.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/merge/ColumnStatsMergerFactory.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/merge/DateColumnStatsMerger.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/merge/DecimalColumnStatsMerger.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/merge/DoubleColumnStatsMerger.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/merge/LongColumnStatsMerger.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/merge/StringColumnStatsMerger.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/columnstats/merge/TimestampColumnStatsMerger.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/columnstats/merge/BinaryColumnStatsMergerTest.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/columnstats/merge/BooleanColumnStatsMergerTest.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/columnstats/merge/ColumnStatsMergerTest.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/columnstats/merge/DateColumnStatsMergerTest.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/columnstats/merge/DecimalColumnStatsMergerTest.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/columnstats/merge/DoubleColumnStatsMergerTest.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/columnstats/merge/LongColumnStatsMergerTest.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/columnstats/merge/TimestampColumnStatsMergerTest.java
Improving the modularity of the *ColumnStatsMerger classes by introducing a common parent class and moving there all the shared code that is not depending on the data type.
Those classes host some complex merging logic that is copy-pasted into several classes, a problem that is bound to worsen as we add new (and more complex) statistics.
No.
Existing and introduced unit-tests relevant for the change: 
```mvn test -Dtest.groups=org.apache.hadoop.hive.metastore.annotation.MetastoreUnitTest -Dtest='*ColumnStats*Test.java' -pl standalone-metastore/metastore-server```
=> HIVE-27000: Improve the modularity of the *ColumnStatsMerger classes

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Allow creating table with only metadata location set.
Schema provided in the create command ain't used, everything depends on the metadata.json
Yes, Create command with metadata_location set doesn't require the schema
UT
=> HIVE-26929: Iceberg: Allow creating iceberg tables without column definition when 'metadata_location' tblproperties is set.

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java, ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestDagUtils.java, ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezOutputCommitter.java
This is backport of HIVE-24629.  
1. TezProcessor should invoke output committer's commitTask after each processor execution.
2. After successful vertex completion, the DAG should invoke the Tez API output committer's commitOutput.
For StorageHandler to be able to use customized OutputCommitter in Tez.
New config value, otherwise no.
unit tests, also local test with storagehandler.
=> HIVE-27016: Backport HIVE-24629 Invoke optional output committer in TezProcessor

ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/MaterializedViewRewritingRelVisitor.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/materialized_view_create_rewrite_10.q, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_10.q.out
When rebuilding a non-transactional MV in presence of delete operations fall back to full rebuild.
Exception was thrown.
Yes. Rebuild is successful.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_create_rewrite_10.q -pl itests/qtest -Pitests
```
=> HIVE-26864: Incremental rebuild of non-transaction materialized view fails

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/queries/positive/alter_multi_part_table_to_iceberg.q, iceberg/iceberg-handler/src/test/queries/positive/alter_part_table_to_iceberg.q, iceberg/iceberg-handler/src/test/queries/positive/alter_table_to_iceberg.q, iceberg/iceberg-handler/src/test/queries/positive/ctas_iceberg_partitioned_orc.q, iceberg/iceberg-handler/src/test/queries/positive/iceberg_v2_deletes.q, iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_partitioned_orc.q, iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_partitioned_orc2.q, iceberg/iceberg-handler/src/test/queries/positive/show_create_iceberg_table.q, iceberg/iceberg-handler/src/test/queries/positive/truncate_force_iceberg_table.q, iceberg/iceberg-handler/src/test/queries/positive/truncate_iceberg_table.q, iceberg/iceberg-handler/src/test/queries/positive/truncate_partitioned_iceberg_table.q, iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/alter_table_to_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_partitioned_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/iceberg_v2_deletes.q.out, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_partitioned_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_partitioned_orc2.q.out, iceberg/iceberg-handler/src/test/results/positive/show_create_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/truncate_force_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/truncate_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/truncate_partitioned_iceberg_table.q.out
Add current snapshot id in show create table output for iceberg tables.
Better Usability 
Yes, Adds current snapshot id in show create table output for iceberg tables.
UT
=> HIVE-27049: Iceberg: Provide current snapshot version in show-create-table.

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java, ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezOutputCommitter.java
In case of multi-insert and statistics auto-gathering, the leaf vertex may not include the filesinkoperator. This is to add datasink for vertex that has FileSinkOperator. It is done in HIVE-4.0 by HIVE-25276 for hive-iceberge. This is to add this condition into HIVE-3.2.0 as well.
To fix issues with multi-insert and auto-stats for StorageHandler to use customized OutputCommitter in Tez.
No
local test with storagehandler.
=> HIVE-27016 (addendum): Invoke optional output committer in TezProcessor for FileSink

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/YarnQueueHelper.java
This PR is raised to rework the code fixed as part of HIVE-26352.
We should remove finally block as it causing the filesystem close exception when using explicit queue name the tez.queue.access is used and statistics gathering is enabled 
No
=> HIVE-27029: hive query fails with Filesystem closed error, Rework done for HIVE-26352

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlInsertPart.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
In add partitions via direct sql, limiting the number of rows in a single insert query such that total parameters in a query do not exceed 2100 for SQL Server db.
Add partitions with SQL Server db  throws SQLServerException when the number of parameters in the direct sql insert query exceeds 2100.
Exception Stack:
`Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: The incoming request has too many parameters. The server supports a maximum of 2100 parameters. Reduce the number of parameters and resend the request.
at com.microsoft.sqlserver.jdbc.SQLServerException.makeFromDatabaseError(SQLServerException.java:258) ~[mssql-jdbc-6.2.1.jre8.jar:?]
at com.microsoft.sqlserver.jdbc.SQLServerStatement.getNextResult(SQLServerStatement.java:1535) ~[mssql-jdbc-6.2.1.jre8.jar:?]
at …
=> HIVE-27060: Exception in add partitions with SQL Server db when number of parameters in insert query exceed 2100

beeline/src/test/org/apache/hive/beeline/TestBeelineArgParsing.java, pom.xml, standalone-metastore/pom.xml
upgrading postgresql from 42.4.1 to 42.5.1
To fix cve CVE-2022-41946
No
I build hive locally on my machine then upgraded the occureneces of postgresql , rebuilt hive with new changes and have pasted the dependency tree in apache jira for the same confirming that all occurences of postgresql were upgraded.
=> HIVE-26914:Upgrade postgresql to 42.5.1 due to CVE-2022-41946

service/src/java/org/apache/hive/service/auth/AuthType.java, service/src/test/org/apache/hive/service/auth/TestAuthType.java
If hive.server2.authentication is just set to "LDAP,JWT", HS2 fails to start with the exception shown in the HIVE-27063
There is some validation code that check to ensure that certain auth mechanisms cannot co-exist with others. This validation code does not do anything with JWT authentication. Added code to account for JWT auth as well.
No
Manually
Unit Tests
=> HIVE-27063: Allow JWT auth to be set independent of other auth mechanisms

ql/src/java/org/apache/hadoop/hive/ql/optimizer/SamplePruner.java, ql/src/test/queries/clientpositive/global_limit.q
Filter Hidden files to avoid failures due to marker files preset in the table directory
To avoid failures during read with Limit clause, when hidden files like _SUCCESS are present
Yes, the query passes when we have hidden files in the table directory
UT
=> HIVE-27071: Select query with LIMIT clause can fail if there are marker files like _SUCCESS and _MANIFEST.

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
**What changes were proposed in this pull request?**
Set metastore.partition.management.task.frequency defaults to a higher value (6 hours) instead of 5 minutes.
**Why are the changes needed?**
Proposed to increase the default frequency as it scans all the tables and partitions under Databases and in PROD scenarios it is not feasible to complete this scan in minutes.
**Does this PR introduce any user-facing change?**
No
**How was this patch tested?**
Existing test cases should not be failing with the config value changes.
=> Hive 27011 - Default value of PartitionManagementTask frequency should be set to higher value

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionState.java, shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java, shims/0.23/src/main/test/org/apache/hadoop/hive/shims/TestHadoop23Shims.java
Copy the value of tez.queue.name to mapreduce.queue.name in case of distcp jobs started as part of the query.
Described on jira.
Yes, if the user was previously aware of the actual yarn queue into which the DistCp jobs went, this is a behaviour change, as from now they go to the queue set in "tez.queue.name"  if it's defined, but this is only activated if hive.mapred.job.follow.tez.queue is true.
Tested on cluster. MAPREDUCE jobs went to the same queue with the patch.
https://issues.apache.org/jira/secure/attachment/13055215/image%20%281%29.png
=> HIVE-27056: Ensure that MR distcp goes to the same Yarn queue as other parts of the query

iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_partitioned_orc.q, iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_partitioned_orc2.q, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_partitioned_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_partitioned_orc2.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/CreateMaterializedViewDesc.java
Set serde parameters when converting `CreateMaterializedViewDesc` to `Table`
Some serde parameters are affects the behavior of storage handler specified at create materialized view statements.
No. But the file format specified in cmv statements are show by `describe formatted` output.
```
mvn test -Dtest.output.overwrite -Dtest=TestIcebergCliDriver -Dqfile=mv_iceberg_partitioned_orc.q,mv_iceberg_partitioned_orc2.q -pl itests/qtest-iceberg -Piceberg -Pitests
```
=> HIVE-27073: Apply SerDe properties when creating materialized view

pom.xml
Upgrade jettison version to 1.5.3
To fix CVE-2022-45693
No
Existing tests
=> HIVE-27027: Upgrade jettison to 1.5.3 to fix CVE-2022-45693

lib/README, pom.xml, ql/pom.xml
Upgrade JavaEWAH to 1.1.7
Fix CVEs
No
Hive was build locally , then javaewah was removed and was successfully built again.
=> HIVE-27012:Remove JavaEWAH dependency from HIVE to fix CVEs.

standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/ThriftHiveMetastore.cpp, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ThriftHiveMetastore_drop_dataconnector_args.php, standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ThriftHiveMetastore.py, standalone-metastore/metastore-common/src/gen/thrift/gen-rb/thrift_hive_metastore.rb, standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
Fix thrift compilation warnings due to missing argument indexes in drop_dataconnector()
Lots of compilation warnings show up when compiling hive_metastore.thrift.
```
[WARNING:/home/quanlong/workspace/Impala/toolchain/cdp_components-36109364/hive-3.1.3000.7.2.17.0-75/standalone-metastore/src/main/thrift/hive_metastore.thrift:2397] No field key specified for ifNotExists, resulting protocol may have conflicts or not be backwards compatible!
[WARNING:/home/quanlong/workspace/Impala/toolchain/cdp_components-36109364/hive-3.1.3000.7.2.17.0-75/standalone-metastore/src/main/thrift/hive_metastore.thrift:2397] No field key specified for checkReferences, resulting protocol may have conflicts or not be backwards compatible!
```
No
Compiled locally and verified the warnings disappeared.
=> HIVE-27103: Fix thrift compilation warnings on drop_dataconnector()

spark-client/src/test/java/org/apache/hive/spark/client/rpc/TestRpc.java
This PR disables TestRpc because it is flaky. I ran the flaky test runner and it failed.
ref: http://ci.hive.apache.org/job/hive-flaky-check/613/console
branch-3 stability
NO
Confirmed that the test skips locally.
=> [HIVE-27062] Disable flaky test TestRpc

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
This patch fixes the improper metrics (TABLE count) incase of RESUME/RESET by taking intersection of tables in ```table_diff_complete``` and actual ```tables on source```. 
```REPL DUMP``` during RESET checks all the tables listed in ```table_diff_complete``` and persists
the table count in replication metrics. This is incorrect for RESET,
because table_diff_complete has those tables which needs to be dropped too.
NO
* Updated unit test for this scenario.
* Tested it in local setup.
=> HIVE-27107 : Fix improper metrics count for RESUME/RESET workflow

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionPoolManager.java
JIRA: HIVE-27106. Improve TezSessionPoolManager#getSession Log.
When reading the code, I found that the log placeholder of Tez Session Pool Manager#getSession is missing one, this jira will fix this problem.
=> HIVE-27106. Improve TezSessionPoolManager#getSession Log.

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalog.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/Catalogs.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestCatalogs.java
Provide a config to set catalog level properties globally for all catalogs.
User Ease
Yes, Iceberg Catalog level properties can be set at global level
UT
=> HIVE-27013: Iceberg: Provide an option to enable iceberg manifest caching for all catalogs.

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/SecurityUtils.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetastoreHttpHeaders.java
This PR targets to improve the usability of the http hive metastore client, by adding support for custom headers and also, supporting default trust store for https.
Add a new hive conf to allow users to inject custom headers
Do not force the headers to be http when the useSSL is turned off, so that if the users are able to use https if they want, w/o a custom truststore.
Improved user experience for http mode in HMS client.
No
ut for the http headers
=> HIVE-27129: Add enhanced support for Hive Metastore Client http support

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, data/conf/iceberg/llap/hive-site.xml, data/conf/iceberg/tez/hive-site.xml, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
That test flag is not in use. And in the long term, using those flags leads to hard to test code so it is logical to remove them. And as it is unused, it is the best time to remove that. 
Remove HIVE_IN_TEST_ICEBERG flag.
It is unused.
No
By running the tests in the pipeline.
=> HIVE-27137: Remove HIVE_IN_TEST_ICEBERG flag

itests/qtest/pom.xml, pom.xml, standalone-metastore/metastore-server/pom.xml, standalone-metastore/pom.xml
Upgrade MySQL Connector Java to 8.0.31 due to security CVE
To Fix CVEs.
No
I built hive locally and checked the depedency tree , thereafter the required changes were made and hive was again rebuilt successfully.Upon again checking the dependency tree the versions were shown correctly.
=> HIVE-26999:Upgrade MySQL Connector Java due to security CVE

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
HIVE-27140 : Set HADOOP_PROXY_USER cause hiveMetaStoreClient close everytime
I this the issuse clearly described
https://issues.apache.org/jira/browse/HIVE-27140
I this the issuse clearly described
https://issues.apache.org/jira/browse/HIVE-27140
No
I this the issuse clearly described
https://issues.apache.org/jira/browse/HIVE-27140
=> HIVE-27140 : Set HADOOP_PROXY_USER cause hiveMetaStoreClient close everytime

ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java, shims/common/src/main/java/org/apache/hadoop/hive/shims/HadoopShims.java
Comparios of HDFS path key strength is not possible if paths belong to different filesystems
To allow such comparisons.
No
Manually
=> HIVE-22813: Hive query fails if table location is in remote EZ and it's readonly

ql/src/test/queries/clientpositive/mm_all.q, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/events/InsertEvent.java
JIRA : https://issues.apache.org/jira/browse/HIVE-27153
The mm_all.q test was failing because of the following error :
`java.lang.AssertionError: 
Client execution failed with error code = 1 running "
insert into table part_mm_n0 partition(key_mm=455) select key from intermediate_n0" fname=mm_all.q 
See ./ql/target/tmp/log/hive.log or ./itests/qtest/target/tmp/log/hive.log, or check ./ql/target/surefire-reports or ./itests/qtest/target/surefire-reports/ for specific test cases logs.
at org.junit.Assert.fail(Assert.java:88)
at org.apache.hadoop.hive.ql.QTestUtil.failed(QTestUtil.java:2232)
at org.apache.hadoop.hive.cli.control.CoreCliDriver.runTest(CoreCliDriver.java:180)
at org.apache.hadoop.hive.cli.control.CliAdapter.runTest(CliAdapter.java:104)
at …
=> HIVE-27153 : Revert "HIVE-20182: Backport HIVE-20067 to branch-3"

itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcGenericUDTFGetSplits.java
This PR disables flaky test TestJdbcGenericUDTFGetSplits on branch-3. The test was seen intermittently failing on unrelated PRs and also on the flaky test runner: http://ci.hive.apache.org/job/hive-flaky-check/614/
To stablize branch-3 and reopen it for commits.
No
Confirmed that test is being skipped locally.
=> HIVE-27148: Disable flaky test TestJdbcGenericUDTFGetSplits

itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/tools/schematool/TestSchemaToolCatalogOps.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/RetryingMetaStoreClient.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RetryingHMSHandler.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestRetriesInRetryingHMSHandler.java
1. `RetryingMetaStoreClient` retry for only `TTransportException`.
2. `RetryingHMSHandler` skip some exceptions which always turn to fail even with retry.
To avoid some unnecessary retry in client and server sides.
1. As a RPC client, `RetryingMetaStoreClient` should only retry for communication errors like transport and connection error.
2. When querying from DBS, `RetryingHMSHandler` do not need retry for some unrecoverable exceptions like `SQLIntegrityConstraintViolationException`.
No
Add unit tests.
=> HIVE-27097: Improve the retry strategy for MetaStore client and server

standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/Util.java, standalone-metastore/pom.xml, storage-api/pom.xml
The guava version is upgrade to 22.0 in standalone-metastore and storage-api module
In HIVE-26484, the guava version is upgraded from 19.0 -> 22.0 in parent pom.xml but not in standalone-metastore/pom.xml and storage-api/pom.xml. The guava version in those 2 module is still 19.0. To be in-sync, hence making this change
No
The build is passing on my local machine
=> HIVE-27167: Upgrade guava version in standalone-metastore and storage-api module

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java, ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionTask.java
This PR backports HIVE-20953 which is needed to fix testBootstrapReplLoadRetryAfterFailureForPartitions
Test fix
No
CI Job
=> HIVE-27154: Backport HIVE-20953 to branch-3

itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliConfigs.java
Disabled sysdb.q test. The test is failing because of diff in BASIC_COLUMN_STATS json string. 
Client Execution succeeded but contained differences (error code = 1) after executing sysdb.q
3803,3807c3803,3807
< COLUMN_STATS_ACCURATE org.apache.derby.impl.jdbc.EmbedClob@125b285b
< COLUMN_STATS_ACCURATE org.apache.derby.impl.jdbc.EmbedClob@471246f3
< COLUMN_STATS_ACCURATE org.apache.derby.impl.jdbc.EmbedClob@57c013
< COLUMN_STATS_ACCURATE org.apache.derby.impl.jdbc.EmbedClob@59f1d7ac
< COLUMN_STATS_ACCURATE org.apache.derby.impl.jdbc.EmbedClob@717777a0
—
> COLUMN_STATS_ACCURATE {"BASIC_STATS":"true","COLUMN_STATS":{"c_boolean":"true","c_float":"true","c_int":"true","key":"true","value":"true"}}
> COLUMN_STATS_ACCURATE {"BASIC_STATS":"true","COLUMN_STATS":{"c_boolean":"true","c_float":"true", …
=> HIVE-27174 : Disabled sysdb.q

pom.xml, service/pom.xml, service/src/java/org/apache/hive/service/server/HiveServer2.java
When the jetty-runner jar defeats the javax.servlet.jsp-api jar for loading JspFactory, a NPE will be here when opening the HS2's home page.
No
Apply and compile the changes, place the jetty-runner jar ahead of CLASSPATH, restart the affected HS2, the NPE is gone.
=> HIVE-27179: HS2 WebUI throws NPE when JspFactory loaded from jetty-runner

ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
During dynamic partitions load, if 'hive.stats.autogather' is true, then skipping invocation of alterPartitions in MoveTask because it is done in BasicStatsTask in order not to invoke it twice.
alterPartitions is invoked twice during dynamic partition load causing runtime delay
No
Hive pre-commit CI pipeline
=> HIVE-22383: Invoking alterPartitions once after as a result of MoveTask

ql/src/java/org/apache/hadoop/hive/ql/exec/DDLTask.java
HIVE-22453: Describe table unnecessarily fetches partitions
Author: (Kevin Cheung, reviewed by Sankar Hariappan)
Signed-off-by: Sankar Hariappan <sankarh@apache.org>
Closes (#2140)
The simple describe table command without EXTENDED and FORMATTED (i.e., DESCRIBE table_name) fetches all partitions when no partition is specified, although it does not display partition statistics in nature.
The command should not fetch partitions since it can take a long time for a large amount of partitions.
For instance, in our environment, the command takes around 8 seconds for a table with 8760 (24 * 365) partitions.
This Backport was already done in branch-3.1 using this [HIVE-24964](https://issues.apache.org/jira/browse/HIVE-24964) so we need to backport the same to branch-3.
No
=> HIVE-27211: Backport HIVE-22453 to branch-3: Describe table unnecessarily fetches partitions

ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
Remove duplicate debug log in Hive.isSubDIr
In class org.apache.hadoop.hive.ql.metadata.HIve, invoke method isSubDir will print twice
`LOG.debug("The source path is " + fullF1 + " and the destination path is " + fullF2);`
we should remove the duplicate debug log.
Below is an example in log file,
`23/03/27 05:11:08 DEBUG Hive: The source path is /projects/hive/table_test/.hive-staging_hive_2023-03-27_05-09-17_848_8941157515106120269-1/-ext-10000/dt=20230327/country=SG/part-00179-51723c84-5be6-428e-862e-c4716e9536cc.c000/ and the destination path is /projects/hive/table_test/dt=20230327/country=SG/part-00179-51723c84-5be6-428e-862e-c4716e9536cc.c000/`
`23/03/27 05:11:08 DEBUG Hive: The source path is /projects/hive/table_test/.hive-staging_hive_2023-03-27_05-09-17_848_8941157515106120269-1/- …
=> HIVE-27189. Remove duplicate debug log in Hive.isSubDIr

hcatalog/core/src/main/java/org/apache/hive/hcatalog/mapreduce/FileOutputCommitterContainer.java
Optimize HCatStorer move task by following:
1. combine dryRun and actual execute in one iteration
the old logic does first iteration of dryRun to make sure it is okay to move, then another iteration to execute the move.  This change do the equivalent of dryRun first to check if it is okay to move while collecting the move objects, then execute the move if all move objects are collected passing checks.
2. parallelize moveTask
parallelization use same hiveconf as hive.mv.files.thread
3. differentiate source filesystem and target filesystem.
As there are still users using HCatStorer (e.g. Pig --useHcatStorer ) and the moveTask is very slow.
No
tested mvn clean test -Dtest=TestHCatExternalDynamicPartitioned,TestHCatDynamicPartitioned,TestHCatPartitioned,TestHCatNonPartitioned
also tested with …
=> HIVE-27143: Optimize HCatStorer moveTask

ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsOperation.java
Add a check for poolId before adding it in.
To Avoid NPE in case of Show Compactions post upgrade
Show Compactions doesn't throw NPE for older entries post upgrade
=> HIVE-27223: Show Compactions failing with NPE.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/Catalogs.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/queries/positive/iceberg_rename.q, iceberg/iceberg-handler/src/test/results/positive/iceberg_rename.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractAlterTableOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/rename/AlterTableRenameOperation.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
Added support for Rename command for Iceberg tables.
To support rename queries for Iceberg tables
Yes, Rename queries can be used for iceberg tables.
UT
=> HIVE-27208: Iceberg: Add support for rename table.

ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java, ql/src/test/org/apache/hadoop/hive/ql/metadata/TestTempAcidTable.java
Added `SessionHiveMetaStoreClient.getTranslateTableDryrun()` that detects the temporary tables and process it.
Temporary tables are in-memory tables maintained per session at HS2. They not managed at HMS. API calls to HMS are intercepted and processed at `SessionHiveMetaStoreClient` itself for the temporary tables. But missed to intercept for `getTranslateTableDryrun()` API.
No
Tested the scenario manually and added unittests
=> HIVE-27164: Create temporary insert only/full acid table fails at metastore transformCreateTable

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
This PR removes the call Splitter.splitToList from the metastore HTTP client and replaces it with a simple split call.
Some open source distributions have a different guava version which do not have this Splitter API. In such distributions the standalone hive metastore client code fails.
No
Existing unit tests cover this change.
=> HIVE-27258: Remove usage of Splitter.splitToList in HiveMetaStoreClient HTTP client

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTConverter.java, ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/translator/TestASTConverter.java, ql/src/test/queries/clientpositive/empty_result_ctas.q, ql/src/test/results/clientpositive/llap/empty_result_ctas.q.out
When converting {{HiveValues([])}} which represents an operator never produces rows to AST handle array types.
AST representation of an array of int with NULL elements should be 
```
TOK_SELEXPR
TOK_FUNCTION
array
TOK_FUNCTION
TOK_INT
TOK_NULL
```
Support array types
Yes. In case of CTAS statements when the query in the statement does not produce any rows and the source table has an array type column where the element type is other than string the target table still inherit the source table schema.
```
vn test -Dtest.output.overwrite -Dtest=TestMiniLlapLocalCliDriver -Dqfile=empty_result_ctas.q -pl itests/qtest -Pitests
```
=> HIVE-27253: Support array type when query does not produce any rows

itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestActivePassiveHA.java
HIVE-23548
TestActivePassiveHA was disables and reason was -
testManualFailoverUnauthorized failing at assertTrue(sendDelete(url1, false).contains("Unauthorized"));
As not sending any Auth header should get HTTP 401 with empty response. Empty response was not handled in sendAuthMethod(...)
This has been fixed in this PR 
Enabling TestActivePassiveHA  in test suite
No
via test. Tested with flakey jenkins job as well
http://ci.hive.apache.org/job/hive-flaky-check/639/
=> HIVE-23548 : TestActivePassiveHA is unstable

ql/src/test/queries/clientnegative/authorization_disallow_transform.q
HIVE-23567
Enabling authorization_disallow_transform.q in test suite
NO
via test
=> HIVE-23567 : authorization_disallow_transform.q is unstable

pom.xml
This PR aims to upgrade `cyclonedx-maven-plugin` to 2.7.6.
2.7.6 will bring the latest bug fixes.
- https://github.com/CycloneDX/cyclonedx-maven-plugin/releases/tag/cyclonedx-maven-plugin-2.7.6
- https://github.com/CycloneDX/cyclonedx-maven-plugin/releases/tag/cyclonedx-maven-plugin-2.7.5
- https://github.com/CycloneDX/cyclonedx-maven-plugin/releases/tag/cyclonedx-maven-plugin-2.7.4
Historically, there were some issue reports on the previous versions with the latest Maven.
- https://github.com/apache/spark/pull/40065
- https://github.com/apache/arrow/issues/35086
As of today, 2.7.6 is verified in Apache ORC/Parquet/Avro/Arrow/Spark communities.
- [ORC-1407: Upgrade cyclonedx-maven-plugin to 2.7.6](https://github.com/apache/orc/pull/1463)
- [PARQUET-2275: Upgrade cyclonedx-maven-plugin to …
=> HIVE-27263: Upgrade `cyclonedx-maven-plugin` to 2.7.6

itests/src/test/resources/testconfiguration.properties, ql/src/java/org/apache/hadoop/hive/ql/optimizer/ReduceSinkMapJoinProc.java, ql/src/test/queries/clientpositive/bucketmapjoin_with_subquery.q, ql/src/test/results/clientpositive/tez/bucketmapjoin_with_subquery.q.out
The changes will fix the issue [HIVE-27069]. The issue is present while using Tez only.
For Bucket Map Join we should use **FIXED** Reducer Trait as it has to map buckets from small table to buckets of big table. Current [code](https://github.com/apache/hive/blob/master/ql/src/java/org/apache/hadoop/hive/ql/optimizer/ReduceSinkMapJoinProc.java#L282) also does the same for BucketMapJoin. When join is applied on tables it takes **SIMPLE_EDGE** as it has to do the table scan so here based on this condition Reducer Trait is set. But when query contains a subquery instead of a table then it takes a **CUSTOM_SIMPLE_EDGE** as it can be dynamically bucketed on the join column. Actually it takes **CUSTOM_SIMPLE_EDGE** when it uses Dynamically Partitioned HashJoin but here it uses Bucket Join only …
=> HIVE-27069: Incorrect results with bucket map join

iceberg/iceberg-handler/src/test/queries/negative/parquet_limit_negative.q, iceberg/iceberg-handler/src/test/queries/positive/parquet_limit.q, iceberg/iceberg-handler/src/test/results/negative/parquet_limit_negative.q.out, iceberg/iceberg-handler/src/test/results/positive/parquet_limit.q.out, itests/qtest-iceberg/src/test/java/org/apache/hadoop/hive/cli/TestIcebergCliDriver.java, itests/qtest-iceberg/src/test/java/org/apache/hadoop/hive/cli/TestIcebergNegativeCliDriver.java
ObjectCache set up for Iceber CLI drivers (both for positive and negative)
Qtests failed if they had a `limit` clause. 
Example: 
```sql
create table icebergtable (id int, name string) stored by iceberg stored as parquet;
insert into icebergtable values (1, 'Joe'), (2, 'Jack');
select * from icebergtable limit 1;
```
No
With QTests
=> HIVE-27272: Fix limit clause issue for iceberg qtests

ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-27282
=> HIVE-27282 : Backport of HIVE-21717 : Rename is failing for directory in move task

itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestOldSchema.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStore.java, standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/BenchmarkTool.java, standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSBenchmarks.java, standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSClient.java
We want to reuse the `dropPartitionsInternal()` method for `drop_partition_common` api to enjoy the high performance, to achieve this we will refactor the `RawStore#dropPartition` api.
1. support direct sql for drop single partition
2. reduce one query to the DB, that is MPartition query in `ObjectStore#dropPartition`
No
1. Pass all existing tests.
2. Add the benchmark test for `dropPartition`:
```bash
java -jar hmsbench-jar-with-dependencies.jar -H localhost --savedata /tmp/benchdata --sanitize -N 10 -N 100 -o bench_results.csv -C -d testbench --params=100 -E 'list.*' -E 'createTable' -E 'dropTable.*' -E 'get.*' -E 'add.*' -E 'renameTable.*' -E 'dropDatabase.*' -E 'openTxn.*' -E 'PartitionManagementTask'
```
**Before use direct sql:**
```bash
Operation                      Mean     Med …
```
=> HIVE-27150: Drop single partition can also support direct sql

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
In MetastoreServerUtils.checkUserHasHostProxyPrivileges(), the check is to see if hadoop.proxyuser* settings in core-site.xml allow this user to execute this. One of the arguments to this method is an IpAddress that it is being executed on, which is fetched from HMSHandler.getIpAddress(). However, when running schematool, this is never is set during initialization. In this case, because it is not HMS server, the SaslServer is not initialized. 
When the core-site.xml has CIDR configurations, SubnetInfo.inRange() check throws an exception when the ip we are checking on in EMPTY.
So in case of schematool, try to use the hostaddress before resorting to empty ip address.
HIVE-27289. To avoid exception during upgrades.
No
Manually.
=> HIVE-27289: Check for proxy hosts with subnet in IP results in exception

itests/util/src/main/java/org/apache/hadoop/hive/ql/externalDB/AbstractExternalDB.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/DatabaseRule.java
=> HIVE-27295: Improve docker logging in AbstractExternalDB

ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezUtils.java, ql/src/test/queries/clientpositive/lateral_view_unionall.q, ql/src/test/results/clientpositive/llap/lateral_view_unionall.q.out
`GenTezUtils.removeUnionOperators` tries to remove union operators from union branches of the plan. I assume it is done because each branch has its own Map vertex and the Union vertex takes the union of the result these.
Let's see the following query
```
SELECT NULL AS first_login_did
FROM tez_test_t5
LATERAL VIEW explode(split('0,6', ',')) gaps AS ads_h5_gap
UNION ALL
SELECT  null as first_login_did
FROM tez_test_t1
UNION ALL
SELECT did AS first_login_did
FROM tez_test_t2
;
```
The plan before `removeUnionOperators`
```
TS[0]-LVF[1]-SEL[2]        -LVJ[5]-SEL[6]-UNION[9]-SEL[12]-UNION[13]-FS[15]
-SEL[3]-UDTF[4]-LVJ[5]
TS[7]-SEL[8]                             -UNION[9]
TS[10]-SEL[11]                                            -UNION[13]
```
The branch having lateral view 
``` …
```
=> HIVE-26779: UNION ALL throws SemanticException when trying to remove partition predicates: fail to find child from parent

pom.xml, ql/pom.xml
Upgrade Commons-text to 1.10.0 because of [CVE-2022-42889](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-42889)
Apache Commons Text versions prior to 1.8 is vulnerable to [CVE-2022-42889](https://nvd.nist.gov/vuln/detail/CVE-2022-42889), which involves potential script execution when processing untrusted input using StringLookup. Direct and transitive references to Apache Commons Text prior to 1.10.0 should be upgraded to avoid the default interpolation behaviour.
NO
On Local Machine
=> HIVE-27287: Upgrade Commons-text to 1.10.0 to fix CVE

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/BenchmarkTool.java, standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSBenchmarks.java, standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSClient.java
A small improvement of `HMSHandler.dropPartitionsAndGetLocations` , retrieve only partNames rather than partName and location pairs if we do not need check location.
Performance improvement, especially when the table partition number is large.
No
1. pass all existing test
2. add a new benchmark test **dropTableMetadataWithPartitions**
- Before this patch
```bash
Operation                      Mean     Med      Min      Max      Err%
dropTableMetaOnlyWithPartitions.10 23.70    21.87    19.36    31.73    14.48
dropTableMetaOnlyWithPartitions.100 54.42    54.15    45.92    76.68    8.891
dropTableMetaOnlyWithPartitions.1000 462.5    456.1    321.0    654.3    15.96
```
- After this patch
```bash
Operation                      Mean     Med      Min      Max      Err% …
```
=> HIVE-27266: Retrieve only partNames if not need drop data in HMSHandler.dropPartitionsAndGetLocations

hbase-handler/pom.xml, pom.xml, serde/src/java/org/apache/hadoop/hive/serde2/avro/TypeInfoToSchema.java
JIRA Link: [https://issues.apache.org/jira/browse/HIVE-27247](https://github.com/apache/hive/pull/url)
These commits were already done in branch-3.1 using this [https://issues.apache.org/jira/browse/HIVE-24436](https://github.com/apache/hive/pull/url), [https://issues.apache.org/jira/browse/HIVE-24414](url) so we need to backport the same to branch-3.
=> HIVE-27247: Backport of HIVE-24436: Fix Avro NULL_DEFAULT_VALUE compatibility issue

jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
keyStore.load() is invoked with null password when the trustStorePassword is not passed in JDBC URL.
Client connection to HS2 fails with transportMode as http, ssl is enabled, sslTrustStore is specified without trustStorePassword in the JDBC URL. trustStorePassword is not a necessary parameter in connection URL. Connection can be established without it.
From the javadocs [Link](https://docs.oracle.com/javase/7/docs/api/java/security/KeyStore.html#load(java.io.InputStream,%20char%5B%5D)) A password may be given to unlock the keystore (e.g. the keystore resides on a hardware token device), or to check the integrity of the keystore data. If a password is not given for integrity checking, then integrity checking is not performed.
At present, org.apache.hive.jdbc.HiveConnection#getHttpClient() …
=> HIVE-27271: Client connection to HS2 fails when transportMode=http, ssl=true, sslTrustStore specified without trustStorePassword in the JDBC URL

common/pom.xml, pom.xml
Upgrade jettison version to 1.5.4
To fix CVE-2023-1436 
No
Existing tests
=> HIVE-27286: Upgrade jettison version to 1.5.4 to address CVE-2023-1436

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/SecurityUtils.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreTimeout.java, standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSClient.java
Currently `HiveMetaStoreClient` use `CLIENT_SOCKET_TIMEOUT` as both socket timeout and connection timeout, we want to introduce a new HiveMetaStoreClient config for connection timeout:
```java
CLIENT_CONNECTION_TIMEOUT("metastore.client.connection.timeout", "hive.metastore.client.connection.timeout", 10,
TimeUnit.SECONDS, "MetaStore Client connection timeout in seconds"),
```
1. achieve a more flexible config for client socket timeout and connection timeout.
2. we can use a smaller connection timeout to fail-fast reconnect to another HMS server.
Yes, user can set the client connection timeout by this conf.
Add a unit test.
=> HIVE-27172: Add the HMS client connection timeout config

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/exec/MapJoinOperator.java, ql/src/test/queries/clientpositive/antijoin2.q, ql/src/test/results/clientpositive/llap/antijoin2.q.out
Proceed MapJoin operation with empty storage if that storage is RHS table of AntiJoin.
Current MapJoinOperator does not join empty RowContainers unless it has any OuterJoin.
Therefore, MapJoinOperator always produces no rows for AntiJoin as it joins non-empty LHS RowContainer and empty RHS RowContainer.
No
I add a qfile test that does not use vectorized MapJoin operator.
I also ran all TPC-DS queries on 1TB dataset with hive.auto.convert.anti.join=true and checked that all queries returns the correct result.
=> HIVE-26659: Proceed MapJoin with empty storage if it performs AntiJoin

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregateIncrementalRewritingRuleBase.java, ql/src/test/queries/clientpositive/materialized_view_create_rewrite_6.q, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_6.q.out
When transforming the logical plan of a materialized view insert-overwrite rebuild to incremental rebuild wrap the case expression which aggregates the values coming from the actual state of the view and the delta into a cast.
```
HiveProject(a=[$5], _o__c1=[CAST(CASE(IS NULL($1), $6, +($6, $1))):DECIMAL(17, 2)], _o__c2=[CASE(IS NULL($2), $7, +($7, $2))], _o__c3=[CAST(/(CAST(CASE(IS NULL($1), $6, +($6, $1))):DECIMAL(17, 2), CASE(IS NULL($2), $7, +($7, $2)))):DECIMAL(11, 6)], _o__c4=[CASE(IS NULL($3), $8, +($8, $3))])
HiveFilter(condition=[OR(AND($4, OR(AND(IS NULL($3), =($8, 0)), AND(=(+($8, $3), 0), IS NOT NULL($3)))), AND(IS NULL($4), OR(AND(IS NULL($3), >($8, 0)), AND(>(+($8, $3), 0), IS NOT NULL($3)))), AND($4, OR(AND(IS NULL($3), >($8, 0)), AND(>(+($8, $3), 0), IS NOT NULL($3)))))]) …
```
=> HIVE-27305: AssertionError in Calcite during planning for incremental rebuild of materialized view with aggregate on decimal column

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/vector/TestHiveIcebergVectorization.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/vector/TestHiveVectorizedReader.java
=> HIVE-26913: Addendum

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/exec/DDLTask.java, ql/src/test/queries/clientpositive/describe_table.q, ql/src/test/results/clientpositive/describe_table.q.out
JIRA Link: [https://issues.apache.org/jira/browse/HIVE-27312](https://github.com/apache/hive/pull/url)
This commit was already done in branch-3.1 using this [https://issues.apache.org/jira/browse/HIVE-27312](https://github.com/apache/hive/pull/url)so we need to backport the same to branch-3.
=> HIVE-27312: Backport of HIVE-24965- Describe table partition stats fetch should be configurable

ql/src/test/queries/clientpositive/materialized_view_create_acid.q, ql/src/test/results/clientpositive/llap/materialized_view_create_acid.q.out
See jira
No
```
mvn test -Dtest.output.overwrite -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_create_acid.q -pl itests/qtest -Pitests
```
=> HIVE-27320: Mask total size in materialized_view_create_acid.q.out

iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc6.q, iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc7.q, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc7.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/NonNativeAcidMaterializedViewASTBuilder.java, ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
* Get the sort acid columns from StorageHandler in case of non native acid MVs when transforming the AST of the incremental mv rebuild.
* Update some comments related to the AST transformation
* Set `hive.txn.manager` in q tests.
Incremental rebuild of MV stored by Iceberg is failed if the MV has aggregate. 
No.
```
mvn test -Dtest.output.overwrite -Dtest=TestIcebergCliDriver -Dqfile=mv_iceberg_orc7.q,mv_iceberg_orc6.q -pl itests/qtest-iceberg -Pitests,iceberg -Drat.skip
```
=> HIVE-27187: Incremental rebuild of materialized view having aggregate and stored by iceberg - ADDENDUM

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
Allow using TPE for snapshot expiry
Perf benefits
Quicker response
Manually
=> HIVE-27325: Expiring old snapshots deletes files with DirectExecutorService causing runtime delays.

ql/src/java/org/apache/hadoop/hive/ql/Context.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnNoBuckets.java
When a tool runs without a session, create an empty id list.
To avoid a potential NPE and be consistent.
No
Unit test explicitly closing session before call
=> HIVE-27268: synthetize empty id lists if no session available

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/AbstractJDBCConnectorProvider.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/PostgreSQLConnectorProvider.java
Mapping int2, int4, float4, float8, character, bool, binary varying and varbinary remotedb datatypes to hive datatypes.
Select query on table in remote database returns NULL values with postgreSQL and Redshift data connectors. This is happening because few datatypes are not mapped from postgres/redshift to hive data types. Thus values for unmapped columns are shown as null.
No
Tested manually
=> HIVE-27316: Map int2,int4,float4,float8,character,bool,binary varying and varbinary remotedb datatypes to hive

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreTimeout.java
Compaction entries should be dequied in a FIFO ordering
Currently there is no ordering during dequeue, which means the order is DB dependent
No
Manually and through unit tests
=> HIVE-27330: Compaction entry dequeue order

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java, iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read_orc.q, iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read_orc.q.out
Disable Llap read of TS on Iceberg tables when virtual columns are projected in vectorized mode.
The Iceberg specific virtual column `ROW_POSITION` can not be populated. In non-llap mode the row position is provided by the Orc reader. However in case of llap mode the read is driven by `LlapRecordReader` which does not provide the row positions.
Yes. Fix data corruption. Deleted rows are not appear in the result of a query.
```
mvn test -Dtest.output.overwrite -Dtest=TestIcebergLlapLocalCliDriver -Dqfile=llap_iceberg_read_orc.q -pl itests/qtest-iceberg -Pitests,iceberg -Drat.skip
```
=> HIVE-27331: Iceberg: Rows are not deleted from table when execution mode is vectorized llap.

jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java, jdbc/src/java/org/apache/hive/jdbc/Utils.java, jdbc/src/java/org/apache/hive/jdbc/ZooKeeperHiveClientHelper.java
Added a new property `storePasswordPath` to JDBC URL that point to the local JCE keystore file storing the password aliases. When an existing password property is present in URL, ignores to fetch that particular alias from local jceks(i.e., giving preference to existing password property). And if password property is not present in URL, fetches the password from local jceks file specified in `storePasswordPath` property.  Hive JDBC can obtains the passwords with [Configuration.getPassword](https://hadoop.apache.org/docs/stable/api/org/apache/hadoop/conf/Configuration.html#getPassword-java.lang.String-) API to read the password from jceks file.
JDBC URL would look like - 
`beeline -u "jdbc:hive2://kvr-host:10001/default;retries=5;ssl=true;sslTrustStore=/tmp/truststore.jks;transportMode=http …
=> HIVE-27308: Avoid exposing client keystore and truststore passwords in the JDBC URL

ql/src/java/org/apache/hadoop/hive/ql/optimizer/ConvertJoinMapJoin.java, ql/src/test/queries/clientpositive/bucket_map_join_tez3.q, ql/src/test/results/clientpositive/llap/bucket_map_join_tez3.q.out
Gather correct indices of bucket expression from big table side ReduceSinkOperator's partition columns.
As HIVE-27267 reportes, BucketMapJoin returns wrong result.
Current BucketMapJoin conversion algorithm sets incorrect expression to partition column, and this leads to mismatch between bucket id of MapJoinOprator and that of rows from small table RS. As a consequence, BucketMapJoin returns a subset of correct result as it does not have complete small table for corresponding bucket.
No
I added a qfile test that compares BucketMapJoin and MapJoin.
=> HIVE-27267: choose correct partition columns from bigTableRS

standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreTimeout.java
Fix the flaky test:
TestHiveMetaStoreTimeout#testResetTimeout
This test was sensitive to network/DB speed, and slow CI builds were resulted in unexpected timeouts.
No
By running TestHiveMetaStoreTimeout#testResetTimeout manually
=> HIVE-27343: Fix flaky tests: TestHiveMetaStoreTimeout#testResetTimeout

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
Delete directly aborted transactions instead of select and loading ids into memory.
select needs to be eliminated and the delete should work with the where clause instead of the built in clause.
we can see no reason for loading the ids into memory and then generate a huge sql.
NO
CI run/UT tests
=> HIVE-27198: Delete aborted transactions directly instead of select and loading ids

pom.xml, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/DbCPDataSourceProvider.java, standalone-metastore/pom.xml
Upgrading commons-dbcp2 to 2.9.0
To be on the latest version of commons-dbcp2
No
Ran the Unit test of standalone-metastore/metastore-server on local machine
=> HIVE-27345: Upgrade commons-dbcp2 to 2.9.0

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
Fix typo.
https://issues.apache.org/jira/browse/HIVE-27363
Users will be unlikely to get confused.
No.
This change doesn't change any behaviors.
=> HIVE-27363: Typo in the description of hive.tez.bucket.pruning

ql/src/java/org/apache/hadoop/hive/ql/hooks/PostExecOrcFileDump.java
Sort directories the in `PostExecOrcFileDump`
Tests dumps orc files of a table may get flaky due to order of directories contain the orc files is not deterministic.
No.
```
mvn test -Dtest.output.overwrite -Dtest=TestMiniLlapLocalCliDriver -Dqfile=acid_bloom_filter_orc_file_dump.q,orc_file_dump.q -pl itests/qtest -Pitests
```
=> HIVE-27365: Fix test acid_bloom_filter_orc_file_dump

pom.xml, vector-code-gen/pom.xml
This is a backport of HIVE-25726: Upgrade velocity to 2.3 due to CVE-2020-13936 (Sourabh Goyal via Naveen Gangam) 
for JIRA: [https://issues.apache.org/jira/browse/HIVE-27334](url)
=> Backport of HIVE-25726: Upgrade velocity to 2.3 due to CVE-2020-13936 (Sourabh Goyal via Naveen Gangam)

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestWarehouseExternalDir.java
Fix TestWarehouseExternalDir
TestWarehouseExternalDir was flaky
NO
http://ci.hive.apache.org/job/hive-flaky-check/679/
http://ci.hive.apache.org/job/hive-flaky-check/680/
http://ci.hive.apache.org/job/hive-flaky-check/681/
=> HIVE-25266: Fix TestWarehouseExternalDir

ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
This PR will change an internal param name defined in SessionState.
The param causes WARN unless we disable `hive.conf.validation`.
```
pod/hive-hiveserver2-7fc4df88b6-dmn8v: 2023-03-01T13:50:38,959  WARN [main] conf.HiveConf: HiveConf of name hive.internal.ss.authz.settings.applied.marker does not exist 
```
That's because it is not listed in HiveConf even though it starts with `hive.`.
https://github.com/apache/hive/blob/rel/release-4.0.0-alpha-2/common/src/java/org/apache/hadoop/hive/conf/HiveConf.java#L6429-L6440
So, this PR will change the prefix from `hive.internal.` into `_hive.`. This manner is inherited from some other private params.
https://github.com/apache/hive/blob/rel/release-4.0.0-alpha-2/ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java#L130-L132
Other …
=> HIVE-27120: Warn when Authorizer V2 is configured

ql/src/test/queries/clientpositive/results_cache_transactional.q, ql/src/test/results/clientpositive/llap/results_cache_transactional.q.out
- HIVE-22816 allowed queries on views with transactional tables to be cached, but did not add any test cases.
A couple of additional test cases.
To ensure that this feature continues to work in the future.
Nope
Ran the added test.
=> HIVE-27358: Add test cases for HIVE-22816 (result caching with views)

iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/hadoop/HadoopInputFile.java
Pass String instead of Long for file length, due to [HADOOP-18724](https://issues.apache.org/jira/browse/HADOOP-18724)
Reasons mentioned over here:
https://github.com/apache/hive/pull/3862#discussion_r1205601741
No
=> HIVE-27392: Use String instead of Long for file length in HadoopInputFile.

ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java, ql/src/test/results/clientpositive/llap/annotate_stats_lateral_view_join.q.out
https://issues.apache.org/jira/browse/HIVE-24240
Fix incorrect computations to estimate UDTF size.
- Put 1 when numRows becomes zero because Hive assumes zero is a number for missing stats
- Use `StatsUtils .scaleColStatistics` to update col stats so as to update # of distinct values
- Wrap the final stats with `applyRuntimeStats`
This is a follow-up of https://github.com/apache/hive/pull/1531.
[This change has been approved once](https://github.com/apache/hive/pull/1984) but it was closed without being merged. So, I opened this PR again.
This PR would help Hive to compute more precise stats for UDTF.
Compatible from the point of view of users.
Revised one unit test.
=> HIVE-24240: Implement missing features in UDTFStatsRule

common/src/java/org/apache/hadoop/hive/ql/log/PerfLogger.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/miniHS2/TestHs2Metrics.java, itests/hive-unit/src/test/java/org/apache/hive/service/cli/operation/TestOperationLoggingAPIWithMr.java, itests/hive-unit/src/test/java/org/apache/hive/service/cli/operation/TestOperationLoggingAPIWithTez.java, itests/hive-unit/src/test/java/org/apache/hive/service/cli/session/TestQueryDisplay.java, ql/src/java/org/apache/hadoop/hive/ql/Driver.java, service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java
This is a backport of HIVE-19133 : HS2 WebUI phase-wise performance metrics not showing correctly (Bharathkrishna Guruvayoor Murali reviewed by Zoltan Haindrich, Vihang Karajgaonkar)
This PR is required for bug fix and improvement for branch-3.2.0 release.
JIRA: [https://issues.apache.org/jira/browse/HIVE-27378](url)
=> HIVE-27378: Backport of HIVE-19133: HS2 WebUI phase-wise performance metrics not showing correctly

ql/src/java/org/apache/hadoop/hive/ql/io/parquet/write/ParquetRecordWriterWrapper.java
Parquet file opened for reading stats is never closed
ParquetRecordWriterWrapper while closing the writer tries to collect the stats by creating a reader and opening the file. But it never closes the reader (hence not closing the file). This can leave the file open hence consuming memory and associated file handle resources.
https://github.com/apache/hive/blob/master/ql/src/java/org/apache/hadoop/hive/ql/io/parquet/write/ParquetRecordWriterWrapper.java#L143-L155
No
Existing tests
=> HIVE-27408: Parquet file opened for reading stats is never closed

pom.xml
[HIVE-27393](https://issues.apache.org/jira/browse/HIVE-27393)
Ant 1.10.12 has 2 CVE:
1. [CVE-2022-23437](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-23437)
2. [CVE-2020-14338](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-14338)
As mention here: https://mvnrepository.com/artifact/org.apache.ant/ant/1.10.12
No
By running build on local machine
=> HIVE-27393: Upgrade ant to 1.10.13 to fix CVE's

iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_partitioned_orc.q, iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_partitioned_orc2.q, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_partitioned_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_partitioned_orc2.q.out, iceberg/iceberg-handler/src/test/results/positive/show_iceberg_materialized_views.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/TextDescTableFormatter.java, ql/src/test/results/clientpositive/llap/masking_mv.q.out, ql/src/test/results/clientpositive/llap/masking_mv_by_text.q.out, ql/src/test/results/clientpositive/llap/materialized_view_cluster.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_acid.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_4.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_5.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_time_window.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_time_window_2.q.out, ql/src/test/results/clientpositive/llap/materialized_view_describe.q.out, ql/src/test/results/clientpositive/llap/materialized_view_distribute_sort.q.out, ql/src/test/results/clientpositive/llap/materialized_view_parquet.q.out, ql/src/test/results/clientpositive/llap/materialized_view_partition_cluster.q.out, ql/src/test/results/clientpositive/llap/materialized_view_partitioned.q.out, ql/src/test/results/clientpositive/llap/show_materialized_views.q.out
See [HIVE-27353](https://issues.apache.org/jira/browse/HIVE-27353)
See [HIVE-27353](https://issues.apache.org/jira/browse/HIVE-27353)
Yes. Output of describe formatted of materialized view is changed
from
```
Table name          	I/U/D since last rebuild	 
hive.default.cmv_basetable_2_n2	0/0/0               	 
hive.default.cmv_basetable_n5	0/0/0               	 
```
to
```
Table name          	Snapshot            	 
default.cmv_basetable_2_n2	:1:9223372036854775807::	 
default.cmv_basetable_n5	:1:9223372036854775807::
```
```
mvn test -Dtest.output.overwrite -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_create_acid.q,materialized_view_describe.q -pl itests/qtest -Pitests
```
=> HIVE-27353: Show saved snapshot of materialized view source tables

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/session/TestClearDanglingScratchDir.java, ql/src/java/org/apache/hadoop/hive/ql/session/ClearDanglingScratchDir.java
When `ClearDanglingScratchDir` service identifies the dangling sessions to clean HDFS, we will be cleaning files/dirs in `HiveConf.ConfVars.LOCALSCRATCHDIR` (local FS) as well.
When Hive session is killed, no chance for shutdown hook to clean-up tmp files. This causes accumulation of tmp files/dirs in local FS as below;
```
> ll /tmp/user/97c4ef50-5e80-480e-a6f0-4f779050852b*
drwx------ 2 user user 4096 Oct 29 10:09 97c4ef50-5e80-480e-a6f0-4f779050852b
-rw------- 1 user user    0 Oct 29 10:09 97c4ef50-5e80-480e-a6f0-4f779050852b10571819313894728966.pipeout
-rw------- 1 user user    0 Oct 29 10:09 97c4ef50-5e80-480e-a6f0-4f779050852b16013956055489853961.pipeout
-rw------- 1 user user    0 Oct 29 10:09 97c4ef50-5e80-480e-a6f0-4f779050852b4383913570068173450.pipeout
-rw------- 1 user user …
```
=> HIVE-27317: Temporary (local) session files cleanup improvements

itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/test/queries/clientnegative/drop_table_used_by_mv2.q, ql/src/test/results/clientnegative/drop_table_used_by_mv.q.out, ql/src/test/results/clientnegative/drop_table_used_by_mv2.q.out, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java, standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java, standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java
This is a backport of Merged PR 496945: Backport Hive-22566 : Drop table involved in materialized view leaves the table in inconsistent state (Pablo Junge, reviewed by Miklos Gergely). Cherry-picked the OSS commit with additional relevant code manually pasted from OSS.
This PR is required for bug fix and improvement for branch-3.2.0 release.
JIRA: [https://issues.apache.org/jira/browse/HIVE-27379](https://github.com/apache/hive/pull/url)
=> HIVE-27379:  Backport HIVE-22566 : Drop table involved in materialized view leaves the table in inconsistent state 

standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
This is a backport of HIVE-23046: Separate housekeeping thread from initiator flag.
This PR is required for bug fix and improvement for branch-3.2.0 release.
JIRA: [https://issues.apache.org/jira/browse/HIVE-27387](https://github.com/apache/hive/pull/url)
=> HIVE-27387: Backport of HIVE-23046: Separate housekeeping thread from initiator flag

pom.xml, standalone-metastore/pom.xml
1. Upgrade commons-cli to 1.5.0 to fix CVE-2020-15250
2. Upgrade commons-compress to 1.23.0
3. Upgrade commons-lang3 to 3.12.0
4. Upgrade commons-io to 2.12.0
[HIVE-27394](https://issues.apache.org/jira/browse/HIVE-27394)
To fix CVE and use the latest versions
No
By running build on local machine
=> HIVE-27394: Upgrade commons dependency to fix CVE

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/session/TestClearDanglingScratchDir.java, ql/src/java/org/apache/hadoop/hive/ql/session/ClearDanglingScratchDir.java
=> Revert "HIVE-27317: Temporary (local) session files cleanup improvements"

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/LlapDecider.java, ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezUtils.java, ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezWork.java, ql/src/java/org/apache/hadoop/hive/ql/plan/ReduceWork.java, ql/src/java/org/apache/hadoop/hive/ql/plan/TezEdgeProperty.java
Let Hive respect `tez.shuffle-vertex-manager.min-src-fraction` and `tez.shuffle-vertex-manager.max-src-fraction` when auto reducer parallelism is enabled. Currently, we don't have any methods to configure the parameters.
https://issues.apache.org/jira/browse/HIVE-24485
We sometimes want to tune the parameters so that Tez can finalize the number of reducers with a more accurate estimation. For example, in extreme cases where the previous stage is very skewed, we may want to configure both params at `1.0`.
The behavior will change if a user configures `tez.shuffle-vertex-manager.{min,max}-src-fraction`.
```
zookage@client-node-0:~$ beeline -e '
> SET hive.tez.auto.reducer.parallelism=true;
> SET hive.tez.min.partition.factor=1.0; -- enforce auto-parallelism
> SET …
```
=> HIVE-24485: Make the slow-start behavior tunable

ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java, ql/src/test/org/apache/hadoop/hive/ql/optimizer/TestSharedWorkOptimizer.java
SharedWorkOptimizer now assigns the same MapJoin cache key to MapJoinOperators if they have the same broadcast inputs.
If n-way join is enabled, MapJoinOperator can have 2 or more broadcast inputs. However, current SharedWorkOptimizer compares the first broadcast input only.
No
We tested this patch by running TPC-DS query 23 on 1TB orc dataset.
=> HIVE-27375: fix map join cache reuse

ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
Addendum for add retry backoff mechanism for abort cleanup
To resolve a possible deadlock contention. The deadlock was seen while executing TestCompactionMetrics#testCleanerFailuresCountedCorrectly multiple times.
````
ERROR [Cleaner-executor-thread-5] txn.CompactionTxnHandler: Unable to delete abort retry entries from COMPACTION_QUEUE due to A lock could not be obtained due to a deadlock, cycle of locks and waiters is:
Lock : ROW, COMPACTION_QUEUE, (1,21)
Waiting XID : {5453, U} , APP, DELETE FROM "COMPACTION_QUEUE" WHERE "CQ_DATABASE" = ?  AND "CQ_TABLE" = ? AND ("CQ_PARTITION" = ? OR "CQ_PARTITION" IS NULL) AND "CQ_TYPE" = 'c'
Granted XID : {5449, X} 
Lock : ROW, COMPACTION_QUEUE, (1,22)
Waiting XID : {5449, U} , APP, DELETE FROM "COMPACTION_QUEUE" WHERE "CQ_DATABASE" = ?  AND …
```
=> HIVE-27332: Addendum: Add retry backoff mechanism for abort cleanup

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
Avoid closing FIleSystem during column statistics stage. FileSystem instance is cached across the service, If we close one and some other thread tries to use that cached FS, it will fail with FS Closed Errors.
Second,
Closing & Recreating a new FS every time is costly, as the FS needs to be initialised every time & hence it shouldn't be closed mid way.
Avoid FS Close Errors
Queries doesn't fail with FS close error when using column stats source as Iceberg
No
=> HIVE-27447: Iceberg: Queries failing due to FileSystem close errors due to column statistics.

itests/hive-jmh/pom.xml
In **_itests/hive-jmh/pom.xml_**, the dependency of hive-exec is defined 2 times which is causing unnecessary maven warnings while building hive. Hence removing the duplicate dependency.
To prevent maven warnings while build 
No
Existing test should be enough
=> HIVE-27443: Remove duplicate dependency from pom to avoid maven warnings

pom.xml
1. Updated snappy-java version to 1.1.10.1 to fix CVE-2023-34455
JIRA: [https://issues.apache.org/jira/browse/HIVE-27450](url)
=> HIVE-27450: Fix for CVE-2023-34455 

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/RenderStrategy.java
Add date and time to the progress log when `hive.server2.in.place.progress` is disabled.
https://issues.apache.org/jira/browse/HIVE-24286
With `hive.server2.in.place.progress` disabled, Hive prints progress periodically. We want to add date and time to each line so that we can review what phase took time or where the job got stuck easily. As I mentioned in [HIVE-24286](https://issues.apache.org/jira/browse/HIVE-24286), Hive on MR or Hive on Spark add date and time.
```
INFO  : Map 1: -/-	Reducer 2: 0/1	
INFO  : Map 1: 0/1	Reducer 2: 0/1	
INFO  : Map 1: 0(+1)/1	Reducer 2: 0/1	
INFO  : Map 1: 1/1	Reducer 2: 0(+1)/1	
INFO  : Map 1: 1/1	Reducer 2: 1/1	
```
The log format can change if a user configures `hive.server2.in.place.progress=false`.
No
I tested the patch on my local machine.
```
INFO …
```
=> HIVE-24286: Render date and time with progress of Hive on Tez

ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFMapIndexStringScalar.java
Addendum to this PR: https://github.com/apache/hive/pull/3492
=> HIVE-27368: Vectorization: ArrayIndexOutOfBoundsException when map key vector has repeating values

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/queries/positive/ctlt_iceberg.q, iceberg/iceberg-handler/src/test/results/positive/ctlt_iceberg.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/convert/AlterTableConvertOperation.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Remove any transactional property from the iceberg table in case of CTLT, as they aren't relevant to it.
CTLT with iceberg table as target and source as managed table fails, due to additional checks that happen due to transactional properties set in the iceberg tables
Yes, CTLT from managed to iceberg table will be successful 
No
UT
=> HIVE-27441: Iceberg: CTLT with source table as Hive managed table fails with "The table must be stored using an ACID compliant format"

serde/src/java/org/apache/hadoop/hive/serde2/typeinfo/TypeInfoUtils.java, serde/src/test/org/apache/hadoop/hive/serde2/typeinfo/TestTypeInfoUtils.java
Now, TypeInfoUtils#parseType only support Decimal(precision,scale) instead of Decimal(precision, scale), for example, support decimal(10,2) instead of decimal(10, 2) with a blank before 2, however, users may create decimal in this format decimal(10, 2) and it will throw exception in 
```
Integer.parseInt(params[1]);
```
we need fix this issue.
Fix the Decimal(precision, scale) parsing error.
No
Added UT
=> HIVE-27439: Support Decimal(precision, scale) format

common/src/java/org/apache/hadoop/hive/conf/Constants.java, common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java, iceberg/iceberg-handler/src/test/queries/negative/show_partitions_negative_test.q, iceberg/iceberg-handler/src/test/queries/positive/show_partitions_test.q, iceberg/iceberg-handler/src/test/results/negative/show_partitions_negative_test.q.out, iceberg/iceberg-handler/src/test/results/positive/show_partitions_test.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/show/ShowPartitionsOperation.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
SHOW PARTITIONS support for iceberg tables.
For Hive partition table , the show partition command outputs the following:
```
+---------------------+
|      partition      |
+---------------------+
| d_part=10/e_part=5  |
| d_part=2/e_part=5   |
| d_part=3/e_part=4   |
+---------------------+
```
In this PR, we are implementing the same feature for hive iceberg tables:
```
+--------------------------------+
|      partition                 |
+--------------------------------+
| Spec-id=0/d_part=10/e_part=5   |
| Spec-id=0/d_part=2/e_part=5    |
| Spec-id=0/d_part=3/e_part=4    |
+--------------------------------+
```
With partition evolution, the output will be per spec id:
```
+--------------------------------+
|      partition                 |
+--------------------------------+
| …
```
=> HIVE-26832: Implement SHOW PARTITIONS for Iceberg Tables

iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/JavaUtils.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/AbstractHMSHandlerProxy.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandlerProxyFactory.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RetryingHMSHandler.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreTimeout.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestRetriesInRetryingHMSHandler.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/conf/TestMetastoreConf.java
1. make `HMSHandler` Proxy configurable by new metastore conf **"metastore.hmshandler.proxy"**
2. provide `AbstractHMSHandlerProxy` to extend customized handler
3. clean some hacked test codes in `HMSHandler`
1. make the handler of metastore flexible to config and extend
2. improve the code of `HMSHandler`
Yes, user can use new conf and api to extend their own handler.
Passing all existing tests.
=> HIVE-27284: Make HMSHandler proxy pluggable

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java, iceberg/iceberg-handler/src/test/queries/positive/iceberg_load_data.q, iceberg/iceberg-handler/src/test/results/positive/iceberg_load_data.q.out, ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/LoadSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/plan/LoadTableDesc.java
Add support to use Append API for partitioned tables for LOAD queries
Better usability.
Yes, Load data queries for iceberg table with PARTITION clause works
No
UT
=> HIVE-27245: Iceberg: Implement LOAD data for partitioned tables via Append API.

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/stats/FilterSelectivityEstimator.java, ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/stats/TestFilterSelectivityEstimator.java, ql/src/test/queries/clientpositive/stats_histogram_null.q, ql/src/test/results/clientpositive/llap/stats_histogram.q.out, ql/src/test/results/clientpositive/llap/stats_histogram_null.q.out
https://issues.apache.org/jira/browse/HIVE-27479
1. Before this PR, the code for computing BETWEEN selectivity estimation assumed that the BETWEEN call consisted of 3 operands: InputRef, LiteralLeft, and LiteralRight. However there is a forth boolean operand (in position 0) that was not accounted for. Due to this, the conditions for entering the computeBetweenPredicateSelectivity function were incorrectly failing. This PR fixes this issue and accounts for the forth boolean operand in the conditions to enter the computeBetweenPredicateSelectivity function.
2. For the BETWEEN case, NULL values are not being accounted for in the selectivity estimation, this PR fixes the selectivity estimation to account for NULLs.
3. The forth boolean operand, which was initially not accounted for, …
=> Hive-27479: Fix for the BETWEEN parameter issue and adjusted selectivity estimation in BETWEEN case for NULLs

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Disallow the creation of a Temporary Hive Iceberg tables
Atlas by default skips ingesting temporary tables created in Hive. But when searched for the newly created temporary Hive tables, it displays them in the search results.
No
Unit test
=> HIVE-27472: Iceberg: Disallow creation of temporary tables

ql/src/java/org/apache/hadoop/hive/ql/exec/Registry.java
Remove unused function resources method param for registerUDF method in Registry for cleanup/better readability.  
https://github.com/apache/hive/blob/25892ea409b3351acbd409d1f66f399a43614798/ql/src/java/org/apache/hadoop/hive/ql/exec/Registry.java#L154-L159
Not used by calling code here, likewise there are more places in the same file https://github.com/suprithIUB/hive/blob/14a1f70607db5ae6cf71b6d4343f308a5167581c/ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java#L496-L514
Cleanup
No
No
Existing tests
=> HIVE-27474 Remove unused function resources method param for registerUDF method in Registry

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStatistics.java, iceberg/iceberg-handler/src/test/results/positive/truncate_iceberg_table.q.out, ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsTask.java, ql/src/java/org/apache/hadoop/hive/ql/stats/ColStatsProcessor.java
Iceberg: Set COLUMN_STATS_ACCURATE after writing stats for Iceberg tables
Currently, we are writing the stats to puffin files but we are not setting the column stats accurate to the desired values.
The focus of the Jira would be to update the field whenever non-native tables update stats in their format.
No
No
Unit test
=> HIVE-27455: Iceberg: Set COLUMN_STATS_ACCURATE after writing stats for Iceberg tables

pom.xml
1. Changes : Upgrade h2database version to 2.2.220 for CVE-2022-45868 fix.
2.  The change is required because the web-based admin console in H2 Database Engine through 2.1.214 can be started via the CLI with the argument -webAdminPassword, which allows the user to specify the password in cleartext for the web admin console. Consequently, a local user (or an attacker that has obtained local access through some means) would be able to discover the password by listing processes and their arguments.
3. Dependency tree: 
[INFO] --- maven-dependency-plugin:3.1.1:tree (default-cli) @ hive-storage-api ---
[INFO]
[INFO] ------------------------< org.apache.hive:hive >------------------------
[INFO] Building Hive 4.0.0-beta-1-SNAPSHOT                               [2/49]
[INFO] …
=> HIVE-27501: CVE-2022-45868 fix

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/DataConnectorProviderFactory.java
`DataConnectorProviderFactory `uses HashMap to cache data connector instances, and there is no way to invalidate the cache unless you restart the MetaStore.  
What is more serious is that if you drop or alter the dataconnector, the cache will not change, and you maybe use a invalid dataconnector next time.
I think we can improve the dataconnector cache from the two aspects:
1. Use Caffeine with a maxmumsize e.g. 100  to cache data connector instead of HashMap, and set a expire time after the last accessing. And we also should close the underlying  datasource connection using Caffeine RemovalListener.
2. After executing Drop or Alter DDL on a dataConnector, we should update cache to clean the dataConnector to avoid using the invalid dataConnector next time.
No
Existing Qtest and Local Hive …
=> HIVE-27440: Improve data connector cache

pom.xml, service/pom.xml
Same as https://github.com/apache/hive/pull/3815 (for branch-3)
branch-2.3 uses Apache Directory Server in some tests. It currently uses version 1.5.6. This version has a transitive dependency to a SNAPSHOT, making it awkward to build and release. We can upgrade to 1.5.7 to remove the SNAPSHOT dependency.
SNAPSHOT dependencies make local builds awkward and release build policies typically don't allow them.
No, Apache Directory Server is only used for tests.
Yes, but it's test only
I built locally
=> HIVE-26880: [2.3] Upgrade Apache Directory Server to 1.5.7

binary-package-licenses/README, druid-handler/pom.xml, pom.xml, ql/pom.xml
Follow the [CALCITE-1474](https://issues.apache.org/jira/browse/CALCITE-1474) to switch from `org.pentaho:pentaho-aggdesigner` to `net.hydromatic:aggdesigner`. 
conjars repo is unavailable, we can not build success without local cache of `org.pentaho:pentaho-aggdesigner`.
The modules are from the same code base, and both are Apache licensed, and the latter is on maven central, so we can drop our dependency on Pentaho's maven repository.
No.
It's drop-in replacement.
Before this change, I can not build success due to can not download the jar. The patch fixes it.
=> HIVE-25173: [2.3] Migrate pentaho-aggdesigner-algorithm to aggdesigner-algorithm

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
- Copy Altered Table's description when Alter Table
- Altered Table's description is not changed.
- No
-No
- Tested with `testTableOps` method.
---
- recreated pull request https://github.com/apache/hive/pull/3633 (made some mistake with rebase)
- @ayushtkn Hi, Can you please take a look again?
=> HIVE-26575 - Copy Serde Description when Alter Table's Serde Description

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezConfigurationFactory.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java, ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezConfigurationFactory.java
This change is about putting tez DAG scoped properties into DAG config while constructing the DAG,
Because without this patch, hive on tez user is unable to make tez options applied on dag level by simply doung set tez.x.y=z in beeline.
No.
No.
Tested on cluster with TEZ-4344.
=> HIVE-27516: Add programatically added DAG scoped properties to DAG Configuration

ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedBatchUtil.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java, storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedRowBatch.java
A reset similar to what is done in VectorizedParquetRecordReader - https://github.com/apache/hive/blob/f78ca5df80c0bcb566f0915cda65112268df492c/ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java#L400
=> HIVE-27437: Vectorization: VectorizedOrcRecordReader does not reset VectorizedRowBatch after processing

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveSortJoinReduceRule.java, ql/src/test/results/clientpositive/llap/limit_join_transpose.q.out
Fix an incorrect push-down of LIMIT + OFFSET.
https://issues.apache.org/jira/browse/HIVE-27484
I know SemanticAnalyzer also doesn't handle LIMIT + OFFSET correctly when LIMIT + OFFSET is pushed down to parallel tasks. I will be working on it in [HIVE-27480](https://issues.apache.org/jira/browse/HIVE-27480) after HIVE-27484.
To prevent wrong results.
Bug fix.
No
Unit tests
=> HIVE-27484: Limit pushdown with offset generate wrong results

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/GenericUDFIcebergBucket.java, iceberg/iceberg-handler/src/test/queries/positive/dynamic_partition_writes.q, iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_writes.q.out
Bucket partition transformation date type support
UDFArgumentException:  ICEBERG_BUCKET() only takes STRING/CHAR/VARCHAR/BINARY/INT/LONG/DECIMAL/FLOAT/DOUBLE types as first argument, got DATE
No
No
qtest
=> HIVE-27522: Iceberg: Bucket partition transformation date type support

pom.xml
Upgrade log4j2 from 2.17.0 to 2.17.2
CVE-2021-44832 - Apache Log4j2 versions 2.0-beta7 through 2.17.0 (excluding security fix releases 2.3.2 and 2.12.4) are vulnerable to a remote code execution (RCE) attack when a configuration uses a JDBC Appender with a JNDI LDAP data source URI when an attacker has control of the target LDAP server. This issue is fixed by limiting JNDI data source names to the java protocol in Log4j2 versions 2.17.1, 2.12.4, and 2.3.2.
No.
Yes, it's a patched version upgrade.
Jenkins.
=> HIVE-27518: [2.3] Upgrade log4j2 from 2.17.0 to 2.17.2

itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestSSL.java
Disable the consistently failed test `TestSSL#testConnectionWrongCertCN`
It was disabled by HIVE-22621 in master, and by https://github.com/apache/hive/pull/3895 in branch-3.
The test failed consistently at 
```
assertTrue(e.toString().contains("java.security.cert.CertificateException"));
```
Suspect was caused by the JDK upgrading which changed the behavior. Anyway, just follow what master did.
No.
No.
Jekins
=> HIVE-26890: [2.3] Disable TestSSL#testConnectionWrongCertCN (Done as part of HIVE-22621 in master)

ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/delete_reducesinkdedup_off.q, ql/src/test/results/clientpositive/llap/acid_no_buckets.q.out, ql/src/test/results/clientpositive/llap/delete_reducesinkdedup_off.q.out, ql/src/test/results/clientpositive/llap/explainanalyze_acid_with_direct_insert.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_4.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_5.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_6.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_7.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_8.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_9.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_nulls.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_one_key_gby.q.out, ql/src/test/results/clientpositive/llap/runtime_stats_merge.q.out
Add sort keys to Reduce Sink created for bucketing on top of File Sink writes delete delta files.
See HIVE-27527
No.
No.
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=delete_reducesinkdedup_off.q -pl itests/qtest -Pitests
=> HIVE-27527: Order of records is not ensured in delete delta files when reduce deduplication is off

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/java/org/apache/hadoop/hive/ql/parse/RowResolver.java, ql/src/test/queries/clientnegative/join_using_clause_ambiguous_table.q, ql/src/test/queries/clientnegative/join_using_clause_wrong_column.q, ql/src/test/queries/clientpositive/join_using_clause.q, ql/src/test/results/clientnegative/join_using_clause_ambiguous_table.q.out, ql/src/test/results/clientnegative/join_using_clause_wrong_column.q.out, ql/src/test/results/clientpositive/llap/join_using_clause.q.out
When we have joins on three or more tables and use the using clause, we get NPE because for the second join, the left side is a join and not a table. Thus `leftTableAlias` is null. In this patch I try to assign leftTableAlias to one of the tableAliases present in left Row Resolver.
Here I assign the last table alias that contain the joining column to the left table alias.
We get a NPE otherwise
No
No
`mvn test -Pitests -Dtest=TestMiniLlapLocalCliDriver -Dtest.output.overwrite=true -Dqfile=join_using_clause.q`
=> HIVE-27495: NPE when trying to transform using clause to on clause

ql/src/java/org/apache/hadoop/hive/ql/HiveQueryLifeTimeHook.java
In the case of HIVE-27565, `tblPath` maybe null, we can skip this if `tblPath` is null.
https://github.com/apache/hive/blob/0447b88d8308be669eb9102637a65736ed2bfccf/ql/src/java/org/apache/hadoop/hive/ql/HiveQueryLifeTimeHook.java#L79
No
=> HIVE-27565: Fix NPE when dropping table in HiveQueryLifeTimeHook::checkAndRollbackCTAS

ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
The list of potential compaction items processed by Initiator is currently unlimited, and this may result in very long Initator loops. To avoid this, the potential compaction items returned by
org.apache.hadoop.hive.metastore.txn.CompactionTxnHandler#findPotentialCompactions(int, long, long)
should be limited.
The same limit needs to be added to cleaner:
org.apache.hadoop.hive.metastore.txn.CompactionTxnHandler#findReadyToClean
org.apache.hadoop.hive.metastore.txn.CompactionTxnHandler#findReadyToCleanAborts
Add limit to these processes
Too many items read in one single step can cause performance problems.
No
New tests added
=> HIVE-27444: Limit items processed by Initiator/Cleaner

ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFTypeOf.java, ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFTypeOf.java, ql/src/test/queries/clientpositive/udf_typeof.q, ql/src/test/results/clientpositive/llap/show_functions.q.out, ql/src/test/results/clientpositive/llap/udf_typeof.q.out
New UDF to get type of supplied argument
Helpful in tests and debugging
It adds a new UDF the users can use.
No
q test added
=> HIVE-27563: Add typeof UDF

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_virtualcol.q, iceberg/iceberg-handler/src/test/results/positive/query_iceberg_virtualcol.q.out
Add virtual column whenever the query is supposed to fetch them.
Fix fetching virtual columns for iceberg table, when no other column is being queried.
Queries only fetching virtual columns passes.
No
UT
=> HIVE-27562: Iceberg: Fetching virtual columns failing.

ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayUnion.java, ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayUnion.java, ql/src/test/queries/clientpositive/udf_array_union.q, ql/src/test/results/clientpositive/llap/show_functions.q.out, ql/src/test/results/clientpositive/llap/udf_array_union.q.out
Implement array_union function in Hive
No
No
=> HIVE-27523 - Implement array_union UDF in Hive

ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFMaskHash.java
Avoid too many logs from being written.
https://issues.apache.org/jira/browse/HIVE-27575
Prevent disk-full or overhead.
No
No
I checked the log is written only once.
```
hive-hiveserver2-859d7686f7-xwhrh: 2023-08-07T22:35:11,886  INFO [6a60330d-5988-48fb-9a94-23d9f6e5f334 HiveServer2-Handler-Pool: Thread-59] generic.MaskHashTransformer: Use SHA256 for masking
```
=> HIVE-27575: MASK_HASH UDF generate a log per row

common/pom.xml, druid-handler/pom.xml, druid-handler/src/java/org/apache/hadoop/hive/druid/DruidStorageHandlerUtils.java, hcatalog/core/pom.xml, hcatalog/server-extensions/pom.xml, hcatalog/webhcat/svr/pom.xml, itests/hive-blobstore/pom.xml, pom.xml, ql/pom.xml, spark-client/pom.xml, testutils/ptest2/pom.xml, testutils/ptest2/src/main/java/org/apache/hive/ptest/api/client/PTestClient.java, testutils/ptest2/src/main/java/org/apache/hive/ptest/execution/JIRAService.java
This is the first step to remove dependency on jackson-core-asl and jackson-mapper-asl.
To fix SPARK-44719: `NoClassDefFoundError` when using Hive UDF.
=> HIVE-27579: Backport HIVE-18433: Upgrade version of com.fasterxml.jackson

pom.xml, standalone-metastore/pom.xml
Thrift has a -strict flag that errors out for certain warnings. In particular, it errors out for implicit field keys, which can be a compatibility problem.
In the past, some changes to the Thrift definitions have introduced this warning, requiring subsequent changes (see HIVE-27103, HIVE-20365). Adding the
-strict flag causes these to be errors, so future
Thrift changes will not be able to introduce implicit field keys. The current Thrift files are clean, and -strict does not impact the Thrift code generated.
Testing:
- Ran "mvn clean install -Pthriftif -DskipTests -Dthrift.home=(thrift 0.16.0 home)"
This changes Thrift code generation to use the -strict flag. The -strict flag causes implicit field keys to fatal errors for code generation. Implicit field keys are a compatibility issue, …
=> HIVE-27396: Add the -strict flag for Thrift generation

pom.xml, testutils/ptest2/pom.xml
This is the second step to remove dependency on jackson-core-asl and jackson-mapper-asl.
To fix SPARK-44719: `NoClassDefFoundError` when using Hive UDF.
=> HIVE-27581: Upgrade jackson  from 2.9.4 to 2.12.0

ql/src/java/org/apache/hadoop/hive/ql/exec/FetchOperator.java
Do not cache HBase table input format in FetchOperator.
Refer: https://issues.apache.org/jira/browse/HIVE-27582
HBase input format is stateful. When there are concurrent queries running, same HBase input format is reused by multiple threads. When one thread closes HBase connection, the other thread that wants to fetch data from HBase can not submit task to HTable's ThreadPoolExecutor because the HBase connection is closed and ThreadPoolExecutor is shutdown. 
Caching of HBase input format is disabled in HiveInputFormat as part of  [HIVE-8808](https://issues.apache.org/jira/browse/HIVE-8808). Same fix needs to be applied in FetchOperator.
No
No
Reproduced the scenario by running the multiple concurrent queries that read data from HBase backed Hive table via HiveServer2. Verified that the …
=> HIVE-27582: Do not cache HBase table input format in FetchOperator

common/src/java/org/apache/hadoop/hive/common/type/Date.java, common/src/test/org/apache/hive/common/util/TestDateParser.java, ql/src/test/queries/clientpositive/check_constraint.q, ql/src/test/results/clientpositive/llap/check_constraint.q.out
1. Change `DateParser` to allow partial parsing of the input string and late resolution.
2. Remove special handling of 'T' and space ' ' in date parser
1. Return valid dates (not nulls) from timestamp strings with delimiters other than space and 'T' (e.g., `2023-08-03_16:02:00`)
2. Improve backwards compatibility by allowing partial parsing supported before HIVE-20007
3. Handle trailing invalid chars in a uniform way. Now `2023-08-03TGARBAGE` and `2023-08-03_GARBAGE` both return `2023-08-03`
Various SQL functions and operations on dates will now return a valid date instead of `null`. A list of affected functions and concrete examples are present in HIVE-27586.
New + existing tests
```
mvn test -Dtest=TestDateParser
```
=> HIVE-27586: Parse dates from strings ignoring trailing (potentialy) invalid chars

accumulo-handler/pom.xml, cli/pom.xml, common/pom.xml, druid-handler/pom.xml, hbase-handler/pom.xml, hcatalog/pom.xml, iceberg/pom.xml, itests/hive-jmh/pom.xml, itests/hive-minikdc/pom.xml, itests/hive-unit/pom.xml, jdbc/pom.xml, kafka-handler/pom.xml, llap-common/pom.xml, llap-server/pom.xml, llap-tez/pom.xml, pom.xml, ql/pom.xml, shims/0.23/pom.xml, shims/common/pom.xml, standalone-metastore/metastore-common/pom.xml, standalone-metastore/metastore-server/pom.xml
This change removes Mockito dependency from the root pom.xml to be able to upgrade mockito on a module bases and it enables removing PowerMock. 
Upstream conversation in the ticket: https://issues.apache.org/jira/browse/HIVE-27592
Remove Mockito and PowerMock from root pom.xml and define those dependencies in the projects that are using them.
To be able to remove PowerMock module-by-module.
No
No
By running precommit tests.
=> HIVE-27592: Remove mockito from root pom.xml

ql/src/java/org/apache/hadoop/hive/ql/exec/OrcFileMergeOperator.java
In OrcFileMergeOperator it was creating a orc reader for every file to obtain ObjectInspector, however as it is already guaranteed that files are compatible, so we only need to create orc reader once to get the ObjectInspector. creating orc reader is expensive as it has file system calls and extract tail metainfo etc.
minor improvement. 
No
No
tested local environment and user dev environment
=> HIVE-27600: Reduce filesystem calls in OrcFileMergeOperator

pom.xml
JIRA link - https://issues.apache.org/jira/browse/HIVE-27622
=> HIVE-27622: Backport of HIVE-26078: Upgrade gson to 2.8.9 (Ashish Sharma, reviewed by Adesh Rao)

ql/src/java/org/apache/hadoop/hive/ql/optimizer/ppr/PartExprEvalUtils.java
JIRA link - https://issues.apache.org/jira/browse/HIVE-27608
=> HIVE-27608 : Backport of HIVE-22106: Remove cross-query synchronization for the partition-eval

pom.xml
JIRA link - https://issues.apache.org/jira/browse/HIVE-27620
=> HIVE-27620 : Backport of HIVE-25945: Upgrade H2 database version to 2.1.210

pom.xml
JIRA link - https://issues.apache.org/jira/browse/HIVE-27621
=> HIVE-27621: Backport of HIVE-25697: Upgrade commons-compress to 1.21

ql/src/java/org/apache/hadoop/hive/ql/plan/ExprNodeDescUtils.java, ql/src/test/queries/clientpositive/partition_varchar1.q, ql/src/test/results/clientpositive/partition_varchar1.q.out
Backport of HIVE-21296: Dropping varchar partition throw exception
Jira link - https://issues.apache.org/jira/browse/HIVE-27572
=> HIVE-27572: Backport of HIVE-21296 to branch-3

itests/src/test/resources/testconfiguration.properties, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/test/queries/clientpositive/insert_overwrite.q, ql/src/test/results/clientpositive/llap/insert_overwrite.q.out
Backport of HIVE-18702: INSERT OVERWRITE TABLE doesn't clean the table directory before overwriting
Jira link - https://issues.apache.org/jira/browse/HIVE-27571
=> HIVE-27571: Backport of HIVE-18702 to branch-3

ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
Backport of HIVE-21815: Stats in ORC file are parsed twice to branch-3
Jira link - https://issues.apache.org/jira/browse/HIVE-27570
=> HIVE-27570: Backport of HIVE-21815 to branch-3

ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezWork.java, ql/src/test/queries/clientpositive/smb_join_after_union.q, ql/src/test/results/clientpositive/llap/smb_join_after_union.q.out
When setting the output name of ReduceSinkOperator, check whether the output ReduceWork is contained in any MergeJoinWork's merged work list.
If so, set the output name to the name of the main work of that MergeJoinWork.
In short, ReduceSinkOperator may point a merged BaseWork of MergeJoinWork instead of its main BaseWork.
When this happens, ReduceSinkOperator does not send intermediate data to next Vertex in runtime.
For more details, let's assume the following partial OperatorGraph.
...
TS1--UNION1-RS1-GBY-DUMMYSTORE-MERGEJOIN
TS2-/
...
TezCompiler creates 5 BaseWorks for the above operators:
- MapWork1(TS1-RS1)
- MapWork2(TS2-(cloned)RS1)
- ReduceWork1(GBY-DUMMYSTORE)
- ReduceWork2(MERGEJOIN)
- MergeJoinWork1(ReduceWork1, ReduceWork2).
The output name of RS1 should be the name of …
=> HIVE-27303: Set correct output name to ReduceSink when there is a SMB join after Union

iceberg/pom.xml, pom.xml
Upgrade kryo serialization lib to latest version. 
Consumes some latest improvements and bug fixes
https://github.com/EsotericSoftware/kryo/compare/kryo-parent-5.2.0...kryo-parent-5.5.0.
No
Yes. Attached file
Existing tests
=> HIVE-27585 Upgrade kryo serialization lib to latest version

shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
My suggestion is that we should not judge hdfs by scheme "hdfs", instead, we can judege `hdfs` by the class or className.
Since we can use `fs.hdfs.impl=alluxio.hadoop.ShimFileSystem` to another hadoop filesystem implementation.
=> HIVE-27631: Fix CCE when set fs.hdfs.impl other than DistributedFileSystem

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, data/conf/hive-site-old.xml, data/conf/hive-site.xml, data/conf/iceberg/llap/hive-site.xml, data/conf/iceberg/tez/hive-site.xml, data/conf/llap/hive-site.xml, data/conf/rlist/hive-site.xml, data/conf/tez/hive-site.xml, itests/hive-blobstore/src/test/resources/hive-site.xml
In `data/conf` module,  `hive-site.xml` is used to qtest&test. It keeps many invalid properties, and if you run test in IDE, you will see lots lof `WARN`: 
```
2023-06-12T01:28:18,074  WARN [main] conf.HiveConf: HiveConf of name hive.mapjoin.max.gc.time.percentage does not exist
2023-06-12T01:28:18,074  WARN [main] conf.HiveConf: HiveConf of name hive.llap.io.cache.orc.size does not exist
2023-06-12T01:28:18,075  WARN [main] conf.HiveConf: HiveConf of name hive.dummyparam.test.server.specific.config.override does not exist
2023-06-12T01:28:18,075  WARN [main] conf.HiveConf: HiveConf of name hive.metastore.metadb.dir does not exist
2023-06-12T01:28:18,075  WARN [main] conf.HiveConf: HiveConf of name hive.llap.io.cache.orc.alloc.min does not exist
2023-06-12T01:28:18,075  WARN [main] …
```
=> HIVE-27431: Clean invalid properties in test moduel

itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java
I am working on research that investigates test smell refactoring in which we identify alternative implementations of test cases, study how commonly used these refactorings are, and assess how acceptable they are in practice.
The first smell is when inappropriate assertions are used, while there exist better alternatives. For example, in [TestJdbcDriver2.java](https://github.com/apache/hive/commit/04a9ddaa91c549a3c3041a45ab9871c4bc70f76d#diff-71a2f75f4a5dc07d285255a36e87deaab739ca7c486c2b1ddc3930f69f46783d), I refactored `assertFalse(queryId.equals(queryId1));` with `assertNotEquals(queryId, queryId1);`.
The second smell is when exception handling can alternatively be implemented using assertion rather than annotation. For example, in …
=> HIVE-27645: Refactor assertFalse(equals()) using assertNotEquals & @Test(excepted) using assertThrows

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestCreateUdfEntities.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHiveAuthorizerCheckInvocation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/function/AbstractFunctionAnalyzer.java, ql/src/test/results/clientnegative/create_function_nonexistent_class.q.out, ql/src/test/results/clientnegative/create_function_nonudf_class.q.out, ql/src/test/results/clientnegative/drop_database_cascade.q.out, ql/src/test/results/clientnegative/udf_local_resource.q.out, ql/src/test/results/clientnegative/udf_nonexistent_resource.q.out, ql/src/test/results/clientpositive/llap/authorization_create_func1.q.out, ql/src/test/results/clientpositive/llap/authorization_functions_in_views.q.out, ql/src/test/results/clientpositive/llap/check_constraint.q.out, ql/src/test/results/clientpositive/llap/create_func1.q.out, ql/src/test/results/clientpositive/llap/llap_udf.q.out, ql/src/test/results/clientpositive/udf_using.q.out
Removing database object from Output `HivePrivilegeObject` and adding to input `HivePrivilegeObject` in Create Function and Drop Function authorization. 
Create/Drop function should not require DROP/WRITE privileges to the database.
Yes, Create/Drop function only requires READ permission to the DB
No
Tested with existing qtests for create/drop function
=> HIVE-22961: Drop function in Hive should not send request for drop database to Ranger plugin

itests/hcatalog-unit/pom.xml, itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/TestDbNotificationCleanup.java, itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/TestDbNotificationListener.java, itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/TestTransactionalDbNotificationListener.java, itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/TestTransactionalDbNotificationListner.java
https://issues.apache.org/jira/browse/HIVE-23680
TestDbNotificationListener was flakey as well as broken .
As a part of fix, There are nowtotal 3 test classes based on broken tests in TestDbNotificationListener 
1. TestDbNotificationListener
Fix of existing tests which includes nontransactional events
2. TestDbNotificationCleanup
This class includes tests which asserts cleanup of events based on TTL configurations
3. TestTransactionalDbNotificationListner
This class included tests with transactional event. This needs extra HMS test setup and acid properties setting. 
http://34.66.156.144:8080/job/hive-precommit/job/master/35/testReport/
http://130.211.9.232/job/hive-flaky-check/24/
NO
No
http://ci.hive.apache.org/job/hive-flaky-check/722/ …
=> HIVE-23680 : TestDbNotificationListener is unstable

ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java, ql/src/test/org/apache/hadoop/hive/ql/parse/TestParseUtils.java
This PR would just format `ParseUtils.java`.
https://issues.apache.org/jira/browse/HIVE-22618
I recommend reviewers take a look at the diff of this PR via the following URL.
https://github.com/apache/hive/compare/master...okumin:HIVE-22618-checkstyle?w=1
Indentations of this file are totally broken and I felt it is hard to modify the file while working on another issue.
I'd say we have no strong reasons to merge this one. I just created it because I hope other PRs are unlikely to conflict with this change now since it is not often updated recently.
No
No
These are the original checkstyle report.
```
root@fcc249b8c79d:~/hive# mvn -pl ql checkstyle:check -Dcheckstyle.consoleOutput=true | grep 'parse/ParseUtils.java'
/root/hive/ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java:227:1 …
```
=> HIVE-22618: Fix checkstyle violations for ParseUtils

ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayRemove.java, ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayRemove.java, ql/src/test/queries/clientpositive/udf_array_remove.q, ql/src/test/results/clientpositive/llap/show_functions.q.out, ql/src/test/results/clientpositive/llap/udf_array_remove.q.out
Implement array_remove function in Hive
No
No
=> HIVE-27628 - implement array_remove UDF in Hive

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
org.apache.hadoop.hive.ql.txn.compactor.CompactorOnTezTest#getRelatedTezEvent fixed to be able to process multiple event files
org.apache.hadoop.hive.ql.txn.compactor.CompactorOnTezTest#getRelatedTezEvent fails to advance to the next event file if there are multiple files available (for example due to date roll)
No
No
Through unit tests
=> HIVE-27652: Fix flakyness caused by CompactorOnTezTest#getRelatedTezEvent

ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFCoalesce.java, ql/src/test/queries/clientpositive/vector_coalesce.q, ql/src/test/results/clientpositive/llap/vector_coalesce.q.out
We already have test cases showing coalesce works for decimal64. However, the annotation wasn't there in GenericUDFCoalesce which caused a class cast issue when the coalesce was in the filter and being used with an equals clause.
In description above
Test failure when coalesce and equals are in where clause
No
No
Unit test added that failed before the fix with a ClassCastException
=> HIVE-27632: Added annotation for decimal64 support for coalesce

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
[HIVE-27657](https://issues.apache.org/jira/browse/HIVE-27657)
Change the default value of hive.fetch.task.conversion.threshold from 1GB to 200MB
With the introduction of [fetch task caching](https://github.com/apache/hive/blob/d0a06239b09396d1b7a6414d85011f9a20f8486a/common/src/java/org/apache/hadoop/hive/conf/HiveConf.java#L3532-L3535), HS2 may quickly run out of memory if there are multiple parallel queries with fetch task.
No
No
=> HIVE-27657: Change hive.fetch.task.conversion.threshold default value

ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHive.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
This PR makes partition order configurable if the metastore does not return all partitions.
We want to improve performance of limit-only queries on many partitioned tables.
For example: `SELECT * FROM large_partition_table limit 10`.
But we want to get the latest partition data. After this PR, we can `set metastore.partition.order.expr="PARTITIONS"."CREATE_TIME"` to achieve it.
No.
No.
Unit test.
=> HIVE-27659: Make partition order configurable if the metastore does not return all partitions

ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/CreateTableEvent.java, ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/TestHiveMetaStoreAuthorizer.java, ql/src/test/queries/clientpositive/auth_create_ext_table_1.q, ql/src/test/results/clientpositive/llap/auth_create_ext_table_1.q.out
Exclude `DFS_URI` from output `HivePrivilegeObject` if the table is an External table.
To address security concerns where currently users had to be granted unnecessary write permissions on an external file location when the table is only used for reading the data.
Yes, External table creation will be successful but Update/ delete operation will fail without write permissions on table location.
No
mvn test -Dtest.output.overwrite=true -Dtest=TestMiniLlapLocalCliDriver -Dqfile=auth_create_ext_table_1.q
=> HIVE-27525:Ease the write permissions on external table during create table operation

ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java, ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/TestHiveMetaStoreAuthorizer.java
Retain all stack traces within the authorization exception.
To facilitate better troubleshooting of authorization failures via logging.
No
No
Add a new UT.
=> HIVE-27461: HiveMetaStoreAuthorizer lost the root cause of checkPrivileges

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestRemoteHiveMetaStoreKerberos.java, itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestSSLWithMiniKdc.java, service/src/java/org/apache/hive/service/cli/thrift/RetryingThriftCLIServiceClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Changed the default value for thrift message size to 2147483647 bytes instead of 1 GB and fixed config help message.
Also, Wrapped the config value to a max of INTEGER.MAX_VALUE.
Wide tables with huge partitions (5k+) can cross current thrift max message size of 1GB as the partition object contains column descriptors and other properties set by Impala.
Help message suggested the upper limit for max message size as 2 GB which is outside of INTEGER.MAX_VALUE range and hence caused overflow when converted to int and got updated to thrift default (100 MB)
No
No
There is no functionality change introduced, so existing test cases should not be failing with these config value changes
=> HIVE-27113: Increasing default for hive.thrift.client.max.message.size to 2GB

itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestIsAuthTypeEnabled.java, jdbc/src/java/org/apache/hive/jdbc/HttpBasicAuthInterceptor.java, jdbc/src/java/org/apache/hive/jdbc/HttpKerberosRequestInterceptor.java, jdbc/src/java/org/apache/hive/jdbc/HttpRequestInterceptorBase.java, jdbc/src/java/org/apache/hive/jdbc/HttpTokenAuthInterceptor.java, jdbc/src/java/org/apache/hive/jdbc/jwt/HttpJwtAuthRequestInterceptor.java, jdbc/src/java/org/apache/hive/jdbc/saml/HttpSamlAuthRequestInterceptor.java, service/src/java/org/apache/hive/service/auth/AuthType.java, service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java, service/src/test/org/apache/hive/service/auth/TestAuthType.java
Since the implementation of HIVE-27352, if a client tool communicating over http transport wants to use an authentication mode other than the first allowed authentication mode, it must include the name of the chosen auth mode in an http header named "auth". However, the same information can also be obtained from the content of the standard http Authorization header, so the auth header is not really needed. This PR removes the "auth" header and infers the authorization mode to be used by client from the value of the Authorization header. 
Old jdbc driver builds, other compatible client tools do not send an "auth" header when using http transport, but use the standard http Authorization header. If the same functionality can be implemented using the value of the Authorization header, then …
=> HIVE-27661: Auth mode inferred from the Authorization header

ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
Backports HIVE-26127 to branch-3. This is a reopen of https://github.com/apache/hive/pull/3561 which was reviewed previously but I missed merging it at that time.
Fixes a bug which affects Spark 3 users.
NO
No
This PR is a simple backport from master branch and relies on the existing tests including in the original PR.
=> HIVE-26127: Insert overwrite throws FileNotFound when destination partition is deleted

ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
- If a Table is created using CTAS with rows > INT_MAX then beeline eats up the thrown error
- As replication also uses the same infra it should also do the same instead of failing with NumberFormatException as CTAS creates the actual table underneath 
Analysis: 
- HMS is not throwing any error and due to a lack of numbering in the error log from the thrift actual root cause of the Error is not known.
- So, added code change will prevent it from breaking the replication
=> HIVE-27669: Hive Acid CTAS fails incremental if no of rows inserted is > INT_MAX

ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFOperator.java, ql/src/test/queries/clientpositive/vector_windowing_row_number.q, ql/src/test/results/clientpositive/vector_windowing_row_number.q.out
This is a backport of [HIVE-22903](https://issues.apache.org/jira/browse/HIVE-22903): Vectorized row_number() resets the row number after one batch in case of constant expression in partition clause
This is required for bug fix and improvements for [hive-3.2.0](https://issues.apache.org/jira/browse/HIVE-26751) release.
JIRA link: [HIVE-27666](https://issues.apache.org/jira/browse/HIVE-27666)
=> HIVE-27666: Backport of HIVE-22903 : Vectorized row_number() resets the row number after one batch in case of constant expression in partition clause

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Pass metadata location to authorizer if that is provided as part of create table
Better Authorizaton checks
Yes, metadata location will go through auth checks while creating table if they are specified.
No
UT
=> HIVE-27322: Iceberg: metadata location overrides can cause data breach.

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestRemoteHiveMetaStoreKerberos.java, itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestSSLWithMiniKdc.java, service/src/java/org/apache/hive/service/cli/thrift/RetryingThriftCLIServiceClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
=> Revert "HIVE-27113: Increasing default for hive.thrift.client.max.message.size to 2GB"

hbase-handler/src/java/org/apache/hadoop/hive/hbase/HBaseStorageHandler.java, hbase-handler/src/test/queries/positive/hbase_between_pushdown.q, hbase-handler/src/test/results/positive/hbase_between_pushdown.q.out
HIVE-27558: HBase table query does not push BETWEEN predicate to storage layer
In HBaseStorageHandler, converting 'BETWEEN' predicate back again to '<= AND >=' prediacte and pushing it down to the HBase. Also in HBase, Keys are sorted lexicographically so the byte representation of negative values comes after the positive values so not pushing down the predicate if any constant value is a negative number. If it is not a range predicate like equality condition then it can be pushed down even the constant value is a negative number.
As a part of optimization, '<= AND >=' predicate will be converted as 'BETWEEN' predicate but HBase don't support BETWEEN so this predicate is not pushing down which resulting into a performance issue. Now the 'BETWEEN' predicate is again converting back to '<= …
=> HIVE-27558: HBase table query does not push BETWEEN predicate to storage layer

ql/src/java/org/apache/hadoop/hive/ql/exec/FetchOperator.java, ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java, ql/src/java/org/apache/hadoop/hive/ql/io/HiveContextAwareRecordReader.java, ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRawRecordMerger.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcSplit.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java, ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java, ql/src/test/queries/clientpositive/acid_vectorization_original.q, ql/src/test/results/clientpositive/llap/acid_vectorization_original.q.out
JIRA link - https://issues.apache.org/jira/browse/HIVE-27644
This ticket backports [HIVE-17917](https://issues.apache.org/jira/browse/HIVE-17917), [HIVE-21457](https://issues.apache.org/jira/browse/HIVE-21457), [HIVE-22582](https://issues.apache.org/jira/browse/HIVE-22582)
The reason behind fixing the TestInputOutputFormat test is this :
This PR targets to skip flush length check for external tables. The reason that some of the queries on external tables took more time was because Hive used to check for flush length files which are only present for Acid tables. In the first call when it concludes that it is an external table, it skips checking for side files hence the total number of calls reduces from 3 to 1.
=> HIVE-27644 : Backport of HIVE-17917, HIVE-21457, HIVE-22582

packaging/src/docker/build.sh
Add iceberg profile in docker build from source
Iceberg works for released versions, but not when building images from source
No
No
Tested locally by building the image locally from source & creating an iceberg table.
=> HIVE-27696: Docker build from source should include iceberg profile.

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, common/src/test/org/apache/hive/common/util/MockFileSystem.java, itests/src/test/resources/testconfiguration.properties, ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java, ql/src/test/org/apache/hadoop/hive/ql/exec/TestMoveTask.java, ql/src/test/queries/clientpositive/flatten_union_subdir.q, ql/src/test/results/clientpositive/tez/flatten_union_subdir.q.out
Allow to flatten subdir in case of UNION
To avoid Subdir in case of UNION queries for compar
Yes, if the config is turned on.
No
UT
=> HIVE-21100: Allow flattening of table subdirectories resulted when using TEZ engine and UNION clause.

Jenkinsfile
Save some tests logs in case of failing tests.
Because currently the artifact is pretty useless, it doesn't contain more info than what's already visible in jenkins.
No, it's precommit related.
No.
Jenkins is supposed to pick up Jenkinsfile from the patch. Need to verify at:
http://ci.hive.apache.org/job/hive-precommit/job/PR-4732/1/
verified, first commit:
```
Obtained Jenkinsfile from 2d2ca54feb59480bbc960c5ffd45aa6134e76f2c
```
=> HIVE-27716: Precommit: Save log files for first 10 failures

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveTypeSystemImpl.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFSum.java, ql/src/test/queries/clientpositive/materialized_view_create_rewrite_11.q, ql/src/test/results/clientpositive/llap/decimal_precision.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_11.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_6.q.out, ql/src/test/results/clientpositive/llap/vector_decimal_precision.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/cbo_query13.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query13.q.out
Set nullability to of `sum` aggregate function return type based on the parameter type.
Materialized view rewrite algorithm compares all aggregate function return types in a candidate MV and the query plan about to replace. Nullability is also checked. Currently if `sum` aggregate function is explicitly defined in a query (or MV definition) the return type is nullable however if it is introduced by [HiveAggregateReduceFunctionsRule](https://github.com/apache/hive/blob/f5d4bf89fb37458a3818d5d5c612b29defb1daa5/ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveAggregateReduceFunctionsRule.java#L326C19-L354) the return type is always not null due to Hive customization of [HiveTypeSystemImpl.deriveSumType](https://github.com/apache/hive/blob/f5d4bf89fb37458a3818d5d5c612b29defb1d …
=> HIVE-27727: Materialized view query rewrite fails if query has decimal derived aggregate

itests/hive-jmh/pom.xml, itests/hive-jmh/src/main/java/org/apache/hive/benchmark/vectorization/mapjoin/load/AbstractHTLoadBench.java
This is the next step of removing PowerMock from Hive.
PowerMock removed, mockito-inline introduced with a mockito upgrade to 4.11
PowerMock seems to be a dead project.
Prerequisite for moving to Java 11
No
Yes
- Ran one of the performance tests that uses the modified class
- Precommit tests
=> HIVE-27736: Remove PowerMock from itests-jmh and upgrade mockito

llap-client/pom.xml, llap-client/src/test/org/apache/hadoop/hive/llap/registry/impl/TestLlapZookeeperRegistryImpl.java, llap-client/src/test/org/apache/hadoop/hive/registry/impl/TestZookeeperUtils.java
It is the next step of removing PowerMock from Hive. 
PowerMock removed, mockito-inline introduced with a mockito upgrade to 4.11
PowerMock seems to be a dead project.
Prerequisite for moving to Java 11
No
Yes
=> HIVE-27701: Remove PowerMock from llap-client

itests/src/test/resources/testconfiguration.properties, ql/src/java/org/apache/hadoop/hive/ql/optimizer/DynamicPartitionPruningOptimization.java, ql/src/test/queries/clientpositive/dynamic_semijoin_reduction_on_aggcol.q, ql/src/test/results/clientpositive/llap/dynamic_semijoin_reduction_on_aggcol.q.out
Backport of HIVE-21799: NullPointerException in DynamicPartitionPruningOptimization, when join key is on aggregation column
Jira link - https://issues.apache.org/jira/browse/HIVE-27573
=> HIVE-27573: Backport of HIVE-21799 to branch-3

jdbc-handler/pom.xml, jdbc-handler/src/test/java/org/apache/hive/storage/jdbc/TestJdbcInputFormat.java
(https://issues.apache.org/jira/browse/HIVE-27704)
To upgrade mockito
NO
YES
=> HIVE-27704 : Remove PowerMock from jdbc-handler and upgrade mockito to 4.11

parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g, parser/src/test/org/apache/hadoop/hive/ql/parse/TestParseDriver.java
When the query is parsed, we end up in the subQuerySource rule because atomSelectStatement, by definition, cannot contain SORT BY, ORDER BY, CLUSTER BY, DISTRIBUTE BY or LIMIT clauses. An exception is thrown because subQuerySource requires an identifier which is not present nor needed in this particular scenario.
Changing `atomSelectStatement` to `selectStatement` solves the issue because `selectStatement` supports SORT BY, ORDER BY, CLUSTER BY, DISTRIBUTE BY and LIMIT clauses.
Up until 3.1.2, it was possible to use SORT BY, ORDER BY, CLUSTER BY, DISTRIBUTE BY or LIMIT clauses in a subquery along with a set operator (ex: UNION). These clauses are [officially supported in subqueries](https://cwiki.apache.org/confluence/display/Hive/Supported+Features%3A++Apache+Hive+3.1). The language …
=> HIVE-27649: Support ORDER BY clause in subqueries with set operators

contrib/src/java/org/apache/hadoop/hive/contrib/serde2/RegexSerDe.java, hcatalog/core/src/main/java/org/apache/hive/hcatalog/data/JsonSerDe.java, kafka-handler/src/java/org/apache/hadoop/hive/kafka/KafkaSerDe.java, serde/src/java/org/apache/hadoop/hive/serde2/AbstractEncodingAwareSerDe.java, serde/src/java/org/apache/hadoop/hive/serde2/AbstractSerDe.java, serde/src/java/org/apache/hadoop/hive/serde2/RegexSerDe.java
Logger variable in AbstractSerDe class was non static. This needs to be a static final in order to prevent multiple copies of Logger variable for the same set of classes.
Multiple copies of Logger variable creation adds up time in the compilation of a query.
No
No
Tested in the local machine before and after the patch and verified by checking the time and also the flamegraph
=> HIVE-27687 Logger variable should be static final as its creation takes more time in query compilation

common/src/java/org/apache/hadoop/hive/common/FileUtils.java, common/src/test/org/apache/hadoop/hive/common/TestFileUtils.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionState.java, ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezSessionState.java
Resolving symlinks before considering local files to be transformed to yarn LocalResource.
Because localizing the same hive-exec jar more then once is a needless burden on HDFS and runtime.
No.
No.
very same as on https://github.com/apache/hive/pull/4741
cluster test worked as expected, unit tests worked as expected also
=> HIVE-27723: Prevent localizing the same original file more than once if symlinks are present

beeline/pom.xml, itests/hive-jmh/pom.xml, jdbc-handler/pom.xml, llap-client/pom.xml, pom.xml, ql/pom.xml, service/pom.xml
Remove powermock.version
For mockito-inline, create a version property and use it. 
Remove powermock.version
For mockito-inline, create a version property and use it. 
To get rid of all the remainings of PowerMock
No
No
=> HIVE-27774: Remove PowerMock - finishing touches

service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java, service/src/test/org/apache/hive/service/cli/thrift/ThriftHttpServletTest.java
[HIVE-27661](https://issues.apache.org/jira/browse/HIVE-27661) (#4666) refactored the authentication code a bit and also introduced a new bug: 
Before the modification, if the client was not authenticated and Kerberos authentication was enabled, a response header was included in the HTTP 401 response: `WWW-Authenticate: Negotiate`  
After the modification, this header is not included in the response, so [the reactive authentication flow implemented in the Knox gateway](https://github.com/apache/knox/blob/master/gateway-discovery-cm/src/main/java/org/apache/knox/gateway/topology/discovery/cm/auth/SpnegoAuthInterceptor.java#L105-L113) does not work anymore.
This change fixes an authentication problem that occurs when the hiveserver is behind a Knox gateway.
No.
No.
Tested with a new unit …
=> HIVE-27764: Add "WWW-Authenticate: Negotiate" header to the response when the client is unauthorized and Kerberos authentication is enabled

packaging/src/docker/conf/hive-site.xml
hive.metastore.warehouse.dir, this configuration item is configured incorrectly, causing the configuration item to not take effect.
bug image:
fix image：
I changed the `packaging/src/docker/conf/hive-site.xml` file.
I discovered this bug when I was using it. Since there is no default directory for non-root users in the container, error messages appear when creating databases and data tables without permission. I corrected hive.metastore.warehouse.dir configuration. This error has been resolved.
The correct related configuration items are in the picture below.
Now there will be no errors when creating databases and tables in docker containers, and the data and directories will appear in the specified directory.
No
UT
=> HIVE-27798: Corrected wrong hive-site.xml

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, common/src/java/org/apache/hadoop/hive/conf/HiveConfUtil.java, common/src/test/org/apache/hadoop/hive/conf/TestHiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/processors/SetProcessor.java, ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
Create a new locked list called **_hive.conf.locked.list_** which contains comma separated configuration that won't be changed during runtime. If someone try to change them at runtime then it will give **_WARN_** log on beeline itself.
In organisations, admin want to enforce some configs which user shouldn't be able to change at runtime and it shouldn't affect user's existing hive scripts. Therefore, this locked list will be useful as it will not allow user to change the value of particular configs and it will also not stop the execution of hive scripts.
This config can be documented.
On a cluster
=> HIVE-27169: New Locked List to prevent configuration change at runtime without throwing error

ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezSessionState.java
=> HIVE-27802: Simplify TestTezSessionState.testSymlinkedLocalFilesAreLocalizedOnce

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/BenchmarkTool.java, standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSBenchmarks.java
1. Create a new common function named `addPartitionsInternal`
2. Both `add_partitions` and `add_partition`  call this new common function.
1. Get the performance improvement in direct SQL for `add_partition`
3. Code cleaner, reduce the duplicate code.
No
No
1. pass all existing add partition related tests
2. add a benchmark test:
```shell
java -jar ./hmsbench-jar-with-dependencies.jar -H localhost --savedata /tmp/benchdata --sanitize -N 10 -N 100 -N 1000 -o bench_results_direct.csv -C -d testbench_http --params=100  -E 'drop.*' -E 'renameTable.*' -E 'getTableObjectsByName.*' -E 'listTables.*' -E 'listPartitions.*' -E 'getPartitions.*' -E 'getPartitionsByNames.*' -E 'getPartitionNames.*' -E 'listPartition' -E 'getPartition'  -E 'getNid' -E 'listDatabases' -E 'getTable' -E 'createTable' -E …
```
=> HIVE-27676: Reuse the add_partitions logic for add_partition in ObjetStore

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesGetExists.java
Changed the function when user search database and table name in some certain pattern.
To make sure that if * are used in searching for database and table name, there is no exception.
No.
Unit tests.
=> HIVE-27346: Getting exception for wildcard (*) search for database and table name

jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java
This PR updates `getUpdateCount()` in `HiveStatement`.
Support update `numModifiedRows` if `TGetOperationStatusResp` contains this value.
No.
No.
Manual test:
1. Upgrade Spark's hive-service-rpc to 4.0.0-beta-1.
2. Port HIVE-14388 to Spark.
3. Execute the code:
```scala
val conn = DriverManager.getConnection("jdbc:hive2://localhost:10000/")
val stmt = conn.createStatement()
stmt.execute("insert into t select * from range(100);")
println(stmt.getUpdateCount)
```
=> HIVE-27815: Support update numModifiedRows

pom.xml
Upgrade ivy to 2.5.2
Fix CVE-2022-46751
No
Yes, Dependency tree attached in the jira
Built locally, relying on pre-commit tests of the PR.
=> HIVE-27824:Upgrade Ivy to 2.5.2

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetastoreDirectSqlUtils.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestFunctions.java
Implement direct SQL for get_all_functions
We have a special Hive cluster which has many udfs, and we often use `Hive::getAllFunctions()` to retrieve all udf functions, but the `getAllFunctions ` often return results slowly(10s~30s). This is because the query of  ` HMSHandler::get_all_functions`  is automatically generated by JDO/DataNucleus and the query will  join `DBS `and `FUNCS `& `FUN_RU`, and the query will be slowly when having many udf functions.
In addition, when we open a Hive session, a new `Hive` object will be initialized, and all functions will be fetched. That is to say, the  ` HMSHandler::get_all_functions`  is often invoked, and we need optimize it using direct SQL.
https://github.com/apache/hive/blob/dec006e81e657bc6edb0d57d31076f04e1f088c5/ql/src/java/org/apache/hadoop/ …
=> HIVE-27780: Implement direct SQL for get_all_functions

hbase-handler/pom.xml, hbase-handler/src/test/org/apache/hadoop/hive/hbase/TestHBaseStorageHandler.java, hbase-handler/src/test/results/negative/cascade_dbdrop.q.out, itests/hcatalog-unit/pom.xml, itests/pom.xml, itests/util/pom.xml, pom.xml
Upgrade hbase to latest stable version 2.5.6
HIVE-26124 has tried to upgrade hbase to 2.4.11, but it failed with hadoop3 compatibility problem.
From https://hbase.apache.org/downloads.html, Hbase2.5.6 seems to be compatible with hadoop3, so let's try to upgrade hbase to 2.5.6.
No
=> HIVE-27651: Upgrade hbase version

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergExpireSnapshots.java, parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableExecuteSpec.java
Allow iceberg table expiry with retain last
Better usability
Yes, Iceberg snapshots can be expired using retain last
No
UT
=> HIVE-27789: Iceberg: Add a way to expire snapshots with retain last.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
In [HIVE-26596](https://issues.apache.org/jira/browse/HIVE-26596), as we have not implement all COW mode, we will enforced mor mode for iceberg v2 table.
In HS2, we check the mode(cow/mor) from hms table properties instead of iceberg properties(metadata json file), and [HIVE-26596](https://issues.apache.org/jira/browse/HIVE-26596) only change hms table properties.  Therefore, it is ok for HS2 to operate iceberg table by checking cow/mor mode from hms properties, but for others like Spark, they operate the iceberg table by checking cow/mor from iceberg properties(metadata json file).
As a result, users maybe use `MOR`mode in HS2 but use `COW` mode in Spark when executing same operation(delete/update/merge). 
Before we implement all COW mode, we need keep iceberg properties in sync with hms …
=> HIVE-27593: Iceberg: Keep iceberg properties in sync with hms properties

common/src/java/org/apache/hadoop/hive/common/auth/HiveAuthUtils.java
This PR disables ssl hostname verification for 127.0.0.1.
We need to setup production tunnel because we can't connect to production environment directly:
```shell
sh -fN -o ServerAliveInterval=60 -o ServerAliveCountMax=3 -L 127.0.0.1:10001:hiveserver2.prod.company.com:10001 bastion.company.com
JDBC url: jdbc:hive2://127.0.0.1:10001/default;ssl=true
```
But it will throw exception after HIVE-15025:
```
Exception in thread "main" java.sql.SQLException: Could not open client transport with JDBC Uri: jdbc:hive2://localhost:10001/default;ssl=true: javax.net.ssl.SSLHandshakeException: No subject alternative DNS name matching localhost found.
at org.apache.hive.jdbc.HiveConnection.<init>(HiveConnection.java:224)
at org.apache.hive.jdbc.HiveDriver.connect(HiveDriver.java:107)
at …
```
=> HIVE-27817: Disable ssl hostname verification for 127.0.0.1

itests/hive-unit/src/test/java/org/apache/hive/service/cli/thrift/TestThriftHttpCLIServiceFeatures.java, jdbc/src/java/org/apache/hive/jdbc/HttpRequestInterceptorBase.java
While debugging session cookies of a sticky session, I noticed that the JDBC driver adds an empty "Cookie" header to the request if no custom cookie is configured. This is both unnecessary and unfortunately intermittently interferes with the sticky session handling in the kubernetes nginx ingress controller, so I created this PR to omit the empty "Cookie" header in this case.
Without this change the nginx ingress controller is not able to route the request to the same hiveserver2 client in a stable way, so the jdbc session will be interrupted sooner or later.
No.
No.
Tested with a new unit test, and also tested manually with a snapshot build of jdbc driver ( - checked the headers logged by the apache http client on debug level with and without custom cookies).
=> HIVE-27866: HttpRequestInterceptorBase should not add an empty "Cookie:" header to the request if no custom cookies have been specified

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStatistics.java
Please refer to HIVE-27869 to reproduce this issue.
The name of HadoopTables iceberg is the same as its location:
https://github.com/apache/iceberg/blob/7cec1d97965a2823878aef17d5c54fc768e8612f/core/src/main/java/org/apache/iceberg/hadoop/HadoopTables.java#L95
And we make up the colStatsPath using iceberg table name and its location:
https://github.com/apache/hive/blob/master/iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java#L595-L596
For HadoopTable iceberg, its colStatsPath will like this and this is a invalid path to hdfs:
`hdfs://localhost:8028/tmp/testiceberg/default/ice_test_001/stats/hdfs:/localhost:8028/tmp/testiceberg/default/ice_test_0018020750642632422610`
I think we need check if it is HadoopTable and then return a proper path in …
=> HIVE-27869: Iceberg: Select HadoopTables will fail at HiveIcebergStorageHandler::canProvideColStats

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/YarnQueueHelper.java
Ranger Yarn Queue policies are not applying correctly, rework done for HIVE-26352
Swallowing all exceptions not correct here, We should catch only required exception type that is IO exception in this case.
No
No
CI runs and existed UT
=> HIVE-27679: Ranger Yarn Queue policies are not applying correctly, rework done for HIVE-26352

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/YarnQueueHelper.java
Fix formatting problems is YarnQueueHelper
For better code readability
No
No
Fix formatting only. no functionality involved
=> HIVE-27871: Fix formatting problems is YarnQueueHelper

common/src/java/org/apache/hadoop/hive/common/FileUtils.java, common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, itests/hive-unit-hadoop2/src/test/java/org/apache/hadoop/hive/common/TestFileUtils.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/CopyUtils.java, shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java, shims/common/src/main/java/org/apache/hadoop/hive/shims/Utils.java
Details:
* Isilon supports xAttr only on /.reserved/raw path. Because of that checkFileSystemXAttrSupport throws AccessControlException
* In case of HDFS encryption zone, a virtual path /.reserved/raw gives superusers direct access to underlying block data in filesystem.
This allows superusers to DistCp data without requiring access to encryption keys, and avoids the overhead of decrypting and re-encrypting data.
Isilon system only supports getXAttrs on /.reserved/raw paths
* Added Additional property dfs.xattr.supported.only.on.reserved.namespace which will be true in case of isilon
* Modified logic of checkFileSystemXAttrSupport to return false in case of isilon if path doesn't start with /.reserved/raw
* Isilon only supports xattr on /.reserved/raw path else it throws …
=> HIVE-27833: Hive Acid Replication Support for Dell Powerscale

ql/src/java/org/apache/hadoop/hive/ql/exec/OperatorUtils.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/ConvertJoinMapJoin.java, ql/src/test/org/apache/hadoop/hive/ql/exec/TestOperatorUtils.java, ql/src/test/queries/clientpositive/auto_sortmerge_join_17.q, ql/src/test/results/clientpositive/llap/auto_sortmerge_join_17.q.out, ql/src/test/results/clientpositive/llap/subquery_in_having.q.out
Do not convert a Common merge join operator to SMB join when any of the join branches has more than one Group by operators in the same reducer.
Each GBY operator buffers one record. These are processed when ReduceRecordSources flushes the operator tree
when end of record stream reached. If the tree has more than two GBY operators CommonMergeJoinOperator can
not process all buffered records and throws exception if the buffered records has different key values. See jira for details https://issues.apache.org/jira/browse/HIVE-27788
Yes. No exception is thrown in such cases.
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=auto_sortmerge_join_17.q -pl itests/qtest -Pitests
```
=> HIVE-27788: Exception when join has 2 Group By operators in the same branch in the same reducer

ql/src/test/queries/clientpositive/cast2.q, ql/src/test/results/clientpositive/llap/cast2.q.out, storage-api/src/java/org/apache/hadoop/hive/common/type/FastHiveDecimalImpl.java
Support valid decimal which has only scale.
Incorrect results
No
No
Yes, added testcase in cast2.q file
=> HIVE-27885 : Cast decimal from string with space without digits before dot returns NULL

pom.xml
Backport HIVE-26173 to branch-2.3: Upgrade derby to 10.14.2.0
Address CVEs, and fix some starting issues.
I found the current Derby can not start on my Ubuntu machine, upgrading fix it.
```
openjdk version "1.8.0_382"
OpenJDK Runtime Environment (Zulu 8.72.0.17-CA-linux64) (build 1.8.0_382-b05)
OpenJDK 64-Bit Server VM (Zulu 8.72.0.17-CA-linux64) (build 25.382-b05, mixed mode)
```
```
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException:null
at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at …
```
=> HIVE-26173: (2.3) Upgrade derby to 10.14.2.0

common/src/java/org/apache/hadoop/hive/common/auth/HiveAuthUtils.java
(cherry picked from commit 2eef89b5b6f350c2c9a72499c3253760df20a328)
=> HIVE-27859: Backport HIVE-27817: Disable ssl hostname verification for 127.0.0.1

pom.xml
aws-java-sdk to 1.12.499 from 1.12.132
So ,that scanners don't keep flagging CVEs
No
Yes
Built manually and relying on precommit
=> HIVE-27907:Upragde aws-java-sdk to 1.12.499

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAugmentSnapshotMaterializationRule.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewUtils.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HivePushdownSnapshotFilterRule.java, ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/TestHiveAugmentSnapshotMaterializationRule.java, ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/TestHivePushdownSnapshotFilterRule.java, ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/TestRuleBase.java
* Use Objects.equals for comparing saved snapshot in MV metadata and table current snapshot.
* HiveStorageHandler.getCurrentSnapshotContext() returns null when table is empty and no snapshot exists. Add null check of snapshotId when creating filter predicate
If both saved snapshot in MV metadata and table current snapshot are null NPE was thrown.
No.
No.
```
mvn test -Dtest=TestHiveAugmentSnapshotMaterializationRule,TestHivePushdownSnapshotFilterRule -pl ql
mvn test -Dtest.output.overwrite -Dtest=TestIcebergLlapLocalCliDriver -Dqfile=mv_iceberg_orc.q -pl itests/qtest-iceberg -Piceberg -Pitests
```
and search for NPE in `hive.log`
=> HIVE-27867: Incremental materialized view throws NPE whew Iceberg source table is empty

ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastHashTableLoader.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastLongHashMapContainer.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastMultiKeyHashMapContainer.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastStringHashMapContainer.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastStringHashMultiSetContainer.java, ql/src/test/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/TestVectorMapJoinFastHashMapContainerNonMatched.java, ql/src/test/queries/clientpositive/vector_fullouter_mapjoin_multithread_fast_htloader.q, ql/src/test/results/clientpositive/llap/vector_fullouter_mapjoin_multithread_fast_htloader.q.out
This patch changes VectorMapJoinFastHashMapContainer to create multiple MatchTracker, each of which tracks distinct HashMap in the HashMapContainer.
In addition, it fixes fixed size array allocation problem in 3 classes and adjusts the number of partitioned HashTable when it is not a power of 2.
Current VectorMapJoinFastHashMapContainers have 1 MatchTracker and multiple HashMaps. MatchTracker tracks MATCHED entries by marking the index of HashTable entry in a bitset. Since multiple HashMaps use the same MatchTracker, if one of the HashTables marks the index as MATCHED, then the other HashMap's entry on the same index is also treated as MATCHED regardless of actual join result. This leads to missing non-matched join results of FullOuterJoin.
No
No
I added unit tests for Long, String, and …
=> HIVE-27269: Create multiple MatchTracker when using VectorFastHashMapContainer

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java
Add ability to mask default location
Better usability  
Yes, if configured the auth uri will have default location masked
No
UT
=> HIVE-27714: Iceberg: metadata location overrides can cause data breach - handling default locations.

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergRestrictDataFiles.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestRestrictedList.java
Add a config which ensures all the data files are within the table location.
Security use-cases
Yes, if the config is turned on, the iceberg tables with data files outside the table directory won't be readable.
No
UT
=> HIVE-27323: Iceberg: malformed manifest file or list can cause data breach.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTransformSortFunctionUtil.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/udf/GenericUDFIcebergBucket.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/udf/GenericUDFIcebergDay.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/udf/GenericUDFIcebergHour.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/udf/GenericUDFIcebergMonth.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/udf/GenericUDFIcebergTruncate.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/udf/GenericUDFIcebergYear.java, iceberg/iceberg-handler/src/test/queries/positive/dynamic_partition_writes.q, iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_copy_on_write_partitioned.q.out, iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_writes.q.out, iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_partitioned.q.out, iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_partitioned_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/update_iceberg_copy_on_write_partitioned.q.out, ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
Iceberg: Push transforms for clustering during table writes
Currently transformed columns (except for bucket transform) are not pushed / passed as clustering columns. This can lead to incorrect clustering on such columns which can lead non-performant writes. Hence push transforms for clustering during table writes.
No
No
QTests
=> HIVE-27918: Iceberg: Push transforms for clustering during table writes

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
The HMSHandler class (standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler) encompasses multiple functions bearing names as 'get_partition*' pertaining to partition information, yet its current implementation lacks comprehensive logging of substantial partition data. This PR adds additional logs to all such functions. The existing code has been refactored to cater to the additional logging helpers.
The current implementation of the HMSHandler class bears many partition info related functions, yet the logs for such functions only bear the Table information, lacking critical partition data. 
No
No
The tests for the affected functions were already present. Running them produces the enhanced logs now.
=> HIVE-27894: Enhanced HMSHandler partition logs

ql/src/test/queries/clientnegative/avro_duplicate_field_name.q, ql/src/test/queries/clientnegative/avro_invalid_field_name.q, ql/src/test/results/clientnegative/avro_duplicate_field_name.q.out, ql/src/test/results/clientnegative/avro_invalid_field_name.q.out
[HIVE-27935](https://issues.apache.org/jira/browse/HIVE-27935): Add Qtest for testing duplicate and invalid field names in Avro Schema
Imporving test coverage for Hive Avro tables
no
No
Qtest
=> HIVE-27935: Add qtest for Avro invalid schema and field names

ql/src/java/org/apache/hadoop/hive/ql/metadata/Partition.java
Check if the SD of a Partition exists to avoid NPE. 
The Partition SD may lost in backend metadata database for some reasons. For these partitions with corrupted metadata, we can  not even drop them if the NPE exists.
No.
No new tests.
=> HIVE-27093: Fix NPE in initialize() of Partition class

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/PartitionIterable.java, ql/src/test/org/apache/hadoop/hive/ql/exec/TestGetPartitionInBatches.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PartitionIterable.java
Adding a range validator as the part of this Jira to keep the lower bound value of hive.metastore.batch.retrieve.max to be 1. Also blocking PartitionIterable call if any user/client ever calls the constructor directly with batch size <1. Currently there is no Validation for the property hive.metastore.batch.retrieve.max. In case if it is ever set to <= 0, PartitionIterable will throw up NoSuchElementException because the batch size will be 0 there. 
GetPartition can fail due to thrift having a size limitation of 2 GB. To bypass this PartitionIterable is used, PartitionIterable converts one getpartition call for a table with large number of partitions into multiple HMS calls of smaller getPartitions calls. PartitionIterable has a batchsize as a parameter. In case if the batchsize is ever …
=> HIVE-27893 Add a range validator in hive.metastore.batch.retrieve.max to only have values greater than 0

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTablesBootstrap.java
Disable the flaky test as it often fails in CI.
I have noticed that this test failed in many PR CI test, such as:
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4917/1/tests/
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4909/2/tests/
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4905/2/tests/
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4913/1/tests/
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4894/2/tests
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4915/4/tests
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4915/5/tests …
=> HIVE-27936: Disable flaky test testBootstrapAcidTablesDuringIncrementalWithConcurrentWrites

ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveJoinInsertDeleteIncrementalRewritingRule.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveRowIsDeletedPropagator.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/InputRefShifter.java, ql/src/test/queries/clientpositive/materialized_view_join_rebuild.q, ql/src/test/queries/clientpositive/materialized_view_repeated_rebuild.q, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_5.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_8.q.out, ql/src/test/results/clientpositive/llap/materialized_view_join_rebuild.q.out, ql/src/test/results/clientpositive/llap/materialized_view_repeated_rebuild.q.out
The incremental MV rebuild plan in presence of delete operations is based on right outer joining the delta result set produced by the MV definition query to the MV.
https://github.com/apache/hive/blob/02851615a2f4ae3fced4edec76c7c4a06f6f63c1/ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveJoinInsertDeleteIncrementalRewritingRule.java#L49-L51
Alter this CBO plan generation by projecting a flag on the MV side and use it in the filter of the delete branch when transforming the plan into a multi insert at the optimized AST level.
1. Let assume that the MV definition has a join. When records with `join_key = x` is deleted the from only one of the joined tables the result records are also deleted from the MV at rebuild time. Then the records with the same key are deleted …
=> HIVE-27446: Exception when rebuild materialized view incrementally in presence of delete operations

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveRelDecorrelator.java, ql/src/test/queries/clientpositive/subquery_complex_correlation_predicates.q, ql/src/test/results/clientpositive/llap/subquery_complex_correlation_predicates.q.out
In cases where different Rel nodes refer to the same correlation var, we avoid creating another correlation var and record the 'rel' using the same correlation. 
SortedSetMultimap can't be used since it doesn't allow duplicates. 
`mapFieldAccessToCorVar.containsKey(fieldAccess)` was never positive in previous versions of Calcite (1.16) since RexFieldAccess had no equals() and hashcode() defined.
fixes plan after decorrelation
No
No
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=subquery_complex_correlation_predicates.q
=> HIVE-27801: Exists subquery rewrite results in a wrong plan

itests/hive-unit/pom.xml, pom.xml
Upgrade ivy to 2.5.2 and htmunit to 2.70.0
CVE Fixing
No
Yes
Locally built , relying on precommit.
=>  HIVE-27824 : Upgrade ivy to 2.5.2 and htmunit to 2.70.0

common/src/java/org/apache/hive/http/HttpServer.java, hcatalog/webhcat/svr/src/main/java/org/apache/hive/hcatalog/templeton/Main.java, service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpCLIService.java
Use SslContextFactory.Server() instead of SslContextFactory() when constructing the factory.
With Jetty 9.4.40, the base constructor fails to handle a KeyStore with multiple certificates in it.
```
Caused by: java.lang.IllegalStateException:
KeyStores with multiple certificates are not supported on the base class org.eclipse.jetty.util.ssl.SslContextFactory.
(Use org.eclipse.jetty.util.ssl.SslContextFactory$Server or org.eclipse.jetty.util.ssl.SslContextFactory$Client instead)
```
No
No
manually tested on a secure cluster
=> HIVE-27952: Use SslContextFactory.Server() instead of SslContextFactory

ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/results/clientpositive/llap/ppd_transform.q.out, ql/src/test/results/clientpositive/llap/schemeAuthority.q.out, ql/src/test/results/clientpositive/llap/schemeAuthority2.q.out
Use Local FS to qualify a path if LOCAL is used
To push correct qualified path to Ranger when using LOCAL
No
No
=> HIVE-25803: URL Mapping appends default Fs scheme even for LOCAL DIRECTORY ops.

ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsTask.java
Remove the duplicate stats info from beeline console.
if `hive.tez.exec.print.summary` is true, beeline console will print duplicate stats info.  Please see HIVE-27961 to check the info.
This stats info is displayed by default([BasicStatsTask.java L315](https://github.com/apache/hive/blob/4a057a7cea11029dbda7adaec09117d46e56d925/ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsTask.java#L315)), and no need to be displayed again when `hive.tez.exec.print.summary` is true.
https://github.com/apache/hive/blob/4a057a7cea11029dbda7adaec09117d46e56d925/ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsTask.java#L312-L316
No
No
No need test
=> HIVE-27961: Beeline will print duplicate stats info when hive.tez.exec.print.summary is true

itests/hive-unit/src/test/java/org/apache/hive/service/cli/operation/TestOperationLoggingAPIWithMr.java
org.apache.hive.service.cli.operation.TestOperationLoggingAPIWithMr#testFetchResultsOfLogWithOrientation test is flaky and can easily result into CI failed.
Here are some affected pipelines:
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4959/3/tests
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4755/15/tests
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4966/1/tests
http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-4517/25/tests
Disable unstable test.
No
No
Pass existing tests.
=> HIVE-27966: Disable flaky testFetchResultsOfLogWithOrientation

data/conf/iceberg/tez/tez-site.xml
Increasing tez.am.resource.memory.mb for tez based iceberg cli driver.
To improve test stability.
No.
No.
Precommit.
=> HIVE-27916: Increase tez.am.resource.memory.mb for TestIcebergCliDrver to 512MB

itests/hive-unit/pom.xml, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestTimedOutTxnNotificationLogging.java
To fix hive-unit tests running by removing a jupiter dependency.
Because tests in hive-unit module are not running again.
No.
Not an upgrade, just removing a test-scoped dependency in hive-unit module.
Precommit tests.
=> HIVE-27978: Tests in hive-unit module are not running again

llap-client/src/java/org/apache/hadoop/hive/llap/registry/impl/LlapZookeeperRegistryImpl.java, llap-client/src/java/org/apache/hadoop/hive/registry/impl/ZkRegistryBase.java, llap-client/src/test/org/apache/hadoop/hive/llap/registry/impl/TestLlapZookeeperRegistryImpl.java
In the query-executor, we create ephemeral nodes which have the special behaviour that they are automatically deleted when the query-coordinator zookeeper client session is terminated. If there are no other Hive VWs on the cluster, sooner or later the entire path will be deleted.
To avoid this, we need to have a persistent node on path /llap-sasl/user-hivefoo0/pnode0.
Hue or beeline session thows InvalidACL exception when executing drop database, drop table or alter table drop partition operations on a Hive Virtual Warehouse that is in Stopped state: "org.apache.zookeeper.KeeperException$InvalidACLException: KeeperErrorCode = InvalidACL for /llap-sasl/user-hive".
The exception appears because the Hive VW wants to evict the cache in the LLAP executors, but those computes in a Stopped …
=> HIVE-27911 : Drop database query failing with Invalid ACL Exception

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, data/conf/iceberg/llap/hive-site.xml, data/conf/iceberg/llap/tez-site.xml, data/conf/iceberg/tez/hive-site.xml, data/conf/iceberg/tez/tez-site.xml, data/conf/llap/hive-site.xml, data/conf/llap/tez-site.xml, data/conf/tez/tez-site.xml, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezAvailableSlotsCalculator.java
- added a useful comment in HiveConf for hive.tez.container.size
- cleaned up hive-site and tez-site xml files accordingly:
- removed hive.tez.container.size from tez-site.xml (even if it works from there, it's a hive option, should be in hive-site for clarity's sake)
- updated hive.tez.container.size in hive-site where a bigger value was removed from tez-site
- minimal refactor in DagUtils in the same area, added debug level messages
Clarity in HiveConf and qtests.
No.
No.
Precommit, and manually checked tez logs.
in DAGAppMaster log:
```
2023-12-05T09:39:06,211 INFO [DelayedContainerManager] rm.YarnTaskSchedulerService: Assigning container to task: containerId=container_1701797922416_0001_01_000002, task=attempt_1701797922416_0001_1_00_000000_0, containerHost=localhost:60444, …
```
=> HIVE-27937: Clarifying comments and xml configs around tez container size

ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
When drop external table, we actually not need delete the table path. But now HMS will check write permission if `AUTHORIZATION_STORAGE_AUTH_CHECKS` enabled no matter the table is external or not.
Fix the bug that drop external table should not fail by the storage permission.
No,
No.
Add a UT.
=> HIVE-27857: Do not check write permission while dropping external table or partition

itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
Introduce ORDER BY clause in some unit tests.
Bumped into intermittent test failures in TestHplSqlViaBeeLine while moving it from MR to Tez, and realized that the ordering is not defined in the test cases, so it makes no sense to look for the execution engine differences as long as we don't have a stable golden output.
No.
No.
With the touched unit tests.
=> HIVE-27977: Fix ordering flakiness in TestHplSqlViaBeeLine

hcatalog/core/src/main/java/org/apache/hive/hcatalog/mapreduce/FileOutputCommitterContainer.java, hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatDynamicPartitioned.java, hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatExternalDynamicPartitioned.java
clean up the code for readibilty
fix the issue when parent partition path exists for multi partitioned dynamic insert.
fix bug:
if a table have multiple partitions (part1=x1, part2=y1), when insert into a new partition(part1=x1, part2=y2) hcatalog FileOutputCommitterContainer throws path part1=x1 already exists error. This is due to the path checking stops at parent level, 
pig -useHcatalog
A = load 'source' using org.apache.hive.hcatalog.pig.HCatLoader();
B = filter A by (part2 == 'y1');
// following succeeds
store B into 'target' USING org.apache.hive.hcatalog.pig.HCatStorer();
//following fails with duplicate publishing error
C = filter A by (part2 == 'y2');
store C into 'target' USING org.apache.hive.hcatalog.pig.HCatStorer();
```
Partition already present with given partition key …
```
=> HIVE-27951: hcatalog dynamic partitioning fails with partition already exist error when exist parent partitions path

ql/src/test/org/apache/hadoop/hive/ql/parse/repl/metric/TestReplicationMetricCollector.java
Fix flaky test. Details in the ticket.
Flaky test on the branch: http://ci.hive.apache.org/job/hive-flaky-check/786/
And also on master: http://ci.hive.apache.org/job/hive-flaky-check/784/
Note: it seems, it became flaky only on downstream. 
Per test case object shouldn't be static
To fix the test
No
No
By running tests and flaky test checker
=> HIVE-27974: Fix flaky test - TestReplicationMetricCollector.testSuccessStageFailure

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaderElectionContext.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaderElectionFactory.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaseLeaderElection.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/leader/TestLeaderElection.java
Fix the flaky test
No
No
http://ci.hive.apache.org/job/hive-flaky-check/800/
=> HIVE-28001: Fix the flaky test TestLeaderElection

ql/src/test/queries/clientpositive/rename_table.q, ql/src/test/results/clientpositive/llap/rename_table.q.out, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdatePart.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/StatObjectConverter.java
=> HIVE-27994: Optimize renaming the partitioned table

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
add log
1. `alter_partitions` outputs multiple partition values, but there is no table name. 
2. When updating the statistics of the partition, there is only the table name, but the partition name is not known.
No
No
=> HIVE-27979: HMS alter_partitions log adds table name

iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_unpartitioned.q.out, iceberg/iceberg-handler/src/test/results/positive/update_iceberg_copy_on_write_partitioned.q.out, iceberg/iceberg-handler/src/test/results/positive/update_iceberg_copy_on_write_unpartitioned.q.out, ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java, ql/src/test/queries/clientpositive/sharedwork_virtualcol_schema_merge.q, ql/src/test/results/clientpositive/llap/sharedwork_virtualcol_schema_merge.q.out
Extend table scan schema comparing with comparing virtual columns in shared work optimizer.
Shared work optimizer can merge table scan operators scanning the same table with different schema. This feature is controlled by `hive.optimize.shared.work.merge.ts.schema` but the current implementation ignores the value of the flag and always merge.
Only in execution plans.
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=sharedwork_virtualcol_schema_merge.q -pl itests/qtest -Pitests
mvn test -Dtest.output.overwrite -Dtest=TestIcebergCliDriver -Dqfile=merge_iceberg_copy_on_write_unpartitioned.q,update_iceberg_copy_on_write_partitioned.q,update_iceberg_copy_on_write_unpartitioned.q -pl itests/qtest-iceberg -Piceberg -Pitests
```
=> HIVE-28009: Shared work optimizer ignores schema merge setting in case of virtual column difference

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergRecordWriter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterBuilder.java, iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_partitioned_orc.q.out, ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java, ql/src/java/org/apache/hadoop/hive/ql/plan/DynamicPartitionCtx.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/HiveCustomStorageHandlerUtils.java
Utilise FanoutWriters when inserting records in an Iceberg table when the records are unsorted
FanoutWriter is a writer in Iceberg which can be used to write records in a table. This writer keeps all the file handles open, until the write is finished. FanoutWriters is used as the writer when the incoming records are unsorted. We can by default have some mechanism to switch to using FanoutWriters instead of ClusteredWriters when custom sort expressions are not present for the given table/query.
Similar stuff is already implemented in Spark - https://github.com/apache/iceberg/pull/8621
No
No
QTests
=> HIVE-27991: Utilise FanoutWriters when inserting records in an Iceberg table when the records are unsorted

llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/AsyncTaskCopyAuxJars.java
LLAP was failing to launch daemons due to incorrect class references not being packed anymore
https://issues.apache.org/jira/browse/HIVE-27942
Updated class references in default aux classes for pool and dbcp to correct class names
No
Is the change a dependency upgrade?
No
NA
=> HIVE-27942: Missing aux jar errors during LLAP launch

llap-common/src/java/org/apache/hadoop/hive/llap/security/LlapSignerImpl.java
=> HIVE-28030: LLAP util code refactor

itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java, ql/src/java/org/apache/hadoop/hive/ql/exec/ColumnStatsUpdateTask.java, ql/src/java/org/apache/hadoop/hive/ql/stats/ColStatsProcessor.java, standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp, standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ColumnStatistics.java, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/GetPartitionsByNamesRequest.java, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/GetTableRequest.java, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/PartitionsStatsRequest.java, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/SetPartitionsStatsRequest.java, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/TableStatsRequest.java, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ColumnStatistics.php, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/GetPartitionsByNamesRequest.php, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/GetTableRequest.php, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/PartitionsStatsRequest.php, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/SetPartitionsStatsRequest.php, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/TableStatsRequest.php, standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py, standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Please see details from HIVE-27984.
HIVE-22046 indroduced the must required `engine` field in hms thrift api, which broken the backward compatibility. This lead to hive3 hms thrift client can not call the hive4 column stats api.
This PR try to make `engine ` field optional and then this will reduce the incompatibility issues.
No
No
Test with local cluster. And this change has no negative effect to Hive.
=> HIVE-27984: Support backward compatibility of hms thrift struct about column stats

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
Mark `DeadlineException` as unrecoverable exception to avoid falling back to jdo query.
`DeadlineException` should be terminated immediately, instead of falling back to jdo query.
https://github.com/apache/hive/blob/b75a59779dcf9c5ef74890c8916dbe9a2c13aef4/standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RetryingHMSHandler.java#L137-L142
No.
No.
Passing test:
```bash
mvn test -Dtest=org.apache.hadoop.hive.metastore.TestObjectStore -pl :hive-standalone-metastore-server
```
=> HIVE-28038: Disable fallback to jdo for DeadlineException

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdatePart.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/retry/SqlRetryHandler.java
Code refactor for `DirectSqlUpdatePart` class:
1. Move lock and unlock operations into `DatabaseProduct` class
2. Use try-for-resources instead of finally close
Code refactor.
No.
No.
Pass existing tests.
=> HIVE-27958: Refactor DirectSqlUpdatePart class

iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergBranchOperation.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveUtils.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Make branches with non lowercase characters accessible.
You can create/have branches with lower cases, but can't query them
Yes, they can now query branches with non lowercase characters.
No
UT
=> HIVE-28057: Iceberg: Branches with non-lowercase characters can't be accessed.

itests/util/src/main/java/org/apache/hadoop/hive/ql/QOutProcessor.java, pom.xml, ql/src/test/results/clientnegative/broken_pipe.q.out, ql/src/test/results/clientnegative/cachingprintstream.q.out, ql/src/test/results/clientnegative/script_broken_pipe3.q.out, ql/src/test/results/clientnegative/script_error.q.out, ql/src/test/results/clientnegative/stack_trace.q.out
Upgrade to tez 0.10.3
Needed for Hive 4.0, as Tez 0.10.3 brings a newer hadoop dependency, which solves some conflicts.
No.
Yes.
https://issues.apache.org/jira/secure/attachment/13066623/hive_on_tez_0_10_3_dep.log
Preceommit testing.
=> HIVE-27992: Upgrade to tez 0.10.3

iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java, shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
This is to utilize the RPC free local DAGAppMaster introduced in TEZ-4236.
Because it makes unit tests stable by not starting a useless RPC in tez local mode.
No.
No.
All tez based qtests.
=> HIVE-26445: Use tez.local.mode.without.network for qtests

hcatalog/webhcat/svr/pom.xml, jdbc/pom.xml, kafka-handler/pom.xml, llap-client/pom.xml, llap-tez/pom.xml, pom.xml, ql/pom.xml, shims/common/pom.xml, standalone-metastore/metastore-common/pom.xml, standalone-metastore/pom.xml
This PR upgrades Zookeeper version to 3.8.3
Zookeeper has been upgraded to [3.8.3](https://github.com/apache/zookeeper/blob/release-3.8.3/pom.xml) as a part of its stable release. 
No
Yes
The automated tests are successful. 
OSS JIRA : [HIVE-28043](https://issues.apache.org/jira/browse/HIVE-28043)
=> HIVE-28043 : Upgrade ZooKeeper to 3.8.3

itests/qtest-druid/pom.xml, standalone-metastore/pom.xml
Sync jetty version across the standalone-metastore/pom.xml and itests/qtest-druid/pom.xml
Looks like this was skipped in HIVE-27757. As in HIVE-24484, it was upgraded uniformly
NO
Yes
Will see the outcome of CI
=> HIVE-28071: Sync jetty version across modules

ql/src/java/org/apache/hadoop/hive/ql/session/ClearDanglingScratchDir.java
Code refine. Make code more readable.
No
No
Existing UT.
=> HIVE-28081: Code refine on ClearDanglingScratchDir::removeLocalTmpFiles

standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestTxnDbUtil.java
queryToString separates the columns with 3 spaces. It would improve the debugging experience if we have a method that shows the data in CSV format so that the output can be easily imported into a spreadsheet.
Two new method in TestTxnDbUtil: queryToCsv (with or without header). 
To easily be able to import the output into a sheet during a debugging session.
No
No
Manually
=> HIVE-28078: TestTxnDbUtil should generate csv files when we query the metastore database

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/MetastoreLock.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
In order to allow the percent symbol to be used as a schema or table name, the percent symbol needs to be escaped.
In alpha 2 and earlier, including a percent symbol wouldn't cause exceptions.  This change is to make beta 1 and beyond compatible.
Currently, in the beta 1 code, if the percent symbol is used as a schema or table name, you will get an UnknownFormatConversionException: Conversion = '_'
No
No
Tested it manually by creating a table with a percent, specifically "[|]#&%@"."[|]#&%@"
=> HIVE-28021: Iceberg: Attempting to create a table with a percent symbol fails

ql/src/java/org/apache/hadoop/hive/ql/Context.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/cte_mat_11.q, ql/src/test/results/clientpositive/llap/cte_3.q.out, ql/src/test/results/clientpositive/llap/cte_mat_10.q.out, ql/src/test/results/clientpositive/llap/cte_mat_11.q.out, ql/src/test/results/clientpositive/llap/cte_mat_3.q.out, ql/src/test/results/clientpositive/llap/cte_mat_4.q.out, ql/src/test/results/clientpositive/llap/cte_mat_5.q.out, ql/src/test/results/clientpositive/llap/cte_mat_6.q.out, ql/src/test/results/clientpositive/llap/cte_mat_8.q.out, ql/src/test/results/clientpositive/llap/cte_mat_9.q.out
Copy statistics of the source FileSinkOperator into the TableScanOperator, which scans a materialized CTE written by the FileSinkOperator.
Currently, Hive estimates the statistics of materialized CTEs are always empty. It causes OOM or significant slowdown.
No.
No.
I added a new test case. [The first commit explains the result with the current master branch](https://github.com/apache/hive/pull/5089/commits/ca6cae1ee2ecacd5fdf4291225edf1c79130a2b2).
=> HIVE-28080: Propagate statistics from a source table to the materialized CTE

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/compaction/IcebergCompactionService.java
Setting CompactionInfo.runAs in Iceberg Compaction Service.
Without runAs set, execution fails during compilation phase on access authorization in internal environments. 
Besides that, if runAs is not set and Iceberg compaction throws any exception, without this fix there will be also another exception thrown in the catch block here:
https://github.com/apache/hive/blob/a348e5d86adc611e4f72d386815a21a96b667ab4/ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java#L258
No
No
Testing with dev jars on local dev env and precommit tests.
=> HIVE-27850: Iceberg: Addendum 2: Set runAs user in CompactionInfo.

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
HIVE_VECTORIZATION_USE_ROW_DESERIALIZE in hiveconf.java imply default value is false，in fact the default value is 'true'
Description statement is wrong.
comment of default value of the config parameter.
Not required as its change of the config param description
=> HIVE-25972: HIVE_VECTORIZATION_USE_ROW_DESERIALIZE in hiveconf.java imply default value is false，in fact the default value is 'true'

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezRuntimeException.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java, ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecDriver.java, ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecuteLostAMQueryPlugin.java, ql/src/test/org/apache/hadoop/hive/ql/reexec/TestReExecuteLostAMQueryPlugin.java
Related to [TEZ-4543](https://issues.apache.org/jira/browse/TEZ-4543), this is to rerun DAG if the client faces a DAG_FAILED due to NoCurrentDAGException in the AM.
TEZ-4543 takes care of returning quite fast if a restarted AM doesn't run the queried DAG.
No.
No.
Tested on cluster, and unit tests for AM + Hive already added.
This is logged when dag_1708961199044_0002_1 failed earlier, and as I kept injected OOM into an AM (making it crash in a k8s environment), dag_1708961199044_0003_1 is failed again.
```
hiveserver2 <14>1 2024-02-26T16:00:37.730Z hiveserver2-0 hiveserver2 1 dedef3f4-339f-4ba3-a6ae-300751d3561d [mdc@18060 class="reexec.ReExecuteLostAMQueryPlugin" dagId="dag_1708961199044_0003_1" level="INFO" operationLogLevel="EXECUTION" …
```
=> HIVE-28093: Re-execute DAG in case of NoCurrentDAGException

hplsql/src/main/java/org/apache/hive/hplsql/functions/InMemoryFunctionRegistry.java, hplsql/src/test/results/local/arity.out.txt, itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
HIVE-27490: HPL/SQL says it support default value for parameters but not considering them when no value is passed
The changes support considering default values specified for that parameter when value is not passed for the param of a HPLSQL procedure.
The change is required to support considering default values specified for that parameter when value is not passed for the param of a HPLSQL procedure.
No
No
Tests are added.
=> HIVE-27490: HPL/SQL says it support default value for parameters but not considering them when no value is passed

pom.xml, standalone-metastore/pom.xml
Bump jackson from 2.13.5 to 2.16.1
Jackson-databind through 2.15.2 allows attackers to cause a denial of service or other unspecified impact via a crafted object that uses cyclic dependencies.
https://nvd.nist.gov/vuln/detail/CVE-2023-35116
https://github.com/FasterXML/jackson-databind/issues/3972
No
Yes
[jacksonTree.txt](https://github.com/apache/hive/files/14342159/jacksonTree.txt)
Manually
=> HIVE-28073: Upgrade jackson version to 2.16.1

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/FilesForCommit.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergCopyOnWriteRecordWriter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergDeleteWriter.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/writer/TestHiveIcebergDeleteWriter.java
Validate Data Files Exist for RowDelta Operations
RewriteFiles Operations called by compaction jobs(Spark), leads to data corruption when running concurrently with MERGE?UPDATE/DELETE Queries
Prevents Data corruption
No
CI
=> HIVE-28102: Iceberg: Invoke validateDataFilesExist for RowDelta operations.

common/src/java/org/apache/hadoop/hive/common/auth/HiveAuthUtils.java, common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java, metastore/src/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, metastore/src/test/org/apache/hadoop/hive/metastore/TestHiveMetaStoreTimeout.java
Backport HIVE-27172 to branch-2.3
Hive 2.3 is used in Apache Spark to communicate with HMS, while making the socket connect timeout configurable and independent with socket timeout is extremely useful.
In practice, we deploy multi HMS instances to achieve load balance and disaster recovery, we expect a short connect timeout in case the target HMS instance is under high load or has network issues, so that the HMS client could quickly failover to another one. While we expect a little bit longer socket timeout in cases some thrift invocations take a long time, e.g. a  HMS may take a dozen minutes to handle a table/partition request if the table is large or has million partitions.
Add a new configuration while the default value keeps the existing behavior.
No
New tests are added.
=> HIVE-27172: (2.3) Add the HMS client connection timeout config

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/SharedCache.java
JIRA : HIVE-28100. Fix Some Typos in CachedStore.
I received some discussions about CachedStore in the mail. I looked at the code of CachedStore and found some typo issues. This PR will fix this issue.
=> HIVE-28100. Fix Some Typos in CachedStore.

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapDaemon.java, llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LocalDirCleaner.java, llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/TestLlapDaemon.java
Implement a LocalDirCleaner which can remove old files from LLAP local dirs.
Because LLAP cannot take care of cleaning up old files in every failure scenario, this was shown in a customer problem. When I investigated [HIVE-24272](https://issues.apache.org/jira/browse/HIVE-24272) I found that local files for failed queries/DAGs are cleaned up, so this is clearly about leftovers after daemon crashes.
No.
No.
Unit test added, tested on llap daemon, added a file as:
```
mkdir -p  /apps/llap/work/usercache/hive/appcache/application_1707917402901_0001/3/output
touch  /apps/llap/work/usercache/hive/appcache/application_1707917402901_0001/3/output/file.out
```
set quick intervals like:
```
hive.llap.local.dir.cleaner.file.modify.time.threshold=60s
hive.llap.local.dir.cleaner.cleanup.interval=30s …
```
=> HIVE-28051: LLAP: cleanup local folders on startup and periodically

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/cte_mat_11.q, ql/src/test/results/clientpositive/llap/cte_mat_11.q.out
Makes the stats population more defensive.
https://issues.apache.org/jira/browse/HIVE-28098
The current implementation fails when column stats are missing.
No, it doesn't.
No.
I added various test cases to cte_mat_11.q.
=> HIVE-28098: Fails to copy empty column statistics of materialized CTE

hcatalog/webhcat/svr/src/main/java/org/apache/hive/hcatalog/templeton/Main.java, service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java, shims/common/src/main/java/org/apache/hadoop/hive/shims/HttpUtils.java, shims/common/src/main/java/org/apache/hadoop/hive/shims/Utils.java
HIVE-13853 added some HTTP-related methods to the shims `Utils`, this PR aims to move it to a dedicated class `HttpUtils`
The invocation of any method in `Utils` will trigger all imported classes to be loaded, which blocks the downstream projects from migrating from `javax.servlet-api` to `jakarta.servlet-api`, see more context at https://github.com/apache/spark/pull/45154#issuecomment-1953601887
No.
No.
Pass CI(no new failed tests) to ensure everything goes well on the Hive side.
Spark integration tests
- Code change: https://github.com/pan3793/spark/tree/hive-2310
- Temporary Maven Repo: https://raw.github.com/pan3793/mvn-repo/release-2.3.102/
- CI report: https://github.com/pan3793/spark/actions/runs/8134350147/job/22230571255
=> HIVE-28104. (2.3) Move HTTP related methods from Utils to HttpUtils in shims

ql/src/test/queries/clientpositive/acid_bloom_filter_orc_file_dump.q
The test uses the PostExecOrcFileDump post exec hook on a limit 1 query. 
It has no order by and the test table contains two rows. Sometimes it picks up the other row than it is in the q.out file. 
Define explicit order
Test stability
No
No
`mvn test -Pitests -pl itests/qtest -Dtest=TestMiniLlapLocalCliDriver -Dqfile=acid_bloom_filter_orc_file_dump.q`
=> HIVE-28142: Fix flakyness in acid_bloom_filter_orc_file_dump

standalone-metastore/metastore-tools/metastore-benchmarks/README.md, standalone-metastore/metastore-tools/metastore-benchmarks/pom.xml
The logging is completely broken in HMS benchmarks. When we create a Log entry, it only outputs a format pattern string instead of the log message. 
Example output:
`%d [%thread] %-5level %logger - %msg`
TxnHandler refactor introduced Spring and it seems spring logging causes the issue. There are two changes in the PR: 
- exclude spring-jcl (https://stackoverflow.com/questions/50176843/log42-xml-is-not-picked-up-when-running-jmh-benchmark-from-test-directory)
- move from assembly to shading plugin to be able to run log4j2CacheTransformer (https://stackoverflow.com/questions/25065580/log4j2-custom-plugins-annotation-processing-with-maven-assembly-plugin)
I want to do some metastore performance benchmarks. It is pretty hard to do that without logging.
No
No
Manually test: `java    -jar …
=> HIVE-28099: Fix logging in HMS benchmarks

ql/src/java/org/apache/hadoop/hive/ql/parse/ExecuteStatementAnalyzer.java, ql/src/test/results/clientpositive/llap/prepare_plan.q.out, ql/src/test/results/clientpositive/llap/prepare_plan_partition_pruning.q.out
Execute Statement should report the correct query string. Because it inherits the conf from the prepare query's sem object, we need to update the query string.
Because currently execute queries report the prepare statement as their query string in all the logs.
No
No
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=execute_query_string.q
=> HIVE-28129 Execute statement doesnot report the correct query string information

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestMetaStoreLimitPartitionRequest.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
1. Add partition number check in `get_partitions_by_names`
2. Skipping get partition ids in `MetaStoreDirectSql#getPartitionsViaPartNames` to reduce the Database calls.
1. `get_partitions_by_names` also need check partition number in case the request number is too large
2. remove unnecessary db calls can improve the performance.
Yes, `get_partitions_by_names` api could also hit partition limit after this PR.
No.
1. Passing all existing tests.
2. Run the `getPartitionsByNames` benchmark tests:
```bash
java -jar ./hmsbench-jar-with-dependencies.jar -H localhost --savedata /tmp/benchdata --sanitize -N 100 -N 10000 -o bench_results_direct.csv -C -d testbench_http --params=100  -E 'drop.*' -E 'renameTable.*' -E 'getTableObjectsByName.*' -E 'listTables.*' -E 'listPartitions.*' -E …
```
=> HIVE-28062: Optimize get_partitions_by_names in direct sql

pom.xml, ql/pom.xml, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/NanoTimeUtils.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/datetime/DateTimeStamp.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/datetime/JDateTime.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/datetime/JDateTimeDefault.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/datetime/JulianDateStamp.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/datetime/TimeUtil.java, service/src/resources/hive-webapps/hiveserver2/hiveserver2.jsp
This is an alternative to https://github.com/apache/hive/pull/4923 to address jodd CVE.
Hive uses jodd's JDateTime to handle Julian's calendar in processing Parquet timestamp, while the calendar is tricky and bugly stuff, considering that branch-2.3 has been in maintaining mode for a long time, I prefer to copy the corresponding code to **avoid involving any unexpected behavior change**.
To address CVE-2018-21234.
Jodd CVE is listed in https://issues.apache.org/jira/browse/SPARK-44757 top 1, with a score 9.8.
No.
No.
UT
=> HIVE-25054: (2.3) Drop vulnerable jodd-core dependency

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/queries/positive/truncate_iceberg_branch.q, iceberg/iceberg-handler/src/test/results/positive/truncate_iceberg_branch.q.out, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java, ql/src/java/org/apache/hadoop/hive/ql/parse/HiveTableName.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Truncate on iceberg branch should work on that branch not on the main table itself
Else truncate operations on the branch wipes out the original table.
Yes, If you call truncate on an iceberg branch it will get truncated instead of the main table
No
UT
=> HIVE-28166: Iceberg: Truncate on branch operates on the main table.

itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CoreCliDriver.java, itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestMetaStoreHandler.java
Running multiple qtests with Postgre will not fail with "Database does not exist: default". It keeps docker up and running between tests. 
Changes to be able to run multiple Qtests with Postgre.
Without this change only one Qtest can be run with Postgre.
No
No
Locally.
=> HIVE-28037: Run multiple Qtest with Postgres

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc4.q, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc4.q.out, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc7.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/TextDescTableFormatter.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/stats/HiveIncrementalRelMdRowCount.java, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_7.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_nulls.q.out, storage-api/src/java/org/apache/hadoop/hive/common/type/SnapshotContext.java
1. Two plans are generated for rebuilding materialized view: incremental and full rebuild plan. The compiler chooses the cheaper plan based on cost. Instead of all records in a non native source table (Iceberg) the table scan operators should return only the number of records appended since the last MV rebuild when calculating the cost of the incremental rebuild plan. 
2. Deprecate `HiveStorageHandler.hasAppendsOnly()` and use the new `getSnapShots()` method.
Improve cost based decision heuristic.
No, but changes in `EXPLAIN` output.
No.
```
mvn test -Dtest.output.overwrite -Dtest=TestIcebergCliDriver -Dqfile=mv_iceberg_orc.q,mv_iceberg_orc2.q,mv_iceberg_orc3.q,mv_iceberg_orc4.q,mv_iceberg_orc5.q,mv_iceberg_orc6.q,mv_iceberg_orc7.q,mv_iceberg_partitioned_orc.q,mv_iceberg_partitioned_orc2.q …
```
=> HIVE-28126: Use added record count in cost model when rebuilding materialized view stored by iceberg

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java, ql/pom.xml, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java, ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestTxnDbUtil.java
Move TestDbTxnManager2.checkLock to TestTxnDbUtil.checkLock
Described on jira.
No.
No.
Unit tests should pass.
=> HIVE-28036: Move checkLock method to TestTxnDbUtil

common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
At present, create basic tables such as orc/parquet with partition transform will succeed. However, we only support iceberg tables for partition transform now, so i think we need to throw a friendly exception if the table does not support partition transform, to avoid user misunderstanding that the basic tables have such ability.
We can throw friendly exception to client if the table does not support partition transform, such as the following exception:
```
0: jdbc:hive2://127.0.0.1:10000/default> create table customer(customer_id int,first_name string,last_name string) partitioned by spec(TRUNCATE(2, last_name)) stored as orc;
Error: Error while compiling statement: FAILED: SemanticException Partition transforms are only supported by Iceberg storage handler (state=42000,code=40000)
``` …
=> HIVE-28154: Throw friendly exception if the table does not support partition transform

shims/common/src/main/java/org/apache/hadoop/hive/io/HiveIOExceptionHandlerUtil.java
Logging improvements
Troubleshooting
No
No
on a cluster
=> HIVE-28133: Log the original exception in HiveIOExceptionHandlerUtil#handleRecordReaderException

iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc5.q, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc5.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/MaterializedViewASTBuilder.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/NativeAcidMaterializedViewASTBuilder.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/NonNativeAcidMaterializedViewASTBuilder.java
Incremental materialized view rebuild plan has a step when the AST built from the optimized Calcite plan is transformed to an AST which represents a multi insert statement when the MV definition has aggregate and no record were deleted from the source tables since the last rebuild. To update existing values in the MV one of the branches of the multi insert is writing delete delta another is writing insert delta files. In case of Iceberg source tables the one which writes the delete delta needs the old values from the MV. If the MV definition has aggregate functions which return value can be calculated from other projected expressions such columns are not projected from the MV in the incremental rebuild plan.
Example MV from `mv_iceberg_orc5.q`
```
create materialized view mat2 stored by …
```
=> HIVE-28127: Exception when rebuilding materialized view with calculated columns on iceberg sources

packaging/src/docker/Dockerfile, packaging/src/docker/docker-compose.yml
Fix docker quickstart issues when running Hive 3.1.3 on Mac M2
[HIVE-28199](https://issues.apache.org/jira/browse/HIVE-28199)
On Mac M2, `docker-compose up` for `HIVE_VERSION=3.1.3` gives the following errors
* `/home/hive/.beeline` directory issue
```
metastore    | *** schemaTool failed ***
metastore    | [
metastore    | WARN] Failed to create directory:
metastore    | /home/hive/.beeline
metastore    | No such file or directory
```
* Underscore in network name, from `/tmp/hive/hive.log` on `hiveserver2`:
```
2024-04-02T16:26:24,867 ERROR [main] utils.MetaStoreUtils: Got exception: java.net.URISyntaxException Illegal character in hostname at index 25: thrift://metastore.docker_default:9083
java.net.URISyntaxException: Illegal character in hostname at index 25: …
```
=> HIVE-28199: Fix docker issues with Hive 3.1.3 on Mac.

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
Cherry-pick #5129 to branch-4.0
=> HIVE-28121: Use direct SQL for transactional altering table parameter (#5129)

standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java
Cherry-pick https://github.com/apache/hive/pull/5129 to branch-3
=> HIVE-28121: Use direct SQL for transactional altering table parameter

beeline/src/test/org/apache/hive/beeline/TestBeelineArgParsing.java, packaging/src/docker/README.md, pom.xml, standalone-metastore/pom.xml
Upgrade Postgres to 42.5.6
Target Critical CVE-2024-1597
No
Yes
https://issues.apache.org/jira/secure/attachment/13068348/mvn_dependency_tree.txt
Locally Built relying on precommit tests
=> HIVE-28188:Upgrade Postgres to 42.7.3 to target CVE-2024-1597

common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/compaction/IcebergMajorQueryCompactor.java, iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_single_partition.q, iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_single_partition.q.out, itests/src/test/resources/testconfiguration.properties, ql/src/java/org/apache/hadoop/hive/ql/DriverUtils.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/PartitionUtils.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactOperation.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/service/CompactionExecutorFactory.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
Adding support for compacting a specific Iceberg partition
Until now it was possible to only compact whole the table at once. If a table is partitioned, it would compact all partitions. 
Now adding a new feature to compact a single specified partition.
Ability to compact Iceberg tables on partition level.
No
New q-test was added that compacts a partitioned table partition-by-partition.
=> HIVE-28077: Iceberg: Major QB Compaction on partition level

data/conf/hive-site.xml, data/conf/iceberg/llap/hive-site.xml, data/conf/iceberg/tez/hive-site.xml, data/conf/llap/hive-site.xml, data/conf/perf/tpcds30tb/tez/hive-site.xml, data/conf/tez/hive-site.xml, packaging/src/docker/conf/hive-site.xml
Change the value of hive.tez.exec.print.summary to true in some hive-site.xml files in the repo to have the tez summary printed for devs where it's applicable.
Because the output of that is quite useful.
No, because it is getting upgraded in hive-site.xml files that are used in case of tests.
Users in production have their config.
No.
Locally:
1. start StartMiniHS2Cluster
2. run queries on tez with beeline
```
CREATE EXTERNAL TABLE test_part(id int) PARTITIONED BY(dt string) STORED AS ORC;
INSERT INTO test_part values (1, '1');
```
3. A summary was printed
```
INFO  : Status: DAG finished successfully in 0.96 seconds
INFO  : DAG ID: dag_1713942599258_0001_4
INFO  :
INFO  : Query Execution Summary
INFO  : -------------------------------------------------------------------------------------- …
```
=> HIVE-28210: Print Tez summary by default in tests

itests/util/src/main/java/org/apache/hive/jdbc/miniHS2/MiniHS2.java
Use a different root folder in MiniHS2.
Describe on jira in detail, but TLDR SCRATCH_DIR makes much more sense to me.
No, MiniHS2 is a testing dev tool.
No.
Locally tested with MiniHS2.
=> HIVE-28212: MiniHS2: use a base folder which is more likely writable on the local FS

parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g, parser/src/java/org/apache/hadoop/hive/ql/parse/ReplClauseParser.g
Refactor HiveParser to split Replication Commands 
Reduce HiveParser size
No
No
Existing Tests
=> HIVE-28226: Split Replication Commands from HiveParser.g.

ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFLower.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFUpper.java, ql/src/test/queries/clientpositive/stats_uppper_lower.q, ql/src/test/results/clientpositive/llap/groupby_grouping_sets_pushdown1.q.out, ql/src/test/results/clientpositive/llap/reduce_deduplicate_extended.q.out, ql/src/test/results/clientpositive/llap/stats_uppper_lower.q.out, ql/src/test/results/clientpositive/llap/vector_udf1.q.out, ql/src/test/results/clientpositive/llap/vectorized_string_funcs.q.out, ql/src/test/results/clientpositive/nonmr_fetch.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query24.q.out
This patch preserves column stats when applying UDF `upper`/`lower` on a column.
Current Hive re-estimates column stats when it encounters UDF. UDF `upper` and `lower` do not change column stats, but current Hive resets `avgColLen` to `hive.stats.max.variable.length`. Keeping the input data's column stats, including `avgColLen`,  will give more accurate stats to later query optimizers and make a better query plan.
No
No
Added a qfile for testing column stats computation on upper/lower UDF. Current Hive chooses MergeJoin due to column stats over-estimation, while this patch chooses MapJoin.
=> HIVE-28196: Preserve column stats when applying UDF upper/lower

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java, metastore/src/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java, metastore/src/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, metastore/src/java/org/apache/hadoop/hive/metastore/ObjectStore.java, metastore/src/java/org/apache/hadoop/hive/metastore/RawStore.java, metastore/src/java/org/apache/hadoop/hive/metastore/hbase/HBaseStore.java, metastore/src/test/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java, metastore/src/test/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java, metastore/src/test/org/apache/hadoop/hive/metastore/client/TestTablesCreateDropAlterTruncate.java, metastore/src/test/org/apache/hadoop/hive/metastore/minihms/AbstractMetaStoreService.java
Port https://github.com/apache/hive/pull/5129 to branch-2.3
This is a follow-up of HIVE-26882, including correctness fixes for some RDBMS.
No
No
UT
=> HIVE-28121. (2.3) Use direct SQL for transactional altering table parameter

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
Change the description of HIVE_OPTIMIZE_METADATA_DELETE config.
Misleading description
No
No
Existing QTests are sufficient
=> HIVE-28227: Change the description of HIVE_OPTIMIZE_METADATA_DELETE config

ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
This PR backports HIVE-20016(https://github.com/apache/hive/commit/3b6d4e279f717ae82a159b33fc858996bf3a3b53) to branch-2.3
It affects Spark usage.
```
Caused by: org.apache.hadoop.hive.ql.metadata.HiveException: Exception when loading 21 in table ****** with loadPath=hdfs://easyops-cluster/user/*****/hive_db/*****.db/ext  /******/.hive-staging_hive_2024-04-30_00-04-48_039_7446411615823654903-1/-ext-10000
at org.apache.hadoop.hive.ql.metadata.Hive.loadDynamicPartitions(Hive.java:1970)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at …
```
=> HIVE-20016: (2.3) Concurrency issue on SessionState setupAuth

iceberg/iceberg-handler/src/test/queries/positive/delete_iceberg_copy_on_write_unpartitioned.q, iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_copy_on_write_unpartitioned.q.out, ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/CopyOnWriteDeleteRewriter.java
Fix delete on entire iceberg table with COW mode, with truncate disabled
To avoid NPE & make the command work
Yes, instead of NPE, the query succeeds
No
UT
=> HIVE-28225: Iceberg: Delete on entire table fails on COW mode.

pom.xml, standalone-metastore/pom.xml, storage-api/pom.xml
Set the necessary properties in the pom file to generate an appropriate Copyright timespan (used by maven-remote-resources-plugin).
The generated META-INF/NOTICE file which resides inside each jar produced by Hive has incorrect copyright years.
Inside all jars the NOTICE file has the following incorrect content:
```
Copyright 2020 The Apache Software Foundation
```
The Copyright statement should include the timespan from the inception of the project to now.
```
Copyright 2008-2024 The Apache Software Foundation
```
The problem can be easily seen by inspecting the jar content after building any module or checking the previously published jars in Maven central.
No
No
Inspecting various jars before/after the changes
```
mvn clean install -DskipTests -pl common/
jar xf …
```
=> HIVE-28161: Incorrect Copyright years in META-INF/NOTICE files

hplsql/src/main/java/org/apache/hive/hplsql/Exec.java, itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java, service/src/java/org/apache/hive/service/cli/operation/ExecuteStatementOperation.java
HIVE-28214: HPLSQL not using the hive variables passed through beeline using --hivevar option
Hive variables passed using --hivevar option through beeline are not getting used in HPLSQL procedures/cursors. So changed code in such a way that they uses the hive variables passed through beeline.
To support hive variables passed through the beeline in HPLSQL.
No
No
=> HIVE-28214: HPLSQL not using the hive variables passed through beeline using --hivevar option

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Allow delegation for HiveMetaStore connections
The log message indicates that `HADOOP_PROXY_USER` is set, but then doesn't allow its use by calling `getRealUser()` which will be `null`.  This change allows delegation for HiveMetaStore connections by using either the real user or self.  The code for this is coming from Hadoop 3.3.6.
Allows proxying instead of throwing an exception.
No
Local builds which have removed `getRealUser()` to allow the use of delegation work as expected.  Running the existing code always fail because `getRealUser()` will always return `null`.
=> HIVE-28209: Allow the use of a proxy user

ql/pom.xml
The hive-exec-core jar is used by spark, oozie, hudi and many other pojects. Removal of the hive-exec-core jar has caused the following issues. 
Spark : https://lists.apache.org/list?dev@hive.apache.org:lte=1M:joda 
Oozie: https://lists.apache.org/thread/yld75ltf9y8d9q3cow3xqlg0fqyj6mkg 
Hudi: https://github.com/apache/hudi/issues/8147 
Until the we  shade & relocate dependencies in hive-exec, we should restore the hive-exec core jar .
=> HIVE-28211: Restore hive-exec-core jar

hplsql/src/main/java/org/apache/hive/hplsql/Exec.java, itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
HIVE-28215: Signalling CONDITION HANDLER is not working in HPLSQL.
Currently the CONDITION HANDLERs defined by user are not getting invoked when the signal is given to the corresponding condition. As a part of processing exception/error handling conditions, user defined conditions also processed (just looging into the log file) so when it has to invoke user defined condition handlers there are no condition handlers in the stack.
To fix the issue of invoking user defined condition handlers properly.
No
No
=> HIVE-28215: Signalling CONDITION HANDLER is not working in HPLSQL.

itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java, service/src/java/org/apache/hive/service/cli/operation/hplsql/HplSqlQueryExecutor.java
HIVE-28247: Execute immediate `select count(*) from tbl` throwing ClassCastException in hplsql mode.
select count(*) query returns a long value but hplsql is expecting a string type value as result ClassCastException is coming. If expected type is String then converting result value to string and returning now.
To support select count(*) query using execute immediate statement.
No
No
=> HIVE-28247: Execute immediate `select count(*) from tbl` throwing ClassCastException in hplsql mode.

itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestMetaStoreLimitPartitionRequest.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java, standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/BenchmarkUtils.java, standalone-metastore/metastore-tools/metastore-benchmarks/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSBenchmarks.java
When `hive.metastore.limit.partition.request` is configured, HMS would get the matched partition counts before getting the real partition objects. The count operation could be a slow query if the input filter or expr is too complex, and such slow filter will be executed twice.
We can make an improvement by the new steps:
1. get matched partition names firstly, 
2. then check limit through the size of partition names,
3.  finally get the partitions by the partition names.
To reduce the slow filter execute times.
No.
No.
Add unit test and benchmark test.
```bash
java -jar hmsbench.jar -H localhost --savedata /tmp/benchdata --sanitize -N 100 -N 10000 -o bench_results.csv -C -d testbench_http --params=100 -M 'getPartitionsByFilter.*'
```
- Before this patch
```bash
Operation       Mean    Med …
```
=> HIVE-28200: Improve get_partitions_by_filter/expr when partition limit enabled

hplsql/src/main/antlr4/org/apache/hive/hplsql/Hplsql.g4, hplsql/src/main/java/org/apache/hive/hplsql/Exec.java, itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
HIVE-28253: Unable to set the value for hplsql.onerror in hplsql mode.
As per current _Hplsql.g4_ grammar file SET command takes only identifier in which dot(.) is not allowed so SET hplsql.onerror won't work as per grammar file. So changed the grammar file to use qualified identifier to accept dot(.).
To change the hplsql.onerror value using SET for error handling in hplsql.
No
No
=> HIVE-28253: Unable to set the value for hplsql.onerror in hplsql mode.

ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/CreateTableEvent.java
Correct the check to restore proper behaviour 
The check is wrong, the string needs to be compared using equals
Yes, the URI will be validated during create for managed table
No
👀
=> HIVE-28260: CreateTableEvent wrongly skips authorizing DFS_URI for managed table.

service/src/java/org/apache/hive/service/cli/session/HiveSessionImpl.java
Fix some StreamReader not set with UTF8，if we actually default charset not support Chinese chars such as latin and conf contain Chinese chars，it would not resolve success，so we need set it as utf8 in StreamReader，we can find all StreamReader with utf8 charset in other compute framework，such as Calcite、Hudi and so on.
HiveSessionImpl init ReaderStream set Charset with UTF-8
No
not need
=> Hive-28251: HiveSessionImpl init ReaderStream set Charset with UTF-8

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestListPartitions.java
Fix the bug on `HMSHandler#checkLimitNumberOfPartitions`:
1. use maxParts to determine if need check partition limit
2. remove maxParts on `checkLimitNumberOfPartitions`
Fix the bug, assume that HMS configure `metastore.limit.partition.request` as 100, the client calls `get_partitions_by_filter` with maxParts as 101, and the matching partition number is 50, in this case the HMS server should not throw `MetaException` by partition limit check.
No.
No.
Fix some unit tests.
=> HIVE-28239: Fix bug on HMSHandler#checkLimitNumberOfPartitions

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdatePart.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
Fix DirectSql for AlterPartitions for some DB
To fix directSql for alter partions
No
No
Checked Logs to see no direct sql related exception where they were present earlier
=> HIVE-28271: DirectSql fails for AlterPartitions.

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java
In `HMSHandler#drop_database_core`, it needs to collect all partition paths that were not in the subdirectory of the table path, but now it only fetch the last batch of paths.
1. Collect all customized partition paths while dropping tables.
2. Add a unit test to cover this case.
Fix the bug, otherwise some partition paths that were not in the subdirectory of table path would not be deleted correctly.
No.
No.
Add a unit test:
```bash
mvn test -Dtest.groups= -Dtest=org.apache.hadoop.hive.metastore.TestRemoteHiveMetaStore#testDropDatabase -pl :hive-standalone-metastore-server
```
=> HIVE-28270: Fix missing partition paths bug on drop_database

ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLTask.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/show/ShowPartitionsOperation.java
SHOW PARTITIONS command implemented on a  non partitioned table should just throw execution error instead of full stack trace.
It is an improvement to already existing flow where a huge stack trace is shown to user wherein only a small prompt is useful.
Yes,
Earlier: 
This PR proposes the following change:
Is the change a dependency upgrade?
No
Manual tests.
After making the necessary changes, we build hive again, and then ran some manual commands to make sure hive is working as expected as well as the required change is working fine.
=> HIVE-26926: SHOW PARTITIONS for a non partitioned table should just throw execution error instead of full stack trace.

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
[HIVE-28250](https://issues.apache.org/jira/browse/HIVE-28250): Refer the JIRA for error message
For easier debugging tez jobs in cluster. **_tez.task-specific_** configs are used for debugging/profiling a particular vertex but we cannot set them at session level. 
NO
NO
On local machine (single node setup)
=> HIVE-28250: Add tez.task-specific configs into whitelist to modify at session level

ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFLower.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFUpper.java, ql/src/test/queries/clientpositive/stats_uppper_lower.q, ql/src/test/results/clientpositive/llap/groupby_grouping_sets_pushdown1.q.out, ql/src/test/results/clientpositive/llap/reduce_deduplicate_extended.q.out, ql/src/test/results/clientpositive/llap/stats_uppper_lower.q.out, ql/src/test/results/clientpositive/llap/vector_udf1.q.out, ql/src/test/results/clientpositive/llap/vectorized_string_funcs.q.out, ql/src/test/results/clientpositive/nonmr_fetch.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query24.q.out
Cherry-pick https://github.com/apache/hive/pull/5191 to branch-4.0
=> HIVE-28196: Preserve column stats when applying UDF upper/lower (branch-4.0)

iceberg/iceberg-handler/src/test/queries/positive/merge_iceberg_copy_on_write_unpartitioned.q, iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_unpartitioned.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/constraint/ConstraintsUtils.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveUtils.java, ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/CopyOnWriteMergeRewriter.java, ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/MergeRewriter.java, ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/MergeStatement.java
Hive rewrites merge statements to insert overwrite statements. When the target table is Iceberg with table property
```
'write.merge.mode'='copy-on-write'
```
The rewrite of
```
explain
merge into target_ice as t using source src ON t.a = src.a
when matched and t.a > 100 THEN DELETE
when not matched then insert (a, b) values (src.a, concat(src.b, '-merge new 2'));
```
should be
```
WITH `src` AS ( SELECT * FROM
(SELECT `PARTITION__SPEC__ID` AS `t__PARTITION__SPEC__ID`,`PARTITION__HASH` AS `t__PARTITION__HASH`,`FILE__PATH` AS `t__FILE__PATH`,`ROW__POSITION` AS `t__ROW__POSITION`,`a` AS `t__a`, `b` AS `t__b`, `c` AS `t__c` FROM `default`.`target_ice`) `t`
FULL OUTER JOIN
`default`.`source` `src`
ON `t__a` = `src`.`a`
),
t AS (
select …
```
=> HIVE-28282: Merging into iceberg table fails with copy on write when values clause has a function call

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
I have noticed that if a iceberg table has lots of metadata/data files, iceberg will use many system cores to do scan planning, which may put some pressure on Tez AM memory/cpu.
We can try to make the thread pool size configurable, to avoid concurrency pressure on Tez AM.
Other OSS also did similar optimization, like FIink:
https://github.com/apache/iceberg/blob/cbb853073e681b4075d7c8707610dceecbee3a82/flink/v1.18/flink/src/main/java/org/apache/iceberg/flink/source/FlinkInputFormat.java#L92-L100
This can configure the icbeberg planning thread size, to reduce Tez AM memory/cpu pressure as well as reduce some pressure on operating system.
If we don't limit the thread pool size, it wii use a default value which is equal system cores when doing `scan.planTasks()`:, …
=> HIVE-28276: Iceberg:Make Iceberg split threads configurable when table scanning

ql/src/java/org/apache/hadoop/hive/ql/exec/ColumnStatsUpdateTask.java
Remove invalid long datatype in ColumnStatsUpdateTask::constructColumnStatsFromInput
IMO, Hive column does not support long data type. We should remove the incorrect data type in ColumnStatsUpdateTask.
https://github.com/apache/hive/blob/a348e5d86adc611e4f72d386815a21a96b667ab4/ql/src/java/org/apache/hadoop/hive/ql/exec/ColumnStatsUpdateTask.java#L104-L106
In addition, the column stats related code blocks should be consistent with code in StatObjectConverter.java, which also does not have long type.
https://github.com/apache/hive/blob/a348e5d86adc611e4f72d386815a21a96b667ab4/standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/StatObjectConverter.java#L378-L379
No
No
Existing UTs
=> HIVE-28091: Remove invalid long datatype in ColumnStatsUpdateTask

standalone-metastore/pom.xml, storage-api/pom.xml
-Pdist profile present in parent pom.xml doesn't come into effect for storage-api module and standalone-metastore module.
Publish SBOM for standalone-metastore and storage-api module
NO
NO
Tested via my local .m2 repository cache. After the fix, it is creating the "-cyclonedx.json" and "-cyclonedx.xml" for storage-api and standalone-metastore.
=> HIVE-28244: Add SBOM for storage-api and standalone-metastore modules

data/files/header_footer_table_4/0003.txt, ql/src/java/org/apache/hadoop/hive/ql/io/SkippingTextInputFormat.java, ql/src/test/queries/clientpositive/file_with_delimiter.q, ql/src/test/results/clientpositive/llap/file_with_delimiter.q.out
Added support for custom delimiter in SkippingTextInputFormat. The "Select count(*) from table" query does not return correct output when data file contains "row level delimiters". This PR fixes this problem.
Bug fix
No
No
Qtest
=> HIVE-27498: Support custom delimiter in SkippingTextInputFormat

common/src/java/org/apache/hive/http/ProfileServlet.java
Added HTML format support to ProfileServlet.
Because HTML is the default format for creating flamegraphs.
No, profile servlet is more like a dev tool.
No.
set web port for hs2 in hive-site.xml
```
+<property>
+  <name>hive.server2.webui.port</name>
+  <value>10003</value>
+</property>
```
```
#tried with both 2.9 and 3.0
export ASYNC_PROFILER_HOME=/Users/laszlobodor/Downloads/async-profiler-2.9-macos
export ASYNC_PROFILER_HOME=/Users/laszlobodor/Downloads/async-profiler-3.0-macos
mvn install -Dtest=StartMiniHS2Cluster -DminiHS2.clusterType=llap -DminiHS2.conf="target/testconf/llap/hive-site.xml"  -DminiHS2.run=true -DminiHS2.usePortsFromConf=true -Dpackaging.minimizeJar=false -T 1C -DskipShade -Dremoteresources.skip=true -Dmaven.javadoc.skip=true -Denforcer.skip=true -pl itests/hive-unit …
```
=> HIVE-28305: ProfileServlet: add html to output formats and prepare for profiler 3.0

ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java
Currently the filterTableMetas() method in the HiveMetastoreAuthorizer is a no-op. It returns the full set of tables that are passed into it. This prevents any filtering that is to be done.
This PR adds logic to be able to filter out the ones that the user does not have access to.
To enhance security in HMS.
No
No
Tested manually in a Ranger enabled environment.
=> HIVE-28286: Add filtering support for get_table_metas (Naveen Gangam)

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
This PR aims to fix Partition spec is incorrect in getPartitionsByFilter RPC.
`Warehouse.makePartName` throws an exception because value is null, causing getPartitionsByFilter call to fail.
```sql
select * from foo where d=''
```
```
2024-05-30T16:21:57,490 ERROR [Metastore-Handler-Pool: Thread-30] metastore.RetryingHMSHandler: MetaException(message:Partition spec is incorrect. {d=})
at org.apache.hadoop.hive.metastore.Warehouse.makePartNameUtil(Warehouse.java:590)
at org.apache.hadoop.hive.metastore.Warehouse.makePartName(Warehouse.java:620)
at org.apache.hadoop.hive.metastore.MetaStoreDirectSql$PartitionFilterGenerator.visit(MetaStoreDirectSql.java:1557)
at org.apache.hadoop.hive.metastore.parser.ExpressionTree$LeafNode.accept(ExpressionTree.java:255)
at …
```
=> HIVE-28291: Fix Partition spec is incorrect in getPartitionsByFilter RPC

ql/src/java/org/apache/hadoop/hive/ql/Driver.java, ql/src/java/org/apache/hadoop/hive/ql/DriverContext.java, ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DummyTxnManager.java, ql/src/test/org/apache/hadoop/hive/ql/TestDriver.java
Store the query error message in a variable in DriverContext.
Because a simple failure reason message should be available for later analysis or query-tracking purposes.
No.
No.
New unit test class with related methods is included: TestDriver.
=> HIVE-28312: Save query error message on Driver level

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/RenderStrategy.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/TezJobMonitor.java
Fixed an issue where the `Task Execution Summary` duration is not displayed.
`Task Execution Summary` duration is not displayed and 0 is always displayed.
No
Confirmed that `Task Execution Summary` duration is displayed after run.
=> HIVE-28309: fixed Task Execution Summary duration is not displayed

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/queries/positive/show_create_iceberg_table.q, iceberg/iceberg-handler/src/test/results/positive/show_create_iceberg_table.q.out, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
Better interpretability with other engines
To make iceberg table readable from Hive, created by engines with hive engine disabled (which is by default in iceberg)
Iceberg tables would be readable from Hive irrespective if the other engine sets the correct the SerDe or StorageHandler
No
UT
=> HIVE-28323: Iceberg: Allow reading tables irrespective whether they were created with hive engined enabled or not.

common/src/java/org/apache/hadoop/hive/conf/Constants.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/miniHS2/StartMiniHS2Cluster.java, llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapDaemon.java, pom.xml, ql/src/java/org/apache/hadoop/hive/ql/ServiceContext.java, ql/src/test/org/apache/hadoop/hive/ql/TestServiceContext.java, service/src/java/org/apache/hive/service/server/HiveServer2.java
Introduce logic for parsing a specific cluster id in hive, that can be used by the environment. 
Hive doesn't have any control over how its environment (kubernetes, yarn, onprem, cloud, whatever) identifies a specific hive compute instance.
No. This env/cli property is optional to use, hive takes care of putting it into the conf (hive.cluster.id) if found.
No.
1. test class for ServiceContext
2. with mini hs2 cluster:
```
mvn install -Dtest=StartMiniHS2Cluster -DminiHS2.clusterType=llap -DminiHS2.conf="target/testconf/llap/hive-site.xml"  -DminiHS2.run=true -DminiHS2.usePortsFromConf=true -Dpackaging.minimizeJar=false -T 1C -DskipShade -Dremoteresources.skip=true -Dmaven.javadoc.skip=true -Denforcer.skip=true -pl itests/hive-unit -Pitests -nsu -Dhive.cluster.id=hello-cluster
#connected …
```
=> HIVE-28324: HIVE_CLUSTER_ID in env: unified way to mark a cluster

ql/src/java/org/apache/hadoop/hive/ql/udf/UDFHex.java, ql/src/test/results/clientpositive/llap/udf_hex.q.out
Fix a typo in the example output of UDFHex
doc fix
no
no
I test this with 4.0.0
```
docker exec -it hiveserver2 beeline -u 'jdbc:hive2://localhost:10000/'  -e "select hex(17)"
+------+
| _c0  |
+------+
| 11   |
+------+
```
=> HIVE-28330: Fix a typo in the example output of UDFHex

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/FilesForCommit.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergMergeTaskProperties.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapred/AbstractMapredIcebergRecordReader.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapred/MapredIcebergInputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/AbstractIcebergRecordReader.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergMergeRecordReader.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergMergeSplit.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergRecordReader.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergSplitContainer.java, ql/src/java/org/apache/hadoop/hive/ql/io/CombineHiveInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/CombineHiveRecordReader.java, ql/src/java/org/apache/hadoop/hive/ql/plan/ConditionalResolverMergeFiles.java, ql/src/java/org/apache/hadoop/hive/ql/plan/MapWork.java, ql/src/java/org/apache/hadoop/hive/ql/plan/MergeTaskProperties.java
Use Iceberg semantics for Merge task
To use Iceberg readers and writers for merge task. 
No
No
Existing tests - iceberg_merge_files.q is present.
=> HIVE-28258: Use Iceberg semantics for Merge task

common/src/java/org/apache/hadoop/hive/conf/Constants.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
In the current show partitions implementation, we need to fetch all columns data(11 columns), but in fact we only need two columns data, `partition `& `spec_id`.
https://github.com/apache/hive/blob/45867be6cb5308566e4cf16c7b4cf8081085b58c/common/src/java/org/apache/hadoop/hive/conf/Constants.java#L108-L110
We can only fetch the two columns through column project, and this can improve the performance in case of big iceberg partition table.
This change can make the `show partitions` more faster.
No
No
Existing Tests.
=> HIVE-28299: Iceberg: Optimize show partitions through column projection

ql/src/java/org/apache/hadoop/hive/ql/ServiceContext.java
Backward-compatible null safe default value for cluster id.
To prevent issues like below:
```
2024-06-18T20:37:43,031  WARN [main] server.HiveServer2: Error starting HiveServer2 on attempt 1, will retry in 60000ms
java.lang.IllegalArgumentException: The value of property hive.cluster.id must not be null
at com.google.common.base.Preconditions.checkArgument(Preconditions.java:217) ~[guava-28.2-jre.jar:?]
at org.apache.hadoop.conf.Configuration.set(Configuration.java:1421) ~[hadoop-common-3.1.1.7.2.18.0-641.jar:?]
at org.apache.hadoop.conf.Configuration.set(Configuration.java:1402) ~[hadoop-common-3.1.1.7.2.18.0-641.jar:?]
at org.apache.hadoop.hive.ql.ServiceContext.setClusterIdInConf(ServiceContext.java:50) ~[hive-exec-3.1.3000.2024.0.19.0-97.jar:3.1.3000.2024.0.19.0-97]
at …
```
=> HIVE-28324: HIVE_CLUSTER_ID in env: unified way to mark a cluster - addendum empty string default

kafka-handler/src/test/org/apache/hadoop/hive/kafka/TransactionalKafkaWriterTest.java
Disable stuck unit test.
To unblock precommit.
No.
No.
Locally, skipped.
=> HIVE-28348: TransactionalKafkaWriterTest hangs in precommit

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergSnapshotRefExec.java, iceberg/iceberg-handler/src/test/queries/positive/alter_table_create_tag.q, iceberg/iceberg-handler/src/test/results/positive/alter_table_create_tag.q.out, parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
Add support for 'If Not Exist' & 'Or Replace' Clause while creating an iceberg tag 
Better Usability
Yes, 'If Not Exists' & 'Or Replace' can be used while creating a Tag
No
UT
=> HIVE-28275: Iceberg: Add support for 'If Not Exists' and 'or Replace' for Create Tag.

itests/src/test/resources/testconfiguration.properties, ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/StageIDsRearranger.java, ql/src/test/results/clientpositive/llap/manyViewJoin.q.out
StageIDsRearranger now returns PhysicalContext instead of null.
The return value of a PhysicalResolver is passed to another PhysicalResolver. So returning null makes problem in the following PhysicalResolver.
No
No
Using manyViewJoin.q. Also I changed the test driver to TestMiniLlapLocalCliDriver, which becomes the default test driver since HIVE-23510.
=> HIVE-28326: Fix StageIDsRearranger

ql/src/java/org/apache/hadoop/hive/ql/exec/CommonJoinOperator.java, ql/src/test/queries/clientpositive/uniquejoin2.q, ql/src/test/results/clientpositive/llap/uniquejoin2.q.out
Change CommonJoinOperator's logic to treat a single dummy row as a null entry. The new logic is already used when it processes OuterJoin.
https://github.com/apache/hive/blob/e7de9164557e6029fd845b8da0f78a6021e965bb/ql/src/java/org/apache/hadoop/hive/ql/exec/CommonJoinOperator.java#L989-L996
https://github.com/apache/hive/blob/e7de9164557e6029fd845b8da0f78a6021e965bb/ql/src/java/org/apache/hadoop/hive/ql/exec/CommonJoinOperator.java#L856-L859
As HIVE-26018 explained, Hive on Tez produces incorrect results for UniqueJoin queries.
No
No
I added a new qfile and checked that both TestMiniLlapLocalCliDriver(Tez engine) and TestCliDriver(MR engine) produce the same result for it.
=> HIVE-26018: Produce the same result for UNIQUEJOIN regardless of execution engine

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestHiveMetaStoreClient.java
1. Revert [#1655](https://github.com/apache/hive/pull/1655).
2. Add a test class for `HiveMetaStoreClient` connections.
Bug fix, connection counts is used in remote metastore with `TTransport`, so we cannot decrease counts when transport is null.
No.
No.
New test class:
```bash
mvn test -Dtest.groups= -Dtest=org.apache.hadoop.hive.metastore.client.TestHiveMetaStoreClient  -pl :hive-standalone-metastore-server
```
=> HIVE-28338: Client connection count is not correct in HiveMetaStore#close

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInternalRecordWrapper.java, iceberg/iceberg-handler/src/test/queries/positive/iceberg_metadata_table.q, iceberg/iceberg-handler/src/test/results/positive/iceberg_metadata_table.q.out
Use the correct type while fetching Metadata Table, with tables having TIMESTAMP
To fix reading Metadata Tables where the main table has a column of TIMESTAMP type
Yes, If the tables of TIMESTAMP data type, then *FILES Metadata tables can be read
No
UT
=> HIVE-28353: Iceberg: Reading *Files Metadata table files if the column is of TIMESTAMP type.

ql/src/java/org/apache/hadoop/hive/ql/plan/ExprNodeGenericFuncDesc.java, ql/src/test/queries/clientpositive/prepare_plan_func_expr.q, ql/src/test/results/clientpositive/llap/prepare_plan_func_expr.q.out
Queries with function expression throw error as their ObjectInspector is not initialized. As part of prepare execute execute workflow, we serialize and deserialize plan during execute analyzer. During this step, ExprNodeGenericFuncDesc's ObjectInspector field is not initialized as it is a transient field and is never part of the serialized byte array. Assuming it can be null, we try to populate the field when required.
To make any queries with function expression work as part of the prepare execute workflow.
No
No
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=prepare_plan_func_expr.q
=> HIVE-28334 Support queries with function expression in the prepare execute workflow

itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestNegativeLlapCliDriver.java, itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliConfigs.java
Rename NegativeLlapCliDriver to NegativeLlapCliConfig
Wrong naming
No
No
=> HIVE-28354: Rename NegativeLlapCliDriver to NegativeLlapCliConfig

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
After HIVE-27725, I think we no need to update partitions stats when renaming table, as table name & db name are not in partition stats.
This change can speed up partitioned table rename operation in case of many partition stats stored in HMS.
This may also fix HIVE-27965.
No
No
Existing Tests.
=> HIVE-28372: No need to update partitions stats when renaming table

itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java, ql/src/java/org/apache/hadoop/hive/ql/parse/LoadSemanticAnalyzer.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnLoadData.java, ql/src/test/queries/clientnegative/load_data_partition.q, ql/src/test/queries/clientnegative/load_wrong_noof_part.q, ql/src/test/results/clientnegative/load_data_partition.q.out, ql/src/test/results/clientnegative/load_wrong_noof_part.q.out
Earlier, the code flows for partitioned and non-partitioned tables were different. The partitioned tables skipped constraints checks before submitting the job for execution. This Pull request ensures that both, the partitioned and non-partitioned tables go through the constraints validations in `applyConstraintsAndGetFiles` function.
For partitioned tables, while executing LOAD DATA/ LOAD DATA LOCAL commands, the check for file existence is not executed on HiveServer2, and this in turn throws `java.io.FileNotFoundException` during Runtime once the job is launched. 
This PR prevents such cases at compile time.
No
No
The test cases already exist. The error messages prompted back to the user are now consistent if the file is not found at HiveServer2
Load Data Error (Non Partitioned Tables) …
=> HIVE-27995: Fix inconsistent behavior of LOAD DATA command for partitoned and non-partitioned tables

itests/src/test/resources/testconfiguration.properties, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/TruncDateFromTimestamp.java, ql/src/test/results/clientpositive/llap/vector_udf_trunc.q.out
Do null-check and skip applying truncDate() if input is null.
Current TimeDateFromString throws NullPointerException due to the lack of null-check.
No
No
Using vector_udf_trunc.q. Also I changed the test driver to TestMiniLlapLocalCliDriver, which becomes the default test driver since  HIVE-23510.
=> HIVE-28327: Fix TruncDateFromTimestamp

jdbc/pom.xml, jdbc/src/java/org/apache/hive/jdbc/saml/IJdbcBrowserClient.java, llap-ext-client/pom.xml
Add classes/trim dependencies to/from the jdbc standalone jar
- Solve the missing classes
- Reduce the jar size from 98M to 42M
No
No
- Tested create/show/select/load queries, fetching the result;
- Tested DatabaseMetaData;
- Tested Kerberos & Delegation token & Simple authentication;
- Tested using ZK for service discovery;
- Inspected the classes inside the standalone jar.
=> HIVE-28315: Missing classes while using hive jdbc standalone jar

ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFMkCollectionEvaluator.java, ql/src/test/queries/clientpositive/udaf_collect_set_2.q, ql/src/test/results/clientpositive/llap/udaf_collect_set_2.q.out
UDAFs, collect_set and collect_list, won't work with complex types, if map-side aggregation is  disabled. This PR will fix this bug.
When users disable the map-side aggregation feature(`"hive.map.aggr`), collect_set doesn't work with complex types, such as struct.
No.
No.
Tested with qtest (TestMiniTezCliDriver)
=> HIVE-28347: Make a UDAF 'collect_set' work with complex types, even when map-side aggregation is disabled.

itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestAuthWithDigestMD5.java, itests/hive-unit-hadoop2/src/test/java/org/apache/hadoop/hive/metastore/security/TestHadoopAuthBridge23.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/security/TokenStoreDelegationTokenSecretManager.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/security/TestTokenStoreDelegationTokenSecretManager.java
Adding two changes to fix this issue:
1. Rework expiry thread to not remove token after renewal time has passed for that particular token. It will actually try to renew the token in this case.
2. Individual calls to retrievePassword during the TSaslClientTransport auth will also try to renew the token if required before retrieving the password.
Facing DigestMD5 token expiry issue in a session which has been open since a long time when a new new connection is opened to HMS using TSaslClientTransport with DigestMD5 based auth. This issue is happening due to the fact that the new connection is trying to authenticate using the token identifier which is removed by the expiry thread in the background.
No
No
Added a test case to check the expiry thread renewing the token automatically after some …
=> HIVE-28042: DigestMD5 token expired or does not exist issue while opening connection to HMS

itests/hive-blobstore/src/test/queries/clientpositive/having.q, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/java/org/apache/hadoop/hive/ql/parse/RowResolver.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/groupby_grouping_window.q, ql/src/test/queries/clientpositive/having.q, ql/src/test/queries/clientpositive/limit_pushdown_negative.q, ql/src/test/queries/clientpositive/prepare_plan.q, ql/src/test/queries/clientpositive/vector_groupby_grouping_window.q, ql/src/test/results/clientpositive/llap/groupby_grouping_window.q.out, ql/src/test/results/clientpositive/llap/having.q.out, ql/src/test/results/clientpositive/llap/prepare_plan.q.out, ql/src/test/results/clientpositive/llap/vector_groupby_grouping_window.q.out
Having clause CBO path of the queries should have visibility from the alias of the select expressions, as this is the case in the non-CBO path.
In order to make the CBO path and non-CBO work the same way in terms of syntax and semantics of having clause
No
No
Unit tests. Specifically mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=limit_pushdown_negative.q
=> HIVE-28321 Support select alias in the having clause for CBO

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ExprNodeConverter.java, ql/src/test/queries/clientpositive/filter_emptyliteral.q, ql/src/test/results/clientpositive/llap/filter_emptyliteral.q.out
An empty literal in the filter should still produce a valid RexNode.
Currently conversion from RexLiteral to ExprNode fail if the literal is an empty string. This causes the CBO to fail for such queries with this filter.
No
No
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=filter_emptyliteral.q
=> HIVE-28431 Fix RexLiteral to ExprNode conversion if the literal is an empty string

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/udf/GenericUDFIcebergBucket.java, iceberg/iceberg-handler/src/test/queries/positive/iceberg_insert_into_partition_transforms.q, iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_into_partition_transforms.q.out
Fix a bug in the iceberg_bucket UDF.
A bucket partition transform with DECIMAL doesn't correctly work when the source column type has extreme configurations. Simply, `GenericUDFIcebergBucket` always uses the default precision and scale regardless of the precise source type.
No
No
Update a qtest which fails in the current master
=> HIVE-28439: Iceberg: Bucket partition transform with DECIMAL can throw NPE

hcatalog/core/src/main/java/org/apache/hive/hcatalog/mapreduce/FosterStorageHandler.java
to unblock hcatloader parquet table project pushdown. HCatLoader sets the needed columns intending to be used for project/filter pushdown, however, org.apache.hadoop.hive.ql.io.parquet.read.DataWritableReadSupport#init ReadContext skips project/filter pushdown when job properties 'columns' is not set. This change sets the 'columns' property.
to unblock hcatloader parquet table project pushdown
No
No
tested locally
=> HIVE-28440: unblock hcatalog parquet project pushdown

ql/src/test/queries/clientpositive/sysdb.q, ql/src/test/results/clientpositive/llap/sysdb.q.out, standalone-metastore/metastore-server/src/main/sql/hive/hive-schema-4.0.0-alpha-2.hive.sql, standalone-metastore/metastore-server/src/main/sql/hive/hive-schema-4.0.0-beta-1.hive.sql, standalone-metastore/metastore-server/src/main/sql/hive/hive-schema-4.0.0.hive.sql, standalone-metastore/metastore-server/src/main/sql/hive/hive-schema-4.1.0.hive.sql, standalone-metastore/metastore-server/src/main/sql/hive/upgrade-4.0.0-alpha-1-to-4.0.0-alpha-2.hive.sql
Fixed syntax error in the sql
Select query on the table is failing post Hive initSchema / upgradeSchema.
no
no
Testcase scenario is added
=> HIVE-28436: Fix Incorrect syntax in Hive schema file for table MIN_HISTORY_LEVEL

pom.xml, ql/pom.xml, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/DbCPDataSourceProvider.java, standalone-metastore/pom.xml
Upgrade commons-dbcp2 and commons-pool2 to 2.12.0
To fix multiple CVEs and make commons-pool2 version consistent across complete project.
No
Yes
New dependency tree: 
[dpn.txt](https://github.com/user-attachments/files/16570391/dpn.txt)
Manually triggered some CRUD operations after dependency upgrade. Rest relying on precommit tests.
=> HIVE-28438: Remove commons-pool2 as an explicit dependency & upgrade commons-dbcp2 to 2.12.0

jdbc/src/java/org/apache/hive/jdbc/HiveBaseResultSet.java, jdbc/src/test/org/apache/hive/jdbc/TestHiveBaseResultSet.java
This PR proposes an implementation for the getClob(int) and getClob(String) methods of [HiveBaseResultSet](https://github.com/apache/hive/blob/fe2e17c3ad4773a4b1066ac525f7de2a86572eca/jdbc/src/java/org/apache/hive/jdbc/HiveBaseResultSet.java).
please see [HIVE-28358](https://issues.apache.org/jira/browse/HIVE-28358).
Yes. The current getClob() methods of HiveBaseResultSet just throw an exception. The proposed change returns a [SerialClob](https://docs.oracle.com/javase/8/docs/api/javax/sql/rowset/serial/SerialClob.html) already initialized with a char array obtained from the corresponding getString() methods.
No
Testing was done inside the "poorly designed application". Other additional tests were not deemed useful since the functionality is not present in the master release.
=> HIVE-28358: Enable JDBC getClob retrieval from String columns

jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java, jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java, jdbc/src/test/org/apache/hive/jdbc/TestHivePreparedStatement.java, jdbc/src/test/org/apache/hive/jdbc/TestHiveStatement.java
If the 4.x Hive Jdbc client connects to an older HS2 or other thrift implementations, it might throw the IllegalStateException: https://github.com/apache/hive/blob/master/jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java#L1253-L1258, as the remote might haven't set the property:  
hive.server2.thrift.resultset.default.fetch.size back to the response of OpenSession request. It also introduces the confusing on what the real fetch size the connection is, as we have both initFetchSize and defaultFetchSize in this HiveConnection, the HiveStatement checks the initFetchSize, defaultFetchSize and 
HIVE_SERVER2_THRIFT_RESULTSET_DEFAULT_FETCH_SIZE.defaultIntVal to obtain the real fetch size, we can make them one in HiveConnection, so every statement created from the connection uses this new …
=> HIVE-28399: Improve the fetch size in HiveConnection

iceberg/iceberg-catalog/pom.xml, iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveOperationsBase.java, iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/TestHelpers.java, iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveTableConcurrency.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestConflictingDataFiles.java, iceberg/pom.xml, pom.xml
Added a missing junit5 dependency. Refer to https://stackoverflow.com/questions/46360736/tests-not-running-through-maven
Maybe this issue was caused by the mixed use of junit4&junit5.
For example if i want to do a mvn test locally:
`mvn clean test -Dtest=TestHiveCommits  -pl iceberg/iceberg-catalog -Piceberg`
will print **Tests run: 0, Failures: 0, Errors: 0, Skipped: 0**, and acutually the test won't be ran.
No
No
Local mvn test in iceberg-catalog moudle
=> HIVE-28421: Iceberg: mvn test can not run UTs in iceberg-cacatlog

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/QueryProperties.java, ql/src/java/org/apache/hadoop/hive/ql/hooks/LineageLogger.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/Optimizer.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/SimpleFetchOptimizer.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/lineage/Generator.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/org/apache/hadoop/hive/ql/optimizer/lineage/TestGenerator.java, ql/src/test/queries/clientpositive/lineage6.q, ql/src/test/results/clientpositive/llap/lineage6.q.out
* Remove hardcoded Atlas HiveHook related filters from lineage information Generator and introduce an independent setting to filter based on statement/operation type.
* Add `isView` property to `QueryProperties` to indicate that this statement is a logical view creation.
Lineage information was not generated in case of create view operation. See jira for details: https://issues.apache.org/jira/browse/HIVE-28409
No.
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=lineage6.q -pl itests/qtest -Pitests
mvn test -Dtest=TestGenerator.java -pl ql
```
=> HIVE-28409: Column lineage when creating view is missing if atlas HiveHook is set

itests/src/test/resources/testconfiguration.properties, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/concatenate/AlterTableConcatenateOperation.java, ql/src/test/queries/clientpositive/list_bucket_dml_8.q, ql/src/test/results/clientpositive/llap/list_bucket_dml_8.q.out
Modify AlterTableConcatenateOperation to refer to MergeFileWork.getInputPaths().
When using a List Bucketing table, FileMergeOperator expects only 1 subdirectory as its input. To satisfy this requirement, AlterTableConcatenateOperation changes input paths by calling MergeFileWork.resolveConcatenateMerge(). But Hive-Tez does not properly propagate the changed input paths to SplitGenerator, which causes the problem
No
No
Using list_bucket_dml_8.q.
This PR changes the test driver for list_bucket_dml_8.q from TestCliDriver to TestMiniLlapLocalCliDriver, as all the other list_bucket_dml_*.q are already run by TestMiniLlapLocalCliDriver. Also MR specific config keys are replaced by corresponding Tez specific keys.
I changed the file format of table from RCFile to ORC because ORC is more popular …
=> HIVE-28300: Fix AlterTableConcatenate when using Hive-Tez

standalone-metastore/metastore-server/src/main/scripts/ext/schemaTool.sh
In a94c0306f48215d96be3b842525c4341772d26f9 `MetastoreSchemaTool` was moved from `org.apache.hadoop.hive.metastore.tools.MetastoreSchemaTool` to `org.apache.hadoop.hive.metastore.tools.schematool.MetastoreSchemaTool`, but it seems like `schemaTool.sh` was not updated.
This results in a `ClassNotFoundException: org.apache.hadoop.hive.metastore.tools.MetastoreSchemaTool`
Update outdated class reference to actual one.
Let `schemaTool.sh` work again :)
Yes, the shell script now works. See "How was this patch tested?" for the CLI output.
No
Before (fails)
```bash
/stackable/apache-hive-metastore-4.0.0-bin $ bin/base --service schemaTool
Exception in thread "main" java.lang.ClassNotFoundException: org.apache.hadoop.hive.metastore.tools.MetastoreSchemaTool
at …
```
=> HIVE-28487: Fix outdated MetastoreSchemaTool class reference in schemaTool.sh

pom.xml
The janino version is getting upgraded from 3.0.11 to 3.1.12
The changes are needed as the current version of Janino has several CVEs 
Vulnerabilities from dependencies:
[CVE-2021-36373](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-36373)
[CVE-2020-1945](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-1945)
[CVE-2020-15250](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2020-15250)
With the upgrade to 3.1.12, all the CVEs would be handled 
No
Yes
=> HIVE-28492: Upgrade Janino version to 3.1.12

ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java, ql/src/test/queries/clientpositive/sharedworkresidual_dpp.q, ql/src/test/results/clientpositive/llap/sharedworkresidual_dpp.q.out
Remove any residual unused operator tree that send DPP events to unknown operators produced as aprt of the operator merge in the SharedWorkOptimizer.
SharedWorkOptimizer leaves residual unused operator tree that send DPP events to unknown operators. These events when they later processed by the processAppMasterEvents fails to produce a physical operator tree.
No
No
cd itests/qtest
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=sharedworkresidual_dpp.q
=> HIVE-28484 SharedWorkOptimizer leaves residual unused operator tree that send DPP events to unknown operators

iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestOptimisticRetry.java, ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecuteOnWriteConflictPlugin.java
Don't fail when the retry strategy is write_conflict in case of a commit failure, but rather retry
To avoid query failures where multiple queries are running concurrently on the same table & writes on similar set of files
Yes, In case of concurrent queries with conflicting files, the query doesn't fail but rather retries. 
No
UT
=> HIVE-28515: Iceberg: Concurrent queries fail during commit with ValidationException.

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/Bug.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelOptUtil.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterProjectTSTransposeRule.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterProjectTransposeRule.java, ql/src/test/queries/clientpositive/subquery_nested_expressions.q, ql/src/test/results/clientpositive/llap/subquery_nested_expressions.q.out
Apply changes in [CALCITE-6513](https://issues.apache.org/jira/browse/CALCITE-6513) into `HiveFilterProjectTransposeRule`.
Applying the rule to nested project operators that contain nested expressions may cause OOM. Please see jira for details
[CALCITE-6513](https://issues.apache.org/jira/browse/CALCITE-6513)
[HIVE-28264](https://issues.apache.org/jira/browse/HIVE-28264)
No.
No.
```
mvn test -Dtest.output.overwrite -Dtest=TestMiniLlapLocalCliDriver -Dqfile=subquery_nested_expressions.q -pl itests/qtest -Pitests
```
=> HIVE-28264: OOM/slow compilation when query contains SELECT clauses with nested expressions

iceberg/checkstyle/checkstyle.xml, iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveClientPool.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java, iceberg/pom.xml
Upgrading maven maven-checkstyle-plugin to latest 3.5.0 and change checkstyle file & some class to adapt the higher version checkstyle rules.
See details HIVE-28514 & HIVE-28499.
BTW, the new CheckStyle version has some extra check rules. I have fixed them in this change.
```
[ERROR] hive/iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveClientPool.java:91:46: Unnecessary parentheses around expression. [UnnecessaryParentheses]
[ERROR] hive/iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java:1546: At-clause should have a non-empty description. [NonEmptyAtclauseDescription]
[ERROR] hive/iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java:1561: At-clause should have a non-empty …
```
=> HIVE-28514: Iceberg: Fix checkstyle file to adapt new checkstyle version

iceberg/iceberg-handler/pom.xml, iceberg/pom.xml, itests/qtest-iceberg/pom.xml, pom.xml, ql/pom.xml
[HIVE-28517](https://issues.apache.org/jira/browse/HIVE-28517)
Difference in roaringbit version in classpath can cause problem in runtime. In iceberg 1.5.2 (currently used), it has dependency on roaringbit 1.0.1 and in hive, we are packaging 0.9.22 version.
No
Yes
[dependency_tree.txt](https://github.com/user-attachments/files/16958281/dependency_tree.txt)
Will see CI outcome
=> HIVE-28517: Roaringbit version should be in sync with iceberg dependency required version

iceberg/iceberg-handler/src/test/results/negative/write_iceberg_branch_negative.q.out, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/authorization_insert_column.q, ql/src/test/results/clientpositive/llap/authorization_insert_column.q.out
**What changes were proposed in this pull request?**
Enhance the HivePrivilegeObject by incorporating detailed column-level information for insert
https://issues.apache.org/jira/browse/HIVE-28511
**Why are the changes needed?**
- Add column access info to HivePrivilegeObject to provide fine-grained access control and improved security
- enforce permissions at the column level during data insertion
**Does this PR introduce any user-facing change?**
No
**Is the change a dependency upgrade?**
No
**How was this patch tested?**
=> HIVE-28511: add column access information to HivePrivilegeObject

common/pom.xml, itests/hive-blobstore/pom.xml, itests/hive-jmh/pom.xml, itests/hive-unit/pom.xml, itests/qtest-accumulo/pom.xml, itests/qtest-iceberg/pom.xml, itests/qtest-kudu/pom.xml, itests/qtest/pom.xml, itests/util/pom.xml, llap-client/pom.xml, llap-common/pom.xml, llap-ext-client/pom.xml, llap-tez/pom.xml, pom.xml, ql/pom.xml, service/pom.xml, shims/0.23/pom.xml
Upgrade jersey to 1.19.4
[HIVE-28360](https://issues.apache.org/jira/browse/HIVE-28360)
After upgrading to Hadoop 3.3.5, the Hive WebHCat server fails to start because of inconsistent versions of the Jersey JAR package. Hive HCat lacks the jersey-server-1.19 jar.
None, that I am aware of.
CI
=> HIVE-28360: Upgrade jersey to 1.19.4

ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java, ql/src/test/results/clientpositive/llap/explainuser_2.q.out, ql/src/test/results/clientpositive/llap/vector_between_in.q.out, ql/src/test/results/clientpositive/llap/vectorized_timestamp.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query83.q.out
Make FilterStatsRule reduce the number of filtered rows by half when # of distinct values is empty.
https://issues.apache.org/jira/browse/HIVE-28363
Simply, `col IN (5)` makes the estimated amount half, `col IN (5, 10)` keeps 100% of stats, `col IN (5, 10, 15)` keeps 100% of stats, and so on. I expect `col IN ({arbitrary number of constants})` to filter out rows to some extent in almost all cases.
FilterStatsRule roughly estimates the number of rows filtered by IN to be `{Original # of rows} * {1 / cardinality} * {# of values in IN}`. The second term is estimated as 0.5 when column stats are unavailable. So, it always returns the original number when `IN` retains two constant values like `col IN (1, 3)`.
Maybe, FilterStatsRule had behaved in the same way as this PR before, but [this …
=> HIVE-28363: Improve heuristics of FilterStatsRule without column stats

common/src/java/org/apache/hadoop/hive/common/JvmMetrics.java, service/src/java/org/apache/hive/service/servlet/OTELExporter.java
Expose JVM level statistics of HiveServer2 via OTEL Exporter
Better Usability with OTEL
Yes, OTEL Collectors can be used to collect JVM level statistics
No
Manual
=> HIVE-28542: OTEL: Implement OTEL Exporter to expose JVM details of HiveServer2

itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/ConstantVectorExpression.java, ql/src/test/queries/clientpositive/chinese_utf8_characters.q, ql/src/test/results/clientpositive/llap/chinese_utf8_characters.q.out
=> HIVE-28544: Ensure using UTF-8 encoding in some String/Char/Varchar related operations

pom.xml, service/pom.xml, service/src/java/org/apache/hive/service/auth/ldap/LdapSearch.java, service/src/test/org/apache/hive/service/auth/ldap/TestLdapSearch.java, standalone-metastore/metastore-common/pom.xml, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/ldap/LdapSearch.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/ldap/TestLdapSearch.java, standalone-metastore/pom.xml
Change-Id: If2db478039cdfe87022b2f3b10ecf5de09dfcbe0
When user name has a comma in it, and it is not escaped properly by Hive when querying LDAP, the query failes.
For example if the given user DN is "user , name", the correct escaped LDAP query should contain: "user r\5c, name".
If connected to LDAP it requires that.
No.
No.
Unit tests.
=> HIVE-28540: Special characters in user DN escaped when querying LDAP

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
[HIVE-28543](https://issues.apache.org/jira/browse/HIVE-28543)
In iceberg table, post inserting the data into iceberg table, the _current-snapshot-id_ in _desc formatted_ output is different from the value stored in backend db (for examlpe: mysql)
NO
NO
On local setup
=> HIVE-28543: Previous snapshotId is stored in backend database for iceberg tables

ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecuteLostAMQueryPlugin.java, ql/src/test/org/apache/hadoop/hive/ql/reexec/TestReExecuteLostAMQueryPlugin.java
Change the pattern matcher to consume a pattern with line breaks.
Because the plugin didn't kick in if the message contains diagnostics which is separated from the original trigger message with line break
No.
No.
Unit test added.
=> HIVE-28569: ReExecuteLostAMQueryPlugin doesn't kick in if the message contains line break and diagnostics

iceberg/iceberg-handler/src/test/queries/positive/iceberg_rename.q, iceberg/iceberg-handler/src/test/results/positive/iceberg_rename.q.out, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetastoreDefaultTransformer.java
Avoid MetdataTransformer to modify the table location in case the translated table is an iceberg table
To make the aggregate query work post rename
Yes, count(*) on renamed iceberg tables work
No
UT
=> HIVE-28570: Iceberg: Aggregate queries on translated iceberg table fails post rename.

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
HIVE-28573: Unable to execute HPLSQl queries when hive authorization is enabled.
HplSqlQueryExecutor sets _QUERY_EXECUTOR_  value to _HPLSQL_ as a part of HPLSQL execution. When _hive.security.authorization.enabled_  hive configuration property is set to _true_, it allows only whitelisted hive configuration properties to modify but here _QUERY_EXECUTOR_ is not whitelisted so throwing error.
Adding _QUERY_EXECUTOR_ to the _hive.security.authorization.sqlstd.confwhitelist_ property so that it won't report the specified error.
To execute HPLSQL statements even _hive.security.authorization.enabled_  hive configuration property is set to _true_,.
No
No
Existing test cases should pass after enabling _hive.security.authorization.enabled_  hive configuration property.
=> HIVE-28573: Unable to execute HPLSQl queries when hive authorization is enabled.

iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_partition_evolution.q, iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_partition_evolution2.q, iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_partitioned.q, iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_unpartitioned.q, iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_unpartitioned_ordered.q, iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_partition_evolution.q.out, iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_partition_evolution2.q.out, iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_partitioned.q.out, iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_unpartitioned.q.out, iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_unpartitioned_ordered.q.out, itests/qtest-iceberg/src/test/java/org/apache/hadoop/hive/cli/TestIcebergLlapLocalCompactorCliDriver.java, parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g, parser/src/test/org/apache/hadoop/hive/ql/parse/TestParseOptimizeTable.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactOperation.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorUtil.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
Support for assigning manual compaction requests on custom compaction pools by using table property or db property `hive.compactor.worker.pool`.
On downstream environments sometimes a single HMS is used with several HS2s with enabled compaction workers, where some HS2s are running on Hive code versions that don't have Iceberg compaction functionality. It is needed to prevent these HS2s from attempting to process Iceberg compaction requests. This PR enables solving this problem using custom compaction pooling.
Yes, it adds the ability of compacting on custom compaction pool whose name is specified in a table property when processing manual compaction requests.
No
Updated q-tests
=> HIVE-28536: Iceberg: support for assigning manual compaction requests on custom compaction pools

common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java, iceberg/iceberg-handler/src/test/queries/negative/iceberg_major_compaction_with_non_partition_column_in_filter.q, iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_partition_evolution_w_id_spec_w_filter.q, iceberg/iceberg-handler/src/test/results/negative/iceberg_major_compaction_with_non_partition_column_in_filter.q.out, iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_partition_evolution_w_id_spec_w_filter.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/ppr/PartitionPruner.java, ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
Change-Id: Ic85efd70599413cdb96073c6cb50690fbc1c11b0
Limiting the columns in where clause in compaction to partition columns.
Currently Hive Iceberg compaction supports any columns in the WHERE clause predicate. However, compaction happens only on partition level. Performance can be improved if the columns in WHERE clause predicate will be limited to partition columns. 
Yes, user will get an exception if uses non partition columns in alter table compaction query.
No.
With qtest.
=> HIVE-28537: Iceberg: allow only partition columns in the WHERE clause

data/conf/hive-log4j2.properties, llap-server/pom.xml, llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/QueryTracker.java, llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/TestLlapDaemonLogging.java, pom.xml, standalone-metastore/metastore-server/pom.xml, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestMetaStoreServerUtils.java, standalone-metastore/pom.xml
- Bump Log4j2 to 2.24.1 to facilitate compilation of GraalVM Native Image. 
- This PR is aimed at ensuring that HiveServer2 JDBC Driver is compatible with future versions of LOG4J as much as possible. I created a unit test at https://github.com/linghengqian/log4j2-v2231-graalvm-native-image-test to prove that the HiveServer2 JDBC Driver using `apache/logging-log4j2:2.23.1` can be used under the GraalVM Native Image compiled by GraalVM CE For JDK 22.0.2.
```shell
sdk install java 8.0.422-tem
sdk install java 22.0.2-graalce
sdk use java 8.0.422-tem
sdk install maven
git clone git@github.com:linghengqian/hive.git -b log4j-bump
cd ./hive/
mvn clean install -DskipTests
mvn clean package -pl packaging -DskipTests -Pdocker
cd ../
git clone …
```
=> HIVE-28417: Bump Log4j2 to 2.24.1 to facilitate compilation of GraalVM Native Image

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java, iceberg/iceberg-handler/src/test/queries/positive/iceberg_stats.q, iceberg/iceberg-handler/src/test/results/positive/iceberg_stats.q.out, iceberg/iceberg-handler/src/test/results/positive/write_iceberg_branch.q.out, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveUtils.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/StatsOptimizer.java, ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java
At present, in case of  `iceberg.hive.keep.stats=true` & `hive.compute.query.using.stats=true`, HS2 will do a fetch task to get iceberg table's `numRows `property from HMS  to optimize `count `query.
If `iceberg.hive.keep.stats=false`, HS2 will always launch tez task to compute table's row count when filing a `count `query.
However, as we know, iceberg table's metadata has some stats information, we can also just start a fetch task to retrieve the row count from iceberg's snapshot summary when `iceberg.hive.keep.stats=false` or no stats stored in hms.  This can avoid launching tez task to compute the table's row count.
BTW, timetravel or branch/tag has different stats from current snapshot, so we need to get the specified snapshotid based on the different iceberg version. Otherwise, we …
=> HIVE-28268: Iceberg: Retrieve row count from iceberg SnapshotSummary in case of iceberg.hive.keep.stats=false

data/conf/hive-log4j2.properties, llap-server/pom.xml, llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/QueryTracker.java, llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/TestLlapDaemonLogging.java, pom.xml, standalone-metastore/metastore-server/pom.xml, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestMetaStoreServerUtils.java, standalone-metastore/pom.xml
Reverts apache/hive#5375
Try to resolve [HIVE-28611](https://issues.apache.org/jira/browse/HIVE-28611)
=> Revert "HIVE-28417: Bump Log4j2 to 2.24.1 to facilitate compilation of GraalVM Native Image"

.github/actions/spelling/expect.txt, serde/src/java/org/apache/hadoop/hive/serde2/OpenCSVSerde.java
This is a revised version of https://github.com/apache/hive/pull/3718 and includes only the applyQuotesToAll changes.  The other, OpenCSV changes were committed separately.
OpenCSV version 3.10 added an option called "applyQuotesToAll."  When set to false, output columns were not quoted unless they needed it. This commit adds support for that option in OpenCSVSerde.  This commit is based on a patch from Sungwoo Park <glapark@gmail.com>, which was originally based on a patch from David Engel <david@istwok.net>.
=> HIVE-20917: Support applyQuotesToAll option in OpenCSVSerde.

beeline/src/test/org/apache/hive/beeline/cli/TestHiveCli.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationMigrationTool.java, llap-server/pom.xml, pom.xml, ql/src/test/org/apache/hadoop/hive/ql/exec/TestGetPartitionAuthWithBatches.java, ql/src/test/org/apache/hadoop/hive/ql/exec/TestGetPartitionInBatches.java, ql/src/test/org/apache/hadoop/hive/ql/exec/TestMsckCreatePartitionsInBatches.java, ql/src/test/org/apache/hadoop/hive/ql/exec/TestMsckDropPartitionsInBatches.java, ql/src/test/org/apache/hadoop/hive/ql/hooks/TestHooks.java, ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveCopyFiles.java, ql/src/test/org/apache/hadoop/hive/ql/metadata/TestTempAcidTable.java, ql/src/test/org/apache/hadoop/hive/ql/parse/TestColumnAccess.java, ql/src/test/org/apache/hadoop/hive/ql/parse/TestQBCompact.java, ql/src/test/org/apache/hadoop/hive/ql/parse/TestQBJoinTreeApplyPredicate.java, ql/src/test/org/apache/hadoop/hive/ql/parse/TestQBSubQuery.java, ql/src/test/org/apache/hadoop/hive/ql/plan/TestReadEntityDirect.java, ql/src/test/org/apache/hadoop/hive/ql/plan/TestViewEntity.java, ql/src/test/org/apache/hadoop/hive/ql/processors/TestSetProcessor.java, ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHivePrivilegeObjectOwnerNameAndType.java, ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDTFGetSQLSchema.java, service/src/test/org/apache/hive/service/server/TestHS2HttpServerLDAP.java, standalone-metastore/pom.xml, storage-api/pom.xml
- Upgraded Maven SureFire Plugin to latest version 3.5.1
- Upgraded junit-jupiter-engine and junit.vintage.version to latest versions
- Fixed multiple test case failures post upgrading Maven SureFire Plugin
- Currently in master branch, all testcases are not running in the pipeline and getting unnoticed because of lower maven surefire plugin. Current report is mentioned below
**Test Result - 0 failures , 2,364 skipped Passed- 49,317 tests**
- Many test cases are failing in BeforeClass post [HIVE-27972](https://issues.apache.org/jira/browse/HIVE-27972) and are getting skipped, instead of failing because of lower Maven surefire plugin. Testcases failures are due to incorrect hive configuration settings when running with Tez.
1. To ensure all test cases are executed correctly.
2. To leverage …
=> HIVE-28519: Upgrade Maven SureFire Plugin to latest version 3.5.1

serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/ObjectInspectorUtils.java
Sorting the fields in function `getDeclaredNonStaticFields()` in ObjectInspectorUtils.java class in order to make the function deterministic. The below flaky tests will be fixed by this.
Multiple flaky tests were detected in _serde_ module while trying to run the tests using the nondex tool. [NonDex](https://github.com/TestingResearchIllinois/NonDex) is a tool for detecting and debugging wrong assumptions on under-determined Java APIs. 
```
mvn install -pl serde -DskipTests
mvn -pl serde test -Dtest=org.apache.hadoop.hive.serde2.objectinspector.TestProtocolBuffersObjectInspectors#testProtocolBuffersObjectInspectors
mvn -pl serde edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=org.apache.hadoop.hive.serde2.objectinspector.TestProtocolBuffersObjectInspectors#testProtocolBuffersObjectIns …
```
=> HIVE-28603 Fixing Multiple Flaky tests in module serde which are due to non determinism

llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/LlapRecordReaderUtils.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/OrcEncodedDataReader.java, llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestIncrementalObjectSizeEstimator.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/encoded/EncodedReader.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/encoded/LlapDataReader.java
OrcEncodedDataReader fully owns the OrcReader instance it creates, so it should be closed there too
It causes connection leaks in case of FileSystems like S3 (where an HTTP connection pool is utilized)
No.
No.
Tested on cluster.
=> HIVE-28616: OrcReader is not closed in OrcEncodedDataReader

itests/hive-unit/src/test/java/org/apache/hive/service/cli/thrift/TestThriftCLIServiceWithAllAndBinary.java, itests/hive-unit/src/test/java/org/apache/hive/service/cli/thrift/TestThriftCLIServiceWithAllAndHttp.java, itests/hive-unit/src/test/java/org/apache/hive/service/cli/thrift/TestThriftCLIServiceWithBinary.java, itests/hive-unit/src/test/java/org/apache/hive/service/cli/thrift/TestThriftCLIServiceWithHttp.java, itests/hive-unit/src/test/java/org/apache/hive/service/cli/thrift/TestThriftCliServiceMessageSize.java, itests/hive-unit/src/test/java/org/apache/hive/service/cli/thrift/TestThriftHttpCLIServiceFeatures.java, service/src/test/org/apache/hive/service/cli/TestRetryingThriftCLIServiceClient.java, service/src/test/org/apache/hive/service/cli/thrift/AbstractThriftCLITest.java, service/src/test/org/apache/hive/service/cli/thrift/ThriftCLIServiceTest.java, service/src/test/org/apache/hive/service/server/TestHS2HttpServer.java
Hive thrift port was hardcoded to 15000, hence port regeneration code was added here
Testcase can fail if the port is occupied by another test in testsplit pipeline
No
No
Local machine
=> HIVE-28194: Regenerate HS2 thrift port in TestRetryingThriftCLIServiceClient

ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java, ql/src/test/queries/clientpositive/sharedwork_dpp_removal_hive_28490.q, ql/src/test/results/clientpositive/llap/sharedwork_dpp_removal_hive_28490.q.out
This patch changes the implementation of SharedWorkOptimizer#findAscendantWorkOperators. For a given operator, original findAscendantWorkOperators() returns a set of operators that belongs to ancestor vertices of the vertex that given operator belongs to. Therefore, some operators that are irrelevant to the given operator also belong to the resultant set, which leads to wrong DPP source removal. The new implementation returns a set of ancestor operators of the given operator.
Please check out the slides attached in the JIRA page (HIVE-28490) for further explanations.
In order to prevent the removal of retainable DPP sources that are still useful in runtime.
No
No
We tested this patch by running all TPC-DS queries in cluster. This patch contains a qfile test that reproduces the wrong DPP …
=> HIVE-28490: Stop removing retainable DPP sources

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/GroupingSetOptimizer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/TezCompiler.java, ql/src/test/queries/clientpositive/groupingset_optimize_hive_28489.q, ql/src/test/results/clientpositive/llap/groupingset_optimize_hive_28489.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query22.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query67.q.out
This patch introduces a new optimization for GroupBy with GroupingSet. GroupingSet often emits too much rows and becomes a bottleneck of query execution. The proposed optimization tries mitigating this situation by reducing the cardinality of GroupBy key. For the detailed explanation, please checkout the slides attached in the JIRA page (HIVE-28489).
This patch introduces a new configuration key: `hive.optimize.grouping.set.threshold`. The default value of 1,000,000,000 is chosen because it showed best performance in 10TB TPC-DS experiment. Setting this value to negative number disables the optimization.
To improve query execution time of GroupBy with GroupingSet.
No
No
We tested this patch using 10TB TPC-DS experiment. This patch contains a qfile test to verify optimized query plan.
=> HIVE-28489: Partition the input data of GroupBy with GroupingSet

iceberg/iceberg-handler/src/test/queries/positive/iceberg_metadata_table.q, iceberg/iceberg-handler/src/test/queries/positive/show_create_iceberg_table.q, iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_merge_mixed.q, iceberg/iceberg-handler/src/test/results/positive/iceberg_metadata_table.q.out, iceberg/iceberg-handler/src/test/results/positive/show_create_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_merge_mixed.q.out, pom.xml
https://github.com/apache/parquet-java/pull/3041/files fixed a bug related to data loss. We should upgrade the latest parquet version to avoid this issue.
btw, Iceberg also revert the low version 1.13.1 & upgrade to 1.14.4 to fix the issue.  https://github.com/apache/iceberg/pull/11462/files
BTW, Parquet 1.14 has added the Hadoop Vectored IO feature in https://issues.apache.org/jira/browse/PARQUET-2171, so i think we can use this good feature after the upgrading. :)
No
see the file [mvndep.log](https://github.com/user-attachments/files/17823381/mvndep.log)
The existing tests
=> HIVE-28625: Upgrade Apache Parquet version to 1.14.4

hplsql/src/test/java/org/apache/hive/hplsql/TestConsole.java, hplsql/src/test/java/org/apache/hive/hplsql/TestHplsqlLocal.java, hplsql/src/test/java/org/apache/hive/hplsql/TestHplsqlOffline.java
This PR introduces a custom `Console` implementation to capture the output of two `hplsql` tests and make them independent from whatever is printed to `System.out` and `System.err`.
Two tests in `hplsql` module (`TestHplsqlLocal` and `TestHplsqlOffline`) make assertions on the output to `System.out` and `System.err`. This makes the tests fragile to any other output that might appear there (see apache/logging-log4j2#2791 for example) and prevents them from running in parallel.
No, no changes to the main code are introduced.
No.
=> HIVE-28656: Improve HPL/SQL tests

llap-common/src/java/org/apache/hadoop/hive/llap/LlapThreadLocalStatistics.java, llap-common/src/java/org/apache/hadoop/hive/llap/LlapUtil.java, llap-common/src/test/org/apache/hadoop/hive/llap/TestLlapThreadLocalStatistics.java, llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/StatsRecordingThreadPool.java
Refactoring StatsRecordingThreadPool and creating a new class LlapThreadLocalStatistics.
Describe in jira.
No.
No.
Unit tests were added for the new class LlapThreadLocalStatistics.
Tested on a cluster (using file + s3), before/after results were almost the same. Ignoring <1% difference between different runs.
E.g. without patch
1.
```
INFO  : File System Counters:
INFO  :    FILE_BYTES_READ: 0
INFO  :    FILE_BYTES_WRITTEN: 39544287
INFO  :    FILE_READ_OPS: 0
INFO  :    FILE_LARGE_READ_OPS: 0
INFO  :    FILE_WRITE_OPS: 0
INFO  :    S3A_BYTES_READ: 53568465091
INFO  :    S3A_BYTES_WRITTEN: 0
INFO  :    S3A_READ_OPS: 3553
INFO  :    S3A_LARGE_READ_OPS: 0
INFO  :    S3A_WRITE_OPS: 0
INFO  : org.apache.hadoop.hive.llap.daemon.impl.StatsRecordingThreadPool$WrappedCallable$LlapExecutorCounters …
```
=> HIVE-28638: Refactor stats handling in StatsRecordingThreadPool

ql/src/test/queries/clientpositive/msck_repair_8.q, ql/src/test/queries/clientpositive/msck_repair_9.q, ql/src/test/results/clientpositive/llap/msck_repair_8.q.out, ql/src/test/results/clientpositive/llap/msck_repair_9.q.out, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestMetaStoreServerUtils.java
[HIVE-28654](https://issues.apache.org/jira/browse/HIVE-28654)
To ensure msck repair command works when default partition "__HIVE_DEFAULT_PARTITION__" is present
NO
NO
Using q files (present in PR)
```
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=msck_repair_9.q -Drat.skip -Dtest.output.overwrite
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=msck_repair_8.q -Drat.skip -Dtest.output.overwrite
```
=> HIVE-28654: MSCK repair fails for default partition when partition column is of numeric type

itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestHiveDatabaseMetaData.java, jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java, jdbc/src/java/org/apache/hive/jdbc/HiveDatabaseMetaData.java
- Impl `DatabaseMetaData#getURL()` and `DatabaseMetaData#getUserName()` for HiveServer2 JDBC Driver.
- I totally don't understand why `DatabaseMetaData#getURL()` and `DatabaseMetaData#getUserName()` are not implemented for HiveServer2 JDBC Driver in https://github.com/apache/shardingsphere/pull/33762 and https://github.com/apache/shardingsphere/issues/29052 . This leads to funny logic like the following.
```java
try (Connection connection = dataSource.getConnection()) {
return connection.getMetaData().getURL();
} catch (final SQLFeatureNotSupportedException sqlFeatureNotSupportedException) {
try (Connection connection = dataSource.getConnection()) {
Class<?> hiveConnectionClass = Class.forName("org.apache.hive.jdbc.HiveConnection");
if (connection.isWrapperFor(hiveConnectionClass)) { …
```
=> HIVE-15540: Impl `DatabaseMetaData#getURL()` and `DatabaseMetaData#getUserName()` for HiveServer2 JDBC Driver

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Enable the dynamic leader election on HMS by default
In the Hive ACID world, we must enable the metastore.compactor.initiator.on and metastore.compactor.cleaner.on on HMS to trigger the table compaction automatically. In a real warehouse, we might have multiple HMS instances behind, or even deploy for different purposes, running the tasks like these on all instances could be a waste of resources, make the HMS scale out not so easily. 
Default value of the following properties changed:
metastore.housekeeping.leader.election host -> lock
metastore.housekeeping.threads.on false -> true
metastore.compactor.initiator.on false -> true
metastore.compactor.cleaner.on false -> true
No
The existing UTs
=> HIVE-28662: Enable the dynamic leader election for HMS

hcatalog/core/src/main/java/org/apache/hive/hcatalog/mapreduce/DynamicPartitionFileRecordWriterContainer.java, hcatalog/core/src/main/java/org/apache/hive/hcatalog/mapreduce/FileOutputFormatContainer.java, hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/HCatMapReduceTest.java, hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatDynamicPartitioned.java, hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatExtension.java
HCatStorer now respects hive.file.output.extension for the output files it writes.
Brings HCatStorer's feature set more in line with Hive's.
Adds support for a property to HCatStorer that would previously have been ignored.
No
TestHCatExtension was added.
=> HIVE-28377: Add support for hive.output.file.extension to HCatStorer

ql/src/java/org/apache/hadoop/hive/ql/DriverContext.java, ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezRuntimeContext.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
Encapsulate runtime related info to a separate class for later usage.
Code refactor.
No.
No.
Easy refactor, precommit tests should pass.
=> HIVE-28623: Implement RuntimeContext to decouple runtime data from TezTask

pom.xml, standalone-metastore/pom.xml
MySQL version upgrade from 8.0.31 to 8.2.0
The current version of MySQL if 8.0.31, which has the following vulnerabilities associated with it:
Direct vulnerabilities:
The current version of MySQL connector jar is 8.0.31, which has the following vulnerabilities associated with it:
Direct vulnerabilities:
CVE-2023-22102
Vulnerabilities from dependencies:
CVE-2024-7254
CVE-2022-3510
CVE-2022-3509
CVE-2022-3171
So, this issue is to remedy this with the version upgrade as a fix.
https://dev.mysql.com/doc/relnotes/connector-j/en/news-8-2-0.html
Mysql connector/J version 8.2.0 is the smallest upgrade that fixes the CVEs and can be used against MySQL Server version 5.7 and later.
Versions 8.3.0 and above are compatible with mysql server versions 8.0 and above, and since the current version is …
=> HIVE-28671 : Upgrade MySQL connector jar version to 8.2.0

llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/AsyncTaskCopyLocalJars.java, pom.xml, ql/src/java/org/apache/hadoop/hive/llap/WritableByteChannelAdapter.java
Upgrade Netty due to CVEs
Fixing CVEs
No
Yes
Dependency tree: 
[dpn_netty_116.txt](https://github.com/user-attachments/files/18327748/dpn_netty_116.txt)
Manual Testing by running few queries after local compilation
=> HIVE-28040: Upgrade netty to 4.1.116.Final due to CVEs

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
Improve the performance of deleting column stats for wide table.
The JDO implementation of deleting column stats needs to retrieve the column stats objects, it could be slow if the table has many columns. 
No.
No.
Add some unit tests:
```bash
mvn test -Dtest.groups= -Dtest=org.apache.hadoop.hive.metastore.TestObjectStore#testPartitionStatisticsOps -pl :hive-standalone-metastore-server
```
=> HIVE-28677: Implement direct sql for delete table/partition column stats

ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHivePrivilegeObjectOwnerNameAndType.java
This test class is intended to validate the HivePrivilegeObject for queries. If the current user is changed, insert queries fail when executed on Tez due to the validation of the staging directory's owner. The staging directory is created by the system user when the test is executed in local file system mode. Since the main goal is to validate the privilege object type and count, without checking the owner name, the simplest fix is to run the tests as the system user.
Since MR is deprecated, remove the test dependency as well, by running with Tez
No
No
Test pipeline
=> HIVE-28619: TestHivePrivilegeObjectOwnerNameAndType to run on Tez

ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientnegative/constraint_invalid_cast.q, ql/src/test/queries/clientnegative/constraint_invalid_cast_partition.q, ql/src/test/results/clientnegative/alter_notnull_constraint_violation.q.out, ql/src/test/results/clientnegative/constraint_invalid_cast.q.out, ql/src/test/results/clientnegative/constraint_invalid_cast_partition.q.out, ql/src/test/results/clientnegative/insert_into_acid_notnull.q.out, ql/src/test/results/clientnegative/insert_into_notnull_constraint.q.out, ql/src/test/results/clientnegative/insert_overwrite_notnull_constraint.q.out, ql/src/test/results/clientpositive/llap/check_constraint.q.out, ql/src/test/results/clientpositive/llap/default_constraint.q.out, ql/src/test/results/clientpositive/llap/enforce_constraint_notnull.q.out
Move Filter operator with enforce constraint call generation after conversion Select operator generation and make the Filter operator the child operator of the conversion Select operator.
Currently, implicit type conversion occurs after constraints are enforced; however, the result of an invalid cast can be `null`. In these cases, the `null` value is inserted despite the fact that a not-null constraint is specified on the target column.
See the execution plan if this simple insert:
```
set hive.stats.autogather=false;
create table t1(
date_col date not null
);
explain
insert into t1 values ('2024-99-99');
```
```
Filter Operator
predicate: enforce_constraint(_col0 is not null) (type: boolean)
Statistics: Num rows: 1 Data size: 8 Basic stats: COMPLETE Column stats: COMPLETE
Select Operator …
```
=> HIVE-28589: Not null constraint does not enforced at invalid cast

ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizationContext.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/CalciteSemanticException.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveComponentAccess.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTConverter.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/RexNodeConverter.java, ql/src/java/org/apache/hadoop/hive/ql/parse/type/RexNodeExprFactory.java, ql/src/test/queries/clientpositive/nested_column_pruning.q, ql/src/test/queries/clientpositive/vector_orc_nested_column_pruning.q, ql/src/test/results/clientpositive/llap/input_testxpath4.q.out, ql/src/test/results/clientpositive/llap/nested_column_pruning.q.out, ql/src/test/results/clientpositive/llap/orc_nested_column_pruning.q.out, ql/src/test/results/clientpositive/llap/vector_orc_nested_column_pruning.q.out
We need to support array field access in the CBO. This is currently already supported in the execution side. Only CBO fails with an error. So we will be by passing the CBO by doing no-op in this case to leave it to hive compiler and execution engine to do rest of the work
In order to enable CBO for all the queries
No
No
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=nested_column_pruning.q
=> HIVE-28408: Support ARRAY field access in CBO

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/HivePreWarmProcessor.java
Fix the URL
To avoid exceptions in the LOG due to wrong jar path
No
No
Manual
=> HIVE-28707: QTest log is filled with HivePreWarmProcessor warn messages

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationMigrationTool.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplicationMigrationTool.java
Fixed minor bugs in ReplicationMigrationTool and enabled TestReplicationMigrationTool class
The testcases were not running properly from beginning and went unnoticed because of lower Maven surefire plugin which suppressed the errors. Post [HIVE-28519](https://issues.apache.org/jira/browse/HIVE-28519) the test cases started failing. Error log is added in the jira.
No
No
Existing test case
=> HIVE-28608: Resolve Issues in ReplicationMigrationTool and Activate Test Suite

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/FileUtils.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreFsImpl.java
Currently the `FileUtils#moveToTrash` would fallback to call `delete()` API even if encountering `FileNotFoundException`, we could fast return if the path does not exist.
To reduce the hdfs calls and avoid the confusing failure log.
No.
No.
Pass existing tests.
=> HIVE-28691: Check if the path exists before deleting in FileUtils#moveToTrash

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/processors/CommandProcessorFactory.java, ql/src/java/org/apache/hadoop/hive/ql/processors/HiveCommand.java, ql/src/java/org/apache/hadoop/hive/ql/processors/ShowProcessListProcessor.java, ql/src/java/org/apache/hadoop/hive/ql/processors/ShowProcesslistProcessor.java, ql/src/java/org/apache/hadoop/hive/ql/session/ProcessListInfo.java, service/src/java/org/apache/hive/service/cli/operation/ExecuteStatementOperation.java, service/src/java/org/apache/hive/service/cli/operation/HiveCommandOperation.java, service/src/java/org/apache/hive/service/cli/operation/ShowProcessListOperation.java, service/src/test/org/apache/hive/service/cli/operation/TestHiveCommandOpForProcessList.java
This PR introduces a new command "Show Processlist" which displays the operations running on Hiveserver2 and provides session and operation details. This is similar to the MYSQL SHOW PROCESSLIST implementation.
This command will help troubleshoot issues with the Hiveserver2, especially stuck queries. We can understand the load on a given HS2 instance and identify inappropriate connections to terminate them.
Yes, attaching sample output for the command
```
0: jdbc:hive2://localhost:10000> show processlist;
+------------+------------+-------------------+---------------------------------------+--------------------------+------------------------+----------------------------------------------------+-----------+-------------------+-------------------+---------------+-----------------+
| User …
```
=> HIVE-27829 : New command "Show Processlist" to display current operations and related details in Hiveserver2 

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java, ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
    - Once Dump/Load is failed with FAILED_ADMIN then following dumps/loads should also be flagged as same instead of SKIPPED
=> HIVE-28670: Show failed status in all the latest replication history event

ql/src/java/org/apache/hadoop/hive/ql/ddl/database/create/CreateDatabaseAnalyzer.java, ql/src/test/results/clientpositive/llap/authorization_privilege_objects.q.out
Refer to [HIVE-28716](https://issues.apache.org/jira/browse/HIVE-28716) and [RANGER-5097](https://issues.apache.org/jira/browse/RANGER-5097) for the info
Currently we are not passing the owner information for database in HivePrivilegeObject. This object is passed to ranger and ranger is using this owner information but as it is missing, NoSuchObjectException is thrown HS2 logs. Check the above mentioned JIRA for stacktrace and debugging screenshot. 
**NOTE: There is no impact on the functionality, table/db is getting created in hive. It more of a noise in the HS2 logs coming from ranger.** 
No
No
On Cluster testing and monitoring HS2 logs
=> HIVE-28716: Add owner information in HivePrivilegeObject for create database query

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/test/queries/clientpositive/cbo_rp_explain.q, ql/src/test/results/clientpositive/llap/cbo_rp_explain.q.out, ql/src/test/results/clientpositive/llap/groupby_ppr_multi_distinct.q.out
1. Refactor enrichment of explain context for all branches with CBO plans
2. Extract PlanModifierForReturnPath outside getOptimizedHiveOPDag to make the effects visible in `EXPLAIN CBO`
3. Move some debug/trace messages and make them more uniform.
Display CBO plan when hive.cbo.returnpath.hiveop is true
EXPLAIN CBO will show the plan as expected.
No
```
mvn test -Dtest=TestMiniLlapLocalCliDriver.java -Dqfile="cbo_rp_explain.q"
```
=> HIVE-28720: EXPLAIN CBO is empty when hive.cbo.returnpath.hiveop is true

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveInsertExchange4JoinRule.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/test/queries/clientpositive/cbo_rp_null_order.q, ql/src/test/results/clientpositive/llap/cbo_rp_null_order.q.out
Use the default null order configured via `hive.default.nulls.last` in the Calcite rule `HiveInsertExchange4JoinRule.java` when creating sort keys. This rule is used only when `hive.cbo.returnpath.hiveop` is enabled.
The setting `hive.default.nulls.last` doesn't have affect to the `HiveSortExchange` operators created by this rule and the RS operators built from them.
Explain output of query plans has join operation may change.
No.
```
mvn test -Dtest.output.overwrite -Dtest=TestMiniLlapLocalCliDriver -Dqfile=cbo_rp_null_order.q -pl itests/qtest -Pitests
```
=> HIVE-28729: Apply nulls order setting in Reduce Sink operator of join branches

ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFCharacterLength.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFLength.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFOctetLength.java
Since it refers to a variable that has not been initialized, NullPointerException occurs and the correct error message is not displayed.
```
if (arguments[0].getCategory() != ObjectInspector.Category.PRIMITIVE) {
throw new UDFArgumentException(
"OCTET_LENGTH only takes primitive types, got " + argumentOI.getTypeName());
}
argumentOI = (PrimitiveObjectInspector) arguments[0];
```
Correct error message is not displayed when an error occurs.
No
At my Hadoop cluster.
=> HIVE-24110: NullPointerException occurs in some UDFs

pom.xml, service/pom.xml, standalone-metastore/pom.xml
Before:
[INFO] +- org.pac4j:pac4j-saml-opensamlv3:jar:4.5.5:compile
[INFO] |  +- org.pac4j:pac4j-core:jar:4.5.5:compile
[INFO] |  +- org.opensaml:opensaml-storage-impl:jar:3.4.6:compile
[INFO] |  |  +- org.ldaptive:ldaptive:jar:1.0.13:compile
[INFO] |  |  +- javax.json:javax.json-api:jar:1.0:compile
[INFO] |  |  +- net.spy:spymemcached:jar:2.12.3:compile
[INFO] |  |  \- **org.glassfish:javax.json:jar:1.0.4:runtime**
After: 
[INFO] +- org.pac4j:pac4j-saml-opensamlv3:jar:4.5.8:compile
[INFO] |  +- org.pac4j:pac4j-core:jar:4.5.8:compile
[INFO] |  +- org.opensaml:opensaml-storage-impl:jar:3.4.6:compile
[INFO] |  |  +- org.ldaptive:ldaptive:jar:1.0.13:compile
[INFO] |  |  +- javax.json:javax.json-api:jar:1.0:compile
[INFO] |  |  \- net.spy:spymemcached:jar:2.12.3:compile
To fix …
=> HIVE-28704: Upgrade pac4j core and opensamlv3 and exclude Javax.json

hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
In Oracle, empty strings ('') are treated as NULL values for VARCHAR2 and CHAR data types. This behavior is unique to Oracle and can be confusing, as an empty string is typically considered distinct from NULL in other databases.
As a result, the TXN_WRITE_NOTIFICATION_LOG table receives duplicate entries for a single Hive ACID transaction involving MERGE statements.
This discrepancy leads to issues: the _files and _dumpmetadata files in a Hive ACID incremental dump will not align if the dump scope includes one or more MERGE statements. Consequently, the Hive ACID incremental LOAD fails at the target (DR), blocking subsequent replication executions.
Solution
* Add additional check for partition being null
Testing:
* Tested on cluster with oracle and mysql as backend database
=> HIVE-28622: Duplicate Entries in TXN_WRITE_NOTIFICATION_LOG Due to Oracle's Handling of Empty Strings

pom.xml
Upgrade aws-java-sdk to 1.12.720
CVE fix
No
[Yes](https://issues.apache.org/jira/secure/attachment/13074333/mvn_dependency_tree1.txt).
Built locally.Relying on precommits
=> HIVE-28730:Upgrade aws-java-sdk to 1.12.720

common/src/java/org/apache/hadoop/hive/common/JvmMetrics.java, itests/hcatalog-unit/pom.xml, itests/hive-unit/src/test/java/org/apache/hive/service/auth/jwt/TestHttpJwtAuthentication.java, itests/util/pom.xml, itests/util/src/main/java/org/apache/hadoop/hive/hbase/HBaseTestSetup.java, pom.xml, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/metatool/MetaToolTaskListExtTblLocs.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestRemoteHiveMetastoreWithHttpJwt.java, standalone-metastore/pom.xml, storage-api/pom.xml
Upgrade Hadoop version from 3.3.6 to 3.4.1
No
Yes. See the file: 
[hadoop_upgrade_dep.txt](https://github.com/user-attachments/files/18392110/hadoop_upgrade_dep.txt)
Existing Tests.
=> HIVE-28191: Upgrade Hadoop Version to 3.4.1

packaging/src/docker/README.md, packaging/src/docker/entrypoint.sh
- Add documentation for initializing the system schemas for HiveServer2 for Docker Image. See https://hive.apache.org/development/quickstart/ .
- The result of my 6-month investigation on https://issues.apache.org/jira/browse/HIVE-28437 is that HiveServer2 definitely supports the use of the `INFORMATION_SCHEMA` database, but it is not enabled by default, which causes a lot of trouble for unit testing scenarios of third-party libraries such as testcontainers-java .
- Early investigations came from https://github.com/linghengqian/hive-server2-jdbc-driver/pull/22 , https://github.com/apache/shardingsphere/issues/29052 . It seems that the Hive documentation https://hive.apache.org/docs/latest/hive-schema-tool_34835119/ does not support viewing images. I will still refer to the documentation …
=> HIVE-28437: Add documentation for initializing the system schemas for HiveServer2 for Docker Image

ql/src/test/queries/clientpositive/casewhen_isnot_boolean_partition.q, ql/src/test/results/clientpositive/llap/casewhen_isnot_boolean_partition.q.out, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/PartFilterVisitor.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/PartitionFilter.g4
Added missing support for parsing '**IS NOT? TRUE/FALSE**' conditions in partition filter pruning. Specifically, it handles cases where partition filters with boolean expressions such as IS NOT TRUE or IS NOT FALSE are involved, ensuring correct partition pruning behaviour.
These changes address data inconsistencies in queries involving partition filter pushdown to the Hive Metastore (HMS), especially when dealing with boolean expressions like **IS NOT? TRUE** or **IS NOT? FALSE**. Previously, the partition pruning logic failed to correctly interpret these expressions, leading to incorrect results and inefficient query execution. With the new parsing logic, partition pruning now handles these complex boolean conditions properly, ensuring accurate data retrieval and better query …
=> HIVE-28705: Fix Data Inconsistency due to missing 'IS NOT? TRUE/FALSE' parsing in Partition Filter Pruning

pom.xml, standalone-metastore/pom.xml
Upgrade curator.version in pom.xml from 5.2.0 to 5.7.1
CVE mentioned in mvn repo: [CVE-2023-2976](https://mvnrepository.com/artifact/org.apache.curator/curator-client/5.2.0#:~:text=490%20artifacts-,Vulnerabilities,-Vulnerabilities%20from%20dependencies)
[HIVE-28751](https://issues.apache.org/jira/browse/HIVE-28751)
No
Yes
[tree.txt](https://github.com/user-attachments/files/18728889/tree.txt)
mvn dependency:tree
=> HIVE-28751: Upgrade curator version from 5.2.0 to 5.7.1 to fix CVE-2023-2976

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java, iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_partition_evolution.q, iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_partition_evolution.q.out
Clean up our Iceberg utilities.
For clean up + add some regression tests.
No
No.
I updated an existing qtest.
=> HIVE-28727: Iceberg: Refactor IcebergTableUtil.toPartitionData

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/HikariCPDataSourceProvider.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/datasource/TestDataSourceProviderFactory.java
HicariConfig's leak detection threshold has to be smaller than the max lifetime. Our default leak detection threshold is greater than the maximum lifetime defined on the HikariCP side and is disabled by default. Please check the JIRA for details.
https://issues.apache.org/jira/browse/HIVE-28749
Make our default value effective.
No.
No.
- I verified the warning disappears with default configurations
- I tested `hikaricp.maxLifetime` was configurable in my local machine
=> HIVE-28749: The default hikaricp.leakDetectionThreshold is not valid

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/queries/negative/iceberg_drop_partition_tranform_column.q, iceberg/iceberg-handler/src/test/results/negative/iceberg_drop_partition_tranform_column.q.out
As of now drop partition on a transformed column isn't supported, but the query succeeds giving an impression of success, rather throw an exception to make it clear 
Better User Experiance 
Yes, Drop Partition on transformed column rather than showing fake success, throws exception
No
UT
=> HIVE-28764: Iceberg: Throw Exception in case of Drop Partition on transformed column.

packaging/src/docker/conf/hive-log4j2.properties, packaging/src/docker/conf/hive-site.xml
Put the default log4j properties in the official Docker image.
File-based logging is inconvenient, and it doesn't follow the common practice of containers.
Yes.
No.
I tested the output in my local machine.
=> HIVE-28748: Docker: Redirect daemon's logs to STDOUT

common/src/java/org/apache/hadoop/hive/ql/log/PerfLogger.java, ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/StatsTask.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsTask.java
Display MoveTask's and StatsTask's duration on the console.
Better observability.
Yes, query output on the console slightly changes.
No.
On cluster. Unfortunately, due to HIVE-28627, the console message is broken, works only intermittently, but in the logs, the very same messages appear.
=> HIVE-28626: Display MoveTask/StatsTask duration on the query summary

iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergExpireSnapshots.java, parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Allow specifying functions while expiring snapshots
Better Usability
Yes, Expire Snapshots allows valid expressions
No
UT
=> HIVE-28763: Iceberg: Support functions while expiring snapshots.

data/conf/hive-log4j2.properties, llap-server/pom.xml, llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/QueryTracker.java, llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/TestLlapDaemonLogging.java, pom.xml, standalone-metastore/metastore-server/pom.xml, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestMetaStoreServerUtils.java, standalone-metastore/pom.xml
This PR is based on https://github.com/apache/hive/pull/5375 (Thx linghengqian and @zhangbutao )
It upgrades log4j to 2.24.3
log4j to 2.24.3
https://github.com/apache/logging-log4j2/issues/1391
No
Yes
- Ran the CI pipeline, all tests passed
- Checked if the pipeline ran all the tests: 
-- This PR: 106494 tests (https://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-5636/5/tests)
-- Latest green test on master: 106491 tests (https://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/master/2411/tests)
=> HIVE-28417: Bump Log4j2 to 2.24.3

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
Add Ozone filesystems to Exim URI whitelist, same as [HIVE-20763](https://issues.apache.org/jira/browse/HIVE-20763) for gcs
To Support Ozone filesystems. The Ozone Filesystem scheme are defined here
https://github.com/apache/ozone/blob/e2bf5998c1e109bf9dbe28e0ad56b69220086814/hadoop-hdds/common/src/main/java/org/apache/hadoop/ozone/OzoneConsts.java#L82-L84
Yes, export can work OOTB for Ozone FileSystems
No
Manual
=> HIVE-28779: Add ozone filesystem to the exim uri schema whitelist.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/misc/sortoder/SortFieldDesc.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Change-Id: Ic313562fbb5d92bb9f42ea7c718ca44c52e99b8e
Refactor NullOrder usage in iceberg write oder function
Make the code more clean
No
No
With qtest.
=> HIVE-28774 Refactor NullOrder usage in iceberg write oder function

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, data/conf/hive-site.xml, data/conf/iceberg/llap/hive-site.xml, data/conf/iceberg/tez/hive-site.xml, data/conf/llap/hive-site.xml, data/conf/mr/hive-site.xml, data/conf/rlist/hive-site.xml, data/conf/tez/hive-site.xml, itests/hive-blobstore/src/test/resources/hive-site.xml, ql/src/java/org/apache/hadoop/hive/ql/optimizer/Optimizer.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/lineage/Generator.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
[HIVE-28768](https://issues.apache.org/jira/browse/HIVE-28768), Use HIVE_LINEAGE_STATEMENT_FILTER configuration to determine whether to compute lineage information or not and for which query type (CTAS, Create View etc) the lineage should be computed.
Currently, lineage information is computed only if few post exec hooks are configured or HIVE_LINEAGE_INFO (doesn't capture "views" related lineage) is set to true. In [HIVE-28409](https://issues.apache.org/jira/browse/HIVE-28409), fine grain control over lineage was introduced and its better to utilize that.
**Point to Ponder**: The lineage information computation will be by-default enabled for ALL query.
For more info please check the discussion [here](https://issues.apache.org/jira/browse/HIVE-28409?focusedCommentId=17927788&page=com.atlas …
=> HIVE-28768: Remove hardcoded post exec hooks

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/patched-iceberg-core/pom.xml, iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/SnapshotProducer.java, ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/queryhistory/repository/IcebergRepository.java
Replaces iceberg's worker thread pool with a same-sized one that accepts tasks after jvm shutdown hook.
Described on jira, tldr, to make query history able to flush records on hs2 shutdown.
No.
No.
Manually tested on local MiniHS2 and Cloudera Data Warehouse, the HS2 showed that the full commit process ran successfully. Without the patch, the RejectedExecutionException was present in both scenarios.
=> HIVE-28759: Hive Query History - records are failed to be written due to iceberg worker pools shut down

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, llap-common/src/java/org/apache/hadoop/hive/llap/security/SecretManager.java
This pull request proposes to introduce changes to support secure ssl based zookeeper access for hive llap secretManager.
To enhance zookeeper connectivity security by leveraging the hadoop side change.
No
No
This patch was tested by deploying the hive side changes on a cluster followed by changing the insecure zookeeper port in the SecretManager configuration of the hiveserver2 and LLAP to the secure port of the zookeeper server running on cluster. We also added the truststore and keystore location and passwords configs as per our cluster setup. We then executed multiple queries, all of which ran successfully. Also, the logs confirmed the secure zookeeper connection.
=> HIVE-28778: Support Secure Zookeeper Access in Hive SecretManager

pom.xml, ql/pom.xml, standalone-metastore/pom.xml
Upgrading the Atlas to 2.4.0, details are in-detailed at [HIVE-28693](https://issues.apache.org/jira/browse/HIVE-28693)
This change will fix the [CVE-2023-20863](https://nvd.nist.gov/vuln/detail/CVE-2023-20863).
And 
Upgrading to Apache Atlas 2.4.0 will not only resolve the vulnerability but also ensure alignment of spriongframework  with Apache Hive, which uses Spring Framework 5.3.39. This version of Spring Framework is included transitively by Hive.
No
Yes
Adding the image for packaged jars and the dependency tree for Spring
And  complete dependency tree 
[hive_28693_dependency_tree.log](https://github.com/user-attachments/files/18328355/hive_28693_dependency_tree.log)
=> HIVE-28693: Upgrade Atlas to 2.4.0 & spring-ldap-core to 2.4.4

jdbc/src/java/org/apache/hive/jdbc/Utils.java, jdbc/src/test/org/apache/hive/jdbc/TestHiveConnection.java
Introduce a new regex pattern to reparse the password from the original jdbc url after getting session vars
Users can use Beeline with JDBC URLs that include passwords containing special characters
No
No
Test with replacing jdbc jar and connecting with passwords with/without special characters.
=> HIVE-28805: Re-parse the password from the original jdbc url

itests/util/src/main/java/org/apache/hadoop/hive/ql/externalDB/MariaDB.java, itests/util/src/main/java/org/apache/hadoop/hive/ql/externalDB/MySQLExternalDB.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mariadb.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mysql.java
Upgrade MySQL version
[HIVE-28597](https://issues.apache.org/jira/browse/HIVE-28597)
No
No
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=qt_database_mysql.q -pl itests/qtest -Pitests
=> HIVE-28597: Upgrade to 8.4.3 LTS version of MySQL and 11.4 LTS version of MariaDB

iceberg/iceberg-catalog/pom.xml, iceberg/iceberg-handler/pom.xml, iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_partition_evolution.q, iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_partition_evolution.q.out, iceberg/iceberg-shading/pom.xml, iceberg/patched-iceberg-api/pom.xml, iceberg/patched-iceberg-api/src/main/java/org/apache/iceberg/util/StructProjection.java, iceberg/patched-iceberg-core/pom.xml, iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/PartitionsTable.java, iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/util/StructLikeMap.java, iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/util/StructLikeWrapper.java
Iceberg PR:
https://github.com/apache/iceberg/pull/12528
=> HIVE-28837: Iceberg: PartitionsTable#partitions returns incomplete list in case of partition evolution and NULL partition values

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/MetastoreLock.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergAcidUtil.java, iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc8.q, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc8.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/NonNativeAcidMaterializedViewASTBuilder.java, ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/stats/HiveIncrementalRelMdRowCount.java
In general materialized view table scan plan is just a TableScan operator.
```
HiveTableScan(table=[[default, mat1]], table:alias=[default.mat1])
```
However in some cases a `Project` is added with cast expressions. For example when the MV schema contains `varchar` typed columns.
```
HiveProject(b=[CAST($0):VARCHAR(256) CHARACTER SET "UTF-16LE"], _c1=[$1])
HiveTableScan(table=[[default, mat1]], table:alias=[default.mat1])
```
* Use `HiveMaterializedViewUtils.extractTable` in `HiveIncrementalRelMdRowCount.source` to get the materialized view table object.
* When transforming the Materialized View rebuild AST to a multi insert AST extract all projected expression aliases from plan branch scanning the materialized view. 
Materialized view scan plan may contain a project with cast …
=> HIVE-28817: Rebuilding a materialized view stored in Iceberg fails when schema has varchar column

llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/SerDeEncodedDataReader.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/VectorDeserializeOrcWriter.java
Similar to what is currently being done in _OrcEncodedDataReader_, FS Initialisation for _SerDeEncodedDataReader_ & _VectorDeserializeOrcWriter_ should be based on _jobConf_ rather than _daemonConf_. 
This will ensure that the _FileSystems_ are being initiated with the configurations being passed as part of _jobConf_ which could be different on a Job basis instead of LLAP IO's _daemonConf_.
No
No
Passing configs by setting them in Hive code, when using LLAP IO, these configs are not being honored by the FS being initialized by _SerDeEncodedDataReader_. This is because _SerDeEncodedDataReader_ uses LLAP IO's daemon config, rather than the _jobConf_ (which typically contains custom set of configs as well).
=> HIVE-28831 : FS Initialisation for SerDeEncodedDataReader & VectorDeserializeOrcWriter should be based on jobConf

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/MetastoreLock.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergAcidUtil.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java
* Revert setting the transactionId of an Acid transaction in Iceberg job configurations
* Materialized views stored by Iceberg and the MV metadata is stored in HMS doesn't need a write lock because
the locking is done by DbTxnManager.acquireMaterializationRebuildLock()
* Acquire materialization rebuild lock when rebuilding an MV stored by Iceberg
Avoid deadlock when rebuilding M stored by Iceberg with native base tables
No.
No.
```
mvn test -Dtest.output.overwrite -Dtest=TestIcebergLlapLocalCliDriver -Dqfile=mv_iceberg_orc8.q -pl itests/qtest-iceberg -Pitests
```
=> HIVE-28817: Rebuilding a materialized view stored in Iceberg fails when schema has varchar column - ADDENDUM

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java, ql/src/test/queries/clientpositive/sharedwork_map_side_aggregations.q, ql/src/test/results/clientpositive/llap/sharedwork_map_side_aggregations.q.out
This PR would limit the maximum number of table scan operators which SWO tries to merge.
https://issues.apache.org/jira/browse/HIVE-28549
We observed SWO makes a negative impact when it merges too many, e.g. 50, operators. If operators are memory intensive, they might throw OOM or might slow down.
I believe we can resolve OOM with the following patch, but we still want an upper limit so that we can tune concurrency or RAM per operator reasonably.
https://github.com/apache/hive/pull/5478
No.
No.
I added a qtest
=> HIVE-28549: Limit the maximum number of operators merged by SharedWorkOptimizer

ql/src/java/org/apache/hadoop/hive/ql/DriverUtils.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/KillTriggerActionHandler.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/WorkloadManager.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMaterializedViewsRegistry.java, ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/StatsUpdater.java, ql/src/test/org/apache/hadoop/hive/ql/stats/TestStatsUpdaterThread.java, service/src/java/org/apache/hive/service/cli/CLIService.java
Ensures session related directories is properly cleaned up when HiveServer2 (HS2) shuts down, by adding a shutdown hook to call close() method, which ensures cleaning session related directories.
Session related directories persist after HS2 shutdown, leading to disk bloat and performance degradation. This fix prevents unnecessary resource accumulation and improves cleanup.
No functional changes for users; it only enhances internal resource management. Temporary directories will now be cleaned up automatically.
No, this PR does not introduce any dependency upgrades.
Manually verified that session directories on /tmp and /tmp/{user_dir}/ are created and removed correctly.
=> HIVE-28770: Fix Session Directories Persisting After HiveServer2 Shutdown

itests/hive-minikdc/pom.xml, pom.xml, service/pom.xml, standalone-metastore/pom.xml
Please refer to [HIVE-28163](https://issues.apache.org/jira/browse/HIVE-28163) and stale PR: https://github.com/apache/hive/pull/5171
When running with jdk17, there were failure in service module regarding apache directory server.
```
mvn test -Dtest='org.apache.hive.service.auth.TestLdapAtnProviderWithMiniDS#testGroupFilterPositive' -pl service
```
NO
YES. Here's the dependency tree:  [dependency-tree.txt](https://github.com/user-attachments/files/19565085/dependency-tree.txt)
In cluster
=> HIVE-28163: Upgrade apache directory server to 2.0.0-M24

standalone-metastore/metastore-tools/pom.xml
Junit version upgrade in hive-metastore-tools
To bring version consistency throughout
No
Yes
Before:
After:
[dptree_junit.txt](https://github.com/user-attachments/files/19502139/dptree_junit.txt)
=> [HIVE-28794]: Remove junit version from hive-metastore-tools/pom.xml to inherit version from parent pom

.gitignore, packaging/src/docker/build.sh
Cache stable Hadoop, Tez, and Hive artifacts. We might have a better approach.
https://issues.apache.org/jira/browse/HIVE-28854
The current implementation downloads them every time. Downloading Hadoop is costly.
No.
No.
I ran locally `./build.sh` and `./build.sh -hive 4.0.1`.
=> HIVE-28854: Speed up Docker builds

llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/AsyncTaskCreateUdfFile.java, llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/FunctionLocalizer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java, ql/src/java/org/apache/hadoop/hive/ql/util/ResourceDownloader.java, ql/src/test/org/apache/hadoop/hive/ql/session/TestAddResource.java
Removed creating resource directories on initialising session state. org.apache.hadoop.hive.ql.util.ResourceDownloader#downloadResource will ensure creating directories when needed.
Previously, resource directories were created outside of SessionState.start, leading to inconsistencies and leftover directories when the session state was not properly closed. This issue was particularly noticeable with Spark SQL, as it resulted in the accumulation of unused session resource directories, consuming disk space and potentially affecting performance. 
Check [SPARK-51571](https://issues.apache.org/jira/browse/SPARK-51571) for reference
Fixing this issue in Hive itself ensures consistent behaviour across all engines that use SessionState, including Spark, making it a more robust and centralized …
=> HIVE-28836: Hive SessionState Resource directories persists if SessionState is not started

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezRuntimeContext.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
Print AM hostname on the console.
Because on DAG submission, the user ends up seeing an application id, which is hard to track back to a Tez AM / coordinator, making the investigation hard. Imagine a long-running query on a cluster that utilizes 30+ Tez AMs, and in case of e.g. a kubernetes environment, logical hostnames are used, like TezAM1, TezAM2...by knowing only the DAG id and application id, there will always be an extra step to locate the AM, which could be painful if the app id <-> hostname pair is only printed once a few hours (days?) ago, if it logged at all (need to be aware that the application can be alive since "forever").
Yes, on DAG submission, not only the AM app id, but the app master's hostname will be printed.
No.
Tested on cluster, check screenshot: …
=> HIVE-28868: Print AM hostname on console

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-rest-catalog/src/main/java/org/apache/iceberg/rest/HMSCatalogFactory.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PropertyServlet.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ServletSecurity.java
Let HMSCatalog, the Iceberg REST catalog on HMS, respect the parameter.
We can't configure the auth mode of the catalog API
No. This feature has not been released yet
No
I ran the server on my local machine
=> HIVE-28840: HMS Iceberg Catalog doesn't respect ICEBERG_CATALOG_SERVLET_AUTH

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveLock.java, iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStatistics.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
HiveIcebergMetaHook acquires the HMS lock only when necessary, depending on the operationType and the config(`engine.hive.lock-enabled`).
Stat tasks fail during insert queries on Iceberg tables.
How to reproduce:
```
set hive.support.concurrency=true;
set hive.txn.ext.locking.enabled=true;
set hive.txn.manager=org.apache.hadoop.hive.ql.lockmgr.DbTxnManager;
set hive.stats.autogather=true;
create table ice_t (i int) stored by iceberg tblproperties ('engine.hive.lock-enabled'='false');
insert into ice_t values (1);
```
StatsTask Fail:
```
2025-03-27T12:54:00,304 INFO [Thread-108] stats.BasicStatsTask: [Warning] could not update stats.Failed with exception Unable to alter table. org.apache.iceberg.hive.LockException: Timed out after 182005 ms waiting for lock on default.ice_t
```
HIVE_LOCKS …
=> HIVE-28851: HiveIcebergMetaHook acquires an HMS lock, regardless of the config and operations

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/Warehouse.java
Fix logging for invalid partition path.
The currently referenced `currPath` is modified before logging, which makes the warning logs meaningless.
```
LOG.warn("Cannot create partition spec from " + currPath + "; missing keys " + requiredKeys);
```
```
21:15:43.814 pool-1-thread-1-ScalaTest-running-InsertSuite WARN warehouse: Cannot create partition spec from file:/; missing keys [b]
```
Minor, the user could see the invalid partition path from logs after this change.
No.
Example of logs for invalid partition path.
```
10:58:14.949 pool-1-thread-1-ScalaTest-running-InsertSuite WARN warehouse: Cannot create partition spec from file:/Users/chengpan/Projects/ne-spark-3.3/target/tmp/warehouse-7c577ad7-5270-430c-b93e-44f8a369aa0f/hive_table/.hive-staging_hive_2025-03-31_19-58-14_723_101934466858 …
```
=> HIVE-28857. Fix logging for invalid partition path

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/security/TokenStoreDelegationTokenSecretManager.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/security/TestTokenStoreDelegationTokenSecretManager.java
No
No
Tested on a cluster with kerberos enabled and also added a UT
=> HIVE-28797: Hive Delegation Token Renewal fails for any kerberos principal user other than hive user

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/test/queries/clientpositive/cbo_windowing_aggregate.q, ql/src/test/results/clientpositive/llap/cbo_windowing_aggregate.q.out
When generating the CBO plan of a query which contains window function calls Hive first creates a `HiveProject` contains the window function calls. Alongside a `RowResolver` object is created based on the `RowResolver` of the input operator of this new `HiveProject`. The source operator might contain more complex expressions not just column references and this information is not carried to the new `RowResolver`. This patch adds the missing setting.
Although having redundant Group by keys doesn't change the semantics of the query it is not forbidden. However Hive throws `SemanticsException` with the message ambiguous column reference. This is caused by that the RowResolver created by the window function handler in the CBO doesn't expect more complex expressions than a column reference. …
=> HIVE-28878: Query with window function and redundant GROUP BY key fails during compilation

hbase-handler/pom.xml, itests/qtest-druid/pom.xml, packaging/src/license/licenses.xml, pom.xml, service/pom.xml, standalone-metastore/pom.xml
Removal of jetty-runner dependency 
Not jetty-runner as a whole was needed only tomcat-jasper was required
No
No
on local machine, I tested it for successful mvn build and testing it with hive-precommit-tests .
=> HIVE-28856: Remove Jetty-Runner

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveUnixTimestampSqlOperator.java, ql/src/test/queries/clientpositive/cbo_join_transitive_pred_loop_1.q, ql/src/test/queries/clientpositive/materialized_view_rewrite_12.q, ql/src/test/queries/clientpositive/materialized_view_rewrite_by_text_10.q, ql/src/test/queries/clientpositive/partition_unix_timestamp.q, ql/src/test/results/clientpositive/llap/cbo_filter_proj_transpose_noinputref.q.out, ql/src/test/results/clientpositive/llap/cbo_join_transitive_pred_loop_1.q.out, ql/src/test/results/clientpositive/llap/materialized_view_rewrite_12.q.out, ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_10.q.out, ql/src/test/results/clientpositive/llap/partition_unix_timestamp.q.out
* Make `UNIX_TIMESTAMP` not a dynamic function to enable Calcite evaluate it compile time.
* Make `UNIX_TIMESTAMP` `HiveSqlFunction`. `HiveSqlFunction` has a property `isRuntimeConstant` which helps identify functions not allowed in materialized view definitions which are enabled for automatic query rewrite.
If `UNIX_TIMESTAMP` is used in a partition filter expression, the expression is pushed to HMS to load all partitions that satisfy the filter. However, in this case, `UNIX_TIMESTAMP` cannot be evaluated because `SessionState` returns null. This results in a `NullPointerException`, which causes a CBO failure on the HS2 side.
No, but more optimizations might be applied because of CBO.
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver …
```
=> HIVE-27291: Constant reduction in CBO does not work for UNIX_TIMESTAMP

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/reexec/TestReExecuteKilledTezAMQueryPlugin.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/AbstractJdbcTriggersTest.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/AbstractTestJdbcGenericUDTFGetSplits.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/BaseJdbcWithMiniLlap.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestKillQueryWithAuthorizationDisabled.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestTriggersMoveWorkloadManager.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestTriggersWorkloadManager.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestWMMetricsWithTrigger.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/miniHS2/StartMiniHS2Cluster.java
Removed an mkdir from MiniHS2 initialization.
I didn't find why it was needed (introduced in the original MiniHS2 patch), and the whole thing works without it (but caused an NPE in LOCALFS_ONLY mode.
No.
No.
Worked with LLAP/TEZ/LOCALFS_ONLY, ran a simple query that needs tez session (I was assuming that the staging dir hack I removed was needed for tez apps):
```
CREATE TABLE test_part(id int) PARTITIONED BY(dt string) STORED AS ORC;
INSERT INTO test_part VALUES (1, '1'),(2, '2');
```
locafs_only
```
mvn clean install -Dtest=StartMiniHS2Cluster -DminiHS2.conf="target/testconf/llap/hive-site.xml"  -DminiHS2.run=true -DminiHS2.usePortsFromConf=true -pl itests/hive-unit -Pitests -DminiHS2.clusterType=LOCALFS_ONLY
```
llap
```
mvn clean install -Dtest=StartMiniHS2Cluster …
```
=> HIVE-28802: NPE in MiniHS2 with miniHS2.clusterType=LOCALFS_ONLY

iceberg/iceberg-handler/src/test/queries/positive/col_stats.q, iceberg/iceberg-handler/src/test/results/positive/col_stats.q.out, ql/src/java/org/apache/hadoop/hive/ql/stats/ColumnStatisticsObjTranslator.java, ql/src/test/results/clientpositive/llap/temp_table_display_colstats_tbllvl.q.out
Transform the column name in ColumnStatsObj to lowercase
NullPointerException Fix
No
No
q test
=> HIVE-28886: CalcitePlanner throws NullPointerException when column name case in ColumnStatisticsObj differs from the table schema

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/test/queries/clientnegative/cbo_ambiguous_colref_in_gby.q, ql/src/test/results/clientnegative/cbo_ambiguous_colref_in_gby.q.out
Check for ambiguity when building expressions of group by keys.
Ambiguous column references are not detected.
Yes, exception is thrown when ambiguous column references are found in group by key expressions.
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestNegativeLlapLocalCliDriver -Dqfile=cbo_ambiguous_colref_in_gby.q -pl itests/qtest -Pitests
```
=> HIVE-28881: Ambiguous column reference is not detected in GROUP BY query.

.github/pull_request_template.md, .github/workflows/build.yml
1. Avoid forcing contributors to upload the dependency tree, which can also be wrong or obsolete. 
2. Avoid having to check and fill an extra field on every submitted PR.
No
No
Inspect output of the macOs (JDK 8) action and verify that dependency tree is shown in the logs.
=> HIVE-27424: Display dependency:tree in GitHub actions

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
Fix the sql in direct SQL implement of `aggrStatsUseDB`.
https://github.com/apache/hive/pull/4744 remove `PARTITION_NAME` column from `PART_COL_STATS` table, it would throw exception now:
```bash
java.sql.SQLSyntaxErrorException: Unknown column 'PARTITION_NAME' in 'where clause'
```
No.
No.
Add unit test:
```bash
mvn test -Dtest.groups= -Dtest=org.apache.hadoop.hive.metastore.TestObjectStore#testAggrStatsUseDB -pl :hive-standalone-metastore-server
```
=> HIVE-28902: Fix unknown column PARTITION_NAME in aggrStatsUseDB

beeline/src/java/org/apache/hive/beeline/schematool/HiveSchemaTool.java
Check [HIVE-28897](https://issues.apache.org/jira/browse/HIVE-28897), for the details
To prevent ERROR logs in schematool if `hive.hook.proto.base-directory` and `tez.history.logging.proto-base-dir` is not set, which could be misleading
NO
NO
On local single node cluster.
=> HIVE-28897: Set logging level to warn for missing proto.base-directory when running schematool

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveDeleteFilter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergRecordReader.java
Refactor Iceberg iterators
Close method is missing in a few places + release the resources sooner (use try-with-resources in a batch iterator)
No
No
Existing tests + manual
=> HIVE-28843: Iceberg iterators refactor

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PersistenceManagerProvider.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/datasource/TestDataSourceProviderFactory.java
The secondary connection factory is used for schema generation, and for value generation operations. Under normal circumstances 2 connections should be sufficient, and currently it is hardcoded to that value. We have found in [HIVE-28839](https://issues.apache.org/jira/browse/HIVE-28839) that connection starvation may still happen. (in that case due to a datanucleus bug)
We should make the "objectstore-secondary" pool size configurable. This is needed at least until a final fix is not available for [HIVE-28839](https://issues.apache.org/jira/browse/HIVE-28839), but probably it is good to have on the long run if we hit other edge cases.
The "objectstore-secondary" pool size is currently hardcoded to 2.
The "datanucleus.connectionPool.maxPoolSize" controls the "objectstore" poolsize, I …
=> HIVE-28900: Make the objectstore-secondary connection pool size configurable

iceberg/pom.xml, itests/qtest-accumulo/pom.xml, itests/qtest-kudu/pom.xml, pom.xml, ql/pom.xml, ql/src/java/org/apache/hadoop/hive/ql/exec/MapJoinOperator.java, ql/src/java/org/apache/hadoop/hive/ql/exec/SerializationUtilities.java, ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java, ql/src/java/org/apache/hadoop/hive/ql/exec/persistence/HybridHashTableContainer.java, ql/src/java/org/apache/hadoop/hive/ql/exec/persistence/KeyValueContainer.java, ql/src/java/org/apache/hadoop/hive/ql/exec/persistence/ObjectContainer.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/ExternalCache.java, ql/src/java/org/apache/hadoop/hive/ql/io/sarg/ConvertAstToSearchArg.java, ql/src/java/org/apache/hadoop/hive/ql/stats/fs/FSStatsAggregator.java, ql/src/java/org/apache/hadoop/hive/ql/stats/fs/FSStatsPublisher.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFIn.java
Change Kryo dependency from `com.esotericsoftware:kryo` to `com.esotericsoftware.kryo:kryo5`
Allow Kryo versions 4.0.x and 5.0.x to coexist without conflict.
No
Using existing unit tests. The patch does not introduce new functionality.
=> HIVE-28915: Use com.esotericsoftware.kryo:kryo5

standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestMetastoreTransformer.java
Change the database path for TestMetastoreTransformer
The TestEmbeddedHiveMetaStore test runs fine when it is launched individually, but it fails on some CI runs cause it conflicts with state from TestMetastoreTransformer. The two tests are trying to create a directory for the database at the same path which leads to failures.
No
```
mvn test -Dtest=TestEmbeddedHiveMetaStore,TestMetastoreTransformer -Dtest.groups= -pl standalone-metastore/metastore-server
mvn test -Dtest=TestMetastoreTransformer,TestEmbeddedHiveMetaStore -Dtest.groups= -pl standalone-metastore/metastore-server
```
=> HIVE-28929: TestEmbeddedHiveMetaStore#testAlterTable fails while trying to create managed directory

ql/src/test/queries/clientpositive/archive_drop.q, ql/src/test/results/clientpositive/llap/archive_drop.q.out, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/Warehouse.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
When drop archived partition/table, only the original path of partition should be considered as a deletion candidate
Hadoop archived path is not supported to be deleted, in current implement the drop_partition/table calls would drop metadata successfully but throw exception when deleting the archived paths.
No.
No.
- Add a qtest
```bash
mvn test -pl itests/qtest -Pitests -Dtest=org.apache.hadoop.hive.cli.TestMiniLlapLocalCliDriver -Dqfile=archive_drop.q
```
- Test locally by sql:
```sql
-- create a table
create table tbl (id int) partitioned by (dt date, region string);
SET hive.execution.engine=mr;
insert overwrite table tbl partition (dt='2025-01-01', region='us') select 1;
insert overwrite table tbl partition (dt='2025-01-01', region='sg') select 2;
-- change to managed table
ALTER …
```
=> HIVE-28903: Skip deleting archived path when drop partition/table

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java
Use session configuration to create `storageHandler` in `PlanUtils.configureJobPropertiesForStorageHandler()` instead of instantiating `Hive` and using it to get configuration.
Creating new instance of `Hive` is a heavy weight operation and it does not give correct HiveConf anyway.
No
Existing tests
=> HIVE-28934: PlanUtils.configureJobPropertiesForStorageHandler should use hive session configuration.

common/src/java/org/apache/hive/http/HttpServer.java, hcatalog/webhcat/svr/src/main/java/org/apache/hive/hcatalog/templeton/Main.java, itests/hive-unit/src/test/java/org/apache/hive/service/TestHttpServices.java, service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpCLIService.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
Disable send server version and `x-powered-by` properties when configuring Jetty.
Exposing the Jetty version in the header is considered a security issue.
No.
1. Manually:
Set `hive.in.test` to `false` in `/data/conf/tez/hive-site.xml` temporary and run
```
mvn test -Dtest=StartMiniHS2Cluster -DminiHS2.clusterType=Tez -DminiHS2.run=true -DminiHS2.usePortsFromConf=true -DminiHS2.conf="target/testconf/tez/hive-site.xml" -Dpackaging.minimizeJar=false -T 1C -DskipShade -Dremoteresources.skip=true -Dmaven.javadoc.skip=true -Denforcer.skip=true -pl itests/hive-unit -Pitests
```
then open a browser and go to the page: 
```
localhost:10002
```
and inspect the Http response headers using the browsers inspect function. It should not contain properties `Server` and `x-powered-by`
2. Automated …
=> HIVE-28653: Jetty version disclosure in Hive

packaging/src/docker/build.sh, packaging/src/docker/entrypoint.sh
This pull request addresses several static analysis issues identified in the shell scripts located in the `packaging` folder. The issues were detected using ShellCheck and include:
1. **SC2086**: Double quote to prevent globbing and word splitting. Link to [SC2086](https://github.com/koalaman/shellcheck/wiki/SC2086)
2. **SC2125**: Brace expansion is not supported in POSIX sh. Link to [SC2125](https://github.com/koalaman/shellcheck/wiki/SC2125)
3. **SC2223**: This default assignment may cause problems when concatenating strings. Link to [SC2223](https://github.com/koalaman/shellcheck/wiki/SC2223)
These changes are necessary to ensure that the shell scripts in the `packaging` folder adhere to best practices and avoid potential issues related to globbing, word splitting, brace expansion, and …
=> HIVE-28937: Static analysis issues fixed in shell scripts

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveCalciteUtil.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveJoinPushTransitivePredicatesRule.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/test/queries/clientpositive/cbo_join_transitive_pred_loop_1.q, ql/src/test/queries/clientpositive/cbo_join_transitive_pred_loop_2.q, ql/src/test/queries/clientpositive/cbo_join_transitive_pred_loop_3.q, ql/src/test/queries/clientpositive/cbo_join_transitive_pred_loop_4.q
1. Remove code that is not actively used by existing tests.
2. Drop redundant config property that is not released yet.
No, cause anyways the disjunctive predicate pushdown currently happens irrespective the value of the property.
```
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile_regex="cbo_join_transitive_pred.*"
mvn test -Dtest=TestTezTPCDS30TBPerfCliDriver -Dtest.output.overwrite
```
=> HIVE-28924: Drop hive.optimize.join.disjunctive.transitive.predicates.pushdown and related logic

pom.xml
Upgrade commons-io to 2.16.1
CVE Fixes.[Dep Tree](https://issues.apache.org/jira/secure/attachment/13076422/mvn_dependency_tree1.txt)
No
Locally Built.Relying on pre-commits
=> HIVE-28946:Upgrade commons-io to 2.16.1

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorUtil.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MRCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/StatsUpdater.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestStatsUpdater.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/entities/CompactionInfo.java
Copy table properties and properties stored in compaction info to the HiveConf instance of Stats Updater
To support passing job configuration properties of compactor to the stats updater job
No.
```
mvn test -Dtest=TestStatsUpdater -pl ql
```
=> HIVE-28947: Add ability to specify Compaction options in stats updater of compactor

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergMergeTaskProperties.java, iceberg/iceberg-handler/src/test/queries/positive/ctas_iceberg_partitioned_orc.q, iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_partitioned_orc.q.out, ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java, ql/src/java/org/apache/hadoop/hive/ql/plan/DynamicPartitionCtx.java, ql/src/java/org/apache/hadoop/hive/ql/plan/FileSinkDesc.java, ql/src/java/org/apache/hadoop/hive/ql/plan/MergeTaskProperties.java
Make Iceberg writer configurable
Write optimization
No
Cluster + iceberg_merge_files.q
=> HIVE-25948: Optimize Iceberg writes by directing records either to Clustered or Fanout writer

common/src/test/org/apache/hadoop/hive/conf/HiveConfForTest.java
Use the same hive.user.install.directory for all tests in the same module that make use of HiveConfForTest objects.
1. Stabilize CI and reduce failures related to ephemeral storage
2. Avoid disk exhaustion and cryptic errors due to the filesystem running low on space
Having a distinct installation directory for each HiveConfForTest object leads to copying the hive-exec*jar (87MB) multiple times necessitating large amounts of disk space. The hive-exec.jar does not change so there is no reason to keep separate copies and it is just wasting space.
No
```
mvn clean test -Dtest=TestTxnCommands*
```
Manually check and ensure that there are not multiple copies of hive-exec.jar under the target directories.
```
find . -name "*jar"
./target/tmp/user_install_dir/zabetak/.hiveJars/hive-exec-4.1.0-SNA …
```
=> HIVE-28955: Tests using HiveConfForTest and Tez engine consume large amounts of disk space

Jenkinsfile, pom.xml
Previously the maven artifacts were stored under .git/.m2 directory. In terms of functionality the exact location (.git/.m2 vs .m2) does not matter. However, putting the artifacts under the .git folder can lead into confusion and false conclusions for people not very familiar with the specificities of the CI.
For instance, someone who is not gonna look into detail on what is present under the .git directory may think that the .git data for the project are huge. Using commands such as `du -h --max-depth=1`, which is also used in some places by the CI, can endorse such false impressions.
Moreover, the .m2 directory is a more common place for storing the maven artifacts in CI/CD pipelines.
No
* Ensure tests run fine
* Inspect CI logs especially those related to `du -h --max-depth=1` command
=> HIVE-28968: In CI use dedicated project-local .m2 directory for storing maven artifacts

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Relocate the prefix of Iceberg REST Catalog properties.
https://issues.apache.org/jira/browse/HIVE-28841
Two reasons.
- The current one is not inconsistent with the constant names, e.g., ICEBERG_CATALOG_SERVLET_FACTORY
- The word "catalog" is too common and might be confusing
No. HMS Iceberg catalog has not been released
No
We have integration tests
=> HIVE-28841: Rename hive.metastore.catalog.* to hive.metastore.iceberg.catalog.*

packaging/src/docker/entrypoint.sh
…se is explicitly set
This commit avoids appending the --verbose flag when it's not explicitly set, preventing invalid arguments from being passed during metastore startup.
When VERBOSE is not set, an empty string argument ("") is passed to the startup command, which causes a parsing error. 
No
**Docker commands:**
**Without Verbose:**
docker run -d -p 9083:9083 --env SERVICE_NAME=metastore --name metastore-standalone apache/hive:${HIVE_VERSION}
**With Verbose:**
docker run -d -p 9083:9083 --env SERVICE_NAME=metastore --env VERBOSE="true" --name metastore-standalone apache/hive:${HIVE_VERSION}
=> HIVE-28973: Metastore service in Docker fails to start unless --verbose is explicitly set

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlInsertPart.java
Please check [HIVE-28971](https://issues.apache.org/jira/browse/HIVE-28971), for more details.
ERROR Message:
```
2025-05-26 23:07:36,111 WARN metastore.ObjectStore: Falling back to ORM path due to direct SQL failure (this is not an error): class javax.jdo.identity.LongIdentity cannot be cast to class org.datanucleus.identity.DatastoreId (javax.jdo.identity.LongIdentity and org.datanucleus.identity.DatastoreId are in unnamed module of loader 'app') at org.apache.hadoop.hive.metastore.DirectSqlInsertPart.addPartitions(DirectSqlInsertPart.java:758) at org.apache.hadoop.hive.metastore.MetaStoreDirectSql.addPartitions(MetaStoreDirectSql.java:516) at org.apache.hadoop.hive.metastore.ObjectStore$7.getSqlResult(ObjectStore.java:2747)
```
To leverage directSql for _msck repair_ command
NO
On …
=> HIVE-28971: DirectSql for msck repair is failing because of wrong casting

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/model/MColumn.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/model/MColumnDescriptor.java
HMS performace degradation post HIVE-28909 for alter table cascade, with this PR the alter query in this Jira runs ~30X faster against the master, and 5X faster without the HIVE-28909 on my local. This also saves the entries stored in back db, before (with or without HIVE-28909) it has 4 million entries in COLUMNS_V2, now it's only about ~800 records.
Why the performance degradation post HIVE-28909?
With HIVE-28909, the column is inserted to the db one by one per partition, before that the partition's columns are added in a batch. With this PR, all the partitions refer to the same MColumnDescriptor the table holds, so no more column is inserted per partition.
No
Current unit tests
=> HIVE-28972: HMS performace degradation post HIVE-28909 for alter query

itests/hive-unit/src/test/java/org/apache/hive/service/auth/saml/TestHttpSamlAuthentication.java
Disabled TestHttpSamlAuthentication temporarily.
It hangs and blocks precommit.
No.
Precommit passed.
=> HIVE-29009: Intermittent CI timeouts while running tests - disable TestHttpSamlAuthentication

packaging/src/docker/README.md, packaging/src/docker/conf/hive-site.xml, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-rest-catalog/pom.xml, standalone-metastore/metastore-server/pom.xml, standalone-metastore/metastore-server/src/assembly/bin.xml, standalone-metastore/metastore-server/src/docker/Dockerfile, standalone-metastore/metastore-server/src/docker/README.md, standalone-metastore/metastore-server/src/docker/build.sh, standalone-metastore/metastore-server/src/docker/conf/metastore-log4j2.properties, standalone-metastore/metastore-server/src/docker/conf/metastore-site.xml, standalone-metastore/metastore-server/src/docker/docker-compose.yml, standalone-metastore/metastore-server/src/docker/entrypoint.sh
Lightweight Docker image for the Hive Metastore
Simplified ddeployment
No
Locally
=> HIVE-27275: Provide docker image for HMS

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Correct assignment of metastore object count metrics.
[HIVE-26701](https://issues.apache.org/jira/browse/HIVE-26701) enhanced metrics for connection pools. It also included some refactoring of existing metrics code in `HMSHandler`. It appears that this change accidentally swapped some metric names, so that `total_count_dbs` counts tables, `total_count_tables` counts partitions and `total_count_partitions` counts databases.
Yes, previous mismatched total metrics will now show correctly.
Manual testing.
=> HIVE-29010: Correct assignment of metastore object count metrics

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
This is to fix the wrong data type logged in the error, when table is created with smallint, tinyint datatypes
wrong data type in error message
Yes
Existing tests, and one updated test testCreateTableWithNotSupportedTypes()
=> HIVE-29013: [ICEBERG] Data type info is not correct in Error message for tinyint, smallint

Jenkinsfile
1. Disable maven's quiet mode (-q) and use default logging for running tests
2. Remove Surefire's logger configuration since defaults should work just fine
Display INFO logs from the tests that are running
No, only CI output is affected.
Manually inspect logs from the CI run.
=> HIVE-29008: CI logs do not display information about test execution

common/pom.xml
Check [HIVE-29001](https://issues.apache.org/jira/browse/HIVE-29001), duplicate dependency of mockito throwing maven warning during build
To have a clean maven build output :-)
NO
Will see CI output
=> HIVE-29001: Remove duplicate mockito dependency in hive-common pom causing maven warnings

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/session/SessionStateUtil.java
Enable conflict detection filter only when plan contains 1 TableScan Operator for a table
BugFix
No
Cluster + locally
https://issues.apache.org/jira/secure/attachment/13076866/iceberg_atomic_merge_update.q
=> HIVE-28987: Iceberg: A faulty query predicate can compromise transaction isolation

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-rest-catalog/src/main/java/org/apache/iceberg/rest/HMSCachingCatalog.java
Remove caching on the Iceberg REST API server. It's mainly because the current code didn't work with caching correctly, as stated in HIVE-29016.
This is an alternative to https://github.com/apache/hive/pull/5871
Disable caching.
No. This feature is not yet shipped.
Unit test
=> HIVE-29016: Disable caching on the Iceberg REST Catalog

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Restore configuration `metastore.initial.metadata.count.enabled` to prevent metastore metrics startup queries
For releases as late as Hive 2.3.10, there was support for a `metastore.initial.metadata.count.enabled` configuration property. This could be set to `false` to prevent running queries to determine the counts of existing databases, tables and partitions. In large-scale ephemeral/serverless deployments with many HiveMetaStore processes starting up, this can be a source of unnecessary load spikes on the database. It appears this property was accidentally removed during the Standalone Metastore separation work, specifically in the [HIVE-17307](https://issues.apache.org/jira/browse/HIVE-17307) metrics refactoring.
Yes, this restores the ability to control configuration for whether or …
=> HIVE-29017: Restore ability to prevent metastore metrics startup queries

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-rest-catalog/src/main/java/org/apache/iceberg/rest/HMSCatalogFactory.java, standalone-metastore/metastore-rest-catalog/src/test/java/org/apache/iceberg/rest/TestRESTCatalogJwtAuth.java, standalone-metastore/metastore-rest-catalog/src/test/java/org/apache/iceberg/rest/TestRESTCatalogNoneAuth.java, standalone-metastore/metastore-rest-catalog/src/test/java/org/apache/iceberg/rest/TestRESTCatalogSimpleAuth.java, standalone-metastore/metastore-rest-catalog/src/test/java/org/apache/iceberg/rest/extension/HiveRESTCatalogServerExtension.java, standalone-metastore/metastore-server/src/docker/conf/metastore-site.xml, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PropertyServlet.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ServletSecurity.java
This PR would add a new authentication mode, NONE, to the Iceberg REST Catalog API. The currently supported SIMPLE and JWT are not central authentication. It is inherited from another Hive servlet. It appears that NONE and OAuth2 are widely used.
To acquire test users.
No. The feature has not been shipped.
Unit and integration tests
=> HIVE-28998: Support Iceberg REST Catalog without authentication

Jenkinsfile
1. Reduce the disk space occupied by the .git directory in CI
2. Speed up checkout times
Pull-requests are now limited to 50 commits (value of depth parameter). When the number of commits exceeds this number the CI run will abort since it will not be able to merge the PR branch with master. Affected PRs can either temporarily increase the value of the depth parameter or squash some commits together.
Manually inspect output of `du` command in pipeline logs
=> HIVE-28969: Use shallow clone with limited depth to reduce .git directory size

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlInsertPart.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdatePart.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetastoreDirectSqlUtils.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/VerifyingObjectStore.java
=> HIVE-29030: Alter partition change column cannot use the direct sql

ql/src/java/org/apache/hadoop/hive/ql/queryhistory/repository/IcebergRepository.java
Set history.expire.max-snapshot-age-ms for query history table upon creation.
To let the service (introduced in [HIVE-28930](https://issues.apache.org/jira/browse/HIVE-28930)) expire snapshots of this table.
No.
No.
Final patch wasn't tested separately, but table property was tested in the early stages of the patch.
=> HIVE-28793: Set default expiry time for query history snapshots

itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestTezTPCDS30TBPerfCliDriver.java, itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliAdapter.java, itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CoreCliDriver.java, itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestMetaStoreHandler.java
1. Move metastore/container destroy logic in buildClassRule of CliAdapter. All database/container lifecyle handling must be in the same place to avoid leaks and inconsistent behavior.
2. Rename QTestMetastoreHandler#afterTest to QTestMetastoreHandler#truncateDatabase to better reflect what is actually doing
3. Perform database truncation (Derby only) only inside buildTestRule. No need to do it also as part of the class rule
4. Handle metastore configuration exclusively in buildClassRule. We need to set the configuration only once before the first test runs and this is exactly what happens if we put it in the class rule.
5. Drop firstTestNotYetRun flag along with related code since there is no longer overlapping logic between test and class rule.
6. Drop now redundant …
=> HIVE-29051: TestTezTPCDS30TBPerfCliDriver leaks Postgres container causing intermittent failures elsewhere

itests/hive-unit/src/test/java/org/apache/hive/service/TestHttpServices.java, pom.xml
Adjust httpclient5 httpcore dependencies in TestHttpServices
https://github.com/richardantal/hive/pull/new/HIVE-29047
In TestHttpServices we use transitive httpclient5 and httpcore5 dependencies because of
https://github.com/apache/hive/commit/174ac6215a2b70c655d3dcfed3dc0001ecb97b9b
Later It will break in case of 1.26 avatica version
No.
I ran TestHttpServices unit test
=> HIVE-29047: Adjust httpclient5 httpcore dependencies in TestHttpServices

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/compaction/IcebergTableOptimizer.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestIcebergCompactorOnTez.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/AcidTableOptimizer.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionException.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorThread.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MetaStoreCompactorThread.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/RemoteCompactorThread.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/TableOptimizer.java, ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Iceberg auto compaction. In this initial version, `IcebergInitiator` remembers the last checked snapshot id of all Iceberg tables and it compares the current snapshot id to the cached snapshot id to determine if further evaluation is needed.
Currently, Iceberg compaction can only be triggered manually.
This PR introduces automatic Iceberg compaction which periodically checks all Iceberg tables and schedules compactions when necessary.
No
New unit tests, precommit tests.
=> HIVE-29028: Iceberg: Implement auto compaction

itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
HIVE-29055: TestHplSqlViaBeeLine#testHplSqlExitConditionHandler is broken and passes silently
Its just a test code change to correct a testcase related to exit handler feature testcase.
To properly test the exit handler feature.
No
_mvn test -Dtest=TestHplSqlViaBeeLine#testHplSqlExitConditionHandler -pl itests/hive-unit -Pitests_
=> HIVE-29055: TestHplSqlViaBeeLine#testHplSqlExitConditionHandler is broken and passes silently

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/conf/TestMetastoreConf.java
1. Move deprecated property registation in the existing static block
2. Drop constructors and variables related to deprecated keys in ConfVars
3. Drop DEPRECATED_TEST_ENTRY that is only useful for testing purposes and adapt existing tests
Improve performance & code maintenance.
Looping through ~400 ConfVars enumeration entries on every creation of a new Configuration entry is resource wasteful and unecessary. The deprecated properties are static and known at compile time so there is no reason to search and register them on every creation of a new Configuration instance. In addition, the presence of deprecation information inside the ConfVars enumeration leads to boilerplate code that is not really necessary.
No
Existing tests
=> HIVE-29046: Avoid unecessary perf overhead from handling deprecated properties in MetastoreConf

common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java, parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g, parser/src/test/org/apache/hadoop/hive/ql/parse/TestParseDriver.java, ql/src/java/org/apache/hadoop/hive/ql/parse/ScheduledQueryAnalyzer.java, ql/src/test/org/apache/hadoop/hive/ql/schq/TestScheduledQueryStatements.java
The changes proposed adds support for IF EXISTS while dropping a Scheduled Query
User wants a safety net while dropping a scheduled query and not straightaway get a NoSuchQueryObjectException
Now, user can add IF EXISTS while dropping Scheduled Query which would not throw an Exception when the Scheduled Query does not exist
I tested it on my local machine
=> HIVE-22810: Add drop scheduled query IF EXISTS support

conf/hive-env.sh.template, service/src/java/org/apache/hive/service/server/HiveServer2.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
Log the HS2 and HMS PID in their respective logs and give sample hms and hs2 HADOOP_OPTS in hive-env.sh.template.
During debugging prod issue, I saw the need for this.
1. If HMS/HS2 is crashing periodically then the heapdump will have the name in default format i.e. `java_pid14784.hprof`, it becomes difficult to identify whether it belongs to HMS or HS2 without loading it in any analyzer tool.
2. To get the gc logs for a particular HS2 or HMS crash requires extraction of timestamp from logs using text manipulation commands etc.
Yes, in HS2 and HMS logs PID will be logged
On local setup
=> HIVE-28983: Log HS2 and HMS PID and update hive-env.sh template

Jenkinsfile
Increase request and limit based on the disk usage stats gathered in a recent run.
Stabilize CI and avoid pod eviction.
No
1. Check CI finishes without pod eviction failures.
2. Monitor requests and limits in Google Cloud Console
=> HIVE-29081: CI fails intermittently cause some runs exceed ephemeral storage limits

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/SplitGrouper.java, ql/src/java/org/apache/hadoop/hive/ql/io/CombineHiveRecordReader.java, ql/src/java/org/apache/hadoop/hive/ql/io/HiveFileFormatUtils.java, ql/src/java/org/apache/hadoop/hive/ql/io/IOPrepareCache.java
Modified the modifier of the cache property in the SplitGroup class to make it non-static.
JIRA: https://issues.apache.org/jira/browse/HIVE-27944
Since the Properties object implement HashTable interface, all the methods of the HashTable interface are synchronised.
In a multi-threaded environment, a deadlock will occur when propA.equals(propB) and propB.equals(propA) occur at the same time.
The problem can be solved with minimal modification by changing SplitGroup.cache to a non-static property.
=> HIVE-27944: When HIVE-LLAP reads the ICEBERG table, a deadlock may occur.

ql/src/java/org/apache/hadoop/hive/ql/hooks/HiveHookEventProtoPartialBuilder.java, ql/src/test/org/apache/hadoop/hive/ql/hooks/TestHiveHookEventProtoPartialBuilder.java
Check [HIVE-29012](https://issues.apache.org/jira/browse/HIVE-29012) for the stacktrace. 
When protologging hook is enabled, it stores the query plan for a query as well. The conf object in ExplainTask is null for the "Hive Hook Proto Log Writer" thread.
No
Will see CI output + local single node setup/cluster testing
=> HIVE-29012: NPE in ExplainTask when protologging posthook is enabled

itests/hive-unit/src/test/java/org/apache/hive/service/auth/saml/TestHttpSamlAuthentication.java
The CI/JVM hang was caused by [JDK-8315422](https://bugs.openjdk.org/browse/JDK-8315422) but now CI is running on JDK 21.0.7+6-LTS so the problem no longer affects this branch.
Full details can be found under: https://issues.apache.org/jira/browse/HIVE-29009
No
1. Downloaded Zulu JDK 21.0.7+6 that is used in CI and set JAVA_HOME to point to it
2. Cloned https://github.com/zabetak/testcontainers-tls-hang-issue-10454
3. Run `for i in {1..100}; do mvn clean test; done` and confirmed it always pass
4. Setup Docker with TLS locally (using Docker-in-Docker) and run the problematic test 
```
mvn test -Dtest=TestHttpSamlAuthentication.java -Pitests -pl itests/hive-unit
```
=> HIVE-29009: Enable TestHttpSamlAuthentication since JDK-8315422 is fixed in JDK 21.0.5

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveUnionSimpleSelectsToInlineTableRule.java, ql/src/test/queries/clientpositive/udtf_with_unionall.q, ql/src/test/results/clientpositive/llap/udtf_with_unionall.q.out
HIVE-29029: When stack UDTF is used with UNION ALL throwing ClassCastException in CBO mode.
Ignore HiveUnionSimpleSelectsToInlineTableRule when stack UDTF is used with UNION ALL.
To fix the ClassCastException when stack UDTF is used with UNION ALL.
No
_mvn -Dtest=TestMiniLlapLocalCliDriver -Dqfile=udtf_with_unionall.q -pl itests/qtest -Pitests_
=> HIVE-29029: When stack UDTF is used with UNION ALL throwing ClassCastException in CBO mode.

ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/PartitionUtils.java, ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHive.java, ql/src/test/queries/clientpositive/alter_table_add_partition.q, ql/src/test/results/clientnegative/archive5.q.out, ql/src/test/results/clientnegative/default_partition_name.q.out, ql/src/test/results/clientpositive/llap/alter_table_add_partition.q.out
=> HIVE-29093 : Fix alter table add partition if DEFAULT_PARTITION_NAME propery is a substring of partitition value to be added

itests/hive-unit/pom.xml, itests/util/pom.xml, itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliAdapter.java, itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestMetaStoreHandler.java, pom.xml, ql/pom.xml, ql/src/test/org/apache/hadoop/hive/ql/lockmgr/ITestDbTxnManager.java, standalone-metastore/metastore-server/pom.xml, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/DatabaseRule.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Derby.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mariadb.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/MetastoreRuleFactory.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mssql.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mysql.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Oracle.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Postgres.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/PostgresTPCDS.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/tools/schematool/TestSchemaToolForMetastore.java, standalone-metastore/pom.xml
1. Use testcontainers library to manage the lifecycle of dockerized databases
2. Use the newest version of the library (1.21.3) everywhere
1. Reduce maintenance burden since we no longer have to manually craft and fix docker handling logic
2. Stabilize CI and by avoiding common problems as port conflicts, container leaks, etc., which are handled automatically by the library
3.  Enhance OS independence since we no longer call Runtime.exec methods. The underlying docker-java library takes care of using the appropriate APIs (REST, etc.)
No
```
mvn test -Dtest=TestMssql,TestDerby,TestMysql,TestOracle,TestPostgres -Dtest.groups= -Dverbose.schematool
```
=> HIVE-24419: Refactor junit database rules to exploit testcontainers

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, service/src/java/org/apache/hive/service/cli/thrift/RetryingThriftCLIServiceClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
Clean up of hive.metastore.server.tcp.keepalive property
since keepalive property is always true according to https://github.com/apache/thrift/blob/0.16.0/lib/java/src/org/apache/thrift/transport/TSocket.java#L78
and so cleanup of this property is required
Yes, no custom value can be set for hive.metastore.server.tcp.keepalive
local build
=> HIVE-28844: Clean up property hive.metastore.server.tcp.keepalive from Metastore

itests/hive-blobstore/pom.xml, itests/qtest-druid/pom.xml, pom.xml, ql/pom.xml
Avatica is tightly connected with Calcite so it doesn't make sense to manage it separately Moreover, there is no need to use the shaded avatica artifact since the latter pulls in tons of things that Hive doesn't need.
No product facing changes for Hive users.
However, due to the removal of the shaded avatica jar some classes will not be part hive-exec so maven projects that depend on hive-exec may run into `ClassNotFoundException` issues if they depend implicitly on code bundled in avatica.
1. Existing tests
2. Build the hive binaries using mvn clean install -DskipTests -Pdist
3. Deployed to local cluster in pseudo-distributed mode and run a bunch of queries
=> HIVE-29107: Drop avatica version management and use of shaded jars

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/HiveSplitGenerator.java
Check [HIVE-29037](https://issues.apache.org/jira/browse/HIVE-29037)
To correct the negative logging
No
On local setup
=> HIVE-29037: Negative elapsed time logging in HiveSplitGenerator

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelShuttle.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelShuttleImpl.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/jdbc/HiveJdbcConverter.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/PlanModifierForASTConv.java, ql/src/test/queries/clientpositive/cbo_self_join_ambiguous_alias_cte.q, ql/src/test/queries/clientpositive/cbo_self_join_ambiguous_alias_mv.q, ql/src/test/queries/clientpositive/cbo_self_join_ambiguous_alias_subquery.q, ql/src/test/results/clientpositive/llap/cbo_self_join_ambiguous_alias_cte.q.out, ql/src/test/results/clientpositive/llap/cbo_self_join_ambiguous_alias_mv.q.out, ql/src/test/results/clientpositive/llap/cbo_self_join_ambiguous_alias_subquery.q.out, ql/src/test/results/clientpositive/llap/external_jdbc_table2.q.out, ql/src/test/results/clientpositive/llap/external_jdbc_table4.q.out
1. Collect all table aliases under joins
2. Introduce derived table whenever the same alias appears more than once
Some queries that contain joins of the same table more than twice fail during compilation while trying to transform the optimized AST (obtained from CBO) to an Operator tree. The "Ambiguous table alias" exception is raised when a HiveJoin contains the same table scan multiple times (without an interleaving project) cause the generated AST is ambiguous.
No.
```
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile_regex=cbo_self_join.*
```
=> HIVE-28222: Ambiguous table alias exception for queries with self joins

ql/pom.xml
Incomplete package migration in [HIVE-28248](https://issues.apache.org/jira/browse/HIVE-28248)
In [HIVE-28248](https://issues.apache.org/jira/browse/HIVE-28248), opencsv was upgraded to v5.9 and its package changed from net.sf.opencsv to com.opencsv.
However, the hive-exec shaded jar configuration was not updated accordingly, and still references the old package.
This Jira updates the shading config to relocate com.opencsv correctly and remove leftover net.sf.opencsv entries.
No
The patch was tested in my cluster. Basically, one such scenario would fail where we create a table with OpenCSVSerde, push some values, followed by running a "Select count(*) from the table" in tez execution environment. On replacing the hive-exec jar, with the current change, the query runs successfully with …
=> HIVE-29154: Fix hive-exec shaded jar config for opencsv package change

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergSplit.java
We would replace the custom `blockLocations` with the one in apache/iceberg.
https://issues.apache.org/jira/browse/HIVE-29148
For consistency and maintainability.
No.
Unit and integration tests
=> HIVE-29148: Replace IcebergSplit#blockLocations with Iceberg's utility

ql/src/java/org/apache/hadoop/hive/ql/parse/TezCompiler.java, ql/src/test/results/clientpositive/llap/dynamic_semijoin_reduction_multicol.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query1.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query1b.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query24.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query64.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query80.q.out
This patch adds the missing parentheses in the calculation of the number of rows affected by Dynamic SemiJoin Reduction.
https://github.com/apache/hive/blob/df98c2e2f4e2370c603f8873f006ee8728afa8a6/ql/src/java/org/apache/hadoop/hive/ql/parse/TezCompiler.java#L1975
Without the parentheses, Hive sets `newNumRows` either to 1 or leaves it unchanged. This can lead to incorrect decisions about whether a SemiJoin branch is beneficial, potentially resulting in suboptimal query plans.
(FYI: In our 10TB TPC-DS experiment, we observed that the patch affected some query plans, but there was no change in query execution time.)
No
I manually checked the log files and verified that the number of rows is now computed correctly.
=> HIVE-29161: Correct the row count computation affected by Dynamic SemiJoin Reduction

ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/cte_mat_acid_1.q, ql/src/test/results/clientpositive/llap/cte_mat_acid_1.q.out
When validating Read and WriteEntities after semantic analysis Hive looks for transactional (ACID) tables and sets the `ValidWriteIdList` if any found. However only the main query's entities are checked.
This patch propose that all Read and WriteEntities should be checked by iterating through all the CTE's too.
When 
* CTE materialization is enabled
* and the CTE is materialized
* and the CTE definition references at least one ACID table
* and the main query doesn't reference any ACID table
the `ValidWriteIdList` is not set hence exception is thrown when executing the CTE materialization plan
No.
```
mvn test -Dtest.output.overwrite -Dtest=TestMiniLlapLocalCliDriver -Dqfile=cte_mat_acid_1.q -pl itests/qtest -Pitests
```
=> HIVE-29146: Query with WITH clause fails during split generation when CTE materaliazation is enabled

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java, ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHive.java, standalone-metastore/metastore-client/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java, standalone-metastore/metastore-client/src/main/java/org/apache/hadoop/hive/metastore/client/BaseMetaStoreClient.java, standalone-metastore/metastore-client/src/main/java/org/apache/hadoop/hive/metastore/client/HookEnabledMetaStoreClient.java, standalone-metastore/metastore-client/src/main/java/org/apache/hadoop/hive/metastore/client/MetaStoreClientWrapper.java, standalone-metastore/metastore-client/src/main/java/org/apache/hadoop/hive/metastore/client/ThriftHiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
In thrift api definition, HMS support to drop partitions by both partition names and expressions. But current api in `IMetaStoreClient` only support drop partitions by expressions, we should add new api to support drop partitions by names.
```java
// IMetaStoreClient.java
List<Partition> dropPartitions(String catName, String dbName, String tblName,
RequestPartsSpec partsSpec, PartitionDropOptions options)
throws NoSuchObjectException, MetaException, TException;
```
To improve the `dropPartitions` function.
Yes, user can use the new api to drop partitions by names.
No.
Add unit test:
```bash
mvn test -Dtest=org.apache.hadoop.hive.ql.metadata.TestHive -pl :hive-exec
```
=> HIVE-28219: Support drop partitions by names in IMetaStoreClient

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStatistics.java, iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_partition_evolution.q.out, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
Column stats predicate support
Perf enhancement
No
No
Existing tests
=> HIVE-29147: Iceberg: Table-level column stats filter support

Jenkinsfile
Set/Increase heapsize to 8GB for SonarScanner agent that runs in separate JVM
The reason is that the base branch (master) did not have a valid scan for over a month since the SonarScanner was consistently failing with OutOfMemoryError.
No
Tested the change using the "Replay" functionality on a previously failed job on master. Sonar step finished successfully in 21 minutes after setting the heap size to 8GB: https://ci.hive.apache.org/job/hive-precommit/job/master/2662/
=> HIVE-29180: SonarQube reports issues unrelated to changes in the pull request

Jenkinsfile
1. Run checkstyle in CI during the Sonar step
2. Upload checkstyle reports to Sonarqube
1. Report checkstyle violations in each PR as part of the Sonarqube report.
2. Prevent further degradation of code quality.
No impact to users. Developpers and reviewers will see new checkstyle violations when raising pull requests.
1. Tested by uploading results manually on a forked ([zabetak_hive](https://sonarcloud.io/project/issues?issueStatuses=OPEN%2CCONFIRMED&id=zabetak_hive)) sonarqube project.
2. Inspect Sonarqube report(s) uploaded through this pull-request.
=> HIVE-29196: Apply and report checkstyle issues via Sonarqube

accumulo-handler/pom.xml, hcatalog/core/pom.xml, hcatalog/hcatalog-pig-adapter/pom.xml, hcatalog/pom.xml, hcatalog/server-extensions/pom.xml, itests/hcatalog-unit/pom.xml, itests/qtest-accumulo/pom.xml, itests/util/pom.xml, packaging/pom.xml, packaging/src/main/assembly/beeline.xml, pom.xml, standalone-metastore/metastore-common/pom.xml, standalone-metastore/metastore-server/pom.xml, standalone-metastore/pom.xml, storage-api/pom.xml
Although Hive has moved to Jline3, 2.x was also getting shipped in packaging.
To have single Jline jar. Check [HIVE-29130](https://issues.apache.org/jira/browse/HIVE-29130) for more details
No
On local setup
=> HIVE-29130: Remove jline 2.x

data/scripts/cat.py, data/scripts/cat_error.py, data/scripts/doubleescapedtab.py, data/scripts/dumpdata_script.py, data/scripts/escapedcarriagereturn.py, data/scripts/escapednewline.py, data/scripts/escapedtab.py, data/scripts/input20_script.py, data/scripts/newline.py, hcatalog/bin/hcat.py, hcatalog/bin/hcat_server.py, hcatalog/bin/hcatcfg.py, hcatalog/src/test/e2e/templeton/inpdir/xmlmapper.py, hcatalog/src/test/e2e/templeton/inpdir/xmlreducer.py, service/lib/py/fb303_scripts/fb303_simple_mgmt.py, testutils/gen-report.py
Make the Python scripts compatible with Python 3 by changing `print ....` to `print(...)`, with some minor fixes where necessary.
Some q files use python scripts. However, the python scripts use syntax that is not compatible with Python 3. Python 2 is out-of-date (last release in 2020), and some operating systems do not provide packages anymore (e.g., Ubuntu LTS 24.04). The goal of this ticket is to make the scripts compatible with Python 3. 
No
Running `mvn test -pl itests/qtest -Pitests -Dtest=TestMiniLlapCliDriver -Dqfile=newline.q` locally.
=> HIVE-25817: Add parentheses to print statements for python3 compatibility

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java
(cherry picked from commit 333227fbd13821365cec1bdbfcb9314a239bea0f)
Note: this is not a full port: it is about porting some missing changes from the previous port especially for test cases.
Add missing ports from Iceberg in `TestHiveCommitLocks`.
It lead to flakyness on downstream. 
No
- Manually ran TestHiveCommitLocks
- Flaky job checker: https://ci.hive.apache.org/job/hive-flaky-check/903/
=> HIVE-29237: Addendum: Hive: Refactor commit lock mechanism from HiveTableOperations (#6648)
