- llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCacheImpl.java
- llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCachePolicy.java
- llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelLrfuCachePolicy.java
- llap-server/src/java/org/apache/hadoop/hive/llap/cache/MemoryManager.java
- llap-server/src/java/org/apache/hadoop/hive/llap/io/metadata/MetadataCache.java
Change-Id: Iadc5067e03ad3ce545d02080fa4b4f0da0aa7988
> [HIVE-21333] Purge the non locked buffers instead of locked ones

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestCreateUdfEntities.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/exec/spark/TestSparkStatistics.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHiveAuthorizerCheckInvocation.java
- ql/src/java/org/apache/hadoop/hive/ql/Driver.java
- ql/src/java/org/apache/hadoop/hive/ql/IDriver.java
- ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecDriver.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/spark/TestHiveSparkClient.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/spark/TestSparkPlan.java
- ql/src/test/org/apache/hadoop/hive/ql/hooks/TestHooks.java
- ql/src/test/org/apache/hadoop/hive/ql/io/TestSymlinkTextInputFormat.java
- ql/src/test/org/apache/hadoop/hive/ql/parse/TestColumnAccess.java
- ql/src/test/org/apache/hadoop/hive/ql/parse/TestHiveDecimalParse.java
- ql/src/test/org/apache/hadoop/hive/ql/plan/TestReadEntityDirect.java
- ql/src/test/org/apache/hadoop/hive/ql/plan/TestViewEntity.java
- ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHivePrivilegeObjectOwnerNameAndType.java
This reverts commit 2e7441f8317818b38a970493858b0ed296ffdda1.
> Revert "HIVE-21996 Remove unused code from Driver"

- streaming/src/java/org/apache/hive/streaming/HiveStreamingConnection.java
- streaming/src/test/org/apache/hive/streaming/TestStreaming.java
Change-Id: Ia5f94c34a044c2990e95204de03b661d162874c7
> HIVE-21146 Enforce TransactionBatch size=1 for blob stores

- .travis.yml
Build on newer OS (bionic) with OpenJDK8, remove unnecessary workaroud, update link
> [HIVE-23000] Improve travis.yml

- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDF.java
https://issues.apache.org/jira/browse/HIVE-22479
`Defered` corrected to `Deferred`
> HIVE-22479: Fix typo in GenericUDF

- Jenkinsfile
- shims/common/src/main/java/org/apache/hadoop/fs/ProxyFileSystem.java
- shims/common/src/main/java/org/apache/hadoop/fs/ProxyLocalFileSystem.java
- shims/common/src/main/java/org/apache/hadoop/hive/io/HdfsUtils.java
- shims/common/src/main/java/org/apache/hadoop/hive/shims/CombineHiveKey.java
- shims/common/src/main/java/org/apache/hadoop/hive/shims/HadoopShimsSecure.java
Change-Id: Ided89254e2464cf9a6f5ebfdce5c1f222988d18e
> HIVE-23629: Enforce clean findbugs in PRs

- Jenkinsfile
- storage-api/src/java/org/apache/hadoop/hive/common/ValidReadTxnList.java
- storage-api/src/java/org/apache/hadoop/hive/common/ValidReaderWriteIdList.java
- storage-api/src/java/org/apache/hadoop/hive/common/io/DataCache.java
- storage-api/src/java/org/apache/hadoop/hive/common/io/DiskRangeList.java
- storage-api/src/java/org/apache/hadoop/hive/common/io/encoded/EncodedColumnBatch.java
- storage-api/src/java/org/apache/hadoop/hive/common/type/FastHiveDecimal.java
- storage-api/src/java/org/apache/hadoop/hive/common/type/FastHiveDecimalImpl.java
- storage-api/src/java/org/apache/hadoop/hive/common/type/HiveIntervalDayTime.java
- storage-api/src/java/org/apache/hadoop/hive/common/type/RandomTypeUtil.java
- storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/BytesColumnVector.java
- storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/TimestampColumnVector.java
- storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedRowBatch.java
- storage-api/src/java/org/apache/hadoop/hive/ql/io/sarg/SearchArgumentImpl.java
- storage-api/src/java/org/apache/hadoop/hive/serde2/io/HiveDecimalWritable.java
- storage-api/src/java/org/apache/hadoop/hive/serde2/io/HiveDecimalWritableV1.java
- storage-api/src/java/org/apache/hive/common/util/BloomFilter.java
- storage-api/src/java/org/apache/hive/common/util/BloomKFilter.java
- storage-api/src/java/org/apache/hive/common/util/Murmur3.java
- storage-api/src/java/org/apache/hive/common/util/SuppressFBWarnings.java
- storage-api/src/test/org/apache/hive/common/util/TestMurmur3.java
Change-Id: I077246ec60b59ba6c65fd86e416040a6fab7d12c
> HIVE-23617: Fixing storage-api FindBug issues

- Jenkinsfile
- hcatalog/webhcat/svr/pom.xml
- itests/hive-jmh/pom.xml
- itests/hive-unit/pom.xml
- pom.xml
- storage-api/pom.xml
- testutils/ptest2/pom.xml
> HIVE-21790: Build Hive2 with JDK 1.8

- Jenkinsfile
- pom.xml
- shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
Change-Id: I9cb3c1e7fe7e8ed52dcbaf0413fe9777ae64f2f6
> HIVE-23686: Fix spotbugs issues in hive-shims

- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRawRecordMerger.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MinorQueryCompactor.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMajorQueryCompactor.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMinorQueryCompactor.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
- ql/src/test/org/apache/hadoop/hive/ql/io/TestAcidUtils.java
- ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java
- ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestOrcRawRecordMerger.java
- streaming/src/test/org/apache/hive/streaming/TestStreaming.java
HIVE-23495: AcidUtils.getAcidState cleanup
> HIVE-23495: AcidUtils.getAcidState cleanup

- ql/src/test/queries/clientpositive/fouter_join_ppr.q
- ql/src/test/results/clientpositive/llap/fouter_join_ppr.q.out
> HIVE-19545: Enable TestCliDriver#fouter_join_ppr.q

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
Added new metrics to the updateCompactionMetrics
Added new tests
> HIVE-23702: Add metastore metrics to show age of the oldest initiated compaction

- ql/src/java/org/apache/hadoop/hive/ql/util/HiveStrictManagedMigration.java
- ql/src/test/org/apache/hadoop/hive/ql/util/TestHiveStrictManagedMigration.java
> HIVE-23612: Option for HiveStrictManagedMigration to impersonate a user for FS operations

- pom.xml
> Revert "HIVE-23689: Bump Tez version to 0.9.2"

- serde/src/java/org/apache/hadoop/hive/serde2/avro/InstanceCache.java
Remove synchronization on cache retrieve have big performance impact
will be great to have in branch-3 also
> HIVE-19261: Avro SerDe's InstanceCache should not be synchronized on retrieve

- itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/hbase/TestPigHBaseStorageHandler.java
> HIVE-23762: ignore flaky tests

- standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CommitTxnRequest.java
- standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Types.php
- standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
- standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
- standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
> HIVE-23759: refactor field order of CommitTxnRequest

- llap-server/src/java/org/apache/hadoop/hive/llap/cache/BaseLlapDataBuffer.java
- llap-server/src/java/org/apache/hadoop/hive/llap/cache/FileCache.java
- llap-server/src/java/org/apache/hadoop/hive/llap/cache/LlapDataBuffer.java
- llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCacheImpl.java
- llap-server/src/java/org/apache/hadoop/hive/llap/cache/SerDeLowLevelCacheImpl.java
> HIVE-23741: Store CacheTags in the file cache level

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
Testing done:
```
mvn test -Dtest=TestAcidOnTez#testCtasTezUnion -pl itests/hive-unit -Pitests
```
> HIVE-19549: Enable TestAcidOnTez#testCtasTezUnion

- ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
> HIVE-23764: Remove unnecessary getLastFlushLength when checking delete delta files

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- common/src/java/org/apache/hadoop/hive/conf/Validator.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java
- ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
- service/src/java/org/apache/hive/service/cli/session/HiveSessionImpl.java
Change-Id: I8ce7061fde58fc94ee4750142f699e3cc23980fd
> HIVE-23699: Cleanup HIVEQUERYRESULTFILEFORMAT handling

- itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/MiniHiveKdc.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestAcidTableSetup.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHiveAuthorizerCheckInvocation.java
- itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java
- itests/util/src/main/java/org/apache/hive/jdbc/miniHS2/MiniHS2.java
- ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
- ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
- ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandlerNoConnectionPool.java
- ql/src/test/org/apache/hadoop/hive/ql/parse/TestUpdateDeleteSemanticAnalyzer.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/AcidEventListener.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/MetaStoreTestUtils.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestCatalogNonDefaultClient.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreSchemaMethods.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreAcidCleanup.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/minihms/RemoteMetaStoreForTests.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/ThrowingTxnHandler.java
Change-Id: Ica7666afe40cb0f0128266c9c3f6ebc560b24c0e
> HIVE-23780: Fail dropTable if acid cleanup fails

- itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/hbase/TestPigHBaseStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/MetricSink.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ReplicationMetricsMaintTask.java
> HIVE-23813 : Fix flaky tests due to JDO Exception

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/TestAcidTxnCleanerService.java
> HIVE-23525: TestAcidTxnCleanerService is unstable

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidOutputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRecordUpdater.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
Created a new configuration.
Checked the places where the _orc_acid_version constant were used
Created a unit test
> HIVE-23825: Create a flag to turn off _orc_acid_version file creation

- llap-client/src/java/org/apache/hadoop/hive/llap/IllegalCacheConfigurationException.java
- llap-client/src/java/org/apache/hadoop/hive/llap/io/api/LlapIo.java
- llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
- llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/OrcEncodedDataReader.java
- llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestOrcMetadataCache.java
> HIVE-23824

- itests/hive-blobstore/src/test/results/clientpositive/insert_into_dynamic_partitions.q.out
- itests/hive-blobstore/src/test/results/clientpositive/insert_overwrite_dynamic_partitions.q.out
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/SortedDynPartitionOptimizer.java
- ql/src/test/results/clientpositive/llap/auto_sortmerge_join_16.q.out
- ql/src/test/results/clientpositive/llap/dynpart_sort_opt_bucketing.q.out
- ql/src/test/results/clientpositive/llap/dynpart_sort_opt_vectorization.q.out
- ql/src/test/results/clientpositive/llap/dynpart_sort_optimization.q.out
- ql/src/test/results/clientpositive/llap/dynpart_sort_optimization_acid.q.out
- ql/src/test/results/clientpositive/llap/dynpart_sort_optimization_acid2.q.out
- ql/src/test/results/clientpositive/llap/llap_smb.q.out
- ql/src/test/results/clientpositive/llap/mm_dp.q.out
> HIVE-23822 Sorted dynamic partition optimization could remove auto stat task

- ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
- ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveMetaStoreChecker.java
> Fix unit tests ( TestHiveMetaStoreChecker and TestMiniLlapLocalCliDriver tests ) in master

- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/test/queries/clientpositive/windowing_windowspec4.q
- ql/src/test/results/clientpositive/llap/windowing_windowspec4.q.out
Change-Id: I2db8c379cf916b680e226b4a6e77832fb1e2317f
> HIVE-23868: Windowing function spec: support 0 preceeding/following

- llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapRecordReader.java
- ql/src/java/org/apache/hadoop/hive/llap/LlapHiveUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRawRecordMerger.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRecordUpdater.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcSplit.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
- ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestOrcRawRecordMerger.java
- ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestVectorizedOrcAcidRowBatchReader.java
Started to use new LLAP getOrcTailFromCache
Refactored stuff to use the tail instead of the reader related things
Added some unit tests for the new smaller components
> HIVE-23840: Use LLAP to get orc metadata

- standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/GetOpenTxnsRequest.java
- standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
- standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
- standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/OpenTxnList.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
- standalone-metastore/metastore-tools/tools-common/src/main/java/org/apache/hadoop/hive/metastore/tools/HMSClient.java
> HIVE-23881 : Deprecate get_open_txns to use get_open_txns_req

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtil.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcFile.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcOutputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtilities.java
> HIVE-23853: CRUD based compaction also should update ACID file version metadata

- data/files/cbo_t1.txt
- parser/src/test/org/apache/hadoop/hive/ql/parse/TestSpecialCharacterInTableNames.java
- parser/src/test/org/apache/hadoop/hive/ql/parse/TestSpecialCharacterInTableNamesQuotes.java
- ql/src/test/queries/clientpositive/special_character_in_tabnames_1.q
- ql/src/test/queries/clientpositive/special_character_in_tabnames_quotes_1.q
- ql/src/test/results/clientpositive/llap/special_character_in_tabnames_1.q.out
- ql/src/test/results/clientpositive/llap/special_character_in_tabnames_quotes_1.q.out
Testing done:
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=special_character_in_tabnames_quotes_1.q,special_character_in_tabnames_1.q -pl itests/qtest -Pitests
```
http://ci.hive.apache.org/job/hive-flaky-check/76/
http://ci.hive.apache.org/job/hive-flaky-check/77/
> HIVE-23888: Simplify special_character_in_tabnames_1.q

- .gitignore
Added VSCode files to gitignore
> HIVE-23875: Add VSCode files to gitignore

- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestRemoteHMSZKNegative.java
> HIVE-23797: Throw exception when no metastore found in zookeeper

- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/test/results/clientpositive/llap/create_view.q.out
- ql/src/test/results/clientpositive/llap/create_view_disable_cbo.q.out
- ql/src/test/results/clientpositive/llap/ppd_deterministic_expr.q.out
- ql/src/test/results/clientpositive/llap/ppd_field_garbage.q.out
- ql/src/test/results/clientpositive/llap/special_character_in_tabnames_1.q.out
- ql/src/test/results/clientpositive/llap/special_character_in_tabnames_quotes_1.q.out
- ql/src/test/results/clientpositive/llap/strict_managed_tables_sysdb.q.out
> HIVE-23849: Hive skips the creation of ColumnAccessInfo when creating a view

- serde/src/java/org/apache/hadoop/hive/serde2/lazybinary/LazyBinaryNonPrimitive.java
- serde/src/test/org/apache/hadoop/hive/serde2/lazybinary/TestLazyBinaryStruct.java
Copy of PR 450
https://github.com/apache/hive/pull/450
CC @belugabehr
> HIVE-20771:  LazyBinarySerDe fails on empty structs

- itests/src/test/resources/testconfiguration.properties
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveDefaultRelMetadataProvider.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelShuttleImpl.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveTezModelRelMetadataProvider.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/cost/HiveVolcanoPlanner.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveCardinalityPreservingJoinRule.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializationRelMetadataProvider.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewBoxing.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewRule.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
- ql/src/test/queries/clientpositive/perf/mv_query30.q
- ql/src/test/queries/clientpositive/perf/mv_query45.q
- ql/src/test/queries/clientpositive/perf/mv_query68.q
- ql/src/test/results/clientpositive/llap/schema_evol_text_vec_part_all_primitive.q.out
- ql/src/test/results/clientpositive/perf/tez/constraints/mv_query30.q.out
- ql/src/test/results/clientpositive/perf/tez/constraints/mv_query45.q.out
- ql/src/test/results/clientpositive/perf/tez/constraints/mv_query68.q.out
> HIVE-23878: Aggregate after join throws off MV rewrite

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveCardinalityPreservingJoinOptimization.java
- ql/src/test/results/clientpositive/llap/constraints_optimization.q.out
Testing done:
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=constraints_optimization.q -pl itests/qtest -Pitests
```
> HIVE-23908: Rewrite plan to join back tables: handle root input is an Aggregate

- service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java
> HIVE-23727: Improve SQLOperation log handling when canceling background

- ql/pom.xml
> HIVE-23847: Extracting hive-parser module broke exec jar upload in tez

- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/add/AlterTableAddPartitionOperation.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestTxnManager.java
- ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveMetaStoreClient.java
- ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveMetaStoreClientApiArgumentsChecker.java
- standalone-metastore/metastore-common/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreClient.java
> send tableId to get_partition APIs

- udf/src/java/org/apache/hadoop/hive/ql/exec/UDFArgumentException.java
> HIVE-23922: Improve code quality, UDFArgumentException.getMessage Method requires only two parameters

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskExecutorService.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSplits.java
Change-Id: I0f8d731d478417a244abe77d087a2248e4167b90
Add a HiveConf setting to include an external client ID to LLAP external client requests. The ID is also included in the external splits so that the ID can be shown in the LLAP executorsStatus.
> HIVE-23972: Add external client ID to LLAP external client

- jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/dao/DatabaseAccessorFactory.java
- jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/dao/HiveDatabaseAccessor.java
> HIVE-23302: Create HiveJdbcDatabaseAccessor for JDBC storage handler

- Jenkinsfile
- spotbugs/spotbugs-exclude.xml
Entire org.apache.hive.service.rpc.thrift package is generated files. We should ignore these when running spotbugs.
Change-Id: I0ec78853b50e3720976daf52a2efbc200047b281
> HIVE-23649: Spotbugs should ignore generated thrift files

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelOptUtil.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterJoinRule.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterProjectTransposeRule.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveJoinConstraintsRule.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveJoinSwapConstraintsRule.java
- ql/src/test/queries/clientpositive/join_constraints_optimization.q
- ql/src/test/results/clientpositive/llap/join_constraints_optimization.q.out
> HIVE-24087 FK side join elimination in presence of PK-FK constraint

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
If compaction fails with a TException or IOException (e.g. IOException from getAcidState which comes) after the compaction txn has been opened, the compaction is marked 'failed' but the compaction txn is never aborted.
We should abort an open compaction txn upon TExceptions/IOExceptions.
> HIVE-24096: Abort failed compaction's txn on TException or IOException

- bin/ext/strictmanagedmigration.sh
- ql/src/java/org/apache/hadoop/hive/ql/util/HiveStrictManagedMigration.java
- ql/src/test/org/apache/hadoop/hive/ql/util/TestHiveStrictManagedMigration.java
> HIVE-24134 : Revert removal of HiveStrictManagedMigration code

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
> HIVE-24160: Scheduled executions must allow state transition EXECUTING->TIMED_OUT

- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
- standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CommitTxnRequest.java
- standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CommitTxnRequest.php
- standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
- standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
- standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
Refactor CommitTxnRequest field order (keyValue and exclWriteEnabled).
HIVE-24125 introduced backward incompatible change.
> HIVE-24150: Refactor CommitTxnRequest field order

- streaming/src/java/org/apache/hive/streaming/TransactionBatch.java
The setupHeartbeat routine was being called before some variables
were initialized.
> HIVE-24077: Streaming Ingest v2 does not send heartbeats

- ql/src/test/org/apache/hadoop/hive/ql/metadata/TestSessionHiveMetastoreClientListPartitionsTempTable.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientWithLocalCache.java
> HIVE-24183: Clean up local HS2 HMS cache code

- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
https://issues.apache.org/jira/browse/HIVE-24082
> HIVE-24082: Expose information whether AcidUtils.ParsedDelta contains statementId

- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/SplitGrouper.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/TezCompiler.java
- ql/src/test/queries/clientpositive/auto_sortmerge_join_10.q
- ql/src/test/results/clientpositive/llap/auto_sortmerge_join_10.q.out
> HIVE-24198 : Map side SMB join is producing wrong result

- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/keyseries/VectorKeySeriesLongSerialized.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastLongHashUtil.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastTableContainer.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/optimized/VectorMapJoinOptimizedLongCommon.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
- ql/src/java/org/apache/hadoop/hive/ql/plan/VectorMapJoinDesc.java
- ql/src/test/queries/clientpositive/probedecode_static_keytype.q
- ql/src/test/results/clientpositive/llap/probedecode_static_keytype.q.out
- ql/src/test/results/clientpositive/llap/vector_partitioned_date_time.q.out
> HIVE-23852: add support for Date type in ReduceSink operator for native vector sink

- hcatalog/streaming/src/java/org/apache/hive/hcatalog/streaming/HiveEndPoint.java
- hcatalog/streaming/src/test/org/apache/hive/hcatalog/streaming/TestStreaming.java
> HIVE-21375 initial commit

- pom.xml
This PR aims to upgrade Apache ORC from 1.5.10 to 1.5.12.
This will bring the latest bug fixes.
No.
Pass the CI with the existing test cases.
> HIVE-24222: Upgrade ORC to 1.5.12

- llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskExecutorService.java
- llap-server/src/main/resources/llap-daemon-log4j2.properties
Change-Id: Ia552ea08ba61831f60e94f5a18913a9d87bb3385
> HIVE-24192: Properly log TaskExecutorService eviction details

- cli/src/java/org/apache/hadoop/hive/cli/CliDriver.java
- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosIncrementalLoadAcidTables.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestStatsReplicationScenarios.java
- itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
- ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
- ql/src/test/org/apache/hadoop/hive/ql/metadata/TestSessionHiveMetastoreClientListPartitionsTempTable.java
- service/src/java/org/apache/hive/service/server/HiveServer2.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientWithLocalCache.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/RetryingMetaStoreClient.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestListPartitions.java
> HIVE-24202: Clean up local HS2 HMS cache code (II)

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetastoreDirectSqlUtils.java
https://issues.apache.org/jira/browse/HIVE-24229
> HIVE-24229. DirectSql fails in case of OracleDB.

- ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Fix possible connection leaks in error conditions in class TxnHandler.
Tests:
TestTxnHandler Unit tests
> HIVE-24236: Fixed possible Connection leaks in TxnHandler (Yongzhi Chen, reviewed by Denys Kuzmenko)

- ql/src/java/org/apache/hadoop/hive/ql/ddl/function/reload/ReloadFunctionsOperation.java
Fix typo in ReloadFunctionsOperation
Hive.get() will register all functions as doRegisterAllFns is true,  so Hive.get().reloadFunctions() may load all functions from metastore twice, use Hive.get(false) instead may be better.
No
Existing tests
> HIVE-24107: Fix typo in ReloadFunctionsOperation

- ql/src/test/queries/clientpositive/subquery_join_rewrite.q
- ql/src/test/results/clientpositive/llap/subquery_join_rewrite.q.out
> HIVE-24248: TestMiniLlapLocalCliDriver[subquery_join_rewrite] is flaky

- ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/NullScanTaskDispatcher.java
- ql/src/test/queries/clientpositive/metadataonly_acid_empty_partition.q
- ql/src/test/results/clientpositive/llap/metadataonly_acid_empty_partition.q.out
Change-Id: Ia63c4a502f77f863f1ee20e0a407893689d79afb
> HIVE-23712: metadata-only queries return incorrect results with empty acid partition

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/SharedCache.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/TableCacheObjects.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStore.java
Adding check and default constraints in cache store of standalone metastore
Adding constraint in cachestore help in fetching complete table fast from metastore
No
Unit test cases added
> HIVE-23695: [CachedStore] Add check/default constraints in CachedStore

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/serde2/TestSysLogSerDe.java
- ql/src/java/org/apache/hadoop/hive/ql/log/syslog/SyslogParser.java
> HIVE-24284 : NPE when parsing druid logs using Hive (Mahesh Kumar Behera reviewed Nishant Bangarwa)

- service/src/java/org/apache/hive/service/CookieSigner.java
SHA string changed to 512
SHA-256 is not FIPS compliant.
No.
Local machine
> Hive-24287: Using SHA-512 for Cookie signature

- bin/hive
SAME AS PR#1344 initially submitted by Xiaomeng. I am just rebasing the patch as the old PR is auto-closed. Looking for a clean test run.
Add an env variable BEELINE_URL_LEGACY, when this value is not empty,
run "beeline -c $BEELINE_URL_LEGACY".
> HIVE-23962 Make bin/hive pick user defined jdbc url

- itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CacheUtils.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/SharedCache.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/InjectableBehaviourObjectStore.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStore.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestCheckConstraint.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestDefaultConstraint.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestForeignKey.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestGetAllTableConstraints.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestNotNullConstraint.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestPrimaryKey.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestUniqueConstraint.java
Data miss match between cachedstore and rawstore
No
test case  added
> HIVE-24258: [CachedStore] Data miss match between cachedstore and rawstore

- accumulo-handler/src/java/org/apache/hadoop/hive/accumulo/serde/AccumuloSerDe.java
- contrib/src/java/org/apache/hadoop/hive/contrib/serde2/RegexSerDe.java
- contrib/src/java/org/apache/hadoop/hive/contrib/serde2/TypedBytesSerDe.java
- druid-handler/src/java/org/apache/hadoop/hive/druid/serde/DruidSerDe.java
- hbase-handler/src/java/org/apache/hadoop/hive/hbase/HBaseSerDe.java
- hcatalog/core/src/main/java/org/apache/hive/hcatalog/data/HCatRecordSerDe.java
- hcatalog/core/src/main/java/org/apache/hive/hcatalog/data/JsonSerDe.java
- itests/custom-serde/src/main/java/org/apache/hadoop/hive/serde2/CustomSerDe1.java
- itests/custom-serde/src/main/java/org/apache/hadoop/hive/serde2/CustomSerDe2.java
- itests/test-serde/src/main/java/org/apache/hadoop/hive/serde2/TestSerDe.java
- jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/JdbcSerDe.java
- kudu-handler/src/java/org/apache/hadoop/hive/kudu/KuduSerDe.java
- ql/src/java/org/apache/hadoop/hive/ql/io/arrow/ArrowColumnarBatchSerDe.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcSerde.java
- ql/src/java/org/apache/hadoop/hive/ql/io/parquet/serde/ParquetHiveSerDe.java
- ql/src/java/org/apache/hadoop/hive/ql/io/protobuf/ProtobufSerDe.java
- ql/src/java/org/apache/hadoop/hive/ql/log/syslog/SyslogSerDe.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/TestFileSinkOperator.java
- serde/src/java/org/apache/hadoop/hive/serde2/AbstractSerDe.java
- serde/src/java/org/apache/hadoop/hive/serde2/JsonSerDe.java
- serde/src/java/org/apache/hadoop/hive/serde2/MetadataTypedColumnsetSerDe.java
- serde/src/java/org/apache/hadoop/hive/serde2/MultiDelimitSerDe.java
- serde/src/java/org/apache/hadoop/hive/serde2/NullStructSerDe.java
- serde/src/java/org/apache/hadoop/hive/serde2/OpenCSVSerde.java
- serde/src/java/org/apache/hadoop/hive/serde2/RegexSerDe.java
- serde/src/java/org/apache/hadoop/hive/serde2/TypedSerDe.java
- serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerDe.java
- serde/src/java/org/apache/hadoop/hive/serde2/binarysortable/BinarySortableSerDe.java
- serde/src/java/org/apache/hadoop/hive/serde2/teradata/TeradataBinarySerde.java
- serde/src/java/org/apache/hadoop/hive/serde2/thrift/ThriftJDBCBinarySerDe.java
> HIVE-24321: Implement Default getSerDeStats in AbstractSerDe

- ql/src/test/queries/clientpositive/cardinality_preserving_join_opt2.q
> Disable cardinality_preserving_join_opt2

- data/conf/hive-log4j2.properties
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/OperatorGraph.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HivePointLookupOptimizerRule.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/graph/DagGraph.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/graph/DiGraph.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/graph/DotExporter.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/graph/OperatorGraph.java
- ql/src/test/results/clientpositive/llap/acid_vectorization_original.q.out
- ql/src/test/results/clientpositive/llap/dynamic_partition_pruning.q.out
- ql/src/test/results/clientpositive/llap/vectorized_dynamic_partition_pruning.q.out
* the OperatorGraph from the downstream-merge patch is moved into thisone instead
* goal of this patch is only to fix the issue introduced by the new logic
> HIVE-24360: SharedWorkOptimizer may create incorrect plans with DPPUnion

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/PointLookupOptimizer.java
> HIVE-24362 : AST tree processing is suboptimal for tree with large number of nodes

- itests/src/test/resources/testconfiguration.properties
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/test/queries/clientpositive/explainanalyze_acid_with_direct_insert.q
- ql/src/test/results/clientpositive/llap/acid_vectorization_original.q.out
- ql/src/test/results/clientpositive/llap/explainanalyze_acid_with_direct_insert.q.out
> HIVE-24336: Turn off the direct insert for EXPLAIN ANALYZE queries

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionInfo.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
> Do not remove metadata for aborted writes that were batched with valid ones in the same delta file

- ql/src/java/org/apache/hadoop/hive/ql/ppd/ExprWalkerInfo.java
- ql/src/test/queries/clientpositive/ppd2.q
- ql/src/test/results/clientpositive/llap/ppd2.q.out
> HIVE-24373 : Wrong predicate is pushed down for view with constant value

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
> HIVE-24401: Fix HiveConf description

- pom.xml
- ql/src/test/org/apache/hadoop/hive/ql/io/parquet/TestHiveSchemaConverter.java
Upgrade Parquet version from 1.11.0 to 1.11.1
Parquet 1.11.1 has some important bug fixes so it would be beneficial to upgrade to it.
No.
N/A
> HIVE-24408: Upgrade Parquet to 1.11.1

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveRelDecorrelator.java
1. When methods which shares the same implementation one of the method's implementation is changed to call its pair. Ex.
```
public Frame decorrelateRel(HiveSortLimit rel) {
return decorrelateRel((Sort) rel);
}
public Frame decorrelateRel(Sort rel) {
...
```
2. Variations of `removeCorrelationExpr` has the same implementation only difference was the number of parameters of the methods. This patch removes the duplicates and variants which has fewer parameters calls the most specific and pass default values for missing parameters.
Decrease the amount of redundant code.
No
No functionality was altered. Execute some q tests which has subquery with `in`, `exists` like `subquery_exists.q`, `subquery_in.q`
> HIVE-24412: Extract common parts of HiveDeCorrelator

- hbase-handler/pom.xml
- pom.xml
This backports HIVE-19662 to branch-3.1
Hive currently use deprecated Avro APIs in Avro version 1.8.x and below, which are removed since 1.9. Therefore if downstream applications use Hive and want to upgrade its own Avro dependency to 1.9.x or up, there could be incompatibility issues. In order to change this, we'll need HIVE-24324 which removes the deprecated API usage with some others in 1.8.x. This is a pre-requisite for that.
No
N/A
> HIVE-24414: Backport HIVE-19662 to branch-3.1

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MajorQueryCompactor.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MinorQueryCompactor.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMajorQueryCompactor.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMinorQueryCompactor.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
See HIVE-24410
Manually on a secure cluster
> HIVE-24410: Query-based compaction hangs because of doAs

- ql/src/java/org/apache/hadoop/hive/ql/exec/AppMasterEventOperator.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
- ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java
- serde/src/java/org/apache/hadoop/hive/serde2/lazybinary/LazyBinarySerDe2.java
> HIVE-24409 : Use LazyBinarySerDe2 in PlanUtils::getReduceValueTableDesc

- hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
> HIVE-24423: Improve DbNotificationListener Thread

- ql/pom.xml
@pvary can you please review? Thanks!
> HIVE-24498: add thrift facebook classes to hive-exec jar

- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorDeserializeRow.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorSerializeRow.java
> HIVE-24503 : Optimize vector row serde by avoiding type check at run time.

- hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/tools/SQLGenerator.java
> HIVE-24460: Refactor Get Next Event ID for DbNotificationListener

- ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java
> HIVE-24530: Potential NPE in FileSinkOperator.closeRecordwriters method

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
See HIVE-24474
No
Manually, since the TxnAbortedException only appears in the logs.
> HIVE-24474: Failed compaction always logs TxnAbortedException (again)

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
> HIVE-24432: Delete Notification Events in Batches

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
> HIVE-24554: TestCompactor fails to compile since HIVE-24477

- metastore/src/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
- ql/src/test/org/apache/hadoop/hive/ql/io/TestAcidUtils.java
This pull request fixes some minor typos.
This pull request fixes some minor typos.
No
No need to be tested.
> HIVE-24559: Fix some spelling issues

- itests/hive-unit/src/test/java/org/apache/hive/jdbc/miniHS2/TestHiveServer2Acid.java
- ql/src/java/org/apache/hadoop/hive/ql/Driver.java
- ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
- ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DummyTxnManager.java
- ql/src/java/org/apache/hadoop/hive/ql/lockmgr/HiveTxnManager.java
Rebased second PR of HIVE-24550
> HIVE-24550: Cleanup only transaction information for the current DriverContext

- service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIService.java
- service/src/test/org/apache/hive/service/cli/TestRetryingThriftCLIServiceClient.java
Bug fix, local `hiveHost` variable was shadowing global one, so that all references to global didn't contain config changes.
hive.server2.thrift.bind.host is not honored. 
No
Local test
> HIVE-20726: hive.server2.thrift.bind.host is not honored

- jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java
> HIVE-24616: Add Logging to Track Query Status

- beeline/src/java/org/apache/hive/beeline/BeeLine.java
- beeline/src/java/org/apache/hive/beeline/Commands.java
> HIVE-24617: Review beeline Driver Scanning Code

- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractAlterTableOperation.java
AbstractAlterTableOperation has a private method (finalizeAlterTableWithWriteIdOp) which receives one of it's field, which doesn't make much sense.
To have a cleaner code.
No.
All the tests are still running.
> HIVE-24611 Remove unnecessary parameter from AbstractAlterTableOperation

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/ExplainTask.java
Adding to configs to enable printing explain not only in log, but also in console in the non-extended mode
We need user facing explain to be printed for users that submit queries exclusively through workflows meaning it's hard to refactor for running with explain
It adds 2 config values that can be used to print explain to console
Company internal test cluster, but since the code touched is currently not tested, no new tests were added
> HIVE-24394: enable printing explain to console at start of query

- jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
> HIVE-24627: Add Debug Logging to Hive JDBC Connection

- ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprFactory.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprNodeDescExprFactory.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/type/FunctionHelper.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/type/HiveFunctionHelper.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/type/RexNodeExprFactory.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/type/TypeCheckProcFactory.java
- ql/src/test/queries/clientpositive/compare_cols_null.q
- ql/src/test/results/clientpositive/llap/compare_cols_null.q.out
> HIVE-24632: Replace with null when GenericUDFBaseCompare has a non-interpretable val

- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Query results cache requires query text having fully qualified table names as cache key. By the time query compilation reach the point where results cache key is generated unparseTranslator instance has the fully qualified table names. Use this to generate cache key.
Generating the key from query text also requires the TokenRewriteStream instance related to the parsed query. Applying transformations stored in the unparseTranslator would alter the TokenRewriteStream and makes invalid for further usage. In order to avoid this a dedicated TokenRewriteStream program is introduced for Query results cache.
All query was parsed twice:
* first parse to have the AST tree for compilation
* second parse to generate cache key from query text having fully qualified table names.
No.
Run existing qtest …
> HIVE-24644: QueryResultCache parses the query twice

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExclusiveReplica.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestTableLevelReplicationScenarios.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpWork.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/AlterTableHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/DumpMetaData.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestReplDumpTask.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/repl/ReplScope.java
> HIVE-24558 : Handle update in table level regular expression

- ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/MapredContext.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFEvaluator.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFExceptionInVertex.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFExceptionInVertex.java
- ql/src/test/queries/clientpositive/exception_in_vertex_udf.q
- ql/src/test/results/clientpositive/llap/exception_in_vertex_udf.q.out
- ql/src/test/results/clientpositive/llap/show_functions.q.out
Implemented a udf and udaf, that can throw exception in parameterized vertex / task / task attempt.
The udf/udaf can help us making a query fail in different stages.
No.
Qtests, manual log checking.
> HIVE-24278: Implement an UDF for throwing exception in arbitrary vertex

- serde/pom.xml
- serde/src/java/org/apache/hadoop/hive/serde2/teradata/TeradataBinaryDataOutputStream.java
- serde/src/java/org/apache/hadoop/hive/serde2/teradata/TeradataBinarySerde.java
> HIVE-24659: Remove Commons Logger from serde Package

- jdbc-handler/pom.xml
- jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/JdbcRecordWriter.java
> HIVE-24660: Remove Commons Logger from jdbc-handler Package

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
> HIVE-24676 : Show locks call failing for postgres RDBMS if the txnId filter is passed

- ql/src/test/queries/clientpositive/unionDistinct_1.q
http://ci.hive.apache.org/job/hive-flaky-check/166/testReport/junit/org.apache.hadoop.hive.cli/TestMiniLlapCliDriver/testCliDriver_unionDistinct_1_/
> HIVE-24680: Disable flaky unionDistinct_1.q test

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
Moved DB fetch out of partition loop
No
Unit tests
> HIVE-24667: Truncate optimization to avoid unnecessary per partition DB get operations

- jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/JdbcRecordWriter.java
- ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
- ql/src/java/org/apache/hadoop/hive/ql/Context.java
- ql/src/java/org/apache/hadoop/hive/ql/Driver.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/PartitionUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/ExplainSQRewriteTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/ExplainTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/ReplCopyTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/ScriptOperator.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/Task.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ExecReducer.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/mr/MapRedTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/MapRecordSource.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/MergeFileRecordProcessor.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java
- ql/src/java/org/apache/hadoop/hive/ql/history/HiveHistoryImpl.java
- ql/src/java/org/apache/hadoop/hive/ql/io/rcfile/truncate/ColumnTruncateTask.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/SimpleFetchOptimizer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/stats/ColStatsProcessor.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFAverage.java
- serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/ObjectInspectorUtils.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/ReplChangeManager.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
> HIVE-24661: Do Not Stringify Exception in Logger messages

- common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestScheduledReplicationScenarios.java
- itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
https://issues.apache.org/jira/browse/HIVE-24674
> HIVE-24674. Set repl.source.for property in the db if db is under repication

- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
- standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/GetPartitionsByNamesRequest.java
- standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/GetPartitionsByNamesRequest.php
- standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
- standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
- standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
…equest
Add two optional entries for thrift structure GetPartitionsByNamesRequest:
getFileMetadata : get file metadata or not.
id for table ID
It will be used by the metadata cache feature.
> HIVE-24392: Add table id to GetPartitionsByNamesRequest

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
Cherry pick HIVE-17155 from master branch
make `findConfigFile` can handle jar protocol
When **spring-boot-maven-plugin** is used, we use  `java -jar` to launch program, and have to use  `org.springframework.boot.loader.LaunchedURLClassLoader` to load class, in such case, jar protocol is used.
No
current UT
> HIVE-17155: findConfFile() in HiveConf.java has some issues with the conf path

- itests/hive-jmh/src/main/java/org/apache/hive/benchmark/ql/exec/KryoBench.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/exec/spark/TestSmallTableCacheEviction.java
- kryo-registrator/pom.xml
- kryo-registrator/src/main/java/org/apache/hive/spark/HiveKryoRegistrator.java
- kryo-registrator/src/main/java/org/apache/hive/spark/NoHashCodeKryoSerializer.java
- pom.xml
- ql/pom.xml
- ql/src/java/org/apache/hadoop/hive/ql/exec/SerializationUtilities.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/persistence/KeyValueContainer.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/persistence/ObjectContainer.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/spark/HiveKVResultCache.java
- ql/src/java/org/apache/hadoop/hive/ql/io/sarg/ConvertAstToSearchArg.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/spark/TestHiveSparkClient.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/spark/TestSparkInvalidFileFormat.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/spark/TestSparkPlan.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/spark/session/TestSparkSessionManagerImpl.java
- ql/src/test/org/apache/hadoop/hive/ql/io/sarg/TestConvertAstToSearchArg.java
- spark-client/pom.xml
Upgrade from kryo4 to kryo5.
Performance improvement, possible code improvements later based on new FieldSerializer.
No.
All the qtests involve kryo usage as it's used for plan serialization/deserialization.
> HIVE-22944: Upgrade to Kryo5

- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/AtlasDumpTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/AtlasDumpWork.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/AtlasLoadTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/atlas/AtlasReplInfo.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/atlas/AtlasRequestBuilder.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestAtlasDumpTask.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestAtlasLoadTask.java
> HIVE-24654: Table level replication support for Atlas metadata

- hcatalog/webhcat/svr/src/main/java/org/apache/hive/hcatalog/templeton/AppConfig.java
- hcatalog/webhcat/svr/src/main/java/org/apache/hive/hcatalog/templeton/Main.java
Signed-off-by: Oleksiy Sayankin <oleksiy.sayankin@gmail.com>
> HIVE-18728 : Secure webHCat with SSL

- beeline/pom.xml
> HIVE-24657: Make Beeline Logging Dependencies Explicit

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
Skips extra DB call and logging in Cleaner if there are no candidates for cleaning.
Optimization
No
Existing unit tests.
> Skip extra work in Cleaner if queue is empty

- ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/DumpMetaData.java
- ql/src/test/org/apache/hadoop/hive/ql/parse/repl/load/TestDumpMetaData.java
> HIVE-24624: Repl Load should detect the compatible staging dir

- common/src/java/org/apache/hadoop/hive/common/type/Date.java
- common/src/java/org/apache/hadoop/hive/common/type/Timestamp.java
- common/src/java/org/apache/hadoop/hive/common/type/TimestampTZUtil.java
- ql/src/test/results/clientpositive/llap/udf_mask.q.out
- ql/src/test/results/clientpositive/llap/udf_mask_first_n.q.out
- ql/src/test/results/clientpositive/llap/udf_mask_last_n.q.out
- ql/src/test/results/clientpositive/llap/udf_mask_show_first_n.q.out
- ql/src/test/results/clientpositive/llap/udf_mask_show_last_n.q.out
> HIVE-24693: Convert timestamps to zoned times without string operations

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- llap-server/src/java/org/apache/hadoop/hive/llap/cache/BaseLlapDataBuffer.java
- llap-server/src/java/org/apache/hadoop/hive/llap/cache/FileCache.java
- llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCacheImpl.java
- llap-server/src/java/org/apache/hadoop/hive/llap/cache/MemoryLimitedPathCache.java
- llap-server/src/java/org/apache/hadoop/hive/llap/cache/PathCache.java
- llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
- llap-server/src/java/org/apache/hadoop/hive/llap/io/decode/OrcColumnVectorProducer.java
- llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/OrcEncodedDataReader.java
- llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestFileCache.java
- llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelCacheImpl.java
- llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestMemoryLimitedPathCache.java
This is a subtask for the cache hydration feature, collecting the required data for storing and restoring the cache content.
LLAP cache hydration will enable save/load the cache contents. To do this some additional metadata is required.
No.
> HIVE-24726: Track required data for cache hydration

- llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapRecordReader.java
Similar logic existed for non ACID reads already: to save GC cycles column vectors are reused instead of being recreated for every single batch.
> HIVE-23826: Reuse column vectors in LlapRecordReader for ACID data too

- common/src/java/org/apache/hadoop/hive/common/type/Date.java
- common/src/java/org/apache/hive/common/util/DateParser.java
- common/src/test/org/apache/hive/common/util/TestDateParser.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/CastStringToDate.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/TruncDateFromString.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/TruncDateFromTimestamp.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFDateAddColCol.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFDateAddColScalar.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFDateAddScalarCol.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDate.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDateAdd.java
> HIVE-24808: Cache Parsed Dates

- pom.xml
- standalone-metastore/pom.xml
- testutils/ptest2/pom.xml
Trying to backport 31935896a78f95ae0792ae7f29960d1b604fbe9d for [HIVE-24788](https://issues.apache.org/jira/browse/HIVE-24788)
> HIVE-24788: Backport HIVE-23338 to branch-3.1

- itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestKillQueryWithAuthorizationDisabled.java
- service/src/java/org/apache/hive/service/server/KillQueryImpl.java
In this PR, it is proposed to add a check for the authorization config value and provide admin access to hive server user in case authorization is disabled.
Following changes are required to enable Workload Manager thread to have kill query access in a non authorized environment.
No
Added Unit Tests to test the patch
> [WIP]HIVE-24751: Add authorization flag check for KillQueryImpl

- ql/src/java/org/apache/hadoop/hive/ql/udf/ptf/BasePartitionEvaluator.java
this patch makes the `Range` class static again - no other significant changes
> HIVE-24823: Fix ide error in BasePartitionEvaluator

- common/src/java/org/apache/hadoop/hive/common/type/TimestampUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/UDFDayOfWeek.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/UDFWeekOfYear.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDF.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDateDiff.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFTrunc.java
- serde/src/java/org/apache/hadoop/hive/serde2/RandomTypeUtil.java
- serde/src/java/org/apache/hadoop/hive/serde2/objectinspector/primitive/PrimitiveObjectInspectorUtils.java
> HIVE-24811: Extend Cached Dates to Other Areas

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/NonBlockingOpDeDupProc.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/correlation/CorrelationUtilities.java
> HIVE-24829: CorrelationUtilities#replaceReduceSinkWithSelectOperator misses KEY mappings

- itests/hive-unit/src/test/java/org/apache/hive/service/cli/thrift/TestThriftCliServiceWithInfoMessage.java
- service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIService.java
https://issues.apache.org/jira/browse/HIVE-24752
Local machine
> HIVE-24752: Returned operation's drilldown link may be broken

- service/src/java/org/apache/hive/service/cli/operation/Operation.java
> HIVE-24792: Potential thread leak in Operation

- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java
Move the output commit until after the proc.close operation
The commit operation might miss those records flushed out by the close() operation.
No
Tested on cluster manually with TPCDS inserts by using the `HiveIcebergOutputCommitter`.
> HIVE-24857: Trigger Tez output commit after close operation

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/ParallelEdgeFixer.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
> HIVE-24841: Parallel edge fixer may run into NPE when RS is missing a duplicate column from the output schema

- standalone-metastore/metastore-common/src/test/resources/log4j2.properties
- standalone-metastore/metastore-server/src/test/resources/log4j2.properties
> HIVE-24832: Remove Spring Artifacts from Log4j Properties Files

- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
> HIVE-24758: Log Tez Task DAG ID, DAG Session ID, HS2 Hostname

- service/src/java/org/apache/hive/service/cli/thrift/ThriftBinaryCLIService.java
- service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIService.java
> HIVE-24739: Clarify Usage of Thrift TServerEventHandler and Count Number of Messages Processed

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
Introduced performance metrics for Initiator and Cleaner
No
Unit tests
> HIVE-24871: Initiator / Cleaner performance metrics

- ql/src/java/org/apache/hadoop/hive/ql/io/avro/AvroGenericRecordReader.java
Fix reader leak in AvroGenericRecordReader
Without the fix resources may be slowly leaked if we hit exception path in AvroGenericRecordReader. 
I specifically observed it in use of `AGRR` in https://github.com/trinodb/trino. Hitting problematic path resulted in leaking S3 connections.
Yes. Leaking resources may eventully result to application malfunction. That was observed in https://github.com/trinodb/trino which uses problematic class.
Manually tested sibling change in forked class in https://github.com/trinodb/trino. It was done using a stress test which reproduced problem without change applied.
With a change we no longer observed leaked connections.
> HIVE-24851: Fix reader leak in AvroGenericRecordReader

- standalone-metastore/pom.xml
Upgrade the cron-utils library to 9.1.3 due to a security vulnerability.
Hive is pulling in cron-utils 8.1.1 which is vulnerable to CVE-2020-26238. It is assigned a CVSSv3 score of Critical.
No.
Manually.
> HIVE-24890: Upgrade the cron-utils library from 8.1.1 to 9.1.3 due to CVE-2020-26238

- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/MetricsInfo.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
Introduced ACID metadata related metrics
No
Unit tests
> HIVE-24879: Create new metrics about ACID metadata size

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
Introduced performance metric for Compaction Worker
No
Unit tests
> HIVE-24874: Worker performance metric

- llap-client/src/java/org/apache/hadoop/hive/llap/io/api/LlapIo.java
- llap-common/src/gen/protobuf/gen-java/org/apache/hadoop/hive/llap/daemon/rpc/LlapDaemonProtocolProtos.java
- llap-common/src/java/org/apache/hadoop/hive/llap/impl/LlapManagementProtocolClientImpl.java
- llap-common/src/protobuf/LlapDaemonProtocol.proto
- llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapProtocolServerImpl.java
- llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapCacheMetadataSerializer.java
- llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
- llap-server/src/test/org/apache/hadoop/hive/llap/io/LlapIoMocks.java
- llap-server/src/test/org/apache/hadoop/hive/llap/io/api/impl/TestLlapCacheMetadataSerializer.java
- llap-server/src/test/org/apache/hadoop/hive/llap/io/encoded/TestLlapOrcCacheLoader.java
- storage-api/src/java/org/apache/hadoop/hive/common/io/CacheTag.java
This is a subtask for the cache hydration feature, it provides a fetch metadata and load data based on metadata functionality to the llap cache.
LLAP cache hydration will enable save/load the cache contents.
No.
> HIVE-24727: Cache hydration api in llap proto

- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/MetricsInfo.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Introduced new metrics about open transactions
No
Unit test
> HIVE-24921: Create new metrics about open transactions

- ql/src/java/org/apache/hadoop/hive/ql/io/avro/AvroGenericRecordReader.java
This is a cherry-pick of https://github.com/apache/hive/pull/2040 (https://issues.apache.org/jira/browse/HIVE-24851) to branch-3
> Backport HIVE-24851: Fix reader leak in AvroGenericRecordReader to branch-3

- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFSQCountCheck.java
https://issues.apache.org/jira/browse/HIVE-24934?filter=-2
> remove vectorized expressions annotation

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
Introduced new metrics about Initiator / Worker hosts and versions
No
Unit test
> HIVE-24932: Create new metric about Initiator / Worker hosts

- ql/src/java/org/apache/hadoop/hive/ql/log/syslog/SyslogParser.java
...Fix sync bottleneck in SyslogParser
> HIVE-24937 : Fix sync bottleneck in SyslogParser

- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/MetricsInfo.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
> HIVE-24955: New metrics about aborted transactions

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/DDLTask.java
- ql/src/test/queries/clientpositive/describe_table.q
- ql/src/test/results/clientpositive/describe_table.q.out
> Backport HIVE-24965: Describe table partition stats fetch should be configurable

- itests/hive-jmh/src/main/java/org/apache/hadoop/hive/ql/udf/ptf/ValueBoundaryScannerBench.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/ptf/ValueBoundaryScanner.java
- ql/src/test/org/apache/hadoop/hive/ql/udf/ptf/TestValueBoundaryScanner.java
…
Change-Id: Id7c741b240e4ce862e29d0d21ecd257b909c6e02
> HIVE-24746: PTF: TimestampValueBoundaryScanner can be optimised during range computation

- ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
- ql/src/test/queries/clientpositive/row__id_2.q
- ql/src/test/results/clientpositive/llap/row__id_2.q.out
When adding identifiers to UnparseTranslator convert them to lower case.
Identifiers are converted to lower case in most places in the code.
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=row__id_2.q -pl itests/qtest -Pitests
```
> HIVE-24993: AssertionError when referencing ROW__ID.writeId

- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/MetricsInfo.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Introduced new metrics about locks
No
Unit test
> HIVE-24985: Create new metrics about locks

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMRTableScan1.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/ProcessAnalyzeTable.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/spark/SparkProcessAnalyzeTable.java
- ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsNoJobTask.java
- ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsTask.java
> HIVE-24928: In case of non-native tables use basic statistics from HiveStorageHandler

- ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Set Dbname and Tablename in getLatestCommittedCompactionInfo.
Dbname and Tablename is required in CompactionInfoStruct.
No
TestCompactionTxnHandler
> HIVE-25017: Fix response in GetLatestCommittedCompaction

- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
Rename metrics that have spaces in the name as it can cause issues when consuming
No
Unit test
> HIVE-25019: Rename metrics that have spaces in the name

- ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/test/queries/clientnegative/groupby_cube2.q
- ql/src/test/queries/clientnegative/groupby_rollup1.q
- ql/src/test/queries/clientnegative/groupby_rollup2.q
- ql/src/test/queries/clientpositive/groupby_rollup2.q
- ql/src/test/queries/clientpositive/vector_groupby_rollup2.q
- ql/src/test/results/clientnegative/groupby_cube2.q.out
- ql/src/test/results/clientnegative/groupby_rollup1.q.out
- ql/src/test/results/clientnegative/groupby_rollup2.q.out
- ql/src/test/results/clientpositive/llap/groupby_rollup2.q.out
- ql/src/test/results/clientpositive/llap/vector_groupby_rollup2.q.out
> HIVE-24986: Support aggregates on columns present in rollups

- parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
- ql/src/test/queries/clientpositive/precedence_is.q
- ql/src/test/results/clientnegative/subquery_subquery_chain.q.out
- ql/src/test/results/clientpositive/llap/precedence_is.q.out
- ql/src/test/results/clientpositive/llap/sharedwork.q.out
Grammar (`IdentifiersParser.g`) has been updated to fix the precedence order.
In Hive, `IS` operator has higher precedence than comparison operator, which is different from most other databases.
Yes, the query results may change for users, because of the change in precedence of `IS` and comparison operator. With this change, comparison operators will have higher precedence.
Added `precedence_is.q`
> HIVE-25028: Hive: Select query with IS operator producing unexpected result

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/Metrics.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/ThrowingTxnHandler.java
Introduce new ratio gauges for initiator/cleaner failures.
No
> HIVE-25018: Create new metrics about Initiator / Cleaner failures

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/MessageBuilder.java
MessageBuilder.getInstance should set the singleton MessageBuilder instance variable once it is fully initialized.
The changes are needed to ensure that all parallel threads access a fully initialized MessageBuilder instance.
No
> HIVE-25051: Callers can access uninitialized MessageBuilder instance causing NPE

- itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestJdbcWithMiniKdc.java
- service/src/java/org/apache/hive/service/cli/HiveSQLException.java
- service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIService.java
- service/src/test/org/apache/hive/service/cli/TestHiveSQLException.java
> HIVE-24772: Revamp Server Request Error Logging

- ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRexExecutorImpl.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTConverter.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ExprNodeConverter.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/SqlFunctionConverter.java
- ql/src/test/queries/clientnegative/cbo_fallback_never_semantic_exception.q
- ql/src/test/queries/clientpositive/explainuser_1.q
- ql/src/test/queries/clientpositive/is_distinct_from.q
- ql/src/test/queries/clientpositive/join_is_not_distinct_from.q
- ql/src/test/queries/clientpositive/join_nullsafe.q
- ql/src/test/queries/clientpositive/semijoin6.q
- ql/src/test/queries/clientpositive/tez_union_group_by.q
- ql/src/test/results/clientnegative/cbo_fallback_never_semantic_exception.q.out
- ql/src/test/results/clientpositive/llap/cbo_fallback_always_semantic_exception.q.out
- ql/src/test/results/clientpositive/llap/cbo_fallback_conservative_semantic_exception.q.out
- ql/src/test/results/clientpositive/llap/cbo_fallback_test_semantic_exception.q.out
- ql/src/test/results/clientpositive/llap/compare_cols_null.q.out
- ql/src/test/results/clientpositive/llap/explainuser_1.q.out
- ql/src/test/results/clientpositive/llap/is_distinct_from.q.out
- ql/src/test/results/clientpositive/llap/join_by_range_rule_not_null.q.out
- ql/src/test/results/clientpositive/llap/join_is_not_distinct_from.q.out
- ql/src/test/results/clientpositive/llap/join_nullsafe.q.out
- ql/src/test/results/clientpositive/llap/orc_predicate_pushdown.q.out
- ql/src/test/results/clientpositive/llap/parquet_predicate_pushdown.q.out
- ql/src/test/results/clientpositive/llap/semijoin6.q.out
- ql/src/test/results/clientpositive/llap/show_functions.q.out
- ql/src/test/results/clientpositive/llap/tez_union_group_by.q.out
- ql/src/test/results/clientpositive/llap/udf_equal.q.out
- ql/src/test/results/clientpositive/llap/vector_nullsafe_join.q.out
`SqlFunctionConverter.java` has been changed to make IS_DISTINCT_FROM operator go through the CBO.
Currently, insert statements are failing when IS DISTINCT FROM or IS NOT DISTINCT FROM operators are used, which can be fixed by simply optimizing through the CBO.
NO
Added tests to `is_distinct_from.q`, and validated the output.
> HIVE-24998: IS [NOT] DISTINCT FROM failing with SemanticException

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractAlterTableOperation.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
When running ALTER TABLE ... SET/UNSET TBLPROPERTIES on an Iceberg table the properties should be updated on the Iceberg side as well. 
The collection of changed property keys are collected on `AbstractAlterTableOperation` and stored in `EnvironemntContext`. `HiveIcebergMetaHook#commitAlterTable` takes care of the processing of `EnvironmentContext` and updating of the iceberg table. 
No
Manual test and unit test
> HIVE-25065: Implement ALTER TABLE for setting iceberg table properties

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
> HIVE-24900 Failed compaction does not cleanup the directories

- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/MetricsInfo.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Divide the open transaction related metrics (number of open transactions, oldest open transaction id, age of the oldest open transaction) based on if it's a replication related transaction or not.
This will give us an ability to give recommendations to the different cases.
No
> HIVE-25021: Divide oldest_open_txn into oldest replication and non-replication transactions

- iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalog.java
> HIVE-25100: Use default values of Iceberg client pool configuration

- ql/pom.xml
removing slf4j from hive-exec jar
maven shade plugin config changes
no
manually checked whether all slf4j stuff was gone from the jar, also testing it together with other software components which are pulling in that artifact
> HIVE-25116: Exclude slf4j from hive-exec uber Jar included by avatica

- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/like/CreateTableLikeOperation.java
- ql/src/test/results/clientpositive/llap/create_like2.q.out
- ql/src/test/results/clientpositive/llap/external_table_purge.q.out
- ql/src/test/results/clientpositive/llap/partition_discovery.q.out
- ql/src/test/results/clientpositive/llap/partition_params_postgres.q.out
- ql/src/test/results/clientpositive/llap/rename_external_partition_location.q.out
- ql/src/test/results/clientpositive/llap/repl_2_exim_basic.q.out
- ql/src/test/results/clientpositive/llap/show_create_table_partitioned.q.out
Removed the discover.partitions config for external tables with partittions.
HMS CPU usage is maximum because of this config.
Yes. if the users want to enable this config, then they need to alter the table property using the command: ALTER TABLE exttbl SET TBLPROPERTIES ('discover.partitions' = 'true');
Local Machine, Remote cluster
> HIVE-25039: Disabling discovery.partitions config for external tables

- itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniDruidCliDriver.java
- itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniDruidKafkaCliDriver.java
- pom.xml
- ql/src/test/queries/clientpositive/druid_timestamptz2.q
- ql/src/test/queries/clientpositive/druidkafkamini_avro.q
- ql/src/test/queries/clientpositive/druidkafkamini_csv.q
- ql/src/test/queries/clientpositive/druidmini_extractTime.q
- ql/src/test/queries/clientpositive/druidmini_floorTime.q
- ql/src/test/queries/clientpositive/druidmini_mv.q
- ql/src/test/queries/clientpositive/druidmini_semijoin_reduction_all_types.q
- ql/src/test/queries/clientpositive/druidmini_test1.q
- ql/src/test/queries/clientpositive/druidmini_test_alter.q
- ql/src/test/queries/clientpositive/druidmini_test_insert.q
- ql/src/test/queries/clientpositive/druidmini_test_ts.q
- standalone-metastore/pom.xml
- testutils/ptest2/conf/deployed/master-mr2.properties
- testutils/ptest2/pom.xml
Jackson version changed to 2.11.0 in the pom files.
To avoid CVE-2020-25649
No.
Local machine.
> HIVE-24816: Jackson version changed to 2.11.0 in the pom files

- bin/replstats.sh
- packaging/src/main/assembly/bin.xml
> HIVE-25092. Add a shell script to fetch the statistics of replication data copy tasks.

- ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
Lowering the log level of classpath logging.
Prevent useless classpath logs on INFO level.
No.
I haven't tested, it should be straighforward.
> HIVE-25107: Classpath logging should be on DEBUG level

- iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out
- iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out
- ql/src/test/results/clientpositive/llap/create_table_explain_ddl.q.out
Fix qfile output
Currently, there are three pre-commit tests is failed after disabling discovery.partitions.
No.
No new tests.
> HIVE-25121: Fix qfile results due to disabling discovery.partitions

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetricsOnTez.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/HiveSplitGenerator.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
- ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/metrics/DeltaFilesMetricReporter.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- service/src/java/org/apache/hive/service/server/HiveServer2.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
Introduced new metrics about the number of delta files in the ACID table
No
Unit + itests
> HIVE-24974: Create new metrics about the number of delta files in the ACID table

- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/MetricsInfo.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Introduce a new metric for tables with greater number of aborted transactions than x, where x comes from metastore conf.
No
Unit test
> HIVE-25037: Create metric: Number of tables with > x aborts

- itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java
> HIVE-25127: Remove Thrift Exceptions From RawStore getCatalogs

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
> HIVE-25139: Filter out null table properties in HiveIcebergMetaHook

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreChecker.java
> HIVE-25151: Remove Unused Interner from HiveMetastoreChecker

- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/TruncDateFromTimestamp.java
> HIVE-24810: Use JDK 8 String Switch in TruncDateFromTimestamp

- llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
- llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/metrics/StatsPerDag.java
- llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/scheduler/StatsPerDag.java
- llap-tez/src/test/org/apache/hadoop/hive/llap/tezplugins/TestLlapTaskSchedulerService.java
Change-Id: I91c004a06b35d60d11551c5fa04db7e6ba6f4550
Optimise locking in LlapTaskSchedulerService
Perf optimization
No
TestLlapTaskSchedulerService
> HIVE-24537: Optimise locking in LlapTaskSchedulerService

- pom.xml
- standalone-metastore/pom.xml
Change-Id: I5ba6d5b695a2804e55f2791c718bdbb562d00652
> HIVE-25155: Bump ORC to 1.6.8

- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/TezJobMonitor.java
> HIVE-25176: Print DAG ID to Console

- iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java
- iceberg/iceberg-handler/pom.xml
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
- iceberg/pom.xml
- pom.xml
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractAlterTableOperation.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
In case of an issue during the table migration this logic is followed:
- drop altered table if it exists but keep the data
- recreate the original table 
- call `msck repair` on new table
Work performed:
- Enhance `HiveMetaHook` with rollback method for alter operation and provide implementation in `HiveIcebergMetaHook`
- add drop/create/msck repair logic to `AbstractAlterTableOperation`
- the need for rollback is signalled through the `EnvironmentContext` properties. The `HiveMetaHook#INITIALIZE_ROLLBACK_ALTER` is set in `HiveIcebergMetaHook#rollbackAlterTable` and evaluated in `AbstractAlterTableOperation`
- Introduced a new `preDropTable` method to `HiveMetaHook` which accepts the `deleteData` parameter in order to retain data files while deleting iceberg tables.
- covered rollback …
> HIVE-25057: Implement rollback for hive to iceberg migration

- hbase-handler/src/java/org/apache/hadoop/hive/hbase/HiveHBaseTableInputFormat.java
> HIVE-25177: Add Additional Debugging Help for HBase Reader

- standalone-metastore/metastore-server/src/main/resources/package.jdo
In a previous checkin, some constraints were added to the package.jdo
file, but there are more constraints that need to be added to fix
the problem.
Added new constraints to package.jdo file
Without these changes, in an unreproduceable scenario, constraint violations are being seen.
No
Tested on customer dev site, no regressions were found.
> HIVE-23756: Added more constraints to the package.jdo file

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/NoOpReplStatsTracker.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWork.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplStateLogWork.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplStatsTracker.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/incremental/IncrementalLoadTasksBuilder.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/ReplLogger.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/IncrementalLoadLogger.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/IncrementalLoadEvent.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/ReplicationMetricCollector.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/event/Stage.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/event/StageMapper.java
- ql/src/test/org/apache/hadoop/hive/ql/parse/repl/metric/TestReplicationMetricCollector.java
- ql/src/test/org/apache/hadoop/hive/ql/parse/repl/metric/TestReplicationMetricSink.java
Same output from replication_metrics:
> HIVE-25165. Generate & track statistics per event type for incremental load in replication metrics.

- pom.xml
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorAssignRow.java
isNull field should be set on vectors nested in StructColumnVector instances, so they are handled by Hive instead  of netty.
netty 4.1.60.Final introduced a [null check](https://github.com/netty/netty/commit/c717d4b97aa164a500098c6fb7b834535d13bf53#diff-49ee8d7612d5ecfcc27b46c38a801ad32ebdb169f7d79f1577313a1de70b0fbbR537), breaking arrow serialization.
No
No new tests were added, the netty update broke some existing ones.
> HIVE-25180: Update netty to 4.1.60.Final

- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizationContext.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFOperator.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
- ql/src/java/org/apache/hadoop/hive/ql/plan/VectorPTFDesc.java
- ql/src/test/queries/clientpositive/vector_ptf_classcast_exception.q
- ql/src/test/results/clientpositive/llap/vector_ptf_classcast_exception.q.out
> HIVE-25117: Vector PTF ClassCastException with Decimal64

- ql/src/java/org/apache/hadoop/hive/ql/exec/CommonMergeJoinOperator.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/MapRecordSource.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/RecordSource.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/ReduceRecordSource.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/ConvertJoinMapJoin.java
- ql/src/test/queries/clientpositive/auto_sortmerge_join_10.q
- ql/src/test/results/clientpositive/llap/auto_sortmerge_join_10.q.out
- ql/src/test/results/clientpositive/llap/groupby_sort_1_23.q.out
- ql/src/test/results/clientpositive/llap/groupby_sort_skew_1_23.q.out
- ql/src/test/results/clientpositive/llap/subquery_in_having.q.out
> HIVE-24073 : Execution exception in sort-merge semijoin

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Fix NPE when the managed path is NULL. Add Null check.
Without the fix, create DB may fail with NPE
No
Manual tests
> HIVE-25211: Create database throws NPE

- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionPool.java
> HIVE-25185: Improve Logging On Polling Tez Session from Pool

- common/src/java/org/apache/hadoop/hive/common/type/Date.java
- common/src/java/org/apache/hadoop/hive/common/type/Timestamp.java
- itests/hive-unit/src/test/java/org/apache/hive/service/auth/saml/TestHttpSamlAuthentication.java
- jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDateFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/util/DateTimeMath.java
- ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFDateFormat.java
- ql/src/test/queries/clientpositive/udf_date_format.q
- ql/src/test/results/clientpositive/llap/udf_date_format.q.out
> HIVE-25093: date_format() UDF is returning values in UTC time zone only

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/BucketVersionPopulator.java
- ql/src/test/org/apache/hadoop/hive/ql/optimizer/TestBucketVersionPopulator.java
- ql/src/test/queries/clientpositive/multi_insert_bucketing_version.q
- ql/src/test/results/clientpositive/llap/multi_insert_bucketing_version.q.out
> HIVE-25224: Multi insert statements involving tables with different bucketing_versions results in error

- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/metrics/DeltaFilesMetricReporter.java
- service/src/java/org/apache/hive/service/server/HiveServer2.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSMetricsListener.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Metrics should be behind a feature flag unless they collected in AcidMetricsService which is already behind a feature flag.
No
Manual tests were conducted.
> HIVE-25081: Put metrics collection behind a feature flag

- bin/replstats.sh
**Sample Command:**
bash replstats.sh toHive distcp_stats /var/lib/hadoop-mapreduce/distcpvalues-1.csv /tmp/distcp_stats cust1-run1  "-n hive -p hive"
**Inputs**
toHive -> option to add csv data to hive table
distcp_stats -> Name of hive table
/var/lib/hadoop-mapreduce/distcpvalues-1.csv -> Location of the CSV file.
/tmp/distcp_stats cust1-run1 -> HDFS location where the CSV needs to be kept. 
cust1-run1 -> Unique Identifier for a specific run, (say in case all metrics are to be stored in one table, it uniquely identifies one run say, run from customer 1 & its first run)
"-n hive -p hive" -> Additional Hive Params.
**Example CSV file Generated**
```
[root@ayushtarget-1 ~]# cat /var/lib/hadoop-mapreduce/distcpvalues.csv
Job Id,Submit Time,Launch Time,Launch Duration,Finished Time,Finish …
```
> HIVE-25231. Add an ability to migrate CSV generated to hive table in replstats.

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionQueryBuilder.java
> HIVE-25258: Incorrect row order after query-based MINOR compaction

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWork.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWorkMBean.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplStatsTracker.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/ReplicationMetricCollector.java
JMX output in UI- First:
JMX output in UI- Second:
JMX output in UI- Third:
Sample Output from JConsole:
JConsole-MBeans Values:
> HIVE-25207. Expose incremental load statistics via JMX.

- common/src/java/org/apache/hadoop/hive/common/metrics/MetricsMBeanImpl.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetricsOnTez.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/metrics/DeltaFilesMetricReporter.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
> HIVE-25259: Tweak delta metrics with custom MBean for Prometheus

- itests/hive-unit/src/test/java/org/apache/hive/beeline/TestBeeLineWithArgs.java
> HIVE-24901: Re-enable tests in TestBeeLineWithArgs

- ql/src/test/results/clientpositive/llap/masking_mv_by_text_2.q.out
update masking_mv_by_text_2.q.out file
Stable build
No
Qtests
> HIVE-25291: Update masking_mv_by_text_2.q.out

- itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniHS2.java
Re-enabling  back TestJdbcWithMiniHS2 test. As it was disable as part of flaky test being marked as ignored.
enabling TestJdbcWithMiniHS2 UT back
No
Yes
> HIVE-23925: Flaky test TestJdbcWithMiniHS2

- pom.xml
Upgrade tez dependency to 0.10.1.
This way, hive will have the latest tez changes.
No.
Full precommit testing.
> HIVE-25254: Upgrade to tez 0.10.1

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
> HIVE-25272: READ transactions are getting logged in NOTIFICATION LOG

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAutoPurgeTables.java
Enable flaky Enable TestAutoPurgeTables test
To increase the code coverage by enabling UTs 
No
Yes, by running the flaky test pipeline - http://ci.hive.apache.org/job/hive-flaky-check/286/
> HIVE-19616: Enable TestAutoPurgeTables test

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLTask.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLWork.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/table/LoadTable.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/ImportSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/plan/ImportTableDesc.java
> HIVE-25164: Bootstrap REPL load DDL task in parallel

- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDateDiff.java
Refactor GenericUDFDateDiff to make code much more clean and readable.
Rewrite GenericUDFDateDiff.class 
No
Yes
> HIVE-25297: Refactor GenericUDFDateDiff

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveProjectJoinTransposeRule.java
- ql/src/test/queries/clientpositive/cbo_proj_join_transpose.q
- ql/src/test/results/clientpositive/llap/cbo_proj_join_transpose.q.out
> HIVE-25278: HiveProjectJoinTransposeRule may do invalid transformations with windowing expressions 

- pom.xml
> HIVE-25312: Upgrade netty to 4.1.65.Final

- pom.xml
> HIVE-25313: Upgrade commons-codec to 1.15

- hbase-handler/src/test/results/negative/hbase_ddl.q.out
- iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AlterTableType.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/column/replace/AlterTableReplaceColumnsOperation.java
- ql/src/test/results/clientnegative/alter_non_native.q.out
Implement `ALTER TABLE ... REPLACE COLUMNS (...)`
- This can be used to drop columns, add columns, change data type of a column, change the comment of a column
> HIVE-25255: Add support for replace columns

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
> HIVE-25267: Fix TestReplicationScenariosAcidTables

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
- iceberg/iceberg-handler/src/test/queries/positive/show_create_iceberg_table.q
- iceberg/iceberg-handler/src/test/results/positive/show_create_iceberg_table.q.out
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/set/AlterTableSetPartitionSpecAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/DDLPlanUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransform.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransformSpec.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Include partition specification of the Iceberg table in the output of the `SHOW CREATE TABLE` command.
> HIVE-25314: Implement SHOW CREATE TABLE command for Iceberg tables

- ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/ExplainSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/security/authorization/command/CommandAuthorizerV1.java
- ql/src/test/queries/clientpositive/explain_defaultauthorizer.q
- ql/src/test/results/clientpositive/llap/explain_defaultauthorizer.q.out
> HIVE-21489: EXPLAIN command throws ClassCastException in Hive

- ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
Fix testReplOpenTxn in testTxnHandler.
http://ci.hive.apache.org/job/hive-flaky-check/271/
> HIVE-25290: Stabilize TestTxnHandler

- .github/assign-by-files.yml
> HIVE-25371: Add myself to thrift file reviewers

- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSMetricsListener.java
> HIVE-25348: Skip metrics collection about writes to tables with tblproperty no_auto_compaction=true if CTAS

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/metrics/DeltaFilesMetricReporter.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSMetricsListener.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/MetricsInfo.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
> HIVE-25345: Add logging based on new compaction metrics

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/Task.java
Fix for IntelliJ compilation.
Fix for NullPointerException
Fix for IntelliJ compilation.
The TestReplicationScenariosAcidTables#testMultiDBTxn is flaky, but we do not see the problem
No
IntelliJ build and unit tests
> HIVE-25368: Code does not build in IDE and a small fix

- ql/src/java/org/apache/hadoop/hive/ql/udf/UDFDayOfMonth.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/UDFMonth.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/UDFYear.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDF.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFAddMonths.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFLastDay.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFMonthsBetween.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFNextDay.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFQuarter.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFToDate.java
- ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFLastDay.java
Refactoring GenericUDFToDate to reduce code redundancy 
Complete code refactor.
No
Yes
> HIVE-25332: Refactor UDF CAST(<Date string> as DATE)

- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
Flaky test
No
http://ci.hive.apache.org/job/hive-flaky-check/309
> HIVE-25249: Fix TestWorker

- ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
> HIVE-25192: Nullify summary for non-native tables

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOnHDFSEncryptedZones.java
> HIVE-25374: Fix test TestReplicationOnHDFSEncryptedZones

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
> HIVE-25115: Compaction queue entries may accumulate in "ready for cleaning" state

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/TaskRunner.java
Fix TestReplicationScenariosAcidTables#testMultiDBTxn
Flaky test check is green.
http://ci.hive.apache.org/job/hive-flaky-check/379/
> HIVE-25367: Fix TestReplicationScenariosAcidTables#testMultiDBTxn

- ql/src/java/org/apache/hadoop/hive/ql/udf/ptf/ValueBoundaryScanner.java
- ql/src/test/org/apache/hadoop/hive/ql/udf/ptf/TestBoundaryCache.java
Optimize range calculation for large windows.
Came from customer case, goal is performance improvement.
No.
Unit tests passed, validated on cluster.
> HIVE-25061: PTF: Improve ValueBoundaryScanner

- iceberg/iceberg-handler/src/test/queries/positive/dynamic_partition_pruning.q
- iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_pruning.q.out
Enable vectorization for TestIcebergCliDriver dynamic_partition_pruning.q
> HIVE-25394

- ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprNodeDescExprFactory.java
- ql/src/test/queries/clientpositive/constant_prop_coalesce.q
- ql/src/test/results/clientpositive/llap/constant_prop_coalesce.q.out
Adding more strict check during fold CASE into COALESCE after CBO: must be (true, false) , or (false, true)
fix a corner case : case expression then true else true --> coalesce(expression,false)
No
Adding a test case constant_prop_caolesce.q
> HIVE-24902: Incorrect result after fold CASE into COALESCE

- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/test/queries/clientpositive/constant_key_column.q
- ql/src/test/results/clientpositive/llap/constant_key_column.q.out
Fix wrong colExprMap generated by SemanticAnalyzer for ReduceSinkOperator
Wrong query results without this patch
No
Added itest constant_key_column.q
> HIVE-25170: Fix wrong colExprMap generated by SemanticAnalyzer

- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableOperation.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- streaming/src/java/org/apache/hive/streaming/HiveStreamingConnection.java
> HIVE-25414 : Optimise Hive::addWriteNotificationLog: Reduce FS call per notification.

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdateStat.java
> HIVE-25438 : Update partition column stats fails with invalid syntax error for MySql

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
> HIVE-25413 : Optimise ObjectStore::alterPartitions to reduce DB calls for getPartitions

- ql/src/test/queries/clientpositive/replication_metrics_ingest.q
- ql/src/test/results/clientpositive/llap/replication_metrics_ingest.q.out
http://ci.hive.apache.org/job/hive-flaky-check/363/
> HIVE-25387: Fix TestMiniLlapLocalCliDriver#replication_metrics_ingest.q

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
> HIVE-25441: Incorrect deltas split for sub-compactions when using

- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSchemaEvolution.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
- ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTBuilder.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/QB.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/plan/TableScanDesc.java
Fix the CBO path
Time Travel is not working when CBO is enabled
No
Unit tests switched to CBO enabled
> HIVE-25480: Fix Time Travel with CBO

- ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java
- ql/src/test/queries/clientpositive/merge_partitioned_insert.q
- ql/src/test/results/clientpositive/llap/merge_partitioned_insert.q.out
> HIVE-25404 insert merge partitioned

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetricsOnTez.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/HiveSplitGenerator.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/metrics/DeltaFilesMetricReporter.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestDeltaFilesMetrics.java
https://github.com/apache/hive/pull/2607
+fixes
Unit tests
> Hive 25450: Delta metrics keys should contain database name - 2

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionInfo.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
to resolve the data loss issue caused by Cleaner
> HIVE-25502: Cleaner causes data loss when processing aborted txn with DP

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/metrics/DeltaFilesMetricReporter.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestDeltaFilesMetrics.java
> HIVE-25513: Delta metrics collection may cause NPE

- itests/src/test/resources/testconfiguration.properties
- ql/src/test/results/clientpositive/create_table.q.out
- ql/src/test/results/clientpositive/llap/create_table.q.out
Introduce new test in the TestCliDriver.
Second commit: Adding create_table.q to .../queries/clientpositive implicitly included the test case for TestMiniLlapDriver too. The test case was added in pull request #2477 but did not run until now. Changes made to fix this test case.
Improve test coverage.
No
QTest
> HIVE-25526: Run create_table Q test from TestCliDriver

- pom.xml
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/ITestDbTxnManager.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mariadb.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mssql.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mysql.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Postgres.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestTxnDbUtil.java
- standalone-metastore/pom.xml
(cherry picked from commit 101e067e7a18c1051782b756d909aaba891f35c4)
> HIVE-25516: ITestDbTxnManager is broken after HIVE-24120

- llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
> HIVE-25527 : LLAP Scheduler task exits with fatal error if the executor node is down.

- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/AcidHouseKeeperService.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
> HIVE-25503: Add cleanup for the duplicate COMPLETED_TXN_COMPONENTS entries

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestScheduledReplicationScenarios.java
Flaky test check green.
http://ci.hive.apache.org/job/hive-flaky-check/386/
> HIVE-24766: Fix TestScheduledReplication

- Jenkinsfile
> HIVE-25378: Enable removal of old builds on hive ci

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/HiveMurmur3Adapter.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java
- ql/src/java/org/apache/hadoop/hive/ql/plan/ColStatistics.java
- ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java
- ql/src/test/org/apache/hadoop/hive/ql/plan/mapping/TestStatEstimations.java
- ql/src/test/queries/clientpositive/in_bitvector_filter.q
- ql/src/test/results/clientpositive/llap/in_bitvector_filter.q.out
https://issues.apache.org/jira/browse/HIVE-19647
> HIVE-19647: use bitvectors in IN operators

- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFOperator.java
- ql/src/test/queries/clientpositive/vector_windowing_row_number.q
- ql/src/test/results/clientpositive/llap/vector_windowing_row_number.q.out
See https://issues.apache.org/jira/browse/HIVE-25549
Qtest
> HIVE-25549: Wrong results for window function with expression in PARTITION BY or ORDER BY clause

- standalone-metastore/metastore-server/src/main/resources/package.jdo
> HIVE-25574: Replace clob with varchar when storing creation metadata

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
> Revert "HIVE-25355 : Exclude EXPLAIN from Read Txns. Need to be reverted once HIVE-25011 i…"

- ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
- ql/src/java/org/apache/hadoop/hive/ql/Context.java
- ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
- ql/src/java/org/apache/hadoop/hive/ql/lockmgr/HiveTxnManager.java
- ql/src/java/org/apache/hadoop/hive/ql/lockmgr/HiveTxnManagerImpl.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
> HIVE-25011: Concurrency: Do not acquire locks for EXPLAIN and initiate implicit transaction for SHOW commands

- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/TestTxnUtils.java
This PR adds a new config to help in division of queries. It will help in creating queries that are compatible with sql max parameters limit in MS SQL.
The default configurations can create queries with very huge number of parameters in the query.
No
Unit Tests
> HIVE-25659: Metastore direct sql queries with IN/(NOT IN) should be split based on max parameters allowed by SQL DB.

- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
Close the Reader automatically
To free up resources
No
Unit tests
> HIVE-25683: Close reader in AcidUtils.isRawFormatFile

- hbase-handler/src/java/org/apache/hadoop/hive/hbase/HBaseStorageHandler.java
- hbase-handler/src/test/org/apache/hadoop/hive/hbase/TestHBaseStorageHandler.java
- hbase-handler/src/test/resources/hbase-site.xml
Described in JIRA.
Described in JIRA.
No.
Tested on cluster + unit test is attached.
> HIVE-25685: HBaseStorageHandler: ensure that hbase properties are present in final JobConf for Tez

- pom.xml
Bump Xerce2 to 2.12.1
Xerce 2.9.1 has high-level vulnerabilities.
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-4002
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2012-0881
> HIVE-25636: Bump Xerce2 to 2.12.1.

- pom.xml
> HIVE-25697 Upgrade commons-compress to 1.21

- itests/src/test/resources/testconfiguration.properties
- ql/src/java/org/apache/hadoop/hive/ql/exec/ObjectCache.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ObjectCache.java
- ql/src/test/queries/clientpositive/offset_limit_mr.q
- ql/src/test/results/clientpositive/offset_limit_mr.q.out
> HIVE-25582: Empty result when using offset limit with MR

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
> HIVE-25115: Addendum: Cleaner queue order change

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
> HIVE-21075 : Metastore: Drop partition performance downgrade with Postgres

- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFNullif.java
- ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFNullif.java
- ql/src/test/queries/clientnegative/nullif_union.q
- ql/src/test/queries/clientpositive/udf_nullif.q
- ql/src/test/results/clientnegative/nullif_union.q.out
- ql/src/test/results/clientpositive/llap/udf_nullif.q.out
> HIVE-25738: NullIf doesn't support complex types

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
> HIVE-25757: Use cached database type to choose metastore backend queries

- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/show/ShowCreateTableOperation.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/JsonDescTableFormatter.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/TextDescTableFormatter.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/DDLPlanUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/ExplainTask.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/CheckConstraint.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/DefaultConstraint.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/ForeignKeyInfo.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/NotNullConstraint.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/PrimaryKeyInfo.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/TableConstraintsInfo.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/UniqueConstraint.java
- ql/src/test/queries/clientpositive/show_create_table.q
- ql/src/test/results/clientpositive/llap/constraints_explain_ddl.q.out
- ql/src/test/results/clientpositive/llap/show_create_table.q.out
Adding table constraints to `SHOW CREATE TABLE <TABLENAME>`
Tests:
`mvn test  -Dtest=TestMiniLlapLocalCliDriver -Dtest.output.overwrite=true -Dqfile=show_create_table.q`
> HIVE-25652: Add constraints in result of “SHOW CREATE TABLE ”

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2WithSplitUpdateAndVectorization.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommandsForMmTable.java
- ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
> HIVE-25755: TestTxnCommands classes refactor

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
- ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
> HIVE-25781: Restore multi-threaded support in Cleaner after HIVE-25115

- storage-api/src/java/org/apache/hive/common/util/TxnIdUtils.java
- storage-api/src/test/org/apache/hive/common/util/TestTxnIdUtils.java
This patch addresses a bug in TxnIdUtils.compare() 
Added additional unit test.
> HIVE-24975: Fixes a bug in ValidWriteIdList comparison in TxnIdUtils

- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
Fix of flaky test TestCompactionMetrics#testOldestReadyForCleaningAge
> HIVE-25716 Fix of flaky test TestCompactionMetrics#testOldestReadyForCleaningAge

- bin/hive-config.sh
- pom.xml
- standalone-metastore/pom.xml
Update log4j2 version to 2.15.0
To avoid Apache Log4j RCE Zero day exploit in all versions < 2.15.0
> HIVE-25795: [CVE-2021-44228] Update log4j2 version to 2.15.0

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Add some more info to the error message
Easier debugging
No
Unit tests
> HIVE-25764: Add reason for the compaction failure message

- common/src/java/org/apache/hadoop/hive/common/JavaUtils.java
- itests/src/test/resources/testconfiguration.properties
- llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/LimitOperator.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java
- ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
- ql/src/test/queries/clientpositive/limit_bailout.q
- ql/src/test/results/clientpositive/llap/limit_bailout.q.out
- ql/src/test/results/clientpositive/llap/smblimit.q.out
- ql/src/test/results/clientpositive/tez/limit_bailout.q.out
> HIVE-25751: Ignore exceptions related to interruption when the limit is reached

- itests/util/src/main/java/org/apache/hadoop/hive/ql/QOutProcessor.java
- itests/util/src/main/java/org/apache/hadoop/hive/ql/qoption/QTestReplaceHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/io/SingleFileSystem.java
- ql/src/test/org/apache/hadoop/hive/ql/io/TestSingleFileSystem.java
- ql/src/test/queries/clientnegative/sfs_nonexistent.q
- ql/src/test/results/clientnegative/sfs_nonexistent.q.out
> HIVE-25791: Improve SFS exception messages

- pom.xml
- standalone-metastore/pom.xml
HIVE-25804: Update log4j2 version to 2.16.0 to incorporate further CVE-2021-44228 hardening
Update log4j version to 2.16.0
To incorporate further changes related to CVE-2021-44228.
> HIVE-25804: Update log4j2 version to 2.16.0 to incorporate further CVE-2021-44228 hardening

- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/TextDescTableFormatter.java
- ql/src/test/results/clientpositive/llap/masking_mv.q.out
- ql/src/test/results/clientpositive/llap/masking_mv_by_text.q.out
- ql/src/test/results/clientpositive/llap/materialized_view_cluster.q.out
- ql/src/test/results/clientpositive/llap/materialized_view_create.q.out
- ql/src/test/results/clientpositive/llap/materialized_view_create_acid.q.out
- ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_4.q.out
- ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_5.q.out
- ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_time_window.q.out
- ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_time_window_2.q.out
- ql/src/test/results/clientpositive/llap/materialized_view_describe.q.out
- ql/src/test/results/clientpositive/llap/materialized_view_distribute_sort.q.out
- ql/src/test/results/clientpositive/llap/materialized_view_parquet.q.out
- ql/src/test/results/clientpositive/llap/materialized_view_partition_cluster.q.out
- ql/src/test/results/clientpositive/llap/materialized_view_partitioned.q.out
- ql/src/test/results/clientpositive/llap/show_materialized_views.q.out
Print transactional stats when `describe formatted` a materialized view.
Helps checking the state of an MV from rebuild perspective.
Yes. A new section is added to the report of `describe formatted`.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_describe.q -pl itests/qtest -Pitests
```
> HIVE-25745: Print transactional stats of materialized view source tables

- pom.xml
- standalone-metastore/pom.xml
> HIVE-25825: upgrade log4j 2.16.0 to 2.17.0+ due to CVE-2021-45105

- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
> HIVE-25830: Hive::loadPartitionInternal establishes connection often

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
Different query for the mysql
To improve the performance
No
Local machine
> HIVE-25841: Improve performance of deleteColumnStatsState

- ql/src/test/queries/clientpositive/order_by_pos.q
- ql/src/test/results/clientpositive/llap/order_by_pos.q.out
> HIVE-25818: Values query with order by position clause fails - ADDENDUM: add test

- ql/src/java/org/apache/hadoop/hive/llap/LlapCacheAwareFs.java
As described in jira, make sure of closing FSDataInputStream in LlapCacheAwareFs.readFully. This is simply achieved by putting the open call into a try-with-resources block (nothing else is changed):
```
try (FSDataInputStream is = fs.open(path, bufferSize)) {
```
This is suspected to lead to a socket leak in LLAP daemons.
No.
Customer side, on cluster.
> HIVE-25806: Possible leak in LlapCacheAwareFs - Parquet, LLAP IO

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterProjectTransposeRule.java
- ql/src/test/queries/clientpositive/ppd_windowing3.q
- ql/src/test/results/clientpositive/llap/ppd_windowing3.q.out
> HIVE-25864 : Hive query optimisation creates wrong plan for predicate pushdown with windowing function

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorUtil.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
isEligibleForCompaction currently runs under the ForkJoin.commonPool
> HIVE-25881: isEligibleForCompaction should be executed under the custom threadPool

- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
> HIVE-25777: ACID: Pick the compactor transaction over insert dir

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
Cleaner code fixed to update the correct metric.
Some test have been added.
> HIVE-25914 Fix of Cleaner updates Initiator cycle metric

- pom.xml
Bump Xerce2 to 2.12.2
Xerce 2.12.1 has high-level vulnerabilities.
- https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2022-23437
> HIVE-25920: Bump Xerce2 to 2.12.2.

- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
- standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CompactionMetricsDataStruct.java
- standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CompactionMetricsDataStruct.php
- standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
- standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
- standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionMetricsData.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionMetricsDataConverter.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
TxnStore#updateCompactionMetricsData can be optimised to use the same DB connection during create/update/delete if the delta metric threshold evaluation is moved inside this method.
Performance optimisation 
No
> HIVE-25916: Optimise updateCompactionMetricsData

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveFilterJoinRule.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveInBetweenExpandRule.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HivePointLookupOptimizerRule.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveRewriteToDataSketchesRules.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/jdbc/JDBCExpandExpressionsRule.java
Improve description of rules in subclasses
Improve debugging info
No
Not needed, only a change of rules' textual description
> HIVE-25884: Improve rule description for rules defined as subclasses

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/stats/HiveRelMdPredicates.java
Make `HiveRelMdPredicates` extend `RelMdPredicates`, and remove redundant methods.
The code was copied from Calcite long time ago, we are trying to unify the code and get rid of the Hive fork.
No
Re-executing the existing unit tests, no differences were found.
> HIVE-25951: HiveRelMdPredicates extends RelMdPredicates

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastHashTableLoader.java
* Introducing new HiveConf controlling the number of threads used in parallel HT load for MJ
* Extending VectorMapJoinFastHashTableLoader to support parallel HT loading
Support parallel HT loading for Fast HT implementations
NO
Existing tests cover functionality and correctness.
Performance tests will be added as part of HIVE-25146
> HIVE-25149: Support parallel load for Fast HT implementations

- itests/hive-minikdc/src/test/java/org/apache/hive/minikdc/TestJdbcWithMiniKdc.java
- service/src/java/org/apache/hive/service/cli/HiveSQLException.java
- service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIService.java
- service/src/test/org/apache/hive/service/cli/TestHiveSQLException.java
> HIVE-25844: Exception deserialization error-s may cause beeline to terminate immediately (backport HIVE-24772)

- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFStructField.java
- ql/src/test/queries/clientpositive/vectorization_nested_struct.q
- ql/src/test/results/clientpositive/llap/vectorization_nested_struct.q.out
> HIVE-25874: Slow filter evaluation of nest struct fields in vectorized executions

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSplit.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestInputFormatReaderDeletes.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestIcebergInputFormats.java
> HIVE-25967 initial change

- Jenkinsfile
- packaging/src/main/assembly/src.xml
Changes in the packaging files for the src tar.gz
We need the src package to be buildable
No
Manually:
```
tar -xvzf apache-hive-4.0.0-SNAPSHOT-src.tar.gz
cd apache-hive-4.0.0-SNAPSHOT-src
mvn clean install -DskipTests -Piceberg
```
> HIVE-25997: Fix release source packaging

- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Backport HIVE-25522 to branch-3
Issue mentioned in JIRA were hit in Hive 3 release
No
> HIVE-25991: Backport HIVE-25522 to branch-3

- hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestPartitionExpressionProxyDefault.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/security/TestDBTokenStore.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtil.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
- ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUpdaterThread.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorThread.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MetaStoreCompactorThread.java
- ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
- ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/TestHiveMetaStoreAuthorizer.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandlerContext.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/IHMSHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreThread.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStoreProxy.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RetryingHMSHandler.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestAdminUser.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreMethods.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreConnectionUrlHook.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestRawStoreProxy.java
- streaming/src/test/org/apache/hive/streaming/TestStreaming.java
> HIVE-25896: Remove getThreadId from IHMSHandler

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
> HIVE-25688: Addendum

- ql/src/java/org/apache/hadoop/hive/ql/plan/ConditionalResolverMergeFiles.java
- ql/src/test/queries/clientpositive/test_merge_tez_files.q
- ql/src/test/results/clientpositive/llap/test_merge_tez_files.q.out
> HIVE-26017 : Insert with partition value containing colon and space is creating partition having wrong value.

- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Initial commit set for the release of hive 3.1.3
CVEs mostly.
CVEs
No
Automated tests on master.
> Branch 3.1.3

- ql/pom.xml
Adding org.antlr:antlr-runtime to the bundle of hive-exec.jar
Without these classes there are ClassNotFoundException-s at runtime
No
By running the `analyze command` in hive-dev-box (now it's passing), and inspecting the bundle as follows:
```
dev@histograms:~/hive$ jar tf /tmp/dev/.hiveJars/hive-exec-4.0.0-SNAPSHOT-c1b7781dcb69f955946a02790df8a821e63c084874265699a7563ef6de864222.jar | grep CommonTree
org/antlr/runtime/tree/CommonTree.class
org/antlr/runtime/tree/CommonTreeAdaptor.class
org/antlr/runtime/tree/CommonTreeNodeStream.class
```
> HIVE-25994: Analyze table runs into ClassNotFoundException-s

- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
> HIVE-26025: Remove IMetaStoreClient#listPartitionNames which is not used

- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractBaseAlterTableAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/constraint/drop/AlterTableDropConstraintAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
This changes the rename table operation to non-blocking. Table rename operation doesn't affect the underlying directory structure, just the metadata.
This along with a few other changes will enable us to implement lockless reads, which provides perf boost to the transactional tables
No
Unit tests
> HIVE-25956: Non blocking RENAME TABLE implementation

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
To prevent missing column error
no
Manual sanity testing
> HIVE-26048: Missing quotation mark in findReadyToClean query

- itests/hive-unit/src/test/java/org/apache/hive/service/server/InformationSchemaWithPrivilegeTestBase.java
- itests/util/src/main/java/org/apache/hadoop/hive/ql/qoption/QTestSysDbHandler.java
- ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/PostgresTPCDS.java
Remove hardcoded version references from the tests
For easier version changes
No
Running the unit tests
> HIVE-26044: Remove hardcoded version references from the tests

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
> HIVE-26058: Choose meaningful names for the Metastore pool threads

- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastHashTable.java
> HIVE-25446: Wrong execption thrown if capacity<=0

- ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rewrite/AlterMaterializedViewRewriteAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
AlterMaterializedViewRewriteAnalyzer does not change the view content It just controls whether the view can be used in automatic query plan rewrite. No need for an EXCLUSIVE lock here.
Required for lockless reads.
No
Unit tests
> HIVE-26051: Non blocking ALTER MATERIALIZED VIEW REWRITE

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
> HIVE-25904: ObjectStore's updateTableColumnStatistics is not ThreadSafe

- ql/src/java/org/apache/hadoop/hive/ql/ddl/view/drop/DropViewAnalyzer.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
> HIVE-26053: Non blocking DROP VIEW

- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/drop/DropTableAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rewrite/AlterMaterializedViewRewriteAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/drop/DropMaterializedViewAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/drop/DropMaterializedViewOperation.java
- ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/Warehouse.java
> HIVE-26052: Non blocking DROP MATERIALIZED VIEW implementation

- pom.xml
> HIVE-26078: Upgrade gson to 2.8.9

- accumulo-handler/src/java/org/apache/hadoop/hive/accumulo/predicate/PrimitiveComparisonFilter.java
- pom.xml
> HIVE-26080: Upgrade accumulo-core to 1.10.1

- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
- ql/src/test/queries/clientpositive/whroot_external1.q
- ql/src/test/results/clientpositive/llap/whroot_external1.q.out
> HIVE-26098 : Duplicate path/Jar in hive.aux.jars.path or hive.reloadable.aux.jars.path causing IllegalArgumentException

- pom.xml
> HIVE-26109: Upgrade groovy to 2.4.21 due to CVE

- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/column/show/ShowColumnsOperation.java
- ql/src/test/queries/clientpositive/show_columns.q
- ql/src/test/results/clientpositive/llap/show_columns.q.out
…ins specific Chinese character
> HIVE-26105 : Show columns shows extra values if column comments contains specific Chinese character

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/rename/AlterTableRenamePartitionAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
- standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/RenamePartitionRequest.java
- standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/RenamePartitionRequest.php
- standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
- standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/Warehouse.java
- standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/AcidEventListener.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
This changes the rename partition operation to non-blocking. The data files of renamed partition would be copied to a new location, and data under prev location would be cleaned up later by the Compactor/Cleaner.
This along with a few other changes will enable us to implement lockless reads, which provides perf boost to the transactional tables.
No
Unit tests
> HIVE-25934: Non blocking RENAME PARTITION implementation

- itests/hive-unit/src/test/java/org/apache/hive/jdbc/miniHS2/TestHiveServer2Acid.java
- ql/src/java/org/apache/hadoop/hive/ql/DriverState.java
- ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
Proper ACID rollback handling in case of operation interruption
No
Itest
> HIVE-26121: Hive transaction rollback should be thread-safe

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java
When running an IOW operation we should check whether partition evolution happened or not. If it is the case, we should validate that the specId of the data manifest files are the same as the current specId. If all the specIds match the current one, it means that the data was rewritten and we are safe to complete the IOW operation. Otherwise, we should throw an exception. 
Avoid data duplication when running IOW on Iceberg tables with partition evolution
No
> HIVE-26133: Insert overwrite on Iceberg tables can result in duplicate entries after partition evolution

- data/files/vector_ptf_part_simple_all_datatypes.txt
- ql/src/test/queries/clientpositive/vector_ptf_bounded_start.q
- ql/src/test/results/clientpositive/llap/vector_ptf_bounded_start.q.out
> HIVE-26141: Fix vector_ptf_part_simple_all_datatypes source file.

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerWithEngineBase.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java
Set vectorization to false when reading/writing iceberg tables in avro format.
Vectorization for iceberg tables in avro is not yet supported.
No
> HIVE-26169: Set non-vectorized mode as default when accessing iceberg tables in avro fileformat

- service/src/java/org/apache/hive/service/cli/operation/HiveCommandOperation.java
- service/src/test/org/apache/hive/service/cli/operation/TestCommandWithSpace.java
fix hive command Operation bug .
jdbc connection hivesrerver2 using dfs command with prefix space will cause exception.
no
```
Connection con = DriverManager.getConnection("jdbc:hive2://10.214.35.115:10000/");
Statement stmt = con.createStatement();
// dfs command with prefix space or "\n"
ResultSet res = stmt.executeQuery(" dfs -ls /");
//ResultSet res = stmt.executeQuery("\ndfs -ls /");
```
> HIVE-26114: Fix jdbc connection hivesrerver2 using dfs command with prefix space will cause exception

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/AbstractJDBCConnectorProvider.java
Use correct OutputFormat when describing jdbc connector table
Incorrect OutputFormat when describing jdbc connector table
No
Small fix, just local cluster test.
**Before the fix:**
_describe formatted db_mysql.test;_
**After the fix:**
_describe formatted db_mysql.test;_
> HIVE-26131: Incorrect OutputFormat when describing jdbc connector table

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/JDBCConnectorProviderFactory.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/AbstractJDBCConnectorProvider.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/DerbySQLConnectorProvider.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/MSSQLConnectorProvider.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/MySQLConnectorProvider.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/OracleConnectorProvider.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/PostgreSQLConnectorProvider.java
Added implementations of connector provider for MSSQL and Oracle.
WIth these changes users will be able to create connectors for mssql and oracle.
Yes, users can now create data connectors based on oracle and mssql. Refer to hive ddl manual of data connectors for syntax.
Local machine, Remote cluster
> HIVE-25091: Implemented connector provider for MSSQL and Oracle

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/MySQLConnectorProvider.java
Change MySQLConnectorProvider driver from mariadb to mysql
mariadb driver may bring problem when getting native tables. We may could not get tables from both remote database and native database when mariadb driver in hive lib. 
Please refer to error stacktrace from https://issues.apache.org/jira/browse/HIVE-26180 
No
Local hive cluster and mysql cluster, and metastore use mysql to store metadata.
Also test with `dataconnector_mysql.q`:
mvn test -Dtest.output.overwrite  -Dtest=TestMiniLlapLocalCliDriver -Dqfile=dataconnector_mysql.q -pl itests/qtest -Pitests
> HIVE-26180: Change MySQLConnectorProvider driver from mariadb to mysql

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveCalciteUtil.java
> HIVE-25758: OOM due to recursive application of CBO rules (javadoc fix)

- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/DataSourceProvider.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/DbCPDataSourceProvider.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/datasource/HikariCPDataSourceProvider.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Create a new connection pool for compaction
To prevent compaction to use up all the connections in the default connection pool.
No.
Manual tests.
> HIVE-26155: Create a new connection pool for compaction

- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/constraint/drop/AlterTableDropConstraintAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
No need for EXCLUSIVE lock here
> HIVE-26106: Non blocking ADD, DROP CONSTRAINT

- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/add/AbstractAddPartitionAnalyzer.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnAddPartition.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
> HIVE-26076: Non blocking ADD PARTITION if not exists

- ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
> HIVE-23391: Non blocking ALTER TABLE add column

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/FilesForCommit.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergAcidUtil.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestHelper.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
- iceberg/iceberg-handler/src/test/queries/positive/update_iceberg_partitioned_avro.q
- iceberg/iceberg-handler/src/test/queries/positive/update_iceberg_partitioned_orc.q
- iceberg/iceberg-handler/src/test/queries/positive/update_iceberg_partitioned_parquet.q
- iceberg/iceberg-handler/src/test/queries/positive/update_iceberg_unpartitioned_parquet.q
- iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_avro.q.out
- iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_orc.q.out
- iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_parquet.q.out
- iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_avro.q.out
- iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_orc.q.out
- iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_parquet.q.out
- iceberg/iceberg-handler/src/test/results/positive/update_iceberg_unpartitioned_parquet.q.out
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
Implemented the UPDATE for Iceberg
Iceberg update
Yes. Update runs
Unit tests
> HIVE-26136: Implement UPDATE statements for Iceberg tables

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MetaStoreCompactorThread.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PersistenceManagerProvider.java
Create a new connection pool for compaction
To prevent compaction to use up all the connections in the default connection pool.
No.
Manual tests.
> HIVE-26177: Create a new connection pool for compaction (DataNucleus)

- common/src/java/org/apache/hadoop/hive/common/FileUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/sqlstd/SQLAuthorizationUtils.java
> HIVE-26199 Reduce FileSystem init during user impersonation

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Allow altering the metadata location of an iceberg table. If the new metadata belongs to another table raise an exception.
The user can execute 
`ALTER TABLE tbl_name SET TBLPROPERTIES('metadata_location'='')`
Unit test
> HIVE-26203: Implement alter iceberg table metadata location

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveFileWriterFactory.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergBufferedDeleteWriter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergDeleteWriter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergRecordWriter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergUpdateWriter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergWriter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergWriterBase.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterBuilder.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterRegistry.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergOutputCommitter.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/writer/HiveIcebergWriterTestBase.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/writer/TestHiveIcebergDeleteWriter.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/writer/TestHiveIcebergUpdateWriter.java
We started to have too many writers and the creation process was hard to understand.
Created a WriterBuilder with a clean interface to hide the internals
Make it easier to read the code
No
Unit tests
> HIVE-26202: Refactor Iceberg Writers

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/CustomTestHiveAuthorizerFactory.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/session/SessionStateUtil.java
Change Iceberg storage handler autz URI from `iceberg://dbName/tableName` format to `iceberg://metadataLocation`
It is possible to set the metadata pointers of table A to point to table B, and therefore you could read table B's data via querying table A.
No
> HIVE-26157: Change Iceberg storage handler authz URI to metadata location

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_partitioned_table.q
- iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_unpartitioned_table.q
- iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_with_joins.q
Turn off vectorization for iceberg metadata tables
Vectorization doesn't work with metadata tables.
No
Manual test
> HIVE-26251: Disable vectorization when querying iceberg metadata tables

- ql/src/java/org/apache/hadoop/hive/ql/exec/persistence/MapJoinTableContainerSerDe.java
- ql/src/java/org/apache/hadoop/hive/ql/security/authorization/command/CommandAuthorizerV2.java
Fixes for the Spark removal patch
Adding back erroneously removed code.
Removing an unused method
Just fixes
Unit tests
> HIVE-26261: Fix some issues with Spark engine removal

- iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergCTAS.java
Improve error message and add some unit tests
When running a CTAS query using a hive table that has a tinyint, smallint, varchar or char column it fails with an "Unsupported Hive type" error message. This can be worked around if the 'iceberg.mr.schema.auto.conversion' property is set to true on session level. We should communicate this possibility when raising the exception.
Unit test
> HIVE-26282: Improve iceberg CTAS error message for unsupported types

- ql/src/java/org/apache/hadoop/hive/ql/ddl/misc/msck/MsckAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/drop/DropTableAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/skewed/AlterTableSkewedByAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/drop/DropMaterializedViewAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
- ql/src/test/org/apache/hadoop/hive/ql/io/TestAcidUtils.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
- ql/src/test/org/apache/hadoop/hive/ql/parse/TestParseUtils.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/AcidEventListener.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/txn/ThrowingTxnHandler.java
Migrate operations that still require an EXCLUSIVE lock to EXCL_WRITE. 
Part of lockless-reads story
No
Unit tests
> HIVE-26293: Migrate remaining exclusive DDL operations to EXCL_WRITE lock & bug fixes

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/VectorizedReadUtils.java
Send only the fileName when creating vectorized Iceberg readers
To improve performance
No
Unit tests
> HIVE-26307: Avoid FS init in FileIO::newInputFile in vectorized Iceberg reads

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
> HIVE-25503: Amendment: Null-safe equality comparison

- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java
`dropDataConnector(String name, boolean ifNotExists, boolean checkReferences)`
if ifNotExists is true, there should be no exceptions thrown here.
No
Unit test
> HIVE-26299: Drop data connector with argument ifNotExists(true) should not throw NoSuchObjectException

- pom.xml
Upgrading commons-io library.
Uptaking new releases to keep up for new features and bug fixes including CVEs.
NO
Unit tests.
> HIVE-26321: Upgrade commons-io to 2.11.0 (Naveen Gangam)

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/MetastoreHousekeepingLeaderTestBase.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCleanerWithReplication.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
- ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PersistenceManagerProvider.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
… HMS Leader & pool sizing
Initialize datanucleus compaction pool only on HMS Leader & pool sizing
Unnecessary high DB connection usage
No
Manual
> HIVE-26177: Amendment: Initialize datanucleus compaction pool only on HMS Leader & pool sizing

- ql/src/java/org/apache/hadoop/hive/ql/plan/VectorPTFDesc.java
- ql/src/test/queries/clientpositive/vector_ptf_1.q
- ql/src/test/results/clientpositive/llap/vector_ptf_1.q.out
> HIVE-26340: Vectorized PTF operator fails if query has upper case window function

- iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveSchemaUtil.java
> HIVE-26298: Selecting complex types on migrated iceberg table does not work. (addendum)

- ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
- ql/src/test/queries/clientpositive/geospatial_udfs.q
- ql/src/test/results/clientpositive/llap/geospatial_udfs.q.out
- ql/src/test/results/clientpositive/llap/show_functions.q.out
Add tests to cover the geospatial UDFs
> HIVE-26240: Add tests for Esri UDFs for Geospatial.

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/RelOptHiveTable.java
- ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java
Fixes the given issue
This is not the expected behaviour
Fix
> HIVE-26358: Querying metadata tables does not work for Iceberg tables using HADOOP_TABLE

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/QueryWrapper.java
> HIVE-26057: Clean useless methods in QueryWrapper

- common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/TableMask.java
- ql/src/test/queries/clientnegative/masking_complex_type.q
- ql/src/test/results/clientnegative/masking_complex_type.q.out
Improving the current error message for column masking over complex data types, currently Hive is throwing a `ParseException` that is confusing to the end user. 
User should have a clear error saying that masking is not supported for complex data types.
No.
`mvn test -Dtest=TestNegativeLlapLocalCliDriver -Dqfile="masking_complex_type.q" -Dtest.output.overwrite -pl itests/qtest -Pitests`
> HIVE-26378: Improve error message for masking over complex data types

- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
> HIVE-26381: Fix link in Javadoc of MetaStoreUtils::getCurrentClassPaths

- ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java
- ql/src/test/queries/clientpositive/ctas_blob.q
- ql/src/test/results/clientpositive/llap/ctas_blob.q.out
> HIVE-26382 : Stats generation fails during CTAS for external partitioned table.

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergRecordObjectInspector.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergRecordObjectInspector.java
Add null check to object inspector
To avoid NPE
No
Unit test
> HIVE-26380: Fix NPE when reading a struct field with null value from iceberg table

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Only call stopHeartbeat when there is a transaction initialized, TXN > 0.
IllegalStateExecption will be thrown if there is nothing to compact.
No
> HIVE-26384: Compactor worker should not stop heartbeat for TXN 0

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
The column name "T2W_DATABASE" needs to be quoted.
> HIVE-26390: TxnHandler.getTxnDbsUpdated() SQL syntax error on Postgres.

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergDecimalObjectInspector.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergCTAS.java
In the case of decimal columns, the scale should be <= than precision. 
https://docs.oracle.com/javadb/10.6.2.1/ref/rrefsqlj15260.html
When creating an iceberg table that has a decimal column and in the column definition the scale <= precision an exception will be raised.
No
> HIVE-26403: Iceberg CTAS fails if source table schema contains decimal column

- ql/src/test/queries/clientpositive/ctas_open_csv_serde.q
- ql/src/test/results/clientpositive/llap/ctas_open_csv_serde.q.out
- serde/src/java/org/apache/hadoop/hive/serde2/OpenCSVSerde.java
Added support for other primitives apart from string in OpenCSV Serde
> HIVE-26388: ClassCastException when there is non string type column in source table of CTAS query.

- hbase-handler/pom.xml
Change hive-standalone-metastore-server dependency imports for hbase-handler. 1) Make the tests jar dependency scope test, 2) Pulling in the non-test dependency for runtime.
The test jar is currently being packaged which is incorrect and could lead to dependency confusion.
Test framework and by verifying in the package directory that the *tests.jar no longer shows up after packaging.
> HIVE-26418: Stop packaging hive-standalone-metastore-server*-tests.jar

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestHelper.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergTestUtils.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/JsonDescTableFormatter.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/TextDescTableFormatter.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/set/AlterTableSetPartitionSpecAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/DDLPlanUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/SortedDynPartitionOptimizer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransform.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/TransformSpec.java
- ql/src/java/org/apache/hadoop/hive/ql/plan/DynamicPartitionCtx.java
Consider iceberg sort-order param when writing out data files. 
Unit test, manual test
> HIVE-26397: Honour Iceberg sort orders when writing a table

- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
> HIVE-26416: AcidUtils.isRawFormatFile() throws InvalidProtocolBufferException for non-ORC file

- ql/src/test/org/apache/hadoop/hive/ql/parse/repl/metric/TestReplicationMetricCollector.java
> HIVE-26411 Fix TestReplicationMetricCollector flakiness

- pom.xml
- ql/pom.xml
Makes commons-pool2 an explicit dependency
To prevent runtime issues and to make a dependency that we directly use explicit.
No.
Through this PRs test framework and verification that the specified version of commons-pool2 is getting put in the packaging directory.
> HIVE-26423: Make commons-pool2 an explicit dependency (and upgrade to 2.11.1)

- data/files/scratch_col_issue_test_data/data.csv
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizationContext.java
- ql/src/test/queries/clientpositive/scratch_col_issue.q
- ql/src/test/results/clientpositive/llap/scratch_col_issue.q.out
> HIVE-26408: Vectorization: Fix deallocation of scratch columns, don't reuse a child ConstantVectorExpression as an output

- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
- ql/src/test/org/apache/hive/testutils/HiveTestEnvSetup.java
- shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
Described on jira.
Test stability.
No.
Full precommit testing.
> HIVE-26444: Use tez.local.mode.without.network for unit tests

- jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/JdbcStorageHandler.java
- Enhance the propagation of objectName to 'internal:metastore://' for STORAGEHANDLER_URI type of HivePrivilegeObject in case of hive.sql.database.type=METASTORE 
- Allows the policy definitions to be created independently from the actual implementation of the HMS database
Enables the authorization, makes it working compared to the current state where it does not work at all 
No
On a cluster
> HIVE-26433: StorageHandler authorization doesn't work with "METASTORE" db type

- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
skip collecting kafka delegation tokens if "kafka.consumer.security.protocol" or "kafka.producer.security.protocol" is set to "PLAINTEXT" in tblproperties.
For a kafka table, it can be pointed to a external unsecured Kafka cluster even hive is running in a secured cluster. In this case, tez will try to collect kafka delegation tokens, but failed
Previously, it failed to collect kafka delegation tokens if a unsecured kafka cluster is referred from a secure cluster.
Manually tested on a kafka cluster with kerberos disabled.
> HIVE-26439: Skip collecting Kafka delegation tokens if PLAINTEXT is set

- itests/util/src/main/java/org/apache/hadoop/hive/ql/externalDB/Oracle.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Oracle.java
Changing oracle docker image.
Optimizing precommit.
No.
```
mvn install  -Pitests,iceberg -Dtest=TestMiniLlapLocalCliDriver -Dqfile=jdbc_table_with_schema_oracle.q,qt_database_all.q,qt_database_oracle.q
```
> HIVE-26450: Use a lightweight oracle image

- pom.xml
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFMapIndexStringScalar.java
- ql/src/test/queries/clientpositive/orc_map_key_repeating.q
- ql/src/test/results/clientpositive/orc_map_key_repeating.q.out
> HIVE-26447: Vectorization: wrong results when filter on repeating map key orc table

- ql/src/test/queries/clientpositive/dataconnector_mysql.q
- ql/src/test/results/clientpositive/llap/dataconnector_mysql.q.out
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/AbstractJDBCConnectorProvider.java
Change `hive.sql.table`  tblproperty value from database.tablename to tablename.
Plead see error info from HIVE-26192;
CBO stage should get jdbc table info by using tablename instead of database.tablename.
No
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=dataconnector_mysql.q -Dtest.output.overwrite=true -pl itests/qtest -Pitests
> HIVE-26192: JDBC data connector queries occur exception at cbo stage

- ql/src/java/org/apache/hadoop/hive/ql/HiveQueryLifeTimeHook.java
Avoid NULL exception on `HiveQueryLifeTimeHook:checkAndRollbackCTAS`
Please see details from  https://issues.apache.org/jira/browse/HIVE-26466
No
No need test
> HIVE-26466: NullPointerException on HiveQueryLifeTimeHook:checkAndRollbackCTAS

- ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizableEvent.java
- ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java
- ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/AlterDataConnectorEvent.java
- ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/CreateDataConnectorEvent.java
- ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/DropDataConnectorEvent.java
- ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/TestHiveMetaStoreAuthorizer.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/events/PreAlterDataConnectorEvent.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/events/PreDropDataConnectorEvent.java
Add data connector authorization on HMS server-side
With this pr, user can authorize  DDL operation of 'connector'  on HMS server-side.
No
UT
> HIVE-26248: Add data connector authorization on HMS server-side

- service/src/java/org/apache/hive/service/servlet/QueryProfileServlet.java
> HIVE-26478: Explicitly set Content-Type in QueryProfileServlet

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
- ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
> HIVE-26487: Auto-compaction may hang or skip some of the eligible items

- common/src/java/org/apache/hadoop/hive/common/FileUtils.java
- common/src/test/org/apache/hadoop/hive/common/TestFileUtils.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtil.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/io/HdfsUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/io/FileOperations.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
Handled FileNotFoudExcrption in cleaner
When cleaner tries to remove files from HDFS location runs into java.io.FileNotFoundException:.In order to fix this we need to handle a exception thrown by DistributedFileSystem.listLocatedStatus method ->FileNotFoundException
No
With junit tests
> HIVE-26481:Cleaner fails with FileNotFoundException

- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/MetaStoreTestUtils.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java
Test improvements for TestHiveMetastore, described in jira.
Fix flaky test + useful assertion messages.
No.
Unit tests.
> HIVE-26500: Improve TestHiveMetastore

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/StorageFormat.java
Add support for ctlt queries for Iceberg tables.
> HIVE-26519: Iceberg: Add support for CTLT queries.

- iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergCTAS.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergMigration.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
> HIVE-26507 (addendum): Do not allow hive to iceberg migration if source table contains CHAR or VARCHAR columns

- ql/pom.xml
- ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLSemanticAnalyzerFactory.java
Workarounds and upgrades to fix issues regarding Reflections
> HIVE-26488: Fix NPE in DDLSemanticAnalyzerFactory during compilation.

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
- iceberg/iceberg-handler/src/test/results/negative/merge_split_update_off.q.out
- iceberg/iceberg-handler/src/test/results/negative/update_split_update_off.q.out
- iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_mixed.q.out
- iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_orc.q.out
- iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_parquet.q.out
- iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_mixed.q.out
- iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_orc.q.out
- iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_parquet.q.out
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelOptMaterializationValidator.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
We should raise an exception during the compilation phase when trying to run ACID operations.
An exception is raised during the execution phase, but that is a bit late. 
No
Unit test
> HIVE-26521: Iceberg: Raise exception when running delete/update statements on V1 tables

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreChecker.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestMsckCheckPartitions.java
change fs.listStatus to fs.listStatusIterator for non-blocking execution
MSCK repair is taking long time to validate multi-level partitionFolders in s3
No
TestHiveMetaStoreChecker testCode covers the code changes
> HIVE-26495 : MSCK repair perf issue HMSChecker ThreadPool threads are blocked at fs.listStatus

- llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapInputFormat.java
Making hostName field in LlapInputFormat static final 
Improves performance by avoiding the hostname resolution every time LlapInputFormat is instantiated.
No.
Unit and Integration tests.
> HIVE-22316: Avoid hostname resolution in LlapInputFormat

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
> HIVE-26543: Improve TxnHandler, TxnUtils, CompactionTxnHandler logging

- .github/assign-by-files.yml
> HIVE-26605: Remove reviewer pattern

- pom.xml
upgrade aws-java-sdk to 1.12.132 version
fixing CVE
No
Manual
> HIVE-26622:upgrade aws-java-sdk to 1.12.132 version

- service/src/java/org/apache/hive/service/cli/thrift/ThriftBinaryCLIService.java
Remove unused imports for org.apache.hive.service.cli.thrift.ThriftBinaryCLIService class
Remove unused imports for org.apache.hive.service.cli.thrift.ThriftBinaryCLIService class
No.
No.
> HIVE-26620: Remove unused imports for ThriftBinaryCLIService class

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/AsyncTaskCreateUdfFile.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
- streaming/src/test/org/apache/hive/streaming/TestStreaming.java
> HIVE-26617: Remove unused configurations

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
Some configurations still need to be set in session conf.
> HIVE-26556: ADDENDUM: Iceberg: Properties set in HiveIcebergSerde are not propagated to jobconf.

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionPoolOnTezTest.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsDesc.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsOperation.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
- ql/src/test/results/clientpositive/llap/dbtxnmgr_compact1.q.out
- ql/src/test/results/clientpositive/llap/dbtxnmgr_showlocks.q.out
- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
- standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ShowCompactResponseElement.java
- standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ShowCompactResponseElement.php
- standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
- standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnQueries.java
- standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
…output
Show Compaction output is sorted so that most recent job will appear at top in the list and extra columns are added to the output
Show Compaction output needed reformatting as it does not have consistency with 
recent added columns to COMPACTION view
https://issues.apache.org/jira/browse/HIVE-26563
No
Junit and Q tests
> Hive-26563: Add extra columns in Show Compactions output and sort the output

- ql/src/java/org/apache/hadoop/hive/ql/exec/ExplainTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/ConstantVectorExpression.java
- ql/src/test/queries/clientpositive/chinese_utf8_characters.q
- ql/src/test/results/clientpositive/llap/chinese_utf8_characters.q.out
> HIVE-26639: ConstantVectorExpression and ExplainTask shouldn't rely on default charset

- ql/src/test/queries/clientpositive/dataconnector_mysql.q
- ql/src/test/results/clientpositive/llap/dataconnector_mysql.q.out
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/AbstractDataConnectorProvider.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/AbstractJDBCConnectorProvider.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/MySQLConnectorProvider.java
> HIVE-26045: Detect timed out connections for providers and auto-reconnect

- ql/src/test/queries/clientpositive/chinese_utf8_characters.q
- ql/src/test/results/clientpositive/llap/chinese_utf8_characters.q.out
- serde/src/java/org/apache/hadoop/hive/serde2/MultiDelimitSerDe.java
> HIVE-26651: MultiDelimitSerDe shouldn't rely on default charset when returning the deserialized string

- iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveCreateReplaceTableTest.java
- iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
- iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveTableConcurrency.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
- iceberg/pom.xml
https://iceberg.apache.org/releases/#100-release
The 1.0.0 release officially guarantees the stability of the Iceberg API.
> HIVE-26675: Update Iceberg from 0.14.1 to 1.0.0

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Please see comment: https://github.com/apache/hive/pull/3312#discussion_r950617222
No
> HIVE-26248: Add data connector authorization on HMS server-side(addendum)

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- hbase-handler/src/test/results/positive/hbase_queries.q.out
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/like/CreateTableLikeOperation.java
- ql/src/test/queries/clientpositive/avro_extschema_insert.q
- ql/src/test/queries/clientpositive/create_like2.q
- ql/src/test/results/clientpositive/llap/avro_extschema_insert.q.out
- ql/src/test/results/clientpositive/llap/create_like.q.out
- ql/src/test/results/clientpositive/llap/create_like2.q.out
- ql/src/test/results/clientpositive/llap/create_like_tbl_props.q.out
- ql/src/test/results/clientpositive/llap/create_like_view.q.out
- ql/src/test/results/clientpositive/llap/partition_discovery.q.out
> HIVE-25813: Create Table x Like commands based storage handlers fail over is fixed

- common/src/java/org/apache/hadoop/hive/common/LogUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
> HIVE-25585: Put dagId to MDC once it's available in HS2

- ql/src/java/org/apache/hadoop/hive/ql/exec/SerializationUtilities.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/ppr/PartitionExpressionForMetastore.java
- ql/src/test/org/apache/hadoop/hive/metastore/TestMetastoreExpr.java
> HIVE-26667: Incompatible expression deserialization against latest HMS

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/PlanModifierForASTConv.java
- ql/src/test/queries/clientpositive/count_distinct_subquery.q
- ql/src/test/results/clientpositive/llap/count_distinct_subquery.q.out
The PlanModifier code modified a RelNode in place, but used the stale RelNode when drilling down into its children.
Described in the jira
Fixes HIVE-26676
No
Added q test
> HIVE-26676: Count distinct in subquery returning wrong results

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveAggregate.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveAntiJoin.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveExcept.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveFilter.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveIntersect.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveJoin.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveProject.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveRelNode.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveSemiJoin.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveSortExchange.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveSortLimit.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveTableFunctionScan.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveTableScan.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveUnion.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/jdbc/HiveJdbcConverter.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewBoxing.java
Remove dead code from `HiveRelNode`:
* nested class `Implementor`
* method
```
void implement(Implementor implementor);
```
No
Run existing Ptest.
> HIVE-26747: Remove implementor from HiveRelNode

- jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
> [HIVE-26743]backport HIVE-24694

- ql/src/java/org/apache/hadoop/hive/ql/udf/ptf/ValueBoundaryScanner.java
- ql/src/test/queries/clientpositive/windowing_tinyint.q
- ql/src/test/results/clientpositive/llap/windowing_tinyint.q.out
Added handling for a tinyint.
Added tinyint handling for a windowng function
To get the tinyint processing to work
No
Added qtest that failed before the change
> HIVE-26726: Tinyint column with windowing fn crashes at runtime

- ql/src/test/queries/clientpositive/complex_alias.q
- ql/src/test/results/clientpositive/llap/complex_alias.q.out
Change-Id: I6d4f5393bd789427f23ea58de98f4a9703a79360
Adding a SORT_QUERY_RESULTS command at the beginning of the complex_alias.q test script to make its results deterministic.
Without the sort command the results of the query are non-deterministic and can occasionally lead to failed tests.
No
Executed locally
> HIVE-26761: Add result sorting to complex_alias.q

- ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/AbstractGenericUDFArrayBase.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayMax.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayMin.java
- ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestAbstractGenericUDFArrayBase.java
- ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayMax.java
- ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayMin.java
- ql/src/test/queries/clientpositive/udf_array_max.q
- ql/src/test/queries/clientpositive/udf_array_min.q
- ql/src/test/results/clientpositive/llap/show_functions.q.out
- ql/src/test/results/clientpositive/llap/udf_array_max.q.out
- ql/src/test/results/clientpositive/llap/udf_array_min.q.out
Implement array_max and array_min UDFs in Hive 
These enhancements are already implemented in Spark
No
> HIVE-26744 - Add array_max and array_min UDFs

- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactOperation.java
- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
- standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/ShowCompactRequest.java
- standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ShowCompactRequest.php
- standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
- standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
- standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
https://issues.apache.org/jira/browse/HIVE-26764
https://issues.apache.org/jira/browse/HIVE-26764.. So that filtering show compaction is optional
Yes
manually
> HIVE-26764:Show compaction request should have all filds optional

- hplsql/src/main/java/org/apache/hive/hplsql/udf/Udf.java
- itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
HPLSQL UDF is not working if it is applied on a column of type varchar/char/decimal in a table.
Checked and supported all primitive types like boolean, smallint, int, bigint, float, double, string, date, timestamp, decimal, varchar and char types.
The changes supports users to create HPLSQL functions with all primitive types.
To fix HIVE-26768 and also it helps users to create HPLSQL functions with all primitive types.
No
Tests are added.
> HIVE-26768: HPLSQL UDF is not working if it is applied on a column of type varchar/char/decimal in a table.

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
- iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_mixed.q
- iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_multitable.q
- iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_orc.q
- iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_parquet.q
- iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_mixed.q.out
- iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_multitable.q.out
- iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_orc.q.out
- iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_parquet.q.out
- iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_mixed.q.out
- iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_multitable.q.out
- iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_orc.q.out
- iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_parquet.q.out
- itests/src/test/resources/testconfiguration.properties
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedInputFormatInterface.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
Fix Vectorization for Iceberg tables
Configuration getting propagated for non iceberg tables as well
Yes, The query passes
Added a UT
> HIVE-26742: Iceberg: Vectorization fails incase of multiple tables in queries.

- Jenkinsfile
> Increase Split to 22.

- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFSum.java
- ql/src/test/queries/clientpositive/windowing_sum_following_null.q
- ql/src/test/results/clientpositive/llap/windowing_sum_following_null.q.out
The sum windowing function is returning an incorrect value when all the "following" rows are null.  The correct value for sum when all the rows are null is "null".
A new member variable had to be added to track for nulls. It uses the same algorithm that is used for sums. The sums are tracked by keeping a running sum across all the rows and subtracting off the running sum outside the window. Likewise, we keep track of a running non null row count for the current row and subtract the non null row count of the row that is leaving the window.
> HIVE-26683: Sum windowing function returns wrong value when all nulls.

- pom.xml
When using the `thriftif` profile to update the thrift-generated files, the thrift version configured is checked against the expected one, and the task fail explicitly if there is a mismatch, instead of trying to compile anyway.
Failing fast saves time and it's more explicit due to the clear error message.
No.
Locally by using a correct/incorrect thrift version and running `mvn clean install -Pthriftif -DskipTests -Dthrift.home=/usr/local`
> HIVE-26692: Check for the expected thrift version before compiling

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/security/authorization/command/CommandAuthorizerV2.java
- ql/src/test/queries/clientpositive/authorization_functions_in_views.q
- ql/src/test/results/clientpositive/llap/authorization_functions_in_views.q.out
Making the authorizations on custom UDFs involved in tables/view configurable.
To avoid giving unwanted permissions on UDFs to any user accessing view/tables having UDFs
No.
Local machine, Remote cluster.
> HIVE-26799: Make authorizations on custom UDFs involved in tables/view configurable.

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/MetastoreHousekeepingLeaderTestBase.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetastoreHousekeepingLeader.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetastoreHousekeepingLeaderEmptyConfig.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetastoreHousekeepingNonLeader.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetastoreLeaseLeader.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetastoreLeaseNonLeader.java
- ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUpdaterThread.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/ReplChangeManager.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PersistenceManagerProvider.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/AuditLeaderListener.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/CMClearer.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/CompactorPMF.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/CompactorTasks.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/HostLeaderElection.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/HouseKeepingTasks.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaderElection.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaderElectionContext.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaderElectionFactory.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaderException.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/LeaseLeaderElection.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/leader/StatsUpdaterTask.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/leader/TestLeaderElection.java
Added unit tests, standalone HMS cluster
> HIVE-26509: Introduce dynamic leader election in HMS

- ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/AlterViewAsAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/CreateViewAnalyzer.java
Added column of source table for alter view query.
Columns of source table should not be null
No
Remote cluster.
> HIVE-26850: Added columns info of source table for alter view query

- iceberg/iceberg-shading/pom.xml
- iceberg/patched-iceberg-core/pom.xml
- iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/hadoop/HadoopInputFile.java
Use fsadvise as normal
Performance benefits
No
> HIVE-26699: Iceberg: S3 fadvise can hurt JSON parsing significantly in DWX.

- itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniDruidCliDriver.java
- itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniDruidKafkaCliDriver.java
- pom.xml
- ql/src/test/queries/clientpositive/druid_timestamptz2.q
- ql/src/test/queries/clientpositive/druidmini_extractTime.q
- ql/src/test/queries/clientpositive/druidmini_floorTime.q
- ql/src/test/queries/clientpositive/druidmini_mv.q
- ql/src/test/queries/clientpositive/druidmini_test1.q
- ql/src/test/queries/clientpositive/druidmini_test_alter.q
- ql/src/test/queries/clientpositive/druidmini_test_insert.q
- ql/src/test/queries/clientpositive/druidmini_test_ts.q
- standalone-metastore/pom.xml
- testutils/ptest2/pom.xml
HIVE-26867 : Backport of HIVE-24816: Jackson version changed to 2.11.0 in the pom files (#2075) (Sai Hemanth Gantasala, reviewed by Yongzhi Chen)
> HIVE-26867 : Backport of HIVE-24816

- itests/bin/generate-cli-splits.sh
- itests/qtest-spark/pom.xml
- itests/qtest-spark/src/test/java/org/apache/hadoop/hive/cli/TestMiniSparkOnYarnCliDriver.java
- itests/qtest-spark/src/test/java/org/apache/hadoop/hive/cli/TestSparkCliDriver.java
- itests/qtest/pom.xml
- itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestCliDriver.java
- itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestEncryptedHDFSCliDriver.java
- itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniLlapCliDriver.java
- itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniLlapLocalCliDriver.java
- itests/util/src/main/java/org/apache/hadoop/hive/cli/control/SplitSupport.java
- itests/util/src/test/java/org/apache/hadoop/hive/cli/control/TestSplitSupport.java
- itests/util/src/test/java/org/apache/hadoop/hive/cli/control/splitsupport/SplitSupportDummy.java
- itests/util/src/test/java/org/apache/hadoop/hive/cli/control/splitsupport/split0/SplitSupportDummy.java
- itests/util/src/test/java/org/apache/hadoop/hive/cli/control/splitsupport/split125/SplitSupportDummy.java
Backport of HIVE-23323: Add qsplits profile to branch-3
> HIVE-26879: Backport of HIVE-23323: Add qsplits profile

- itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniLlapArrow.java
(cherry picked from commit 77187b3e621d6d35634338e72b4006aaf8ba22fb)
> HIVE-26878 : Ignore TestJdbcWithMiniLlapVectorArrow

- ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
- ql/src/java/org/apache/hadoop/hive/ql/Driver.java
- ql/src/java/org/apache/hadoop/hive/ql/DriverContext.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
The functional change is to not clear the query context completely when re-compiling the query.
It is a bug that can cause duplicate records or other incorrect behavior.
No - except fixing the bug
Added test cases and tested on a 3 node cluster.
> HIVE-26875: Preserve query context on transaction conflict

- pom.xml
- ql/src/java/org/apache/hadoop/hive/ql/io/arrow/ArrowColumnarBatchSerDe.java
- ql/src/java/org/apache/hadoop/hive/ql/io/arrow/Serializer.java
- ql/src/test/org/apache/hadoop/hive/ql/io/arrow/TestArrowColumnarBatchSerDe.java
Backported https://issues.apache.org/jira/browse/HIVE-20751 and https://issues.apache.org/jira/browse/HIVE-23987 for this.
Please refer to this JIRA : https://issues.apache.org/jira/browse/HIVE-26899
> HIVE-26899 : Backport HIVE-20751 HIVE-23987 Upgrade arrow to 0.11.0 in branch-3

- itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliConfigs.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-26907
> HIVE-26907 : Backport of HIVE-20741: Disable udaf_context_ngrams.q and udaf_corr.q tests

- itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliConfigs.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-26909
> HIVE-26909 : Backport of HIVE-20715: Disable test:  udaf_histogram_numeric

- pom.xml
This PR aims to publish SBOM artifacts along with the other Apache projects.
- https://cwiki.apache.org/confluence/display/COMDEV/SBOM
Here is an article to give some context.
- https://www.activestate.com/blog/why-the-us-government-is-mandating-software-bill-of-materials-sbom/
Software Bill of Materials (SBOM) are additional artifacts containing the aggregate of all direct and transitive dependencies of a project. The US Government (based on NIST recommendations) currently accepts only the three most popular SBOM standards as valid, namely: [CycloneDX](https://cyclonedx.org/), [Software Identification (SWID) tag](https://csrc.nist.gov/projects/Software-Identification-SWID), [Software Package Data Exchange® (SPDX)](https://spdx.dev/).
This PR uses one of the Maven plugin, [CycloneDX maven …
> HIVE-26912: Publish SBOM artifacts

- pom.xml
Upgrade Parquet version.
To be in sync with Iceberg Parquet version & Other benifits
No
Jenkins Tests
> HIVE-26917: Upgrade parquet to 1.12.3.

- ql/src/java/org/apache/hadoop/hive/ql/exec/HiveWritableComparator.java
- ql/src/test/queries/clientpositive/join_cond_zero_comp_negativezero.q
- ql/src/test/results/clientpositive/llap/join_cond_zero_comp_negativezero.q.out
A query whose join predicate compared 0 with -0 where at least one of these was a floating-point value returned incorrect results.
The changes will fix [HIVE-26936](https://issues.apache.org/jira/browse/HIVE-26936) issue.
The IEEE 754 floating point spec specifies that signed -0.0 and 0.0 should be treated as equal. 
As per the IEEE 754 floating point spec specifies that signed -0.0 and 0.0 should be treated as equal but currently as a part of join condition we are treating them as different so fixed the same to consider them as equal.
No
Using .q files.
> HIVE-26936: Floating point zero and signed zero comparison as a part of join predicate is considered as not equal.

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
Fixed a bug in ReplicationSemanticAnalyzer which unsets a property required by optimized bootstrap during failback.
To ensure proper working of optimized bootstrap during failback.
No
> HIVE-26597: Fix unsetting of db property repl.target.for in ReplicationSemanticAnalyzer

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
This change helps to gracefully fail with proper error message when target db is dropped.
Avoids NPE.
NO
* Tested the change in local environment and also in on-prem cluster.
> HIVE-26943 : Fix NPE during Optimised Bootstrap when db is dropped

- common/src/test/org/apache/hadoop/hive/common/metrics/metrics2/TestCodahaleMetrics.java
This commit was done in the mast branch without raising a JIRA ticket, Please check this commit : 130f80445d589cdd82904cea1073c84d1368d079. Disabling this test since it is flaky.
> HIVE-26915: Disable TestCodahaleMetrics.testFileReporting flaky

- service/pom.xml
- standalone-metastore/pom.xml
> HIVE-26681:Remove dom4j: flexible XML framework for Java from hive

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplWithReadOnlyHook.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/repl/ReplConst.java
Details :
* Basically first load(Boostrap load) set's the target db readonly.
* During incremental load it checks if target db is set to readonly, if not set then it makes target db readonly (basically to ensure backward compatibility)
Tests :
* Added unit tests to cover the same
* Tested manually in local environment
This makes TARGET database readonly just after first bootstrap load.
It ensures the TARGET database is always consistent and is only used for syncing changes from the SOURCE
NO
* added unit tests from the same
* Also tested this in local environment
> HIVE-26711 The very first REPL Load should make the Target Database read-only.

- itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestTriggersWorkloadManager.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-26969
Please find the unstable scenario here : http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3900/11/tests/
(cherry picked from commit 4dbf991b48f5e7b34428c7c23fe34a77e0a9987a)
> HIVE-26969 : Backport of HIVE-20074: Disable TestTriggersWorkloadManager as it is unstable

- ql/src/test/results/clientpositive/llap/results_cache_2.q.out
- ql/src/test/results/clientpositive/llap/sharedwork.q.out
- ql/src/test/results/clientpositive/llap/subquery_views.q.out
- testutils/ptest2/src/main/resources/log4j2.properties
- testutils/ptest2/src/test/resources/log4j2.properties
JIRA link : https://issues.apache.org/jira/browse/HIVE-26970
These tests were fixed already in branch-3.1 but were not backported to branch-3. Please follow this commit ID where these tests were fixed : a9dc9368
> HIVE-26970 : Fixes for some test failures with LLAP Driver

- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
> HIVE-24404: Invoke getUserName before getMSC to avoid metastore client connection been closed and retry

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
Setting savepoint in transaction before direct sql processing and rollback to savepoint before moving to JDO processing.
Failure in direct SQL processing do not undo the changes made to database before falling back to JDO based processing. Thus results in stale/dangling entries in database forever.
For instance, during dropPartitions() direct SQL processing, after dropping rows from few tables(like PARTITIONS, PARTITION_PARAMS, PARTITION_KEY_VALS etc), it causes typecast exception in dropStorageDescriptors() and fallback to JDO processing. But datanucleus JDO processing cannot delete rows from remaining tables(i.e., from sds, serdes, sds_params, serde_params, sort_cols, bucketing_cols, skewed cols/values/location if any for the partitions) since the partition is already deleted in the …
> HIVE-26976: Failure in direct SQL processing do not undo the changes made to database before fallback to JDO

- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerTimezone.java
- ql/src/java/org/apache/hadoop/hive/ql/io/sarg/ConvertAstToSearchArg.java
> HIVE-26989 Fix predicate pushdown for Timestamp with TZ

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
Add err flag, which is true when an error is caught which launching a worker job, and use this flag as check for thread to wait/sleep
[HIVE-26947](https://issues.apache.org/jira/browse/HIVE-26947)
Avoid high frequency connection respawning to HMS in case of any exception
No
Unit tests
> HIVE-26947: Handle compaction.Worker sleep for err cases to avoid high frequency connection respawning to HMS

- ql/src/test/results/clientnegative/subquery_subquery_chain.q.out
JIRA link : https://issues.apache.org/jira/browse/HIVE-26973
Link to test failures : (http://ci.hive.apache.org/job/hive-precommit/job/branch-3)
> HIVE-26973 : Test fixes for subquery_subquery_chain.q

- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
Problem:
- If Incremental Dump operation failes while dumping any event id in the staging directory. Then dump directory for this event id along with file _dumpmetadata still exists in the dump location. which is getting stored in _events_dump file
- When user triggers dump operation for this policy again, It again resumes dumping from failed event id, and tries to dump it again but as that event id directory already created in previous cycle, it fails with the exception Solution:
- fixed cleanFailedEventDirIfExists to remove folder for failed event id for a selected database
> HIVE-26933: Cleanup dump directory for eventId which was failed in previous dump cycle

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
Handling controlled failover during optimized bootstrap.
To ensure optimized bootstrap completes successfully.
> HIVE-26600: Handle failover during optimized bootstrap

- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergTimeTravel.java
- parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g
- ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Allow expressions in time travel queries, such as 
````
FOR SYSTEM_TIME AS OF CURRENT_TIMESTAMP - interval '10' hours
````
User experience
Yes
Unit test
> HIVE-26995: Iceberg: Enhance time travel syntax with expressions

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplAcrossInstancesWithJsonMessageFormat.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExternalTables.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestTableLevelReplicationScenarios.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWork.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/incremental/IncrementalLoadEventsIterator.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/incremental/IncrementalLoadTasksBuilder.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/EventsDumpMetadata.java
Make repl dump, dump events in batches so that repl load does not load all the events in staging directory into memory.
To avoid O.O.M incase of large number of events dumped by repl dump.
No
> HIVE-26937: Batching incremental events to avoid O.O.M during repl load

- jdbc/pom.xml
JIRA link : https://issues.apache.org/jira/browse/HIVE-27028
This commit is already present in branch-3.1 from where Hive-3.1.3 was cut. So we should include this Backport on branch-3.
> HIVE-27028 : Backport of HIVE-18874: JDBC: HiveConnection shades log4j interfaces

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/EventHandler.java
Fixed a bug in Repl Dump to fix dumped events count when open transactions are filtered.
To ensure appropriate dumped  events count are reflected in replication metrics.
> HIVE-26961: Fix improper replication metric count when open transactions are filtered.

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_copy_on_write.q
- iceberg/iceberg-handler/src/test/results/positive/iceberg_copy_on_write.q.out
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
Allow Copy On Write for Delete Queries.
To support COW mode for deletes for iceberg tables.
Yes, For Deletes COW mode can be used.
UT
> HIVE-27031: Iceberg: Implement Copy-On-Write for Delete Queries.

- ql/src/test/results/clientpositive/llap/external_jdbc_auth.q.out
JIRA link : https://issues.apache.org/jira/browse/HIVE-27090
This test was newly added in https://issues.apache.org/jira/browse/HIVE-20651 but the test has continuously failed on branch-3. Needs a fix. No other change had been committed to this test after this ticket. Since the ticket was merged in branch-3 without validating the test, fixing it now.
> HIVE-27090 : Test fix for external_jdbc_auth.q

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/PartitionProjectionEvaluator.java
> HIVE-27091: Add double quotes for tables in PartitionProjectionEvaluator

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Fix the flaky compaction tests
Note: follow-up task: https://issues.apache.org/jira/browse/HIVE-27121
In order to make CI builds more stable
No
Manually
> HIVE-27117: Fix compaction related flaky tests

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorUtil.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/FSRemover.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MetaStoreCompactorThread.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MetadataCache.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/handler/TaskHandler.java
Use Caffeine for caching metadata objects in Compactor threads
Caffeine is a better library than Guava for caching, hence better to use it.
No
Existing tests
> HIVE-27122: Use Caffeine for caching metadata objects in Compactor threads

- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/OptimisedBootstrapUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWork.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWorkMBean.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/DumpMetaData.java
- Added dump_execution_id in Metadata file which is being picked up by Load operation
> HIVE-27123 : In PRE_OPTIMIZED_BOOTSTRAP operation, Load side stores dump_execution_id as -1

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- iceberg/iceberg-handler/src/test/queries/positive/delete_all_iceberg.q
- iceberg/iceberg-handler/src/test/results/positive/delete_all_iceberg.q.out
- ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
apply "truncate" optimisation in case of "delete *". 
Currently, in MOR mode, Hive creates "positional delete" files during deletes. With "Delete from <tab or specific partition> ", the entire dataset in the table or partition is written as a "positional delete" file.
During read operation, all these files are read again causing huge delay.
> HIVE-27160: Iceberg: Optimise delete (entire) data from table

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/events/filesystem/DatabaseEventsIterator.java
- standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/InjectableBehaviourObjectStore.java
This PR backports HIVE-20680 to branch-3 needed to fix TestReplicationScenariosAcrossInstances
Fix TestReplicationScenariosAcrossInstances
NO
CI Job
> HIVE-27171: Backport HIVE-20680 to branch-3

- service/src/java/org/apache/hive/service/cli/OperationStatus.java
- service/src/java/org/apache/hive/service/cli/operation/Operation.java
- service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIService.java
- service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIServiceClient.java
This PR backports HIVE-20897 to branch-3 to fix TestJdbcDriver2#testSelectExecAsync2
Test fix
No
CI Job
> HIVE-27175: Backport HIVE-20897 to branch-3

- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
- standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetastoreHttpHeaders.java
This PR targets to backport the https://issues.apache.org/jira/browse/HIVE-27129 to branch 3.
No noticeable difference has been introduced in the backport. 
existing test in the original PR
> HIVE-27136: Backport HIVE-27129 to branch-3 

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/session/SessionStateUtil.java
Cache iceberg table while reading stats.
Perf benifits.
No
Existing Tests.
> HIVE-27185: Iceberg: Cache iceberg table while loading for stats.

- common/src/java/org/apache/hive/http/ProfileServlet.java
Adding support for method name profiling to Hive's ProfileServlet.
Hive has ProfileServlet. It makes use of async-profiler and allows profiling specific events. Currently profileServlet supports events like cpu, alloc, lock etc. It will be good to enhance to support method name profiling as well.
No
- Automated pre-commit tests; 
- Manual testing: below files are outputs of 2 calls to ProfilerServlet, one with event=CPU (default) and another with profiling specific method:
1. curl "http://localhost:10002/prof?output=tree&duration=60&interval=1"
2. curl "http://localhost:10002/prof?output=tree&duration=60&interval=1&method=org.apache.hadoop.hive.ql.io.AcidUtils.getTableValidWriteIdListWithTxnList"
[async-prof-pid-95455-cpu-2.tree.txt](https://github.com/apache/hive/files/11150886/async-prof …
> HIVE-27184: Add class name profiling option in ProfileServlet.

- beeline/pom.xml
- beeline/src/test/org/apache/hive/beeline/TestBeelineArgParsing.java
- pom.xml
- standalone-metastore/pom.xml
Upgrade postgresql to 42.5.1 from 9.x in branch-3
The changes are needed to fix critical CVE's like mentioned here https://mvnrepository.com/artifact/org.postgresql/postgresql
No this just upgrades the postgres version
Jenkins build
> HIVE-27216: Upgrade postgresql to 42.5.1 from 9.x in branch-3

- jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-27232
This commit was present in branch-3.1 (Hive 3.1.3 release) so it is necessary to backport this to branch-3.
> HIVE-27232 : Backport of HIVE-24694: Early connection close to release server resources during creating

- service/src/java/org/apache/hive/service/cli/operation/OperationManager.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-27231
This commit was present in Hive-3.1.3 release so it is necessary to backport this to branch-3
> HIVE-27231 : Backport of HIVE-26530 to branch-3

- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/security/TokenStoreDelegationTokenSecretManager.java
- standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/security/TestTokenStoreDelegationTokenSecretManager.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-27230
This ticket was present in branch-3.1 from where Hive-3.1.3 was released, so it is necessary to backport these changes to branch-3
> HIVE-27230 : Backport of HIVE-22033 and HIVE-26522 to branch-3

- service/src/java/org/apache/hive/service/server/HiveServer2.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-27206
This issue was already a part of Hive-3.1.3 so it should be cherry picked to branch-3
> HIVE-27206: Backport of HIVE-20179: Some Tez jar-s are not on classpath so HS2 keeps too long

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/reexec/TestReExecuteKilledTezAMQueryPlugin.java
- ql/src/java/org/apache/hadoop/hive/ql/DriverFactory.java
- ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecuteLostAMQueryPlugin.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-27249
> HIVE-27249: Backport of HIVE-23619: Add new plugin to rerun queries when Tez AM is down due to lost node

- ql/src/test/queries/clientpositive/schq_materialized.q
- ql/src/test/results/clientpositive/llap/schq_materialized.q.out
HIVE-23691
Enabling schq_materialized.q in test suite
No
via test
> HIVE-23691 : TestMiniLlapLocalCliDriver#testCliDriver[schq_materializ…ed] is flaky

- iceberg/pom.xml
- pom.xml
Upgrade kryo version to 5.2.0 
Please Refer [HIVE-27110](https://issues.apache.org/jira/browse/HIVE-27110) for more info.
No
manual
> [HIVE-27110] Upgrade com.esotericsoftware:Kryo version to 5.2.0 

- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/metrics/TestMetrics.java
HIVE-23682
To enable test in testsuite
NO
testcse
> HIVE-23682 : TestMetrics is flaky

- ql/src/test/queries/clientpositive/external_jdbc_table3.q
- ql/src/test/queries/clientpositive/external_jdbc_table4.q
HIVE-25289
To enable tests in test suite
NO
with test case
> HIVE-25289 : Fix external_jdbc_table3 and external_jdbc_table4

- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
This PR backports HIVE-27258 to branch-3 since the issue also affects branch-3.
Backport HIVE-27261 to branch-3
No
Existing unit tests cover this functionality.
> HIVE-27261: Backport HIVE-27258 to branch-3

- pom.xml
- standalone-metastore/pom.xml
Upgrade jackson version to 2.13.5
To resolve CVE-2022-42004
No
Existing tests
> HIVE-27127: Upgrade jackson version to 2.13.5

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/queries/positive/col_stats.q
- iceberg/iceberg-handler/src/test/queries/positive/use_basic_stats_from_iceberg.q
- iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_mixed.q
- iceberg/iceberg-handler/src/test/results/positive/col_stats.q.out
- iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_writes.q.out
- iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_mixed.q.out
- iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_mixed.q.out
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/stats/ColStatsProcessor.java
- ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java
> HIVE-27158: Store hive columns stats in puffin files for iceberg tables

- pom.xml
Upgrading Parquet to 1.13.0
Parquet 1.12.x has issues with buffers nog being closed properly.
Compiled locally
> HIVE-27300: Upgrade Parquet to 1.13.0

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergTimeTravel.java
- parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
With this PR,   we  can use reference name for the `SYSTEM_VERSION AS OF` clause and  query history data using branch name based on specific snapshotID.  This has been implemented on spark side: https://iceberg.apache.org/docs/latest/spark-queries/#time-travel.
This is the first step that Introducing branch feat in hive which can unblock many useful features.
Next, i will implement branch DDL syntax in hive like spark syntax.
No.
UT
> HIVE-27197: Iceberg: Support Iceberg version travel by reference name

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
JIRA Link: [https://issues.apache.org/jira/browse/HIVE-27248](url)
This commit was already done in branch-3.1 using this [https://issues.apache.org/jira/browse/HIVE-24653](url) so we need to backport the same to branch-3.
> HIVE-27248: Backport of HIVE-24653: Race condition between compactor marker generation and get splits

- itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CoreBeeLineDriver.java
- ql/src/test/results/clientpositive/beeline/desc_table_formatted.q.out
- ql/src/test/results/clientpositive/beeline/escape_comments.q.out
- ql/src/test/results/clientpositive/beeline/smb_mapjoin_1.q.out
Adding ability to mask lines in output files in Beeline q-tests like in other q-tests' drivers.
To be able to mask outputs in Beeline q-tests. I encountered this need in a downstream repository and I thought it would be beneficial to add it to the upstream repository too because it may be used in the future.
No.
Passing CI tests and a manual testing that masking is working on a local dev environment.
> HIVE-27281: Add ability of masking to Beeline q-tests

- ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayIntersect.java
- ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayIntersect.java
- ql/src/test/queries/clientpositive/udf_array_intersect.q
- ql/src/test/results/clientpositive/llap/show_functions.q.out
- ql/src/test/results/clientpositive/llap/udf_array_intersect.q.out
Implement array_intersect function in Hive
No
> HIVE-27118 - implement array_intersect UDF in Hive

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreTimeout.java
> Revert "HIVE-27330: Compaction entry dequeue order"

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/handler/CompactionCleaner.java
Addendum: Fix missing min clause for open txn id
Min clause was missing which can cause problems
No
Existing tests
> HIVE-27019: Addendum: Fix missing min clause for open txn id

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_stats.q
- iceberg/iceberg-handler/src/test/results/positive/iceberg_stats.q.out
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/StatsOptimizer.java
Do not rely on iceberg summary information in case of deletes
Iceberg summary stats could be off in case of concurrent deletes: 
https://github.com/apache/iceberg/blob/477da36e3fd5be7f96903010557ddf5ebfad7c6d/api/src/main/java/org/apache/iceberg/RowDelta.java#L132-L133
No
iceberg_stats.q
> HIVE-27347: Addendum: count(*) should be using Iceberg stats only if there are no deletes

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
- iceberg/iceberg-handler/src/test/queries/positive/alter_table_to_iceberg.q
- iceberg/iceberg-handler/src/test/results/positive/alter_table_to_iceberg.q.out
DataFiles.Builder.withPartitionPath() used in TableMigrationUtil.listPartitions may lead to issues when supplied partition column value contain special characters ("/").
BigFix
No
alter_table_to_iceberg.q
> HIVE-27367: Iceberg: Encode partition key values to avoid unnecessary partition keys split in DataFiles.fillFromPath

- Jenkinsfile
- dev-support/nightly
- hcatalog/core/pom.xml
- hcatalog/webhcat/java-client/pom.xml
- hcatalog/webhcat/svr/pom.xml
- llap-server/pom.xml
- metastore/pom.xml
- pom.xml
- ql/pom.xml
- service/pom.xml
- standalone-metastore/pom.xml
- storage-api/pom.xml
- upgrade-acid/pom.xml
Similar to [HIVE-25715](https://issues.apache.org/jira/browse/HIVE-25715) along with [HIVE-26849](https://issues.apache.org/jira/browse/HIVE-26849) but we want this to happen for branch 3 as well.
> Hive-27371: Create nightly builds on branch-3

- ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHive.java
- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-27219
This issue was already a part of [Hive-3](https://issues.apache.org/jira/browse/HIVE-3.1.3) so it should be cherry picked to branch-3
> HIVE-27219: Backport of HIVE-25616: Hive-24741 backport to 3.1

- pom.xml
- ql/src/java/org/apache/hadoop/hive/ql/io/arrow/Serializer.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-27381
> HIVE-27381 : Upgrade Arrow to 7.0.0

- pom.xml
- ql/src/java/org/apache/hadoop/hive/ql/io/arrow/Serializer.java
> Revert "HIVE-27381 : Upgrade Arrow to 7.0.0"

- iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_avro.q.out
- iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_orc.q.out
- iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_parquet.q.out
- iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_unpartitioned_parquet.q.out
- iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_avro.q.out
- iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_orc.q.out
- iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_parquet.q.out
- iceberg/iceberg-handler/src/test/results/positive/update_iceberg_unpartitioned_parquet.q.out
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/DynamicPartitionPruningOptimization.java
I missed a fix when refining HIVE-19335 to enable EXTERNAL iceberg table use stats.  This was found when i rerun dynamic_semijoin_reduction.q in which i transform iceberg type to EXTERNAL, but actually the execution plan should not be changed. Please see https://github.com/apache/hive/pull/4341/files#diff-3abb3774d1aa95235ca6c87cae91452ab59ddce60b6270eb46c038a19d12d88a
NO
> HIVE-27409: Iceberg: table with EXTERNAL type can not use statistics to optimize the query - ADDENDUM

- iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
- iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read_orc.q
- iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read_parquet.q
- iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read_orc.q.out
- iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read_parquet.q.out
move the column names to lowercase 
Can't alter the table schema if partition spec contains some columns not in the lower registry
No
q tests
> HIVE-27436: Iceberg: Alter table schema fails when partition spec contains columns not in the lower registry

- service/pom.xml
- standalone-metastore/pom.xml
> HIVE-27425:Upgrade Nimbus-JOSE-JWT to 9.31 due to CVEs

- hplsql/src/main/java/org/apache/hive/hplsql/Exec.java
- hplsql/src/main/java/org/apache/hive/hplsql/HplValidationException.java
- hplsql/src/main/java/org/apache/hive/hplsql/udf/Udf.java
- hplsql/src/test/java/org/apache/hive/hplsql/udf/TestHplsqlUdf.java
- itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
Move loadSource method out of Udf to Exec. Now hplsql() function will have stored procedure as the last argument.
This removes HMS dependency from Udf as stored procedure is now an argument to the hplsql function
No
Unit tests
> HIVE-27349: Move HMS call to get stored procedure out of Udf

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/FixedBucketPruningOptimizer.java
- ql/src/test/queries/clientpositive/tez_fixed_bucket_pruning.q
- ql/src/test/results/clientpositive/llap/tez_fixed_bucket_pruning.q.out
JIRA link : https://issues.apache.org/jira/browse/HIVE-27251
> HIVE-27251 : Backport of HIVE-22121 to branch-3

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_load_data.q
- iceberg/iceberg-handler/src/test/results/positive/iceberg_load_data.q.out
- ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/LoadSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/plan/LoadTableDesc.java
Use Append API for unpartitioned Iceberg Tables for LOAD
Using Append API, prevents
NO
UT
> HIVE-27244: Iceberg: Implement LOAD data for unpartitioned table via Append API.

- ql/src/java/org/apache/hadoop/hive/ql/io/orc/RecordReaderImpl.java
Add a null check in RecordReaderImpl.close().
Current implementation can throw NPE because the constructor of its super class may call this.close(), which mutates the uninitialized field 'batch'.
No
I tested this patch in my local environment.
> HIVE-27344: Add a null check in RecordReaderImpl.close()

- metastore/src/java/org/apache/hadoop/hive/metastore/ObjectStore.java
Set auth privileges should respect getauth.
Recover tests `org.apache.hadoop.hive.metastore.TestHiveMetaStore.testPartition`
No.
Pass `org.apache.hadoop.hive.metastore.TestHiveMetaStore.testPartition`
> HIVE-25616: [FOLLOWUP] Set auth privileges should respect getauth

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergExpireSnapshots.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableExecuteSpec.java
Allow expiring snapshots using snapshot Ids
Better Usability
Allows expiring snapshots via snapshot id
No
UT
> HIVE-27454: Iceberg: Allow expire snapshots by id.

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/Catalogs.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergTagOperation.java
- iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_tag.q
- iceberg/iceberg-handler/src/test/results/negative/write_iceberg_branch_negative.q.out
- iceberg/iceberg-handler/src/test/results/positive/query_iceberg_tag.q.out
- iceberg/iceberg-handler/src/test/results/positive/write_iceberg_branch.q.out
- ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
- ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTBuilder.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/ppr/PartitionPruner.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/plan/TableScanDesc.java
- storage-api/src/java/org/apache/hadoop/hive/common/TableName.java
Support query iceberg tag like this: 
`select * from db.tbl.tag_tagName;`
In addition, Iceberg tag can not be written data and we should throw exception in compile stage if users want to write data to iceberg tag. 
No
No
`mvn test -Dtest.output.overwrite -Dtest=TestIcebergCliDriver -Dqfile=query_iceberg_tag.q -pl itests/qtest-iceberg -Piceberg -Pitests -Drat.skip`
> HIVE-27503: Support query iceberg tag

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergTimestampWithZoneObjectInspectorHive3.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerTimezone.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/serde/objectinspector/TestIcebergTimestampWithZoneObjectInspectorHive3.java
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_timestamp_with_local_time_zone.q
- iceberg/iceberg-handler/src/test/results/positive/iceberg_timestamp_with_local_time_zone.q.out
Fetch task returns wrong results for Timestamp with local time zone datatype for Iceberg tables
Returns incorrect results
No
No
Qtest, Unit test
> HIVE-27513: Iceberg: Fetch task returns wrong results for Timestamp with local time zone datatype for Iceberg tables

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/PartitionUtil.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/TestGetPartitionInBatches.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/TestMsckCreatePartitionsInBatches.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/TestMsckDropPartitionsInBatches.java
- ql/src/test/results/clientpositive/llap/temp_table_add_part_multiple.q.out
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Added batching and retry mechanism while fetching `List<Partitions>` in Hive.getAllPartitionsOf.
Hive.getAllPartitionsOf fetches all the partitions in one HMS call. In case of wide table(>1500 columns), the total size of `List<Partition>` object in case would exceed 2GB for small number of partitions and would fail at thrift side. By implementing batching the size of the thrift object can be reduced.
No
No
Added test cases as well as tested it locally
> HIVE-27505: Added batching with retry mechanism in Hive.getAllPartitionsOf call.

- ql/src/test/results/clientpositive/orc_merge10.q.out
> HIVE-27540 : Fixed orc_merge10.q test

- beeline/src/java/org/apache/hive/beeline/Commands.java
- common/src/java/org/apache/hadoop/hive/common/JavaUtils.java
- llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/FunctionLocalizer.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/AddToClassPathAction.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/SerializationUtilities.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ExecDriver.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ExecMapper.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/mr/ExecReducer.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/spark/SparkRecordHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/RecordProcessor.java
- ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/TestAddToClassPathAction.java
- spark-client/src/main/java/org/apache/hive/spark/client/SparkClientUtilities.java
- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
> HIVE-27508 : Backport of HIVE-21584 to branch-3

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/KillMoveTriggerActionHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/WmTezSession.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/WorkloadManager.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestWorkloadManager.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-27538
Original issue link : https://issues.apache.org/jira/browse/HIVE-24201
> HIVE-26751 : Backport of HIVE-24201 to branch-3

- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnUtils.java
- standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/txn/TestTxnUtils.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-27542
> HIVE-27542: Backport HIVE-25659 to branch-3

- common/src/java/org/apache/hadoop/hive/common/FileUtils.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-27545
> HIVE-27545: Backport of HIVE-22273 to branch-3

- llap-server/src/java/org/apache/hadoop/hive/llap/cli/LlapStatusServiceDriver.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-27547
> HIVE-27547 : Backport of HIVE-22219 to branch-3

- llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskRunnerCallable.java
JIRA link : https://issues.apache.org/jira/browse/HIVE-27550
> HIVE-27550 : Backport of HIVE-22113 to branch-3

- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/test/queries/clientpositive/masking_reserved.q
- ql/src/test/results/clientpositive/masking_reserved.q.out
JIRA link : https://issues.apache.org/jira/browse/HIVE-27551
> HIVE-27551 : Backport of HIVE-22208 to branch-3

- jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
- jdbc/src/java/org/apache/hive/jdbc/Utils.java
JIRA link - https://issues.apache.org/jira/browse/HIVE-27619
> HIVE-27619 : Backport of HIVE-12371: Adding a timeout connection parameter for JDBC

- itests/src/test/resources/testconfiguration.properties
- ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezUtils.java
- ql/src/test/queries/clientpositive/tez_union_udtf.q
- ql/src/test/results/clientpositive/tez/tez_union_udtf.q.out
JIRA link - https://issues.apache.org/jira/browse/HIVE-27602
> HIVE-27602 : Backport of HIVE-21915 to branch-3

- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/tools/MetastoreSchemaTool.java
- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/tools/SchemaToolCommandLine.java
- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/tools/SchemaToolTaskMergeCatalog.java
JIRA link - https://issues.apache.org/jira/browse/HIVE-27603
> HIVE-27603 : Backport of HIVE-22498 to branch-3

- ql/src/java/org/apache/hadoop/hive/ql/log/LogDivertAppender.java
JIRA link - https://issues.apache.org/jira/browse/HIVE-27609
> HIVE-27609 : Backport of HIVE-22115 to branch-3

- pom.xml
JIRA link - https://issues.apache.org/jira/browse/HIVE-27623
> HIVE-27623: Backport of HIVE-26081: Upgrade ant to 1.10.9 (Ashish Sharma, reviewed by Adesh Rao)

- storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/DateColumnVector.java
- storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/TimestampColumnVector.java
- storage-api/src/test/org/apache/hadoop/hive/ql/exec/vector/TestDateColumnVector.java
- storage-api/src/test/org/apache/hadoop/hive/ql/exec/vector/TestTimestampColumnVector.java
Backport of HIVE-22405: Add ColumnVector support for ProlepticCalendar to branch-3
Jira link - https://issues.apache.org/jira/browse/HIVE-27569
> HIVE-27569: Backport of HIVE-22405 to branch-3

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerTestUtils.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_atomic_merge_update.q
- iceberg/iceberg-handler/src/test/results/positive/iceberg_atomic_merge_update.q.out
- ql/src/java/org/apache/hadoop/hive/ql/Context.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
Iceberg: Branches of Merge/Update statements should be committed atomically
Branches of Merge/Update statements should be committed atomically
Merge and update queries call commit table twice per query as a result they create 2 snapshots. For any concurrent reads , read data from the incorrect snapshot may result in inconsistent results. 
No
No
Q file and manual test
> HIVE-27589: Iceberg: Branches of Merge/Update statements should be committed atomically

- ql/src/java/org/apache/hadoop/hive/ql/DriverUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
JIRA link - https://issues.apache.org/jira/browse/HIVE-27615
> HIVE-27615 : Backport of HIVE-21280 to branch-3

- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/mapjoin/fast/VectorMapJoinFastHashTable.java
JIRA link - https://issues.apache.org/jira/browse/HIVE-27618
> HIVE-27618 : Backport of HIVE-25446 to branch-3

- itests/src/test/resources/testconfiguration.properties
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/correlation/ReduceSinkDeDuplicationUtils.java
- ql/src/test/queries/clientpositive/dynpart_sort_optimization_distribute_by.q
- ql/src/test/results/clientpositive/dynpart_sort_optimization_distribute_by.q.out
- ql/src/test/results/clientpositive/llap/dynpart_sort_optimization_distribute_by.q.out
- ql/src/test/results/clientpositive/tez/dynpart_sort_optimization_distribute_by.q.out
JIRA link - https://issues.apache.org/jira/browse/HIVE-27617
> HIVE-27617 : Backport of HIVE-18284 to branch-3

- ql/src/java/org/apache/hadoop/hive/ql/Context.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
JIRA link - https://issues.apache.org/jira/browse/HIVE-27607
> HIVE-27607 : Backport of HIVE-21182: Skip setting up hive scratch dir during planning

- ql/src/java/org/apache/hadoop/hive/ql/io/sarg/ConvertAstToSearchArg.java
improve output close automicly
output need close automicly and some typo in comments
no
no
can be used
> HIVE-27599: ConvertAstToSearchArg improvement with output and typo in comments

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
- iceberg/iceberg-handler/src/test/queries/negative/fastforward_iceberg_branch_conflict.q
- iceberg/iceberg-handler/src/test/queries/positive/fastforward_iceberg_branch.q
- iceberg/iceberg-handler/src/test/results/negative/fastforward_iceberg_branch_conflict.q.out
- iceberg/iceberg-handler/src/test/results/positive/fastforward_iceberg_branch.q.out
- parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
- parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
- parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableExecuteSpec.java
Add support for fast forward a branch
Better usability of iceberg branches & tags
Yes, an iceberg branch can be fast forwarded
No
UT
> HIVE-27630: Iceberg: Fast forward branch.

- ql/src/java/org/apache/hadoop/hive/llap/LlapCacheAwareFs.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/encoded/EncodedReaderImpl.java
JIRA link - https://issues.apache.org/jira/browse/HIVE-27611
> HIVE-27611 : Backport of HIVE-22168 to branch-3

- shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
> HIVE-27566: Fix some yarn cluster options for tests

- ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHive.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
This PR fixes getting partitions with max_parts.
Bug fix.
No.
No.
Unit test.
> HIVE-27667: Fix get partitions with max_parts

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_insert_into_partition.q
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_insert_into_partition_transforms.q
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_insert_into_partition_with_evolution.q
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_insert_overwrite_partition.q
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_insert_overwrite_partition_transforms.q
- iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_into_partition.q.out
- iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_into_partition_transforms.q.out
- iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_into_partition_with_evolution.q.out
- iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_overwrite_partition.q.out
- iceberg/iceberg-handler/src/test/results/positive/iceberg_insert_overwrite_partition_transforms.q.out
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DummyTxnManager.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/DummyPartition.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Iceberg: Insert into/overwrite partition support
Support inserting data in the following query types -
Inserting data via static partition -
```
INSERT INTO|OVERWRITE TABLE tableName PARTITION(pCol = pColValue) VALUES (...);
INSERT INTO|OVERWRITE TABLE tableName PARTITION(pCol = pColValue) SELECT query;
```
Inserting data via dynamic partitioning - 
```
INSERT INTO|OVERWRITE TABLE tableName PARTITION(pCol) VALUES (...); 
INSERT INTO|OVERWRITE TABLE tableName PARTITION(pCol) SELECT query; 
```
Inserting data via static and dynamic partitioning with static partitioning coming at the beginning - 
```
INSERT INTO|OVERWRITE TABLE tableName PARTITION(pCol1 = pColValue, pCol2) VALUES (...); 
INSERT INTO|OVERWRITE TABLE tableName PARTITION(pCol1 = pColValue, pCol2) SELECT query;
```
No
No
QTests
> HIVE-27627: Iceberg: Insert into/overwrite partition support

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergCherryPick.java
- parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
- parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableExecuteSpec.java
Allow cherry-pick operation
To enable cherry-pick for iceberg tables
They can cherry-pick a commit
No
UT
> HIVE-27654: Iceberg: Cherry-Pick commit to a branch.

- llap-ext-client/src/java/org/apache/hadoop/hive/llap/LlapBaseInputFormat.java
> HIVE-27668 : Backport of HIVE-21126 to branch-3

- packaging/src/docker/README.md
- packaging/src/docker/build.sh
- packaging/src/docker/entrypoint.sh
Introduce an env variable SCHEMA_COMMAND for Hive 3, usage:
docker run -d -p 10000:10000 -p 10002:10002 --env SERVICE_NAME=hiveserver2 --env SCHEMA_COMMAND= upgradeSchema  --name hive3 apache/hive:3.1.3
No
Build the image and run the container successfully on my M1 laptop.
> HIVE-27670: Failed to build the image locally on Apple silicon

- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/CodahaleMetrics.java
- standalone-metastore/metastore-common/src/test/java/org/apache/hadoop/hive/common/metrics/metrics2/TestCodahaleReportersConf.java
https://issues.apache.org/jira/browse/HIVE-17350
This is a bug fix
Few Metrics parameters are not populating with the values
No
No
Unit test
> HIVE-17350: metrics errors when retrying HS2 startup

- pom.xml
Jansi 2.4.0 adds support for:
Mac-arm64 target
linux armv6 platform 
aarch64 
https://github.com/fusesource/jansi/blob/master/changelog.md
> HIVE-27656: Upgrade jansi.version to 2.4.0

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/security/ZooKeeperTokenStore.java
Add log for ZooKeeperTokenStore
Trace the lifecycle of tokenPath in zookeeper
No
No
Only log changed, no test added.
> HIVE-27564 : Add log for ZooKeeperTokenStore to trace the lifecycle of tokenPath

- common/src/test/org/apache/hadoop/hive/common/metrics/metrics2/TestCodahaleMetrics.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java
- ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHive.java
- ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveRemote.java
- service/src/test/org/apache/hive/service/cli/session/TestSessionManagerMetrics.java
- standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
- standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/MetaStoreTestUtils.java
- standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/TestMarkPartition.java
- standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/client/MetaStoreClientTest.java
> HIVE-27721 : Backport of HIVE-23396: Many fixes and improvements to stabilize tests to branch-3

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergBranchExec.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergBranchOperation.java
> HIVE-27711: Iceberg: Allow creating a branch from tag name - ADDENDUM

- hcatalog/pom.xml
- itests/hive-unit/pom.xml
- itests/qtest-spark/pom.xml
- kryo-registrator/pom.xml
- pom.xml
- ql/pom.xml
- service/pom.xml
- spark-client/pom.xml
JIRA link - HIVE-27722
Added org.bouncycastle as dependency and excluded the dependencies of the same which lead to version mismatch while running tests
> HIVE-27722 : Added org.bouncycastle as dependency to branch-3

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergTruncateTable.java
- iceberg/iceberg-handler/src/test/queries/negative/truncate_iceberg_table_with_partition_spec.q
- iceberg/iceberg-handler/src/test/queries/negative/truncate_table_partition_spec_with_part_evolution.q
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_truncate_partition.q
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_truncate_partition_with_evolution.q
- iceberg/iceberg-handler/src/test/results/negative/truncate_iceberg_table_with_partition_spec.q.out
- iceberg/iceberg-handler/src/test/results/negative/truncate_table_partition_spec_with_part_evolution.q.out
- iceberg/iceberg-handler/src/test/results/positive/iceberg_truncate_partition.q.out
- iceberg/iceberg-handler/src/test/results/positive/iceberg_truncate_partition_with_evolution.q.out
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/truncate/TruncateTableAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/AcidExportSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SplitUpdateSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/TransformSpec.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
- serde/src/java/org/apache/hadoop/hive/serde2/typeinfo/TypeInfoUtils.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Iceberg: Truncate partition support
To support Truncate partition on Iceberg tables.
There are some changes to the inputs, please refer the Jira itself.
No
Qtests
> HIVE-27672: Iceberg: Truncate partition support

- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/handler/CompactionCleaner.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/handler/TaskHandler.java
- ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCleaner.java
- storage-api/src/java/org/apache/hadoop/hive/common/ValidCleanerWriteIdList.java
- storage-api/src/java/org/apache/hadoop/hive/common/ValidCompactorWriteIdList.java
- storage-api/src/java/org/apache/hadoop/hive/common/ValidReaderWriteIdList.java
Cleaner should honor compaction writeIdHwm. Introduced ValidCleanerWriteIdList
Cleaner check remaining logic was inaccurate
No
No
UT
> HIVE-27526: Cleaner should honor compaction writeIdHwm

- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandler.java
- itests/hive-unit-hadoop2/pom.xml
- itests/hive-unit/pom.xml
- itests/qtest-iceberg/pom.xml
- itests/qtest/pom.xml
- pom.xml
- serde/pom.xml
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/security/TestTokenStoreDelegationTokenSecretManager.java
- standalone-metastore/pom.xml
- storage-api/pom.xml
Upgrade Hadoop
Better usablility
Nopes
Jenkins
> HIVE-27757: Upgrade hadoop to 3.3.6.

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergExpireSnapshots.java
- parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableExecuteSpec.java
Allow expiring snapshot based on time range
Better Usability
Yes, Snapshots can be expired by time range.
No
UT
> HIVE-27771: Iceberg: Allow expire snapshot by time range.

- data/conf/iceberg/llap/tez-site.xml
- data/conf/iceberg/tez/tez-site.xml
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/FilesForCommit.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergCopyOnWriteRecordWriter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergRecordWriter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterBuilder.java
- iceberg/iceberg-handler/src/test/queries/positive/delete_iceberg_copy_on_write_partitioned.q
- iceberg/iceberg-handler/src/test/queries/positive/delete_iceberg_copy_on_write_unpartitioned.q
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_copy_on_write.q
- iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_copy_on_write_partitioned.q.out
- iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_copy_on_write_unpartitioned.q.out
- iceberg/iceberg-handler/src/test/results/positive/dynamic_semijoin_reduction.q.out
- iceberg/iceberg-handler/src/test/results/positive/iceberg_copy_on_write.q.out
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/lineage/ExprProcFactory.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
````
WITH t AS (
select `PARTITION__SPEC__ID`,`PARTITION__HASH`,`FILE__PATH`,-1,`id` from (
select `PARTITION__SPEC__ID`,`PARTITION__HASH`,`FILE__PATH`,-1,`id`, row_number() OVER (partition by `FILE__PATH`) rn from `default`.`ice01`
where id>2
) q
where rn=1
)
insert into table `default`.`ice01` select `PARTITION__SPEC__ID` AS `__d__PARTITION__SPEC__ID`,`PARTITION__HASH` AS `__d__PARTITION__HASH`,`FILE__PATH` AS `__d__FILE__PATH`,`ROW__POSITION` AS `__d__ROW__POSITION`,`id` AS `__d__id` from `default`.`ice01`
where NOT (id>2)
AND `FILE__PATH` IN ( select `FILE__PATH` from t )
union all
-- referenced data files to exclude from the new snapshot
select * from t
````
Doesn't rewrite all the data files
No
No
mvn test -Dtest=TestIcebergLlapLocalCliDriver -Dqfile=iceberg_v2_deletes.q
> HIVE-27031: Addendum: Iceberg: Implement Copy-On-Write for Delete Queries

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSetCurrentSnapshot.java
- parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableExecuteSpec.java
HIVE-26927 has implemented setting current snapshotId with a existing snapshotId, and we can continue to extend this to set curren snapshotId with the table's SnapshotRef(branch or tag).
https://iceberg.apache.org/docs/latest/spark-procedures/#set_current_snapshot
Spark supports setting current snapshotId using snapshotId or snapshotRef. We can refer to this to implement setting current snapshotId with SnapshotRef(branch or tag).
No
No
UT
> HIVE-27793: Iceberg: Support setting current snapshot with SnapshotRef

- common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterBuilder.java
- iceberg/iceberg-handler/src/test/queries/positive/update_iceberg_copy_on_write_partitioned.q
- iceberg/iceberg-handler/src/test/queries/positive/update_iceberg_copy_on_write_unpartitioned.q
- iceberg/iceberg-handler/src/test/results/positive/update_iceberg_copy_on_write_partitioned.q.out
- iceberg/iceberg-handler/src/test/results/positive/update_iceberg_copy_on_write_unpartitioned.q.out
- iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_parquet.q.out
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SplitUpdateSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
COW support for update operation
part of COW support
No
No
mvn clean test -Dtest=TestIcebergCliDriver -Dqfile=update_iceberg_copy_on_write_partitioned.q
mvn clean test -Dtest=TestIcebergCliDriver -Dqfile=update_iceberg_copy_on_write_unpartitioned.q
depends on #4700
> HIVE-27783: Iceberg: Implement Copy-On-Write for Update queries

- bin/ext/beeline.sh
- bin/hive
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcrossInstances.java
- itests/src/test/resources/testconfiguration.properties
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWork.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/incremental/IncrementalLoadEventsIterator.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/repl/incremental/IncrementalLoadTasksBuilder.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/plan/MapJoinDesc.java
- ql/src/java/org/apache/hadoop/hive/ql/plan/VectorMapJoinDesc.java
- ql/src/test/queries/clientpositive/vector_mapjoin_complex_values.q
- ql/src/test/results/clientpositive/llap/vector_mapjoin_complex_values.q.out
JIRA link - https://issues.apache.org/jira/browse/HIVE-27807
Backports - HIVE-20629, HIVE-20705, HIVE-20734
> HIVE-27807 : Backport of HIVE-20629, HIVE-20705, HIVE-20734

- pom.xml
Upgrade parquet to 1.13.1.  Apache Iceberg also uses this latest parquet version.
No
Yes, Dependency tree attached in the jira
Compiled locally
> HIVE-27826: Upgrade to Parquet 1.13.1

- ql/src/java/org/apache/hadoop/hive/ql/udf/ptf/WindowingTableFunction.java
- ql/src/test/queries/clientpositive/windowing.q
- ql/src/test/results/clientpositive/llap/windowing.q.out
- ql/src/test/results/clientpositive/spark/windowing.q.out
Backport of HIVE-21104
JIRA URL : https://issues.apache.org/jira/browse/HIVE-27708
> HIVE-27708: Backport of HIVE-21104: PTF with nested structure throws ClassCastException

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_drop_partition.q
- iceberg/iceberg-handler/src/test/results/positive/iceberg_drop_partition.q.out
- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Iceberg: Drop partition support
To implement Drop partition for Iceberg
No
No
QTests
> HIVE-27779: Iceberg: Drop partition support

- pom.xml
Update the CycloneDX Maven plugin for SBOM generation to 2.7.10
> HIVE-27864 Update plugin for SBOM generation to 2.7.10

- ql/src/java/org/apache/hadoop/hive/ql/exec/DDLPlanUtils.java
- ql/src/test/results/clientpositive/llap/show_create_table.q.out
Currently SHOW CREATE TABLE and EXPLAIN DDL outputs are incorrect when a table has a FK constraint on a composite key. An example is shown in the Jira: https://issues.apache.org/jira/browse/HIVE-27533
Multiple ALTER TABLE statements are printed for each column in the constraint, which is a bug.
FOREIGN KEY constraints will print correctly now.
No
`mvn test -Dtest=TestMiniLlapLocalCliDriver -Dtest.output.overwrite=true -Dqfile=show_create_table.q`
> HIVE-27533: Incorrect FOREIGN KEY constraints in SHOW CREATE TABLE

- standalone-metastore/metastore-server/src/main/resources/package.jdo
> HIVE-27862: Map propertyContent to a wrong column in package.jdo

- hplsql/src/main/java/org/apache/hive/hplsql/Exec.java
- hplsql/src/main/java/org/apache/hive/hplsql/Stmt.java
- hplsql/src/test/queries/offline/update.sql
- hplsql/src/test/results/offline/update.out.txt
While parsing the update statement currently it just parsing entire SQL as string so the variables used in update statement are not getting replaced. Now we are parsing each part of the UPDATE query like assignments, where clause, etc.. so that the variables will get replaced with actual values.
To fix [HIVE-27491](https://issues.apache.org/jira/browse/HIVE-27491) issue.
No
No
Unit tests are added.
> HIVE-27491: HPL/SQL does not allow variables in update statements

- beeline/src/java/org/apache/hive/beeline/BeeLine.java
- beeline/src/java/org/apache/hive/beeline/BeeLineOpts.java
- beeline/src/main/resources/BeeLine.properties
- jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
- jdbc/src/java/org/apache/hive/jdbc/Utils.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/TezCompiler.java
- service/src/java/org/apache/hive/service/auth/ldap/HttpEmptyAuthenticationException.java
- service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java
JIRA link - https://issues.apache.org/jira/browse/HIVE-27888
Backport of HIVE-22429, HIVE-14898, HIVE-22231, HIVE-20507, HIVE-24786 to branch-3
> HIVE-27888: Backport of HIVE-22429, HIVE-14898, HIVE-22231, HIVE-20507, HIVE-24786 to branch-3

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java
Waits for the Jetty server to die.
Threads in the jetty pool are all daemon threads, such pool does not prevent the JVM from exiting when the main thread finishes his job.
No
No
Manually test on my laptop.
> HIVE-27865: HMS in http mode shuts down silently with no errors

- common/src/java/org/apache/hadoop/hive/conf/Constants.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/queries/positive/ctlt_iceberg.q
- iceberg/iceberg-handler/src/test/results/positive/ctlt_iceberg.q.out
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/io/PartitionSerializer.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetastoreDefaultTransformer.java
Fixes 'TRANSLATED_TO_EXTERNAL' table property
Bugfix
No
No
q test
> HIVE-26950: Iceberg: Addendum: CTLT sets incorrect 'TRANSLATED_TO_EXTERNAL' table property

- ql/src/java/org/apache/hadoop/hive/ql/parse/ImportSemanticAnalyzer.java
Remove common-lang usage, replaced with commons-lang3
Though there is a rule to band import, but the does not cover the full class name usage.
```
<restrictImports implementation="de.skuzzle.enforcer.restrictimports.RestrictImports">
<reason>Do not use commons-lang</reason>
<bannedImports>
<bannedImport>org.apache.commons.lang.**</bannedImport>
</bannedImports>
<includeTestCode>true</includeTestCode>
</restrictImports>
```
No
No
Pass CI
> HIVE-27896: Remove common-lang usage

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergDeleteOrphanFiles.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/actions/HiveIcebergDeleteOrphanFiles.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergExpireSnapshots.java
- parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
- parser/src/java/org/apache/hadoop/hive/ql/parse/HiveLexerParent.g
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/execute/AlterTableExecuteAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableExecuteSpec.java
Implement delete orphan files
To clean orphan files.
adds a delete orphan files query for iceberg tables
No.
UT
> HIVE-27906: Iceberg: Implement Delete Orphan Files.

- Jenkinsfile
http://ci.hive.apache.org/job/hive-nightly/
[HIVE-25715](https://issues.apache.org/jira/browse/HIVE-25715) added nightly builds, and it give users a chance to test the snapshot binary package.
But the builds didn't contain Iceberg module, It would be good to include Iceberg module. And then user like [HIVE-27898](https://issues.apache.org/jira/browse/HIVE-27898) can use the snapshot binary package to test some queries.
No
No
No need test.
> HIVE-27912: Include Iceberg module in nightly builds

- ql/src/java/org/apache/hadoop/hive/ql/exec/ExplainTask.java
PR for below patch
https://issues.apache.org/jira/secure/attachment/13057249/HIVE-27240.patch
To Fix NPE
No
Is the change a dependency upgrade?
No
NA
> HIVE-27240: NPE on Hive Hook Proto Log Writer.

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
This patch changes the default value of `hive.optimize.cte.materialize.threshold` to -1. (Original value was 3.)
According to HIVE-24167, Hive fails to compile some queries when CTE materialization is enabled. 
No
No
I didn't add any test as this patch does not introduce any new feature.
> HIVE-27856: Disable CTE materialization by default

- ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
- ql/src/test/queries/clientpositive/insert_and_load_overwrite_drop_partition.q
- ql/src/test/results/clientpositive/llap/insert_and_load_overwrite_drop_partition.q.out
This PR adds an additional check for cleaning up the destination directory while executing an INSERT/LOAD OVERWRITE TABLE statement for those partitions which do not exist in the metastore.
For the partitions not in metastore but contain some files in the filesystem, INSERT OVERWRITE TABLE with partition does not clean the directory before overwriting.
No
No
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=insert_and_load_overwrite_drop_partition.q
> HIVE-27930: Insert/Load overwrite table partition does not clean up directory before overwriting

- README.md
https://github.com/apache/hive/commit/4c7dbd560f9034fbce77d17a82bd0a4abc3091fd#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
HIVE-26134 has removed spark execution, there are only 2 execution frameworks left, MR&Tez.
No
No
No need test.
> HIVE-27934: Fix incorrect description about the execution framework in README.md

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- ql/src/test/queries/clientpositive/groupby_sort_2_23.q
- ql/src/test/results/clientpositive/cbo_rp_auto_join1.q.out
- ql/src/test/results/clientpositive/llap/auto_sortmerge_join_10.q.out
- ql/src/test/results/clientpositive/llap/bucket_groupby.q.out
- ql/src/test/results/clientpositive/llap/groupby_sort_2_23.q.out
Disable `hive.map.groupby.sorted` optimization.
The optimization leads to data correctness issues. See jira https://issues.apache.org/jira/browse/HIVE-27876 for details
> HIVE-27876 Incorrect query results on tables with ClusterBy & SortBy

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergFilterFactory.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergFilterFactory.java
BugFix
Runtime predicate pushdown doesn't work after HIVE-27273
No
No
On a cluster with 1Tb dataset
> HIVE-27962: Iceberg: Runtime predicate pushdown doesn't work

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
direct sql should  bail early if no functions. Avoid querying empty partition fields.
No
No
Manually test.
> HIVE-27780: Implement direct SQL for get_all_functions - ADDENDUM

- packaging/src/docker/README.md
- packaging/src/docker/entrypoint.sh
Add option to enable verbose logging for schematool and metastore service inside docker container
Improved logging
Add option to enable verbose logging
No
Local docker build and run for the mentioned services
> HIVE-27969: Add verbose logging for schema initialisation and metastore service in docker container

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetastoreDefaultTransformer.java
Fix wrong db name in exception.
No
No
> HIVE-27989: Wrong database name in MetaException from MetastoreDefaultTransformer.java

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/jdbc/commands/RemoveDuplicateCompleteTxnComponentsCommand.java
SQL query runtime improvement
Performance optimization
No
No
mvn test -Dtest=ITestDbTxnManager#testRemoveDuplicateCompletedTxnComponents -Dtest.metastore.db=mysql;
mvn test -Dtest=ITestDbTxnManager#testRemoveDuplicateCompletedTxnComponents -Dtest.metastore.db=postgres;
mvn test -Dtest=ITestDbTxnManager#testRemoveDuplicateCompletedTxnComponents -Dtest.metastore.db=oracle;
> HIVE-27406: Addendum: Query runtime optimization

- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/TezJobMonitor.java
Please check HIVE-21520. This PR is based on @rbalamohan 's patch and this try to fix incorrect display time(Compile Query & Prepare Plan & Submit Plan) in Beeline console.
**Before this PR:**
INFO  : Query Execution Summary
INFO  : ----------------------------------------------------------------------------------------------
INFO  : OPERATION                            DURATION
INFO  : ----------------------------------------------------------------------------------------------
INFO  : Compile Query                           0.00s
INFO  : Prepare Plan                            0.00s
INFO  : Get Query Coordinator (AM)              0.00s
INFO  : Submit Plan                         1704899467.78s
INFO  : Start DAG                               0.05s
INFO  : Run DAG …
> HIVE-21520: Query 'Submit plan' time reported is incorrect

- hplsql/src/main/java/org/apache/hive/hplsql/Stmt.java
- itests/hive-unit/pom.xml
- itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
If either table name or table alias is used in column name in the loops then selecting only column name to retrieve the data from cursor by assuming _<table/alias_name>.<column_name>_ is the pattern.
To fix the issue HIVE-27489.
No
No
Using Unit test code.
_mvn test -Dtest=TestHplSqlViaBeeLine#testTableAliasInColumnName -pl itests/hive-unit -Pitests_
> HIVE-27489: HPL/SQL does not support table aliases on column names in loops.

- llap-common/src/gen/protobuf/gen-java/org/apache/hadoop/hive/llap/daemon/rpc/LlapDaemonProtocolProtos.java
- llap-common/src/gen/protobuf/gen-java/org/apache/hadoop/hive/llap/plugin/rpc/LlapPluginProtocolProtos.java
- ql/src/gen/protobuf/gen-java/org/apache/hadoop/hive/ql/hooks/proto/HiveHookEvents.java
- ql/src/gen/protobuf/gen-test/org/apache/hadoop/hive/ql/io/protobuf/SampleProtos.java
Add the generated protobuf code
Since protobuf is already upgraded
Should be NO, Protobuf is compatible over the wire
It is a by product of a dependency upgrade
Jenkins Run
> HIVE-28017: Add generated protobuf code.

- pom.xml
- ql/pom.xml
- standalone-metastore/pom.xml
Make all springframework dependencies in sync
Iceberg Major Compaction is failing.
Yes, Iceberg Major compaction will work 
Yes
Locally
> HIVE-28052: Iceberg: Major QB Compaction fails with ClassNotFoundException: org.springframework.core.ErrorCoded

- ql/src/java/org/apache/hadoop/hive/ql/parse/type/RexNodeExprFactory.java
- ql/src/test/queries/clientpositive/subquery_join.q
- ql/src/test/results/clientpositive/llap/subquery_join.q.out
Cleaned up `getPosition` method in `RexNodeExprFactory`
`getPosition` method didn't return the position of a column as soon as it found it in one of the RowResolvers. It threw an Exception if it encountered the column again in `outerRR`. Now it returns early.
No
No
`mvn test -Dtest=TestMiniLlapLocalCliDriver -Dtest.output.overwrite=true -Dqfile=subquery_join.q`
> HIVE-28054: SemanticException for join condition in subquery

- pom.xml
- service/pom.xml
Upgrade Bouncy Castle to 1.77
Bouncy Castle for java before 1.68(excluding) is found with a potential LDAP injection:
https://nvd.nist.gov/vuln/detail/CVE-2023-33201
No
Yes
[bcprovTree.txt](https://github.com/apache/hive/files/14256600/bcprovTree.txt)
Manually
> HIVE-28065: Upgrade Bouncy castle to bcprov-jdk18on 1.77

- pom.xml
> HIVE-28056: Bump com.jayway.jsonpath:json-path from 2.8.0 to 2.9.0

- kafka-handler/src/test/org/apache/hadoop/hive/kafka/KafkaStorageHandlerInfoTest.java
Added a new unit test for KafkaStorageHandlerInfo
To improve the testing of kafka storage handler and the coverage
No
No
Unit test.
> HIVE-27556: Add Unit Test for KafkaStorageHandlerInfo

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
correct desc of `hive.metastore.disallow.incompatible.col.type.changes`,  In fact the default value is true.
no
no need test
> HIVE-28090: Correct desc of `hive.metastore.disallow.incompatible.col.type.changes` of `HiveConf.java`

- iceberg/iceberg-handler/src/test/queries/positive/merge_iceberg_copy_on_write_unpartitioned.q
- iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_unpartitioned.q.out
- ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/CopyOnWriteMergeRewriter.java
Fix the subquery union sql 
BugFix
No
No
mvn test -Dtest=TestIcebergLlapLocalCliDriver -Dqfile=merge_iceberg_cow.q -Drat.skip=true -Dtest.output.overwrite=true
> HIVE-28084: Iceberg: COW fix for Merge operation

- core/src/test/java/org/apache/hive/hcatalog/DerbyPolicy.java
- hcatalog/core/src/test/java/org/apache/hive/hcatalog/DerbyPolicy.java
- hcatalog/core/src/test/java/org/apache/hive/hcatalog/cli/TestPermsGrp.java
- hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatPartitionPublish.java
- hcatalog/core/src/test/java/org/apache/hive/hcatalog/package-info.java
- hcatalog/webhcat/java-client/src/test/java/org/apache/hive/hcatalog/api/TestHCatClient.java
- metastore/src/test/org/apache/hadoop/hive/metastore/TestHiveMetaStoreGetMetaConf.java
- metastore/src/test/org/apache/hadoop/hive/metastore/TestHiveMetaStorePartitionSpecs.java
Backport HIVE-18586 to branch-2.3
To recover Derby testing issue.
No
No.
CI
> HIVE-18586: (2.3) Upgrade Derby to 10.14.1.0

- iceberg/iceberg-handler/src/test/queries/positive/merge_iceberg_copy_on_write_partitioned.q
- iceberg/iceberg-handler/src/test/queries/positive/merge_iceberg_copy_on_write_unpartitioned.q
- iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_partitioned.q.out
- iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_unpartitioned.q.out
- ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/CopyOnWriteMergeRewriter.java
Syntax improvement for the Merge query with insert clause
Usability
No
No
mvn test -Dtest=TestIcebergCliDriver -Dqfile=merge_iceberg_copy_on_write_partitioned.q,merge_iceberg_copy_on_write_unpartitioned.q
> HIVE-28119: Iceberg: Allow insert clause with a column list in Merge query not_matched condition

- ql/src/java/org/apache/hadoop/hive/ql/exec/SecureCmdDoAs.java
> HIVE-28134: Improve SecureCmdDoAs.

- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/TezJobMonitor.java
Print filesystem summary in beeline.
For better debuggability.
Yes, improved file system usage stats in beeline.
No.
Tested on cluster with tez container mode.
Without patch:
```
INFO  : Query Execution Summary
INFO  : ----------------------------------------------------------------------------------------------
INFO  : OPERATION                            DURATION
INFO  : ----------------------------------------------------------------------------------------------
INFO  : Compile Query                           8.51s
INFO  : Prepare Plan                            0.61s
INFO  : Get Query Coordinator (AM)              0.17s
INFO  : Submit Plan                             0.42s
INFO  : Start DAG                               0.59s
INFO  : Run DAG                                 7.34s
INFO …
```
> HIVE-28111: FSCountersSummary is only printed when LLAP IO is enabled

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergMergeTaskProperties.java
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_merge_files.q
- iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_merge_files.q.out
- itests/src/test/resources/testconfiguration.properties
- ql/src/java/org/apache/hadoop/hive/ql/io/CombineHiveInputFormat.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/plan/ConditionalResolverMergeFiles.java
- ql/src/java/org/apache/hadoop/hive/ql/plan/MergeTaskProperties.java
HIVE-28069: Iceberg: Implement Merge task functionality for Iceberg tables
To minimise the number of small files.
No
No
QTest
> HIVE-28069: Iceberg: Implement Merge task functionality for Iceberg tables

- NOTICE
- storage-api/NOTICE
Backport HIVE-27467 to 2.3, I also update the copyright years in NOTICE.
https://github.com/apache/spark/pull/45372#issuecomment-1977151289
No
No
Review
> HIVE-27467. (2.3) NOTICE files use incorrect wording "developed by" instead of "developed at"

- llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/PriorityBlockingDeque.java
- pom.xml
Backport HIVE-27468 to 2.3
https://github.com/apache/spark/pull/45372#issuecomment-1977151289
No.
No.
Review
> HIVE-27468: (2.3) Restore original license in PriorityBlockingDeque

- LICENSE
- binary-package-licenses/com.google.re2j-LICENSE
Backport HIVE-27478 to 2.3
https://github.com/apache/spark/pull/45372#issuecomment-1977151289
No.
No.
Review
> HIVE-27478: (2.3) Remove re2j, SQLLine, ClassNameCompleter entries from LICENSE file

- pom.xml
- standalone-metastore/pom.xml
https://datasketches.apache.org/docs/Community/Downloads.html shows that the latest version of datasketches-hive(Java Hive Adaptor) is 1.2.0, so we can upgrade it to from 1.1.0 to 1.2.0.
No
Yes
[mvn_den_log.txt](https://github.com/apache/hive/files/14668570/mvn_den_log.txt)
Existing UTs.
> HIVE-28139: Upgrade to datasketches 1.2.0

- ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFArrayAppend.java
- ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFArrayAppend.java
- ql/src/test/queries/clientnegative/udf_array_append_1.q
- ql/src/test/queries/clientnegative/udf_array_append_2.q
- ql/src/test/queries/clientpositive/udf_array_append.q
- ql/src/test/results/clientnegative/udf_array_append_1.q.out
- ql/src/test/results/clientnegative/udf_array_append_2.q.out
- ql/src/test/results/clientpositive/llap/show_functions.q.out
- ql/src/test/results/clientpositive/llap/udf_array_append.q.out
Implement array_append function in Hive
No
No
> HIVE-27671 - Implement array_append UDF to append an element to array

- iceberg/iceberg-handler/src/test/queries/positive/iceberg_merge_files.q
- iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_merge_files.q.out
- ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java
HIVE-28069: Addendum: Iceberg: Implement Merge task functionality for Iceberg tables - Add serde properties for CTAS and CMV
If file format is missing, it uses Parquet which leads to incorrect file format exceptions.
No
No
QTest
> HIVE-28069: Addendum: Iceberg: Implement Merge task functionality for Iceberg tables - Add serde properties for CTAS and CMV

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- iceberg/iceberg-handler/src/test/queries/positive/delete_all_iceberg.q
- iceberg/iceberg-handler/src/test/results/positive/delete_all_iceberg.q.out
- ql/src/java/org/apache/hadoop/hive/ql/parse/DeleteSemanticAnalyzer.java
- ql/src/test/results/clientpositive/llap/delete_all_non_partitioned.q.out
- ql/src/test/results/clientpositive/llap/delete_all_partitioned.q.out
- ql/src/test/results/clientpositive/llap/insert_update_delete.q.out
HIVE-28167: Full table deletion fails when converting to truncate for Iceberg and ACID tables
Full table deletion fails when converting to truncate for Iceberg and ACID tables
No
No
QTest
> HIVE-28167: Full table deletion fails when converting to truncate for Iceberg and ACID tables

- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestConflictingDataFiles.java
Run the test with vectorization true
IOContext gets shared in unit test causing non-vectorized to be flaky. 
No
Unit test TestConflictingDataFiles
> HIVE-28153: Flaky test TestConflictingDataFiles.testMultiFiltersUpdate

- jdbc/src/java/org/apache/hive/jdbc/Utils.java
- jdbc/src/test/org/apache/hive/jdbc/TestHiveConnection.java
Make default port effective.
Default port is not set effectively.
No
No
added unit test
> HIVE-28217: Make default port effective

- pom.xml
- ql/pom.xml
- serde/pom.xml
- serde/src/java/org/apache/hadoop/hive/serde2/OpenCSVSerde.java
Upgrade opencsv version to 5.9 (latest)
Hive has some classes which depend on openscv from Orc 1.8.5 library. Orc 1.9.3 doesn't supply opencsv and Hive doesn't compile. Need to upgrade opencsv in Hive before upgrading Orc version in Hive.
No
Pre-commit tests
> HIVE-28248: Upgrade opencsv to v5.9

- packaging/src/docker/README.md
While the quickstart page for Docker was up to date, the readme was not. I added the updates on the page to the readme.
Quicstart page: https://hive.apache.org/developement/quickstart/
It allows the user to see the current readme page.
No.
Since it only covers changes to the readme, I confirmed that the readme reads properly on markdown.
> Update Hive version in Docker README

- llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
Change-Id: I464211cc35e445c91b1b603fcf5c53b82e1d153a
Log message change.
Avoiding confusion.
Log message changes.
<No.
No test for log messages.
> HIVE-28246 Fix confusing log messages in LlapTaskSchedulerService

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergSnapshotRefExec.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergBranchOperation.java
- iceberg/iceberg-handler/src/test/queries/positive/alter_table_create_branch.q
- iceberg/iceberg-handler/src/test/results/positive/alter_table_create_branch.q.out
- iceberg/iceberg-handler/src/test/results/positive/alter_table_create_tag.q.out
- parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/snapshotref/AlterTableCreateSnapshotRefAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/AlterTableSnapshotRefSpec.java
Add support for if not exists and OR Replace while creating Branches
Better Usability 
Yes, Queries with If not exists and OR Replace with create branch can be executed
No
UT
> HIVE-28274: Iceberg: Add support for 'If Not Exists' and 'or Replace' for Create Branch.

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
- ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java
- ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java
Fixed projected column size logic
Incorrect projected column size leads to wrong split estimates and task overprovision.
No
No
qtests + TestInputOutputFormat#testProjectedColumnSize
> HIVE-28202: Incorrect projected column size after ORC upgrade to v1.6.7

- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMetaStoreClientWithLocalCache.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java
- ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHiveMetaStoreClient.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Clean up invalid exception thrown in MetaStoreClient
Lots of invalid exception were added in hms client methods, and this make the codes look like more redundant.
We can remove these invalid exception from method signature.
No
No
Existing UTs
> HIVE-28092: Clean up invalid exception thrown in MetaStoreClient

- ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/TestUtilities.java
Attempt making the scratch directory writable before failing
Better User/Admin experiance, in cloud situations where managing 
Yes, The Env setup won't fail if it is able to make the directory writable
No
In an actual Cloudera Azure Env
> HIVE-28287: Attempt make the scratch directory writable before failing.

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInternalRecordWrapper.java
1. Shoud return a new scan after applying column project parameter, Otherwise it doesn't make any sense
2. `scan.project()` and `scan.select()` can not be specified at the same time
Check this:
https://github.com/apache/iceberg/pull/1353/files#diff-a94dee2a22a2890689a84529a978a769bdc3b084f35d79caf9608d49b2e1cc1b
No
No
> HIVE-28306: Iceberg: Return new scan after applying column project parameter

- accumulo-handler/src/test/org/apache/hadoop/hive/accumulo/TestHiveAccumuloHelper.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/esri/HiveGeometryOIHelper.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/esri/ST_GeometryRelational.java
Replace org.apache.log4j.Logger with org.slf4j.Logger.
Logger should be created via facade(SLF4J), but some classes still directly access to Logger implementation. This patch fixes this issue.
No
No
This patch was not tested as it just changes logger instantiation code.
> HIVE-28304: Replace org.apache.log4j.Logger with org.slf4j.Logger

- llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java
This patch adds configuration/null checks to prevent NullPointerException.
As I explained the JIRA ticket(HIVE-28369), Hive throws NPE during proactive eviction when `hive.llap.io.encode.enabled` is false. 
No
No
Tested manually.
This cannot be tested using qtest because we cannot set up LLAP configuration in qfile as LLAP environment is initialized before test driver reads qfiles.
> HIVE-28369: Fix LLAP cache proactive eviction

- common/pom.xml
- hcatalog/server-extensions/pom.xml
- hcatalog/webhcat/svr/pom.xml
- llap-client/pom.xml
- llap-common/pom.xml
- llap-tez/pom.xml
- metastore/pom.xml
- serde/pom.xml
- service/pom.xml
- shims/0.23/pom.xml
- shims/common/pom.xml
- standalone-metastore/metastore-common/pom.xml
- standalone-metastore/pom.xml
- storage-api/pom.xml
Upgrades nimbus-jose-jwt to 9.37.3 and removes the older versions being pulled in transitively.
Fix CVEs
No
Yes.Tree attached in the [Jira.](https://issues.apache.org/jira/secure/attachment/13070269/mvn_dependency_tree.txt)
Relying on precommits
> HIVE-28375:Upgrade Nimbus-JOSE-JWT to 9.37.3

- hcatalog/webhcat/svr/src/main/bin/webhcat_config.sh
- parser/src/java/org/apache/hadoop/hive/ql/parse/ParseDriver.java
- parser/src/test/org/apache/hadoop/hive/ql/parse/HqlParser.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/Operator.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFEvaluator.java
- ql/src/test/org/apache/hadoop/hive/ql/plan/TestConditionalResolverCommonJoin.java
fix typo Overriden to Overridden
https://issues.apache.org/jira/browse/HIVE-28404
> HIVE-28404: Fix typo Overriden to Overridden

- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp
- standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h
- standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/DropCatalogRequest.java
- standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/DropCatalogRequest.php
- standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py
- standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
- standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/client/TestCatalogs.java
HIVE-28443: Add ifExists field to dropCatalogRequest to not throw exception when ifExists is set.
> HIVE-28443: Add ifExists field to dropCatalogRequest

- jdbc-handler/src/main/java/org/apache/hive/storage/jdbc/dao/GenericJdbcDatabaseAccessor.java
- ql/src/test/queries/clientpositive/external_jdbc_view.q
- ql/src/test/results/clientpositive/llap/external_jdbc_view.q.out
Proper handling of FQ names
````
Caught exception while trying to execute query\rjava.lang.RuntimeException: Cannot find <sampledb>.<sampletable> in sql query SELECT … FROM "<sampledb>"."<sampletable>"\r	at...
````
No
No
qtest
> HIVE-28451: JDBC: TableName matcher fix in GenericJdbcDatabaseAccessor#addBoundaryToQuery

- iceberg/checkstyle/checkstyle.xml
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/data/CachingDeleteLoader.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveDeleteFilter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/AbstractIcebergRecordReader.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergMergeRecordReader.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergRecordReader.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/vector/TestHiveVectorizedReader.java
Cache delete files on executors to save on multiple reads
No
No
Itest + regression test on a cluster
> HIVE-28452: Iceberg: Cache delete files on executors

- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergCTAS.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
CTAS, CTLT query failure while fetching URI for authorization
CTAS, CTLT query failure while fetching URI for authorization
No
No
Unit test
> HIVE-28482: Iceberg: CTAS, CTLT query failure while fetching URI for authorization

- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/CustomPartitionVertex.java
- ql/src/test/queries/clientpositive/smb_join_with_different_bucket_size.q
- ql/src/test/results/clientpositive/llap/smb_join_with_different_bucket_size.q.out
Fix CustomPartitionVertex to routes correct small table buckets.
New algorithm routes bucket N of small table to bucket M of big table if N % G == M % G, where G is g.c.d. of bucket size of small and big tables.
Current map-side SMB join returns wrong result when the bucket size of two input tables are not equal.
No
I added a qfile test, which is used in JIRA page.
> HIVE-27357: Fix CustomPartitionVertex.getBucketSplitMapForPath()

- .github/workflows/docker-GA-images.yml
- Jenkinsfile
- itests/pom.xml
- packaging/pom.xml
- packaging/src/docker/build.sh
- pom.xml
[HIVE-25027](https://issues.apache.org/jira/browse/HIVE-25027) hidden the iceberg module by default. IMO, we have put lots of effort into iceberg module and it is more stable than before. We should enable the iceberg module by default in case of mvn build.
No
No
After this change, you can build the package including iceberg moudle with this cmd:
`mvn clean install -DskipTests -Pdist`
> HIVE-28494: Iceberg: mvn build enables iceberg module by default

- itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java
Compare absolute UNIX timestamps value instead of using regex.
https://issues.apache.org/jira/browse/HIVE-28355
No
mvn test
> HIVE-28355: Fix intermittent failure of TestHplSqlViaBeeLine#testUNIX_TIMESTAMPHplSQLFunction

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
Only the alterSchemaVersion method of ObjectStore does not perform rollbackTranscation() if committed is false in finally.
so if commited = false, commitTransaction -> rollbackTranscation
https://issues.apache.org/jira/browse/HIVE-28500
> [HIVE-28500] Update alterSchemaVersion in ObjectStore.java

- iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hadoop/HiveHadoopTableTestBase.java
- iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hadoop/TestHiveHadoopCommits.java
- iceberg/patched-iceberg-core/pom.xml
- iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java
PR: core:Refactor the code of HadoopTableOptions
https://github.com/apache/iceberg/pull/10623 
All test cases can be found in this PR
HIVE-ISSUE: https://issues.apache.org/jira/browse/HIVE-28373
> HIVE-28373: Iceberg: Refactor the code of HadoopTableOptions

- standalone-metastore/metastore-server/pom.xml
https://issues.apache.org/jira/browse/HIVE-28497
Exclude commons-codec:commons-codec:jar:1.11 from org.apache.httpcomponents:httpclient
To address vulnerability sonatype-2012-0050
No
Yes
Before exclusion: [before.txt](https://github.com/user-attachments/files/16848311/before.txt)
After exclusion: [after.txt](https://github.com/user-attachments/files/16848340/after.txt)
mvn dependency:tree -Dincludes=commons-codec:commons-codec:jar
> HIVE-28497: Address CVE due to commons-codec:commons-codec:jar:1.11

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/hadoop/HadoopTableOperations.java
Fix new added iceberg class code style
> HIVE-28514: Addendum: Fix new added iceberg class code style

- pom.xml
Upgrade to Tez 0.10.4
Blocks features and bugfixes.
No.
Yes.
Hive precommit uses the new Tez version extensively
> HIVE-28434: Upgrade to tez 0.10.4

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestConflictingDataFiles.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java
- ql/src/java/org/apache/hadoop/hive/ql/Compiler.java
- ql/src/java/org/apache/hadoop/hive/ql/Driver.java
- ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/Executor.java
- ql/src/java/org/apache/hadoop/hive/ql/QueryPlan.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/database/drop/DropDatabaseAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/compact/AlterTableCompactAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/ExecuteStatementAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/ExportSemanticAnalyzer.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnExIm.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnLoadData.java
- ql/src/test/org/apache/hadoop/hive/ql/TestTxnNoBuckets.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
- streaming/src/java/org/apache/hive/streaming/TransactionBatch.java
Introduces the locking to serialize some operation execution
Fixes the data correctness in case of concurrent Insert and IOW
No
No
ITests
> HIVE-28366: Iceberg: Concurrent Insert and IOW produce incorrect result

- iceberg/iceberg-handler/src/test/queries/positive/merge_iceberg_orc.q
- iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_orc.q.out
- ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/MergeRewriter.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/sql/MultiInsertSqlGenerator.java
Merge-Insert with reserved keywords as column names
Fix
No
No
Qtest
> HIVE-28282: Addendum: Merge-Insert with reserved keywords as column names

- iceberg/iceberg-handler/src/test/queries/positive/merge_iceberg_copy_on_write_partitioned.q
- iceberg/iceberg-handler/src/test/queries/positive/merge_iceberg_copy_on_write_unpartitioned.q
- iceberg/iceberg-handler/src/test/queries/positive/merge_iceberg_orc.q
- iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_partitioned.q.out
- iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_copy_on_write_unpartitioned.q.out
- iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_orc.q.out
- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/constraint/ConstraintsUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/CopyOnWriteMergeRewriter.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/MergeRewriter.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/MergeStatement.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/rewrite/sql/MultiInsertSqlGenerator.java
> [WIP] 4.0.1

- ql/src/java/org/apache/hadoop/hive/ql/io/HiveSequenceFileInputFormat.java
Set files in thread safe manner in HiveSequenceFileInputFormat
Set files in thread safe manner in HiveSequenceFileInputFormat
Setting files is not thread safe right now.
No
No
Concurrent tests run on a cluster with extremely high number of SELECT query execution.
> HIVE-28530: Set files in thread safe manner in HiveSequenceFileInputFormat

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java
Remove an unnecessary Statsistics.clone() invocation in StatsRulesProcFactory.applyRuntimeStats().
Current StatsRulesProcFactory.applyRuntimeStats() clones original stats and then calls scaleToRowCount() on it.
But Statistics.scaleToRowCount() always returns the clone of itself, so we don't have to clone the original stats in StatsRulesProcFactory.applyRuntimeStats().
No
No
Tested in local environment
> HIVE-28556: Do not clone Statistics before scaleToRowCount()

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/compaction/IcebergMajorQueryCompactor.java
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_partition_evolution_ordered.q
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_unpartitioned_ordered.q
- iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_partition_evolution_ordered.q.out
- iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_unpartitioned.q.out
- iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_major_compaction_unpartitioned_ordered.q.out
- itests/src/test/resources/testconfiguration.properties
- parser/src/java/org/apache/hadoop/hive/ql/parse/AlterClauseParser.g
- parser/src/test/org/apache/hadoop/hive/ql/parse/TestParseOptimizeTable.java
- ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorUtil.java
Added sort order support for Hive Iceberg Compaction that allows to optionally order the data as part of compaction operation.
Sort ordering the data as part of compaction can give additional performance improvement.
Yes, Hive Iceberg compaction command now supports ORDER BY clause.
No
New q-tests.
> HIVE-28524: Iceberg: Major QB Compaction add sort order support

- pom.xml
- ql/pom.xml
- standalone-metastore/pom.xml
Upgradation of spring.version from 5.3.21 to 5.3.39
1. Upgradation of spring.version from 5.3.21 to 5.3.39 in pom.xml and standalone-metastore/pom.xml
2. Exclusion of org.springframework:spring-context from atlas-intg in ql/pom.xml
No
Yes
Adding the image for packaged jars and the dependency tree for Spring
[dependency_tree_new.txt](https://github.com/user-attachments/files/16958001/dependency_tree_new.txt)
> HIVE-28245: Upgrade Spring to 5.3.39 due to CVE

- service/src/java/org/apache/hive/service/servlet/OTELExporter.java
Add Execution Engine details in the QueryData
For Better Usability 
Execution Engine details are shown as part of Query Info
No
Manual
> HIVE-28648: OTEL: Add Execution Engine as part of the Query Data.

- data/files/jsonserde.txt
- ql/src/test/queries/clientpositive/json_serde3.q
- ql/src/test/results/clientpositive/llap/json_serde3.q.out
- serde/src/java/org/apache/hadoop/hive/serde2/JsonSerDe.java
- serde/src/java/org/apache/hadoop/hive/serde2/json/HiveJsonReader.java
1. Ensure case-sensitive handling of boolean strings in JSON deserialization and resolve inconsistencies between INSERT statements and direct JSON loading.
2. Implement automatic detection and appropriate deserialization of JSON nodes, distinguishing between base64-encoded and raw strings.
The changes are needed to follow SQL standards by treating any string other than "false" (case-insensitive) as true and to resolve inconsistencies between outputs when using an INSERT statement and loading a JSON value directly. Additionally, Hive needs to automatically detect if a JSON node is base64-encoded and handle it accordingly, ensuring proper deserialization of both base64-encoded and raw strings.
[Steps to reproduce the issue and more details mentioned in jira description: …
> HIVE-28632: Fix issues in JSON SerDe implementations related to Boolean, Binary

- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreDeadlock.java
> HIVE-28659: Disable test: TestMetaStoreDeadlock

- common/src/java/org/apache/hive/http/HttpServer.java
- service/src/java/org/apache/hive/service/auth/ldap/LdapAuthService.java
- service/src/java/org/apache/hive/service/server/HiveServer2.java
- service/src/java/org/apache/hive/service/servlet/LDAPAuthenticationFilter.java
- service/src/java/org/apache/hive/service/servlet/LoginServlet.java
- service/src/resources/hive-webapps/hiveserver2/loginForm.jsp
- service/src/test/org/apache/hive/service/server/TestHS2HttpServerLDAP.java
Handle the security issue on HS2 WebUI's authentication
Any un-authenticated user can still access to /hiveserver2.jsp;login or /log even if the LDAP is enabled
No
No
Tested locally with standalone HS2
> HIVE-28594: Handle the issue on HS2 WebUI's LDAP authentication

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
- ql/src/test/org/apache/hadoop/hive/ql/optimizer/TestSharedWorkOptimizer.java
Map join container cache key should be unique for each map join hash table if they are of different join types. This will prevent hash table from getting shared between different join types. 
Sharing same hash table between different join types will not work because they expect different hash table type based on the join type. Otherwise we might run into ClassCastException and also potential wrong results in certain cases.
No
No
cd ql
mvn test -Dtest=TestSharedWorkOptimizer#testMapJoinCacheReuse
> HIVE-28532 Map Join Reuse cache allows to share hashtables for different join types

- common/pom.xml
- common/src/java/org/apache/hadoop/hive/common/OTELUtils.java
- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapDaemon.java
- service/pom.xml
- service/src/java/org/apache/hive/service/server/HiveServer2.java
Allow configuring the Retry Policy for OTEL Exporters
To have better stability during failures or N/W issues with OTEL collectors
No
No
Manual
> HIVE-28698: OTEL: Add Retry Policy in the Exporter.

- iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_single_partition_with_evolution.q
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_major_compaction_single_partition_with_evolution2.q
Fix not stable Iceberg tests
To have consistent results when executed locally and on Jenkins.
No
No
> HIVE-28706: Iceberg: fix not stable tests

- pom.xml
Upgrade joda version from 2.9.9(released in 2017) to 2.13.0(released in 2024)
No
Yes. see 
[joda_upgrade.txt](https://github.com/user-attachments/files/18418702/joda_upgrade.txt)
> HIVE-28709: Upgrade Joda time to latest version

- llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/ContainerRunnerImpl.java
Fix logging format issues in ContainerRunnerImpl file
should use logging format instead of string concatenation
No
No
Existing UT
> HIVE-28635: Fix logging format issues in ContainerRunnerImpl file

- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizationContext.java
See the: https://issues.apache.org/jira/browse/HIVE-25043
That want to use a custom UDF that supports Vectorized when hive.vectorized.adaptor.usage.mode=chosen is specified.
No
Remote cluster.
> HIVE-25043: Support custom UDF in Vectorized mode

- ql/src/test/results/clientpositive/llap/query_history.q.out
Change the query output plan in the output
To fix the test
No
No
Ran locally
> HIVE-28769: Fix test: query_history.q.

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergFilterFactory.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_drop_partition_transform_column.q
- iceberg/iceberg-handler/src/test/results/negative/iceberg_drop_partition_tranform_column.q.out
- iceberg/iceberg-handler/src/test/results/positive/iceberg_drop_partition_transform_column.q.out
- parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g
- ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/TransformSpec.java
- ql/src/test/results/clientpositive/llap/query_history.q.out
Allow drop partition with transformed partition columns by providing year(<columnName>)= 'value'
To support drop partition with transformed columns
Yes, Drop partition works for transformed columns
No
UT
> HIVE-28762: Iceberg: Add support for partitions with transforms in Drop partition.

- standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
Don't change writeId to 0 during alter partition query
External systems that consume the alter partition event expect the same writeId when trivial properties are changed on the partition.
No
No
Local tests
> HIVE-28803: Persist writeId as -1 instead of 0 during alter operation

- ql/src/test/queries/clientpositive/hybridgrace_hashjoin_2.q
- ql/src/test/results/clientpositive/llap/hybridgrace_hashjoin_2.q.out
- ql/src/test/results/clientpositive/tez/hybridgrace_hashjoin_2.q.out
Disable SharedWorkOptimization(`hive.optimize.shared.work`) in `hybridgrace_hashjoin_2.q`.
After applying HIVE-26986, the CI often fails to run `hybridgrace_hashjoin_2.q` due to OOM. Since the OOM comes from the merged Map vertex, we temporarily disable SWO in order to prevent the failure of the CI.
No
No
This patch addresses the issue in the CI, so I can't test the patch in my local environment. I will check whether this patch actually prevents OOM in the CI environment.
> HIVE-28832: Disable SharedWorkOptimization in hybridgrace_hashjoin_2

- common/src/java/org/apache/hive/common/IPStackUtils.java
- common/src/test/org/apache/hive/common/IPStackUtilsTest.java
- jdbc/src/java/org/apache/hive/jdbc/ZooKeeperHiveClientHelper.java
- jdbc/src/test/org/apache/hive/jdbc/ZooKeeperHiveClientHelperTest.java
- ql/src/java/org/apache/hadoop/hive/ql/lockmgr/HiveLockObject.java
- ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestHiveLockObject.java
- service/src/java/org/apache/hive/service/server/HS2ActivePassiveHARegistry.java
Avoid unsafe splits by a colon symbol on URIs that might contain IPv6 literals.
To support IPv6 in Hive.
No
No
New unit tests.
> HIVE-28782: Avoid unsafe splits on URIs that might contain IPv6 literals

- itests/qtest-kudu/pom.xml
- itests/util/pom.xml
- kudu-handler/pom.xml
- pom.xml
Upgrade Kudu to 1.17.0
Higher version brings improvements including support for JDK-17
No
Yes
[dpn_kudu_1170.txt](https://github.com/user-attachments/files/19683219/dpn_kudu_1170.txt)
CI tests should be enough to validate the kudu upgrade
> HIVE-28896: Upgrade kudu to 1.17.0

- iceberg/iceberg-handler/src/test/results/positive/col_stats.q.out
- standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/StatsSetupConst.java
- standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/common/TestStatsSetupConst.java
Use lowercase for stats columns
Duplicate column names in `describe formatted` stats output because `StatsSetupConst` is case-sensitive
No
No
qtest + unit
> HIVE-28886:  Addendum: Column names in the DESCRIBE FORMATTED stats output should be in lowercase

- standalone-metastore/pom.xml
Version upgrade for grpc
To resolve CVEs like  CVE-2023-2976 and CVE-2020-8908
No
> HIVE-28933: Upgrade grpc version to 1.72.0

- itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/TestDbNotificationListener.java
Ignore user defined database creation time from equality comparison.
Avoid intermittent test failures and stabilize CI.
The test is problematic cause it sets explicitly the creation time and it expects the same to be returned in the notification message. However, the HMS always overrides the `createTime` (expected behavior according to tests added by HIVE-21077) field during the creation of the database so the initial value is lost. Slight delays (more than 1 second) between the initialization of the test and the creation of the database are causing the test to fail. The test is more likely to fail in CI where delays are more common.
No
Adding delays (e.g., `Thread.sleep(2000)`) before `ms.createDatabase` call and running the test.
> HIVE-28949: TestDbNotificationListener#createDatabase fails intermittently due to different createTime

- iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergFilterFactory.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/compaction/IcebergQueryCompactor.java
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_minor_compaction_bucket.q
- iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_minor_compaction_bucket.q.out
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestIcebergCompactorOnTez.java
- itests/src/test/resources/testconfiguration.properties
Using partition spec id and partition values for condition on partitions in compaction query instead of partition hash 
Partition hash does not guarantee uniqueness. it is not meant to serve as a unique key, but rather a mean for consistent distribution.
No
New and existing q-tests.
> HIVE-28935: Iceberg: fix partition filtering condition in compaction query

- packaging/src/main/assembly/bin.xml
- pom.xml
- ql/pom.xml
Added  `jts-core` into the shaded hive-exec jar, and exclued it from hive binary package (lib directory). As this jar only be used in  the Tez job.
See [HIVE-28958](https://issues.apache.org/jira/browse/HIVE-28958)
Tested against local hive & hadoop cluster
> HIVE-28958: Tez job failed with: NoClassDefFoundError: org/locationtech/jts/geom/Geometry

- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java
Do not commit the task if it was killed
Correctness issue
No
> HIVE-28962: Prevent committing outputs if an exception was thrown in the Tez processor

- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/reexec/TestReExecuteKilledTezAMQueryPlugin.java
Improved the test for Tez AM re-execution by making it wait until the query is fully running before killing the YARN application.
The test was unreliable because it sometimes killed the application before the query had started, causing false failures.
No
Flaky test pipeline passed.
Before:
After:
> HIVE-28999: Fix Flaky Test: TestReExecuteKilledTezAMQueryPlugin.testKillQueryById

- llap-client/src/java/org/apache/hadoop/hive/llap/tezplugins/helpers/LlapTaskUmbilicalServer.java
- llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/ShuffleHandler.java
- llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskCommunicator.java
- llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
- pom.xml
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSplits.java
> HIVE-28986: Upgrade to Tez 0.10.5

- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionPoolManager.java
Fix an NPE.
Fix an NPE.
No.
Manually.
> HIVE-29007 Fix NPE in TezSessionPoolManager

- itests/src/test/resources/testconfiguration.properties
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- ql/src/test/queries/clientpositive/insert_cbo_false.q
- ql/src/test/results/clientpositive/llap/insert_cbo_false.q.out
Added code for hadnling INSERT INTO statement with target columns specifed in the case of CBO=false.
[HIVE-28595](https://issues.apache.org/jira/browse/HIVE-28595)
No
No
mvn test -Dtest=TestMiniLlapCliDriver -Dqfile=insert_cbo_false.q
> HIVE-28595: Not able to insert data with hive.cbo.enable=false

- ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/RelFieldTrimmer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
- ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/rules/TestHiveRelFieldTrimmer.java
A cherry-pick for HIVE-28667.
Although this patch is a relatively minor change. However, this change can eliminate unnecessary error logs in Hive, which will help improve the user experience when viewing Hive logs.
So it is necessary to cherry-pick this patch to branch-4.1.
> HIVE-28667: Error initializing field trimmer instance when starting HS2 (#5879)

- standalone-metastore/metastore-server/pom.xml
- standalone-metastore/metastore-server/src/docker/README.md
- standalone-metastore/metastore-server/src/docker/build.sh
- standalone-metastore/metastore-server/src/docker/conf/metastore-site.xml
- standalone-metastore/metastore-server/src/docker/docker-compose.yml
mvn clean install -DskipTests -DallModules -Pdocker
cd src/docker
docker compose up -d
- POST localhost:9001/iceberg/v1/namespaces/default/tables
````
{
"name": "customer_orders",
"schema": {
"type": "struct",
"fields": [
{
"id": 1,
"name": "order_id",
"type": "int",
"required": true
},
{
"id": 2,
"name": "customer_id",
"type": "int",
"required": true
},
{
"id": 3,
"name": "order_total",
"type": "double",
"required": true
},
{
"id": 4,
"name": "order_date",
"type": "string",
"required": true
}
]
},
"stage-create": false
}
````
- GET localhost:9001/iceberg/v1/namespaces/default/tables
> HIVE-27275: Addendum: Add missing dependencies and expose ports

- ql/src/java/org/apache/hadoop/hive/ql/io/merge/MergeFileTask.java
Close the JobClient
Prevents leak by releasing the resource
No
> HIVE-23708: MergeFileTask#execute need to close JobClient

- .github/workflows/docker-GA-images.yml
> HIVE-29071: Add release workflow for HMS docker image

- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/compaction/IcebergTableOptimizer.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/metastore/task/IcebergHouseKeeperService.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/metastore/task/TestIcebergHouseKeeperService.java
Removed starting of a Hive session in IcebergTableOptimizer
Usage of the Session in Hive-Iceberg brings additional dependencies (Tez) into Hive Docker.
No
Hive pre-commit testing
> HIVE-29028: Iceberg: Addendum: Retrieve tables without session

- Jenkinsfile
Cheery-pick https://github.com/apache/hive/pull/5949/files into branch-4.1
Fix CI
> HIVE-29081: CI fails intermittently cause some runs exceed ephemeral storage limits (#5949)

- itests/src/test/resources/testconfiguration.properties
- ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java
- ql/src/test/queries/clientpositive/partition_default_name_change_numeric.q
- ql/src/test/results/clientpositive/tez/partition_default_name_change_numeric.q.out
Cherry-pick https://github.com/apache/hive/commit/eaa9d32e78930a8b2f83b5a7b06bc6fe6540b479 into branch-4.1
> HIVE-29069: Fix Query Failure while computing Range Partition Column stats on Numeric partition column types (#5932)

- ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedRowBatchCtx.java
- ql/src/test/queries/clientpositive/vector_decimal_partition.q
- ql/src/test/results/clientpositive/llap/vector_decimal_partition.q.out
- storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/Decimal64ColumnVector.java
Cherry-pick https://github.com/apache/hive/commit/6237d78e6ba031c0b1fe73add544443f599aac44 into branch-4.1
> HIVE-29080: Fix Incorrect results for queries on Decimal column Partitioned table with Vectorization enabled (#5953)

- iceberg/checkstyle/checkstyle.xml
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/Catalogs.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java
- iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java
- iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
- iceberg/iceberg-handler/src/test/queries/positive/hadoop_catalog_create_table.q
- iceberg/iceberg-handler/src/test/results/positive/llap/hadoop_catalog_create_table.q.out
- itests/src/test/resources/testconfiguration.properties
Cherry-pick https://github.com/apache/hive/commit/6bd4d987a08de735bd99fca73226c55ee4e508ab into branch-4.1
> HIVE-29083: Iceberg: Unable to create table using HadoopCatalog (#5959)

- RELEASE_NOTES.txt
- standalone-metastore/RELEASE_NOTES.txt
Update RELEASE_NOTES before releasng 4.1.0 version.
> Update RELEASE_NOTES for 4.1.0 version

- standalone-metastore/RELEASE_NOTES.txt
> Update standalone hms RELEASE_NOTES

- ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/HiveAuthzContext.java
- ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java
Enhance HiveAuthzContext with a Client Configuration Map
Adding a map to hold client additional information in HiveAuthzContext will improve auditing and authorization flexibility by making the system aware of the client application making a request
No
Regression Tests
> HIVE-29082: Enhance HiveAuthzContext with a Client Configuration Map

- jdbc/pom.xml
Fix the missing jars when using hive-jdbc-standalone.jar. See details from HIVE-29092 to check how to test this case.
No
Local java api test using hive-jdbc-standalone jar
> HIVE-29092: NoClassDefFoundError: io/netty/util/NetUtil when using hive jdbc standalone jar

- jdbc/pom.xml
…
Cherry pick https://github.com/apache/hive/commit/93c765df0272523d5d70614b8ff422f1f2f2168a into branch-4.1
> HIVE-29092: NoClassDefFoundError: io/netty/util/NetUtil when using hive jdbc standalone jar (#5981)

- ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
CREATE TABLE is handled by DDLSemanticAnalyzerFactory as it is a ddl statement
Earlier handles function of  DDLSemanticAnalyzerFactory returns false for TOK_CREATETABLE
No
local build and unit tests
> HIVE-28724:CREATE TABLE is not handled by DDLSemanticAnalyzerFactory

- ql/src/test/org/apache/hadoop/hive/ql/exec/vector/aggregation/TestVectorAggregation.java
The TestVectorAggregation took 63s on my laptop due to a slow implementation of getLinearRandomNumber. I propose to replace the for loop with an analytical solution (HIVE-29155). With the patch, TestVectorAggregation takes only 23s. I've added javadoc to the method to make it easier to understand what the method is doing.
I hope it is OK to remove some unused imports as well.
TestVectorAggregation is slower than necessary, therefore consuming resources (time & CPU) in the CI and machines of developers.
No
Manual test that the distribution of generated numbers stays the same. See attachment of HIVE-29155. TestVectorAggregation was executed and passes.
> HIVE-29155: Improve performance of TestVectorAggregation

- iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/MetastoreUtil.java
- iceberg/iceberg-handler/src/test/queries/positive/iceberg_rest_catalog.q
- iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_rest_catalog.q.out
Fixes to make Insert operations work with HMS REST Catalog Client.
Insert didn't work with HMS REST Catalog Client.
No
Updated `iceberg_rest_catalog.q` to perform Insert and Select operations.
> HIVE-29220: Iceberg: Enable write operations with REST Catalog HMS Client

- common/src/java/org/apache/hadoop/hive/common/FileUtils.java
- common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
- hcatalog/core/src/main/java/org/apache/hive/hcatalog/common/HCatUtil.java
- itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCleanerWithReplication.java
- metastore/src/java/org/apache/hadoop/hive/metastore/HiveClientCache.java
- metastore/src/java/org/apache/hadoop/hive/metastore/HiveMetaStoreUtils.java
- metastore/src/test/org/apache/hadoop/hive/metastore/TestHiveClientCache.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionPoolSession.java
- ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionState.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/CopyUtils.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/AbstractEventHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/CommitTxnHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/CreateFunctionHandler.java
- ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/io/FileOperations.java
- ql/src/java/org/apache/hadoop/hive/ql/security/authorization/StorageBasedAuthorizationProvider.java
- ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSplits.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/mr/TestMapRedTask.java
- ql/src/test/org/apache/hadoop/hive/ql/exec/tez/SampleTezSessionState.java
- service/src/java/org/apache/hive/service/cli/CLIService.java
- service/src/java/org/apache/hive/service/cli/thrift/ThriftCLIService.java
- shims/common/src/main/java/org/apache/hadoop/fs/DefaultFileAccess.java
- shims/common/src/main/java/org/apache/hadoop/hive/shims/Utils.java
Clean some unnecessary `LoginException` usages.
Clean code.
No.
Passing existing tests.
> HIVE-29209: Remove unnecessary usage of LoginException
