hcatalog/streaming/src/java/org/apache/hive/hcatalog/streaming/HiveEndPoint.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/AlterTableAddPartitionDesc.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/AlterTableAddPartitionOperation.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/events/filesystem/FSTableEvent.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/table/LoadPartitions.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/parse/DDLSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/ImportSemanticAnalyzer.java, ql/src/test/results/clientpositive/add_part_multiple.q.out, ql/src/test/results/clientpositive/drop_partitions_filter.q.out, ql/src/test/results/clientpositive/llap/add_part_with_loc.q.out, ql/src/test/results/clientpositive/spark/add_part_multiple.q.out, streaming/src/java/org/apache/hive/streaming/HiveStreamingConnection.java
AlterTableAddPartitionDesc should be immutable, like the rest of the desc classes. This can not be done 100% right now, as it requires the refactoring of the ImportSemanticAnalyzer, so the task will be finished only then.
Add Partition logic should be moved from Hive.java to AlterTableAddPartitionOperation.java, only the metastore calls should remain in Hive.java.
=> Hive 22028 Clean up Add Partition

hcatalog/streaming/src/java/org/apache/hive/hcatalog/streaming/HiveEndPoint.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/AlterTableAddPartitionDesc.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/AlterTableAddPartitionOperation.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/events/filesystem/FSTableEvent.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/table/LoadPartitions.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/parse/DDLSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/ImportSemanticAnalyzer.java, ql/src/test/results/clientpositive/add_part_multiple.q.out, ql/src/test/results/clientpositive/drop_partitions_filter.q.out, ql/src/test/results/clientpositive/llap/add_part_with_loc.q.out, ql/src/test/results/clientpositive/spark/add_part_multiple.q.out, streaming/src/java/org/apache/hive/streaming/HiveStreamingConnection.java
This reverts commit 853bf6252a0d5b0d10f35248b4b4785c08380914.
=> Revert "HIVE-22028 Clean up Add Partition"

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestCreateUdfEntities.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/exec/spark/TestSparkStatistics.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHiveAuthorizerCheckInvocation.java, ql/src/java/org/apache/hadoop/hive/ql/Driver.java, ql/src/java/org/apache/hadoop/hive/ql/IDriver.java, ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecDriver.java, ql/src/test/org/apache/hadoop/hive/ql/exec/spark/TestHiveSparkClient.java, ql/src/test/org/apache/hadoop/hive/ql/exec/spark/TestSparkPlan.java, ql/src/test/org/apache/hadoop/hive/ql/hooks/TestHooks.java, ql/src/test/org/apache/hadoop/hive/ql/io/TestSymlinkTextInputFormat.java, ql/src/test/org/apache/hadoop/hive/ql/parse/TestColumnAccess.java, ql/src/test/org/apache/hadoop/hive/ql/parse/TestHiveDecimalParse.java, ql/src/test/org/apache/hadoop/hive/ql/plan/TestReadEntityDirect.java, ql/src/test/org/apache/hadoop/hive/ql/plan/TestViewEntity.java, ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHivePrivilegeObjectOwnerNameAndType.java
In the IDriver interface there is an "int compile(String command)' function which is only used by tests. As this is production code, it should be removed from the interface. Also there are several other unused codes and functions/fields with visibility that should be reduced.
=> HIVE-21996 Remove unused code from Driver

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLUtils.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLWork.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/database/AlterDatabaseSetPropertiesOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/database/CreateDatabaseOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/function/ShowFunctionsDesc.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/misc/MsckOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/process/ShowCompactionsOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/process/ShowTransactionsOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractAlterTableOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/creation/CreateTableDesc.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/creation/DropTableDesc.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/creation/ShowCreateTableOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/DescTableOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/lock/ShowLocksOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/AlterTableSetPropertiesOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/AlterTableAddPartitionDesc.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/AlterTableDropPartitionDesc.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/AlterTableDropPartitionOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/AlterTableArchiveOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/AlterTableUnarchiveOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/CreateViewDesc.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/CreateViewOperation.java, ql/src/test/results/clientpositive/show_create_table_alter.q.out
Also fixed small checkstyle issues and removed unused codes from some other ddl files.
=> HIVE-22010 - Clean up ShowCreateTableOperation

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorThread.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
Update metrics when the initiator runs, and we have every data at hand
=> HIVE-23624: Add metastore metrics to show the compaction status

accumulo-handler/src/java/org/apache/hadoop/hive/accumulo/predicate/compare/StringCompare.java, hcatalog/core/src/main/java/org/apache/hive/hcatalog/mapreduce/FileOutputCommitterContainer.java, vector-code-gen/src/org/apache/hadoop/hive/tools/GenVectorCode.java
[HIVE-21636](https://issues.apache.org/jira/browse/HIVE-21636) replaceAll() to replace() where the extra regex compilation associated with replaceAll() is not needed
=> [HIVE-21636] ReplaceAll() -> replace() for non regex strings

beeline/src/java/org/apache/hive/beeline/Commands.java
Beeline: Null pointers should not be dereferenced
=> HIVE-23615: Null pointers should not be dereferenced

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/parse/type/TypeCheckProcFactory.java, ql/src/test/org/apache/hadoop/hive/ql/parse/type/TestBigIntCompareValidation.java
Comparing bigints and (var)chars may output wrong results
=> HIVE-23269: Unsafe comparing bigints and strings

pom.xml
Update the Tez version to 0.9.2
Local unit tests completed successfully.
=> HIVE-23689: Bump Tez version to 0.9.2

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionState.java
- add a configuration item to support setting tez job name
- feature
- https://issues.apache.org/jira/browse/HIVE-23026
- We can use 'set tez.job.name=<customized_job_name>;' or '--hiveconf ez.job.name=<customized_job_name>' to use this function to customize Yarn application name when we run a sql. 
- We recommend setting  the 'customized_job_name' to a Java String.format() string that can accept the hive session ID as a single parameter.
=> HIVE-23026: Allow for custom YARN application name for TEZ queries (branch-2)

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, llap-client/src/java/org/apache/hadoop/hive/registry/impl/ZkRegistryBase.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/security/ZooKeeperTokenStore.java
HIVE-23715: Fix zookeeper ssl keystore password handling issues
=> HIVE-23715: Fix zookeeper ssl keystore password handling issues

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/reexec/TestReExecuteKilledTezAMQueryPlugin.java, itests/hive-unit/src/test/java/org/apache/hive/TestKillTezAM.java, ql/src/java/org/apache/hadoop/hive/ql/DriverFactory.java, ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecuteLostAMQueryPlugin.java
If the AM running the query is killed due to node going down, the query is killed. This plugin checks the error message received and matches with lost node exception. If yes, the query is re-run.
=> HIVE-23619: Add new reexecute plugin to rerun queries in case AM is down due to lost node

ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbLockManager.java
Moving the logging of lock request object to debug, since it prints out the lock request for ALL partitions, which can be huge.
=> HIVE-23738: DBLockManager::lock() : Move lock request to debug level

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
This log is not needed at INFO log level.
=> HIVE-23774: Reduce log level at aggrColStatsForPartitions in MetaStoreDirectSql.java

shims/common/src/main/java/org/apache/hadoop/fs/ProxyFileSystem.java
HADOOP-16582 have changed the way how mkdirs() work:
Before HADOOP-16582:
All calls to mkdirs(p) were fast-tracked to FileSystem.mkdirs which were then re-routed to mkdirs(p, permission) method. For ProxyFileSytem the call would look like
FileUtiles.mkdir(p)  ----->  FileSystem.mkdirs(p) ---> ProxyFileSytem.mkdirs(p,permission)
An implementation of FileSystem have only needed implement mkdirs(p, permission)
After HADOOP-16582:
Since FilterFileSystem overrides mkdirs(p) method the new call to ProxyFileSystem would look like
FileUtiles.mkdir(p) ---> FilterFileSystem.mkdirs(p) -->
This will make all the qtests fails with the below exception
Caused by: java.lang.IllegalArgumentException: Wrong FS: pfile:/media/ebs1/workspace/hive-3.1-qtest/group/5/label/HiveQTest/hive-1.2.0/itests/qtest/target …
=> HIVE-23751: QTest: Override #mkdirs() method in ProxyFileSystem To Align After HADOOP-16582

ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java
Run AcidUtils.getHdfsDirSnapshots to collect the relevant files, and use that for stats generation
=> HIVE-23791: Optimize ACID stats generation

serde/src/test/org/apache/hadoop/hive/serde2/objectinspector/TestStandardObjectInspectors.java
The background information is presented here: https://issues.apache.org/jira/browse/HIVE-22952
This PR aims to fix the issue without hurting any performance at all. It uses LinkedHashMap instead of HashMap in the test so that the test is no more flaky.
=> HIVE-22952 Use LinkedHashMap in TestStandardObjectInspectors.java

ql/src/java/org/apache/hadoop/hive/ql/exec/persistence/BytesBytesMultiHashMap.java, ql/src/test/org/apache/hadoop/hive/ql/exec/persistence/TestBytesBytesMultiHashMap.java
Observed that MapJoin is failing when row count is provided as (2^x)+(2^(x+1)). Fixing it and added a unit test to check against such case
=> HIVE-23509: MapJoin AssertionError: Capacity must be power of 2

ql/src/java/org/apache/hadoop/hive/ql/Driver.java, ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java, service/src/test/org/apache/hadoop/util/ShutdownHookManagerInspector.java, service/src/test/org/apache/hive/service/cli/operation/TestQueryShutdownHooks.java
Each query creates a shutdownRunner which will release transactional resources in case JVM exits mid-query. These shutdownRunners are not removed until session is closed. Session lifetime is unbounded. These shutdown hooks can cause OOM. We should remove them once query is committed or rolled back.
Change-Id: I0b747bbfb2a451c2be1a28f21d4fb6354f76ee5a
=> HIVE-23830: Remove shutdownRunner runner after query is committed

itests/src/test/resources/testconfiguration.properties, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/CastStringToDate.java, ql/src/test/queries/clientpositive/vectorization_cast_string_to_date.q, ql/src/test/results/clientpositive/llap/vectorization_cast_string_to_date.q.out
=> HIVE-23807 Wrong results with vectorization enabled

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHiveAuthorizerCheckInvocation.java, ql/src/java/org/apache/hadoop/hive/ql/Driver.java, ql/src/java/org/apache/hadoop/hive/ql/DriverFactory.java, ql/src/java/org/apache/hadoop/hive/ql/DriverState.java, ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java, ql/src/java/org/apache/hadoop/hive/ql/DriverUtils.java, ql/src/java/org/apache/hadoop/hive/ql/Executor.java, ql/src/java/org/apache/hadoop/hive/ql/HiveDriverRunHook.java, ql/src/java/org/apache/hadoop/hive/ql/HiveDriverRunHookContext.java, ql/src/java/org/apache/hadoop/hive/ql/IDriver.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSplits.java
Driver is now cut down to it's minimal size by extracting all of it's sub tasks to separate classes. The rest should be cleaned up by
- moving out some smaller parts of the code to sub task and utility classes wherever it is still possible
- fix checkstyle issues
- add missing javadocs
=> HIVE-23814: Clean up Driver (Miklos Gergely)

parser/bin/fixHiveParser.sh, parser/pom.xml
HivePasrser.g can not be extended anymore as adding any more tokens leads to a "code too large" problem, because the compiled code size would exceed 65536 bytes. The real solution would be to introduce anltr4, in the meantime it can be fixed be moving the tokenNames variable into a separate file.
=> HIVE-23857: Fix HiveParser 'code too large' problem (Miklos Gergely, reviewed by David Mollitor)

beeline/src/java/org/apache/hive/beeline/Rows.java, beeline/src/test/org/apache/hive/beeline/TestIncrementalRows.java
Fixed Binary data type in beeline rows to encode to Base64
https://issues.apache.org/jira/browse/HIVE-23856
=> HIVE-23856: Beeline Should Print Binary Data in Base64

jdbc/src/java/org/apache/hive/jdbc/HiveQueryResultSet.java
Debugging fetch request will help in troubleshooting client side requests to HS2.
hive-jdbc probably needs better logging overall, will likely be taking a look at that in the future.
=> HIVE-23874: Added debug line for fetchRequest in the HiveQueryResultSet

.github/pull_request_template.md
The proposed change is an update to the github pull request template. I've copied the template from the Apache Spark project which seems to work pretty well.
The project is now accepting PR's from github, which is great in that it should drastically increase the number of contributors. Consequently this also means an increase in the number of PR's which means that we need to make reviewing PR's as easy as possible for the people who have those permissions.
Yes, contributors who create a new PR will see the new PR template.
This patch was not tested.
=> HIVE-23915: Improve Github PR Template

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/test/queries/clientpositive/having_distinct_function.q, ql/src/test/results/clientpositive/llap/having_distinct_function.q.out
Testing done:
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=having_distinct_function.q -pl itests/qtest -Pitests
```
=> HIVE-23911: CBO fails when query has distinct in function and having clause

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/AtlasDumpTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/RangerDumpTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/RangerLoadTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/atlas/AtlasRestClientBuilder.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/atlas/AtlasRestClientImpl.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/atlas/RetryingClientTimeBased.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ranger/NoOpRangerRestClient.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ranger/RangerRestClient.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ranger/RangerRestClientImpl.java, ql/src/java/org/apache/hadoop/hive/ql/exec/util/Retryable.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/Utils.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/io/FileOperations.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/metric/MetricSink.java, ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestRangerDumpTask.java, ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestRangerLoadTask.java, ql/src/test/org/apache/hadoop/hive/ql/exec/repl/ranger/TestRangerRestClient.java, ql/src/test/org/apache/hadoop/hive/ql/exec/util/TestRetryable.java
=> HIVE-23897 : Create a common Retry Interface for replication

ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionInfo.java, ql/src/java/org/apache/hadoop/hive/ql/exec/HiveFunctionInfo.java, ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprFactory.java, ql/src/java/org/apache/hadoop/hive/ql/parse/type/ExprNodeDescExprFactory.java, ql/src/java/org/apache/hadoop/hive/ql/parse/type/FunctionHelper.java, ql/src/java/org/apache/hadoop/hive/ql/parse/type/HiveFunctionHelper.java, ql/src/java/org/apache/hadoop/hive/ql/parse/type/RexNodeExprFactory.java, ql/src/java/org/apache/hadoop/hive/ql/parse/type/TypeCheckProcFactory.java, ql/src/test/org/apache/hadoop/hive/ql/parse/type/TestBigIntCompareValidation.java
Part of the code has already been refactored to become database agnostic
(i.e. HiveFunctionHelper).
Further refactoring needs to be done on TypeCheckProcFactory which also
should be database agnostic.
The most interesting part of this code change involved the addition of
HiveFunctionInfo.  Previous to this commit, a query specific GenericUDF was
cloned out of the FunctionRegistry every time that the FunctionInfo.getGenericUDF()
was called. With this commit, a new query specific FunctionInfo (HiveFunctionInfo)
is created with the cloned GenericUDF.
For more details, please see …
=> HIVE-23941: Refactor TypeCheckProcFactory to be database agnostic

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
While using Nifi to stream data into Hive tables, it can happen that the newly created partitions have a different owner than the table itself. Running compaction on these partitions will fail with AccessControlException. 
Change compaction to use partition owner as base for proxy user.
=> HIVE-23929: Run compaction as partition owner

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MajorQueryCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MinorQueryCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMajorQueryCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMinorQueryCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
See HIVE-23966 for details.
Minor compaction results will have different file names.
Unit tests
=> HIVE-23966: Minor query-based compaction always results in delta dirs with minWriteId=1

ql/src/java/org/apache/hadoop/hive/ql/optimizer/topnkey/TopNKeyPushdownProcessor.java, ql/src/test/queries/clientpositive/topnkey_inner_join.q, ql/src/test/queries/clientpositive/topnkey_inner_join2.q, ql/src/test/results/clientpositive/llap/topnkey_inner_join.q.out, ql/src/test/results/clientpositive/llap/topnkey_inner_join2.q.out, ql/src/test/results/clientpositive/perf/tez/constraints/mv_query44.q.out, ql/src/test/results/clientpositive/perf/tez/constraints/query44.q.out, ql/src/test/results/clientpositive/perf/tez/constraints/query65.q.out, ql/src/test/results/clientpositive/perf/tez/constraints/query99.q.out
Followup for HIVE-23723. In HIVE-23723 we only check 1.) if join is a PK-FK join, 2.) FK side is not filtered, 3.) first n order by columns are originated from the FK side. It doesn't check if the order by columns actually match (including sort oder + null order) to columns used in the reduce output operator. This patch is intended to fix that.
=> HIVE-23937. Take null ordering into consideration when pushing TNK through inner joins (amagyar)

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java, ql/src/test/org/apache/hadoop/hive/ql/lockmgr/DbTxnManagerEndToEndTestBase.java, ql/src/test/queries/clientpositive/explain_locks.q, ql/src/test/results/clientpositive/llap/explain_locks.q.out
(cherry picked from commit 0e4b02af485cb1972ebc4f251d853c710e70164f)
test out fix
Pushed exclusive MERGE INSERT under the feature flag
Backward compatibility
new feature flag property was introduced 'hive.txn.xlock.mergeinsert'
TestDbTxnManager2
=> HIVE-24000: Put exclusive MERGE INSERT under the feature flag

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/Bug.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelDistribution.java
Avoid `UnsupportedOperationException` when calculating cost using `HiveOnTezCostModel`.
https://issues.apache.org/jira/browse/HIVE-23963?focusedCommentId=17169985&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17169985
See above section.
no
Run query 74 and 84 using a 30tb metastore dump:
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestTezPerfDBCliDriver -Dqfile=query74.q,query84.q -Dtest.metastore.db=postgres.tpcds -pl itests/qtest -Pitests
```
=> HIVE-23963: UnsupportedOperationException in queries 74 and 84 while applying HiveCardinalityPreservingJoinRule

ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommandsForMmTable.java
Hive reads insert-only tables truncated by Impala as if the truncation hadn't happened.
Yes, getAcidState will not filter out files with names beginning with "_empty"
Unit test
=> HIVE-24021: Read insert-only tables truncated by Impala correctly

ql/src/java/org/apache/hadoop/hive/ql/optimizer/ConstantPropagateProcFactory.java, ql/src/java/org/apache/hadoop/hive/ql/ppd/OpProcFactory.java
Logging in ConstantPropagateProcFactory
Make the logging in ConstantPropagateProcFactory more straightforward
No
No
=> HIVE-23997: Some logs in ConstantPropagateProcFactory are not straightforward

pom.xml
This PR aims to upgrade ORC to 1.5.10.
This will bring the latest bug fixes.
- [ORC-616 In Patched Base encoding, the value of headerThirdByte goes beyond the range of byte](https://issues.apache.org/jira/browse/ORC-616)
- [ORC-613 OrcMapredRecordReader mis-reuse struct object when actual children schema differs](https://issues.apache.org/jira/browse/ORC-613)
No.
Pass the CI with the existing UTs.
=> HIVE-24030: Upgrade ORC to 1.5.10

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientWithLocalCache.java
getAggrColStats API takes a long time to run in HMS. Adding it to the HS2 local cache can reduce the query compilation time significantly.
https://issues.apache.org/jira/browse/HIVE-24025
=> [HIVE-24025] Add getAggrColStatsFor to the HS2 local cache

common/src/java/org/apache/hadoop/hive/ql/log/PerfLogger.java, ql/pom.xml, ql/src/java/org/apache/hadoop/hive/ql/QueryDisplay.java
This PR proposes to shade Guava from hive-exec in Hive branch-2. This is basically for triggering test for #1356.
When trying to upgrade Guava in Spark, found the following error. A Guava method became package-private since Guava version 20. So there is incompatibility with Guava versions > 19.0.
```
sbt.ForkMain$ForkError: sbt.ForkMain$ForkError: java.lang.IllegalAccessError: tried to access method com.google.common.collect.Iterators.emptyIterator()Lcom/google/common/collect/UnmodifiableIterator; from class org.apache.hadoop.hive.ql.exec.FetchOperator
at org.apache.hadoop.hive.ql.exec.FetchOperator.<init>(FetchOperator.java:108)
at org.apache.hadoop.hive.ql.exec.FetchTask.initialize(FetchTask.java:87)
at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:541)
at …
```
=> HIVE-23980: Shade Guava from hive-exec in Hive branch-2

ql/src/java/org/apache/hadoop/hive/ql/io/parquet/ParquetRecordReaderBase.java, ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsNoJobTask.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommandsForMmTable.java
See HIVE-24023 for details.
Unit test
=> HIVE-24023: Hive parquet reader can't read files with length=0

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/DriverFactory.java, ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecuteLostAMQueryPlugin.java, ql/src/java/org/apache/hadoop/hive/ql/reexec/ReExecutionDagSubmitPlugin.java
DAG submission failure can also happen in environments where AM container died causing DNS issues. DAG submissions are safe to retry as the DAG hasn't started execution yet. There are retries at getSession and submitDAG level individually but some submitDAG failure has to retry getSession as well as AM could be unreachable, this can be handled in re-execution plugin. This PR adds a new re-execution plugin for intermittent DAG submission failures. 
To make hive resilient to environments with network/DNS issues.
Yes. Adds the re-exec plugin as default option.
Manually. Tez code was changed to explicitly throw UnknownHostException to simulate DNS/network issue and tested to make sure retry happens.
=> HIVE-24068: Add re-execution plugin for handling DAG submission and unmanaged AM failures

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java, streaming/src/java/org/apache/hive/streaming/AbstractRecordWriter.java
We need to keep info about the updated partition as well, and pass this to addDynamicPartitions. Here i am reusing addedParitions, as I don't see any effect on stats either. Reviewers please suggest if you think it can affect.
To fix automatic compaction in case of streaming ingest with dynamic partition.
No
Added unit-test.
=> HIVE-24020: Fix Automatic compaction for streaming ingest with dynamic partition

llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
https://issues.apache.org/jira/browse/HIVE-24061
Changes:
1. Adjust locality delay when the task is getting scheduled.
2. Reset locality delay when all nodes in the cluster are busy and wouldn't be able to schedule tasks.
3. Optimize schedulePendingTasks to exit early, when all nodes are busy. This helps in reducing lock contention as well.
Patch was tested on a medium scale cluster and observed good improvement in runtime of queries.
=> HIVE-24061: Improve llap task scheduling for better cache hit rate

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
Currently QB compaction runs as the session user, unlike MR compaction which runs as the table/partition directory owner (see CompactorThread#findUserToRunAs).
We should make QB compaction run as the table/partition directory owner and enable user impersonation during compaction to avoid any issues with temp directories.
=> HIVE-24089: Run QB compaction as table directory user with impersonation

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java
hive.debug.local.task was added in HIVE-1642. Even then, it was never used. It was possibly a leftover from development/debugging. There are no references to either HIVEDEBUGLOCALTASK or hive.debug.localtask in the codebase.
Change-Id: I27a385c264c362f6507eee4e29caf52f46e7dcba
=> HIVE-24093: Remove unused hive.debug.localtask

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHiveAuthorizerCheckInvocation.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/command/CommandAuthorizerV2.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java, ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/TestHiveMetaStoreAuthorizer.java
Apart from super users, normal users can create/alter/drop views via HMS
Even normal users can create/alter/drop views
No
On local cluster and Unit tests. New unit tests are added.
=> Spark client can create/alter/drop a view

ql/src/java/org/apache/hadoop/hive/ql/optimizer/SharedWorkOptimizer.java
SharedWorkOptimizer compares ReduceSinkOperators by comparing the operators' configs in ReduceSinkDesc but it doesn't check null sort order.
ReduceSinkOperators are considered to be equal if both operators has a ReduceSinkDesc object holding the same configuration. However null sort order was not checked during similarity check.
No.
Run SharedWorkOptimizer q tests.
=> [WIP]HIVE-23406: SharedWorkOptimizer should check nullSortOrders when comparing ReduceSink operators

ql/src/java/org/apache/hadoop/hive/ql/optimizer/correlation/ReduceSinkDeDuplicationUtils.java, ql/src/java/org/apache/hadoop/hive/ql/plan/ReduceSinkDesc.java, ql/src/test/queries/clientpositive/dynamic_semijoin_reduction_on_aggcol.q, ql/src/test/queries/clientpositive/reduce_deduplicate_null_keys.q, ql/src/test/results/clientpositive/llap/reduce_deduplicate_null_keys.q.out
Remove double backtracking of columns inside ReduceSinkDeDuplicationUtils#ggressiveDedup.
To prevent NPE during planning or execution. Examples in the JIRA case.
Changes in the EXPLAIN plans but probably for the best.
`mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=reduce_deduplicate_null_keys.q`
=> HIVE-24104: NPE due to null key columns in ReduceSink after deduplication

parser/src/java/org/apache/hadoop/hive/ql/parse/ASTNode.java, parser/src/test/org/apache/hadoop/hive/ql/parse/TestParseDriverIntervals.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/skewed/AlterTableSetSkewedLocationAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
1. Drop the defensive copy of children inside ASTNode#getChildren.
2. Protect clients by accidentally modifying the list via an
unmodifiable collection.
Profiling shows the vast majority of time spend on creating defensive
copies of the node expression list inside ASTNode#getChildren.
The method is called extensively from various places in the code
especially those walking over the expression tree so it needs to be
efficient.
Most of the time creating defensive copies is not necessary. For those
cases (if any) that the list needs to be modified clients should perform
a copy themselves.
No
The test was added in a separate branch since it is not meant to be committed upstream for the following reasons:
- the query for reproducing the problem takes up a few MBs
- requires some changes in the …
=> HIVE-24031: Infinite planning time on syntactically big queries

streaming/src/java/org/apache/hive/streaming/HiveStreamingConnection.java
There 3 HMS connections used by HiveStreamingConnection. One for TX one for hearbeat and for notifications. The close method only closes the first 2 leaving the last one open which eventually overloads HMS and it becomes unresponsive.
=> HIVE-24149. HiveStreamingConnection doesn't close HMS connection (amagyar)

ql/src/java/org/apache/hadoop/hive/ql/exec/OrcFileMergeOperator.java
Field Map<Integer, Writer> outWriters isn't cleared during operation close.
=> HIVE-24158: Cleanup isn't complete in OrcFileMergeOperator#closeOp

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionQueryBuilder.java
Keep the orc.bloom.filter during Query based compaction.
Fix the bug
No
Test added
=> HIVE-24162: Query based compaction looses bloom filter

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/Compiler.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java, ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientWithLocalCache.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java
This PR creates a query-level cache for HMS requests. The lifecycle of that cache is associated to the lifecycle of the query. This basically means that each unique request to certain HMS APIs should only be served once from HMS, while follow-up repetitive calls will be retrieved from cache. The initial implementation includes caching for 19 APIs.
This PR also extends existing local HS2 HMS cache implementation introduced in HIVE-23949 to support other requests (getTableColumnStatistics, getPartitionsByNames). In fact, implementation relies on some of the logic introduced in that JIRA since there are some commonalities.
This should improve compilation latency.
No.
=> HIVE-24176: Create query-level cache for HMS requests and extend existing local HS2 HMS cache

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
Check secure env before taking care of delegation tokens.
Broken kafka_storage_handler.q test after HIVE-23408
No
Tested with temporarily enabled qtest.
=> HIVE-24159: Kafka storage handler broken in secure environment pt2: short-circuit on non-secure environment

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnMr.java
Setting the execution engine as MR in the driver field (driver.getConf().setBoolVar(...)) only affects queries in setup and teardown.
Compaction runs using the conf field. So the execution engine needed to be set to MR in conf so that compaction would pick it up.
=> HIVE-24172: Fix TestMmCompactorOnMr

ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/like/CreateTableLikeOperation.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/create_like2.q, ql/src/test/results/clientpositive/llap/create_like2.q.out
Included check to skip TXN tblproperties for external table from MMM
CTLT is failing from MM to External
no
Using repro sql, included it as part of testcase.
=> HIVE-24188: CTLT from MM to External or External to MM are failing with hive.strict.managed.tables & hive.create.as.acid

Jenkinsfile, pom.xml
Enable precommit tests for github PR against branch-2.3.
Adding a new Jenkinsfile for the repo. This is almost the same file used in the master branch, except changing timeout from 6 to 12 hours.
No
N/A
=> HIVE-24035: Add Jenkinsfile for branch-2.3

llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/ShuffleHandler.java
Change-Id: Ia410f54c36821184bdfcd661152fc261da22cfac
LLAP's ShuffleHandler can return DISK_ERROR_EXCEPTION message in case of a fatal error.
It can improve shuffle's health by blaming map task earlier.
No.
It was tested on cluster by injecting some errors from code.
=> HIVE-24190: LLAP: ShuffleHandler might return DISK_ERROR_EXCEPTION according to TEZ-4233

ql/src/java/org/apache/hadoop/hive/ql/ddl/database/showcreate/ShowCreateDatabaseOperation.java, ql/src/test/queries/clientpositive/database_location.q, ql/src/test/results/clientpositive/llap/database_location.q.out
To add the missing managed location part to the SHOW CREATE DATABASE command.
Because it is missing from there, and the purpose of this command is to provide a statement that would create a database as similar as possible.
Users will see a better result for their SHOW CREATE DATABASE commands.
A new SHOW CREATE DATABASE was added into database_location.q.
=> HIVE-24178: Add managed location to SHOW CREATE DATABASE (Miklos Gergely)

ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/truncate/TruncateTableAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java, ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommandsForMmTable.java, ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java, ql/src/test/results/clientpositive/llap/acid_stats3.q.out, ql/src/test/results/clientpositive/llap/acid_stats5.q.out, ql/src/test/results/clientpositive/llap/check_constraint.q.out, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/StatsSetupConst.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreChecker.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java, storage-api/src/java/org/apache/hadoop/hive/common/AcidConstants.java, storage-api/src/java/org/apache/hadoop/hive/common/AcidMetaDataFile.java
Truncate table for transactional tables no longer deletes all the data, rather just creates an empty base dir.
Faster truncate, it can allow concurrent reads
No
Tests were added
=> HIVE-20137: truncate for transactional tables

common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelOptMaterializationValidator.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelShuttle.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveRelShuttleImpl.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveSubQueryRemoveRule.java, ql/src/test/queries/clientnegative/offset_in_subquery.q, ql/src/test/queries/clientpositive/subquery_join_rewrite.q, ql/src/test/results/clientnegative/offset_in_subquery.q.out, ql/src/test/results/clientpositive/llap/subquery_join_rewrite.q.out
* Fix incorrect result when subquey in exists contains limit.
* Error when query has a subquery with offset
* Fix correctness issue
```
create table web_sales (ws_order_number int, ws_warehouse_sk int) stored as orc;
insert into web_sales values
(1, 1),
(1, 2),
(2, 1),
(2, 2);
```
Query
```
select * from web_sales ws1
where exists (select 1 from web_sales ws2 where ws1.ws_order_number = ws2.ws_order_number limit 1);
```
should return 4 rows but returns only 2.
* Correctness can not be guaranteed if subquery has offset.
Semantic exception is thrown when user tries to execute a query which has a subquery with offset.
See `offset_in_subquery.q`
```
mvn test -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=subquery_join_rewrite.q -pl itests/qtest -Pitests -Dtest.output.overwrite
mvn …
```
=> HIVE-24199: Incorrect result when subquey in exists contains limit

llap-server/bin/runLlapDaemon.sh
Changed JVM opts to JDK11 compatible in runLlapDaemon.sh
Old options are not compatible with JDK11, and JVM fails to start.
Only expert user change, as gc logs will have a slightly different format with the change.
Tested on cluster.
=> HIVE-23938: LLAP: JDK11 - some GC log file rotation related jvm arguments cannot be used anymore

ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorGroupByOperator.java, ql/src/test/org/apache/hadoop/hive/ql/exec/vector/TestVectorGroupByOperator.java
https://issues.apache.org/jira/browse/HIVE-24234
Queries with grouping sets process input records multiple times and increases significantly the number hash aggregation lookup operations. When there is not significant reduction with aggregation, it becomes memory intensive and adds up to JVM mem pressure. 
Earlier, due to minor bug, it wasn't switching over to streaming mode. This has been fixed in the current patch and also takes care of the situation, when grouping sets are not very effective in reduction. 
Tried out Q67 in TPCDS in internal cluster which shows significant improvement with this.
For standalone tests, TestVectorGroupByOperator covers this.
=> HIVE-24234: Improve checkHashModeEfficiency in VectorGroupByOperator

ql/src/java/org/apache/hadoop/hive/ql/Executor.java
HiveHistory logs the task that ends abnormally.
When the task returns with the exitVal not equal to 0,  The Executor would skip marking the task return code and calling endTask.  This may make the history log incomplete for such tasks.
No
=> HIVE-24069: HiveHistory should log the task that ends abnormally

ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java, ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java
in HDFS environment if a writer is using hflush to write ORC ACID files during a transaction commit, the results might be seen as missing when reading the table before this file is completely persisted to disk (thus synced)
This is due to hflush not persisting the new buffers to disk, it rather just ensures that new readers can see the new content. This causes the block information to be incomplete, on which BISplitStrategy relies on. Although the side file (_flush_length) tracks the proper end of the file that is being written, this information is neglected in the favour of block information, and we may end up generating a very short split instead of the larger, available length.
When ETLSplitStrategy is used there is not even a try to rely on ACID side file when calculating file length, …
=> HIVE-24266

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Resolve the table again after compaction is finished; compare the id with the table id from when compaction began. If the ids do not match, abort the compaction's transaction.
Manual tests
=> HIVE-24235: Drop and recreate table during MR compaction leaves behind base/delta directory

ql/src/java/org/apache/hadoop/hive/ql/Driver.java
Driver is still a huge class, with a lot of methods. They are not representing the order of the process done by the Driver (compilation, execution, result providing, closing). Also the constructors are not at the beginning of the class. All of these make the class harder to read. By re-ordering them it would be easier.
To make the Driver class cleaner, thus easier to read/understand.
No.
All the tests are still passing.
=> HIVE-24184: Re-order methods in Driver (Miklos Gergely)

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
There is unquoted column name NWI_TABLE in one of the SQL queries which executed during REPL LOAD.
This causes the command to fail when Postgres is used for metastore.
=> HIVE-24256: quote NWI_TABLE column in TxnHandler

llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCacheImpl.java, llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelCacheImpl.java
bugfix
If multiple threads put the same buffer to the cache, only one succeeds. The other one detects this, and replaces its own buffer. This is marked by a bit mask encoded in a long, where the collided buffers are marked with a 1. By shifting the integer 1, it can happen that due to an overflow some buffers will not be removed after a collision, and the reference count decreases below zero, which is not a valid state.
No
=> HIVE-24293: Integer overflow in llap collision mask

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/test/queries/clientpositive/acid_vectorization_original_tez.q, ql/src/test/queries/clientpositive/avro_nullable_fields.q, ql/src/test/queries/clientpositive/llap_text.q, ql/src/test/queries/clientpositive/metadata_only_queries.q, ql/src/test/queries/clientpositive/metadata_only_queries_with_filters.q, ql/src/test/queries/clientpositive/orc_llap_counters.q, ql/src/test/queries/clientpositive/orc_llap_counters1.q, ql/src/test/queries/clientpositive/vector_binary_join_groupby.q, ql/src/test/queries/clientpositive/vector_windowing_multipartitioning.q, ql/src/test/queries/clientpositive/vector_windowing_navfn.q, ql/src/test/queries/clientpositive/windowing_distinct.q, ql/src/test/queries/clientpositive/windowing_multipartitioning.q, ql/src/test/queries/clientpositive/windowing_navfn.q, ql/src/test/results/clientpositive/llap/avro_nullable_fields.q.out, ql/src/test/results/clientpositive/llap/llap_text.q.out, ql/src/test/results/clientpositive/llap/metadata_only_queries.q.out, ql/src/test/results/clientpositive/llap/metadata_only_queries_with_filters.q.out, ql/src/test/results/clientpositive/llap/orc_llap_counters.q.out, ql/src/test/results/clientpositive/llap/orc_llap_counters1.q.out, ql/src/test/results/clientpositive/llap/vector_binary_join_groupby.q.out, ql/src/test/results/clientpositive/llap/vector_windowing_multipartitioning.q.out, ql/src/test/results/clientpositive/llap/vector_windowing_navfn.q.out, ql/src/test/results/clientpositive/llap/windowing_distinct.q.out, ql/src/test/results/clientpositive/llap/windowing_multipartitioning.q.out, ql/src/test/results/clientpositive/llap/windowing_navfn.q.out, ql/src/test/results/clientpositive/tez/acid_vectorization_original_tez.q.out, serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazyBinary.java, serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazySerDeParameters.java, serde/src/java/org/apache/hadoop/hive/serde2/lazy/fast/LazySimpleDeserializeRead.java
Updated the LazySimple SerDe to no longer attempt to auto-detect if Binary columns were Base64 and instead use a table property. The previous way this was done was expensive and did not correctly check if the values were valid Base64 which in niche cases could result in statistics being computed incorrectly.
=> HIVE-23829: Compute Stats Incorrect for Binary Columns

llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCacheImpl.java, llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelCacheImpl.java
HIVE-23741 introduced an optimization so that CacheTags are not stored on buffer level, but rather on file level, as one cache tag can only relate to one file. With this change a buffer->filecache reference was introduced so that the buffer's tag can be calculated with an extra indirection i.e. buffer.filecache.tag.
However during buffer collision in putFileData method, we don't set the filecache reference of the collided (new) buffer: https://github.com/apache/hive/commit/2e18a7408a8dd49beecad8d66bfe054b7dc474da#diff-d2ccd7cf3042845a0812a5e118f82db49253d82fc86449ffa408903bf434fb6dR309-R311
Later this cases NPE when the new (instantly decRef'ed) buffer is evicted.
=> HIVE-24297

Jenkinsfile
Two changes combined in this PR:
- backport [HIVE-23323](https://issues.apache.org/jira/browse/HIVE-23323) to enable better parallelism for qtests
- Add Jenkinsfile
Without a Jenkinsfile we won't trigger CI for new PRs against the branch-3.1. This allows ppl to test their code.
No
Existing tests
=> HIVE-24331: Add Jenkinsfile for branch-3.1

ql/src/java/org/apache/hadoop/hive/ql/io/merge/MergeFileTask.java
Hi, we find that MapReduce's file merge map containers will download user's extra resources(such as: added jars, files, archives) before launching task. When these resources are large or the network is busy, file merge jobs will be timeout, causing the query be failed. As we all know, file merge task will run correctly just with hive-exec.jar and MapReduce framework. Therefore, there is no need to download user's resources. The patch below prevents setting `tmpjars` for FileMerge Task.
Remove `tmpjars` for `MergeFileTask`.
For queries with some large jars, it's unnecessary for `MergeFileTask` to download extra resources and when the network is not good, containers might be time-out.
No
It has been tested in our product env.
=> HIVE-23685: Removing user's extra resources while executing File Merge Task

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java
If the Cleaner didn't remove any files, don't mark the compaction queue entry as "succeeded" but instead leave it in "ready for cleaning" state for later cleaning. If it removed at least one, then the compaction queue entry as "succeeded".
=> HIVE-24314: compactor.Cleaner should not set state mark cleaned if it didn't remove any files

pom.xml
This PR aims to upgrade Apache ORC from 1.5.6 to 1.5.8.
This will bring eleven bug fixes.
- ORC 1.5.7: https://issues.apache.org/jira/projects/ORC/versions/12345702
- ORC 1.5.8: https://issues.apache.org/jira/projects/ORC/versions/12346462
No.
Pass the CI with the existing test cases.
=> HIVE-24316. Upgrade ORC from 1.5.6 to 1.5.8 in branch-3.1

ql/src/test/results/clientnegative/avro_decimal.q.out, serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroDeserializer.java, serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerdeUtils.java, serde/src/java/org/apache/hadoop/hive/serde2/avro/SchemaToTypeInfo.java
This mainly replace `JsonProperties.getJsonProp` with `JsonProperties.getObjectProp`. 
Note that there's one place in `SchemaToTypeInfo` where we explicitly call `getIntValue` to forbid string as precision/scale values (see [HIVE-7174](https://issues.apache.org/jira/browse/HIVE-7174)). To retain the old behavior, we check if the returned object is integer type, and if not, return a default 0 following `JsonNode` implementation.
`JsonProperties#getJsonProp` has been marked as deprecated in Avro 1.8 and removed since Avro 1.9. This replaces the API usage for this with `getObjectProp` which doesn't leak Json node from jackson. This will help downstream apps to depend on Hive while using higher version of Avro, and also help Hive to upgrade Avro version itself.
No
=> HIVE-24324: Remove deprecated API usage from Avro

shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
https://issues.apache.org/jira/browse/HIVE-24342
if the path is hdfs and if the fs is mounted fs, then we will use resolvePath to recheck whether the path is really on hdfs. In the case ViewFS based file systems, the target fs could be on some other fs, ex: o3fs://
This is needed for supporting ViewHDFS like functionality as it supported mounting other fs-es under hdfs paths.
No
This has been tested in real cluster installation with mounting to o3fs paths. The JIRA description provided the details about verification. After this fix, querying from table succeeded.
=> HIVE-24342: isPathEncrypted should make sure resolved path also from HDFS.

ql/src/java/org/apache/hadoop/hive/ql/ddl/table/lock/show/ShowDbLocksAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/lock/show/ShowLocksAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java
1. Avoid multiple shutdown hooks for the same threadpool in DbTxnManager
2. Close new HiveTxnManager in ShowLocksAnalyzer to release resources
Avoid the memory leak when executing `SHOW LOCKS` statements and simplify code.
No
`mvn test -pl itests/hive-unit -Dtest=TestDbTxnManagerMemoryLeak -Pitests`
If it finishes then there is no memory leak, otherwise most of the time you get an OutOfMemoryError. 
See the JIRA case for more details.
**The commit with the test is not meant to be merged into master**
=> HIVE-24179: Memory leak in HS2 DbTxnManager when compiling SHOW LOCKS statement

hbase-handler/pom.xml, pom.xml
This backports [HIVE-19662](https://issues.apache.org/jira/browse/HIVE-19662) to branch-2.3, which bumps Avro version from 1.7.7 to 1.8.2. 
In order to backport HIVE-24324 to branch-2.3 to remove deprecated Avro API usage so that downstream applications (such as Apache Spark) who depend on Hive 2.3.x can upgrade their Avro version, we'll need to first backport HIVE-19662 and bump Avro version in branch-2.3 first as it is currently on 1.7.x, while HIVE-24324 requires Avro 1.8.x.
No
=> HIVE-24379: Backport HIVE-19662 to branch-2.3

ql/src/java/org/apache/hadoop/hive/ql/metadata/Table.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
- `Table.checkValidity` should use `getDeserializer` instead of `getDeserializerFromMetaStore`. This will use the cached version of the Deserializer so it will prevent creating a new one.
- `SemanticAnalyzer.genConversionSelectOperator` should get a `Deserializer` as an input parameter, since we already has that at hand
- When we are generating the FileSinkPlan on an destination table, we should reuse the table deserializer to get the columns whenever it is possible
To speed up query planning
No
Unit tests
=> HIVE-24399: Optimize Deserializer creation

itests/qtest/pom.xml, jdbc/pom.xml, pom.xml, ql/pom.xml
https://issues.apache.org/jira/browse/HIVE-24138
=> HIVE-24138. Llap external client flow is broken due to netty shading.

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/Optimizer.java
The lineage information is not populated unless certain hooks are enabled.
However, this is a bit fragile, and no way for another hook that we write to get this information. This proposes a flag to enable this instead.
=> HIVE-24051 : Hive lineage information exposed in ExecuteWithHookContext

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/test/queries/clientpositive/create_view_when_mv_exists.q, ql/src/test/results/clientpositive/llap/create_view_when_mv_exists.q.out
Disable materialized view rewrite at view creation.
Hive doesn't support view creation when one of the source tables is a materialized view. When the `create view` command is executed the select statement is compiled and the optimizer applies materialized view rewrites if any suitable materialized view exists. A successful rewrite leads to Exception:
```
org.apache.hadoop.hive.ql.parse.SemanticException: View definition references materialized view default.mv1
```
See the jira for full stacktrace.
Users can create views even if its query is matching with an existing materialized view query. No SemanticException should be thrown because of that.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=create_view_when_mv_exists.q -pl itests/qtest …
```
=> HIVE-24249: Create View fails if a materialized view exists with the same query

hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java
=> HIVE-24424: Use PreparedStatements in DbNotificationListener getNextNLId

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, llap-client/src/java/org/apache/hadoop/hive/llap/tezplugins/helpers/LlapTaskUmbilicalServer.java, llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskCommunicator.java
https://issues.apache.org/jira/browse/HIVE-24426
=> HIVE-24426. Spark job fails with fixed LlapTaskUmbilicalServer port.

common/src/java/org/apache/hadoop/hive/ql/log/PerfLogger.java, itests/hive-blobstore/pom.xml, itests/hive-unit/pom.xml, itests/qtest-accumulo/pom.xml, itests/qtest-spark/pom.xml, ql/pom.xml, ql/src/java/org/apache/hadoop/hive/ql/QueryDisplay.java
This PR proposes to shade Guava from hive-exec in Hive 2.3 branch.
When trying to upgrade Guava in Spark, found the following error. A Guava method became package-private since Guava version 20. So there is incompatibility with Guava versions > 19.0.
```
sbt.ForkMain$ForkError: sbt.ForkMain$ForkError: java.lang.IllegalAccessError: tried to access method com.google.common.collect.Iterators.emptyIterator()Lcom/google/common/collect/UnmodifiableIterator; from class org.apache.hadoop.hive.ql.exec.FetchOperator
at org.apache.hadoop.hive.ql.exec.FetchOperator.<init>(FetchOperator.java:108)
at org.apache.hadoop.hive.ql.exec.FetchTask.initialize(FetchTask.java:87)
at org.apache.hadoop.hive.ql.Driver.compile(Driver.java:541)
at org.apache.hadoop.hive.ql.Driver.compileInternal(Driver.java:1317)
at …
```
=> HIVE-23980: Shade Guava from hive-exec in Hive 2.3

serde/src/java/org/apache/hadoop/hive/serde2/avro/TypeInfoToSchema.java
This pr replace `null` with `JsonProperties.NULL_VALUE` to fix compatibility issue:
1. java.lang.NoSuchMethodError: 'void org.apache.avro.Schema$Field.<init>(java.lang.String, org.apache.avro.Schema, java.lang.String, org.codehaus.jackson.JsonNode)'
```
- create hive serde table with Catalog
*** RUN ABORTED ***
java.lang.NoSuchMethodError: 'void org.apache.avro.Schema$Field.<init>(java.lang.String, org.apache.avro.Schema, 
java.lang.String, org.codehaus.jackson.JsonNode)'
at org.apache.hadoop.hive.serde2.avro.TypeInfoToSchema.createAvroField(TypeInfoToSchema.java:76)
at org.apache.hadoop.hive.serde2.avro.TypeInfoToSchema.convert(TypeInfoToSchema.java:61)
at org.apache.hadoop.hive.serde2.avro.AvroSerDe.getSchemaFromCols(AvroSerDe.java:170)
at …
```
=> HIVE-24436: Fix Avro NULL_DEFAULT_VALUE compatibility issue

ql/src/java/org/apache/hadoop/hive/ql/Driver.java, ql/src/java/org/apache/hadoop/hive/ql/DriverContext.java
The Driver class has some very long methods, they are now having a more manageable size. Also some minor checkstyle errors were fixed in some Driver associated classes
To make the Driver class more understandable.
No.
All the tests are still running.
=> HIVE-24333 Cut long methods in Driver to smaller, more manageable pieces (Miklos Gergely)

metastore/pom.xml, packaging/src/main/assembly/bin.xml, pom.xml, ql/pom.xml, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
HIVE-17234 has removed HBase metastore from master. But maven dependency have not been removed. We should remove it.
Reduce dependency to make Spark dependency more clear:
https://github.com/apache/spark/blob/3ce4ab545bfc28db7df2c559726b887b0c8c33b7/pom.xml#L1997-L2007
No.
N/A
=> HIVE-21588: Remove HBase dependency from hive-metastore

standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/PostgresTPCDS.java
Update docker metastore version to zabetak/postgres-tpcds-metastore:1.3
on which some cleanup was performed to remove stale entries in various
tables including MIN_HISTORY_LEVEL.
See https://github.com/zabetak/hive-postgres-metastore/commit/04be88888bd2e9400d7ae604a4112aaa4531dd36
To fix test failures while running `TestTezTPCDS30TBPerfCliDriver` tests. More details in the JIRA.
No
`mvn test -Dtest=TestTezTPCDS30TBPerfCliDriver`
=> HIVE-24489: TPC-DS dockerized tests fail due to stale entries in MIN_HISTORY_LEVEL metastore table

ql/src/java/org/apache/hadoop/hive/ql/io/orc/FixAcidKeyIndex.java, ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestFixAcidKeyIndex.java
Change-Id: I6b9f501f2804aa5c71ee03cadcea3ec24fdd6005
There is a utility in hive which can validate/fix corrupted hive.acid.key.index.
hive --service fixacidkeyindex
Unfortunately it is only tailored for a specific problem (https://issues.apache.org/jira/browse/HIVE-18907), instead of generally validating and recovering the hive.acid.key.index from the stripe data itself.
The PR generalize the validation/recovery by checking/rebuilding the hive.acid.key.index from the data itself.
The name fixacidkeyindex suggests that this is a general validation/fixer tool for the index.
hiveconf params can now be specified to the tool, to minimize the diff in the recovered file. (E.g: --hiveconf hive.exec.orc.default.block.padding=false)
Unit test and manual testing.
=> HIVE-24475: Generalize fixacidkeyindex utility

packaging/src/main/assembly/bin.xml
This proposes to exclude calcite in packaging to avoid conflicting with shaded calcite in ql.
The issue is similar to HIVE-23593. In 2.3.8 RC, ql already has a shaded calcite, but we see such error:
Caused by: java.lang.NoSuchMethodError: org.apache.calcite.rel.RelCollationImpl.<init>(Lorg/apache/hive/com/google/common/collect/ImmutableList;)V
at org.apache.hadoop.hive.ql.optimizer.calcite.HiveRelCollation.<init>(HiveRelCollation.java:29)
at org.apache.hadoop.hive.ql.optimizer.calcite.RelOptHiveTable.getCollationList(RelOptHiveTable.java:181)
at org.apache.calcite.rel.metadata.RelMdCollation.table(RelMdCollation.java:175)
We find in 2.3.8 binary distribution, there are calcite jars:
calcite-core-1.10.0.jar
calcite-druid-1.10.0.jar
calcite-linq4j-1.10.0.jar
We need to exclude calcite in …
=> HIVE-24512. Exclude calcite in packaging

ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorBytesCountDistinct.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorCountDistinct.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorDecimalCountDistinct.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorDoubleCountDistinct.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorLongCountDistinct.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorTimestampCountDistinct.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java, ql/src/java/org/apache/hadoop/hive/ql/plan/VectorPTFDesc.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFCount.java, ql/src/test/queries/clientpositive/vector_ptf_count_distinct.q, ql/src/test/results/clientpositive/llap/vector_ptf_count_distinct.q.out
Implements vectorized count(distinct txt1) over(partition by txt1), so a distinct count. Currently, this is not supported, and silently falls back to non-distinct which leads to wrong result.
Qtests are included.
=> HIVE-24245: Vectorized PTF with count and distinct over partition producing incorrect results.

ql/src/java/org/apache/hadoop/hive/ql/io/arrow/Serializer.java, ql/src/test/org/apache/hadoop/hive/ql/io/arrow/TestSerializer.java
Use an empty batch to generate the schema for the empty results
Clients expect the full schema even for empty results
No
Unit and other test
=> HIVE-24504: VectorFileSinkArrowOperator does not serialize complex types correctly

itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniTezCliDriver.java, ql/src/java/org/apache/hadoop/hive/ql/exec/LimitOperator.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorLimitOperator.java, ql/src/test/org/apache/hadoop/hive/ql/exec/TestLimitOperator.java, ql/src/test/org/apache/hadoop/hive/ql/exec/vector/TestVectorLimitOperator.java, ql/src/test/org/apache/hadoop/hive/ql/exec/vector/util/FakeVectorRowBatchFromObjectIterables.java, ql/src/test/queries/clientpositive/authorization_view_1.q, ql/src/test/queries/clientpositive/authorization_view_disable_cbo_1.q, ql/src/test/queries/clientpositive/input14_limit.q, ql/src/test/results/clientpositive/llap/authorization_view_1.q.out, ql/src/test/results/clientpositive/llap/authorization_view_disable_cbo_1.q.out
Change-Id: I12d2719acdf80ffa3a5c14b1c3fce2d4cbe00911
Using an object cache, LimitOperator/VectorLimitOperator/TezProcessor can exit quickly if a limit is already reached. 
Performance benefit.
No.
Tested on cluster.
=> HIVE-24207: LimitOperator can leverage ObjectCache to bail out quickly

standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/DatabaseRule.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Derby.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mssql.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Mysql.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Oracle.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/Postgres.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/dbinstall/rules/PostgresTPCDS.java
bugfixes:
* force remove the container prior to starting the test
* also remove the volume on deletion (tpcds30tb left a ~600M garbage volume behind on each run)
additions:
* add option to enable specifying the docker host address (enables to run them from hive-dev-box containers)
* container name suffix support (needed to possibly run multiple instance of the same test at the same time)
=> HIVE-24488: Make tests using docker more comfortable

common/src/java/org/apache/hive/common/util/CleanerUtil.java, llap-server/src/java/org/apache/hadoop/hive/llap/cache/SimpleAllocator.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/encoded/EncodedReaderImpl.java
This is a port of HADOOP-12760 into hive codebase for JDK9+ compatibility.
We need to support JDK9+ runtime for hive.
No.
It's being tested on cluster.
=> HIVE-17709: remove sun.misc.Cleaner references

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreMethods.java
Recursive call in a method that leads to Stack overflow. get_partitions_by_names(final String dbName, final String tblName, final List<String> partNames) is deprecated and is not getting used from HS2. Fixing the recursion in case older HMS clients call this method. 
No
Unit test added to ensure Stackoverflow does not happen.
=> Fix recursive call

common/pom.xml, common/src/java/org/apache/hadoop/hive/common/log/InPlaceUpdate.java, llap-common/pom.xml, llap-common/src/java/org/apache/hadoop/hive/llap/AsyncPbRpcProxy.java, llap-server/pom.xml, llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/AMReporter.java, llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapTaskReporter.java, llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskExecutorService.java, llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/WorkloadManager.java, ql/src/test/org/apache/hadoop/hive/ql/exec/tez/SampleTezSessionState.java, standalone-metastore/metastore-tools/tools-common/pom.xml, storage-api/pom.xml
=> HIVE-24542: Prepare Guava for Upgrades

Jenkinsfile, pom.xml, ql/pom.xml
This includes `calcite-core`'s transitive dependencies:
- net.hydromatic:eigenbase-properties
- org.codehaus.janino:janino
- org.codehaus.janino:commons-compiler
- org.pentaho:pentaho-aggdesigner-algorithm
in the fat `hive-exec` jar. 
Currently as part of effort of shading Guava from Hive, we shade Calcite and exclude all its artifacts from the binary distribution. However, this also removes all its transitive dependencies which will still needed at runtime. Without these, Hive queries will fail with error like:
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/eigenbase/util/property/BooleanProperty
at org.apache.calcite.util.SaffronProperties.<init>(SaffronProperties.java:66)
at org.apache.calcite.util.SaffronProperties.instance(SaffronProperties.java:134)
at …
```
=> HIVE-24551: Hive should include transitive dependencies from calcite after shading it

ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/acid_vectorization_original.q
When collecting identifiers to expanded query text Convert replacement text to lower case when adding it to `UnparseTranslator`.
Virtual column identifiers like `ROW__ID` are converted to lower case when added to `UnparseTranslator` except when the query contains joins.
```
select o1.ROW__ID r1, o1.* from over10k_orc o1 join over10k_orc o2
on o1.ROW__ID.rowid == o2.ROW__ID.rowid and o1.ROW__ID.writeid == o2.ROW__ID.writeid and o1.ROW__ID.bucketid == o2.ROW__ID.bucketid;
```
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=acid_vectorization_original.q -pl itests/qtest -Pitests
```
=> HIVE-24547: Fix acid_vectorization_original

beeline/pom.xml, hcatalog/core/pom.xml, hcatalog/hcatalog-pig-adapter/pom.xml, hcatalog/server-extensions/pom.xml, hcatalog/webhcat/java-client/pom.xml, itests/hive-minikdc/pom.xml, itests/hive-unit-hadoop2/pom.xml, itests/hive-unit/pom.xml, itests/qtest-accumulo/pom.xml, itests/util/pom.xml, service/pom.xml
This patch proposes to exclude calcite dependencies from test-jar dependency of `hive-exec`.
The test "org.apache.hive.beeline.cli.TestHiveCli - testSetHeaderValue" we found the exception:
```
Caused by: java.lang.NoSuchMethodError: org.apache.calcite.rel.RelCollationImpl.<init>(Lorg/apache/hive/com/google/common/collect/ImmutableList;)V
at org.apache.hadoop.hive.ql.optimizer.calcite.HiveRelCollation.<init>(HiveRelCollation.java:29) ~[hive-exec-2.3.8.jar:2.3.8]
at org.apache.hadoop.hive.ql.optimizer.calcite.RelOptHiveTable.getCollationList(RelOptHiveTable.java:181) ~[hive-exec-2.3.8.jar:2.3.8]
at org.apache.calcite.rel.metadata.RelMdCollation.table(RelMdCollation.java:175) ~[calcite-core-1.10.0.jar:1.10.0]
at org.apache.calcite.rel.metadata.RelMdCollation.collations(RelMdCollation.java:122 …
```
=> HIVE-24553. Exclude calcite from test-jar dependency of hive-exec

ql/src/java/org/apache/hadoop/hive/ql/ddl/table/constraint/drop/AlterTableDropConstraintAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/constraint/drop/AlterTableDropConstraintDesc.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java, ql/src/test/results/clientnegative/drop_invalid_constraint2.q.out, ql/src/test/results/clientpositive/llap/default_constraint.q.out
Advance write ID during drop constraint
To server consistent metadata from HS2 cache
No
Added new tests
=> HIVE-24513: Advance write ID during drop constraint

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
Close metastore connection when CompactionHeartbeater is destoyed
No
=> HIVE-24548: CompactionHeartbeater leaks metastore connection

ql/src/java/org/apache/hadoop/hive/ql/lib/DefaultGraphWalker.java
Change-Id: I9390db2b356b7f36f906b2ab3214e4975984108a
=> HIVE-24556: Optimize DefaultGraphWalker for case with no grandchild

ql/src/test/org/apache/hadoop/hive/ql/security/authorization/plugin/TestHivePrivilegeObjectOwnerNameAndType.java
This change modifies the test TestHivePrivilegeObjectOwnerNameAndType in the hope that it will reduce the intermittent failures that I saw on my unrelated PR. The full trace of the failure is available in the JIRA.
Deflake the test.
No
Ran the modified test locally.
=> HIVE-24562: Deflake TestHivePrivilegeObjectOwnerNameAndType

itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/SharedCache.java
This PR modifies the test TestCachedStoreUpdateUsingEvents to not use "file:/tmp" which is error prone since clean up method can delete all the files in /tmp. Also fixes a harmless NPE which unnecessarily spams the log file.
I observed this test to be failing on a unrelated PR. I am hoping that these changes will help remove any flakiness if present.
No
Ran the test locally.
=> HIVE-24561: Deflake TestCachedStoreUpdateUsingEvents test

ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
ParseDriver pd = new ParseDriver() 
This code is redundant code, it is recommended to delete it
=> HIVE-24571: Redundant code in SemanticAnalyzer.java file

ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMaterializedViewsRegistry.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveRelOptMaterialization.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Materialization.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/MaterializedViewsCache.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewUtils.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CBOPlan.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java, ql/src/test/org/apache/hadoop/hive/ql/metadata/TestMaterializedViewsCache.java, ql/src/test/queries/clientpositive/materialized_view_rewrite_11.q, ql/src/test/results/clientpositive/llap/materialized_view_rewrite_11.q.out
1. Store the scope of each materialized view in the cache/registry. It specifies whether the MV can be used in both Calcite and Sql text based query rewrites or Sql text based only.
2. Scope value is calculated when the MV definition is parsed during adding the MV to the Registry.
Number of Materialized views added to the Calcite based rewrite planner affects query compilation performance. Too much view definition increases the planning time without any benefit. There are plan patterns which are not supported by the planner. MV having such patterns in its definition can be filtered out before even added to the planner.
No.
```
mvn test -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_rewrite_11.q -pl itests/qtest -Pitests
```
=> HIVE-24434: Filter out materialized views for rewriting if plan pattern is not allowed

ql/src/java/org/apache/hadoop/hive/ql/io/avro/AvroGenericRecordReader.java
=> HIVE-24587: DataFileReader is not closed in AvroGenericRecordReader#extractWriterProlepticFromMetadata

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, itests/src/test/resources/testconfiguration.properties, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/StorageFormat.java, ql/src/test/queries/clientpositive/default_storage_handler.q, ql/src/test/results/clientpositive/default_storage_handler.q.out
Add new config option to set a default storage handler class. If this config is set to a valid, existing class, the storage handler class won't have to be explicitly provided in the create table statement with the `STORED BY `clause, but will be 'inserted' under the hood.
For example, if `hive.default.storage.handler.class=org.apache.iceberg.mr.hive.HiveIcebergStorageHandler` is set,
then the command `CREATE TABLE abc (a int, b string) LOCATION ...` will be equivalent to 
`CREATE TABLE abc (a int, b string) STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler' LOCATION ...`
In order to use existing create table commands for new table formats, such as Iceberg, without modification.
new config option settable via beeline/hive-site
q tests + manually with local run
=> HIVE-24541: add config option for default storage handler class

ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
NPE is thrown if LLAP mode is turned on and LLAP daemon executes a query on an ACID table if LLAP IO is disabled. Although this doesn't seem to be a very useful LLAP environment setup, we'll need to cover this edge case too.
=> HIVE-24585

itests/hive-unit/src/test/java/org/apache/hive/jdbc/miniHS2/TestHiveServer2Acid.java, ql/src/java/org/apache/hadoop/hive/ql/Driver.java, ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java, ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java, ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DummyTxnManager.java, ql/src/java/org/apache/hadoop/hive/ql/lockmgr/HiveTxnManager.java
Driver should only cleanup transactionmanager if it is still processing the same query.
No.
New unit test.
=> HIVE-24550: Cleanup only transaction information for the current DriverContext

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, llap-client/src/java/org/apache/hadoop/hive/llap/io/api/LlapIo.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapInputFormat.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapRecordReader.java, ql/src/java/org/apache/hadoop/hive/ql/io/AcidInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java, ql/src/java/org/apache/hadoop/hive/ql/io/sarg/ConvertAstToSearchArg.java, ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java, ql/src/test/org/apache/hadoop/hive/ql/io/sarg/TestSearchArgumentImpl.java
Changes:
- Added new method in LLAP IO API so that a cached LLAP record reader can be created for arbitrary files
- Made ColumnizedDeleteEventRegistry make use of this when LLAP is available and the feature is turned on
- Removed some unnecessary / inefficient code parts in LlapInputFormat and AcidInputFormat
Functional testing: existing testing already covers this change:
- TestVectorizedOrcAcidRowBatchReader unit test covers the code paths of this change when the feature is off (no LLAP present)
- TestMiniLlapCliDriver/acid_direct_update_delete.q qtest covers the code paths where LLAP is present and ACID delete deltas are cached into LLAP IO (since the feature flag is by default turned on)
Performance testing: used S3 to see performance gains on a small (6 rows) table read that had ~20 …
=> HIVE-24337: Cache delete delta files in LLAP cache

spark-client/src/main/java/org/apache/hive/spark/client/AbstractSparkClient.java
delete spark tmp files when spark driver exit
if not change, tmp files only delete when hiveserver jvm exit, and tmp files may too large
test in my cluster
=> HIVE-24570 Hive on spark tmp file should be delete when driver process finished

ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
Automatic compaction initiation stops if compaction fails for a given partition two consecutive time. The Initiator should retry after some time elapses.
Compaction not running for a table / partition can have serious performance impact
No.
Added unittest.
=> HIVE-24602: Retry compaction after configured time

ql/src/java/org/apache/hadoop/hive/ql/hooks/PostExecOrcFileDump.java, ql/src/java/org/apache/hadoop/hive/ql/io/AcidDirectory.java, ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java, ql/src/java/org/apache/hadoop/hive/ql/io/HdfsUtils.java, ql/src/java/org/apache/hadoop/hive/ql/io/OriginalDirectory.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java, ql/src/test/org/apache/hadoop/hive/ql/io/TestAcidInputFormat.java, ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java, ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestVectorizedOrcAcidRowBatchReader.java
- Remove unneccessary AcidUtils.getAcidState call from OrcInputformat when the table is not transactional
- Remove redundant filesystem utility functions from AcidUtils to HdfsUtils
Make the code more readable
No
Current unit tests.
=> HIVE-24581: Remove AcidUtils call from OrcInputformat for non transactional tables

ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java, ql/src/test/queries/clientpositive/comma_in_column_name.q, ql/src/test/results/clientpositive/llap/comma_in_column_name.q.out
OrcInputFormat  getDesiredRowTypeDescr method should use column delimiter to generate column names.
Current logic can create wrong names when column names contain commas.
no
q file
=> HIVE-24539: OrcInputFormat schema generation should respect column delimiter

testutils/pom.xml, testutils/src/java/org/apache/hive/testutils/junit/extensions/Log4jConfig.java, testutils/src/java/org/apache/hive/testutils/junit/extensions/Log4jConfigExtension.java, testutils/src/test/java/org/apache/hive/testutils/junit/extensions/TestLog4jConfigExtension.java, testutils/src/test/resources/test0-log4j2.properties, testutils/src/test/resources/test1-log4j2.properties
Add new Junit Jupiter annotation/extension.
Run easily unit tests using a specific log4j configuration with minimal side-effects.
No
`mvn test -pl testutils -Dtest=TestLog4jConfigExtension`
=> HIVE-24588: Run tests using specific log4j2 configuration conveniently

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, metastore/scripts/upgrade/hive/hive-schema-4.0.0.hive.sql, metastore/scripts/upgrade/hive/upgrade-3.1.0-to-4.0.0.hive.sql, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java, ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java, ql/src/test/org/apache/hadoop/hive/ql/TxnCommandsBaseForTests.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtilities.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/conf/TestMetastoreConf.java
Rename compaction 'attempted' status to 'did not initiate'
See HIVE-24587.
Show compactions and sys.COMPACTIONS tables will list "attempted" status as "did not initiate" now.
Unit test for case of initiator failure.
=> HIVE-24586: Rename compaction 'attempted' status

ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/AnnotateWithStatistics.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java, ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java, ql/src/test/queries/clientpositive/annotate_stats_lateral_view_join.q, ql/src/test/results/clientnegative/udf_assert_true.q.out, ql/src/test/results/clientnegative/udf_assert_true2.q.out, ql/src/test/results/clientpositive/llap/annotate_stats_lateral_view_join.q.out, ql/src/test/results/clientpositive/llap/lateral_view.q.out, ql/src/test/results/clientpositive/llap/lateral_view_cp.q.out, ql/src/test/results/clientpositive/llap/lateral_view_explode2.q.out, ql/src/test/results/clientpositive/llap/lateral_view_noalias.q.out, ql/src/test/results/clientpositive/llap/lateral_view_onview.q.out, ql/src/test/results/clientpositive/llap/lvj_mapjoin.q.out, ql/src/test/results/clientpositive/llap/multi_insert_lateral_view.q.out, ql/src/test/results/clientpositive/llap/nested_column_pruning.q.out, ql/src/test/results/clientpositive/llap/orc_nested_column_pruning.q.out, ql/src/test/results/clientpositive/llap/reduce_deduplicate_null_keys.q.out, ql/src/test/results/clientpositive/llap/select_column_pruning.q.out, ql/src/test/results/clientpositive/llap/skewjoin_mapjoin6.q.out, ql/src/test/results/clientpositive/llap/udtf_json_tuple.q.out, ql/src/test/results/clientpositive/llap/udtf_parse_url_tuple.q.out, ql/src/test/results/clientpositive/llap/union26.q.out, ql/src/test/results/clientpositive/llap/unionDistinct_1.q.out, ql/src/test/results/clientpositive/llap/union_lateralview.q.out, ql/src/test/results/clientpositive/llap/vector_orc_nested_column_pruning.q.out, ql/src/test/results/clientpositive/llap/vector_windowing.q.out, ql/src/test/results/clientpositive/nonmr_fetch.q.out, ql/src/test/results/clientpositive/skewjoinopt10.q.out, ql/src/test/results/clientpositive/tez/tez_union_udtf.q.out
Estimate statistics of LATERAL VIEW correctly.
StatsRulesProcFactory doesn't have any rules to handle a JOIN by LATERAL VIEW.
This can cause an underestimation in case that UDTF in LATERAL VIEW generates multiple rows.
Significant underestimation can happen when LATERAL VIEW increases the number of records a lot and the source table has large.
No.
Added one test case.
=> HIVE-24203: Implement stats annotation rule for the LateralViewJoinOperator

ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
AcidUtils already returns the file list in base and delta directories if it does recursive listing on S3, listing those directories can be removed from the Initiator
No.
Existing unit tests
=> HIVE-24615: Remove unnecessary FileSystem listing from Initiator

parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g, parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g, parser/src/test/org/apache/hadoop/hive/ql/parse/TestValuesClause.java, ql/src/test/queries/clientpositive/values.q, ql/src/test/results/clientpositive/llap/values.q.out
Prior this patch for defining a row of constant values Select clause could be used:
```
SELECT * FROM t1 foo
JOIN (select 1,'a') as bar ON foo.col1 = bar.col1
```
This enables the usage of Values clasuse:
```
SELECT * FROM t1 foo
JOIN (VALUES(1,'a'),(4,'b')) as bar ON foo.col1 = bar.col1
```
With Select clause only one row could be defined. There is no such limitation with Values clause.
Yes. From now the Values clause can be used in subqueries and can be a query itself.
```
mvn test -Dtest=TestValuesClause -pl parser
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=values.q -pl itests/qtest -Pitests
```
=> HIVE-24613: Support Values clause without Insert

common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java, ql/src/java/org/apache/hadoop/hive/ql/Context.java, ql/src/java/org/apache/hadoop/hive/ql/Driver.java, ql/src/java/org/apache/hadoop/hive/ql/io/rcfile/truncate/ColumnTruncateTask.java, ql/src/java/org/apache/hadoop/hive/ql/parse/AcidExportSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/ColumnStatsAutoGatherContext.java, ql/src/java/org/apache/hadoop/hive/ql/parse/ColumnStatsSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/LoadSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java, ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSQLSchema.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDTFGetSplits.java, ql/src/test/org/apache/hadoop/hive/ql/exec/TestContext.java, ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezTask.java, ql/src/test/org/apache/hadoop/hive/ql/optimizer/physical/TestNullScanTaskDispatcher.java, ql/src/test/org/apache/hadoop/hive/ql/tool/TestLineageInfo.java
Remove superfluous throws IOException from Context constructor, which may never be thrown.
To keep the code clean by not having unused parts in it.
No.
All the tests are still running fine.
=> HIVE-24610 Remove superfluous throws IOException from Context

parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g, parser/src/test/org/apache/hadoop/hive/ql/parse/TestValuesClause.java, ql/src/test/queries/clientpositive/values.q, ql/src/test/results/clientpositive/llap/values.q.out
1. Move the `valuesSource` rule alternative from `queryStatementExpression` parser rule to `atomSelectStatement`
2. Remove `valuesClause` rule alternative from `regularBody` since it is covered through 
`selectStatement`->`atomSelectStatement`->`valuesSource`->`valuesClause`
Enable queries which has values clause as operand of set operation. See jira or `values.q` for example
Yes. Users can write queries which has values clause as operand of set operation. This feature was not enabled in the past and Hive thrown exception such cases. Existing queries are not affected.
```
mvn test -Dtest=TestValuesClause -pl parser
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=values.q -pl itests/qtest -Pitests
```
=> HIVE-24635: Support Values clause as operand of set operation

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
When FS Root is updated using metatool, if the DB has managed location defined, 
updateMDatabaseURI API should update the managed location as well. Currently it only updates location uri.
Hive metatool is used for cases where NN changes and the metastore fs root has to be updated. When updating the fs root using metatool, if the databases have MANAGEDLOCATION explicitly defined the tool misses to update the fs root of the managed location. 
Fixes user facing bug for specific fs root change scenario.
Manually in test cluster which has ability to Update FS Root.
=> HIVE-24514: UpdateMDatabaseURI does not update managed location URI

ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java, ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestVectorizedOrcAcidRowBatchReader.java, ql/src/test/org/apache/hadoop/hive/ql/metadata/TestMSCKRepairOnAcid.java
Remove multiple parsedDelta implementation in AcidUtils:
- Remove code duplication
- Use ParsedDeltaLight everywhere where rawformat is not used, because parsing that is cheaper
code quality
No
Previous unit tests
=> HIVE-24630: clean up multiple parseDelta in AcidUtils

itests/util/src/main/java/org/apache/hadoop/hive/llap/LlapItUtils.java, llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapDaemon.java, llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/TestLlapDaemon.java
Llap daemon should enforce the proper number of io threads (>= executors)
It can cause query hang otherwise.
No.
On Cloudera Data Warehouse.
=> HIVE-24626: LLAP: reader threads could be starvated if all IO elevator threads are busy to enqueue to another readers with full queue

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java, ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestDagUtils.java, ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestTezOutputCommitter.java
1. TezProcessor should invoke output committer's commitTask after each processor execution.
2. After successful vertex completion, the DAG should invoke the Tez API output committer's commitOutput. 
To make Hive writes work with Iceberg tables. Data files in Iceberg will only become active/visible, once they've been committed to the table as part of a new snapshot.
New config value, otherwise no.
=> HIVE-24629: Invoke output committer in TezProcessor

ql/src/java/org/apache/hadoop/hive/ql/exec/FetchOperator.java, ql/src/test/queries/clientpositive/exim_04_evolved_parts.q, ql/src/test/results/clientpositive/llap/exim_04_evolved_parts.q.out
Remove unnecessary file listing from Fetchoperator, rather handle FileNotFoundException, to make it more performant on s3.
Rebased the original patch from Sahil Takiar.
No
Current unit tests. Manually test: deleted some directories during execution to cause FileNotFoundEx.
=> HIVE-14165: Remove unnecessary file listing from FetchOperator

itests/hcatalog-unit/pom.xml, itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/hbase/ManyMiniCluster.java, itests/util/pom.xml, pom.xml, ql/pom.xml
Make Hive buildable with HBase 2.x GA releases that are built for Hadoop 3
Currently Hive includes an old pre-relase version of HBase.
Hive should be able to use GA HBase 2.x code.
No
1. Download Hbase 2.2.6 sources
2. Rebuild and install HBase 2.2.6 locally with -Dhadoop.profile=3.0
3. Build and test hive locally:
mvn clean install -DskipTests  -Dhbase.version=2.2.6; 
mvn test -Dhbase.version=2.2.6; 
cd itests; 
mvn clean install -DskipTests  -Dhbase.version=2.2.6;  
mvn test -Dhbase.version=2.2.6
There were some test failures on my system, but they were all present in a control run without the patch.
=> HIVE-24473 Make Hive buildable with HBase 2.x GA versions

itests/src/test/resources/testconfiguration.properties, ql/src/java/org/apache/hadoop/hive/ql/optimizer/correlation/ReduceSinkDeDuplicationUtils.java, ql/src/test/queries/clientpositive/dynpart_sort_optimization_distribute_by.q, ql/src/test/results/clientpositive/llap/dynpart_sort_optimization_distribute_by.q.out, ql/src/test/results/clientpositive/tez/dynpart_sort_optimization_distribute_by.q.out
…
Changes are required in ReduceSinkDeduplication to merge properly the Child reduce sink operator and parent reduce sink operator
A Null Pointer Exception occurs when inserting data with 'distribute by' clause when hive.optimize.sort.dynamic.partition=true we expect the keys to be sorted in the reducer side so that reducers can keep only one record writer open at any time thereby reducing the memory pressure on the reducers (HIVE-6455) , But in case of non-vectorizied , non-llap execution the keys are not sorted and fails with NPE.
Refer: https://issues.apache.org/jira/browse/HIVE-18284?focusedCommentId=17173124&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-17173124
Caused due to: https://issues.apache.org/jira/browse/HIVE-13260
No
Added a qtest
=> HIVE-18284: Fix NPE when inserting data with 'distribute by' clause with dynpart sort optimization

common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java, parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/java/org/apache/hadoop/hive/ql/parse/QB.java, ql/src/java/org/apache/hadoop/hive/ql/parse/QBParseInfo.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientnegative/cte_col_alias.q, ql/src/test/queries/clientnegative/cte_col_alias_clash.q, ql/src/test/queries/clientpositive/cte_8.q, ql/src/test/queries/clientpositive/cte_mat_1.q, ql/src/test/results/clientnegative/cte_col_alias.q.out, ql/src/test/results/clientnegative/cte_col_alias_clash.q.out, ql/src/test/results/clientpositive/llap/cte_8.q.out, ql/src/test/results/clientpositive/llap/cte_mat_1.q.out
1. Improve the parser to accept CTE clause has `with column list` specified:
```
WITH cte(a, b) AS ...
```
2. When transforming subquery AST tree to Calcite RelNode tree a new RowResolver is created for the subquery's top node to point its alias. Extend this logic with assign the `with column list` elements to each entry if explicitly specified in the `WITH` clause.
SQL standard enables this feature.
Yes. When users specify `with column list` the list elements must be used to reference expressions in the CTE' select clause from the main query.
```
mvn test -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=cte_8.q,cte_mat_1.q -pl itests/qtest -Pitests
mvn test -DskipSparkTests -Dtest=TestNegativeCliDriver -Dqfile=cte_col_alias_clash.q,cte_col_alias.q  -pl itests/qtest -Pitests
```
=> HIVE-24633: Support CTE with column labels

ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java
If delete delta caching is turned off, the plain record reader inside DeleteReaderValue allocates a batch with a schema that is equivalent to that of an insert delta.
This is unnecessary as the struct part in a delete delta file is always empty. In cases where we have many delete delta files (e.g. due to compaction failures) and a wide table definition (e.g. 200+ cols) this puts a significant amount of memory pressure on the executor, while these empty structures will never be filled or otherwise utilized.
I propose we specify an ACID schema with an empty struct part to this record reader to counter this.
=> HIVE-24670

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/RenderStrategy.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/monitoring/TezJobMonitor.java
This makes the Hive on tez progress log interval configurable using the same parameter used in map reduce
(https://issues.apache.org/jira/browse/HIVE-24637)
For long running Hive jobs the current hardcoded value of 3seconds can result in very large logs
Default interval of logging progress log when running on Tez changes from 3 to 6 sec
Internal Hive deployment
=> HIVE-24637 make Tez progress log interval configurable

shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java, shims/0.23/src/main/test/org/apache/hadoop/hive/shims/TestHadoop23Shims.java
HIVE-23840 introduced the feature of reading delete deltas from LLAP cache if it's available. This refactor opens an opportunity for NPE to happen:
Caused by: java.lang.NullPointerException
at org.apache.hadoop.hive.shims.Hadoop23Shims.getFileId(Hadoop23Shims.java:1410)
at org.apache.hadoop.hive.ql.io.HdfsUtils.getFileId(HdfsUtils.java:55)
at org.apache.hadoop.hive.llap.io.encoded.OrcEncodedDataReader.determineFileId(OrcEncodedDataReader.java:509)
at org.apache.hadoop.hive.llap.io.encoded.OrcEncodedDataReader.getOrcTailForPath(OrcEncodedDataReader.java:579)
at org.apache.hadoop.hive.llap.io.api.impl.LlapIoImpl.getOrcTailFromCache(LlapIoImpl.java:322)
at org.apache.hadoop.hive.ql.io.orc.VectorizedOrcAcidRowBatchReader.getOrcTail(VectorizedOrcAcidRowBatchReader.java:683)
at …
=> HIVE-24683

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/ppd/OpProcFactory.java, ql/src/java/org/apache/hadoop/hive/ql/ppd/OpWalkerInfo.java, ql/src/test/results/clientpositive/llap/dynamic_partition_join_noncbo.q.out, ql/src/test/results/clientpositive/llap/hybridgrace_hashjoin_2.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query17.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query25.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query29.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query95.q.out, ql/src/test/results/clientpositive/tez/hybridgrace_hashjoin_2.q.out
When transitively replicate predicate filters over equijoin conditions if the replication is failed due to referenced column in the predicate is not a key column in the ReduceSink operator 
1. traverse the branches of the join operator to find a an equijoin having a join expression where the column referenced in the predicate
2. replace the column in the predicate with the column coming from the other side of the equijoin expression found int step 1.
3. continue with the modified predicate.
See jira for detailes
No.
Executing `explain logical` query95.q:
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestTezTPCDS30TBPerfCliDriver -Dqfile=query95.q -pl itests/qtest -Pitests
```
Check the difference of the output of above command when this ppd extension is turned on/off.
On: …
=> HIVE-24564: Extend PPD filter transitivity to be able to discover new opportunities

pom.xml, ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestVectorizedOrcAcidRowBatchReader.java, ql/src/test/org/apache/hadoop/hive/ql/io/sarg/TestConvertAstToSearchArg.java, ql/src/test/org/apache/hadoop/hive/ql/io/sarg/TestSearchArgumentImpl.java, standalone-metastore/pom.xml, storage-api/pom.xml, storage-api/src/java/org/apache/hadoop/hive/common/io/CacheTag.java, storage-api/src/java/org/apache/hadoop/hive/common/type/CalendarUtils.java, storage-api/src/java/org/apache/hadoop/hive/ql/io/sarg/ExpressionTree.java, storage-api/src/java/org/apache/hadoop/hive/ql/io/sarg/PredicateLeaf.java, storage-api/src/java/org/apache/hadoop/hive/ql/io/sarg/SearchArgument.java, storage-api/src/java/org/apache/hadoop/hive/ql/io/sarg/SearchArgumentImpl.java, storage-api/src/test/org/apache/hadoop/hive/ql/io/sarg/SearchArgumentFactoryTest.java, storage-api/src/test/org/apache/hadoop/hive/ql/io/sarg/TestSearchArgumentFactory.java
This pull request provides a method to get a non-normalized copy of the SArg expression. This can be useful for applications where the smaller non-normalized expression is useful.
I've changed the SArg ExpressionTree leaves to keep a pointer to the PredicateLeafImpl rather than just the id. That makes a lot of things easier, including dealing with keeping the normalized and non-normalized versions in sync with the leaves.
It also changes the format of the toString to be easier to read, but to make the old tests easier to port I've provided a toOldString method that generates the old string.
=> HIVE-24458: Add a method to provide a non-normalized ExpressionTree

common/src/java/org/apache/hadoop/hive/common/JavaUtils.java
When a class loader is being closed, it should also be released from the `org.apache.commons.logging.LogFactory#factories`, where it is being used as a key.
Current implementation has a slow but steady memory leak.
No
=> HIVE-24636: Memory leak due LogFactory retaining ClassLoaders

pom.xml, ql/src/java/org/apache/hadoop/hive/ql/io/TeradataBinaryFileOutputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/TeradataBinaryRecordReader.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/fallback/FallbackHiveAuthorizer.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/AddPartitionEvent.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/AlterDatabaseEvent.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/AlterPartitionEvent.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/AlterTableEvent.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/CreateDatabaseEvent.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/CreateTableEvent.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/DropDatabaseEvent.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/DropPartitionEvent.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/DropTableEvent.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/LoadPartitionDoneEvent.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/ReadDatabaseEvent.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/events/ReadTableEvent.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/filtercontext/DatabaseFilterContext.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/filtercontext/TableFilterContext.java, service/src/java/org/apache/hive/service/servlet/QueriesRESTfulAPIServlet.java
Replace org.apache.commons.logging with org.slf4j and prevent it from being reintroduced.
I encountered HIVE-24636, a memory leak related to commons-logging. I either had to fix the leak on master, or remove commons-logging. Since HIVE-20019 already removed commons-logging, it just got reintroduced later, I chose the latter.
No
=> HIVE-24691: Ban commons-logging (again)

ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/groupby_having_distinct.q, ql/src/test/results/clientpositive/llap/groupby_having_distinct.q.out
Fixing _Having_ with _distinct_ issue in SemanticAnalyzer where _Having_ clause should update both aggregationExpressions and Distinct expressions.
There can be cases where the aggregation is on a distinct column as in:
``
SELECT `min_nsoc`
FROM
(SELECT `npp`,
MIN(`nsoc`) AS `min_nsoc`,
COUNT(DISTINCT `nsoc`) AS `nb_nsoc`
FROM tmp_src1
GROUP BY `npp`) `a`
WHERE `nb_nsoc` > 0;
``
No
Added query file: groupby_having_distinct.q
=> HIVE-24478: Subquery GroupBy with Distinct SemanticException: Invalid column reference

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionState.java
https://issues.apache.org/jira/browse/HIVE-24695
There are cases when TezSessionState would not be able to start. (e.g resource constraints on YARN queues).
However by this time, session directories & certain resources are localized. (e.g, hive-exec jars are stored in hdfs:///tmp/hive/hive/_tez_session_dir//hive-exec.jar). When tezClient is not started, it does not clear up the resources. This leaks ~100MB data in HDFS per failure.
e.g 
hdfs:///tmp/hive/_tez_session_dir/006cac9b-93d5-47f3-bdb2-0a0cb626a8cd-resources/hive-exec.jar
hdfs:///tmp/hive/hive/_tez_session_dir/53531429-d119-4e47-bcb2-5cb686d537ff/
Need to clear up resources in session directory, when errors are encountered in tez session init phase.
No
Small scale cluster
=> HIVE-24695: Clean up session resources, if TezSession is unable to start

common/src/java/org/apache/hadoop/hive/common/type/TimestampTZUtil.java, common/src/test/org/apache/hadoop/hive/common/type/TestTimestampTZ.java
This resolves https://issues.apache.org/jira/browse/HIVE-24353
Change timestampTZ parsing from using convenience methods that throw exceptions to a chain of queries against the parsed temporalAccessor. 
This improves the performance for timestamp parsing. 
No.
Existing tests are covering all branches already. 
One test was added, but it has no assertions.
=> HIVE-24353: performance: do not throw exceptions when parsing dates

ql/src/java/org/apache/hadoop/hive/ql/optimizer/SemiJoinReductionMerge.java, ql/src/java/org/apache/hadoop/hive/ql/parse/TezCompiler.java, ql/src/java/org/apache/hadoop/hive/ql/plan/ExprNodeDescUtils.java, ql/src/test/results/clientpositive/llap/dynamic_semijoin_reduction_2.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query17.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query25.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query29.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query50.q.out
Use hash(hash(hash(a,b),c),d) instead of hash(a,b,c,d) when constructing
the multi-col semijoin reducer.
In order to use fully vectorized execution on multi-col semijoin reducers.
Only changes in EXPLAIN plans.
`mvn test -Dtest=TestTezPerfCliDriver -Dqfile="query50.q"`
=> HIVE-24221: Use vectorizable expression to combine multiple columns in semijoin bloom filters

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/BaseReplicationAcrossInstances.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExternalTables.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/DirCopyTask.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/HdfsUtils.java
https://issues.apache.org/jira/browse/HIVE-24698
=> HIVE-24698. Sync ACL's for the table directory during external table replication.

ql/src/test/queries/clientpositive/orc_ppd_timestamp_precision.q, ql/src/test/results/clientpositive/llap/orc_ppd_timestamp_precision.q.out
Timestamp PPD Test with nanosecond precision
Nanosecond precision timestamps where not supported prior to ORC-1.6 thus we need to add some tests
Np
orc_ppd_timestamp_precision.q
=> HIVE-23036: [TEST] ORC PPD eval with sub-millisecond timestamps

ql/src/java/org/apache/hadoop/hive/ql/hooks/UpdateInputAccessTimeHook.java
When UpdateInputAccessTimeHook is used as pre-hook, any simple queries on transactional table throws exception (full stactrace in https://issues.apache.org/jira/browse/HIVE-24501)
```
org.apache.hadoop.hive.ql.metadata.HiveException(Unable to alter table. Cannot change stats state for a transactional table default.test without providing the transactional write state for verification
```
For updating only access time, the stats of table and partitions does not have to be updated. This PR sets environment context to skip updating the stats.
Bug with exception trace in https://issues.apache.org/jira/browse/HIVE-24501
No.
Manually on dev cluster.
=> HIVE-24501: UpdateInputAccessTimeHook should not update stats

ql/src/test/org/apache/hadoop/hive/ql/metadata/TestHive.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
This PR improves the performance of get_partitions_ps_with_auth for certain cases when it is requesting for all the partitions. get_partitions_ps_with_auth is not directSQL enabled and if it is requesting for all the partitions, we can redirect it to a faster partitions API which supports directSQL. When filters are provided the API continues to use existing datanuclues path so there is no change with that behaviour.
Performance improvement for a HMS API.
No
Modified existing unit-test to make sure it is working as expected. Also tested on a real-world workload where performance improvement was substantial.
=> HIVE-24741: get_partitions_ps_with_auth performance improvement

ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java, ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java, ql/src/test/results/clientpositive/llap/acid_multiinsert_dyn_part.q.out, ql/src/test/results/clientpositive/llap/mm_all.q.out
The dynamic partition infos can be collected from the manifest files, no need to do a costly file listing later in the MoveTask
No.
All unit tests are working, local performance tests
=> HIVE-24682: Collect dynamic partition info in FileSink for direct insert 

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelLrfuCachePolicy.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/decode/GenericColumnVectorProducer.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/SerDeEncodedDataReader.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/VectorDeserializeOrcWriter.java, llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelLrfuCachePolicy.java
HIVE-22492 has introduced threadlocal buffers in which LlapCachableBuffer instances are stored before entering LRFU's heap - so that lock contention is eased up.
This is a nice performance improvement, but comes at the cost of losing the exact accounting of llap buffer instances - e.g. if user gives a purge command, not all the cache space is free'd up as one'd expect because purge only considers buffers that the policy knows about. In this case we'd see in LLAP's iomem servlet that the LRFU policy is empty, but a table may still have the full content loaded.
Also, if we use text based tables, during cache load, a set of -OrcEncode threads are used that are ephemeral in nature. Attaching buffers to these threads' thread local structures are ultimately lost. In an edge case we could load …
=> HIVE-24736

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregateIncrementalRewritingRule.java, ql/src/test/queries/clientpositive/materialized_view_create_rewrite_one_key_gby.q, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_one_key_gby.q.out
During incremental materialized view rebuild CBO plain is transformed from an insert over write plan to a merge into plan if MV definition contains aggregate. During this transformation the union operator is replaced with a right outer join of the union branches and the join keys are coming from the aggregate keys. 
Check the number of expressions before creating the `AND` expression and return use expression itself as the root of the join expression if only one expression exists.
When building the join expressions the key equality checks are concatenated by `AND` operators. Building of `AND` expressions are throws AssertionError when only one operand/aggregate key/join key exists.
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver …
```
=> HIVE-24763: Incremental rebuild of Materialized view fails

jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java, jdbc/src/java/org/apache/hive/jdbc/Utils.java
Improvement [HIVE-12371](https://issues.apache.org/jira/browse/HIVE-12371): Adding a timeout connection parameter for JDBC
We run into the problem of [HIVE-22196](https://issues.apache.org/jira/browse/HIVE-22196): Socket timeouts happen when other drivers set DriverManager.loginTimeout.
It is a good idea to add timeout parameter to hiveserver2 jdbc url. So that we do not use the global DriverManager.loginTimeout which may be unexpected set by other components in the program.
No
Tested by local install jar
=> HIVE-12371 Adding a timeout connection parameter for JDBC

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java, ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java, ql/src/java/org/apache/hadoop/hive/ql/io/AcidOutputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/BucketCodec.java, ql/src/java/org/apache/hadoop/hive/ql/io/HiveFileFormatUtils.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRecordUpdater.java, ql/src/java/org/apache/hadoop/hive/ql/plan/FileSinkDesc.java, ql/src/test/org/apache/hadoop/hive/ql/io/TestBucketCodec.java
Currently the bucketId field is stored on 12 bits. When TEZ starts more tasks than 4095 it overflows.
The proposed solution is to let the bucket id overflow into the statement id. Depending on the maximum statement id (we  know that at compile time) we can dynamically allocate bits for the bucket id from the statement id field.
For example in a single statement operation only one bit is needed for the statement id and 11 extra bits can be allocated for the bucket id.
In case of a multi insert where the max statement id lets say 100 (0b000001100100), five extra bits can be allocated for the bucket Id.
Compaction ignores statement ids therefore the same buckets (delta_1_1_0/bucket_00904_0 and delta_1_1_178/bucket_00904_0) will be merged together after running a major compaction, so we won’t …
=> HIVE-24715 Increase bucketId range (amagyar)

jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
JDBC http client retries are applied only during initial connection establishment and is not applied for broken connection cases (idle timeout triggering tcp connection reset). This PR replaces custom retry handler with default retry handler with user specified maxRetries (jdbc param). The default retry handler retries all exceptions exception (InterruptedIOException, UnknownHostException, ConnectException, SSLException) and does not retry non-idempotent http methods which is sufficient for handling the broken connection cases.
To make jdbc http client more resilient for socket disconnections by the intermediate proxies.
No. maxRetries is already user facing parameter which is reused.
Tested in Azure with LB timeout set to default 4 mins for idle timeout and nginx reverse proxy (5 min …
=> HIVE-24786: JDBC HttpClient should retry for idempotent and unsent http methods

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactorFactory.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
Fix how HIVE_COMPACTOR_COMPACT_MM will disable compaction for insert only tables.
Currently if this property is disabled, compaction will be initiated for insert_only tables and fail in MR based compaction
No
Current unit tests
=> HIVE-24785: Fix HIVE_COMPACTOR_COMPACT_MM property

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelCachePolicy.java, llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelLrfuCachePolicy.java, llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelLrfuCachePolicy.java
This is a subtask for the cache hydration feature, collecting the most important n% of the cached buffers based on the policy.
LLAP cache hydration will enable save/load the cache contents. As it's a good idea to save/load just the most important portion of the cache this feature was added to the policy.
No
=> HIVE-24725: Collect top priority items from llap cache policy

itests/src/test/resources/testconfiguration.properties, itests/util/src/main/java/org/apache/hadoop/hive/ql/udf/generic/TestConfigureUDF.java, ql/src/java/org/apache/hadoop/hive/ql/exec/ExprNodeGenericFuncEvaluator.java, ql/src/java/org/apache/hadoop/hive/ql/exec/MapredContext.java, ql/src/test/queries/clientpositive/udf_configure.q, ql/src/test/results/clientpositive/llap/udf_configure.q.out
Change-Id: Ic6ddbf9ffb14c293caadf1f8ec1e7ec0f9291a31
UDF configure does not get called if fetch task conversion happens.
This attempts to resolve this by calling configure with a dummy MapredContext.
It is a bit ugly in that MapredContext seems to be legacy baggage with various members that do not make sense for a variety of engines and code.
Some custom UDFs are designed with the expectation that configure is called in all instances. Users sometimes use it to inspect configuration values or to set new values to propagate to the evaluate method or to do one time setup.
Yes - it will now call configure in cases where configure was not called before.
Added udf_configure.q and manual testing
=> HIVE-24645: Call configure for UDFs after fetch task conversion

itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStoreUpdateUsingEvents.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CacheUtils.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/SharedCache.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/cache/TestCachedStore.java
1. Redundant check if table is present or not
2. Currently in order to get all constraint form the cachedstore. 6 different call is made with in the cached store. Which led to 6 different call to raw store
1. Check only once if table exit in cached store.
2. Instead of calling individual constraint in cached store. Add a method which return all constraint at once and if data is not consistent then fall back to rawstore.
No
running all UTs
=> HIVE-24259: [CachedStore] Optimise get all constraint api

ql/src/java/org/apache/hadoop/hive/ql/stats/fs/FSStatsAggregator.java, ql/src/test/queries/clientpositive/insert_overwrite_stats.q, ql/src/test/results/clientpositive/llap/insert_overwrite_stats.q.out
https://issues.apache.org/jira/browse/HIVE-24764
insert overwrite on a partition resets row count stats in other partitions. This causes partitions to return PARTIAL value and in some cases, it ends up generating suboptimal plan.
FSStatsAggregator::aggregateStats should return the value when the partitions are present in its statslist. Otherwise, it should return empty or null value. This would prevent stats from being overwritten in BasicStatsTask::updateStats for other partitions during 'insert overwrite' operation.
=> Hive 24764: insert overwrite on a partition resets row count stats in other partitions

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java, ql/src/test/org/apache/hadoop/hive/ql/hooks/TestHiveProtoLoggingHook.java
Allows customers to direct everything related to compaction to a dedicated queue
Improvement
"hive.compactor.job.queue" setting would be considered by query based compactions as well
Unit test
=> HIVE-24781: Allow to use custom queue for query based compaction

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregateIncrementalRewritingRule.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/test/queries/clientpositive/materialized_view_create_rewrite_nulls.q, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_4.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_nulls.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_one_key_gby.q.out
When transforming plan of materialized view rebuild to incremental rebuild in case of the view definition has aggregate:
* Use null safe equality operators in join condition instead of equality operators
* Introduce a Project on top of MV scan having all columns from the view plus a boolean literal which indicates whether the row with the key values coming from the joinRightInput exists in the view. Use this flag in `CalcitePlanner.fixUpASTAggregateIncrementalRebuild` to decide which branch a row should go: update or insert.
* Add null checks of aggregated values when calculated new aggregated values.
Rows with null aggregate keys and aggregated values was not handled by incremental MV rebuild and it could lead to data corruption.
Yes. Query result changes. See jira for example.
```
mvn …
```
=> HIVE-24775: Incorrect null handling when rebuilding Materialized view incrementally

itests/pom.xml, standalone-metastore/metastore-tools/pom.xml
Exclude javax.servlet.jsp dependency from metastore-tools and itests
to avoid pulling transitively javax.el (similar approach to HIVE-19579).
Exclusion should take place in top-level dependency management sections.
Build may fail since [javax.servlet.jsp|https://repo1.maven.org/maven2/org/glassfish/web/javax.servlet.jsp/2.3.2/javax.servlet.jsp-2.3.2.pom] defines the following
```
<dependency>
<groupId>org.glassfish</groupId>
<artifactId>javax.el</artifactId>
<version>[3.0.0,)</version>
</dependency>
```
and this might create problems due to https://issues.apache.org/jira/browse/MNG-3092.
No
Add the following snippet to ~/.m2/settings.xml
```
<repositories>
<repository>
<id>mvn.central</id>
<url>https://repo1.maven.org/maven2/</url>
</repository>
<repository>
<id>hortonworks</id> …
```
=> HIVE-24809: Build failure while resolving javax.el dependency

serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerdeUtils.java
This pr disable validate default values when parsing Avro schemas.
It will throw exception when upgrading Avro to 1.10.1 for this schema::
```json
{
"type": "record",
"name": "EventData",
"doc": "event data",
"fields": [
{"name": "ARRAY_WITH_DEFAULT", "type": {"type": "array", "items": "string"}, "default": null }
]
}
```
```
org.apache.avro.AvroTypeException: Invalid default for field ARRAY_WITH_DEFAULT: null not a {"type":"array","items":"string"}
at org.apache.avro.Schema.validateDefault(Schema.java:1571)
at org.apache.avro.Schema.access$500(Schema.java:87)
at org.apache.avro.Schema$Field.<init>(Schema.java:544)
at org.apache.avro.Schema.parse(Schema.java:1678)
at org.apache.avro.Schema$Parser.parse(Schema.java:1425)
at org.apache.avro.Schema$Parser.parse(Schema.java:1396)
at …
```
=> HIVE-24797: Disable validate default values when parsing Avro schemas

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
Set `materializationTime` when updating `CreationMetadata` using `ObjectStore.updateCreationMetadata`
When Rebuilding a MaterializedView a new `CreationMetadata` instance is created for the view which contains updated information like `ValidTxnList`. Initially this object has a `materializationTime` value with `0` and this is going to be stored in the `HiveMaterializedViewsRegistry` wrapped by the `RelOptMaterialization` object represents the view. However the `materializationTime` value stored in the MetaStore is recalculated and stored during the update hence MS and the registry has different values. This can lead unnecessary registry refresh or even `NullPointerException` as the jira explains.
No.
```
mvn test -Dtest=TestObjectStore#testUpdateCreationMetadataSetsMaterializationTime -pl …
```
=> HIVE-24822: Materialized View rebuild loses materializationTime property value

itests/hive-jmh/src/main/java/org/apache/hive/benchmark/serde/HiveCharBench.java, serde/src/java/org/apache/hadoop/hive/serde2/io/HiveCharWritable.java, serde/src/test/org/apache/hadoop/hive/serde2/io/TestHiveCharWritable.java
Addressing a performance optimization in HiveCharWritable::getStrippedValue:
```
-    // A lot of these methods could be done more efficiently by operating on the Text value
-    // directly, rather than converting to HiveChar.
-    return new Text(getHiveChar().getStrippedValue());
```
Performance.
No.
New unit tests are included.
=> HIVE-24416: Optimise HiveCharWritable::getStrippedValue

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveSubQueryRemoveRule.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
1. Replace HiveSubQueryFinder with RexUtil.SubQueryFinder
2. Modify HiveSubQueryRemoveRule to match only relevant nodes
Core readability and small performance improvement.
No
Existing tests
=> HIVE-24835: Replace HiveSubQueryFinder with RexUtil.SubQueryFinder

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/AckTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/AckWork.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplAck.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
Storing last notificationID of target cluster while executing repl load command.
No
Added one test => TestReplicationScenariosAcidTables#testNotificationFromLoadMetadataAck
=> HIVE-24783: Store currentNotificationID on target during repl load op.

ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
=> HIVE-24858: UDFClassLoader leak in Configuration.CACHE_CLASSES

itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestWMMetricsWithTrigger.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/WorkloadManager.java
Update the metrics and resource allocations in the pool after kill trigger processing is completed.
Following two bugs were found with respect to Azure HDInsight customers
1. Workload manger doesn't process allocation changes after KillTrigger which leads to existing queries not able to ffully utilize the resources of the query which is killed.  
2. It is also found that the Workload Manager thread is not updating the runningQueries metric for the pool  after kill trigger is processed making metrics unreliable afterwards.
These changes are done to fix the above two bugs.
No
Added a unit test to validate metrics before and after execution of kill trigger
=> HIVE-24803: update metrics and allocation after kill trigger status becomes available

ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFPercentileCont.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFPercentileDisc.java
Fix constant values in `GenericUDAFPercentileCont/Disc` description.
Values were copy/pasted from `GenericUDAFDenseRank`
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=udaf_percentile_disc.q,udaf_percentile_cont.q -pl itests/qtest -Pitests
```
=> HIVE-24863: Wrong property value in UDAF percentile_cont/disc description

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java
- Removed unused method createViewTask(MetaData metaData, String dbNameToLoadIn, HiveConf conf)
- Changed the call from from getAllCols to getCalls while creating CreateViewDesc
itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java
- Added test case to include replication of partitioned views.
Using Table.getAllColls to get view columns adds partition columns in both table column and partition column list resulting name conflicts for partition columns.
No
Updated relevant test case to include partitioned view.
=> HIVE-24818 : REPL LOAD of views with partitions fails

ql/src/java/org/apache/hadoop/hive/ql/log/LogDivertAppender.java
ETL flow prints Partition Basic Stats in beeline or client console. After HIVE-16061, this stats are not getting printed on the client.
As there are multiple clients connecting to HS2 & running ETL, it was difficult for end user to search for stats in HS2 logs. This feature will help to know data loaded per partition.
No
I did manual testing by including this fix in my local cluster & validated client console shows the logs.
=> HIVE-23779: BasicStatsTask Info is not getting printed in beeline console

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java
Compaction reattempt should clear the old attempt files before running the current attempt
Compaction task can be pre-empted by yarn for resource or some network issue could cause hdfs read failures, which when re-attempted to new NM can succeed. This re-attempt is failing because of stale files from old failed attempt.
No
No testcase is included.
=> HIVE-24882: Compaction task reattempt fails with FileAlreadyExistsException for DeleteEventWriter

common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java, ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java, ql/src/java/org/apache/hadoop/hive/ql/exec/Registry.java, ql/src/java/org/apache/hadoop/hive/ql/exec/WindowFunctionDescription.java, ql/src/java/org/apache/hadoop/hive/ql/exec/WindowFunctionInfo.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/ASTConverter.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/java/org/apache/hadoop/hive/ql/parse/PTFTranslator.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/WindowingSpec.java, ql/src/java/org/apache/hadoop/hive/ql/parse/type/HiveFunctionHelper.java, ql/src/java/org/apache/hadoop/hive/ql/plan/ptf/WindowFunctionDef.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFFirstValue.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFLastValue.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFParameterInfo.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/SimpleGenericUDAFParameterInfo.java, ql/src/test/queries/clientnegative/nulltreatment.q, ql/src/test/results/clientnegative/nulltreatment.q.out, ql/src/test/results/clientnegative/windowing_invalid_udaf.q.out
1. Add `respectNulls` boolean property to `GenericUDAFParameterInfo`.
2. Map this property to Windowing specification/definitions objects.
3. Introduce property to `WindowFunctionDescription` which show whether the function supports handling null treatment settings. 
* If the `supportNullTreatment` property is not set explicitly the UDAF does not support null treatment and the compiler throws `SemanticException` if specified.
* If the `supportNullTreatment` property is set to true but the function call does not specify null treatment the default null treatment is used: `RESPECT NULLS`
* The specified null treatment is used othervise.
This patch is a follow-up of #2060. See jira for details.
Yes. When calling `lead` or `lag` functions by specifying `RESPECT/IGNORE NULLS`
* and no default …
=> HIVE-24908: Adding Respect/Ignore nulls as a UDAF parameter is ambiguous

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMaterializedViewRebuild.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp, standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/Materialization.java, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/Materialization.php, standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py, standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb, standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
When checking a Materialized view validity check whether any of the source tables compacted since the last materialized view rebuild.
During Materialized view rebuild we choose from incremental or full rebuild. 
To make this choice existing implementation searches for delete transactions affect the source tables of the MV in `COMPLETED_TXN_COMPONENTS` table (Metastore) since the last rebuild. However these records are deleted during compaction. This leads to corrupted materialized view datasets since incremental rebuild will be used which does not handle deleted records.
Yes. Query the materialized view and queries which plan is rewritten to scan the materialized view may produce different results.
Only transactional materialized views are affected.
```
mvn test -Dtest.output.overwrite …
```
=> HIVE-24840: Materialized View incremental rebuild produces wrong result set after compaction

ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
We should auto-abort/remove open replication txns that are older than a time threshold (default: 24h).
Unit test
=> HIVE-24881: Abort old open replication txns

ql/src/java/org/apache/hadoop/hive/ql/parse/MapReduceCompiler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/OptimizeTezProcContext.java, ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/TezCompiler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/spark/OptimizeSparkProcContext.java, ql/src/java/org/apache/hadoop/hive/ql/parse/spark/SparkCompiler.java
Idem with summary.
Small refactoring to improve code readability.
The ReadEntity, and WriteEntity parameters in TaskCompiler#optimizeOperatorPlan are
passed in this method and various subsequent ones but they are never actually used
so they can be removed.
No
Existing tests
=> HIVE-24931: Remove Read/WriteEntity parameters from TaskCompiler#optimizeOperatorPlan

ql/src/java/org/apache/hadoop/hive/ql/exec/Operator.java, ql/src/test/org/apache/hadoop/hive/ql/exec/TestOperators.java, ql/src/test/results/clientpositive/tez/explainanalyze_3.q.out
Taking child operator's done field into consideration on vectorForward.
Because otherwise e.g. limit operator's setDone(true) won't help in preventing the processing of all the rows.
No.
Precommit testing.
=> HIVE-24930: Operator.setDone() short-circuit from child op is not used in vectorized codepath (if childSize == 1)

ql/src/java/org/apache/hadoop/hive/ql/parse/QBSubQuery.java, ql/src/test/queries/clientpositive/subquery_exists_windowfunc.q, ql/src/test/results/clientnegative/subquery_windowing_corr.q.out, ql/src/test/results/clientpositive/llap/subquery_exists_windowfunc.q.out
Loose correlated subquery restrictions: enable correlated exists/not exists subquery rewrite when subquery has windowing clause. 
In case of Exists/Not exists subqueries we are not interested in the result of the window function call but the existence of any record.
Yes. Currently such queries can not be executed with Hive and an error message is printed. With this patch queries will be executed and the result will be printed. 
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=subquery_exists_windowfunc.q -pl itests/qtest -Pitests
```
=> HIVE-24929: Allow correlated exists subqueries with windowing clause

ql/src/java/org/apache/hadoop/hive/ql/parse/type/TypeCheckProcFactory.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFBaseCompare.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFIn.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFOPEqual.java, ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFOPNotEqual.java, ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFInitializeOnCompareUDF.java, ql/src/test/queries/clientpositive/equals_list_types.q, ql/src/test/queries/clientpositive/equals_map_types.q, ql/src/test/queries/clientpositive/equals_struct_types.q, ql/src/test/results/clientnegative/udf_in.q.out, ql/src/test/results/clientpositive/llap/equals_list_types.q.out, ql/src/test/results/clientpositive/llap/equals_map_types.q.out, ql/src/test/results/clientpositive/llap/equals_struct_types.q.out
1. Refactor GenericUDFBaseCompare#initialize to allow equalities between
MAP/LIST/STRUCT types and improve readability.
2. Add positive and negative parameterized tests for GenericUDF#initialize
method with various argument types.
3. Re-work and unify messages in UDFArgumentException when types do not
match.
4. Add positive qtests for MAP, LIST, and, STRUCT types and different UDFs.
1. Allow simple comparisons between non primitive types.
2. Avoid unexpected parse and runtime exceptions when performing comparisons involving MAP, LIST, STRUCT types.
3. Extend test coverage of comparisons operators on STRUCT, LIST, MAP, and primitive types.
Allows more SQL queries and provides proper failure information when comparisons are not supported.
```
mvn test …
```
=> HIVE-24886: Support simple equality operations between MAP/LIST/STRUCT types

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestWarehouseDnsPath.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/Warehouse.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Based on its javadoc comment getDnsPath is supposed to change the authority part (ip) of a path to a domain name. To do so it creates a new FileSystem object and gets the default path from it, and uses the authority from the the default path to replace the authority of the input.
There are multiple problems with this. Instantiating a new FileSystem is expensive. Replacing the authority on a blobstore path (s3a) is not needed since s3 uses bucket name instead of a hostname in the path.
Even in HDFS case the original function doesn't do what the original intention might was. The new file system is initialized with the input path so the default FS path is always same as the input path (unless a relative path is used as an input). The only useful thing this function does is transforming a …
=> HIVE-24838. Reduce FS creation in Warehouse::getDnsPath for object stores

ql/src/java/org/apache/hadoop/hive/ql/parse/QBSubQuery.java, ql/src/java/org/apache/hadoop/hive/ql/parse/QBSubQueryParseInfo.java
1. Remove outdated comment lines and if condition which was moved to `QBSubQueryParseInfo` and implementations of `ExprFactory.createSubqueryExpr`
2. Renamed boolean variable `noImplicityGby` -> `hasExplicitGby` and negate its semantics.
Code cleanup. This is a follow-up of: #2039
No.
```
mvn test -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=subquery_full_aggregate.q -pl itests/qtest -Pitests
```
=> HIVE-24935: Remove outdated check for correlated exists subqueries with full aggregate

ql/src/java/org/apache/hadoop/hive/ql/exec/DDLTask.java
Backport HIVE-22453. Describe table unnecessarily fetches partitions
When users have highly partitioned table (10k+), all describe commands will take a very long time to complete. This change will make it such that only "describe extended/formatted table" will start gathering partition statistics.
No
Manual testing.
=> Backport HIVE-22453: Describe table unnecessarily fetches partitions

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableOperation.java, ql/src/test/queries/clientpositive/describe_table.q, ql/src/test/results/clientpositive/llap/describe_table.q.out, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
In certain 3rd party hive UIs, they issue a describe table command, and usually it's either "describe formatted table" or "describe extended table", and it will take a very long time for highly partitioned tables (10k+). In the UI, there is no way to change the settings (to use "describe table"), thus impairing the user experience. Prior to the feature where partition stats was gathered, the experience with using the UI had no problems.
This will allow users to selectively change the describe formatted/extended table behavior at any time.
Yes. A new setting to change the behavior of describe extended/formatted on demand. Default setting of "false" will have no impact.
The describe formatted/extended will not collect stats if you change it to "true".
``` …
```
=> HIVE-24965: Describe table partition stats fetch should be configurable

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestScheduledReplicationScenarios.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java
Set repl.source.for property in the db if db is under replication in incremental dump.
No
=> HIVE-24953: Set repl.source.for property in the db if db is under replication in incremental dump.

ql/pom.xml, ql/src/java/org/apache/hadoop/hive/ql/util/HiveStrictManagedMigration.java, ql/src/java/org/apache/hadoop/hive/ql/util/HiveStrictManagedMigrationControlConfig.java, ql/src/test/org/apache/hadoop/hive/ql/util/TestHiveStrictManagedMigration.java, ql/src/test/resources/hsmm/hsmm_cfg_01.yaml, ql/src/test/resources/hsmm/hsmm_cfg_02.yaml
Currently HiveStrictManagedMigration supports db regex and table regex options that allow the user to specify what Hive entities it should deal with. In cases where we have thousands of tables across thousands of DBs iterating through everything takes a lot of time, while specifying a set of tables/DBs with regexes is cumbersome.
We should make it available for users to prepare control files with the lists of required items to migrate and feed this to the tool. A directory path pointing to these control files would be taken as a new option for HSMM.
=> HIVE-24981

llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/SerDeEncodedDataReader.java, llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java
Moving some potential expensive statements (e.g. `Arrays.toString`) into the adjacent debug-logging guards, since these statements are merely used by the following debug-logging calls.
Note that the fix in `LlapTaskSchedulerService.java` is different with other cases in this patch, because the variable `requestedHostsDebugStr` is used by several debug-logging calls, and we have to declare and assign the variable before these debug-logging calls.
Minor (performance) improvement to logging code
No
Minor improvement to logging code, and no need to test.
=> HIVE-25001: Improvement for some debug-logging guards

hplsql/src/main/java/org/apache/hive/hplsql/Arguments.java, hplsql/src/main/java/org/apache/hive/hplsql/Exec.java, hplsql/src/main/java/org/apache/hive/hplsql/executor/QueryExecutor.java, hplsql/src/main/java/org/apache/hive/hplsql/udf/Udf.java, itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java, service/src/java/org/apache/hive/service/cli/operation/ExecuteStatementOperation.java
HPLSQL supports stored function calls from HiveQL selects:
For example:
```
create function hello(s string) returns string;
begin
return 'hello ' || s;
end;
```
The above stored function can be used in a select:
```
select hello(name) from employees;
```
HPLSQL translates this to a UDF call.
```
SELECT hplsql('hello(:1)', name) FROM users;
```
The hplsql UDF is going to call the hplsql interpreter to evaluate the hello function. The earlier implementation used to look up the interpreter from the session state. But this only works if the evaluation happens in compile time and the UDF is running inside the HS2 process. This is not true for general therefore the UDF should instantiate a new interpreter and use that to eval the function call.
=> HIVE-24997. HPL/SQL udf doesn't work in tez container mode (amagyar)

ql/src/java/org/apache/hadoop/hive/ql/io/avro/AvroGenericRecordReader.java
This is a cherry-pick of #2040 (https://issues.apache.org/jira/browse/HIVE-24851) to branch-3.1
Followup after cherry-pick to `branch-3` from https://github.com/apache/hive/pull/2104.
=> Backport HIVE-24851: Fix reader leak in AvroGenericRecordReader to branch-3.1

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/AbstractThriftHiveMetastore.java
Added an abstract class for HMS APIs which can be extended by a remote cache that implements these APIs. This abstract class will have default implementation for all the HMS APIs, which will just throw UnsupportedOperation exception. Idea is that if the remote cache is dynamically pulling the HMS API interface, it should not fail, whenever a new HMS API is added. 
Abstract class for HMS APIs 
No
Existing tests will test the changes.
=> HIVE-25005: Add abstract class for HMS API interface with default implementation

Jenkinsfile, packaging/pom.xml, pom.xml
Hide Iceberg module behind a profile
After creating patched-iceberg-core and patched-iceberg-api modules the maven build works fine, but IntelliJ needs manual classpath setup for the build in the IntelliJ to succeed.
Most of the community does not use Iceberg and eventually the "patched" modules will be removed as the Hive-Iceberg integration stabilizes and the Iceberg project releases the changes we need. In the meantime we just hide the whole Iceberg module behind a profile which is only used on the CI and if the developer specifically sets it. 
No
Rebuilt the project in maven and in IntelliJ
=> HIVE-25027: Hide Iceberg module behind a profile

ql/src/test/org/apache/hadoop/hive/metastore/txn/TestCompactionTxnHandler.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
Clear failed and not initiated compactions from COMPLETED_COMPACTIONS that are older than a week (configurable) if there already is a newer successful compaction on the table/partition and either (1) the succeeded compaction is major or (2) it is minor and the not initiated or failed compaction is also minor –– so a minor succeeded compaction will not cause the deletion of a major not initiated or failed compaction from history.
Make completed compactions more legible
Yes
Unit tests
=> HIVE-24980: Add timeout for failed and "not initiated" compaction cleanup

hbase-handler/pom.xml, hcatalog/core/pom.xml, hcatalog/hcatalog-pig-adapter/pom.xml, kryo-registrator/pom.xml, llap-server/pom.xml, llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/AsyncTaskCopyLocalJars.java, llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/FadvisedChunkedFile.java, llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/FadvisedFileRegion.java, llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/ShuffleHandler.java, llap-server/src/test/org/apache/hadoop/hive/llap/shufflehandler/TestShuffleHandler.java, pom.xml, ql/pom.xml, serde/pom.xml, shims/0.23/pom.xml, spark-client/pom.xml, standalone-metastore/pom.xml, upgrade-acid/pre-upgrade/pom.xml
Upgrade netty3 to netty4 in Shuffle Handler.
Netty3 is EOL since 2016.
No.
Tested on cluster, microstrategy workload 100/100 queries passed.
=> HIVE-24524: LLAP ShuffleHandler: upgrade to netty4

ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Move `getSimpleTableNameBase` and `findTabRefIdxs` to allow using them from `BaseSemanticAnalyzer.getTableAlias `
See jira.
No.
```
mvn test -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=fetch_deleted_rows.q -pl itests/qtest -Pitests
```
=> HIVE-25012: Parsing table alias is failing if query has table properties specified

itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/DummyRawStoreFailEvent.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/SessionHiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientWithLocalCache.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java, standalone-metastore/metastore-common/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreClient.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/IHMSHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreControlledCommit.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/DummyRawStoreForJdoConnection.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Sending table Id as part of get_table_request to verify weather table cached in HMS cache store is fresh or stale.
Change signature of all get_tables apis to request object model to accept tableId.
New api  get_table( GetTableRequest )
by adding and running all exisiting UTest and Qtest
=> HIVE-23820: [HS2] Send tableId in request for get_table_request API

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveCalciteUtil.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveProject.java
Refactor HiveProject removing unused fields/methods and deprecated calls.
Improve readability.
No.
=> HIVE-25047: Remove unused fields/methods and deprecated calls in HiveProject

llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java, llap-tez/src/test/org/apache/hadoop/hive/llap/tezplugins/TestLlapTaskSchedulerService.java
schedulePendingTasks on the LlapTaskScheduler currently goes through all the pending tasks and tries to allocate them based on their Priority – if a priority can not be scheduled completely, we bail out as lower priorities would not be able to get allocations either.
Optimize by only walking through the nodes with capacity (if any) ,and not all available hosts, for scheduling these tasks based on their priority and locality preferences.
Scheduling perf
No
TestLlapTaskSchedulingService
=> HIVE-24914: Improve LLAP scheduling by only traversing hosts with capacity

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DynamicPartitionPruner.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/HiveSplitGenerator.java, ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/DynamicPartitionPruningOptimization.java, ql/src/java/org/apache/hadoop/hive/ql/parse/GenTezUtils.java, ql/src/java/org/apache/hadoop/hive/ql/plan/DynamicPruningEventDesc.java, ql/src/java/org/apache/hadoop/hive/ql/plan/MapWork.java, ql/src/java/org/apache/hadoop/hive/ql/plan/TableScanDesc.java, ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestDynamicPartitionPruner.java
There are 3 parts of the changes here:
- Pruner changes to provide a filter instead of changing the file lists
- HiveInputFormat changes to combine the Pruning filter with the original filter
- Iceberg handler changes:
- New method in SerDe to return the current partitioning columns
- HiveStoragePredicateHandler implements the addDynamicSplitPruningEdge method which returns true if there is a filter for any of the partitioning columns
- Added new test for partition pruning
To archive comparable performance for Iceberg tables
No
Multiple queries
Plan to add more tests later, but it would be good to have them as a `qtest` and it should be done in a different PR as it is a sizable task in itself
=> HIVE-24962: Implement partition pruning for Iceberg tables

llap-tez/src/java/org/apache/hadoop/hive/llap/tezplugins/LlapTaskSchedulerService.java
Moving the (compute intensive) selection of preemption candidates on a separate thread.
Make sure scheduling task cycles are as fast as possible and remove any non-essential work from that loop.
No
TestLlapTaskSchedulerService
=> HIVE-24472: Optimize LlapTaskSchedulerService::preemptTasksFromMap

llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/TaskExecutorService.java, llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/TaskExecutorTestHelpers.java, llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/TestTaskExecutorService.java, llap-server/src/test/org/apache/hadoop/hive/llap/daemon/impl/comparator/TestShortestJobFirstComparator.java
Victim Task (A) should be preempted in favor of a candidate Task (B) when:
1. A is NOT on the same DAG and Vertex as B  AND
1.1. B is a Guaranteed Task while A is not OR
1.2. Both are guaranteed but A is not finishable and B is
To make sure that Victim task is not behind some upstream updates (asynchronous),  we check its sources' state (by QueryFragmentInfo.canFinish method)
Non-useful Task preemptions can increase query latency
No
Updated TestTaskExecutorService.testFinishablePreemptsNonFinishable()
=> HIVE-25049: LlapDaemon preemption should not be triggered for same Vertex tasks

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/KillMoveTriggerActionHandler.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TriggerValidatorRunnable.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/WmTezSession.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/WorkloadManager.java, ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestWorkloadManager.java
Currently, the Workload management move trigger kills the query being moved to a different pool if destination pool does not have enough capacity. This PR introduces a "delayed move" configuration which doesn't immediately kill the query when the destination pool is full but lets the query run in the source pool as long as possible. Workload manager will attempt the move to destination pool only when there is claim upon the source pool.  Also, introduces additional options for retrying delayed moves periodically and moving the session to the destination pool after a specified amount of time (delayed move timeout).
Design Doc- 
[DelayedMoveDesign.docx](https://github.com/apache/hive/files/6394264/DelayedMoveDesign.docx)
For better utilization of cluster resources. 
No
Unit test
=> HIVE-24201: WorkloadManager can support delayed move if destination pool does not have enough sessions

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
https://issues.apache.org/jira/browse/HIVE-24806
Compute findUserToRunAs on need basis to avoid FS lookup calls. https://issues.apache.org/jira/browse/HIVE-24806 has more details.
To reduce lookup calls in initiator.
No
Test on small internal cluster.
=> HIVE-24806: Compactor: Initiator should lazy evaluate findUserToRunAs()

hplsql/src/main/java/org/apache/hive/hplsql/packages/HmsPackageRegistry.java, standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/ThriftHiveMetastore.cpp, standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/ThriftHiveMetastore.h, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ThriftHiveMetastoreClient.php, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ThriftHiveMetastoreIf.php, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ThriftHiveMetastore_find_package_result.php, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/ThriftHiveMetastore_get_stored_procedure_result.php, standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ThriftHiveMetastore.py, standalone-metastore/metastore-common/src/gen/thrift/gen-rb/thrift_hive_metastore.rb, standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RetryingHMSHandler.java
Thrift doesn't support returning null-s from functions. Instead of returning nulls, we should throw an exception.
This patch also puts back the changes which were accidentally removed by 
https://github.com/apache/hive/commit/6de2d51ac812a9393e8ff5e6de7bd911cb83f237#diff-90c669c961ab250c01087a409b31126cce7ac0672c40f465e7ee262ed7bcdadd
=> HIVE-25033. HPL/SQL thrift call fails when returning null (amagyar)

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
- Get task num from job conf under a key, instead of hacking the numReduceTasks function
- We can still use numReduceTasks/numMapTasks as a fall back
- Increasing test timeout due to recent failure with 200 secs
This should fix cases when the num succeeded task count is 0, and therefore we mistakenly take the task count from the numMapTasks.
=> HIVE-25076: Get number of write tasks from jobConf for Iceberg commits

ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
Improve `Table#getEmptyTable` performance by disabling `registerAllFunctionsOnce`.
`Table#getEmptyTable` do not need `registerAllFunctionsOnce` . The stack trace:
```java
at org.apache.hadoop.hive.ql.exec.Registry.registerGenericUDF(Registry.java:177)
at org.apache.hadoop.hive.ql.exec.Registry.registerGenericUDF(Registry.java:170)
at org.apache.hadoop.hive.ql.exec.FunctionRegistry.<clinit>(FunctionRegistry.java:209)
at org.apache.hadoop.hive.ql.metadata.Hive.reloadFunctions(Hive.java:247)
at org.apache.hadoop.hive.ql.metadata.Hive.registerAllFunctionsOnce(Hive.java:231)
at org.apache.hadoop.hive.ql.metadata.Hive.<init>(Hive.java:388)
at org.apache.hadoop.hive.ql.metadata.Hive.create(Hive.java:332)
at org.apache.hadoop.hive.ql.metadata.Hive.getInternal(Hive.java:312)
at …
```
=> HIVE-21563: Improve Table#getEmptyTable performance by disabling registerAllFunctionsOnce

ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
* separate query rewrite based on MV and MV rebuild code
* move fixUpIncrementalRebuild methods to AlterMaterializedViewRebuildAnalyzer
* extract each type of incremental rebuild plan rewrite
Readable code
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_create_rewrite_4.q,materialized_view_create_rewrite_5.q,materialized_view_create_rewrite_6.q -pl itests/qtest -Pitests
```
=> HIVE-25089: Move Materialized View rebuild code to AlterMaterializedViewRebuildAnalyzer

data/conf/llap/tez-site.xml, data/conf/tez/tez-site.xml, itests/hive-unit/src/test/java/org/apache/hadoop/hive/UtilsForTest.java, itests/hive-unit/src/test/java/org/apache/hive/beeline/TestBeeLineWithArgs.java, itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/miniHS2/TestHiveServer2Acid.java, itests/hive-unit/src/test/java/org/apache/hive/service/cli/operation/TestOperationLoggingAPIWithTez.java, shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
Prevent tez minicluster's settings to be overriden silently by hadoop shim.
It confuses developer who changes values in data/conf/*/hive-site.xml and data/conf/*/tez-site.xml 
No.
```
mvn clean test -Dtest.output.overwrite=true -Pitests -Denforcer.skip=true -pl itests/qtest -pl ./shims/0.23  -Dtest=TestMiniLlapCliDriver -Dqfile=varchar_join1.q
```
Checked logs, and it works as expected (./itests/qtest/target/tmp/log/hive.log)
1. original xmls, e.g. hive.tez.container.size=128 (same behavior as without the patch, but now shim doesn't override because there is an explicit value in the xml, which happens to be the same btw)
```
2021-02-04T01:06:43,986  INFO [main] shims.HadoopShimsSecure: Hadoop23Shims doesn't touch 'hive.tez.container.size' value 128
2021-02-04T01:06:43,986  INFO [main] …
```
=> HIVE-24730: Shims classes override values from hive-site.xml and tez-site.xml silently

ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/show/ShowMaterializedViewsDesc.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/show/ShowMaterializedViewsFormatter.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMaterializedViewsRegistry.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveRelOptMaterialization.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveMaterializedViewUtils.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/MaterializedViewIncrementalRewritingRelVisitor.java, ql/src/test/org/apache/hadoop/hive/ql/metadata/TestMaterializedViewsCache.java, ql/src/test/queries/clientpositive/show_materialized_views.q, ql/src/test/results/clientpositive/llap/show_json_format.q.out, ql/src/test/results/clientpositive/llap/show_materialized_views.q.out
1. Analyze Materialized view definition plan and check if can be transformed to incremental rebuild plan when when loading and parsing materializations in `HiveMaterializedViewsRegistry`
2. Store the result in the registry in `HiveRelOptMaterialization`
3. Print it when the command `SHOW MATERIALIZED VIEWS` executed
Improve `SHOW MATERIALIZED VIEWS`.
Yes. A new column is added to the output of `SHOW MATERIALIZED VIEWS`
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=show_materialized_views.q -pl itests/qtest -Pitests
```
=> HIVE-25066: Show whether a materialized view supports incremental review or not

iceberg/pom.xml
IDE test runs can otherwise result in:
```
Caused by: java.lang.ClassNotFoundException: com.google.protobuf.GeneratedMessageV3
at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
... 62 more
```
and
```
sed by: java.lang.NoClassDefFoundError: Could not initialize class org.apache.calcite.avatica.ConnectionPropertiesImpl
at org.apache.calcite.avatica.MetaImpl.<init>(MetaImpl.java:72)
at org.apache.calcite.jdbc.CalciteMetaImpl.<init>(CalciteMetaImpl.java:85)
at org.apache.calcite.jdbc.Driver.createMeta(Driver.java:169)
at org.apache.calcite.avatica.AvaticaConnection.<init>(AvaticaConnection.java:121)
``` …
=> HIVE-25106: Do not exclude avatica and protobuf for Iceberg

hcatalog/core/src/test/java/org/apache/hive/hcatalog/cli/TestPermsGrp.java, hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatPartitionPublish.java, hcatalog/webhcat/svr/src/test/java/org/apache/hive/hcatalog/templeton/TestWebHCatE2e.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/AbstractTestAuthorizationApiAuthorizer.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestFilterHooks.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreStatsMerge.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStoreWithEnvironmentContext.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreEndFunctionListener.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreEventListener.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreEventListenerOnlyOnCommit.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreInitListener.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestMetaStoreMetrics.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestRemoteHiveMetaStore.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestRemoteHiveMetaStoreIpAddress.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestRetryingHMSHandler.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestDDLWithRemoteMetastoreSecondNamenode.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/FolderPermissionBase.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/StorageBasedMetastoreTestBase.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/TestAuthorizationPreEventListener.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/TestClientSideAuthorizationProvider.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/TestMetastoreAuthorizationProvider.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/TestMultiAuthorizationPreEventListener.java, itests/hive-unit/src/test/java/org/apache/hive/service/cli/thrift/ThriftCliServiceMessageSizeTest.java, itests/util/src/main/java/org/apache/hive/jdbc/miniHS2/MiniHS2.java, metastore/src/java/org/apache/hadoop/hive/metastore/MetaStoreUtils.java, service/src/test/org/apache/hive/service/cli/thrift/ThriftCliServiceTestWithCookie.java
This backports HIVE-18147 from branch-2 to branch-2.3 to fix a few flaky tests. I'll let the PR to run through CI and directly cherry-pick the commits if CI looks good.
=> HIVE-18147 : Tests can fail with java.net.BindException: Address already in use

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, metastore/src/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
This changes `getTable`, `getTableObjectsByName` and `tableExists` in `HiveMetastoreClient` to use `get_table` instead of `get_table_req` introduced in HIVE-15062.
[HIVE-15062](https://issues.apache.org/jira/browse/HIVE-15062) introduced a backward-incompatible change by replacing `get_table` with `get_table_req`. As consequence, when HMS client w/ version > 2.3 interacts with a HMS w/ version < 2.3, errors will occur with the following message:
```
AnalysisException: org.apache.hadoop.hive.ql.metadata.HiveException: Unable to fetch table testpartitiondata. Invalid method name: 'get_table_req';
```
Looking at HIVE-15062, the `get_table_req` is to introduce client-side check for capabilities. However in branch-2.3 the check is a no-op since there is no capability yet (it is assigned to …
=> HIVE-24608: Switch back to get_table in HMS client for Hive 2.3.x

ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedPrimitiveColumnReader.java, ql/src/test/org/apache/hadoop/hive/ql/io/parquet/TestVectorizedColumnReader.java, ql/src/test/org/apache/hadoop/hive/ql/io/parquet/VectorizedColumnReaderTestBase.java
The date type should be treated as int instead of long.
otherwise exception will be thrown when read parquet files with date column when vectorization is enabled.
no.
add a unit test for date.
=> HIVE-21200: Vectorization: date column throwing java.lang.UnsupportedOperationException for parquet

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
https://issues.apache.org/jira/browse/HIVE-25072
Reduce number of table lookups in alterpartitions
To reduce load in HMS
no
small internal cluster
=> HIVE-25072: Optimise ObjectStore::alterPartitions

ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
Call `isSourceTablesCompacted` instead of `isSetSourceTablesCompacted` when validating materialized views. Latter method only check whether the property is null or not.
`isSetSourceTablesCompacted` method check whether the property value should be treated as null values or not and we need the non-null value here.
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_create_rewrite_4.q -pl itests/qtest -Pitests
mvn test -Dtest=TestMaterializedViewRebuild -pl itests/hive-unit -Pitests
```
=> HIVE-24840: Materialized View incremental rebuild produces wrong result set after compaction ADDENDUM

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosAcidTables.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java, ql/src/java/org/apache/hadoop/hive/ql/Compiler.java, ql/src/java/org/apache/hadoop/hive/ql/Context.java, ql/src/java/org/apache/hadoop/hive/ql/exec/ReplTxnTask.java, ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java, ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java, ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager.java, ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java, standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/ThriftHiveMetastore.cpp, standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp, standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/AbortTxnRequest.java, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/CommitTxnRequest.java, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/AbortTxnRequest.php, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/CommitTxnRequest.php, standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py, standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java, standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Skip the repl events from getting logged in notification log
Currently REPL dump events are logged and replicated as a part of replication policy. Whenever one replication cycle completed, we always have one transaction left open on the target corresponding to repl dump operation. This will never be caught up without manually dealing with the transaction on target cluster.
No
=> HIVE-24909: Skip the repl events from getting logged in notification log

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/check_constraint.q, ql/src/test/results/clientnegative/merge_constraint_notnull.q.out, ql/src/test/results/clientpositive/llap/check_constraint.q.out, ql/src/test/results/clientpositive/llap/enforce_constraint_notnull.q.out, ql/src/test/results/clientpositive/llap/insert_into_default_keyword.q.out
1. Add a Project on top of constraint Filter when building CBO plan from AST since Filter schema can have more columns than result schema. 
2. Disable plan generation for constraint for update statements if CBO is enabled.
CBO failed because of Result schema and CBO plan schema mismatch. 
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=check_constraint.q -pl itests/qtest -Pitests
```
=> HIVE-25109: CBO fails when updating table has constraints defined

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
Places DEBUG logging information after every major transformation step of the CBO planner.
More DEBUG info and overcomes the following shortcomings:
1. If there is a failure (exception) in some transformation step
intermediate plans are lost, thus losing track of which plan led to the
problem.
2. Intermediate logs are useful for identifying plan problems while
working on a patch; unfortunately the logs are explicitly disabled in
test mode which means that in order to appear the respective code needs
to change every time we need to see those logs.
3. Logging at the end necessitates keeping additional local variables
which makes the code slightly harder to read.
DEBUG logs are slightly different.
No need for tests.
=> HIVE-25046: Log CBO plans right after major transformations

standalone-metastore/metastore-server/src/main/sql/postgres/hive-schema-4.0.0.postgres.sql, standalone-metastore/metastore-server/src/main/sql/postgres/upgrade-3.2.0-to-4.0.0.postgres.sql
Create index on SDS.CD_ID for Postgres.
Performance improvment. The index is already present for other RDBMS vendors.
No.
Manually, on customer side.
=> HIVE-24911: Metastore: Create index on SDS.CD_ID for Postgres

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergCTASHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergQueryLifeTimeHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithMultipleCatalogs.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java
- CTAS table is created inside the `HiveIcebergSerDe`
- StorageHandler API is extended with `isDirectInsertCTAS`
- In the execution plan, table creation task and move task are skipped if storageHandler.isDirectInsertCtas == true
- Also, a PreInsert hook is attached, so that the commitInsertTable hook will be called
- Rollback is implemented using a lifecycle hook
=> HIVE-25034: Implement unpartitioned CTAS for Iceberg

pom.xml, ql/pom.xml, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/NanoTimeUtils.java, service/src/resources/hive-webapps/hiveserver2/hiveserver2.jsp, service/src/resources/hive-webapps/hiveserver2/logconf.jsp
All of the util classes that were used in Hive as part of `jodd-core` dependency have moved to jodd-util.
Upgrading to 6.0.0 version of the jodd-util package.
Hive uses a version of `jodd-core` dependency directly that is susceptible to CVE-2018-21234. We need to upgrade this library to a more recent version but the higher versions don't exactly have the same classes and methods that Hive needs. There is a breaking change introduced in the library  https://github.com/oblac/jodd/blob/master/CHANGELOG_v4.md#breaking-changes-1. 
Currently, we use the JDateTime class(https://github.com/apache/hive/blob/7b3ecf617a6d46f48a3b6f77e0339fd4ad95a420/ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/NanoTimeUtils.java#L26) and HtmlEncoder class …
=> HIVE:25054 Upgrade `jodd-core` dependency to get rid of CVE-2018-21234

ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandlerWithOneConnection.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Pass dbConn to the function getOpenTxns so that it doesn't request another connection from pool.
If we let a thread holds more than one connection, a starvation problem might emerge when there are multiple simultaneous requests.
No
Existing tests
=> HIVE-25113: Connection starvation in TxnHandler.getValidWriteIds

druid-handler/src/java/org/apache/hadoop/hive/druid/DruidStorageHandler.java, druid-handler/src/java/org/apache/hadoop/hive/druid/DruidStorageHandlerUtils.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, kudu-handler/src/java/org/apache/hadoop/hive/kudu/KuduStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
Currently users are required to run the ADD JAR command in their session if they want to use Iceberg tables in Hive jobs.
This should be done in an automatic way similarly to how hbase-, kudu-, .. etc handlers are doing it.
Options
=> HIVE-25160: Automatically pass on iceberg-handler jar as job dependency

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergRecordWriter.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerTestUtils.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergTestUtils.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
Wrap the Record before calculating partitions
Timestamp/Date needs values converted to long/int respectively to calculate partitions
No
Added new unit tests
=> HIVE-25062 Iceberg: Fix date partition transform insert issue

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerLocalScan.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithMultipleCatalogs.java, iceberg/iceberg-handler/src/test/queries/negative/create_iceberg_table_failure.q, iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table.q, iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table_stored_by_iceberg.q, iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table_stored_by_iceberg_with_serdeproperties.q, iceberg/iceberg-handler/src/test/results/negative/create_iceberg_table_failure.q.out, iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_by_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_by_iceberg_with_serdeproperties.q.out, parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g, ql/src/java/org/apache/hadoop/hive/ql/parse/StorageFormat.java
This PR introduces syntactic shortcut to allow the creation of Iceberg tables  without providing the handler class
`CREATE TABLE ice_t (a int) STORED BY ICEBERG [WITH SERDEPROPERTIES (...)]`
At the moment, when we want to create an Iceberg table, we have to provide the fully qualified iceberg storage handler class name.
`CREATE TABLE ice_t (a int) STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler' [WITH SERDEPROPERTIES (...)]`
Unit test, q test
=> HIVE-25162: Add support for CREATE TABLE ... STORED BY ICEBERG statements

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveRelFieldTrimmer.java, ql/src/test/queries/clientpositive/multi_count_distinct_null.q, ql/src/test/results/clientpositive/llap/multi_count_distinct_null.q.out
Copy grouping sets when rewriting gby constant keys in `HiveRelFieldTrimmer`
`HiveExpandDistinctAggregatesRule` introduce an Aggregate with grouping sets even if query projects only count distinct constant expressions.
Yes. Queries projects only count distinct constant expressions won't fail.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapCliDriver -Dqfile=multi_count_distinct_null.q -pl itests/qtest -Pitests
```
=> HIVE-25166: Query with multiple count(distinct constant) fails

llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/LlapServiceDriver.java
Use LocalDateTime instead of Instant to generate an llap version string when HIVE_VERSION is not set.
The current code throws a  java.time.temporal.UnsupportedTemporalTypeException,
making it impossible to start the llap jobs when HIVE_VERSION  is not set.
No. 
Built Hive and started llap successfully 
(well, at least it got past the point where the exception was thrown).
=> HIVE-25163 UnsupportedTemporalTypeException when starting llap

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/alter_table_to_iceberg.q.out, pom.xml, ql/pom.xml, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/ParquetRecordReaderBase.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/convert/ETypeConverter.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/read/DataWritableReadSupport.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/timestamp/NanoTimeUtils.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/ParquetDataColumnReaderFactory.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/write/DataWritableWriteSupport.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/write/DataWritableWriter.java, ql/src/test/org/apache/hadoop/hive/ql/io/parquet/VectorizedColumnReaderTestBase.java, ql/src/test/org/apache/hadoop/hive/ql/io/parquet/convert/MyConverterParent.java, ql/src/test/org/apache/hadoop/hive/ql/io/parquet/convert/TestETypeConverter.java, ql/src/test/org/apache/hadoop/hive/ql/io/parquet/serde/TestParquetTimestampUtils.java, ql/src/test/org/apache/hadoop/hive/ql/io/parquet/serde/TestParquetTimestampsHive2Compatibility.java, ql/src/test/queries/clientpositive/parquet_int96_legacy_compatibility_timestamp.q, ql/src/test/queries/clientpositive/parquet_legacy_mixed_timestamp.q, ql/src/test/queries/clientpositive/parquet_timestamp.q, ql/src/test/results/clientpositive/llap/materialized_view_parquet.q.out, ql/src/test/results/clientpositive/llap/parquet_int96_legacy_compatibility_timestamp.q.out, ql/src/test/results/clientpositive/llap/parquet_stats.q.out
1. Add new read/write config properties to control legacy zone conversions in Parquet.
2. Deprecate hive.parquet.timestamp.legacy.conversion.enabled property since it is not clear if it applies on conversion during read or write.
3. Exploit file metadata and property to choose between new/old conversion rules.
4. Update existing tests to remove usages of now deprecated hive.parquet.timestamp.legacy.conversion.enabled property.
5. Simplify NanoTimeUtils#getTimestamp & NanoTimeUtils#getNanoTime by removing 'skipConversion' parameter
1. Provide the end-users the possibility to write backward compatible timestamps in Parquet files so that files can be read correctly by older versions.
2. Improve code readability of NanoTimeUtils APIs.
No.
1. Add timestamp read/write compatibility test with …
=> HIVE-25104: Backward incompatible timestamp serialization in Parquet for certain timezones

itests/hive-unit/src/test/java/org/apache/hadoop/hive/metastore/TestDisallowColChangesExceptionList.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DefaultIncompatibleTableChangeHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreIncompatibleChangeHandler.java
hive.metastore.disallow.incompatible.col.type.check config currently checks if a alter table operation is making a incompatible schema change to the table. By default it is set to true which would error out the alter table call when such a change is detected. However, this change is too restrictive for certain file-formats like Kudu. In case of Kudu, it is allowed to drop a column which could result in the schema to be incompatible according to current implementation of this check. This causes a bad user-experience for Kudu users and there is no real work-around than to disable this check all together. Disabling the check is not an option since for file-formats like Parquet this is should be true to avoid data corruption/incorrect results.
This change introduces a new config which can be …
=> HIVE-24987: Introduce a exception list to skip incompatible column change check

itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcDriver2.java, jdbc/src/java/org/apache/hive/jdbc/HiveQueryResultSet.java, jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java
=> HIVE-25203: HiveQueryResultSet and client operation are not expected to be closed twice

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g, parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g, parser/src/java/org/apache/hadoop/hive/ql/parse/ParseDriver.java, parser/src/java/org/apache/hadoop/hive/ql/parse/ParseResult.java, ql/src/java/org/apache/hadoop/hive/ql/Context.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CacheTableHelper.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Added code to ensure the validWriteIdList for all tables are fetched
before any table request is done.
The tables are now gathered at parsing time within FromClauseParser.g.
One of the initial steps while parsing is to make an HMS call to fetch
the validWriteIdList for all parsed tables. This is done within a newly
added class called CacheTableHelper. The only purpose of this class is
to populate the query HMS cache for future calls to HMS. The methods to
this class do not contain any return values.
One complication to sending the request up front is when the query contains
views. The views will have underlying physical tables that need fetching but
we won't know these tables until after doing an HMS call. This is handled
by using the underlying tables of the most recent time a query used …
=> HIVE-25189: Fetch validWriteIdList for tables before table request.

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/CachedClientPool.java, iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCatalogs.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/serde/objectinspector/IcebergDecimalObjectInspector.java, iceberg/iceberg-shading/pom.xml
Remove benmanes caffeine shading
So we do not include 2 versions of Caffeine cache which is not really needed
No
Unit tests
=> HIVE-25201: Remove Caffein shading from Iceberg

hbase-handler/src/test/queries/negative/create_table_stored_by_stored_as_failure.q, hbase-handler/src/test/results/negative/create_table_stored_by_stored_as_failure.q.out, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/queries/negative/create_iceberg_table_stored_as_with_serdeproperties_failure.q, iceberg/iceberg-handler/src/test/queries/negative/create_iceberg_table_stored_as_with_tableproperties_failure.q, iceberg/iceberg-handler/src/test/queries/positive/create_iceberg_table_stored_as_fileformat.q, iceberg/iceberg-handler/src/test/results/negative/create_iceberg_table_stored_as_with_serdeproperties_failure.q.out, iceberg/iceberg-handler/src/test/results/negative/create_iceberg_table_stored_as_with_tableproperties_failure.q.out, iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_as_fileformat.q.out, parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/StorageFormat.java
Support `STORED AS fileformat` syntax together with `STORED BY ICEBERG` or `STORED BY 'org.apache.iceberg.mr.hive.HiveIcebergStorageHandler'`
Work covered in this PR:
- Enhance semantic rule to support both`STORED AS` and `STORED BY` together
- Updated SemanticAnalyzer and StorageFormat to parse the new query format
- Created q tests
Currently, the file format is configurable through the `TBLPROPERTIES` which can be inconvenient, if the end-user doesn't know which table property key should be used to specify the file format. 
New syntax:
`CREATE TABLE ... STORED BY ICEBERG [WITH SERDEPROPERTIES()][STORED AS fileformat]`
Manual test, q test
=> HIVE-25194: Add support for STORED AS ORC/PARQUET/AVRO for Iceberg

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergQueryLifeTimeHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java, ql/src/java/org/apache/hadoop/hive/ql/session/SessionStateUtil.java
Store CTAS and write commit related information in the QueryState object. Use a util class to help add and get resources (including commit info) from the session state.
Makes it cleaner not to have convoluted conf prefixes, avoids accidental session conf pollution
no
manual tests
=> HIVE-25195: Store Iceberg write commit and ctas information in QueryState

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
1. Create and setup `HiveDefaultRelMetadataProvider` before the first call of `HiveRelFieldTrimmer`.
2. Invalidate the metadata query on the current `RelOptCluster` instance to trigger the newly set MetadataQuery instantiation.
`HiveRelFieldTrimmer` uses `RelMetadataProvider` to get expression lineage. If the query contains several union operators determining expression lineage can result into exponential number of expressions due to UNIONs which can lead to OOM.
We already have a fix for this issue (HIVE-24304) but prior this patch the fix was not used because it is part of `HiveDefaultRelMetadataProvider` which is not used when `HiveRelFieldTrimmer` was called the first time.
No.
It is not straight forward to repro this issue from q tests since the RelMetadataProvider is stored in a …
=> HIVE-25220: Query with union fails CBO with OOM

ql/src/java/org/apache/hadoop/hive/ql/exec/MemoryInfo.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/stats/annotation/StatsRulesProcFactory.java, ql/src/java/org/apache/hadoop/hive/ql/stats/StatsUtils.java
Apply Sane Default for Tez Containers as Last Resort
If Tez Container Size is an invalid value ( <= 0 ) then it falls back onto the MapReduce configurations, but if the MapReduce configurations have invalid values ( <= 0 ), they are excepted regardless and this will cause failures down the road.
No
Existing tests
=> HIVE-24707: Apply Sane Default for Tez Containers as Last Resort

common/src/java/org/apache/hadoop/hive/common/auth/HiveAuthUtils.java, common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, common/src/java/org/apache/hive/http/HttpServer.java, service/src/java/org/apache/hive/service/cli/thrift/ThriftBinaryCLIService.java, service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpCLIService.java, service/src/java/org/apache/hive/service/server/HiveServer2.java, service/src/test/org/apache/hive/service/server/TestHS2HttpServerPamConfiguration.java
When starting a jetty http server, one can explicitly exclude certain (unsecure)
SSL cipher suites. This can be especially important, when Hive
needs to be compliant with security regulations. Need add properties to support Hive WebUi and HiveServer2 to this
For Hive Binary Cli Server, we can set include certain SSL cipher suites.
Yes, need to document the new properties:
hive.server2.binary.include.ciphersuites
hive.server2.http.exclude.ciphersuites
hive.server2.webui.exclude.ciphersuites
Unit tests
=> HIVE-25238: Make SSL cipher suites configurable for Hive Web UI and HS2

ql/src/java/org/apache/hadoop/hive/ql/parse/WindowingSpec.java, ql/src/test/queries/clientnegative/ptf_window_boundaries_range_without_order.q, ql/src/test/results/clientnegative/ptf_window_boundaries_range_without_order.q.out
I just wanted to own the 2000th PR so created this. :)
Btw, throwing an exception if the user tries to use bounded range window without ORDER BY clause, similarly to Postgres.
the patch is basically only a check and throw:
```
if (windowFrame.getWindowType() == WindowType.RANGE
&& (windowFrame.getStart().isBoundedNotCurrent()
|| windowFrame.getEnd().isBoundedNotCurrent())) {
throw new SemanticException(
"RANGE with offset PRECEDING/FOLLOWING requires exactly one ORDER BY column");
}
```
all other changes are only formatting...WindowingSpec class was in very bad shape from formatting point of view, I think this was a good opportunity to clean it
Described in JIRA.
The exception in the mentioned use-case.
Manually and with a negative test.
=> HIVE-24804: RANGE with offset PRECEDING/FOLLOWING requires at least one ORDER BY column

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java, serde/src/java/org/apache/hadoop/hive/serde2/ColumnProjectionUtils.java
When putting together the column name list for projection pruning, use the `serdeConstant` delimiter value instead of blindly using the comma as the separator.
Currently, `ColumnProjectionUtils` saves the list of columns as a string into the job conf for projection pruning purposes. However, it mistakenly uses comma as the separator in all cases, which can lead to problems when we use a comma in one of the column names. 
No
Unit tests
=> HIVE-25222: Fix column name issue with commas

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Since Iceberg counts as being a non-native Hive table, addColumn operation needs to be implemented by the help of Hive meta hooks.
=> HIVE-25200: Alter table add columns support for Iceberg tables

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/Context.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveRelOptMaterialization.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveFilter.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/java/org/apache/hadoop/hive/ql/parse/QBExpr.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/masking_mv_by_text_2.q, ql/src/test/queries/clientpositive/materialized_view_rewrite_by_text_6.q, ql/src/test/queries/clientpositive/materialized_view_rewrite_by_text_7.q, ql/src/test/queries/clientpositive/materialized_view_rewrite_by_text_8.q, ql/src/test/results/clientpositive/llap/masking_mv_by_text_2.q.out, ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_6.q.out, ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_7.q.out, ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_8.q.out
1. Generate expanded query text of subqueries and use it to lookup materializations.
2. If materialization exists replace the subquery Calcite plan with materialized view scan.
Improve query text based materialized view query rewrite.
Yes. `Explain` and `Explain cbo` output can change.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_rewrite_by_text_8.q,materialized_view_rewrite_by_text_7.q,materialized_view_rewrite_by_text_6.q -pl itests/qtest -Pitests
```
=> HIVE-25240: Query Text based MaterializedView rewrite of subqueries

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java
Move isEligibleForCompaction evaluation under the Initiator thread pool	
Checking for eligibility >1 mil of distinct table / partition combinations can take a while by the Initiator since all steps are performed in the main thread.
No
Itest
=> HIVE-25217: Move isEligibleForCompaction evaluation under the Initiator thread pool

ql/src/test/org/apache/hadoop/hive/ql/exec/vector/TestVectorLimitOperator.java
=> HIVE-25274: TestLimitOperator fails if default engine is Tez

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java
We should use the MoveTask to commit the changes (inserts/insert overwrites)
MoveTask is used for multiple things, like stat generation. When we removed the Move tasks, we caused several unseen issues. We should reintroduce the MoveTask
No
Unit tests
=> HIVE-25208: Refactor Iceberg commit to the MoveTask/MoveWork

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveIcebergVectorizedRecordReader.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/VectorizedRowBatchIterator.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapred/AbstractMapredIcebergRecordReader.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapred/MapredIcebergInputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java, iceberg/iceberg-handler/src/test/queries/negative/create_iceberg_table_failure.q, iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read.q, iceberg/iceberg-handler/src/test/results/negative/create_iceberg_table_failure.q.out, iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read.q.out, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedRowBatchCtx.java
As https://github.com/apache/iceberg/pull/2613 is resolved, we should port it to Hive codebase, to enable vectorized ORC reads on Iceberg-backed tables.
=> HIVE-25216

bin/hive, common/pom.xml, druid-handler/pom.xml, hbase-handler/pom.xml, itests/hive-unit/pom.xml, llap-server/pom.xml, llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/AsyncTaskCopyAuxJars.java, llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/LlapServiceCommandLine.java, pom.xml, ql/pom.xml, ql/src/java/org/apache/hadoop/hive/ql/exec/spark/HiveSparkClientFactory.java
- Mark all HBase dependencies as provided, so that they are not include in the distribution package
- Add the hbase mapredcp jars to CLASSPATH  in the hive startup script
- remove SKIP_HBASECP option from llap service in hive script
- Add new -k llap option to specify hbase mapredcp libraries
- Change the code that adds the hbase dependencies to LLAP jobs automatically ti use -k  instead
- Let HiveSparkClientFactory work even if it cannot access the HBase libraries
Hive currently includes the HBase libraries in its distribution package, and also adds the HBase libraries separately 
vi the 'hbase mapredcp' command in the startup script.
There are multiple problems with this:
- It's redundant
- The included HBase libraries are ancient, and cannot be easily updated 
- The …
=> HIVE-25101: Remove HBase libraries from Hive distribution

ql/src/test/results/clientpositive/llap/masking_mv_by_text_2.q.out, ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_6.q.out, ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_7.q.out, ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_8.q.out
q.out updates
The tests are failing
No
Run the tests
=> HIVE-25279: Fix q.outs caused by concurrent commits of HIVE-25240 and HIVE-25229

ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizationContext.java, ql/src/test/queries/clientpositive/vector_adaptor_usage_mode.q, ql/src/test/results/clientpositive/llap/vector_adaptor_usage_mode.q.out
If hive.vectorized.adaptor.usage.mode is set to chosen only certain UDFS are vectorized through the vectorized adaptor.
Queries like this one, performs very slowly because the concat is not chosen to be vectorized.
```
select count(*) from tbl where to_date(concat(year, '-', month, '-', day)) between to_date('2018-12-01') and to_date('2021-03-01');  
```
=> HIVE-25242. Query performs extremely slow with vectorized.adaptor = chosen

itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniLlapVectorArrow.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestMiniLlapVectorArrowWithLlapIODisabled.java, ql/src/java/org/apache/hadoop/hive/ql/io/arrow/Serializer.java
Handled the scenario mentioned in - https://issues.apache.org/jira/browse/HIVE-25243
If we get struct value as null, we set isNull[i] = true for all the fields of the struct as well.
To avoid NPE in arrow serializer
No
Created a new test for it - TestMiniLlapVectorArrowWithLlapIODisabled
=> HIVE-25243: Llap external client - Handle nested values when the parent struct is null

ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFDateFormat.java, ql/src/java/org/apache/hadoop/hive/ql/util/DateTimeMath.java, ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFDateFormat.java, ql/src/test/queries/clientpositive/udf_date_format.q, ql/src/test/results/clientpositive/llap/udf_date_format.q.out
Use new java time APIs to get the result instead of older APIs to restore functionality
date_format UDF gives 
1. incorrect time values for dates prior to 1901-01-01 00:00:00 if the timezone is not UTC
2. incorrect date and time values for dates prior to October 15, 1582 (Default Gregorian Calendar change)
These changes fix both of the above issues
The functionality is restored for the date_format UDF
1. Unit tests
2. Local tests with MiniHS2 functionality
=> HIVE-25268: Restore the functionality of date_format UDF

itests/hive-unit/src/test/java/org/apache/hive/service/TestHS2ImpersonationWithRemoteMS.java, jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java
Fix flaky test  TestHS2ImpersonationWithRemoteMS.testImpersonation. It was already fixed as part of HIVE-25093 but that is not the right way to do. Raising the PR again to create separate patch. 
It is failing intermittently and putting unwanted pressure on hive-precommit  setup.
No
Yes
=> HIVE-25250: Fix TestHS2ImpersonationWithRemoteMS.testImpersonation	

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/alter_table_to_iceberg.q.out, ql/src/java/org/apache/hadoop/hive/ql/io/avro/AvroContainerOutputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/avro/AvroGenericRecordReader.java, ql/src/test/queries/clientpositive/avro_write_legacy_timestamp.q, ql/src/test/queries/clientpositive/avro_write_new_timestamp.q, ql/src/test/results/clientpositive/llap/avro_schema_evolution_native.q.out, ql/src/test/results/clientpositive/llap/avro_write_legacy_timestamp.q.out, ql/src/test/results/clientpositive/llap/avro_write_new_timestamp.q.out, serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroDeserializer.java, serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroGenericRecordWritable.java, serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerDe.java, serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerializer.java, serde/src/test/org/apache/hadoop/hive/serde2/avro/TestAvroDeserializer.java
1. Add new read/write config properties to control legacy zone conversions in Avro.
2. Exploit file metadata and property to choose between new/old conversion rules.
Provide the end-users the possibility to write backward compatible timestamps in Parquet files so that files can be read correctly by older versions.
No
1. New qtests for writting Avro timestamps (`avro_write_legacy_timestamp.q`, `avro_write_new_timestamp.q`)
2. Manual tests
* Export Avro table with current Hive version setting `hive.avro.timestamp.write.legacy.conversion.enabled=true`
* Read from external Parquet table with Hive 2 (commit 324f9fa)
=> HIVE-25219: Backward incompatible timestamp serialization in Avro for certain timezones

itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestJdbcWithMiniHS2.java
TestJdbcWithMiniHS2#testHttpRetryOnServerIdleTimeout was disable as part of HIVE-19509 because of its flaky nature. Since the issue is fixed. So enabling it back.
to increase test coverage.
No
Yes, by running flaky pipeline - http://ci.hive.apache.org/job/hive-flaky-check/284/
=> HIVE-19707: Enable TestJdbcWithMiniHS2#testHttpRetryOnServerIdleTimeout

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java
All newly introduced compaction related metrics should be lower case.
Some consumers of the metrics only accept lower case names.
No
Unit test
=> HIVE-25252: All new compaction metrics should be lower case

iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandlerTestUtils.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java
When committing Iceberg writes, currently we only have the JobID without the vertexID, therefore we have to list the folder `<tableLocation>/temp` first, and parse out the full JobIDs (incl. vertexID) from the resulting folder names. 
With Tez 0.10.1 released, now we have a new API we can call to acquire the full JobID, making the file listing unnecessary.
=> HIVE-25308: Use new Tez API to get JobID for Iceberg commits

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
NPE is thrown upon inserting values into an Iceberg table, as statistics generation triggers an alter table operation with undefined (alter)operation type
=> HIVE-25287

ql/src/java/org/apache/hadoop/hive/ql/ddl/process/show/compactions/ShowCompactionsOperation.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
If compaction was manually initiated, it shouldn't count towards the total number of hosts running the initiator
Unit tests
=> HIVE-25318: Number of initiator hosts metric should ignore manually initiated compactions

ql/src/java/org/apache/hadoop/hive/ql/optimizer/topnkey/TopNKeyPushdownProcessor.java, ql/src/test/queries/clientpositive/external_jdbc_table_perf.q, ql/src/test/results/clientpositive/llap/external_jdbc_table_perf.q.out
Map partition key columns in TNK operator to columns in parent select operator when pushing TNK through Select.
Partition key columns are not mapped and may contains invalid column references to parent operator schema.
Yes. Queries with plan mentioned in the jira won't fail with `can not find <colref>` error at execution time.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=external_jdbc_table_perf.q -pl itests/qtest -Pitests
```
=> HIVE-25316: Map partition key columns when pushing TNK op through select

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Fixed a bug caused by open txn commit timeout
No
http://ci.hive.apache.org/job/hive-flaky-check/321
=> HIVE-25288: Fix TestMmCompactorOnTez

ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/HiveCalciteUtil.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveCardinalityPreservingJoinOptimization.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregatePartitionIncrementalRewritingRule.java, ql/src/test/queries/clientpositive/materialized_view_partitioned_create_rewrite_agg.q, ql/src/test/queries/clientpositive/materialized_view_partitioned_create_rewrite_agg_2.q, ql/src/test/results/clientpositive/llap/materialized_view_partitioned_create_rewrite_agg.q.out, ql/src/test/results/clientpositive/llap/materialized_view_partitioned_create_rewrite_agg_2.q.out
1. Add rewrite rule: Insert overwrite the partitions which are affected since the last rebuild only and leave the rest of the partitions intact.
Improve performance of MV rebuild if MV is partitioned insert only and contains aggregate.
No. However `explain` output may change.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_partitioned_create_rewrite_agg.q -pl itests/qtest -Pitests
```
=> HIVE-25253: Incremental rebuild of partitioned insert only materialized views

iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/truncate/TruncateTableAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/drop/AbstractDropPartitionAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/BaseSemanticAnalyzer.java
Iceberg tables are unpartitioned from the HMS's POV even when the underlying Iceberg table itself is partitioned. It is non-user-friendly to leak this implementation detail to the user, and let them face a SemanticException saying it's an unpartitioned table. Instead, we should introduce some point at which we throw a unified exception message saying it's an unsupported op.
=> Handle Iceberg queries with partition clauses

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/ExpressionToOrcSearchArgument.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/VectorizedReadUtils.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcInputFormat.java, serde/src/java/org/apache/hadoop/hive/serde2/ColumnProjectionUtils.java
HIVE-25256 added support for Iceberg backed tables to support CHANGE COLUMN statement. These include type, name and order changes to the schema. Native ORC tables only support renames, but with the help of Iceberg as an intermediary table format layer, this can be achieved, and works well for non-vectorized reads already.
We should adjust the vectorized read path to support the same.
This change makes vectorized orc reads relies on Iceberg on finding out about column renames and reorders, so that the low level ORC vectorized reader can be appropriately configured.
=> HIVE-25360

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java, iceberg/iceberg-handler/src/test/queries/negative/truncate_iceberg_table_external_purge_false.q, iceberg/iceberg-handler/src/test/queries/negative/truncate_iceberg_table_with_partition_spec.q, iceberg/iceberg-handler/src/test/queries/positive/truncate_force_iceberg_table.q, iceberg/iceberg-handler/src/test/queries/positive/truncate_iceberg_table.q, iceberg/iceberg-handler/src/test/queries/positive/truncate_partitioned_iceberg_table.q, iceberg/iceberg-handler/src/test/results/negative/truncate_iceberg_table_external_purge_false.q.out, iceberg/iceberg-handler/src/test/results/negative/truncate_iceberg_table_with_partition_spec.q.out, iceberg/iceberg-handler/src/test/results/positive/truncate_force_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/truncate_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/truncate_partitioned_iceberg_table.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/misc/truncate/TruncateTableAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp, standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/TruncateTableRequest.java, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/TruncateTableRequest.php, standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py, standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Added support for TRUNCATE TABLE operation for Hive Iceberg tables. Since these tables are unpartitioned in Hive, only the TRUNCATE without partition spec is supported.
Had to extend the thrift API: added the EnvironmentContext parameter to the TruncateTableRequest class. This is needed because for Iceberg tables the data deletion will happen through the Iceberg API in a MetastoreHook and not in the Metastore itself. It is because for Iceberg table we cannot delete the files manually from metastore since this way the table history would be lost.
The TRUNCATE operation will work for Iceberg tables.
Added unit test and q test for the many use cases.
=> HIVE-25325: Add TRUNCATE TABLE support for Hive Iceberg tables

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerWithEngine.java
Allows Iceberg table update columns command
non-HiveCatalog based Iceberg tables need to be able to refresh the column list in the HMS DB
Allows Iceberg table update columns command
Added the command to the relevant unit tests
=> HIVE-25361: Allow Iceberg table update columns command

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java, iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveSchemaUtil.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Fix the conversion of the HiveSchema
Fix the bug
Fixing the bug
Added unit tests
=> HIVE-25377: Creating Iceberg table where some columns has comments but the last one does not fails

pom.xml, standalone-metastore/pom.xml
This PR aims to bump ORC to 1.6.9.
This will bring the latest bug fixes like ORC-804 .
No.
Pass the CIs.
=> HIVE-25384: Bump ORC to 1.6.9

ql/src/test/queries/clientpositive/autoColumnStats_2.q, ql/src/test/results/clientpositive/llap/autoColumnStats_2.q.out, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdateStat.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
For the path where stats merge is done, optimisation using direct sql was missing. Now if the direct sql mode is enabled, the stats are collected in a map and updated in a batch.
perf improvement.
No
Ptest.
=> HIVE-25342 : Optimize set_aggr_stats_for for mergeColStats path.

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregateIncrementalRewritingRuleBase.java, ql/src/test/queries/clientpositive/materialized_view_create_rewrite_4.q, ql/src/test/queries/clientpositive/materialized_view_create_rewrite_5.q, ql/src/test/queries/clientpositive/materialized_view_create_rewrite_6.q, ql/src/test/queries/clientpositive/materialized_view_create_rewrite_7.q, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_7.q.out
Insert overwrite MV rebuild plans root operator is an Aggregate operator which contains `sum0` function if the MV definition has `count` aggregate function call. The incremental rebuild plan is going to be a Project which contains `case` expressions for each aggregate function call in the original plan. Add `sum0` function to the list of functions which can be transformed to `case` expression.
Enable MVs containing count aggregate functions.
No.
Run existing MV rebuild tests and added a new one targeting MV with count.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_create_rewrite.q,materialized_view_create_rewrite_2.q,materialized_view_create_rewrite_3.q,materialized_view_create_rewrite_4.q,materialized_view_create_rewrite_ …
```
=> HIVE-25369: Handle Sum0 when rebuilding materialized view incrementally

ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/BufferedVectorizedRowBatch.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorAbstractLeadLag.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorBase.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorLag.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFEvaluatorLead.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFGroupBatches.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorPTFOperator.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/ptf/VectorSpillBlockContainer.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java, ql/src/java/org/apache/hadoop/hive/ql/plan/PTFDesc.java, ql/src/java/org/apache/hadoop/hive/ql/plan/VectorPTFDesc.java, ql/src/java/org/apache/hadoop/hive/ql/plan/VectorPTFInfo.java, ql/src/test/queries/clientpositive/vector_ptf_bounded_start.q, ql/src/test/queries/clientpositive/vector_ptf_lead_lag.q, ql/src/test/results/clientpositive/llap/pcs.q.out, ql/src/test/results/clientpositive/llap/ptf.q.out, ql/src/test/results/clientpositive/llap/vector_ptf_bounded_start.q.out, ql/src/test/results/clientpositive/llap/vector_ptf_lead_lag.q.out, ql/src/test/results/clientpositive/llap/vector_ptf_part_simple.q.out, ql/src/test/results/clientpositive/llap/vector_windowing.q.out, ql/src/test/results/clientpositive/llap/vector_windowing_expressions.q.out, ql/src/test/results/clientpositive/llap/vector_windowing_gby2.q.out, ql/src/test/results/clientpositive/llap/vector_windowing_navfn.q.out, ql/src/test/results/clientpositive/llap/vector_windowing_rank.q.out, ql/src/test/results/clientpositive/llap/vectorized_ptf.q.out
Implement vectorized evaluators for lead and lag functions.
For better vectorization coverage (performance).
No.
Performance tested on cluster, added new qtests + old qtests got vectorized without query result change.
=> HIVE-24945: Support vectorization for lead/lag functions

ql/src/java/org/apache/hadoop/hive/ql/udf/ptf/ValueBoundaryScanner.java, ql/src/test/org/apache/hadoop/hive/ql/udf/ptf/TestValueBoundaryScanner.java
Introduced faster TimestampWritableV2 handling into isDistanceGreater method.
Performance improvement.
No.
Unit test included, behavior is the same before/after the patch. Tested on cluster.
=> HIVE-25058: PTF: TimestampValueBoundaryScanner can be optimised during range computation pt2 - isDistanceGreater

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, itests/hive-unit/src/test/java/org/apache/hive/service/server/InformationSchemaWithPrivilegeTestBase.java
https://issues.apache.org/jira/browse/HIVE-25391
Turning off privilege synchronizer by default.
priv sync becomes expensive in lot of env depending on number of tables, table width etc. And not many are using it (i.e information_schema). Hence turning off by default and let users choose to enable it on need basis.
no
=> HIVE-25391: Turn off priv synchronizer by default

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
https://issues.apache.org/jira/browse/HIVE-25014
Table details were fetched multiple times within column stats updation. Depending on the width of the table, this was called multiple times. Datanuc* moves from persistent -> detached state on commit. https://www.datanucleus.org/products/accessplatform_4_2/jpa/object_lifecycle.html.
Since we commit at the end of all processing, fetching table details once is good enough.
No
small internal cluster
=> HIVE-25014: Optimise ObjectStore::updateTableColumnStatistics

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Cleaner.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/Metrics.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
See HIVE-25390
See HIVE-25390
Removes metrics compaction_failed_initiator_ratio and compaction_failed_cleaner_ratio
Changed unit tests
=> HIVE-25390: Metrics compaction_failed_initiator_ratio and compaction_failed_cleaner_ratio should be counters

.github/workflows/auto-assign.yml
Only run of org is apache
Signed-off-by: Josh Soref <jsoref@users.noreply.github.com>
When I create a fork, and then create a PR in that fork, I get half of an error from the auto-assign workflow. Since it's really only configured to work in apache, it shouldn't run in my forks.
Forks by devs will have fewer workflows run
I set the default branch of my fork to this branch and then created a PR from another branch into the default branch. The auto assign workflow was skipped.
I then added an additional commit to the default branch that changed `apache` to the name of the owner of my fork, and pushed that to the fork. And then I closed and reopened the PR, the auto-assign workflow was run.
=> HIVE-25415: Disable auto-assign reviewer on forks

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/VectorizedRowBatchIterator.java, iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read.q, iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read.q.out
Similarly to HIVE-25360 reordering partition columns can cause a problem, this time when constant value filling happens for partition columns. Column indices must be mapped to the current schema (which may contain the columns reordered)
=> HIVE-25376

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Use `REPLACE COLUMNS` only for dropping one or more columns. If there's any column reorder, column rename, adding columns, changing column type or changing column comment, we throw an exception.
Limit the damage the user can do with this command :)
Yes, limitation of the REPLACE command (but only for Iceberg tables; Hive tables are unaffected).
unit tests
=> HIVE-25328: Limit scope of REPLACE COLUMNS for Iceberg tables

ql/src/test/queries/clientpositive/nullBitVectorStats.q, ql/src/test/results/clientpositive/llap/nullBitVectorStats.q.out, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/StatObjectConverter.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/model/MPartitionColumnStatistics.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/model/MTableColumnStatistics.java
While getting the stats from the backend database, convert the bit vector column having magic value ("HL") with null bit vector.
Causes exception while merging the stats in Postgres backend 
No
Unit tested
=> HIVE-25417 : Null bit vector is not handled while getting the stats for Postgres backend

data/scripts/derby/q_test_extDB_cleanup.derby.sql, data/scripts/derby/q_test_extDB_init.derby.sql, data/scripts/mysql/q_test_extDB_cleanup.mysql.sql, data/scripts/mysql/q_test_extDB_init.mysql.sql, data/scripts/postgres/q_test_extDB_cleanup.postgres.sql, data/scripts/postgres/q_test_extDB_init.postgres.sql, itests/qtest/pom.xml, itests/qtest/src/test/java/org/apache/hadoop/hive/cli/TestMiniLlapExtDBCliDriver.java, itests/src/test/resources/testconfiguration.properties, itests/util/src/main/java/org/apache/hadoop/hive/cli/control/AbstractCliConfig.java, itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CliConfigs.java, itests/util/src/main/java/org/apache/hadoop/hive/cli/control/CoreCliDriver.java, itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestArguments.java, itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestExternalDB.java, itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java, itests/util/src/main/java/org/apache/hadoop/hive/ql/externalDB/AbstractExternalDB.java, itests/util/src/main/java/org/apache/hadoop/hive/ql/externalDB/MySQLExternalDB.java, itests/util/src/main/java/org/apache/hadoop/hive/ql/externalDB/PostgresExternalDB.java, ql/src/test/queries/clientpositive/dataconnector_mysql.q, ql/src/test/results/clientpositive/llap/dataconnector_mysql.q.out, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/dataconnector/jdbc/MySQLConnectorProvider.java, testutils/ptest2/conf/deployed/master-mr2.properties
[HIVE-25423](https://issues.apache.org/jira/browse/HIVE-25423): Add new test driver to automatically launch and load external database.
Add new test driver - **TestMiniLlapExtDBCliDriver** - which has the ability to automatically launch external database with custom SQL script(default init and cleanup script located at data/script/[databaseType]). Moved dataconnector.q test to test suite **externalDB.llap.query.files**
To run tests:
`mvn test -Dtest=TestMiniLlapExtDBCliDriver -Dqfile=xxxxxx.q`
Add new test dataconnector_mysql.q to benchmark the new test driver's loading ability, desired output located in dataconnector_mysql.q.out.
Currently this test driver only support mysql external database launching. Postgres and Derby support will land sequentially.
=> HIVE-25423: Add new test driver to automatically launch and load external database (Same as PR#2559, squashed commit for test trigger)

ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFFromUnixTime.java, ql/src/test/org/apache/hadoop/hive/ql/udf/generic/TestGenericUDFFromUnixTime.java, ql/src/test/queries/clientpositive/foldts.q, ql/src/test/queries/clientpositive/udf5.q, ql/src/test/results/clientpositive/llap/foldts.q.out, ql/src/test/results/clientpositive/llap/udf5.q.out
**What changes were proposed in this pull request?**
i) Fixed the code in the evaluate() in GenericUDFFromUnixTime to consider leap seconds.
ii) Refactor GenericUDFFromUnixTime class to make code much more clean and readable.
**Why are the changes needed?**
SELECT from_unixtime(unix_timestamp(cast('1400-01-01' as date)));
was giving wrong results, because the from_unixtime() function was not considering leap seconds while representing Timestamp. So it was required to change the epoch time in the
from_unixtime() to ZonedDateTime.
The required conversion was done with the help of the Instant class, which represents a moment given the epoch time. 
**Does this PR introduce any user-facing change?**
No
**How was this patch tested?**
Added relevant qtests in udf5.q
=> HIVE-25403: Fixing from_unixtime() in GenericUDFFromUnixTime class so as to consider leap seconds

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransformSpec.java
Currently ALTER TABLE CHANGE COLUMN statement only updates the Iceberg-backed table's schema, but not it's partition spec. Updating the spec is required to allow subsequent partition spec changes (like set partition spec calls) to succeed.
Note: to do this in HiveIcebergMetaHook class we can't just create an updateSchema and an updatePartitionSpec object, do the modifications and commit both of them, as the last commit will fail due to invalid base. We might want to do this in two separate steps instead.
=> HIVE-25375

ql/src/java/org/apache/hadoop/hive/ql/exec/repl/DirCopyTask.java, shims/0.23/src/main/java/org/apache/hadoop/hive/shims/Hadoop23Shims.java
Problem: Concurrency issues.
We were using same conf object across multiple threads. So, if one thread unsets 'mapred.mapper.new-api', this change would be reflected in other threads also and ultimately resulting in distcp job failure.
=> HIVE-25433: DistCp job fails with yarn map compatibility mode issue.

ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFDateDiffColCol.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFDateDiffColScalar.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorUDFDateDiffScalarCol.java, ql/src/test/org/apache/hadoop/hive/ql/exec/vector/expressions/TestVectorGenericDateExpressions.java, ql/src/test/queries/clientpositive/udf_datediff_with_tz.q, ql/src/test/results/clientpositive/llap/udf_datediff_with_tz.q.out
Please find the repro and detailed description here - https://issues.apache.org/jira/browse/HIVE-25449
Removed usage of SimpleDateFormat which was using local timezone parsing scalar dates. 
This fixes the bug described in the Jira and datediff() now gives correct values.
No
Manual testing and added two new unit tests - testDateDiffColScalarWithTz() and testDateDiffScalarColWithTz()
=> HIVE-25449: datediff() gives wrong output when run in a tez task with some non-UTC timezone

ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedListColumnReader.java, ql/src/test/org/apache/hadoop/hive/ql/io/parquet/TestVectorizedListColumnReader.java, ql/src/test/queries/clientpositive/parquet_map_null_vectorization.q, ql/src/test/results/clientpositive/llap/parquet_map_null_vectorization.q.out, storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/BytesColumnVector.java
This change prepares parquet VectorizedListColumnReader to read null values properly.
Customers were facing very similar exceptions in the case of null values, the exception was reproducible with qtest.
No.
1. new qtest (fails without the patch)
2. TestVectorizedListColumnReader and TestVectorizedMapColumnReader cover many cases, and helped fixing some issues with the original patch.
=> HIVE-23688: fix Vectorization IndexArrayOutOfBoundsException when read null values in map

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
[HIVE-25277](https://issues.apache.org/jira/browse/HIVE-25277)
Deleting a Hive partition is slow when use a Cloud object store as the warehouse for which ListFiles is expensive. A root cause is that the recursive parent dir deletion is very inefficient: there are many duplicated calls to isEmpty (ListFiles is called at the end). This fix sorts the parents to delete according to the path size, and always processes the longest one (e.g., a/b/c is always before a/b). As a result, each parent path is only needed to be checked once.
It improves partition deletion time. The improvement is around 7X in our test.
No
Tested partition deletion end-to-end.
=> HIVE-25277: fix slow partition deletion issue by removing duplicated isEmpty checks.

metastore/src/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Use `alter_partition`, `alter_partitions` when `EnvironmentContext` is null.
[HIVE-12730](https://issues.apache.org/jira/browse/HIVE-12730) uses `alter_partition_with_environment_context` and `alter_partitions_with_environment_context` instead of `alter_partition` and `alter_partitions` when the `EnvironmentContext` is null.
This causes the client version to be greater than 2.1 to connect to server<2.1, and this error will occur.
```java
Caused by: org.apache.thrift.TApplicationException: Invalid method name: 'alter_partitions_with_environment_context'
at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_alter_partitions_with_environment_context(ThriftHiveMetastore.java:2843)
at …
```
=> HIVE-25500: Switch back to alter_partition(s) in HMS client for Hive 2.3.x

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/exec/SerializationUtilities.java, ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java, ql/src/java/org/apache/hadoop/hive/ql/plan/MapWork.java, ql/src/test/org/apache/hadoop/hive/ql/exec/TestSerializationUtilities.java
While serializing MapWork objects, some of the properties in pathToPartitionInfo's PartitionDesc objects can be removed.
+ I grabbed the opportunity to remove the clonePlan flag from the affected codepath as it hasn't had any effect on the serialization itself.
Due to performance reasons, please refer to Jira description.
No.
Tested with vectorization_part.q test with different options:
```
set hive.plan.mapwork.serialization.skip.properties=.*; <-- fails, all props are removed
set hive.plan.mapwork.serialization.skip.properties=num.*; <-- regex match: numRows, numFiles
set hive.plan.mapwork.serialization.skip.properties=rawDataSize,totalSize; <-- exact match: rawDataSize,totalSize
set hive.plan.mapwork.serialization.skip.properties=.*Size,serialization.ddl; <-- regex+exact match: …
```
=> HIVE-25501: Provide a configurable filter for removing useless properties from PartitionDesc objects before MapWork serialization

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorThread.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java
=> HIVE-25393: Prevent concurrent compaction and DDL operations

iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestHelper.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergTestUtils.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
- Add a couple of new helper methods to TestHelper and TestTables so we can easily create tables with V2 (formatVersion=2)
- Create new TestHiveIcebergV2 test suite for testing reads/writes to V2 tables with deletes
- Create new test util methods to create equality and position delete files in tests
=> HIVE-25529: Test reading/writing V2 tables with delete files

ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLDesc.java
Advance the write ID by default for DDLs. 
We have to advance the write ID for the all DDLs, so that we can provide strong consistency while serving table metadata from HMS cache. 
No
By current tests
=> Hive-25460 : Advance the Write ID by default 

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HiveAggregateSortLimitRule.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/test/queries/clientpositive/topnkey_gby_limit.q, ql/src/test/results/clientpositive/llap/bucket_groupby.q.out, ql/src/test/results/clientpositive/llap/filter_union.q.out, ql/src/test/results/clientpositive/llap/groupby1_limit.q.out, ql/src/test/results/clientpositive/llap/limit_pushdown.q.out, ql/src/test/results/clientpositive/llap/limit_pushdown4.q.out, ql/src/test/results/clientpositive/llap/offset_limit_ppd_optimizer.q.out, ql/src/test/results/clientpositive/llap/topnkey_gby_limit.q.out
Create Calcite rule to add sorting to `HiveSortLimit` operators above `HiveAggregates` which have aggregate functions.
Queries with Group by and Limit without Order by has a physical plan which may generates wrong results. See jira for details.
Yes. Fix possible correctness issues.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=topnkey_gby_limit.q -pl itests/qtest -Pitests
```
=> HIVE-24579: Incorrect Result For Groupby With Limit

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveTableBaseTest.java, iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveTableTest.java
For all Iceberg table operations (select, insert, alter, etc..) Hive tries to load the Iceberg table by reading in its metadata files.
If these metadata files are not present or are inaccessible for any reason, then operations on such a table will result in a long > 10 minutes hang for the user's session. This is because there's a retry logic with exponential intervals, and 21 retries by default in place.
We should make the retry count configurable, and with a lower default setting.
=> HIVE-25563

ql/src/test/org/apache/hadoop/hive/metastore/txn/TestTxnHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
Add missing bracket when assembling direct sql query to get materialization invalidation info.
The query was syntactically incorrect and blocked incremental materialized view rebuild when one or more MV source table had uncommitted transaction when the MV was last rebuilt and the snapshot was taken however they might be committed later and has an affect on the next MV rebuild.
No.
```
mvn test -Dtest=TestTxnHandler -pl ql
```
=> HIVE-25572: Exception while querying materialized view invalidation info

ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rebuild/AlterMaterializedViewRebuildAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveInsertOnlyScanWriteIdRule.java, ql/src/test/queries/clientpositive/materialized_view_create_rewrite_7.q, ql/src/test/queries/clientpositive/materialized_view_create_rewrite_8.q, ql/src/test/queries/clientpositive/materialized_view_create_rewrite_9.q, ql/src/test/queries/clientpositive/materialized_view_parquet.q, ql/src/test/queries/clientpositive/materialized_view_partitioned_create_rewrite_agg_2.q, ql/src/test/queries/clientpositive/materialized_view_partitioned_create_rewrite_agg_3.q, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_8.q.out, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_9.q.out, ql/src/test/results/clientpositive/llap/materialized_view_parquet.q.out, ql/src/test/results/clientpositive/llap/materialized_view_partitioned_create_rewrite_agg.q.out, ql/src/test/results/clientpositive/llap/materialized_view_partitioned_create_rewrite_agg_2.q.out, ql/src/test/results/clientpositive/llap/materialized_view_partitioned_create_rewrite_agg_3.q.out
1. Add Calcite rule to turn on populating writeId in insert only TableScans.
2. Apply the rule in case of incremental materialized view rebuild
* when there were no delete operations since the last MV rebuild
* or only partition based incremental rebuild can be applied.
Materialized views with insert only source tables can not be rebuilt incrementally.
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_create_rewrite_8.q,materialized_view_create_rewrite_9.q,materialized_view_partitioned_create_rewrite_agg.q,materialized_view_partitioned_create_rewrite_agg_2.q,materialized_view_partitioned_create_rewrite_agg_3.q -pl itests/qtest -Pitests
```
=> HIVE-25546: Enable incremental rebuild of Materialized views with insert only source tables

serde/src/java/org/apache/hadoop/hive/serde2/avro/AvroSerdeUtils.java
This cherry-picks the commit from #1994 (addressing HIVE-24797).
#2699 makes the same change for version 3.1.
=> Backport to 3: HIVE-24797: Disable validate default values when parsing Avro schemas

iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java, ql/src/java/org/apache/hadoop/hive/ql/exec/MapOperator.java
When updating column pruning information `READ_NESTED_COLUMN_PATH_CONF_STR`, update `READ_COLUMN_NAMES_CONF_STR` and `READ_COLUMN_IDS_CONF_STR` as well. 
Iceberg MR queries are failing if multiple tables are queried and several columns are pruned
No
=> HIVE-25673: Column pruning fix for MR tasks

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSplit.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestIcebergInputFormats.java, iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read.q.out, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/HashableInputSplit.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/HostAffinitySplitLocationProvider.java, ql/src/java/org/apache/hadoop/hive/ql/io/BucketizedHiveInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/CombineHiveInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/HiveInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/LlapCacheOnlyInputFormatInterface.java, ql/src/java/org/apache/hadoop/hive/ql/plan/MapWork.java, ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestHostAffinitySplitLocationProvider.java
Since HiveIcebergInputformat doesn't implement any LLAP marker interfaces, cache affinity is never tried, and so any split containing ORC file parts may go to a random LLAP daemon, causing subpar hit ratio later.
So we should:
let HS2 know that cache affinity is required for this inputformat
prevent Iceberg from grouping separate files together in one combined split in case of LLAP execution
provide proper getPath() result for HiveIcebergSplit, so that HostAffinitySplitLocationProvider calculates different hashes for different files (right now getPath() returns table location only)
=> Hive 25651

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaUtil.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSchemaEvolution.java, iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read.q, iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read.q, iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read.q.out, iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read.q.out, iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read.q.out
Revamp the algorithm which detects reordered columns. The current implementation is faulty. The new idea is too look for the column which has the highest index difference between its position in the HMS and Iceberg schemas.
E.g. Current schema: A, B, C, D
New schema (A moved to the end): B, C, D, A
Index difference for each column: A: 3, B: 1, C: 1, D: 1
So we know that A was the one that got moved.
In general, there are 3 scenarios: 
1) highest index diff = 0 -> there were no reorders
2) highest index diff = 1 -> two adjacent columns got swapped with each other:
E.g. A, B, C, D -> A, C, B, D
In this case we cannot identify for sure which one got moved by the user, but we it's okay because we can either do moveAfter(C, A) or moveAfter(B, C), they should be equivalent operations
3) highest …
=> HIVE-25690: Fix column reorder detection for Iceberg schema evolution

ql/src/java/org/apache/hadoop/hive/ql/io/arrow/ArrowColumnarBatchSerDe.java, ql/src/java/org/apache/hadoop/hive/ql/io/arrow/Deserializer.java, ql/src/test/org/apache/hadoop/hive/ql/io/arrow/TestArrowColumnarBatchSerDe.java
…pes When there are more than 1024 values
Instead of initializing the ColumnVector with default size which is 1024, Initialize it with the the size of record size required.
Changes are needed to allow Arrow SerDe to Serialize/deserialize complex data types When there are more than 1024 values
No
Unit test were added to confirm the behaviour
=> HIVE-25443 : Arrow SerDe Cannot serialize/deserialize complex data types When there are more than 1024 values

jdbc/src/java/org/apache/hive/jdbc/HiveStatement.java
Let the JDBC client ignore invalid operation handle problems in case of a close operation.
Because in case of socket timeout and due to the retry logic of HIVE-24786, 2 different close requests can arrive to the same operation, and after thorough testing, it turned out the timing of those are almost undefined (that's why we handled 2 detected cases in the patch)
Yes, if the client logging is set accordingly, WARN level messages will show that an invalid operation handle happened on server side while closing the operation, but the query still succeeds.
Tested on Azure (+AWS) where socket timeout happened quite often.
=> HIVE-25509: CLIService.closeOperation should not fail if operation handle is not present

serde/src/java/org/apache/hadoop/hive/serde2/MultiDelimitSerDe.java
Before HIVE-16922, serdeConstants.collection_delim was equal to 'colelction.delim'
Thus we created our own collection_delim in MultiDelimSerDe with the right typo
Since this has been corrected, we can now put back collection.delim from serdeConstants
Refactoring
No
Existing test
=> HIVE-25679: Use serdeContants collection delim in MultiDelimSerDe

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/security/TestMetastoreClientSideAuthorizationProvider.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
This change will gate #get_table_meta HMS API to abide by any of the authotization model with which the HiveMetastore comes up with
When Apache Hue or any other application which uses #get_table_meta API is not gated to use any of the authorization model which HiveMetastore provides when all  the tables in the database is shown even if the user doesn't have grant access on the database
No
The changes were tested in a customer Hadoop + Hive + Hue cluster with the changes and verified that the tables in the database is not shown  if the user doesn't have grant access on the database
=> HIVE-25680 : Authorize #get_table_meta HiveMetastore Server API to use any of the HiveMetastore Authorization model

ql/src/java/org/apache/hadoop/hive/ql/exec/JoinUtil.java, ql/src/test/queries/clientpositive/sort_merge_join.q, ql/src/test/results/clientpositive/llap/sort_merge_join.q.out
For CommonMergeJoinOperator, the tableDesc will be null in the case that all columns in that table is not used. The tableDesc is null lead to using a dummy row to denote all rows in that table instead of adding row into rowContainer.
However, rows in that table cannot be ignored when it contains filter in on clause.
Reproduced steps are commented in the following ticket.
https://issues.apache.org/jira/browse/HIVE-25721
=> HIVE-25721: Outer join result is wrong

llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/ShuffleHandler.java, llap-server/src/test/org/apache/hadoop/hive/llap/shufflehandler/TestShuffleHandler.java
Initializing shuffle port in the constructor before it's assigned to a random port in start()
Described in jira.
Not really, shuffle port was random until now, user not necessarily noticed.
Tested on Cloudera Warehouse and added unit test.
=> HIVE-25691: LLAP: ShuffleHandler port should respect value in config

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java
We should set abort to true, when we catch any Exception.
For tez engine in our cluster, I found some duplicate line, especially tez speculation is enabled. In partition dir, I found both 000002_0 and 000002_1 exist.
It's a very low probability event. HIVE-10429 has fix some bug about interrupt, but some exception was not caught.
In our cluster, Task receive SIGTERM, then ClientFinalizer(Hadoop Class) was called, hdfs client will close. Then will raise exception, but abort may not set to true.
Then removeTempOrDuplicateFiles may fail because of inconsistency, duplicate file will retain.
(Notes: Driver first list dir, then Task commit file, then Driver remove duplicate file. It is a inconsistency case)
Manual test in our cluster. 
And I add some delay in our test code, then increase the …
=> HIVE-25561: Killed task should not commit file.

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/exec/OrcFileMergeOperator.java, ql/src/java/org/apache/hadoop/hive/ql/hooks/PostExecOrcFileDump.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/FixAcidKeyIndex.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcFileFormatProxy.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcRawRecordMerger.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcAcidRowBatchReader.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcInputFormat.java, ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestInputOutputFormat.java, ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestNewInputOutputFormat.java, ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestOrcFile.java, ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestOrcRecordUpdater.java, ql/src/test/org/apache/hadoop/hive/ql/io/orc/TestOrcSerDeStats.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtilities.java, streaming/src/test/org/apache/hive/streaming/TestStreaming.java
Closing the ORC readers explicitly
This fixes the resource leak where the file readers remain open until a GC cleans them up
No
Unit tests should remain green
=> HIVE-25736: Close ORC readers

ql/src/java/org/apache/hadoop/hive/ql/hooks/HiveProtoLoggingHook.java
If `hive.hook.proto.file.per.event=true` (recommended for S3A filesystem), the Hive proto `EventLogger` will create a new file for each proto event. However, if we already had an appropriate writer (i.e. maybeRolloverWriterForDay() returns false) from some previous operation - we don't close the previous writer instance before creating a new one.
=> HIVE-25741: Close previous writer in proto logger

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/HivePointLookupOptimizerRule.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/RexNodeConverter.java, ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/rules/TestHivePointLookupOptimizerRule.java, ql/src/test/org/apache/hadoop/hive/ql/optimizer/calcite/translator/TestRexNodeConverter.java, ql/src/test/queries/clientpositive/cbo_case_when_wrong_type.q, ql/src/test/results/clientpositive/llap/cbo_case_when_wrong_type.q.out, ql/src/test/results/clientpositive/perf/tpcds30tb/tez/query39.q.out
1) `HivePointLookupOptimizerRule` should not attempt at merging `IN` clauses when the constant types is different, we fix this in the current PR.
2) Another issue emerging in the added qtest query is that constants in `case when` expressions are not typed following the type of the predicate they will be compared too. In the qtest this leads to the creation of `IN` clauses with constants of type `INTEGER` where `SMALLINT` type would have been more appropriate, which makes the optimizer missing opportunities.
1) Merging `IN` clauses with incompatible types can lead to empty results while some are expected.
2) The second issue does not harm correctness but limits rewrite opportunities.
Queries involving `case when` might have better typing for constants and this can lead to further …
=> HIVE-25734: Wrongly-typed constant in case expression leads to incorrect empty result

ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java, ql/src/test/queries/clientpositive/udf_explode.q, ql/src/test/results/clientpositive/llap/udf_explode.q.out
Given two tables:
```
create table source1 (dt string, d1 int, d2 int) stored as orc;
create table source2 (dt string, d1 int, d2 int) stored as orc;
insert into source1 values ('20211107', 1, 2);
insert into source2 values ('20211108', 11, 22);
```
If you run this query with UNION ALL, the `key` column will be missing from the output:
```
select explode(map('D219', D219
,'D220', D220)) as (key, value)
from (
select '20211107' as date_key
,1 as D219
,2 as D220
) t
union all
select explode(map('D221', D221
,'D222', D222)) as (key, value)
from (
select '20211107' as date_key
,1 as D221
,2 as D222
) t
```
Result:
```
1
2
11
22
```
Correct result should be:
```
D219	1
D220	2
D221	11
D222	22
```
(Note: If you run the two subqueries individually, it works fine. The problem occurs with the …
=> Fix projection for union all queries with multiple aliases

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
This patch fixes the following issue: once the compaction worker finishes, commitTxn/abortTxn is invoked first, and the heartbeater thread is only interrupted after that (that's because autoclosable resources in a try-with-resources (`CompactionTxn.close()` in this case) are executed before the finally block). This can lead to race conditions where the txn has already been deleted from the backend DB via commit/abort, but the concurrently running heartbeater thread still attempts to send a last heartbeat after that, but the txn id won't be found in the DB, leading to `NoSuchTxnException`.
=> HIVE-25740: Avoid compaction heartbeater error logging in race conditions

ql/src/java/org/apache/hadoop/hive/ql/DriverTxnHandler.java, ql/src/java/org/apache/hadoop/hive/ql/Executor.java, ql/src/java/org/apache/hadoop/hive/ql/QueryState.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java
This change gives the benefit of query-level HMS response cache to other parts of Hive after analysis.
The specific reason this was investigated was due to the execution time of post-exec hooks - for example the Atlas HiveHook gets metadata for the objects accessed in the query. This can a decent amount of latency retrieving results since it can cause multiple round trips to the HMS.
It should not. It should be transparent and cause performance improvements.
Via existing hive tests and via manual testing with the Atlas post exec hook.
=> HIVE-25768: Extend lifetime of query-level HMS response cache

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
Fix the logic of dropDanglingColumnDescriptors() in direct SQL
A dangling column descriptor might not be deleted via direct SQL
No
A test is added to TestObjectStore to check CDs are cleaned up after partitions dropped
=> HIVE-25773: Column descriptors might not be deleted via direct sql

ql/src/java/org/apache/hadoop/hive/ql/io/CombineHiveRecordReader.java
Enable lazy evaluation for a LOG.debug message in CombineHiveRecordReader.
It became a perf bottleneck, even in case of INFO level logging, because string concatenation was evaluated regardless of logging level.
No.
Tested on customer side on a cluster which hit the perf issue.
=> HIVE-25794: CombineHiveRecordReader: log statements in a loop leads to memory pressure

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestConstraintsMerge.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java, ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java, ql/src/test/results/clientnegative/merge_constraint_notnull.q.out, ql/src/test/results/clientpositive/llap/acid_direct_update_delete_with_merge.q.out, ql/src/test/results/clientpositive/llap/acid_no_buckets.q.out, ql/src/test/results/clientpositive/llap/acid_subquery.q.out, ql/src/test/results/clientpositive/llap/check_constraint.q.out, ql/src/test/results/clientpositive/llap/create_transactional_full_acid.q.out, ql/src/test/results/clientpositive/llap/dynamic_semijoin_reduction_3.q.out, ql/src/test/results/clientpositive/llap/enforce_constraint_notnull.q.out, ql/src/test/results/clientpositive/llap/explain_locks.q.out, ql/src/test/results/clientpositive/llap/insert_into_default_keyword.q.out, ql/src/test/results/clientpositive/llap/masking_acid_no_masking.q.out, ql/src/test/results/clientpositive/llap/semijoin_hint.q.out, ql/src/test/results/clientpositive/llap/sort_acid.q.out, ql/src/test/results/clientpositive/llap/sqlmerge.q.out, ql/src/test/results/clientpositive/llap/sqlmerge_stats.q.out
When generating the  insert part of an update clause of a merge statement replace the default keywords to the corresponding default values defined in default constraints.
To support splitting update clauses of merge statements into two insert branches: one for inserting new values and one for inserting into delete deltas. The first insert doesn't have to be sorted which can give a performance boost. See [HIVE-21158](https://issues.apache.org/jira/browse/HIVE-21158) and [HIVE-21159](https://issues.apache.org/jira/browse/HIVE-21159) for more details.
When `default` keyword is used the optimization can not be triggered because the compilation of the rewritten statement failed.
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=sqlmerge_stats.q …
```
=> HIVE-21172: DEFAULT keyword handling in MERGE UPDATE clause issues

iceberg/pom.xml
Introduce maven `validate.skip` flag to be able to skip checkstyle and spotless checks, which can speed up local development/quick iterations.
Example:
`mvn clean install -Dvalidate.skip`
=> Add flag to skip validate phase for Iceberg module

itests/hcatalog-unit/src/test/java/org/apache/hive/hcatalog/listener/TestDbNotificationListener.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
Metastore client throws an exception when events are cleaned up from the metastore side and the lastEventId which is being requested is too old. However, it is possible that client does not care if the events are in sequence or not. In such a case, client should be able to pass in a flag to ignore throwing the exception and return the remaining events from the server.
Introduces a new HMS client API for a use-case which it doesn't handle currently.
No
Added a new unit test.
=> HIVE-25796: Allow metastore clients to fetch remaining events after cleanup

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/rules/views/HiveAggregateInsertDeleteIncrementalRewritingRule.java, ql/src/test/queries/clientpositive/materialized_view_create_rewrite_6.q, ql/src/test/results/clientpositive/llap/materialized_view_create_rewrite_6.q.out
When generating incremental rebuild plan for MVs having aggregate and delete operations in any source tables check if the view definition contains any `count` aggregate function which has argument. If it has add expression to check if that argument is `null` or not. 
Records with `null` values should not be counted in the final aggregation.
Yes. This patch fixes a data correctness issue.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_create_rewrite_6.q -pl itests/qtest -Pitests
```
=> HIVE-25805: Wrong result when rebuilding MV with count(col) incrementally

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java
Return the output row resolver of an udtf when generating the select clause of the Calcite plan instead of null.
The row Resolver is required several case. One of the is when checking whether the specified column index falls into the correct range when generating the order by operator of a values query.
Values queries don't fail with exception but provides a result when order by is specified with column indexes.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=order_by_pos.q -pl itests/qtest -Pitests
```
=> HIVE-25818: Values query with order by position clause fails

common/pom.xml, common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, common/src/java/org/apache/hadoop/hive/conf/HiveConfUtil.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezSessionState.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java, ql/src/test/org/apache/hadoop/hive/ql/exec/TestHiveCredentialProviders.java, ql/src/test/org/apache/hadoop/hive/ql/exec/tez/TestDagUtils.java
Adapting the changes of HIVE-14822 to Tez.
The actual change is very small:
1. call updateJobCredentialProviders on the needed tez codepaths (session creation + tez dag submission) 
2. adapt updateJobCredentialProviders to needed tez options (only AM needed, details are in code comments)
~~3. depending on HADOOP-18066, setting the hs2 job keystore password into config (+added as redacted), details are on HADOOP-18066~~ <-- not anymore, fixed code in TezSessionState
Tez support.
No.
Tested on cluster against Azure.
=> HIVE-25829: Tez exec mode support for credential provider for jobs

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/InputFormatConfig.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java
Cross-porting https://github.com/apache/iceberg/pull/3752 from Iceberg (commit da712eaf60744c933c08fe1cab7a00cdcb2f4829)
Note: unlike in Iceberg, the default in Hive is `iceberg.mr.config.serialization.disabled=true`.
=> HIVE-25843: Add flag to disable Iceberg FileIO config serialization

bin/hive-config.sh, druid-handler/pom.xml, hbase-handler/pom.xml, jdbc/pom.xml, llap-server/pom.xml, pom.xml, ql/pom.xml, ql/src/java/org/apache/hadoop/hive/ql/log/NoDeleteRollingFileAppender.java, service/pom.xml, testutils/ptest2/pom.xml
This change should mimic what done in the 3.x and master branches to fix the various CVEs related to log4j.
The Apache Bigtop project used the same patch on top of 2.3.6 (released with Bigtop 1.5) and all our build/smoke-tests passed.
More info https://github.com/apache/bigtop/pull/844
=> HIVE-25824: Upgrade log4j dependencies to 2.17.0

ql/src/java/org/apache/hadoop/hive/ql/optimizer/FixedBucketPruningOptimizer.java, ql/src/test/queries/clientpositive/bucketpruning1.q, ql/src/test/results/clientpositive/llap/bucketpruning1.q.out, ql/src/test/results/clientpositive/llap/tez_fixed_bucket_pruning.q.out
This PR adds fix for an easy use case where bucket pruning doesn't work: whenever we see a bucket column in an AND condition with other expressions we should go ahead with the pruning. Currently if these other expressions are not on the leaf level, pruning is turned off for no reason..
=> HIVE-21074

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/test/queries/clientpositive/order_by_pos.q, ql/src/test/results/clientpositive/llap/order_by_pos.q.out
Return the output `RowResolver` object when generating Select logical plan instead of null.
the select row resolver is required for generating Order by logical plan when the columns are referenced by indexes.
No.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=order_by_pos.q -pl itests/qtest -Pitests
```
=> HIVE-25858: DISTINCT with ORDER BY on ordinals fails with NPE

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestFetchWriteIdFromInsertOnlyTables.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorMR.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnLoadData.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnNoBuckets.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java
This PR fixes the issue that the statistics gathering for Query based compactions are not honouring the custom queue settings. It also deprecates the hive.mr.compactor.gather.stats setting which is honoured only by the MR based compactor, and introduces the hive.compactor.gather.stats setting, which is honoured by both MR and Query based compactors. The values of the two settings are combined with logical OR in case of MR based compaction. The stats gathering also changed since there is no need for column based statistics gathering in case of compaction, the basic statistics should be enough.
hive.compactor.job.queue config limits resources available for compaction, so users can limit the effects of compaction on the cluster. However this setting does not affect stats collection which …
=> HIVE-25801: Custom queue setting is not honoured by Query based compaction StatsUpdater

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnStore.java
Store the last run timestamp in the MT_KEY2 column of the AUX table for the initiator, so that its persisted across restarts.
The time of last run is used as a filter when finding compaction candidates.
Because it's only stored in memory, we lose this filtering capability if the service restarts, so it would make sense to persist it.
No.
Manual testing was done.
=> HIVE-25862: Persist the time of last run of the initiator

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
When custom URI resolver is not specified, the default thrift metastore URI goes through DNS reverse resolution (getCanonicalHostname) which is unlikely to resolve correctly when the HMS is sitting behind LBs and proxies. This is a change in behaviour from hive 2.x branch which isn't required. If reverse resolution is required, custom URI resolver can be implemented.
=> HIVE-25646: Thrift metastore URI reverse resolution could fail in some environments

ql/src/java/org/apache/hadoop/hive/ql/parse/ParseUtils.java
(1) Remove unused import
(2) Remove unused method _sameTree(ASTNode node, ASTNode otherNode)_
make code more readable
No
no test
=> HIVE-25828: Remove unused import and method in ParseUtils

standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
Increase default value of "metastore.thread.pool.size" from 10 to 15.
HiveMetastore uses a threadpool to execute tasks listed under "metastore.task.threads.remote" and "metastore.task.threads.always" configs. The size of this threadpool is controlled by "metastore.thread.pool.size" config which by default is set to 10. The number of tasks in the two lists has grown significantly in the last two years, but the size of the pool remained the same.
No
=> HIVE-25889: Increase default value of "metastore.thread.pool.size"

ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/update/MaterializedViewUpdateOperation.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMaterializedViewsRegistry.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/MaterializedViewsCache.java, ql/src/test/org/apache/hadoop/hive/ql/metadata/TestMaterializedViewsCache.java, ql/src/test/queries/clientpositive/materialized_view_partitioned.q, ql/src/test/results/clientpositive/llap/materialized_view_partitioned.q.out
1. Replace ConcurrentMap.compute to computeIfAbsent in MaterializedViewsCache.putIfAbsent
2. Add a new version of `HiveMaterializedViewsRegistry.refresh()`
3. When rebuilding Instead of adding a new instance of the same MV refresh the existing one in the cache.
Using ConcurrentMap.compute enabled adding multiple entries of the same Materialization instance to the sqlText -> materialization map.
`HiveMaterializedViewsRegistry.refresh(HiveConf conf, Table oldMaterializedViewTable, Table materializedViewTable)` did not removed outdated cache entry since a newer version of the passed table object was loaded from MetaStore in `MaterializedViewUpdateOperation`.
No.
```
mvn test -Dtest=TestMaterializedViewsCache -pl ql
mvn test -Dtest.output.overwrite -DskipSparkTests …
```
=> HIVE-24820: MaterializedViewCache enables adding multiple entries of the same Materialization instance

ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveMaterializedViewsRegistry.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/MaterializedViewsCache.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/test/org/apache/hadoop/hive/ql/metadata/TestMaterializedViewsCache.java
`MaterializedViewsCache` nested maps.
```
somedb -> someview -> Materialization
```
1. When removing entries from the inner map check whether that map is empty and remove it from the outer map.
2. Add `isEmpty()` method to `HiveMaterializedViewsRegistry`
See description of jira.
No.
```
mvn test -Dtest=TestMaterializedViewsCache -pl ql
```
=> HIVE-25899: Materialized view registry does not clean dropped views

itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java
Remove the MV entry from `HiveMaterializedViewsRegistry` created by q tests in `QTestUtil`.
Uncleaned `HiveMaterializedViewsRegistry` caused interference with other q tests when running them in batch.
No.
1. Remove the `DROP MATERIALIZED VIEW` statements from some qtests which deals with MVs and run them in batch. Attache a debugger and check the state of `HiveMaterializedViewsRegistry` after each test run in `QTestUtil`.
2. Both tests creates MV with the same name and the interference affects the MV rebuild plan in materialized_view_partitioned_2.q
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_partitioned.q,materialized_view_partitioned_2.q -pl itests/qtest -Pitests
```
=> HIVE-25906: Clean MaterializedViewCache after q test run

ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedListColumnReader.java
Refactor `compareBytesColumnVector(BytesColumnVector cv1, BytesColumnVector cv2)` for better readability, and copy `lcv.child.isNull` to `resultCV.isNull` which was not getting updated earlier.
=> HIVE-25893: NPE when reading Parquet data because ColumnVector isNull[] is not updated

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveFileWriterFactory.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergRecordWriter.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/test/queries/positive/dynamic_partition_writes.q, iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_writes.q.out, iceberg/patched-iceberg-core/pom.xml, iceberg/patched-iceberg-core/src/main/java/org/apache/iceberg/io/ClusteredWriter.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
Currently Hive relies on PartitionedFanoutWriter to write records to Iceberg tables. This has a big disadvantage when it comes to writing many-many partitions, as it keeps a file handle open to each of the partitions.
For some file systems like S3, there can be a big resource waste due to keeping bytebuffers for each of the handles, that may result in OOM scenarios.
ClusteredWriter will only write one file at a time, and will not keep other file handles open, but it will expect that the input data is sorted by partition keys.
=> HIVE-25772: Use ClusteredWriter when writing to Iceberg tables

llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/ShuffleHandler.java
Release the ByteBuf instance at the last usage point instead of releasing the http response.
It threw exceptions silently in ShuffleHandler logs, easily reproducible in TestShuffleHandler.
No.
Rerun TestShuffleHandler, IllegalReferenceCountException disappeared.
=> HIVE-25706: ShuffleHandler: Make sure of properly releasing netty reference counted objects

ql/src/java/org/apache/hadoop/hive/ql/io/parquet/read/DataWritableReadSupport.java
https://issues.apache.org/jira/browse/HIVE-25927
Trivial fix for DataWritableReadSupport to make it more cpu friendly.
Fix n^2 comparisons in getProjectedGroupFields().
No
=> HIVE-25927: Fix DataWritableReadSupport

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorUtil.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java
This PR fixes the issue when the Heartbeater of the CompactionTxn is not shut down. This could happen if an exception is thrown from CompactionTxn.abort() or CompactionTxn.commit() which is not caught by the catch block. The fix reworks heartbeat handling the following way:
1. The heartbeater is shut down BEFORE calling abort() or commit(), so regardless of the outcome of the transaction, or if an exception is thrown or not, the heartbeater won't stay alive. Another benefit that, this approach solves the logging after commit()/abort() issue too, without the need of the previously introduced additional logic (See: HIVE-25740).
To fix the issue that in some cases the heartbeater of a CompactionTxn is not shut down properly.
No.
Through unit tests.
=> HIVE-25898: Compaction txn heartbeating after Worker timeout

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/test/queries/clientpositive/create_view_when_mv_exists.q, ql/src/test/queries/clientpositive/create_view_when_mv_exists2.q, ql/src/test/results/clientpositive/llap/create_view_when_mv_exists2.q.out
Check whether the current command is a create view command when trying to apply materialized view rewrite by exact sql text match.
Rewriting Views to MV scans are not supported currently.
Yes. Such views can be created and no error messages given.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=create_view_when_mv_exists.q,create_view_when_mv_exists2.q -pl itests/qtest -Pitests
```
=> HIVE-25937: Create view fails when definition contains a materialized view definition

ql/src/java/org/apache/hadoop/hive/ql/stats/BasicStatsTask.java, ql/src/test/queries/clientpositive/stats_part_multi_insert.q, ql/src/test/results/clientpositive/llap/stats_part_multi_insert.q.out
When inserting into partitioned tables the list of affected partitions are provided by Dynamic partitioning when updating Statistics. Reload the Partition objects from HMS when `BasicStatsTask` gets them.
All write branches/entities of sql statements has its own `BasicStatsTask` instance which updates the stats of the partition when the statement finished execution. The Tasks are executed sequentially however the state of partitions were loaded only once from metastore by Dynamic partitioning so each `BasicStatsTask` updated the same staring state.
Yes. Incorrect results are fixed.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=stats_part_multi_insert.q -pl itests/qtest -Pitests
```
=> HIVE-25918: Invalid stats after multi inserting into the same partition

pom.xml
Due to [CVE-2021-29425](https://nvd.nist.gov/vuln/detail/CVE-2021-29425) all the commons-io versions below 2.7 are affected.
Tez and Hadoop have upgraded commons-io to 2.8.0 in [TEZ-4353](https://issues.apache.org/jira/browse/TEZ-4353) and [HADOOP-17683](https://issues.apache.org/jira/browse/HADOOP-17683) respectively and it will be good if Hive also follows the same.
=> HIVE-25942: Upgrade commons-io to 2.8.0 due to CVE-2021-29425

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/VectorizedReadUtils.java, iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read_orc.q, iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read_orc.q.out, llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapRecordReader.java
Files of migrated partitioned tables don't contain partition values, however Iceberg's read schema has them. The difference between this read schema and file schema is considered an unsupported schema evolution by LlapRecordReader so it bails out before starting to read.
We should remove identity partition column names from the read the schema, if we find that it's a not an Iceberg-written (so is migrated) file.
=> HIVE-25955: Partitioned tables migrated to Iceberg aren't cached in LLAP

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, ql/src/java/org/apache/hadoop/hive/ql/parse/PartitionTransform.java
Always drop and recreate the full partition specification for Iceberg tables when altering the partition specification.
Also fixed the upper/lower case issue when referencing columns.
Altering the specification parameters were not recognised in the current code, so the specification for those columns are not changed when only the parameters were changed
No
Added unit tests
=> HIVE-25961: Altering partition specification parameters for Iceberg tables are not working

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, service/src/java/org/apache/hive/service/auth/AuthType.java, service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java, service/src/test/org/apache/hive/service/auth/TestAuthType.java, service/src/test/org/apache/hive/service/cli/thrift/ThriftHttpServletTest.java
A new class AuthType is added to support multiple authentication. This class can parse comma separated list of "hive.server2.authentication" and prohibits invalid values in server start-up.
Any password based request in HTTP mode can bypass when SAML is set due to the line below.
```
clientUserName = doPasswdAuth(request, HiveAuthConstants.AuthTypes.NONE.toString());
```
Yes, user can set "hive.server2.authentication" to comma separated list now. We currently support SAML with one password base authentication together.
No new tests added.
=> HIVE-25957: Fix password based authentication with SAML enabled

ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/CompactorTest.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestDeltaFilesMetricFlags.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestDeltaFilesMetrics.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/CodahaleMetrics.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/common/metrics/metrics2/JsonFileMetricsReporter.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/JsonReporter.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MapCapableJsonMetricsModule.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MapMetrics.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/Metrics.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/metrics/TestMetricRegistry.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/metrics/TestMetrics.java
Expose Compaction Observability delta metrics using the JsonReporter
- Custom MapMetrics has been included into the MetricsRegistry.
- The MetricsRegistry will call the listeners for the built-in metrics. Since the MapMetrics is not a built-in one it causing an IllegalArgument Exception. To avoid this exception to happen We handle a specific case.
- A new Jackson JSON module has been added (MapCapableJsonMetricsModule) to add serialization of the `mbeans`
- MapCapableJsonMetricsModule has been registered to the JsonReporter
- AcidMetricsService now leveraging both on the new metrics instead and the MetricsMBeanImpl + JMX
=> HIVE-25959: Expose Compaction Observability delta metrics using the JsonReporter

common/src/java/org/apache/hadoop/hive/common/FileUtils.java, common/src/test/org/apache/hadoop/hive/common/TestFileUtils.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/FileUtils.java
Changes replace to replaceFirst and rather than comparing with FileStatus, changes to compare with the Actual Path
=> HIVE-25960: Fix S3a recursive listing logic.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
StorageDescriptor won't initialize table location in the compile stage.  It will cause null exception when invoke StorageDescriptor getLocation method in IcebergTableUtil.
https://github.com/apache/hive/blob/970c41c302719cdca9bb9d004c6beca19451188b/iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java#L84
I think we can use directly iceberg storage uri with the form **'iceberg://dbName/tableName**'.
No
=> HIVE-25964: Create iceberg table with ranger authorization failed with storage URI NullPointerException

ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestCompactionMetrics.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java
The JsonReporter and JsonFileMetricsReporter writing the same file.
This issue is caused by the HIVE-25842.
Since the Metrics is launching also a JmxExporter the `MetricsFactory.init(conf);` is unnecessary in the HiveMetaStore the delta metrics will be exposed.
This test has been tested manually by checking the JMX console for the reported obsolete delta metrics.
=> HIVE-25973: Fix JsonReporter and JsonFileMetricsReporter writing the same file

ql/src/java/org/apache/hadoop/hive/ql/hooks/PostExecutePrinter.java, ql/src/test/results/clientpositive/llap/stats_part_multi_insert.q.out
Lineage entries are sorted before printing them. The comparator used for the sorting uses the string representation of `Partition` objects for comparing them.
This patch propose to use only the partition values for Partition comparison instead
More than one partition objects may represents the same partition in the lineage info map. This is very common since each column has a different entry but the same partition. There are cases when more than one branches of the statement updates the same partition. In this case properties of the cached Partition objects may different:
```
stats_part PARTITION(p=101).key ...]   -> Partition[(p=101)... transient_lastDdlTime=1645697627,...]
stats_part PARTITION(p=101).value ...] -> Partition[(p=101)... transient_lastDdlTime=1645697627,...]
stats_part …
```
=> HIVE-25979: Order of Lineage is flaky in qtest output

iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveMetastore.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergMigration.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java
During Iceberg table migration of partitioned tables we should drop the partition objects from the HMS.
So we have a clean HMS metastore db
No
The existing unit test are checking the migration path
=> HIVE-25894: Table migration to Iceberg doesn't remove HMS partitions

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/ObjectCache.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezProcessor.java
For branch-2.3 : [CR](https://github.com/apache/hive/pull/3046)
We are closing the cached thread pool which is delaying the tez task jvm shutdown. 
The pool is used for loading [hash table](https://github.com/apache/hive/blob/7b7e8d4d7910b9b6dc2fe498a6a4228c628853c1/ql/src/java/org/apache/hadoop/hive/ql/exec/MapJoinOperator.java#L180) in case of mapjoin operator. 
Without the change, tez task jvm takes upto 1 min to shutdown.
No
Monitored the JVM exit time. 
`2022-02-03 16:47:54,432 [INFO] [main] |util.Debug|: Hook: class org.apache.hadoop.hive.ql.exec.tez.ObjectCache$2
2022-02-03 16:48:04,079 [DEBUG] [Thread-4] |util.ShutdownHookManager|: Completed shutdown in 0.001 seconds; Timeouts: 0
2022-02-03 16:48:04,088 [DEBUG] [Thread-4] |util.ShutdownHookManager|: ShutdownHookManger completed …
=> HIVE-25971: Closing the thread pool created for async cache

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
This PR fixes the isse that if the the delayed cleaner start is enabled, the compaction requests with null CQ_COMMIT_TIME (this can happen if the compaction worker runs on an older version of hive) are never picked up by the cleaner.
This issue can cause that the compaction requests are stuck in 'ready for cleaning' state and accumulating.
No
Through unit and integration tests
=> HIVE-26010: Compactions not picked up by cleaner if CQ_COMMIT_TIME is null and delayed cleaning is enabled

hcatalog/webhcat/java-client/src/main/java/org/apache/hive/hcatalog/api/HCatClientHMSImpl.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/misc/msck/MsckAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/partition/drop/AlterTableDropPartitionOperation.java, ql/src/java/org/apache/hadoop/hive/ql/exec/SerializationUtilities.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/ppr/PartExprEvalUtils.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/ppr/PartitionExpressionForMetastore.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/ppr/PartitionPruner.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionQueryBuilder.java, ql/src/test/org/apache/hadoop/hive/metastore/TestMetastoreExpr.java, ql/src/test/org/apache/hadoop/hive/ql/metadata/TestSessionHiveMetastoreClientListPartitionsTempTable.java
This PR fixes the issue, when compaction fails on tables with boolean partition column.
@zabetak , @kgyrtkirk This PR affects some classes which are really not my table, and I'm unsure if my changes are fine. Could you please also review it?
Compaction must work properly on tables with boolean partition column as well.
No
Using automated tests.
=> HIVE-25645: Query-based compaction doesn't work when partition column type is boolean

common/src/java/org/apache/hadoop/hive/conf/HiveConfUtil.java, llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/AsyncTaskCreateUdfFile.java, llap-server/src/java/org/apache/hadoop/hive/llap/cli/service/LlapServiceDriver.java
In case a command like:
```
hive --skiphadoopversion --skiphbasecp --service jar /usr/lib/hive/lib/hive-llap-server.jar org.apache.hadoop.hive.llap.cli.service.LlapServiceDriver -i 1 -skipValidateConf --partialDownload --downloadType udffile  --hiveconf a=b
```
the configuration a=b doesn't make its way to AsyncTaskCreateUdfFile, and adding a single option or a few options is much easier through --hiveconf than hacking a new config file to the classpath somehow
Describe above.
No.
Tested on cluster by above command.
=> HIVE-26001: LlapServiceDriver: forward hiveconf from commandline to AsyncTaskCreateUdfFile

pom.xml, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/ParquetRecordReaderBase.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java
Had some issues with https://github.com/apache/hive/pull/3091 . Creating separate PR here for HIVE-25845.
Make use of columnindexes when reading parquet files. More details in https://issues.apache.org/jira/browse/HIVE-25845 
Additional note:  Data cache for parquet wasn't there and "wrapPathForCache" has been disabled for parquet reader in VectorizedParquetRecordReader. When data caching with parquet is stabilized with LLAP, this can be re-enabled.
To reduce IO load and improve perf.
No
small internal cluster
With TPCH @ 100 GB scale (customer table has 15000000 records), here is the query which was tried out.
Note that with patch, it reads just 11 MB of data instead of 94 MB without patch. This will be highly beneficial for cloud stores.
select count(*) from customer where c_custkey > …
=> HIVE-25845: Support ColumnIndexes for Parq files

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DirectSqlUpdateStat.java
Fix directsql `FOR UPDATE` to work with all of the databases
`mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=list_bucket_dml_9.q -Dtest.metastore.db=mssql` was failing
Fixing the issue
By running the unit test above
=> HIVE-26040: Fix DirectSqlUpdateStat.getNextCSIdForMPartitionColumnStatistics for mssql

streaming/src/test/org/apache/hive/streaming/TestStreaming.java, streaming/src/test/org/apache/hive/streaming/TestStreamingDynamicPartitioning.java
We should set the warehouse locations in the tests, so the managed location will also be inside the temporary folder. This will prevent the tests to fail, if the previous ones left some directories behind
These tests are often failing on the CI
No
Run the tests manually also used a breakpoint to make sure that the directories are correct
=> HIVE-26042: Fix flaky streaming tests

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
Currently the `create_table_core` api will check if table exists twice, we can remove the second check.
For code improvement.
No
Just remove duplicated code, no additional tests are introduced.
=> HIVE-26016: Remove duplicate table exists check in create_table_core api of HMSHandler

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestObjectStore.java
Some api in ObjectStore invoke `getMTable()` but not check that if the returned value is null, which may cause the NPE, like `addPartitions()`, `addPartition()`, `alterPartition()` et.
Such api described above will check that whether the table exists in `HMSHandler` (first check), but if the table is dropped by other threads after the first check, the NPE will happen.
**The simple idea is that we can check the table each time we get from `getMTable()`.**
To fix the NPE from `getMTable()` while others dropping this table.
No
Just add one test in `TestObjectStore`, can use the minimal test command:
```
mvn test -Dtest=org.apache.hadoop.hive.metastore.TestObjectStore#testPartitionOps -pl :hive-standalone-metastore-server
```
=> HIVE-26036: NPE caused by getMTable() in ObjectStore

packaging/src/main/assembly/src.xml
Remove the generated files from the source tarball
Decreases the probability of an error, and decreases the size of the tarball
No
Created the tarball, checked that the files are not there.
Also run `mvn clean install -DskipTests -Pitests,dist -T8` on the source and checked that the missing files are generated
=> HIVE-26070: Remove the generated files from the source tarball

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
Invalidate acid directory cache on table drop
Cache can give back invalid directory location on table drop if we recreate the same table.
No.
Manual tests as of now.
=> HIVE-26060: Invalidate acid table directory cache on drop table

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergTestUtils.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergCTAS.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java
Implements the following query:
```
CREATE TABLE t PARTITIONED BY SPEC(day(ts)) AS SELECT ...
```
We need to have a way to create a table with the spec
Implements a new syntax
New unit test
=> HIVE-26077: Implement CTAS for Iceberg tables with partition spec

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
When the pre-compaction checks fail in Worker, the compaction state should be set to "REFUSED" instead of "SUCCEEDED" among with the appropriate error message.
The org.apache.hadoop.hive.ql.txn.compactor.Worker#findNextCompactionAndExecute method does several checks (The table/partition exists, is not sorted, there are enough files to compact, etc.) before it actually executes the compaction request. If the compaction request fails on any of these checks, it is put to "SUCCEEDED" state which is often misleading for users. SHOW COMPACTIONS will show these requests as succeeded without an error, while the table is not compacted at all.
No
Manually and through unit tests.
=> HIVE-26026: Use the new "REFUSED" compaction state where it makes sense

iceberg/iceberg-shading/pom.xml, iceberg/patched-iceberg-api/pom.xml, iceberg/patched-iceberg-core/pom.xml, iceberg/pom.xml
Move the patched iceberg modules under org.apache.hive package from org.apache.iceberg
We do not want to accidentally put trash under other projects package
No
Run the compilation
=> HIVE-26099: Move patched-iceberg packages to org.apache.hive group

iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_writes.q.out, ql/src/java/org/apache/hadoop/hive/ql/optimizer/SortedDynPartitionOptimizer.java
Bulk insert into partitioned table creates lots of files in iceberg, because the SortedDynPartitionOptimizer doesn't set the key->reducer affinity that could be done by just marking the sort expressions as 'partition' columns.
=> HIVE-26110

ql/src/java/org/apache/hadoop/hive/ql/parse/ColumnStatsSemanticAnalyzer.java, ql/src/test/queries/clientpositive/columnstats_columnname_parse.q, ql/src/test/results/clientpositive/llap/columnstats_columnname_parse.q.out
Remove second `unparseIdentifier` on `columnName`
`unparseIdentifier` was applied twice on `columnName`
No
`mvn test -pl itests/qtest -Pitests -Dtest=TestMiniLlapLocalCliDriver -Dtest.output.overwrite=true -Dqfile=columnstats_columnname_parse.q`
=> HIVE-25728: ParseException while gathering Column Stats

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java
<!--
Compaction requests originated from an abort of a dynamic partition insert can cause a NPE in Initiator.
Compaction requests originated from an abort of a dynamic partition insert can cause a NPE in Initiator.
No.
Manually and through unit tests.
=> HIVE-26116: Fix handling of compaction requests originating from aborted dynamic partition queries in Initiator

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSplit.java
I originally thought that we only need the hack whenever residuals are present, so I added this condition:
https://github.com/apache/hive/commit/1aa6ce800004798e78ea53c3bec2beedb5f55b6c#diff-9487d7073613adf5132783cf905ea72164eb4c19461c50e5ce3cd735bb5704a3R127
What I didn't know is that in some cases the residuals() invocation may end up returning True while the expression is still some longer construct. The residuals() invocation actually evaluates said expression against the partition information found in the base scan file task... Because of this the residuals are left untouched and will cause OOM.. 
This addendum removes aforementioned unnecessary condition
=> addendum for HIVE-25967

packaging/src/main/assembly/beeline.xml
The jar name the beeline standalone assembly build is looking for, original-jar-with-dependencies.jar, does not match the name of the jar being built by the beeline build, jar-with-dependencies.jar. So the uber jar is not being bundled into the final apache-hive-beeline.xxx.tar.gz
To include the uber jar into the beeline assembly.
No
Manually
=> HIVE-26118: [Standalone beeline] Jar name mismatch in assembly (Naveen Gangam)

ql/src/test/queries/clientpositive/serde_multi_delimit.q, ql/src/test/results/clientpositive/llap/serde_multi_delimit.q.out, serde/src/java/org/apache/hadoop/hive/serde2/lazy/LazyStruct.java
To support reading single column from a text table which is delimited by multiple characters.
Select query fails without this fix.
No
testcase is included in the patch
=> HIVE-26096: Select on single column MultiDelimitSerDe table throws AIOBE

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableOperation.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadWork.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/table/LoadPartitions.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/bootstrap/load/table/LoadTable.java, ql/src/java/org/apache/hadoop/hive/ql/parse/ReplicationSpec.java, ql/src/java/org/apache/hadoop/hive/ql/plan/ImportTableDesc.java
Rather than dropping tables, overwrite the metadata of the tables, so that data copy can be optimised
=> Hive 25921: Overwrite table metadata for bootstraped tables.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSplit.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/VectorizedReadUtils.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestIcebergInputFormats.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestInputFormatReaderDeletes.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestIcebergInputFormats.java
The filter expression that goes with the file scan tasks is actually not a "residual" one, but rather the original data filter. This is good for us, as now we know that for any Hive job the expression is the same object - so we can transfer it another way to Hive execution processes:
- The expression itself is generated via https://github.com/apache/iceberg/blob/master/mr/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java#L82-L93 before split generation within the AM. There's nothing to prevent us from reusing this same logic on the executors.
- At the same time we can ask ignoreResiduals() on the table scan, so that Iceberg only uses the filter for split generation, but won't actually attach it to the file scan tasks, and therefore their enwrapping splits.
- On the …
=> HIVE-26137 Optimized transfer of Iceberg residual expressions from AM to execution

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergDeleteWriter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergRecordWriter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergWriter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergAcidUtil.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java, iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_avro.q.out, iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/delete_iceberg_partitioned_parquet.q.out
While `HiveIcebergRecordWriter` always writes data out according to the latest spec, the `HiveIcebergDeleteWriter` might have to write delete files into partitions that correspond to a variety of specs, both old and new. Therefore we should pass the `table.specs()`map into the `HiveIcebergWriter` so that the delete writer can choose the appropriate spec on a per-record basis.
This PR also fixes the issue that we shouldn't sort by the bucket value for delete queries (as we do for regular writes), as it can mess up the ordering of the incoming records to the delete writer. In case of deletes, the records are already clustered together using the hash of the partition struct.
=> HIVE-26156: Iceberg delete writer should handle deleting from old partition specs

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/orc/VectorizedReadUtils.java
For schema evolution and projection purposes we produce an ORC file footer byte buffer in VectorizedReadUtils.
Currently Iceberg's bundled/shaded ORC is used to produce these file footer bytes when dealing with Iceberg/ORC tables. This version of ORC is newer (1.7.3) than what Hive uses (1.6.9).
Later on we could face compatibility issues when trying to reconstruct an OrcTail object with a 1.6.9 reader from the bytes that the 1.7.3 reader serialized. We need to invert the direction as we can rely more on backward compatibility than on forward compatibility of ORC.
=> HIVE-26161 Use Hive's ORC dependency version when producing file footer for Iceberg

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
At present, get_all_tables  method in HMSHandler would not get table from remote database. However, other component like presto and some jobs we developed have used this api instead of get_tables which could retrieve all tables both native database and remote database .
I think we shoud fix get_all_tables to make it retrive tables from remote database.
We can refer to code snippet from  `get_tables`:
https://github.com/apache/hive/blob/a29810ce97a726fc70aecb53ebd648c3237106c4/standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java#L6117-L6122
No
No need test
=> HIVE-26171: HMSHandler get_all_tables method can not retrieve tables from remote database

standalone-metastore/pom.xml
Upgrade cron-utils to 9.1.6.
Fix [CVE-2021-41269](https://nvd.nist.gov/vuln/detail/CVE-2021-41269) issue.
No.
Jenkins
=> HIVE-26032: Upgrade cron-utils to 9.1.6

ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/test/queries/clientpositive/materialized_view_rewrite_by_text_9.q, ql/src/test/results/clientpositive/llap/materialized_view_rewrite_by_text_9.q.out
Temporary apply the `HiveSubQueryRemoveRule` before collecting tables scanned by the initial CBO plan when performing sql text based MV rewrite.
For Materialized View rewrite based on exact sql text match Hive uses the initial CBO plan which may contains sub-query expressions but the algorithm traverse the plan and collects the tables can not handle sub-query expressions.
Yes. If a query plan was rewritten to scan an outdated MV the results can be different.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=materialized_view_rewrite_by_text_9.q -pl itests/qtest -Pitests
```
=> HIVE-26160: Materialized View rewrite does not check tables scanned in sub-query expressions

ql/src/java/org/apache/hadoop/hive/ql/Driver.java
Add the current querystate object to SessionState's QueryStateMap if it's missing.
Many unit tests are initializing the driver object once, but reusing it for all the query executions in the whole test method. Since the queryStateMap in the SessionState is cleared after the first query execution, all subsequent queries will not be able to access the querystate through the SessionState. 
No
=> HIVE-26167: QueryStateMap in SessionState is not maintained correctly

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/GenericUDFIcebergBucket.java, iceberg/iceberg-handler/src/test/queries/positive/dynamic_partition_writes.q, iceberg/iceberg-handler/src/test/results/positive/dynamic_partition_writes.q.out, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedRowBatchCtx.java
Fixes an error when null value is inserted to an Iceberg partitioned table to a partition column
Otherwise an exception is thrown.
No
Enhanced the appropriate unit test
=> HIVE-26193: Fix Iceberg partitioned tables null bucket handling

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInternalRecordWrapper.java, iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_partitioned_table.q, iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_of_partitioned_table.q.out
The following test case surfaced two issues with metadata table queries:
```
CREATE EXTERNAL TABLE `partevv`( `id` int, `ts` timestamp, `ts2` timestamp)  STORED BY ICEBERG STORED AS ORC TBLPROPERTIES  ('format-version'='1');
ALTER TABLE partevv SET PARTITION SPEC (id);
INSERT INTO partevv VALUES (1, current_timestamp(), current_timestamp());
INSERT INTO partevv VALUES (2, current_timestamp(), current_timestamp());
ALTER TABLE partevv SET PARTITION SPEC (day(ts));
INSERT INTO partevv VALUES (100, current_timestamp(), current_timestamp());
select * from default.partevv.partitions;  
```
- NPE for removed partition columns from new specs:
```
Caused by: java.lang.NullPointerException
at org.apache.iceberg.mr.mapreduce.IcebergInternalRecordWrapper.lambda$converter$5(IcebergInternalRecordWrappe …
```
=> HIVE-26189: Iceberg metadata query throws exceptions after partition evolution

iceberg/iceberg-handler/src/test/queries/positive/query_iceberg_metadata_of_partitioned_table.q, iceberg/iceberg-handler/src/test/results/positive/query_iceberg_metadata_of_partitioned_table.q.out
=> HIVE-26189: Iceberg metadata query throws exceptions after partition evolution (addendum)

iceberg/iceberg-handler/pom.xml, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/FilesForCommit.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergBufferedDeleteWriter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergDeleteWriter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergRecordWriter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergUpdateWriter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergWriter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergWriterBase.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergAcidUtil.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/data/IcebergGenerics2.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/TestHelper.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/HiveIcebergWriterTestBase.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergDeleteWriter.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergUpdateWriter.java, iceberg/pom.xml
- Refactor the HiveIcebergWriter-s to have a common interface
- Refactor the FilesForCommit to use Collections instead of Lists.
- Create a HiveIcebergBufferedDeleteWriter to collect the deleted row data in memory and write it out sorted when the writer is closed
- Added tests for different Delete writers
First step for implementing `UPDATE`s.
Not yet
Added unit tests
=> HIVE-26183: Create delete writer for the UPDATE statements

ql/src/java/org/apache/hadoop/hive/ql/hooks/WriteEntity.java, ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
Modify the REPLACE/RENAME COLUMNS operation to not acquire EXCLUSIVE lock limiting the system concurrency.
No
Unit tests
=> HIVE-26023: Non blocking REPLACE, RENAME COLUMNS implementation

iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
Added a new test
To make sure that the delete is working for every type of fields, and it keeps working 
No
Added a unit test
=> HIVE-26200: Add tests for Iceberg DELETE statements for every supported type

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/Catalogs.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java
Provide support for creating iceberg tables using existing metadata
To be able to reuse any metadata. 
`CREATE TABLE icebergTbl STORED BY ICEBERG TBLPROPERTIES('metadata_location'='some_location')` is now supported on Hive Catalog tables.
=> HIVE-26190: Implement create iceberg table with metadata location

parser/src/java/org/apache/hadoop/hive/ql/parse/FromClauseParser.g, parser/src/java/org/apache/hadoop/hive/ql/parse/HiveParser.g, parser/src/java/org/apache/hadoop/hive/ql/parse/IdentifiersParser.g, parser/src/test/org/apache/hadoop/hive/ql/parse/TestParseDefault.java, ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/UnparseTranslator.java, ql/src/test/queries/clientpositive/insert_into_default_keyword_2.q, ql/src/test/results/clientpositive/llap/insert_into_default_keyword_2.q.out
Introduce parser token and rule for `default` keyword.
Use the Token in SemanticAnalyzers when replacing `default` keyword with default constraint values.
Prior this patch 
* the `default` keyword was treated as an identifier.
* and the lookup in the sql text was done by exact match of the string `default` in some cases.
Yes, see jira for example.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=insert_into_default_keyword.q,insert_into_default_keyword_2.q -pl itests/qtest -Pitests
mvn test -Dtest=TestParseDefault -pl parser
```
=> HIVE-25969: Unable to reference table column named default

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/command/CommandAuthorizerV2.java
Resurrecting https://github.com/apache/hive/pull/2583 :
Make tables based on storage handlers authorization (HIVE-24705) configurable.
cc: @saihemanth-cloudera
=> HIVE-25444

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/RawStore.java
We need to improve the ObjectStore.cleanWriteNotificationEvents in the same way as it was done for notification log table in:
https://issues.apache.org/jira/browse/HIVE-24432
=> HIVE-26225: Delete operations in ObjectStore.cleanWriteNotificationEvents should be performed in different transactions

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/BaseReplicationAcrossInstances.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenarios.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/DDLOperationContext.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/DescTableOperation.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/storage/concatenate/AlterTableConcatenateOperation.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
Problems:
1. Some replication tests don't close the ongoing HMS connections.
2. At one place in ReplLoadTask, we initiate a fresh HMS connection but don't close it.
3. In DDLOperationContext.java, sometimes stored Hive db object is closed and a new object is instantiated. In this case, Actual ddl operations (say CreateDatabaseOperation) will make fresh HMS connection in outdated Hive obj and it will never get closed since that this connection is not accessible. This is causing connection leakage.
=> HIVE-26237: Check if replication cause metastore connection leakage

ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFIn.java, ql/src/test/queries/clientpositive/udf_in_binary.q, ql/src/test/results/clientpositive/llap/udf_in_binary.q.out
Fixing the OR condition evaluation for binary types
Fix the wrong query results
Just the fix
Added query test
=> HIVE-26235: OR Condition on binary column is returning empty result

ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFBaseTrim.java, ql/src/test/queries/clientpositive/udf_trim.q, ql/src/test/results/clientpositive/llap/udf_trim.q.out
NULL is a special value in SQL and therefore trim function should return NULL instead of error out. 
Argument object inspector now accommodates NULL value as VOID type.
No.
Added ptest with additional cases.
=> HIVE-24598: handle null in trim function

common/src/java/org/apache/hadoop/hive/common/type/TimestampTZUtil.java, ql/src/test/org/apache/hadoop/hive/ql/io/parquet/serde/TestParquetTimestampUtils.java, ql/src/test/org/apache/hadoop/hive/ql/io/parquet/serde/TestParquetTimestampsHive2Compatibility.java
Timestamps where the year is more than 4 digits will not have an extra + sign in front of them
So these big timestamps could be read and rewritten so they can conform the original 9999 year limit.
Timestamps where the year is more than 4 digits will not have an extra + sign in front of them. Since it was not supported even before this change, I think it is ok to have this in.
=> HIVE-26233: Problems reading back PARQUET timestamps above 10000 years

ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcNewInputFormat.java
This PR aims to use `org.apache.orc.Reader.getSchema` instead of the deprecated `org.apache.orc.Reader.getTypes` API.
`getTypes` was deprecated.
- https://github.com/apache/orc/blob/main/java/core/src/java/org/apache/orc/Reader.java#L144
```java
/**
* Get the list of types contained in the file. The root type is the first
* type in the list.
* @return the list of flattened types
* @deprecated use getSchema instead
* @since 1.1.0
*/
List<OrcProto.Type> getTypes();
```
In addition, AS-IS implementation is only a slow-wrapper.
- https://github.com/apache/orc/blob/1e2962064b209f1b00188877f08d4226da85c640/java/core/src/java/org/apache/orc/impl/ReaderImpl.java#L259-L262
```java
@Override
public List<OrcProto.Type> getTypes() {
return OrcUtils.getOrcTypes(schema);
}
```
- …
=> HIVE-26260: Use `Reader.getSchema` instead of deprecated `Reader.getTypes`

ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java, ql/src/java/org/apache/hadoop/hive/ql/plan/VectorPTFDesc.java, ql/src/test/queries/clientpositive/vector_ptf_1.q, ql/src/test/results/clientpositive/llap/llap_smb_ptf.q.out, ql/src/test/results/clientpositive/llap/semijoin2.q.out, ql/src/test/results/clientpositive/llap/vector_ptf_1.q.out
Convert window function names to lower case when looking up in vectorizable function registry.
Support case insensitivity of window functions when vectorizing PTF operator.
No, but explain vectorization output may change if query has window functions
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=vector_ptf_1.q -pl itests/qtest -Pitests
```
=> HIVE-26274: No vectorization if query has upper case window function

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java
As discussed in [HIVE-25420](https://issues.apache.org/jira/browse/HIVE-25420) time column is not native Hive type, reading it is more complicated, and is not supported for vectorized read when the file format is ORC. Trying this currently results in an exception, so we should make an effort to gracefully fall back to non-vectorized reads when there's such a column in the query's projection.
=> HIVE-25421: Fallback from vectorization when reading Iceberg's time columns

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java
In org.apache.hadoop.hive.metastore.txn.TxnHandler#compact() use the java.sql.PreparedStatement#setXXX methods instead of the org.apache.hadoop.hive.metastore.tools.SQLGenerator#prepareStmtWithParameters() method.
The SQL statement modified by HIVE-26107 in org.apache.hadoop.hive.metastore.txn.TxnHandler#compact is not working with Postgres DB. org.apache.hadoop.hive.metastore.tools.SQLGenerator#prepareStmtWithParameters() can handle only string parameters.
No
Manually and through unit tests
=> HIVE-26267: Addendum to HIVE-26107: perpared statement is not working on Postgres

pom.xml
Upgrade Snappy Java lib
To be able to run build and tests locally on macOS M1 (aarm64)
locally
=> HIVE-26268: Upgrade Snappy to 1.1.8.4

ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java, ql/src/test/org/apache/hadoop/hive/ql/lockmgr/TestDbTxnManager2.java
Now that DDL operations that required EXCLUSIVE lock were migrated to EXCL_WRITE, we can go ahead and remove READ locks
Part of lockless-reads story
No
Unit tests
=> HIVE-26165: Remove READ locks for ACID tables

ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDAFMkCollectionEvaluator.java
This would reduce the time complexity of `COLLECT_SET` from `O({maximum length} * {num rows})` into `O({maximum length} + {num rows})`.
https://issues.apache.org/jira/browse/HIVE-26184
I'm observing some reducers take much time due to this issue.
No
I have run the reproduction case in HIVE-26184 with this patch and confirmed the reduce vertex finished more than 30x faster.
=> HIVE-26184: COLLECT_SET with GROUP BY is very slow when some keys are highly skewed

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, common/src/test/org/apache/hadoop/hive/conf/TestHiveConf.java
Securing the WebUI SSL keystore password
Without the fix the users can see the keystore password of the SSL configured WebUI
No
Already existing test case was extended
=> HIVE-26142: Extend the hidden conf list with webui keystore pwd

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
Performance optimization: the MetaStoreDirectSql#runTestQuery determines whether the direct SQL can be used. Before the fix the code queries the whole DBS table without any filters. The proposed change is to add a filter "WHERE DB_ID=1" which should be fast as it is the primary key for that table.
Performance improvement. With bigger deployments the test query can run 10x faster (~3 ms instead of 30 ms), and this test query runs for every ObjectStore initialization.
No
In my local dev env I've run the "mvn test" successfully in the "standalone-metastore".
=> HIVE-25879: MetaStoreDirectSql test query should not query the whole DBS table

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/ParquetSchemaFieldNameVisitor.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergMigration.java, iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_orc.q, iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_parquet.q, iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_parquet.q.out, iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_parquet.q.out
This PR contains 3 fixes:
- Change iceberg field ID generation while converting hive schema to iceberg schema.
- set vectorization to false if we are reading an array column that contains a non-primitive type element from a parquet file
- resolve NPE while reading a complex type column that contains a non-primitive type element from a parquet file in a migrated table
When converting hive schema to iceberg schema the field ID is generated as we traverse the schema tree in preorder. This can be an issue while converting multiple levels of complex types since iceberg expects that the IDs are generated using a custom tree traversal technique. 
Vectorized reads in parquet of arrays having a non-primitive element is not yet supported in hive
No
Unit test, q test
=> HIVE-26298: Selecting complex types on migrated iceberg table does not work

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationOptimisedBootstrap.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/OptimisedBootstrapUtils.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplLoadTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/AbstractEventHandler.java
Normal Replication => 		A -----------------------------------------------> B 
--------------A went down and B takes over----------
After failover =>			A ←----------------------------------------------- B
This patch solves below two problems:
1. What happens to the openTxns on A post A went down? 
Soln: Reverse replication should abort then on first load operation on A←B.
2. What happens to Repl_Created openTxns on B(opened prior to failover) after reverse replication starts?
Soln: Abort all the repl_created txns on B cluster.
=> HIVE-26316: Handle dangling open txns on both src & tgt in unplanned failover.

ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnArithmeticDecimal64Column.txt, ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnArithmeticDecimal64Scalar.txt, ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnArithmeticDecimal64ScalarUnscaled.txt, ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnBetween.txt, ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnCompareDecimal64Column.txt, ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnCompareDecimal64Scalar.txt, ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnDivideDecimal64Column.txt, ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnDivideDecimal64Scalar.txt, ql/src/gen/vectorization/ExpressionTemplates/Decimal64ColumnScaleUp.txt, ql/src/gen/vectorization/ExpressionTemplates/Decimal64ScalarArithmeticDecimal64Column.txt, ql/src/gen/vectorization/ExpressionTemplates/Decimal64ScalarArithmeticDecimal64ColumnUnscaled.txt, ql/src/gen/vectorization/ExpressionTemplates/Decimal64ScalarCompareDecimal64Column.txt, ql/src/gen/vectorization/ExpressionTemplates/FilterDecimal64ColumnCompareDecimal64Column.txt, ql/src/gen/vectorization/ExpressionTemplates/FilterDecimal64ColumnCompareDecimal64Scalar.txt, ql/src/gen/vectorization/ExpressionTemplates/FilterDecimal64ScalarCompareDecimal64Column.txt, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/CastLongToDecimal64.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/ConvertDecimal64ToDecimal.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/Decimal64ColumnInList.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/FilterDecimal64ColumnBetween.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/FilterDecimal64ColumnInList.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/FilterDecimal64ColumnNotBetween.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/IfExprDecimal64ColumnDecimal64Column.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/IfExprDecimal64ColumnDecimal64Scalar.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/IfExprDecimal64ScalarDecimal64Column.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/IfExprDecimal64ScalarDecimal64Scalar.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/expressions/VectorExpression.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java, ql/src/test/queries/clientpositive/vector_decimal_7.q, ql/src/test/results/clientpositive/llap/vector_decimal_7.q.out
The exception was happening because the code that casts the Decimal64 to
Decimal was not being added in filtered expressions.
Once this code was added, it caused a regression in check_constraint.q. The
reason for this was because we do not want to convert Decimal64 to Decimal
if the expression explicitly handles decimal64 types. A method was added
to these classes that will prevent the conversion in these cases.
=> HIVE-26208: Exception in Vectorization with Decimal64 to Decimal casting

iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/alter_table_to_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_as_fileformat.q.out, iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_by_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_by_iceberg_with_serdeproperties.q.out, iceberg/iceberg-handler/src/test/results/positive/describe_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/truncate_force_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/truncate_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/truncate_partitioned_iceberg_table.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/info/desc/formatter/TextDescTableFormatter.java
Remove the misleading data
So the users should see the correct info only
Removes the data as shown in the test file changes
Unit tests
=> HIVE-26334: Remove misleading bucketing info from DESCRIBE FORMATTED output for Iceberg tables

ql/src/test/queries/clientpositive/msck_repair_hive_25980.q, ql/src/test/results/clientpositive/llap/msck_repair_hive_25980.q.out, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreChecker.java
Remove unnessary fs.exists call in [HiveMetaStoreChecker.checkTable](https://github.com/apache/hive/blob/2a2889a178fa0196c4ddccb38b32a9ba2c58b8f9/standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreChecker.java#L329)
Currently [HiveMetaStoreChecker.checkTable](https://github.com/apache/hive/blob/2a2889a178fa0196c4ddccb38b32a9ba2c58b8f9/standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreChecker.java#L329) checks fs.exists for all the existing partitions one by one, This can be a costly operation for Object/Cloud storage if there are 1000s of partitions as it could run for long time.
We currently get all the partition directories in table path as part of …
=> HIVE-25980: Reduce fs calls in HiveMetaStoreChecker.checkTable

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, hcatalog/server-extensions/src/main/java/org/apache/hive/hcatalog/listener/DbNotificationListener.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/ReplicationTestUtils.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationFilterTransactions.java, ql/src/java/org/apache/hadoop/hive/ql/exec/ReplTxnTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/AbortTxnHandler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/CommitTxnHandler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/OpenTxnHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/events/AbortTxnEvent.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/AbortTxnMessage.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/MessageBuilder.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/json/JSONAbortTxnMessage.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/events/TestAbortTxnEventDbsUpdated.java
Purpose: Currently, all Txn events OpenTxn, CommitTxn, and RollbackTxn are included in the REPL DUMP, even when the transcation does not involve the database being dumped
(replicated). These events are unnecessary and result is excessive space required for the dump, as well as increasing work that results from these events being replayed
during REPL LOAD.
Solution proposed: To reduce this unnecessary space and work, added the hive.repl.filter.transactions configuration property. When set to "true", extra Txn events
will be filtered out as follows: CommitTxn and RollbackTxn are included in the REPL DUMP only if the transaction referenced had a corresponding ALLOCATE_WRITE_ID event
that was dumped. OpenTxn is never dumped, and the OpenTxn event will be implcitly Opened when REPL LOAD …
=> HIVE-26265: Option to filter out Txn events during replication.

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/YarnQueueHelper.java
The Yarn queue check url now called with the HIVE login user's credentials.
The queue check url was called with empty credentials, and therefore failed.
No
Manually
=> HIVE-26352: Tez queue access check fails with GSS Exception on Compaction

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterRegistry.java, iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_avro.q.out, iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/update_iceberg_partitioned_parquet.q.out, iceberg/iceberg-handler/src/test/results/positive/update_iceberg_unpartitioned_parquet.q.out, ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java, ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/session/SessionStateUtil.java
Rewrite update statements of iceberg tables to multi insert statement similarly in case of native acid tables.
When generating the rewritten statement:
* Get the virtual columns from the table's storage handler in case of non native acid tables
* Include the old values to the select clause of the delete branch of the multi insert statement.
When executing the multi insert:
* Two iceberg writers are used which produce a data delta file and a delete delta file. The result of these writers should be merged into one `FilesForCommit` if both writers are run in the same task.
* In case of more complex statements (ex. partitioned and/or bucketed) more than one Tez task produces commit info so this patch enables storing all of them.
* Every `FileSinkOperator` creates its own jobConf instance …
=> HIVE-26319: Iceberg integration: Perform update split early

ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java, ql/src/test/queries/clientpositive/sqlmerge.q, ql/src/test/results/clientpositive/llap/sqlmerge.q.out
Remove extra `,` character after the virtual column `ROW__ID` when generating update branch of merge statements.
Causes parse exception when parsing the rewritten query when both
```
hive.split.update
hive.merge.split.update
```
are false
Yes. No exception should be thrown.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=sqlmerge.q -pl itests/qtest -Pitests
```
=> HIVE-26361: Merge statement compile fails if split update is off

ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java, ql/src/test/results/clientnegative/merge_constraint_notnull.q.out, ql/src/test/results/clientpositive/llap/acid_no_buckets.q.out, ql/src/test/results/clientpositive/llap/dynamic_semijoin_reduction_3.q.out, ql/src/test/results/clientpositive/llap/enforce_constraint_notnull.q.out, ql/src/test/results/clientpositive/llap/insert_into_default_keyword.q.out, ql/src/test/results/clientpositive/llap/semijoin_hint.q.out, ql/src/test/results/clientpositive/llap/sqlmerge.q.out, ql/src/test/results/clientpositive/llap/sqlmerge_stats.q.out
Disable generating auto column stats collecting pipeline in the execution plan in case of Update/Delete/Merge statements.
* Column stats are marked stale after executing Update/Delete/Merge statements because it can not be generated from the changed rows in case of delete operation so adding the pipeline into insert branches of a merge does not makes sense.
* For Update/Delete statements only the way we checking whether adding the pipeline is refactored.
No. But output of explain merge statements may changes.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=sqlmerge.q,sqlmerge_stats.q -pl itests/qtest -Pitests
```
=> HIVE-26365: Remove column statistics collection task from merge statement plan

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestMetaStoreServerUtils.java
Fix a bug in comparing column fields between old table and new table.
Hive is case-insensitive in field name, but some engines are case-sensitive, so when calling `alter_table` the existing column name may not be equal because of the case.
No
We add two unit tests, can be run with command:
```bash
$ mvn test -Dtest=org.apache.hadoop.hive.metastore.utils.TestMetaStoreServerUtils -pl :hive-standalone-metastore-server
```
=> HIVE-26355: Column compare should be case insensitive for name

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DynamicPartitionPruner.java
=> HIVE-26182: Some improvements to make DPP more debuggable

ql/src/java/org/apache/hadoop/hive/ql/optimizer/Optimizer.java, ql/src/test/queries/clientnegative/check_merge.q, ql/src/test/results/clientnegative/check_merge.q.out, ql/src/test/results/clientpositive/llap/acid_no_buckets.q.out, ql/src/test/results/clientpositive/llap/check_constraint.q.out, ql/src/test/results/clientpositive/llap/dynamic_semijoin_reduction_3.q.out, ql/src/test/results/clientpositive/llap/enforce_constraint_notnull.q.out, ql/src/test/results/clientpositive/llap/insert_into_default_keyword.q.out, ql/src/test/results/clientpositive/llap/sqlmerge.q.out, ql/src/test/results/clientpositive/llap/sqlmerge_stats.q.out
Enable constant propagation for merge statments after predicate push down even if CBO succeeded.
CBO can not handle merge statements and enforce constraint call is added after CBO. This case the constant propagator delivered by Hive is called only with the option `ConstantPropagateOption.SHORTCUT` but with this setting the algorithm does not evaluate deterministic functions like `BETWEEN`.
As a result constraint checks having expressions with constants are also evaluated at execution time only.
No. But when submitting a merge statement constraint violations may detected faster.
```
mvn test -Dtest.output.overwrite -Dtest=TestNegativeLlapCliDriver -Dqfile=check_merge.q -pl itests/qtest -Pitests
```
=> HIVE-26371: Constant propagation does not evaluate constraint expressions at merge when CBO is enabled

standalone-metastore/metastore-server/pom.xml, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java, standalone-metastore/pom.xml
This PR is a follow up of HIVE-21456. In our internal testing, we found the following issues and this PR fixes them:
- Http thread pool name was not getting set in Jetty server
- Found an issue in which PersistenceManager object was not getting cleaned up after the completion of a http request. Fixed it by adding a listener in Jetty's connector. The listener listens for the completion of Http request and then closes the RawStore (a thread local entity). The RawStore, in turn, cleans up PersistenceManager. 
- Added jetty's dependency in metastore pom.xml. Earlier this dependency was getting honored from hadoop-common.
- Fixed a unit test  testJDOPersistanceManagerCleanup() in TestHiveMetaStore
To fix issues described above
No
Fixed an existing test i.e testJDOPersistanceManagerCleanup. The …
=> [WIP] HIVE-21456: addendum: Improvements in Thrift over HTTP for Hive MetaStore

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java
Vectorized reading of nested types of Parquet lists or maps is currently not supported by Hive's implementation of vectorized Parquet readers. It's an edge case, but we should fall back gracefully to non-vectorized read mode.
=> HIVE-26410: Reading nested types within maps in Parquet Iceberg is not supported with vectorization

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputCommitter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterBuilder.java, iceberg/iceberg-handler/src/test/queries/positive/merge_iceberg_orc.q, iceberg/iceberg-handler/src/test/queries/positive/merge_iceberg_partitioned_orc.q, iceberg/iceberg-handler/src/test/results/positive/llap/merge_iceberg_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/llap/merge_iceberg_partitioned_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_partitioned_orc.q.out, ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java, ql/src/test/results/clientpositive/llap/acid_direct_update_delete_with_merge.q.out, ql/src/test/results/clientpositive/llap/acid_no_buckets.q.out, ql/src/test/results/clientpositive/llap/acid_subquery.q.out, ql/src/test/results/clientpositive/llap/check_constraint.q.out, ql/src/test/results/clientpositive/llap/create_transactional_full_acid.q.out, ql/src/test/results/clientpositive/llap/dynamic_semijoin_reduction_3.q.out, ql/src/test/results/clientpositive/llap/dynpart_sort_optimization_acid.q.out, ql/src/test/results/clientpositive/llap/enforce_constraint_notnull.q.out, ql/src/test/results/clientpositive/llap/insert_into_default_keyword.q.out, ql/src/test/results/clientpositive/llap/llap_acid.q.out, ql/src/test/results/clientpositive/llap/llap_acid_fast.q.out, ql/src/test/results/clientpositive/llap/masking_acid_no_masking.q.out, ql/src/test/results/clientpositive/llap/runtime_stats_merge.q.out, ql/src/test/results/clientpositive/llap/semijoin_hint.q.out, ql/src/test/results/clientpositive/llap/sort_acid.q.out, ql/src/test/results/clientpositive/llap/sqlmerge.q.out, ql/src/test/results/clientpositive/llap/sqlmerge_stats.q.out
1. Extract common parts which collects and appends the sort and delete columns in case of split update and merge.
2. Merge IcebergWriter data and delete file collections.
3. Append the number of writers in the job to the operationId to generate a unique file name for each writer.
1. Implement merge into iceberg table by reusing split update code parts.
2. A merge with an insert and an update branch has at least two insert IcebergWriters. If the target table is not partitioned no sorting and exchange is required and both FileSink operators wrapping the IcebergWriters are located in the same Reducer and Job.
Yes. Merge statements should not throw any exceptions when the target is an iceberg table.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestIcebergLlapLocalCliDriver …
```
=> HIVE-26385: Iceberg integration: Implement merge into iceberg table

metastore/if/hive_metastore.thrift, metastore/src/gen/thrift/gen-cpp/ThriftHiveMetastore.cpp, metastore/src/gen/thrift/gen-cpp/ThriftHiveMetastore.h, metastore/src/gen/thrift/gen-php/metastore/ThriftHiveMetastore.php, metastore/src/gen/thrift/gen-py/hive_metastore/ThriftHiveMetastore.py, metastore/src/gen/thrift/gen-rb/thrift_hive_metastore.rb
Fix HMS thrift method recv_get_table_objects_by_name's exception list
[HIVE-15062](https://issues.apache.org/jira/browse/HIVE-15062) accidentally removed the HMS thrift method recv_get_table_objects_by_name exception list, after [HIVE-24608](https://issues.apache.org/jira/browse/HIVE-24608), some IT consistently failed because of that.
e.g. `org.apache.hive.metastore.TestSetUGIOnOnlyClient#testSimpleTable`
```
org.apache.thrift.TApplicationException: Internal error processing get_table_objects_by_name
at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:79)
at org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore$Client.recv_get_table_objects_by_name(ThriftHiveMetastore.java:1544)
at …
```
=> HIVE-26434: Fix HMS thrift method recv_get_table_objects_by_name's exception list

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaHook.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java
It is unnecessary to call alter_table_req() twice when running an alter operation on iceberg. The first call should be skipped.
1. Performance considerations. 
2. HMS operation listeners would not be triggered twice. 
No
Manual test.
=> HIVE-26421: HMSClient atler_table_req() is called twice when running an alter operation on iceberg table

llap-server/src/java/org/apache/hadoop/hive/llap/cache/LowLevelLrfuCachePolicy.java, llap-server/src/java/org/apache/hadoop/hive/llap/daemon/impl/LlapPooledIOThread.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java, llap-server/src/test/org/apache/hadoop/hive/llap/cache/TestLowLevelLrfuCachePolicy.java
BPWrapper is used in LRFU cache eviction policy to decrease the time spent waiting for lock on the heap. This is done by adding a buffer as threadlocal and accumulating CacheableBuffer instances there before trying to acquire a lock. This works well when we have threads from pools such as IO-Elevator threads or OrcEncode threads.
For ephemeral threads there's no advantage of doing this as the buffers in threadlocals may never reach the heap or list structures of LRFU, thereby also making evictions less efficient. This can happen e.g. LLAPCacheAwareFS is used with Parquet, where we're using the Tez threads for both execution and IO.
We should disable BPWrappers for such cases.
=> HIVE-26428 Limit usage of LLAP BPWrapper to threads of IO threadpools

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, service/src/java/org/apache/hive/service/auth/jwt/JWTValidator.java, service/src/java/org/apache/hive/service/auth/jwt/URLBasedJWKSProvider.java
Introduce a property to skip SSL cert verification for downloading JWKS in HS2
We usually used a self-signed certificate for a token generation service in testing/staging environment and this kind of certificates is not accepted in JVM. To ease the need of testing, we can use this property to turn off certificate verification for testing purpose.
Yes, users can turn off certificate verification for testing JWT authentication.
Manually tested
=> HIVE-26425: Skip SSL cert verification for downloading JWKS in HS2

metastore/src/java/org/apache/hadoop/hive/metastore/SerDeStorageSchemaReader.java, ql/src/java/org/apache/hadoop/hive/ql/exec/ReplCopyTask.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/AbstractEventHandler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/events/CreateFunctionHandler.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/ReplChangeManager.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/StringUtils.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/ObjectStore.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreServerUtils.java
=> HIVE-22417: Remove stringifyException from MetaStore

common/src/java/org/apache/hadoop/hive/common/type/UnsignedInt128.java, common/src/test/org/apache/hadoop/hive/common/type/TestUnsignedInt128.java
Currently, these method `setV0`, `setV1`, `setV2` of `UnsignedInt128` call `updateCount` directly.
The `updateCount` of `UnsignedInt128` have a lot `if ... else ...` logic.
In fact, we can improve the code by judge `count` field of `UnsignedInt128`.
Improve UnsignedInt128.setV*()
'No'.
Just update the inner implementation.
New test cases.
=> HIVE-26448: Improve UnsignedInt128.setV*()

ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/plan/ExprNodeDescUtils.java
When collecting columns for join's child RS operator's row schema search for all the key column occurrences and add them to the row schema. Name the column using the corresponding key index.
See jira description.
No.
Force calling `checkAndConvertSMBJoin` by setting `mapJoinConversion` to `null` when Converting join to mapjoin by changing the line
https://github.com/apache/hive/blob/8b312d54ea206461cb50450ac95ec267aba60b21/ql/src/java/org/apache/hadoop/hive/ql/optimizer/ConvertJoinMapJoin.java#L158
to
```
MapJoinConversion mapJoinConversion = null;
```
```
set hive.auto.convert.join=true;
set hive.auto.convert.sortmerge.join=true;
set hive.optimize.dynamic.partition.hashjoin=true;
create table LU_CUSTOMER (CUSTOMER_ID int, value string);
create table ORDER_FACT (CUSTOMER_ID int, …
```
=> HIVE-26452: NPE when converting join to mapjoin and join column referenced more than once

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/parquet/ParquetFooterInputFromCache.java, iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read_parquet.q, iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read_parquet.q.out, itests/src/test/resources/testconfiguration.properties, llap-client/src/java/org/apache/hadoop/hive/llap/io/api/LlapIo.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/api/impl/LlapIoImpl.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/LlapOrcCacheLoader.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/OrcEncodedDataReader.java, llap-server/src/java/org/apache/hadoop/hive/llap/io/encoded/SerDeEncodedDataReader.java, ql/src/java/org/apache/hadoop/hive/llap/LlapHiveUtils.java, ql/src/java/org/apache/hadoop/hive/ql/io/SyntheticFileId.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java
This change makes LLAP caching available for Parquet formatted tables stored with Iceberg. 
For Parquet we can only rely on the LlapCacheAwareFS, which is a wrapper for InputStreams opened from files to be swapped by cache buffer reading streams.
I also refactored the FileID generation to remove some code duplication, as previously invoked from ORC, Serde and Parquet readers.
=> HIVE-26115: LLAP cache utilization for Iceberg Parquet files

ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/AuthorizationMetaStoreFilterHook.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/HivePrivilegeObjectUtils.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/DefaultMetaStoreFilterHookImpl.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreFilterHook.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/FilterUtils.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestFilterHooks.java
HMS client-side filter out results of 'show connectors' based on authorization, eg. ranger authorization. 
No
UT and local hive cluster with ranger
=> HIVE-26246: Filter out results 'show connectors' on HMS client-side

ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
When running CTAS Iceberg already maintains a lock on the target table. Since [HIVE-26244] (https://issues.apache.org/jira/browse/HIVE-26244) introduced a new locking mechanism for CTAS queries on any table, the two are clashing, resulting in deadlock.
Deadlock when running iceberg CTAS.
No
Manual test
=> HIVE-26483: Use DDL_NO_LOCK when running iceberg CTAS query

ql/src/java/org/apache/hadoop/hive/ql/exec/repl/util/ReplUtils.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/AtlasDumpBegin.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/AtlasDumpEnd.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/BootstrapDumpBegin.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/BootstrapDumpEnd.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/BootstrapDumpFunction.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/BootstrapDumpTable.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/IncrementalDumpBegin.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/IncrementalDumpEnd.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/IncrementalDumpEvent.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/RangerDumpBegin.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/log/state/RangerDumpEnd.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/AtlasLoadBegin.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/AtlasLoadEnd.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/BootstrapLoadBegin.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/BootstrapLoadEnd.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/BootstrapLoadFunction.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/BootstrapLoadTable.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/DataCopyEnd.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/IncrementalLoadBegin.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/IncrementalLoadEnd.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/IncrementalLoadEvent.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/RangerLoadBegin.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/load/log/state/RangerLoadEnd.java, ql/src/test/org/apache/hadoop/hive/ql/parse/repl/TestReplStateLogTimeFormat.java
converted the time logged in replState from epoch to UTC
to improve debuggability.
=> HIVE-26363: converting replLogger time format from epoch to UTC

ql/src/java/org/apache/hadoop/hive/ql/Driver.java, ql/src/java/org/apache/hadoop/hive/ql/lockmgr/DbTxnManager.java, ql/src/java/org/apache/hadoop/hive/ql/lockmgr/HiveTxnManager.java, ql/src/java/org/apache/hadoop/hive/ql/lockmgr/HiveTxnManagerImpl.java, standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.cpp, standalone-metastore/metastore-common/src/gen/thrift/gen-cpp/hive_metastore_types.h, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/AllocateTableWriteIdsRequest.java, standalone-metastore/metastore-common/src/gen/thrift/gen-php/metastore/AllocateTableWriteIdsRequest.php, standalone-metastore/metastore-common/src/gen/thrift/gen-py/hive_metastore/ttypes.py, standalone-metastore/metastore-common/src/gen/thrift/gen-rb/hive_metastore_types.rb, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClient.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/IMetaStoreClient.java, standalone-metastore/metastore-common/src/main/thrift/hive_metastore.thrift, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/HiveMetaStoreClientPreCatalog.java
The proposed change is to reallocate writeIds during recompilation in the case that a transaction is not out of date. This ensures that writeIds are committed in increasing order. Currently, it is possible for an earlier transaction to commit with a newer writeId than a later transaction. See the JIRA for more information.
Incorrect results are possible without.
It should not (except correct results).
Tested by modifying Hive as described in the JIRA. (User controllable sleeps).
=> HIVE-26472: Allocate new writeIds during re-compilation

ql/src/java/org/apache/hadoop/hive/ql/udf/UDFSubstr.java, ql/src/test/queries/clientpositive/udf_substr.q, ql/src/test/results/clientpositive/llap/udf_substr.q.out, ql/src/test/results/compiler/errors/invalid_function_param2.q.out
Impala allows a bigint as an argument for the substr function.
This will allow Hive substr function to take bigint arguments too.
Allow substr function to take bigint arguments
Extra functionality, in case the param passed in is a bigint instead of an int. No reason why we can't support this.
Yes, we should change our user documentation to show that we allow bigint params
Added unit tests
=> HIVE-26294: Allow substr to take bigint params

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java, iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_as_fileformat.q.out
Hive allows creating tables stored in ORC in two different syntaxes
1. > `STORED AS ORC`
2. > `STORED AS ORCFILE`
When running a create iceberg table statement that is using the second option we should map the `ORCFILE` keyword to `ORC`
The iceberg library throws an exception when the table was created using the `ORCFILE` syntax.
No
=> HIVE-26476: map ORCFILE to ORC while creating an iceberg table

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveIcebergVectorizedRecordReader.java, iceberg/iceberg-handler/src/test/queries/positive/llap_iceberg_read_orc.q, iceberg/iceberg-handler/src/test/results/positive/llap/llap_iceberg_read_orc.q.out
HiveIcebergVectorizedRecordReader currently only sets selectedInUse but not selected that can cause the following exceptions where ORC row level filtering kicks in:
```
Caused by: java.lang.RuntimeException: all is not in sort order and unique
at org.apache.hadoop.hive.ql.exec.vector.expressions.FilterExprOrExpr.subtract(FilterExprOrExpr.java:69)
at org.apache.hadoop.hive.ql.exec.vector.expressions.FilterExprOrExpr.evaluate(FilterExprOrExpr.java:195)
at org.apache.hadoop.hive.ql.exec.vector.expressions.FilterExprAndExpr.evaluate(FilterExprAndExpr.java:42)
at org.apache.hadoop.hive.ql.exec.vector.VectorFilterOperator.process(VectorFilterOperator.java:125)
at org.apache.hadoop.hive.ql.exec.Operator.vectorForward(Operator.java:968)
at …
```
=> HIVE-26506: HiveIcebergVectorizedRecordReader doesn't set the selected array

bin/hive
Adds Hbase Jars in HMS classpath
Tested in actual env.
=> HIVE-26511: Fix NoClassDefFoundError in HMS for HBaseConfiguration.

beeline/src/test/org/apache/hive/beeline/TestBeelineArgParsing.java, pom.xml, standalone-metastore/pom.xml
Upgrade postgres version from 42.2.14 to 42.4.1
CVE and security issues
issues visible in https://mvnrepository.com/artifact/org.postgresql/postgresql
No
Maven build and Unit test.
=> HIVE-26253: upgrade postgresql to 42.4.1 due to security issues

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveSchemaConverter.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergCTAS.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Raise exception when trying to convert hive table to iceberg if the hive table contains CHAR or VARCHAR columns.
Previously CHAR and VARCHAR columns were mapped to STRING columns on the iceberg side since iceberg doesn't have support for those. 
CHAR and VARCHAR types are fixed-length meaning that the values can be shorter than the specified length, and the remaining characters are padded with spaces. These spaces are trimmed during comparison.
When a table is migrated to iceberg the CHAR columns are read as a STRING on the iceberg side, therefore the whole content of the record is considered important. When running a filter against these columns we would need to add the whole content of the record, including white spaces. This can cause confusion since the same query run on a hive and …
=> HIVE-26507: Do not allow hive to iceberg migration if source table contains CHAR or VARCHAR columns

ql/src/java/org/apache/hadoop/hive/ql/exec/FunctionRegistry.java, ql/src/test/results/clientpositive/llap/show_functions.q.out
Remove the unused udf function from being registered, it is just a wrapper class, no need to register and have runtime issues while using it.
=> HIVE-26512: ST_GeometryProcessing is incorrectly registered as function.

ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/grouping_upper_lower_case.q, ql/src/test/results/clientpositive/llap/grouping_upper_lower_case.q.out
Using `equalsIgnoreCase` instead of `equals` to compare String.
Without this change `grouping` and `GROUPING` behaves differently.
No
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dtest.output.overwrite=true -Dqfile=grouping_upper_lower_case.q
=> HIVE-26534: GROUPING() function errors out due to case-sensitivity of function name

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/CompactionMetricData.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
A new metric is added:
Number of 'Initiated' compaction requests per compaction pool.
To be able to properly supervise the pool based compaction.
No
Manually and through unit tests
=> HIVE-26471: New metric for Compaction pooling

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HiveAlterHandler.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/cache/CachedStore.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestHiveAlterHandler.java
Update table column statistic for partitioned tables as well (if exist).
It may happen that table statistic exist for partitioned table in TAB_COL_STATS table (if statistics were calculated through Impala).
No
Manually and through tests
=> HIVE-26504: User is not able to drop table

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java, ql/src/test/queries/clientpositive/acid_stats3.q, ql/src/test/queries/clientpositive/check_constraint.q
The config 'hive.metastore.acid.truncate.usebase' was disabled due to [HIVE-25050](https://issues.apache.org/jira/browse/HIVE-25050) and subsequent patches in master have renamed it to 'hive.acid.truncate.usebase'. However, since the necessary fixes required for this config are already present in the current master branch, we can enable it by default. Hence the scope of this Jira will be to enable this in the master branch only so that eventual releases can benefit from this feature.
To enable a feature by default.
No
Tested on a cluster after enabling by default and existing unit tests are already present for this configuration.
=> HIVE-26536: Enable 'hive.acid.truncate.usebase' by default

pom.xml
version upgrade for h2
To address some CVEs
No
not tested
=> Hive 25945: Upgrade H2 database version to 2.1.214

pom.xml, standalone-metastore/pom.xml
Upgrade Apache Log4j2 to 2.18.0
There are some critical CVEs. 
CVE-2019-17571 (CRITICAL severity) 
CVE-2020-9493 (CRITICAL severity)
CVE-2021-4104 (HIGH severity)
CVE-2022-23302 (HIGH severity)
CVE-2022-23305 (CRITICAL severity)
CVE-2022-23307 (HIGH severity)
No.
Unit tests and maven clean build.
=> Hive Security - Upgrade Apache Log4j to 2.18.0 due to critical CVEs

common/src/java/org/apache/hadoop/hive/ql/ErrorMsg.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/OrcSerde.java, ql/src/test/queries/clientpositive/create_table_like_file_orc.q, ql/src/test/results/clientpositive/llap/create_table_like_file_orc.q.out
CREATE TABLE LIKE syntax was added in https://github.com/apache/hive/pull/3443, and this PR added the ability to create table   based on existing orc files.
It is convenient for user to create a table based on a orc file.
NO
mvn test -Dtest=TestMiniLlapLocalCliDriver -Dqfile=create_table_like_file_orc.q -Dtest.output.overwrite=true
=> HIVE-26551: Support CREATE TABLE LIKE FILE for ORC

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergInputFormat.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_mixed.q, iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_orc.q, iceberg/iceberg-handler/src/test/queries/positive/vectorized_iceberg_read_parquet.q, iceberg/iceberg-handler/src/test/results/positive/alter_multi_part_table_to_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/alter_part_table_to_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/alter_table_to_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_as_fileformat.q.out, iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_by_iceberg.q.out, iceberg/iceberg-handler/src/test/results/positive/create_iceberg_table_stored_by_iceberg_with_serdeproperties.q.out, iceberg/iceberg-handler/src/test/results/positive/describe_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_mixed.q.out, iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/llap/vectorized_iceberg_read_parquet.q.out, iceberg/iceberg-handler/src/test/results/positive/show_create_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/truncate_force_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/truncate_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/truncate_partitioned_iceberg_table.q.out, iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_mixed.q.out, iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/vectorized_iceberg_read_parquet.q.out, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorizedInputFormatInterface.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/physical/Vectorizer.java
Temporary Hack to allow for non mixed ORC tables to support Vectorization
Added Explain vectorization at relevant places
=> HIVE-26529: Iceberg: Fix VectorizedSupport support for DECIMAL_64 in HiveIcebergInputFormat.

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveCommitLock.java, iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommitLocks.java, iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/TestHiveCommits.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/IcebergTableUtil.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveShell.java, iceberg/iceberg-handler/src/test/results/negative/alter_acid_table_to_iceberg_failure.q.out, iceberg/iceberg-handler/src/test/results/negative/alter_managed_table_to_iceberg_failure.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/AbstractAlterTableOperation.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java
Concurrent alter_table calls can interfere and can cause the metadata_location property of an Iceberg table to be messed up.
Basically there's no table level locking for Iceberg tables in Hive during the usual operations, and thus some extra performance related features are available, like concurrent inserts, as opposed to native Hive tables. This was done under the assumption that the optimistic locking pattern that is used in HiveTableOperations protects changing the metadata_location by the use of an HMS table lock there only.
This is fine until some other alter_table calls get into the system such as one from StatTask or DDLTask. Such tasks perform their work as:
- get the current table
- do the alteration
- send the changes via alter_table call to HMS
In between the retrieval of the …
=> HIVE-26576: Alter table calls on Iceberg tables can inadvertently change metadata_location

llap-common/src/java/org/apache/hadoop/hive/llap/tez/Converters.java
Copy of user payload take a few milliseconds sometimes. This delay adds up for all tasks of a single vertex in LlapTaskCommunicator as it processes tasks one by one. User payload never changes in this codepath. Copy used to be made because of limitations of Protobuf library. Protobuf added a UnsafeByteOperations class that avoid copying of ByteBuffers in 3.1 version. This can be resolved now since Protobuf has been upgraded.
To reduce query startup latency by removing unneeded copying of ByteBuffers.
No
Unit and integration tests
=> HIVE-23745: Avoid copying userpayload in task communicator

ql/src/java/org/apache/hadoop/hive/ql/QueryInfo.java, service/src/java/org/apache/hive/service/cli/operation/Operation.java, service/src/java/org/apache/hive/service/cli/operation/OperationLogManager.java, service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java, service/src/java/org/apache/hive/service/cli/session/SessionManager.java, service/src/test/org/apache/hive/service/cli/operation/TestOperationLogManager.java, service/src/test/org/apache/hive/service/cli/operation/TestQueryLifeTimeHooksWithSQLOperation.java, service/src/test/org/apache/hive/service/cli/operation/TestSQLOperationMetrics.java
Proposed change is to separate live query's operation log and historical operation log. Upon operation close, OperationLogManager.closeOperation is called to move the operation log from session directory to historical log dir. OperationLogManager is only responsible to clean up historical operation logs.
This reduces confusion when admin look at operation logs. Also make it easier to add feature to persist history query info and logs, for example onto hdfs/cloud.
No
tested locally
=> HIVE-26564: Separate query live operation log and historical operation log

pom.xml
[HIVE-26594](https://issues.apache.org/jira/browse/HIVE-26594)
Upgrade netty to 4.1.77 due to CVE-2022-24823
Netty is an open-source, asynchronous event-driven network application framework. The package `io.netty:netty-codec-http` prior to version 4.1.77.Final contains an insufficient fix for CVE-2021-21290. When Netty's multipart decoders are used local information disclosure can occur via the local system temporary directory if temporary storing uploads on the disk is enabled. This only impacts applications running on Java version 6 and lower. Additionally, this vulnerability impacts code running on Unix-like systems, and very old versions of Mac OSX and Windows as they all share the system temporary directory between all users. Version 4.1.77.Final contains a patch for this …
=> Upgrade netty to 4.1.77 due to CVE-2022-24823

pom.xml
JIRA: HIVE-26613. Upgrade jettison to 1.5.1 to fix CVE-2022-40149.
=> HIVE-26613. Upgrade jettison to 1.5.1 to fix CVE-2022-40149.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergSelects.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, serde/src/java/org/apache/hadoop/hive/serde2/SerDe.java
Extract the properties set in the SessionConf in HiveIcebergSerde to the JobConf.
Removing the explicit set config in the UT added as a workaround for this case.
=> HIVE-26556: Iceberg: Properties set in HiveIcebergSerde are not propagated to jobconf

ql/src/java/org/apache/hadoop/hive/ql/exec/Utilities.java
Make the Jar path fully qualified, so as to prevent resolution to fs.defaultFs in any application
Some applications don't explicitly assume the path to LFS, rather resolve to fs.defaultFs
Nopes.
Build distribution & tried the same command. Doesn't happen in Tests due to https://github.com/apache/hive/blob/9db31108e1a44b2fb0436134fa78eea79418d4ad/iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java#L249-L252
May be specific to query engines as well. Tez I suppose alway expects the Path to be in LFS
=> HIVE-26614: Fix adding custom jars in Job Classpath.

iceberg/iceberg-catalog/pom.xml, iceberg/iceberg-catalog/src/test/java/org/apache/iceberg/hive/HiveCreateReplaceTableTest.java
https://issues.apache.org/jira/browse/HIVE-26583
We have found that the tests on iceberg-catalog are not running at all and HiveCreateReplaceTableTest.testReplaceTableTxnTableNotExists fails. 
Use `junit-vintage-engine` to enable `junit-jupiter-api` tests running with Junit4 test runner. 
No
- Run HiveCreateReplaceTableTest.testReplaceTableTxnTableNotExists
- Run all tests on iceberg-catalog
=> HIVE-26583: Make tests running on iceberg-catalog

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/AcidMetricService.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/CompactionMetricData.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/metrics/MetricsConstants.java
- Fix the INITIATED PER POOL metric computing by counting all the INITIATED queue items.
- Add 3 new metrics:
-- WORKING PER POOL
-- OLDEST ENQUEUE AGE PER POOL
-- OLDEST START AGE PER POOL
The metric computing introduced was bad because only elements matching the oldestEnqueueTime > element.getEnqueueTime() were counted.
No
Manually
=> HIVE-26471: Addendum: Fix metric computing

iceberg/iceberg-catalog/src/main/java/org/apache/iceberg/hive/HiveTableOperations.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergOutputFormat.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Allow parquet write related configurations via session & Table Properties.
=> HIVE-26608: Iceberg: Allow parquet write properties to iceberg via session conf and Table Properties.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java
[HIVE-26596](https://issues.apache.org/jira/browse/HIVE-26596) took care of maintaining the delete-mode setting on Iceberg V2 tables, but lacks the same for update- and merge modes.
=> HIVE-26635

ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorDeserializeRow.java, ql/src/test/org/apache/hadoop/hive/ql/exec/vector/TestVectorSerDeRow.java, ql/src/test/org/apache/hadoop/hive/ql/exec/vector/VectorRandomRowSource.java, serde/src/java/org/apache/hadoop/hive/serde2/lazy/fast/LazySimpleDeserializeRead.java, serde/src/java/org/apache/hadoop/hive/serde2/lazybinary/fast/LazyBinaryDeserializeRead.java, storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/Decimal64ColumnVector.java, storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/DecimalColumnVector.java, storage-api/src/java/org/apache/hadoop/hive/ql/exec/vector/IDecimalColumnVector.java
A ClassCastException error was being thrown while deserializing a Decimal64Vector.
It is unnecessary for the code to check the DataTypePhysicalVariation property within VectorDeserializeRow.  There is already enough information to determine that the binding should bedone with the Decimal64Vector. So the code now just checks for the instance when deciding on the binding.
Another bug was found while implementing this fix. The Lazy reads were always converting the decimal into its decimal64 form which isn't necessary when there is no decimal64 binding. This code is now pushed into VectorDeserializeRow which is the only place in the repository which references this variable.
See commit description
See commit description
No
=> HIVE-26573: Fix ClassCastException issues for Decimal64 vectorization.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java
Filter out metadata.json when migrating a hive table to iceberg.
When migrating a hive table to an iceberg in certain cases a Runtime exception is raised
ERROR : Failed
java.lang.RuntimeException: s3a://dev-nfqe-base/cc-cdw-nfqe-q7wj9a/archive/env-8pt556/parquet/bakeoff/large/pli/metadata/00000-94fffe5c-c307-4341-9ea3-f5fa4863d301.metadata.json is not a Parquet file. Expected magic number at tail, but found [32, 93, 10, 125]
The hive-to-iceberg table migration has the following logic.
1. In order to walk through all the data files we request a file iterator from the filesystem. This iterator will provide all the references to be able to scan the data files.
2. The new iceberg table is created, meaning that a new entry is added to the hive catalog and on the file system level the metadata …
=> HIVE-26657: [Iceberg] Filter out the metadata.json file when migrating

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/MessageDeserializer.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/json/JSONMessageDeserializer.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/messaging/json/gzip/DeSerializer.java
Add new API for deserialization for commit compaction event
External listeners would be able to read the commit compaction event from the notification log table.
No
Unit tests and local cluster.
=> HIVE-26647: Implemented deserialization API for commit compaction event

beeline/src/main/resources/beeline-log4j2.properties, common/src/java/org/apache/hadoop/hive/conf/Constants.java, jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java, jdbc/src/java/org/apache/hive/jdbc/HttpDefaultResponseInterceptor.java, jdbc/src/java/org/apache/hive/jdbc/HttpRequestInterceptorBase.java, jdbc/src/java/org/apache/hive/jdbc/HttpResponseInterceptorBase.java, jdbc/src/java/org/apache/hive/jdbc/Utils.java, jdbc/src/test/org/apache/hive/jdbc/TestHiveConnection.java, jdbc/src/test/org/apache/hive/jdbc/TestHttpRequestInterceptor.java, service/src/java/org/apache/hive/service/cli/thrift/ThriftHttpServlet.java
=> HIVE-26670: Track every single HTTP request between beeline and hs2

ql/src/java/org/apache/hadoop/hive/ql/exec/tez/DagUtils.java
Improve logging in `DagUtils#localizeResource` to clarify root cause for why localizing a resource has failed.
While creating a Tez session, `DagUtils#localizeResource` is responsible for copying the client's hive-exec.jar into HDFS (`hive.jar.directory`). This process can be triggered from multiple threads concurrently, in which case one thread performs the copy while the others wait, polling for arrival of the destination file.
If there is an `IOException` during this process, it's assumed that the thread attempting the write failed, and all others abort. No information about the underlying `IOException` is logged. Instead, the log states "previous writer likely failed to write." In some cases though, the `IOException` can occur on a polling thread for reasons unrelated to what happened …
=> HIVE-13288: Confusing exception message in DagUtils.localizeResource

.gitignore, pom.xml
The Hive build currently runs with maven-shade-plugin version 3.1.1, released in April 2018. This issue proposes to upgrade to the latest version, 3.4.1, released in October 2022.
The new version by default also generates `dependency-reduced-pom.xml` files, as documented here: [`createDependencyReducedPom`](https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#createDependencyReducedPom). These files don't need to go into source control, and it's common to put a pattern in .gitignore.
See [HIVE-26648](https://issues.apache.org/jira/browse/HIVE-26648) for an example of another patch that is blocked due to a bug in version 3.1.1.
No
I applied the [HIVE-26648](https://issues.apache.org/jira/browse/HIVE-26648) patch locally and tried to build:
```
mvn clean package -Piceberg …
```
=> HIVE-26684: Upgrade maven-shade-plugin from 3.4.1 for bug fixes.

kudu-handler/src/java/org/apache/hadoop/hive/kudu/KuduHiveUtils.java, kudu-handler/src/test/org/apache/hadoop/hive/kudu/TestKuduInputFormat.java
JIRA: HIVE-26705. Fix Typo in hive-kudu-handler.
When reading the code, I found typo and repaired the typo of the moudle.
=> HIVE-26705. Fix Typo in hive-kudu-handler.

ql/pom.xml
Add the RoaringBitmap to hive-exec jar required by iceberg during Runtime for processing delete files.
Queries with Iceberg Table fails
In Actual env. Doesn't reproduces in Unit Test, Maven puts all the jars on the class path, but during execution these jars aren't there at Runtime with Tez
=> HIVE-26709: Iceberg: Count(*) fails for V2 tables with delete files.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveBatchContext.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveBatchIterator.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveIcebergVectorizedRecordReader.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java, ql/src/java/org/apache/hadoop/hive/ql/io/RowPositionAwareVectorizedRecordReader.java, ql/src/java/org/apache/hadoop/hive/ql/io/orc/VectorizedOrcInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java, ql/src/test/org/apache/hadoop/hive/ql/io/parquet/TestVectorizedColumnReader.java, ql/src/test/org/apache/hadoop/hive/ql/io/parquet/VectorizedColumnReaderTestBase.java
Currently we leverage VectorizedOrcRecordReader and VectorizedParquetRecordReader during vectorized Iceberg reads. In order to read V2 tables where delete files with positional deletes are present, we need to make these record reader implementations provide the row number information too.
=> HIVE-26694: Populate file row position information during vectorized Iceberg reads

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergStorageHandlerNoScan.java
Following the same semantics as Hive-Hbase Handler, encode only the relevant components rather than the complete URI
Tested in actual Env
=> HIVE-26707: Iceberg: Write failing due to Ranger Authorization failure.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveBatchContext.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveRow.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveStructLike.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveValueConverter.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/vector/TestHiveIcebergVectorization.java, ql/src/java/org/apache/hadoop/hive/ql/exec/vector/VectorExtractRow.java
In order to utilize the existing DeleteFilter implementation of Iceberg we'll need to provide a row iterator that iterates through the rows of a VectorizedRowBatch instance.
This can be used during a read with positional deletes, but it will be especially required for implementing equality deletes.
A HiveRow concept needs to be created along with a converter class that provides row data information that's usable as an Iceberg Record.
=> HIVE-26696: Implement row iterator for VectorizedRowBatch

hcatalog/core/pom.xml, hcatalog/hcatalog-pig-adapter/pom.xml, hcatalog/pom.xml, hcatalog/server-extensions/pom.xml
Remove hsqldb dependency in hive 
fix cve
no
manual
=> HIVE-26656:Remove hsqldb dependency in hive due to CVE-2022-41853

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, itests/hive-jmh/src/main/java/org/apache/hive/benchmark/ql/exec/DumbTableExport.java, itests/hive-jmh/src/main/java/org/apache/hive/benchmark/ql/exec/TableAndPartitionExportBench.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/TestReplicationScenariosExternalTables.java, ql/src/java/org/apache/hadoop/hive/ql/exec/ExportTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/repl/ReplDumpTask.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/ExportJob.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/ExportService.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/PartitionExport.java, ql/src/java/org/apache/hadoop/hive/ql/parse/repl/dump/TableExport.java, ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java, ql/src/test/org/apache/hadoop/hive/ql/exec/repl/TestReplDumpTask.java, ql/src/test/org/apache/hadoop/hive/ql/parse/repl/dump/TestExportService.java, service/src/java/org/apache/hive/service/server/HiveServer2.java
Currently partitions of table is dump in parallel manner. But if table is not partitioned, it is dumped serially.
This change introduces parallelism at table level as well. A single thread pool which is currently being used
for partition level is also used for table level. The table level dump task is added to same thread pool.
The degree of parallelism depends upon config parameter REPL_PARTITIONS_DUMP_PARALLELISM whose defaul value is 100.
The new ExportService is introduced with this change which would be responsible for exporting table and partitions during repl dump. The ExportService is initialized and configured with thread pools by HiveServer2 service.
A new Hiveconfig variable ie "REPL_TABLE_DUMP_PARALLELISM is introduced to define the number of threads which would be created in …
=> HIVE-26437: Dump unpartitioned tables in parallel.

ql/src/java/org/apache/hadoop/hive/ql/udf/generic/GenericUDFMaskHash.java, ql/src/test/queries/clientpositive/udf_mask_hash_config.q, ql/src/test/results/clientpositive/llap/udf_mask_hash_config.q.out
Fetch the conf from the job context
In Actual Prod the session conf isn't available, it stays NULL, which leads to NPE
Makes the code works.
Tested the actual scenario in the prod cluster. Conf objects are shared in Unit Tests, Added a basic test for sanity to ensure nothing else breaks
SS from the actual env with the fix:
=> HIVE-26724: Mask UDF failing with NPE.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveDeleteFilter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/mapreduce/IcebergInputFormat.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestTables.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/vector/TestHiveIcebergVectorization.java, iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/merge_iceberg_partitioned_orc.q.out
Implement a DeleteFilter that changes an Iterable of VectorizedRowBatches in a way that whenever a new batch is seen in the next() method, we iterate its rows and apply the original Iceberg DeleteFilter on it. In VRBs we can utilize the selected array to mark rows as selected (not deleted), so essentially we're going to implement the markRowDeleted method.
=> HIVE-26697: Create vectorized Hive DeleteFilter for Iceberg tables

jdbc/src/java/org/apache/hive/jdbc/HiveConnection.java, jdbc/src/java/org/apache/hive/jdbc/Utils.java
Hive JDBC client validates the host name by its canonical name by default. This behaviour leads to `SSLHandshakeExcpetion` when trying to connect using alias name with Kerberos authentication. To solve this issue a new connection property is introduced to be able disabling canonical host name check: `enableCanonicalHostnameCheck` having default value `true`.
When the property is not given in connection string (or its value is true) then the original behaviour is applied i.e. checking canonical host name.
It is not possible to create SSL connection with Kerberos authentication when the server certificate is not issued to the canonical host name but to an alternative domain name.
See details about the exception and steps for reproducing in the …
=> HIVE-26723: Configurable canonical name checking.

standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/security/TestTokenStoreDelegationTokenSecretManager.java
Added a test for delegation token renewal that was fixed as part of HIVE-22033
For future regression tests
No
Unit test added tests successfully
=> HIVE-26522: Added test for HIVE-22033 regarding delegation token renewal

standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/security/TokenStoreDelegationTokenSecretManager.java, standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/security/TestTokenStoreDelegationTokenSecretManager.java
Backport of HIVE-22033 and HIVE-26522 to branch-3.1
To support delegation token renewal in 3.1 release
No
=> [WIP] HIVE-26522: Backport of HIVE-22033 and HIVE-26522 to branch-3.1

metastore/src/test/org/apache/hadoop/hive/metastore/TestTokenStoreDelegationTokenSecretManager.java, shims/common/src/main/java/org/apache/hadoop/hive/thrift/TokenStoreDelegationTokenSecretManager.java
Backport of HIVE-22033 and HIVE-26522 to branch-2.3
To support delegation token renewal in 2.3 release
No
=> HIVE-26522: Backport of HIVE-22033 and HIVE-26522 to branch-2.3

ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/test/queries/clientpositive/authorization_nested_views.q, ql/src/test/results/clientpositive/llap/authorization_nested_views.q.out
Fix the resolution for inner Views to avoid permission checks for inner views
Query fails due to Auth error, even if they have permission for the view being queried
Yes, The queries work fine, if they have permission on the view being queried, irrespective of, if it was created using With clause
Added a UT
=> HIVE-26736: Authorization failure for nested Views having WITH clause.

common/src/java/org/apache/hadoop/hive/conf/Constants.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/queries/positive/ctas_iceberg_partitioned_orc.q, iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_partitioned_orc.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/plan/PartitionDesc.java, ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java, ql/src/java/org/apache/hadoop/hive/ql/plan/TableDesc.java
* Pass a flag to jobConfig to indicate if we are in an explain command and do not create Iceberg tables in case of explain ctas.
* Add the newly created table path to the ctas property and use this value when overlaying jobProperties in IcebergStorageHandler
Explain command should not make changes in the catalog. 
No.
```
mvn test -Dtest.output.overwrite -Dtest=TestIcebergCliDriver -Dqfile=ctas_iceberg_partitioned_orc.q -pl itests/qtest-iceberg -Piceberg -Pitests
```
=> HIVE-26628: Iceberg table is created when running explain ctas command

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/HiveIcebergDeleteWriter.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/writer/WriterBuilder.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/writer/HiveIcebergWriterTestBase.java, iceberg/iceberg-handler/src/test/queries/positive/iceberg_v2_deletes.q, iceberg/iceberg-handler/src/test/results/positive/iceberg_v2_deletes.q.out, iceberg/iceberg-handler/src/test/results/positive/llap/iceberg_v2_deletes.q.out
Allow writing actual row data in delete file as optional
To avoid cost of reading/writing actual row data while reading/write delete files
No
Added UT to ensure functionality. Tested File Contents and operations in actual env. 
**Output: (With Config Enabled)**
```
[root@ayushsaxena-2 ~]# sudo -u hive hive --orcfiledump -d hdfs://cluster:8020/warehouse/tablespace/external/hive/ice02/data/00000-0-delete-hive_20221112171847_aba7a24a-68ec-46fa-bed4-3588f4a92e74-job_16680670596081_0052-1-00001.orc
Processing data file hdfs://cluster:8020/warehouse/tablespace/external/hive/ice02/data/00000-0-delete-hive_20221112171847_aba7a24a-68ec-46fa-bed4-3588f4a92e74-job_16680670596081_0052-1-00001.orc [length: 1075]
{"file_path":"hdfs:\/\/cluster:8020\/warehouse\/tablespace\/external\/hive\/ice02\/data\/00 …
```
=> HIVE-26734: Iceberg: Add an option to allow positional delete files without actual row data.

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveValues.java
Add missing `HiveRelNode` interface implementation to `HiveValues`
All Hive operators must implement it to ensure Hive calling convetion.
No
Existing ptests.
=> HIVE-26524: Use Calcite to remove sections of a query plan known never produces rows - ADDENDUM

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/StatsUpdater.java
HIVE-20172 solved an issue where HMS was running the compaction worker, and StatUpdater thus ran in the very same JVM causing kerberos issues while connecting to "itself". The fix was to update HMS URI setting to empty string. This way HMS wouldn't have to go around itself to connect to itself :)
But.. this is not correct anymore, as Hive doesn't support running the compaction worker on HMS side anymore, but only on HS2. So in any case this code part ends up executed in HS2, where an embedded HMS will be created due to this empty string URIs config, and eventually will open connections directly to HMS backend DB.
We need to remove this setting as it was fixing something that is not relevant anymore.
=> HIVE-26740: HS2 makes direct connections to HMS backend DB due to Compaction/StatsUpdater

hplsql/src/main/java/org/apache/hive/hplsql/Var.java, itests/hive-unit/src/test/java/org/apache/hive/beeline/TestBeeLineWithArgs.java, itests/hive-unit/src/test/java/org/apache/hive/beeline/TestHplSqlViaBeeLine.java, service/src/java/org/apache/hive/service/cli/operation/hplsql/HplSqlQueryExecutor.java
Decimal or null values coming from Hive service side are not handled properly in HPL.
When we're using beeline in HPL mode then the results of queries such as SELECT CAST are returned in RowSet objects directly from HS2 code. This is due to HplSqlQueryExecutor expecting RowSet type in OperationRowResult. For this RowSet interface, a ColumnBasedSet class brings the imlementation which holds a ColumnBuffer list to hold the result data.
The internal representation however cannot hold BigDecimal values, as seen here: https://github.com/apache/hive/blob/master/serde/src/java/org/apache/hadoop/hive/serde2/thrift/ColumnBuffer.java#L396 so while the SELECT CAST query will produce a HiveBigDecimal instance, it will be converted to String at …
=> HIVE-26745: HPL unable to handle Decimal or null values in hplsql mode

common/src/java/org/apache/hadoop/hive/conf/Constants.java
=> HIVE-26746: Request tracking: change to X-Request-ID header

llap-server/src/java/org/apache/hadoop/hive/llap/shufflehandler/ShuffleHandler.java
Adding LoggingHandler in ShuffleHandler pipeline for better debuggability.
For corner case debugging, it will be helpful to understand when netty processed OPEN/BOUND/CLOSE/RECEIVED/CONNECTED events along with payload details.
Adding "LoggingHandler" in ChannelPipeline mode to help in debugging.
No.
Pre-commit testing.
=> HIVE-23754: LLAP, Add LoggingHandler in ShuffleHandler pipeline for better debuggability

pom.xml, standalone-metastore/metastore-common/pom.xml, standalone-metastore/metastore-common/src/main/protobuf/org/apache/hadoop/hive/metastore/hive_metastore.proto, standalone-metastore/metastore-common/src/main/protobuf/org/apache/hadoop/hive/metastore/metastore.proto, standalone-metastore/pom.xml, standalone-metastore/spotbugs/spotbugs-exclude.xml
This is a rebased version of https://github.com/apache/hive/pull/3534, 
* Added a proto3 syntax Hive Metastore proto file that was based off the existing `hive_metastore.thrift` file.
* It generally tries to follow grpc best practices, so there are some slight variations on thrift, for example enums, response types of response specific empty protos, snake_case.
* Guava is updated to version 22, which is required for proto3/grpc for compiling the protos.
As this is "new" API, the new grpc API doesn’t include the same method with different signature, i.e. get_databases(string db_id) is usurped by get_databases(GetDatabasesRequest request).
The proto file is necessary because in order to have native gRPC support in Hive Metastore, there needs to be gRPC equivalents of all the preexisting …
=> HIVE-26484: Add proto3 hivemetastore.proto

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergV2.java, iceberg/iceberg-handler/src/test/queries/positive/ctas_iceberg_partitioned_orc.q, iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_partitioned_orc.q.out, ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/CalcitePlanner.java, ql/src/java/org/apache/hadoop/hive/ql/parse/MergeSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/RewriteSemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/UpdateDeleteSemanticAnalyzer.java
Read queries shouldn't fail for tables with copy-on-write mode
Yes, Read queries with copy-on-write will be successful.
Added UT.
=> HIVE-26786: Iceberg: Read queries with copy-on-write failing.

common/src/java/org/apache/hadoop/hive/conf/Constants.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/Catalogs.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergMetaHook.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergSerDe.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveTableUtil.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergCTAS.java, iceberg/iceberg-handler/src/test/queries/positive/ctas_iceberg_orc.q, iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_orc.q.out, iceberg/iceberg-handler/src/test/results/positive/ctas_iceberg_partitioned_orc.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/table/create/CreateTableDesc.java, ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/HiveStorageHandler.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java, ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java, ql/src/java/org/apache/hadoop/hive/ql/plan/TableDesc.java
Refactor the way ctas is executed:
* Do not create the table in `HiveIcebergSerDe` since it is also created at compile time.
* Add a DDLTask before the `TezTask` to create the Iceberg table.
* Collect the properties added to jobconfig from the Serde object and location and fileio from HiveCatalog. Location can be calculated at compile time using `SemanticAnalyzer.getCtasOrCMVLocation`
* Persist the new table metaobject to a temp file when committing the table creation.
* Read back the table metaobject anytime it is required from the TezTask and the MoveTask.
See jira.
No
```
mvn test -Dtest.output.overwrite -Dtest=TestIcebergCliDriver -Dqfile=ctas_iceberg_partitioned_orc.q -pl itests/qtest-iceberg -Piceberg -Pitests -Drat.skip
```
=> HIVE-26771: Use DDLTask to created Iceberg table when running ctas statement

pom.xml, standalone-metastore/pom.xml
The junit-jupiter-api dependency coming from curator-test comes in conflict with the one used by the surefire plugin and the one used in Hive causing many problems with the discovery of tests in many modules.
Excluding the junit-jupiter-api dependency from curator remedies the problem for now.
No
```
cd itests/hive-unit && mvn test
mvn test -Dtest=StartMiniHS2Cluster
```
=> HIVE-26796: Tests in modules dependent on curator-test are skipped silently

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java
This PR assumes that if ConfVars.USE_CUSTOM_RDBMS is set that we will expect DbType.CUSTOM, therefore, it will not use DbType.UNDEFINED to compare to the database type set in theDatabaseProduct.
getDbType(productName) returns DbType.UNDEFINED
But when theDatabaseProduct == null and ConfVars.USE_CUSTOM_RDBMS is set  theDatabaseProduct.dbType is initialized to DbType.CUSTOM.  DbType.UNDEFINED will never equal  DbType.CUSTOM
No
I compile the code, added a subclass of DatabaseProduct for Db2 and installed Hive Metastore using a backend Db2 database.
=> HIVE-26767: Fix HIVE-24120 to work for custom databases

cli/src/java/org/apache/hadoop/hive/cli/CliDriver.java, ql/src/java/org/apache/hadoop/hive/ql/exec/tez/TezTask.java, ql/src/java/org/apache/hadoop/hive/ql/session/SessionState.java, service/src/java/org/apache/hive/service/cli/operation/Operation.java, service/src/java/org/apache/hive/service/cli/operation/SQLOperation.java, service/src/java/org/apache/hive/service/cli/operation/hplsql/HplSqlOperation.java, shims/common/src/main/java/org/apache/hadoop/hive/shims/HadoopShims.java
Add UserName in CallerContext for HDFS Audit logs to pick.
With Impersonation turned off, every call shows from Hive User, So, to allow tracking the actual user.
Nopes,
Tried a Query in Actual Cluster.
=> HIVE-26789: Add UserName in CallerContext for queries.

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactionQueryBuilder.java
Query-based compaction fails on tables having columns with keywords(i.e. row in this case) for columns. The compaction fails while running insert into statement as it does not quote the columns correctly.
This fixes the current bug with Query based compaction
NO
Currently tested manually, and added a UT to TestCrudCompactorOnTez#testCompactionShouldNotFailOnKeywordField
=> HIVE-26801: Query based compaction fails on tables having columns with keywords(i.e. row in this case)

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, ql/src/java/org/apache/hadoop/hive/ql/exec/FileSinkOperator.java, ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java, ql/src/java/org/apache/hadoop/hive/ql/exec/OrcFileMergeOperator.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/GenMapRedUtils.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java
1. add a hive configuration hive.use.scratchdir.for.staging
2. for native table, no-mm, no-direct-insert, no-acid, change dynamic partition staging directory layout from
<dest_path>/<static_partition>/<staging_dir>/<dynamic_partition>
to 
<dest_path>/<staging_dir>/<static_partition>/<dynamic_partition>
3. when hive.use.scratchdir.for.staging=true, FileSinkOperator's dirName, DynamicContext's sourcePath change from
<dest_path>/{hive.exec.stagingdir}
to
<hive.exec.scratchdir>
for example for query 
insert into/overwrite table partition(year=2001, season) select...
before the change, the FileSinkOperator conf has
<table_path>/year=2001/.staging_dir/season=xxx
after the change, it has
<table_path>/.staging_dir/year=2001/season=xxx
This change allow to swap <table_path> with another path such …
=> HIVE-26758: Allow use scratchdir for staging final job

ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestStringableList.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/utils/TestStringableMap.java
Moved unit test for StringableList, StringableMap to they own dedicated test classes instead.
=> HIVE-26392 Move StringableMap tests into a dedicated test class

ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/reloperators/HiveValues.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/calcite/translator/PlanModifierForASTConv.java, ql/src/test/queries/clientpositive/empty_result.q, ql/src/test/results/clientpositive/llap/empty_result.q.out, ql/src/test/results/clientpositive/llap/empty_result_outerjoin.q.out
Set the column names int the root `HiveValues` schema in the logical plan to the ones coming from the result schema.
When logical plan is generated the column names in the root operator schema are generated names and does not reflect to the names and aliases specified in the main query's project schema. These are set after logical plan generation but this step is missing when root operator is `HiveValues`.
Yes. If
```
set hive.cli.print.header=true;
```
the printed column names may changed.
```
mvn test -Dtest.output.overwrite -DskipSparkTests -Dtest=TestMiniLlapLocalCliDriver -Dqfile=empty_result.q -pl itests/qtest -Pitests
```
=> HIVE-26817: Set column names in result schema when plan has Values root

iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc.q, iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc2.q, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc2.q.out, itests/util/src/main/java/org/apache/hadoop/hive/ql/QTestUtil.java, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/create/CreateMaterializedViewDesc.java, ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java, ql/src/java/org/apache/hadoop/hive/ql/parse/SemanticAnalyzer.java, ql/src/java/org/apache/hadoop/hive/ql/parse/TaskCompiler.java, ql/src/java/org/apache/hadoop/hive/ql/plan/PlanUtils.java, standalone-metastore/metastore-common/src/gen/thrift/gen-javabean/org/apache/hadoop/hive/metastore/api/hive_metastoreConstants.java
* Treat creation materialized view as ctas since technically they are similar. MV creation has some extra steps like persisting creation metadata and the view location should not be translated by metastore translator
* If storage handler is specified: pass the generated view location to storage handler at compile time and at commit in move task
* Insert MV create task to create the view and update MV task to enable the view usage for automatic query rewrites in TaskCompiler when direc insert is enabled by the storage handler.
Improve MV functionality by enabling iceberg storage of the view data.
Iceberg storage format my appear in outputs of sql statements like `DESCRIBE FORMATTED` and `EXPLAIN CREATE/ALTER MATERIALIZED VIEW`
```
mvn test -Dtest.output.overwrite …
```
=> HIVE-26578: Enable Iceberg storage format for materialized views

ql/src/java/org/apache/hadoop/hive/ql/exec/FetchTask.java, ql/src/java/org/apache/hadoop/hive/ql/optimizer/SimpleFetchOptimizer.java, ql/src/java/org/apache/hadoop/hive/ql/plan/FetchWork.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands.java
Currently, fetch task is caching results irrespective of whether fetch task conversion is enabled or not. This can lead to situation wherein the queries have fetch task conversion disabled but the results are cached. Fetch task must be aware if it is used for fetch task conversion or not. In the latter case, caching should be disabled.
Fetch task conversion and fetch task caching must go hand in hand.
No
Unit tests
=> HIVE-26821: Fetch task caching should only depend on fetch task conversion

ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/HiveMetaStoreAuthorizer.java, ql/src/java/org/apache/hadoop/hive/ql/security/authorization/plugin/metastore/filtercontext/DataConnectorFilterContext.java, standalone-metastore/metastore-server/src/test/java/org/apache/hadoop/hive/metastore/TestFilterHooks.java
HMS server-side filters out results of 'show connectors' based on authorization, 
This is the follow-up task of https://issues.apache.org/jira/browse/HIVE-26248 .
No
1. Unit test;
2. Integration test using our customized ranger-hive plugin which has added connector auth check , and i will create PR to Apache Ranger to add connector auth in future.
=> HIVE-26247: Filter out results 'show connectors' on HMS server-side

itests/hive-unit/src/test/java/org/apache/hive/service/cli/operation/TestOperationLoggingLayout.java
Backport of HIVE-25795: [addendum] Unit test failures from upgrade to log4j 2.16.0. This would resolve test failures from itests/hive-unit/src/test/java/org/apache/hive/service/cli/operation/TestOperationLoggingLayout.java and ensure we are closer to branch-3 clean build. To be compared with http://ci.hive.apache.org/blue/organizations/jenkins/hive-precommit/detail/PR-3850/1/tests/ for this test success.
=> HIVE-26866 : Backport of HIVE-25795

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/TestAcidOnTez.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCompactor.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/StatsUpdater.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands2.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnCommands3.java, ql/src/test/org/apache/hadoop/hive/ql/TestTxnLoadData.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestWorker.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionInfo.java
Update stats of table/partition using noscan operation when stats autogather is enabled
Currently, statistics are always updated for major compaction and never updated for minor compaction since minor compaction performs little updates on the statistics (such as number of files in table/partition & total size of the table/partition). It is better to utilize NOSCAN operation  for both these compaction since NOSCAN operations performs faster update of statistics and updates the relevant fields such as number of files & total sizes of the table/partitions if stats autogather is enabled. If autostats gather is disabled then go for full update of statistics.
No
Unit tests
=> HIVE-26788: Update stats of table/partition using noscan operation when stats autogather is enabled

ql/src/test/results/clientpositive/llap/temp_table_partition_timestamp.q.out, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/utils/MetaStoreUtils.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/DatabaseProduct.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/ExpressionTree.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/parser/Filter.g
Change the filter parser to process the new timestamp data type filter generated by CBO to be pushed down the filter predicate to the metastore
In my testing setup of table having 10k partitions in the table. When we do a select query on one of the partitions without the change it was 300 ms and after the change it was 14 ms.
No
1. Manual testing
2. Existing automated tests
=> HIVE-26787: Pushdown Timestamp data type to metastore via directsql/JDO

common/src/java/org/apache/hadoop/hive/common/FileUtils.java, common/src/test/org/apache/hadoop/hive/common/TestFileUtils.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java, ql/src/java/org/apache/hadoop/hive/ql/util/HiveStrictManagedMigration.java
When trying to figure out whether filesystems are equal, in case of ozone file systems, check if they belong to same volume bucket
LOAD fails if the table location and file are different ozone buckets.
LOAD from different ozone bucket works now.
In Actual Env.
=> HIVE-26848: Ozone: LOAD data fails in case of move across buckets.

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorOnTezTest.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestMmCompactorOnTez.java, ql/src/test/org/apache/hadoop/hive/ql/hooks/TestHiveProtoLoggingHook.java
The 3 tests in TestCrudCompactorOnTez which use the ProtoLoggingHook run at different times. Unfortunately, the 3 tests are run at the following times as described in the logs - 
Test 1 - 
`INFO [main] compactor.TestCrudCompactorOnTez: Current time: 2022-12-15T23:57:44 `
Test 2 - 
`INFO [main] compactor.TestCrudCompactorOnTez: Current time: 2022-12-16T00:00:32 `
Test 3 - 
`INFO [main] compactor.TestCrudCompactorOnTez: Current time: 2022-12-16T00:04:12 `
As we can see, the tests are run on 2 different dates. Therefore, HiveProtoLoggingHook generates a unique event logs for every unique date. This is the behaviour of HiveProtoLoggingHook.
https://github.com/apache/hive/blob/master/ql/src/java/org/apache/hadoop/hive/ql/hooks/HiveProtoLoggingHook.java#L296-L310
However the expectation from …
=> HIVE-26871: TestCrudCompactorOnTez is flaky after HIVE-26479

iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/vector/TestHiveIcebergVectorization.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java
Fix Row Number calculation in Parquet Vectorized V2 reads.
Vectorized V2 reads with multiple blocks and some getting filtered leads to wrong positions being calculated, messing up with the PositionalDeleteFilter
Yes, Correct Results with Parquet V2 reads
On Local Env with subset of data from the actual Env. & UT
=> HIVE-26884: Iceberg: V2 Vectorization returns wrong results with deletes.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveBatchIterator.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/vector/TestHiveIcebergVectorization.java
Fix NPE while reading Iceberg V2 Parquet V2 table in case of empty batches.
NPE while reading Parquet V2 table
Yep, Query passes without NPE
UT, On top on HIVE-26884 (Would require a rebase for the UT to give correct result, but won’t give NPE)
=> HIVE-26885: Iceberg: Parquet Vectorized V2 reads fails with NPE.

common/src/java/org/apache/hadoop/hive/conf/HiveConf.java, itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestRestrictedList.java, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/datasource/DataSourceProviderFactory.java, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/datasource/DbCPDataSourceProvider.java, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/datasource/HikariCPDataSourceProvider.java, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/txn/TxnHandler.java, standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/datasource/TestDataSourceProviderFactory.java
Backport [HIVE-17317](https://issues.apache.org/jira/browse/HIVE-17317). This patch introduced support for DBCP as a connection pool for the metastore database. It also corrected HIkariCP configuration by changing a pooling type constant from `"hikari"` to `"hikaricp"`.
As compared to the original HIVE-17317 patch, here are the differences in this backport:
* Changes in `ObjectStore` are no longer required, because the relevant logic was later refactored into `PersistenceManagerProvider` on branch-3.
* Similarly, there are no changes required in `BoneCPDataSourceProvider` on branch-3.
* `DataSourceProviderFactory` has minor cosmetic differences on how the `FACTORIES` list is defined, and some other changes are no longer required.
* `HikariCPDataSourceProvider` only needs the change of the …
=> HIVE-26702: Backport HIVE-17317 (DBCP and HikariCP property configuration support) to 3.2.0.

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/HiveIcebergStorageHandler.java, iceberg/iceberg-handler/src/test/java/org/apache/iceberg/mr/hive/TestHiveIcebergInserts.java
Allow IOW on empty iceberg tables.
Helps with compactions
Yes, IOW can be performed on empty tables.
UT
=> HIVE-26868: Iceberg: Allow IOW on empty table with Partition Evolution.

ql/src/java/org/apache/hadoop/hive/ql/exec/MoveTask.java, ql/src/java/org/apache/hadoop/hive/ql/metadata/Hive.java
Transforming Hive::moveAcidFiles for cloud storage to work in parallel instead of sequentially.
Currently this function ends up transferring DELTA, DELETE_DELTA, BASE prefixes sequentially from staging to final location. This causes delays even with simple updates statements, which updates smaller number of records in cloud storage. The proposed change fixes that.
No.
Hive pre-commit testing.
=> HIVE-23559: Optimise Hive::moveAcidFiles for cloud storage.

beeline/src/java/org/apache/hive/beeline/schematool/HiveSchemaTool.java
We only commit when all the changes in schema upgrade is successful.
Otherwise, we do not commit.
Currently, as schematool applies schema changes during an upgrade, each change is autocommitted. So if it fails after applying a few changes from an upgrade file, those changes remain in the schema. So re-running the schematool fails at the first line because that change already exists.
Instead, we should create a transactional boundary between each upgrade file, aka commit only after all the changes in an upgrade file are successful.
No.
Maven build and unit test.
=> HIVE-25707: SchemaTool may leave the metastore in-between upgrade steps

itests/hive-unit/src/test/java/org/apache/hive/jdbc/TestSSL.java
This was done as part of [HIVE-22621](https://issues.apache.org/jira/browse/HIVE-22621) on oss/master. This test also fails with the same error in Hive-3.1.3 release. So we can safely ignore this test from branch-3. Please find the JIRA link : https://issues.apache.org/jira/browse/HIVE-26890
=> HIVE-26890 : Disable TestSSL#testConnectionWrongCertCN (Done as part of HIVE-22621 in master)

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/HMSHandler.java
In our production environment, we found that the value of the metric "active_calls_alter_partition" was negative. This is very confusing.
After checking the HMSHandler.class, we found that the method alter_partitions_with_environment_context called()
startTableFunction("alter_partitions", catName, db_name, tbl_name);
...
endFunction("alter_partition", oldParts != null, ex, tbl_name);
So the metric "active_calls_alter_partition" will be decremented by one after the "alter_partitions" function execution ends, causing the value become a negative number
=> HIVE-26065: fix incorrect metric active_calls_alter_partitions and active_calls_alter_partition

hcatalog/core/src/test/java/org/apache/hive/hcatalog/cli/TestPermsGrp.java, hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatMultiOutputFormat.java, hcatalog/core/src/test/java/org/apache/hive/hcatalog/mapreduce/TestHCatPartitionPublish.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/parse/WarehouseInstance.java, itests/util/src/main/java/org/apache/hive/jdbc/miniHS2/MiniHS2.java, standalone-metastore/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java, standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/MetaStoreTestUtils.java, standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/TestHiveMetaStore.java, standalone-metastore/src/test/java/org/apache/hadoop/hive/metastore/TestRemoteHiveMetaStore.java
HIVE-26869 : Backport of HIVE-19104: When test MetaStore is started with retry the instances should be independent
Change-Id: I4955b9dd2c5b82da9510ae3a2342b8d96ab86781
=> HIVE-26869 : Backport of HIVE-19104: Fix TestHS2ImpersonationWithRemoteMS.testImpersonation

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java, ql/src/test/org/apache/hadoop/hive/ql/txn/compactor/TestInitiator.java, standalone-metastore/metastore-common/src/main/java/org/apache/hadoop/hive/metastore/conf/MetastoreConf.java
REBALANCE type compaction now can be scheduled by the initiator
Without initiator, REBALANCE compaction would only be issued by users. To make sure read performance does not degrade over time, tables must be checked automatically too.
No
Manually and through unit tests
=> HIVE-26718: Enable initiator to schedule rebalancing compactions

iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/HiveVectorizedReader.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/mr/hive/vector/ParquetSchemaFieldNameVisitor.java, iceberg/iceberg-handler/src/main/java/org/apache/iceberg/parquet/ParquetFooterInputFromCache.java, iceberg/iceberg-shading/pom.xml, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/ParquetRecordReaderBase.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/VectorizedParquetInputFormat.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/read/ParquetRecordReaderWrapper.java, ql/src/java/org/apache/hadoop/hive/ql/io/parquet/vector/VectorizedParquetRecordReader.java
Reuse ParquetMetadata
Performance Benifits.
No.
Jenkins Build
=> HIVE-26913: HiveVectorizedReader::parquetRecordReader should reuse footer information.

standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/MetaStoreDirectSql.java
1. Fixed cast exception in `dropStorageDescriptors` method while iterating over result fetched for `SKEWED_VALUES.STRING_LIST_ID_EID`.
2. Fixed cast exception in `dropDanglingColumnDescriptors` method while iterating over result fetched for `SDS.CD_ID`(this exception is observed with oracle db).
When a partitioned table with skewed columns is dropped, appropriate entries in HMS tables i.e., SDS, SERDES, SERDE_PARAMS, SKEWED_COL_NAMES, SKEWED_COL_VALUE_LOC_MAP, SKEWED_VALUES are not deleted due to cast exception. Issue link:[HIVE-26860](https://issues.apache.org/jira/browse/HIVE-26860). These entries will remain in the backing datastore forever.
**Exception stack:**
```
MetaStoreDirectSql.java:2690) at org.apache.hadoop.hive.metastore.MetaStoreDirectSql.access$2000(MetaStoreDirectSql.java:1 …
```
=> HIVE-26860: Entries in HMS tables are not deleted upon drop partition table with skewed columns

itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorTestUtil.java, itests/hive-unit/src/test/java/org/apache/hadoop/hive/ql/txn/compactor/TestCrudCompactorOnTez.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/CompactorFactory.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Initiator.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/StatsUpdater.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/Worker.java, standalone-metastore/metastore-server/src/main/java/org/apache/hadoop/hive/metastore/txn/CompactionTxnHandler.java
For rebalance compaction requests on inert-only tables, a MAJOR 
compaction will run as a fallback. For details see: https://issues.apache.org/jira/browse/HIVE-26674 (limitations section)
To allow the users to request rebalance compactions on insert-only tables.
No.
Manually, and through unit tests
=> HIVE-26717: Query based Rebalance compaction on insert-only tables

iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc.q, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc.q.out, ql/src/java/org/apache/hadoop/hive/ql/ddl/view/materialized/alter/rewrite/AlterMaterializedViewRewriteAnalyzer.java
Check whether non-native source tables of a materialized view supports snapshots when enabling the mv for automatic query rewrites.
Allow such mvs to be used in automatic query rewrites.
Yes. Enabling for rewrite is successful.
```
mvn test -Dtest.output.overwrite -Dtest=TestIcebergCliDriver -Dqfile=mv_iceberg_orc.q -pl itests/qtest-iceberg -Piceberg -Pitests -Drat.skip
```
=> HIVE-26924: Alter materialized view enable rewrite throws SemanticException for source iceberg table

iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc2.q, iceberg/iceberg-handler/src/test/queries/positive/mv_iceberg_orc3.q, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc2.q.out, iceberg/iceberg-handler/src/test/results/positive/mv_iceberg_orc3.q.out, ql/src/java/org/apache/hadoop/hive/ql/io/AcidUtils.java, ql/src/test/org/apache/hadoop/hive/ql/metadata/StorageHandlerMock.java
Set the lock type based in the table's storage handler in case of non native tables when creating LockComponent's for output tables.
Iceberg table writes does not require exclusive lock since Iceberg handles the concurrency. However locking is necessary when committing the Iceberg change and updating the metadata file at Hive side. Originally for insert overwrite an exclusive lock was acquired in the beginning of the transaction to the target table and a second write lock was requested for the Iceberg commit in the same transaction but this second one was never been acquired because the two lock request caused a deadlock.
No.
```
mvn test -Dtest.output.overwrite -Dtest=TestIcebergCliDriver -Dqfile=mv_iceberg_orc2.q -pl itests/qtest-iceberg -Piceberg -Pitests -Drat.skip
```
=> HIVE-26922: Deadlock when rebuilding Materialized view stored by Iceberg

ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MinorQueryCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMajorQueryCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/MmMinorQueryCompactor.java, ql/src/java/org/apache/hadoop/hive/ql/txn/compactor/QueryCompactor.java
commitCompaction of query-based compactors just do some cleanup on tmp table dirs. It could fail if the tmp table dirs is already removed. See an example in https://issues.apache.org/jira/browse/IMPALA-11756
It doesn't make sense to fail the compaction due to this.
This PR catches the FileNotFoundException in commitCompaction() when the tmp table dir doesn't exist. Ignore and skip removing the dir, and don't fail the compaction.
The compaction is already finished so don't need to fail it if the tmp dirs are already cleaned up.
No
Run existing tests.
=> HIVE-26904: commitCompaction of query-based compaction should not fail when tmp table dirs are already cleaned up
